### ISSUE TITLE
Pasting from Hansontable to Excel - spaces become unicode \xA0 (non-breaking space) instead of \x20 (space)

### ISSUE THREAD

**Issue by harveycubewise** [handsontable/handsontable#10017] opened 2022-10-13 09:38 UTC
### Description
When text is copied from a handsontable, the clipboard is loaded with both html and plain text representations of the data. When pasted to Excel, by default it will attempt to paste the html version.

However, handsontable replaces all unicode spaces (`\x20`) with `&nbsp;` in the html representation. This makes sense when generating html for the browser, but for the clipboard, it results in Excel converting spaces back to unicode `\xA0`.

This results in the test original input in the handsontable cell/s not matching the text in Excel, as (in javascript, for example) 'ABC[0x00A0]DEF' != 'ABC[0x0020]DEF'.

### Steps to reproduce
1. Open provided JSFiddle
2. Select all rows and paste into a new Excel sheet in column B
3. In column A, manually type ['value row 0', 'value row 1'... 'value row 4'] across 5 rows
4. In column C1, enter the formula '=A1=B1'
5. Copy the formula in C1 down to row 5.
6. Observe that FALSE is returned in all cases.

![image](https://user-images.githubusercontent.com/95455748/195556131-b37bec58-4f40-48be-b3a2-1a652433d577.png)

### Demo
[https://jsfiddle.net/w7ep5c28/1/](https://jsfiddle.net/w7ep5c28/1/)

### Your environment
* Handsontable version: 11.1.0
* Browser name and version: Brave v1.44.108 Chromium: 106.0.5249.103 (Official Build) (64-bit)
* Operating system: Windows 11 Pro 10.0.22000 Build 22000

### Suggested fix

In the function `_dataToHTML(input)` replace line:

`var parsedCellData = (0, _mixed.isEmpty)(cellData) ? '' : cellData.toString().replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/(<br(\s*|\/)>(\r\n|\n)?|\r\n|\n)/g, '<br>\r\n').replace(/\x20/gi, '&nbsp;').replace(/\t/gi, '&#9;');`

with

`var parsedCellData = (0, _mixed.isEmpty)(cellData) ? '' : cellData.toString().replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/(<br(\s*|\/)>(\r\n|\n)?|\r\n|\n)/g, '<br>\r\n').replace(/\t/gi, '&#9;');`

More detail in the forum post here: https://forum.handsontable.com/t/copy-values-with-spaces-from-handsontable-to-excel/6213/4?u=hwithington

**Comment by adrianszymanski89** [comment] 2022-10-13 09:40
Hi @harveycubewise 

Thank you again for this suggestion. We definitely should consider improving this feature.

**Comment by AMBudnik** [comment] 2022-11-02 13:39
Updated forum topic https://forum.handsontable.com/t/gh-10017-copy-values-with-spaces-from-handsontable-to-excel/6213

**Comment by aninde** [comment] 2023-05-16 12:15
Hi @harveycubewise 
I have been actively testing the upcoming v12.4.0, which specifically addresses the problem you encountered. The issue has been successfully resolved in the upcoming v12.4.0. Here's the [updated demo](https://jsfiddle.net/aninde/kf1rmajb/).

Although I was unable to reproduce your specific usage scenario on macOS, I was able to identify and replicate the problem on Windows.

**Comment by harveycubewise** [comment] 2023-05-16 23:49
> Hi @harveycubewise I have been actively testing the upcoming v12.4.0, which specifically addresses the problem you encountered. The issue has been successfully resolved in the upcoming v12.4.0. Here's the [updated demo](https://jsfiddle.net/aninde/kf1rmajb/).

Excellent, thanks @aninde. I repeated my steps above and it does works as expected now! 

I will be very keen to update our code-base once the new release is available.

**Comment by AMBudnik** [comment] 2023-05-23 11:26
Hi @harveycubewise Just a quick update. We just officially released Handsontable v12.4.0 where this issue is fixed.

**Closed by AMBudnik** 2023-05-23 11:26 UTC
Labels: enhancement, Copy-paste, Reported
