### ISSUE TITLE
manualMoveRow don't work after loadData

### ISSUE THREAD

**Issue by minhtranite** [handsontable/handsontable#3568] opened 2016-06-09 05:01 UTC
Demo https://jsfiddle.net/vn38minhtran/tkLc7ozg/22/

**Comment by AMBudnik** [comment] 2016-06-09 08:28
Hi @vn38minhtran 
I guess that there's something else blocking your data switch.
I made a simplified example http://jsfiddle.net/wpws3bd5/ which works as expected.

**Comment by vn38minhtran** [comment] 2016-06-09 09:34
@AMBudnik 
I fork your example to [new example](http://jsfiddle.net/vn38minhtran/fbr6ecwe/6/) with some modify. You can see after you move row 3 to top and click button, row 3 still ontop (first row). In my case, i want after load data Handsontable will render correctly the order in the data array.

**Comment by AMBudnik** [comment] 2016-06-09 09:42
Great example @vn38minhtran 
I tried other rows also and you're right it skips a row.

**Comment by AMBudnik** [comment] 2017-01-23 11:06
Same issue with 0.30.1, demo: http://jsfiddle.net/handsoncode/9py00tjz/

**Comment by AMBudnik** [comment] 2017-04-04 12:24
still replicable in v0.31.2

**Comment by superpig** [comment] 2018-02-01 12:04
I have the same prome, does this problem have any solution ?

**Comment by AMBudnik** [comment] 2018-02-01 12:15
Sorry, I have tried to find a workaround but without any success

**Comment by AMBudnik** [comment] 2018-04-24 11:37
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment] 2018-09-07 08:18
It still does not change the data. Tested with version [`5.0.1`](http://jsfiddle.net/handsoncode/9py00tjz/)

![gif](https://user-images.githubusercontent.com/10757813/45204321-22d86d80-b27f-11e8-88cb-d83dde68adf3.gif)

The row that we've moved stays at the top untouched by the data changes.

A situation is a bit different when I [add one more row to make then even](http://jsfiddle.net/txag68jv/).

![2gif](https://user-images.githubusercontent.com/10757813/45205222-d0e51700-b281-11e8-9f9a-796ac307c8b6.gif)

The data loads with the same order that we set it. We can check it here http://jsfiddle.net/m4soL75r/
The data changes (now we do not revert the one that we already had). Instead I am loading a new table with different data and data structure (object then array). 

![3gif](https://user-images.githubusercontent.com/10757813/45205727-46051c00-b283-11e8-89c2-8f47952f6556.gif)

What's also odd is the delay in data loading. We get only a half of the results loaded on the button click, A second part appears after couple of miliseconds. We previously had only 4 columns and the 4 columns are blank at the beginning. 

After runing the `loadData` the `getData()` shows

![image](https://user-images.githubusercontent.com/10757813/45206554-8b2a4d80-b285-11e8-9795-a99b3081e5a5.png)

The `hot.getSettings().manualRowMove` after data is loaded returns only `true`.

**Comment by mismith** [comment] 2018-12-11 05:33
This bug still seems present, any chance there's a fix in the works?

**Comment by AMBudnik** [comment] 2018-12-11 08:03
Hey @mismith 

the issue is still opened but it hasn't been scheduled yet

**Comment by mismith** [comment] 2018-12-11 17:06
@AMBudnik gotcha. Seems like a great ticket given all the fiddles you've linked above! 🌮

**Comment by mismith** [comment] 2019-04-01 20:16
@AMBudnik Any progress lately?

**Comment by AMBudnik** [comment] 2019-04-02 08:36
Sorry, I do not have any information about scheduling this issue. Firstly I thought that it might get fixed with the new[ index mapper](https://github.com/handsontable/handsontable/issues/5112) but I had a discussion with our developer and it looks like those issues are not connected.

**Comment by justechn** [comment] 2019-04-11 17:47
We are currently looking into using Handsontable in our saas product and paying for a commercial license, but this bug is a deal breaker. I have sent an email requesting a pricing quote, but if this cannot be fixed soon we will be forced to go with another product.

**Comment by AMBudnik** [comment] 2019-04-15 08:04
Hey @justechn Can you send over an example with your implementation? In some cases, we can erase the mapper or turn off the plugin. If you do not wish to share the code here you can also send me an email at support@handsontable.com

**Comment by justechn** [comment] 2019-04-15 17:57
Our current implementation is old and convoluted and would be difficult to reproduce. We are planning a rewrite, but I need to know for sure that if we go with Handsontable that drag to sort will be fully working and we won't run into any weird behaviour.

**Comment by aninde** [comment] 2019-09-16 12:16
We are currently testing a new `Index mapper`, which was specially built to solve similar problems. 
I recommend observing information from the issue [#5751](https://github.com/handsontable/handsontable/issues/5751). Changes will be released soon.

New index mapper fixed ‘loadData’ after `manualMoveRow`, but now there is an additional error.
Unfortunately in version 8.0.0rc after loadData cannot move a column or row again.

**Demo**
version 8.0.0.rc http://jsfiddle.net/aninde/t12c68qy/

**Steps of reproduction:**

1. Move the third row at firs position.
2. Load data by pressing the button.
3. Move the fourth row at firs position.

**Actual result:**
When dragging the row, the place where it is to be pasted is marked gray. The size of the gray selection appears to be before loading data.
A changed row appears for a moment in the new position. Then it disappears and table renderers what has been uploaded in loadData.

**Expected result:**
manualRowMove/manualColumnMove should work after loadData

**Comment by aninde** [comment] 2019-09-17 09:34
Unfortunately, we need to reopen this topic due to the error described above. I changed the title of the issue.

**Comment by aninde** [comment] 2019-09-25 13:34
Similar bug, but related to columns was found by @AMBudnik in [#4480](https://github.com/handsontable/handsontable/issues/4480#issuecomment-535005113)

**Comment by wszymanski** [comment] 2019-09-26 10:40
Good case. There shouldn't be empty rows when `loadData` change dataset.  It works in this way on actual `7.1.1`, but it's a bug. I fixed that. This guideline duplication was also fixed.

https://cdn.jsdelivr.net/gh/handsontable/handsontable@a4995f0c804b7fe87d03b9c698bf66f4dfa746dd/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@a4995f0c804b7fe87d03b9c698bf66f4dfa746dd/dist/handsontable.full.css

**Comment by aninde** [comment] 2019-09-26 11:17
Good job @wszymanski. The new build of `8.0.0-rc1` fixed described here bug. 

**Demo**
v. 8.0.0-rc1 http://jsfiddle.net/aninde/7mcn02go/

**Comment by AMBudnik** [comment] 2019-11-15 09:52
Hey @minhtranite @justechn @mismith @minhtranite 

have you already had time to test the 8.0.0-beta1 where this issue should be solved?

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```
`npm i handsontable@beta`

**Comment by pnowak** [comment] 2020-05-21 11:05
Still works well in 8.0.0-beta2-rev6 - http://jsfiddle.net/72zwpers/

![May-21-2020 13-03-02](https://user-images.githubusercontent.com/1555809/82553099-b0e3ad00-9b63-11ea-8788-b2c1679a21a1.gif)

**Comment by pnowak** [comment] 2020-07-21 13:28
Still works well in 8.0.0-beta.2  - https://jsfiddle.net/bcqvt9o3/

**Comment by aninde** [comment] 2020-08-06 10:43
Updated demo with `v8.0.0` still works as intended http://jsfiddle.net/aninde/3v864ckb/. 
Closing as solved and released.

**Closed by aninde** 2020-08-06 10:43 UTC
Labels: Moving, Status: Released, Type: Bug

**Comment by AMBudnik** [comment] 2020-08-07 08:47
Hi @mismith @justechn @minhtranite @superpig 

Can you confirm if updating to v 8.0.0 solves the issue for you?

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
