### ISSUE TITLE
Is `copyRowsLimit` still a thing?

### ISSUE THREAD

**Issue by dancrumb** [handsontable/handsontable#4643] opened 2017-11-30 21:02 UTC
### Description
`copyRowsLimit` has disappeared from the documentation and following a long overdue upgrade of the handsontable version I'm using, I've just received a bug report from a customer that points to the rows limit... is this still a configuration option or was it removed?

### Your environment
* Handsontable version: 0.34.5
* Browser Name and version: Multiple
* Operating System: Multiple

**Comment by AMBudnik** [comment] 2017-12-01 13:31
Hi @dancrumb 

Now you can do it like this

`copyPaste: {pasteMode: '', rowsLimit: 100, columnsLimit: 100}`

Sorry. It's missing from the docs.

**Comment by swistach** [comment] 2018-09-05 10:02
Duplicate of #3524

**Closed by swistach** 2018-09-05 10:02 UTC
Labels: Plugin: copy-paste, Type: Documentation needed
