### ISSUE TITLE
'afterPaste' gets wrong instance values when type is 'numeric' or column has validator

### ISSUE THREAD

**Issue by atelierJVA** [handsontable/handsontable#4593] opened 2017-11-04 21:51 UTC
### Description
I want to paste numbers in a table, and then perform some calculations on them in the `afterPaste`hook using the instance `getDataAtCol`method. 

The issue is that if I define all the columns as `text` it works fine—I get the values that are in the cells—, but if I define any column as `numeric` it does not work— I get  `null` or the previously existing values for all cells—.
(in both cases, the `data`argument in the hook call has the right values)

I have traced the problem to the fact that `numeric` type has a default validator, and that validators calls are async, and  `afterPaste`is called before the value has been assigned to the cells.

The relevant code in  `copyPaste.js`, where `this.hot.runHooks(…)` is called before `this.hot.populateFromArray(…)` async calls have finished:
```
onPaste(event) {
	...
	this.hot.populateFromArray(areaStart.row, areaStart.col, inputArray, areaEnd.row, areaEnd.col, 'CopyPaste.paste', this.pasteMode);
	this.hot.runHooks('afterPaste', inputArray, this.copyableRanges);
}
```

I think that `afterPaste` hook should only be called when all the validators have finished, so you can have access to the actual validated data that is in the table.

### Steps to reproduce

1. Create a handsontable with a `number`type column and define an `afterPaste` hook that prints the content of the first column to the console
2. Run and paste one or more numeric values in the column
3. The output of the console will be an array of ‘nulls’, not the values pasted

### Demo
Here it works because the column is `text`: [JSFiddle_with_text_type-works](http://jsfiddle.net/gyx99pw8/)
When defining the column as `numeric`it fails: [JSFiddle_with_number_type-fail](http://jsfiddle.net/bsjadwyo/)
and also fails when using a validator in  a `text`column: [JSfiddle_with_text_validator-fail](http://jsfiddle.net/mzvqg981/)

### Your environment
* Handsontable version: 0.34.5
* Browser Name and version: Safari 11.0.1 / Chrome 62
* Operating System: macOS 10.12.6

**Comment by AMBudnik** [comment] 2017-11-13 13:01
Thank you for sharing the issue. I have commented all settings and left only 

```
columns: [{
      type: 'numeric'
    }]
```

still, we get `null` from `getData~` methods inside the `afterPaste `hook.

It looks like the issue is there since the `afterPaste` hook was added. It was in the version 0.31.1

**Comment by AMBudnik** [comment] 2018-04-23 09:40
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions (first tested `0.31.1` where the `afterPaste` has been added).

**Comment by AMBudnik** [comment] 2018-08-24 12:57
I've tested v 5.0.1 and it works the same but what I've found that it is a matter of data being recalculated at the right time. When I add a small delay (`50ms`) we get the correct data in the `getDataAtCol`. Here's an example with the delay applied http://jsfiddle.net/hca7ytjL/

**Comment by swistach** [comment] 2019-09-05 15:45
Why not use `beforeChange`?
Demo: http://jsfiddle.net/umob6Led/

`afterPaste` and `beforePaste` hooks base on string values put into a 2D array. If you need to calculate anything after save and validate actions then `beforeChange` with filtering `source` argument seems to be the better option for some calculations (any change in `changes` argument might be overwritten in hook's callback).

**Comment by AMBudnik** [comment] 2019-09-06 09:37
That's a great conclusion @swistach 
It looks like the `beforeChange` hook is the best one to choose here so we shouldn't call it an issue - just the wrong hook choice. That's why I'm closing this topic.

**Closed by AMBudnik** 2019-09-06 09:37 UTC
Labels: Copy-paste, Core: callbacks, Type: Bug
