### ISSUE TITLE
Blue cover bug before change language

### ISSUE THREAD

**Issue by mrkwskiti** [handsontable/handsontable#6230] opened 2019-08-24 23:23 UTC
### Description
When changing cell after change language. The cell will have a blue cover on it

### Steps to reproduce

1. choose some cell
2. change language ( window + spacebar )
3. edit this cell
4. changing cell

### Demo

<img width="583" alt="Annotation 2019-08-25 061908" src="https://user-images.githubusercontent.com/31288625/63643677-50bcf900-c700-11e9-87ab-df639fe84d1b.png">
https://jsfiddle.net/d3x7khgf/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
* Operating System: Windows 10 Version 1903

**Comment by AMBudnik** [comment] 2019-08-26 10:59
Please provide a demo where the issue will be replicable. https://jsfiddle.net/d3x7khgf/ doesn't implement language logic.

**Comment by wojciechczerniak** [comment] 2019-12-28 11:33
Duplicate of #6012

**Closed by wojciechczerniak** 2019-12-28 11:33 UTC
Labels: Core: selection, Type: Bug
