### ISSUE TITLE
"updateSettings" doesn't update classes

### ISSUE THREAD

**Issue by pbadenski** [handsontable/handsontable#4059] opened 2017-02-07 21:33 UTC
### Description
"updateSettings" doesn't update classes

### Steps to reproduce & Demo
See here for working example: http://jsfiddle.net/qh6a3Lvx/

Table should be green.

### Your environment
* Handsontable version: Latest
* Browser Name and version: Chrome 56.0.2924.87 (64-bit)
* Operating System: Mac Sierra (10.12.3)

**Comment by AMBudnik** [comment] 2017-02-08 08:20
Thanks for sharing @pbadenski 
You're right - it's a bug.

**Comment by wojciechczerniak** [comment] 2019-12-28 18:41
Duplicate of #6295. The fix is on its way #6425

**Closed by wojciechczerniak** 2019-12-28 18:41 UTC
Labels: Core: update settings, Type: Bug
