### ISSUE TITLE
[Bug]: Selection is not displayed when the table is in a foreign object

### ISSUE THREAD

**Issue by kumilingus** [handsontable/handsontable#10480] opened 2023-08-28 11:56 UTC
### Describe the bug

After inserting the table into SVG `<foreignObject>`, the cell selection boxes will stop appearing. The user can edit the cell, but the `input` element is hidden (or misplaced).

An example use case is the possibility to insert tables into an SVG document and connect columns or rows using links.
https://jsfiddle.net/kumilingus/j4s8bf97/

### Video/Screenshots

Selecting the `B3` cell:
<img width="323" alt="image" src="https://github.com/handsontable/handsontable/assets/3967880/9bac736e-35c7-4f6b-b582-f17d72a0520f">

Editing the `B3` cell:
<img width="320" alt="image" src="https://github.com/handsontable/handsontable/assets/3967880/bd5f72c0-279c-43d7-b283-d750dd7999b8">

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/kumilingus/1upLrsy5/

### Handsontable version

13.0.0

### Your environment

Chrome, FF, Safari / macOS

**Comment by adrianszymanski89** [comment] 2023-08-28 13:36
Closed as a duplicate of the ZenDesk issue.

**Closed by adrianszymanski89** 2023-08-28 13:36 UTC
Labels: bug
