### ISSUE TITLE
Autofill throws error since version 19.0 when used with formula.js

### ISSUE THREAD

**Issue by gonwalf** [handsontable/handsontable#3111] opened 2016-01-10 09:15 UTC
Dragging the autofill handle down results in an error.

[jsfiddle Example](http://jsfiddle.net/jeanmarc/663sr199/5/)

Error message in the JS console:
`Uncaught TypeError: Cannot read property '0' of undefined`

**Comment by AMBudnik** [comment] 2016-01-11 10:43
Confirmed.

**Comment by AMBudnik** [comment] 2016-03-22 13:37
Couldn't reproduce with latest 0.24.1 version. 
I'm closing this issue but if there's something that I'm missing please leave a comment.

**Closed by AMBudnik** 2016-03-22 13:37 UTC
Labels: Bug, Plugin: formula support
