### ISSUE TITLE
AfterValidate and Return False

### ISSUE THREAD

**Issue by parissge** [handsontable/handsontable#3099] opened 2016-01-04 16:18 UTC
According to the documentation for version 0.20.0 if I want to cancel changes in afterValidate I can return false.
I have this code
afterValidate: function (isValid, value, row, prop, source) {                
                if (isValid == false && source == "edit") {
                    return false;
                } 
            }
but my changes are not cancelled. Am I doing something wrong?
Thank you for your time.

**Comment by AMBudnik** [comment] 2016-01-05 12:57
Hi, can you create a demo with your code? 
Thanks in advance.

**Comment by jakedeichert** [comment] 2016-02-08 23:02
I'm also having the same issue. Returning `false` does not cancel the change. 

I see you need a demo, I may have time later to do a quick one. I just wanted to point out that I also think there's a bug here.

**Comment by jakedeichert** [comment] 2016-02-08 23:13
Here's a demo: http://jsfiddle.net/gnkaxfxu/

Type in a non-numeric value in any row except the first row. 

Result: the cell turns red
Expected result: the value should not have changed

**Comment by jakedeichert** [comment] 2016-02-09 16:12
Here's a temporary workaround: http://jsfiddle.net/pxjraoL5/

The important code is:

~~~js
hot.addHook('afterChange', function(changes, source) {
  for (var c = 0; c < changes.length; c++) {
    var row = changes[c][0];
    var col = changes[c][1];
    var newValue = changes[c][3];
    hot.getCellValidator(row, col)(newValue, function(isValid) {
      if (!isValid) {
        hot.setDataAtCell(row, col, null);
      }
    });
  }
});
~~~

If `isValid` is `false`, then I just set that cell to empty/null.

**Comment by AMBudnik** [comment] 2016-03-07 14:11
thanks for sharing details @jakedeichert 
I tried the second demo (with a workround) and it does not allow to exit edit mode and after that editing is freezed.
Sorry if I'm not getting the idea but maybe this one's a better approach http://jsfiddle.net/gnkaxfxu/2/?

**Comment by jakedeichert** [comment] 2016-03-07 18:52
@AMBudnik hmmmm I think I remember testing that jsfiddle and it worked. I think since Handsontable was updated to 0.23.0 17 days ago, it has broke my work-around since that jsfiddle I believe links to the most up to date version of handsontable.full.js. 

Could this be another bug causing my jsfiddle to break? The console says `Cannot read property 'allowEmpty' of undefined` however, according to the 0.23.0 update (https://github.com/handsontable/handsontable/releases/tag/0.23.0) allowEmpty is true by default.

**Comment by jakedeichert** [comment] 2016-03-07 18:57
@AMBudnik yupp, I think I confirmed it.

Here's my same jsfiddle using an external resource of handsontable v0.22.0: http://jsfiddle.net/bcqrrgud/ 
Try my work-around now. The cell properly deletes if you enter a letter for example.

Note, my old jsfiddle (http://jsfiddle.net/gnkaxfxu/) was pointing to the latest version (0.23.0) of handsontable.full.js and I believe there's a new bug around `allowEmpty`. Try this fiddle again and open your console to see the error.

**Comment by AMBudnik** [comment] 2016-03-08 12:10
thanks for feedback and detailed explanation @jakedeichert

**Comment by jansiegel** [comment] 2016-03-11 10:41
@jakedeichert, @AMBudnik 

Ok, first thing - the documentation for `afterValidate` is misleading indeed. Returning `false` from the callback does *not* cancel any changes. What it does, is marking the cell as invalid (which can disallow the change, when using it with `allowInvalid: false`). It should be updated, for sure.

Second thing - the `allowEmpty` problem is caused by running the validator without proper context, resulting in `this.allowInvalid` being undefined.

I've made a workaround (based on your example) using the `beforeChange` hook, but I'm not sure if it'll fit your needs. What it does is:
* *before* the changes are applied to the dataset, runs them through a validator
* if the validation was successful, it does nothing
* if it wasn't, it modifies the change, so it contains the old cell value (or you can use `null` or whatever you'd like here)
* after the change replacement, it marks the cell as valid, so it won't get highlighted

What do you think? http://jsfiddle.net/js_ziggle/6tLLagr4/1/

**Comment by jansiegel** [comment] 2016-03-11 10:56
Change in the docs (https://github.com/handsontable/handsontable/commit/06006007fac4bf293a57180cb8c1734986c30d47) was pushed to the develop branch and will be out with the next release (scheduled for Monday, March 14th)

**Comment by jakedeichert** [comment] 2016-03-11 15:24
@jansiegel thanks for updating the documentation!

Also, that solution works great. It avoids the quick red flicker that my workaround had.

Thanks for the help. I think you can close this?

**Comment by AMBudnik** [comment] 2016-03-11 15:27
@jakedeichert as it is already merged to he develop branch I also think that we can close this issue.
thank you @jansiegel

**Closed by AMBudnik** 2016-03-11 15:27 UTC
Labels: Core: validation, Documentation needed, Priority: normal
