### ISSUE TITLE
Left positionning of comment box is not good when we freeze columns.

### ISSUE THREAD

**Issue by JereMiO** [handsontable/handsontable#9643] opened 2022-07-08 16:38 UTC
### Description
The comment box is on the wrong place when you freeze a column which contain a cell with comment and you use the horizontal scrolling.

### Steps to reproduce
1. https://jsfiddle.net/b682tar4/10/
2. Freeze Colum B
3. Reduce width of preview
4. Scroll to right
5. Hover cell which contains comment

### Demo
https://jsfiddle.net/b682tar4/10/

### Your environment
* Handsontable version: 12.1.1
* Browser name and version: chrome 103
* Operating system: Win10

![image](https://user-images.githubusercontent.com/303791/178032959-e8d15732-0667-40e6-aacc-57364b576610.png)

**Comment by AMBudnik** [comment] 2022-12-14 13:13
Hi @JereMiO 

Good news! We just published Handsontable v12.3.0. Here https://jsfiddle.net/wrv7achn/, you can test the newest version https://jsfiddle.net/wrv7achn/ where the issue is fixed.

I am closing the issue as done. But if you have any questions, please feel free to leave a comment.

**Closed by AMBudnik** 2022-12-14 13:13 UTC
Labels: Type: Duplicate, Reported
