### ISSUE TITLE
Does handsontable support not enlarge the selection when selection contain merge cell

### ISSUE THREAD

**Issue by bellcliff** [handsontable/handsontable#4113] opened 2017-03-03 15:29 UTC
#### What Happens :
 When click column/row header, and if the column contained merge cells, which the selection will expand itself to contain all columns/rows which mapping the merged cell instead of the column/row header

#### What should happen:
Do we support: the selection do not expand to cover all merged cells, but only the exact row/column

### Steps to reproduce

1. click the row/column header cell, to select a row/column
2.
3.

### Demo

It's the same example as shown on office doc site about cell feature merged cells .
http://jsfiddle.net/4stfv7Lm/

### Your environment
* Handsontable version: 0.30.1
* Browser Name and version: Chrome 56
* Operating System:

**Comment by AMBudnik** [comment] 2017-03-07 08:45
Hi @bellcliff 

Yes, you are right by default you select all columns that correspond to the merged area and currently you cannot select only one column.

**Comment by ibrahimyilmaz7** [comment] 2017-03-15 10:10
@AMBudnik 

Isn't that a bug? It continues in the current version (v1.10.1) as well.

**Comment by AMBudnik** [comment] 2017-03-15 13:22
@ibrahimyilmaz7 
Currently, it is an intended behavior that when I want to select a column `C` here


![image](https://cloud.githubusercontent.com/assets/10757813/23950217/84c1d620-098a-11e7-9434-30d5c6c7b41b.png)


I will also select columns `B` and `D` cause there's a merged area `[B2:D4]`

![image](https://cloud.githubusercontent.com/assets/10757813/23950264/b65de5e8-098a-11e7-8f08-e772c7f92278.png)

**Comment by AMBudnik** [comment] 2017-03-20 09:15
I think that we can close this issue as (like written post above) the behavior won't change for columns.

**Closed by AMBudnik** 2017-03-20 09:15 UTC
Labels: Status: Answered
