### ISSUE TITLE
Rows are misaligned on the column/row resize demo

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2354] opened 2015-04-09 13:37 UTC
Rows are misaligned by `1px` (ht_clone_left copy is higher by `1px`) in this demo: http://handsontable.com/demo/column_resize.html 

![image](https://cloud.githubusercontent.com/assets/7397134/7067792/3eef8716-dece-11e4-9790-8ede190b5b93.png)

**Comment by AMBudnik** [comment] 2015-04-10 07:29
Maybe [this](https://jsfiddle.net/ob13cyxw/) 1px misalignment is related. After scroll multiple lines cells are lower so fixed area has a 1px spare frame under.

![zrzut ekranu 2015-04-10 o 09 27 07](https://cloud.githubusercontent.com/assets/10757813/7083584/0b33345e-df64-11e4-8993-50c1e82dac17.png)

**Comment by AMBudnik** [comment] 2015-04-10 14:58
Here's the 'cleared' [version](https://jsfiddle.net/mam2ea82/2/), when we add `colHeaders: true` we'll get a scroll like in this issue https://github.com/handsontable/handsontable/issues/2361

**Comment by AMBudnik** [comment] 2015-04-22 08:45
Related https://github.com/handsontable/handsontable/issues/1780

**Comment by AMBudnik** [comment] 2015-05-04 08:03
We could take a look at https://github.com/handsontable/handsontable/issues/2407 also.

**Comment by AMBudnik** [comment] 2015-07-24 11:45
Issue no longer exists, it will stay closed but please leave us feedback if something it still misaligned.

**Comment by awsp** [comment] 2015-08-04 20:54
Hi @AMBudnik,
I am still somehow getting slightly misalignment after using version 0.16.1. 
Looks like the 1px starts to get expanded when there are more rows exist. 
Starting from row 1 to row 7, see screenshot. 

![screen shot 2015-08-04 at 10 47 12 am](https://cloud.githubusercontent.com/assets/2015218/9072403/a9b58720-3a96-11e5-8993-ebd36cef840d.png)


Here is the code I was using, 
```html
<html>
  <head>
    <link href="http://handsontable.com/bower_components/handsontable/dist/handsontable.full.min.css" rel="stylesheet" type="text/css">
    <script src="http://handsontable.com/bower_components/handsontable/dist/handsontable.full.min.js"></script>
  </head>
  <body>
    <div id="example"></div>
    <script>
      var data = [
        {}
      ];

      var container = document.getElementById('example');
      var hot = new Handsontable(container, {
        data: data,
        rowHeaders: true,
        minSpareRows: 1,
        width: window.innerWidth,
        height: window.innerHeight,
        colHeaders: true,

        columns: [
          { data: 'foo1', width: 400 },
          { data: 'foo2' },
          { data: 'foo3' },
          { data: 'foo4' },
          { data: 'foo5' },
          { data: 'foo6' },
          { data: 'foo7' },
          { data: 'foo8' },
          { data: 'foo9' },
          { data: 'foo10' },
          { data: 'foo11' },
          { data: 'foo12' },
          { data: 'foo13' }
        ]
      });
    </script>
  </body>
</html>
```

**Comment by AMBudnik** [comment] 2015-08-11 21:50
Could you please create a full demo @awsp ?

**Comment by awsp** [comment] 2015-08-12 02:08
@AMBudnik
Here you are, its basically a clone from the above HTML code using Handsontable 0.16.1 at this moment. 

[http://awsp.github.io/handsontable/index.html](http://awsp.github.io/handsontable/index.html)

Tho I couldn't re-create this issue on JSFiddle (see [demo](http://jsfiddle.net/t9zzmvv9/)). If anybody could check this out for me that, I would really appreciate that. 

PS: Both demos were on the exact same browser.

**Comment by AMBudnik** [comment] 2015-08-12 13:28
Thanks for your demo @awsp after scrolling first column shrinks a little (1-2px). I'll reopen this issue.

**Comment by cgatesman** [comment] 2015-10-19 19:04
I was going to open an issue about the row borders being out of alignment when using fixedColumnsLeft > 0, and I prepared a simple JSFiddle demonstrating it.  I found this issue and assume it's the same issue.

http://jsfiddle.net/cgatesman/138vbo89/

You can click on the button to toggle the fixed/frozen column on and off and see that the rows will come into alignment when fixedColumnsLeft === 0.

**Comment by nischalsource** [comment] 2015-11-16 13:02
Any resolution of this?

**Comment by AMBudnik** [comment] 2015-11-16 13:14
@nischalsource as long as one of our programmers will start to work on this case it'll be given a new status (label).

**Comment by AMBudnik** [comment] 2016-01-13 11:54
related: https://github.com/handsontable/handsontable/issues/3118 same with zoom in/out

**Comment by markusp72** [comment] 2016-01-27 08:21
+1

**Comment by gstanislav** [comment] 2016-02-18 16:41
Is there a workaround?

**Comment by sbichenko** [comment] 2016-02-21 18:26
Here's a workaround that worked for me:

```
tr:not(:last-child) {
    border-bottom: none;
}
tr:first-child td {
    border-top: none; /* causes top border of blue selection box to be under header */
}
tr:first-child th {
    border-bottom-width: 1px !important;
}

**Comment by basrita** [comment] 2016-03-01 13:02
hi @sbichenko . I have tried with that but no change.still same problem for me.
![screenshot](https://cloud.githubusercontent.com/assets/7194256/13427720/facc09b4-dfdb-11e5-8400-9e497a26293a.png)

**Comment by threemr** [comment] 2016-05-15 03:38
+1 on this issue, but with a key difference: the misalignment only occurs when using the "checkbox" type of cell. When using just numbers or text, the alignment is perfect. I just upgraded to version 0.24.3. 

It seems different browsers render this bug differently too. When using Chrome, the misalignment is only 1px across the board, so not too noticeable even as you go down many rows. However, on Firefox or IE11, the difference keeps growing pixel by pixel, as on the examples others have posted above.

I tried the workaround suggested by @sbichenko, but unfortunately that didn't work either.

**Comment by krzysztofspilka** [comment] 2016-06-08 13:53
@AMBudnik could you put here a demo where it is still reproducible? I couldn't track down the bug in the 0.25.1 version.

**Comment by AMBudnik** [comment] 2016-06-08 14:08
@krzysztofspilka guess it's working fine now. 

I've tested a version with/without: height/width settings, very long text, `fixedColumnsLeft` and the checkbox as @thanpolas suggested, full demo: http://jsfiddle.net/x3xzd7u2/

**Comment by nothingmi** [comment] 2016-08-19 09:03
Why don't u add an option for header? It's maybe easier to fix this bug.
If I set columnHeaderHeight to 40px, the table looks like:
![image](https://cloud.githubusercontent.com/assets/14083659/17804522/98f69752-662e-11e6-8866-b519311abe44.png)
The row header & column header are neither center & middle. But it will works if I add class htCenter & htMiddle in THs.
Is it a solution? Thanks!

**Comment by AMBudnik** [comment] 2016-09-02 13:54
I think that the issue can be closed as I wasn't able to replicate any of the listed behaviors.
Thanks for sharing demos and feedback.

**Closed by AMBudnik** 2016-09-02 13:54 UTC
Labels: Bug, Core: alignment/height/width, Plugin: freeze / resize / move, Priority: normal

**Comment by nischalsource** [comment] 2016-09-02 16:16
yes, I was one of the original sufferers from this error. It stopped being a problem for us. However I cant remember how we solved this error.

**Comment by AMBudnik** [comment] 2016-09-05 08:19
thank you from your feedback @nischalsource 
if anything similar would appear just give me a hint.

**Comment by Joshua-W-Adams** [comment] 2017-09-06 05:30
I was having the same issue and managed to fix it by setting a larger value to the rowHeights property or turning it off completely. In my case changing from 20 to 25 fixed the misalignment. Maybe this solution will work for you aswell.

**Comment by ottosson** [comment] 2017-09-13 12:18
I have this problem too!

I fixed the first two columns (`fixedColumnsLeft: 2`) and the first contains pictures that can vary in height.

The misalignment varies when I scroll vertically.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/3355320/30376840-03aa62a8-988e-11e7-9061-391916543b2e.png">

**Comment by AMBudnik** [comment] 2017-09-13 12:22
Hi @ottosson 

have you tried adding the image inside a fixed height/width container or adding `autoRowSize` to the settings?

**Comment by ottosson** [comment] 2017-09-13 12:38
@AMBudnik, containing the image in a fixed size div solved the problem!

Thanks a lot!

**Comment by AMBudnik** [comment] 2017-09-13 13:10
you're welcome @ottosson

**Comment by bakeiro** [comment] 2018-05-23 09:17
The solution of @sbichenko worked for me!
CSS Code:
`
tr:not(:last-child) {
    border-bottom: none;
}
tr:first-child td {
    border-top: none; /* causes top border of blue selection box to be under header */
}
tr:first-child th {
    border-bottom-width: 1px !important;
}
`

**Comment by bj00rn** [comment] 2019-02-01 10:23
@AMBudnik has a fix for this been released?

**Comment by AMBudnik** [comment] 2019-02-04 10:43
@bj00rn the issue has been already solved. If it does not work for you after updating to the latest version please let me know at support@handsontable.com
