### ISSUE TITLE
Uncaught exception when pasting into rows with pre-populated values

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4737] opened 2018-01-19 16:07 UTC
### Description

There is an uncaught error in the demo about pre-populating values: 
`Uncaught TypeError: Cannot read property 'length' of undefined`

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.15.0/demo-pre-populating.html
2. Open developer tools > console
3. Copy two rows and paste into the last row 
OR
3. Copy three rows and paste into the one before last row (penultimate)

### Demo

https://docs.handsontable.com/pro/1.15.0/demo-pre-populating.html

### Your environment
* Handsontable version: 0.35.0 / 1.15.0
* Browser Name and version: Chrome 63
* Operating System: MacOS

**Comment by redcom** [comment] 2018-01-24 12:44
Hi,
Where would it be a good place to submit a fix for this issue?

At the moment I just fork the docs-pro and committed the fix there and wanted to open a PR for handsontable repo

**Comment by AMBudnik** [comment] 2018-01-24 12:57
Hi @redcom 

if the issue relates only to an incorrect use of the code in a demo you can share it to the `docs` repository. However, you would also need to [sign the CLA](https://docs.google.com/forms/d/1sNbsA7MGelGNxsBRvBoY3swq7YEMYhXNpR7NPk4tWPo/edit#response=ACYDBNhV1MTfdr_NRjtxSKISOkC3HVhagIFXk_ZELGMEB_3L4uIlD2CG9AtqXYs) if you haven't done it already.

**Comment by swistach** [comment] 2018-05-17 12:05
Duplicate of handsontable/docs#57 and handsontable/docs#58

**Closed by swistach** 2018-05-17 12:05 UTC
Labels: Type: Bug
