### ISSUE TITLE
Hiding first rows bug

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5817] opened 2019-02-25 14:10 UTC
### Description

After hiding the first two rows, the row headers become de-synchronized by 1px.

### Steps to reproduce

1. Go to https://jsfiddle.net/2rfbx0kc/.
2. Hide first to rows (`1` and `2`) using the context menu.
3. In the result, the table row headers position is misleading.

### Demo

https://jsfiddle.net/2rfbx0kc/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 72
* Operating System: macOS

**Comment by AMBudnik** [comment] 2019-09-17 11:16
The issue is replicable in v `7.1.1` https://jsfiddle.net/handsoncode/vg2s0awr/ 
and works the same using `8.0.0.-rc1` https://jsfiddle.net/handsoncode/48L3grc1/

**Comment by wojciechczerniak** [comment] 2019-09-17 14:33
From #5847
> ### Description
> 
> And rowHeaders/colHeaders isn't switched on.
> In TH with class `.firstVisibleColumn` (added from `hiddenColumns` plugin) adds style `border-left-width: 0;`.
> ### Demo
> 
> https://jsfiddle.net/bzua1pyt/
> https://jsfiddle.net/uhr5an76/
> ### Your environment
> 
>     * Handsontable version: At least 1.14.0 - http://jsfiddle.net/w3ycztv2/
>     * Browser Name and version: Chrome  72.0.3626.119, Firefox 65.0.1  and Safari 12.0.1
>     * Operating System: OS Sierra 10.12.6

**Comment by AMBudnik** [comment] 2020-03-24 13:03
It works the same in 8.0.0-beta1 https://jsfiddle.net/wk6qafj7/

![Zrzut ekranu 2020-03-24 o 14 02 20](https://user-images.githubusercontent.com/10757813/77428297-25a2a100-6dd8-11ea-80df-888f82fa84a3.png)

**Comment by AMBudnik** [comment] 2020-05-08 09:07
Remains the same in 8.0.0-beta2-rev2 https://jsfiddle.net/b91e7htj/

![](https://user-images.githubusercontent.com/10757813/81390625-13788a00-911c-11ea-8a05-ceec460cee03.png)

**Comment by wojciechczerniak** [comment] 2020-06-10 06:44
@AMBudnik @aninde Can't replicate with the latest `8.0.0-beta.2-rev13`: https://jsfiddle.net/rybv2jdL/

**Comment by aninde** [comment] 2020-08-06 09:26
Updated demo with v8.0.0 https://jsfiddle.net/aninde/mtdjzb70/. Still works well. Closing as released.

**Closed by aninde** 2020-08-06 09:26 UTC
Labels: Headers, Hiding, Type: Bug
