### ISSUE TITLE
[8.2] afterSetRangeEnd local hook calls scrolling with wrongly parametrized WOT on HT with fixedColumns

### ISSUE THREAD

**Issue by dtomaszewski** [handsontable/handsontable#7462] opened 2021-01-13 07:39 UTC
### Description
When Fixed columns are present in HT internal hook afterSetRangeEnd is called multiple times on open dropdown, some are with correct params (I'm not convinced if it should be called so often without any visual effect but it may be connected with some internal functionalities IDK).

![Screenshot 2021-01-13 at 08 19 52](https://user-images.githubusercontent.com/4403684/104419040-31826e00-5578-11eb-82b5-3e48ccd53584.png)

I've debugged HT code a bit and I've noticed that first calls are executed with correct HT instance as WOT instance but last call is executed with WOT with wrong HT instance, it's just dropdown element instead of whole handsontable (mainTableScrollableElement is also wrong in the same way which causes multiple comparison with rootWindow being wrong).

![ht1](https://user-images.githubusercontent.com/4403684/104420844-ca19ed80-557a-11eb-9c2c-30913973ab4d.jpg)

This issue causes weird behaviour of HT, most annoying for us and our clients is that limited dropdowns are scrolled to the right (scrollTo method is called then setScrollPosition with mainTableScrollableElement set as dropdown item). The same thing happens when user enters some characters which match any of list items, dropdown is scrolled again.

**This issue block us with update to HT8 when we have critical issue with filtering columns performance which forces us to update to HT8 so please treat this issue as urgent. If You need any more information from my side please contact me directly or through this issue**

### Steps to reproduce
1. Create HT with fixed columns
2. Use multiple dropdown inputs with limited width
3. Add fixed columns
4. See that some of inputs are scrolled to the right

### Demo
http://jsfiddle.net/6zjnuf0c/14/

Open dropdown in col J and see that it's scrolled to the right, scroll it to the left, type 1, see that it's scrolled again.

### Your environment
* Handsontable version: 8.2 Commercial version
* Browser Name and version: Chrome last
* Operating System: MacOs

**Comment by AMBudnik** [comment] 2021-01-13 08:09
Hi @dtomaszewski 

Interestingly when I commend out `trimDropdown` the scrollbar is in the middle
![image](https://user-images.githubusercontent.com/10757813/104422816-87a5e000-557d-11eb-956a-11ddf53cb833.png)
I'm sure that this scenario hasn't been tested. We usually do not recommend using external CSS to change elements' dimensions.

Maybe it would be better to use 'handsontable' cell type http://jsfiddle.net/handsoncode/ovmtdsx5/ ? No CSS needed.

![GIF 13 01 2021 09-09-08](https://user-images.githubusercontent.com/10757813/104423992-0d765b00-557f-11eb-8bce-bfa1ad177d0f.gif)

**Comment by dtomaszewski** [comment] 2021-01-13 08:16
@AMBudnik we have much more complicated scenario there which will not be easy to change. I've used dropdown type of cell just to reproduce this issue, we use custom editors and I have no time and reason to change it.

Nevertheless CSS is not an issue here, Issue is that HT code behaves wrong in place I've shown. It's probably not the only issue caused by this so I'd appreciate it if dev team could take a look at this case.

**Comment by dtomaszewski** [comment] 2021-01-14 13:43
Hello @AMBudnik do You have any news about this issue ? Or some kind of workaround where I'm able to scroll this cell back manually until it's solved? (Note that it scrolls every time user inputs any value)

**Comment by AMBudnik** [comment] 2021-01-14 13:48
I have asked my colleague to share his opinion on the subject as soon as he finishes his current task. We should get an update here tomorrow (or on Monday at the latest).

**Comment by dtomaszewski** [comment] 2021-01-14 13:51
Thanks a lot @AMBudnik

**Comment by dtomaszewski** [comment] 2021-01-18 08:07
If someone will have similar issue my workaround is (placed in custom cell open method) :

`    
        const wtHolder = this.TEXTAREA_PARENT.querySelector('.handsontableEditor .wtHolder');

        fromEvent(wtHolder, 'scroll')
            .pipe(take(1))
            .subscribe(() => {
                wtHolder.scrollLeft = 0;
            });

        fromEvent(this.TEXTAREA, 'change')
            .pipe(takeUntil(close$))
            .subscribe(() => {
                wtHolder.scrollLeft = 0;
            });`

It's working but it's temporary ugly fix, waiting for official solution.

**Comment by swistach** [comment] 2021-01-18 16:20
Hi @dtomaszewski,
First of all, I'd like to share a context, why it's working that way (and why it works that by design).
`DropdownEditor` bases on `AutocompleteEditor`, `HandsontableEditor` and `TextEditor`. Thanks that we have a huge interface and a lot of functionalities shared between all these three editors (shortcuts, refreshing dimensions etc).
By default (and is not possible to overwrite) we set `cellProperties.strict` to `true` (https://github.com/handsontable/handsontable/blob/master/src/editors/dropdownEditor.js#L20) - this is an important property, because of the fact that `HandsontableEditor` uses this flag to run `selectCell` (https://github.com/handsontable/handsontable/blob/master/src/editors/handsontableEditor.js#L33-L34).

Why we have to selectCell after DropdownEditor is open?
Support for keybindings and setting value from the selected option - eg.: if you open an editor and hit <kbd>ENTER</kbd> then we know what value to set based on the current selection.

SelectCell automatically tries to scroll to show selected cell in the viewport - in your case cell is much wider than viewport and the default behaviour is to scroll to right-bottom corner. We have to remember that by default DropdownEditor and AutocompleteEditor are trimming to the column width. If you try to customize it by CSS styling then it might work in an unpredictable way.
But there is a rescue in the situation like that - `preventScrolling` in `afterSelection` hook. Long story short - it's an object where you can block the default behaviour. As I mentioned above, under the hood it's still Handsontable and accordingly to this condition: https://github.com/handsontable/handsontable/blob/master/src/editors/handsontableEditor.js#L93-L95 we can pass additional options to the instance of Handsontable in DropdownEditor. I prepared a simple demo: https://jsfiddle.net/fqLstung/2/

Additionally, I'd like to mention it's present in v7 also: https://jsfiddle.net/fqLstung/3/

Last working version of Handsontable, where `afterSelection` was not necessary is v6: https://jsfiddle.net/fqLstung/

I hope the above explanation helps you in migration.

**Comment by dtomaszewski** [comment] 2021-01-19 13:30
@swistach thank's for Your explanation, I've read it and I need to have a deep look at Your examples. Two questions bother me still, look at my example, why it's so inconsistent, column E does not scroll when column J scrolls, second thing is that it only happens when we have fixed columns without it it works fine for all columns. Are You 100% sure it's by design ?

**Comment by swistach** [comment] 2021-01-19 18:13
You're welcome.
Oh yes, I forgot to mention, that auto-selection after open works in two cases:
1) If the editable cell is empty (has no value)
2) If the editable cell contains one of the possible options to choose by DropdownEditor

So in your example:
- `E` column is not empty - DropdownEditor does not select anything after open because in `source` contains other options;
- `F` column is empty - DropdownEditor selects a first option.

In column `E` if you'll use `ArrowDown` after open DropdownEditor you'll get the same scroll-behaviour.

**Comment by dtomaszewski** [comment] 2021-01-22 09:10
@swistach do I understand it well that You say - we have value in cell and no value in second cell and one dropdown is scrolled and second is not ? And it's correct ? What's the single UX reason to behave that way ? I understand that there are technical explanation but isn't it fundamentally wrong behavior?

**Comment by swistach** [comment] 2021-01-26 11:46
Not exactly, I meant if the value in the cell is present in values available in dropdown, then after opening editor this item will be selected - because dropdownEditor bases on Handsontable - that means we scroll viewport to the selection. In case we cannot find the same value in dropdown or cell is empty, we have nothing to select.
If you customize dropdown and you have wider inner content (its container needs horizontal scroll) then table scrolls its `scrollableContainer` to the far right-bottom corner of the selection - but remember that most scenarios base on the default options - fit in the same width as a column and whole dropdown content is visible without horizontal scroll.

It's difficult to judge it's bad behaviour or not - but at the moment it works as we expected and we do not plan to change this in the nearest future. At the same time, we try to adjust built-in components to cover as many use case scenarios as possible. And for not-covered use cases, we give end-developers multiple options and hooks to customization and overwriting the default behaviour. It helps us to keep our components quite simple to maintain and as easy to understand as possible for end-devs.

However, you raised up a very interesting point we should consider in our UX planning. I'm going to mark your issue as an improvement suggestion. Also, I close this issue for now till we back to the UX issue. Feel free to share with us your considerations about how we can improve this component, you can continue this topic here.

**Closed by swistach** 2021-01-26 11:46 UTC
Labels: Status: Answered
