### ISSUE TITLE
Fast vertical drag and drop adds too many empty rows

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#3991] opened 2017-01-11 13:41 UTC
### Description

Autofill plugin adds **two empty rows** when applying drag down. It should add **only one empty row** when handle reach last one row. 

### Steps to reproduce

1. Go to: http://jsfiddle.net/wojciech/anLLLrhz/1/
2. Select cell
3. Drag down to last one row
4. Drop selection immediately when handle will reach last cell

![drag1](https://cloud.githubusercontent.com/assets/141330/21850339/689b83e4-d80a-11e6-9e45-8a40fbd9b313.gif)
![drag2](https://cloud.githubusercontent.com/assets/141330/21850344/6ab94e9a-d80a-11e6-9db8-55a093bc7d5d.gif)
### Demo

http://jsfiddle.net/wojciech/anLLLrhz/1/

### Your environment
* Handsontable version: 29.2
* Browser Name and version: Google Chrome 55.0.2883.95 (64-bit)
* Operating System: macOS Sierra 10.12.2

**Comment by gresspav** [comment] 2017-01-12 12:42
Dangerous feature. May be it should be turned off by default.

**Comment by AMBudnik** [comment] 2017-01-12 13:27
@gresspav 
here I guess that @wszymanski wanted only to fix the issue with adding too many empty rows while using fill handle. Here we can see that 2 rows are added instead of one.

**Comment by AMBudnik** [comment] 2018-04-20 08:32
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment] 2019-03-01 10:37
@wszymanski we weren't able to replicate it with @wojciechczerniak in the latest version so closing the issue.

**Closed by AMBudnik** 2019-03-01 10:37 UTC
Labels: Guess: few hours, Plugin: auto fill, Priority: normal, Type: Bug
