### ISSUE TITLE
[Bug] Integer drop-down values always invalid.

### ISSUE THREAD

**Issue by lewisjb** [handsontable/handsontable#4143] opened 2017-03-21 00:06 UTC
### Description

If you have a drop-down column where all the possible values are integers, then whenever you change that cell it marks it as invalid.

With a small amount of debugging via the `afterChange` hook, it appears to be because when you select a value from the drop-down it sets the cell value to a string, but `1 !== '1'`.

### Steps to reproduce

1. Create an integer drop-down column.
2. Change it's value to any in the drop-down, the cell will be red.

### Demo

http://jsfiddle.net/s2q1ypjq/

### Your environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome 55
* Operating System: Ubuntu

**Comment by AMBudnik** [comment] 2017-03-22 11:02
Thank you for sharing @lewisjb 
This is definitely a bug. Also I would like to bound this issue https://github.com/handsontable/handsontable/issues/4111 as it relates to changing between data types.

**Comment by AMBudnik** [comment] 2017-05-18 11:48
Hi @lewisjb 
we are happy to announce that the changes are already online. Current version is 0.32.0. Please let me know if the issue is solved and it works in your project as well.

**Comment by AMBudnik** [comment] 2017-05-22 11:26
I am closing this issue as there are no other questions or concerns but if someone has any please leave a comment.

**Closed by AMBudnik** 2017-05-22 11:26 UTC
Labels: Cell type: autocomplete / dropdown / handsontable, Priority: high, Status: Released, Tested, Type: Bug

**Comment by TRManderson** [comment] 2017-11-10 02:08
We still have this issue running with 0.32.0. Have there been any relevant changes in more recent releases?

**Comment by AMBudnik** [comment] 2017-11-10 10:35
Hi @TRManderson 
it's working on the latest version http://jsfiddle.net/84jyqjmw/
and he's a working example using v0.32.0 http://jsfiddle.net/3adb9foj/

I am testing this on Chrome 62/Win 10.

**Comment by TRManderson** [comment] 2017-11-10 10:40
Thank you very much :)

That tells me it's an issue in our code!

**Comment by AMBudnik** [comment] 2017-11-10 10:41
You're welcome @TRManderson 

I am keeping my fingers crossed for finding the bug.
