### ISSUE TITLE
[1.10.2+] The filter works wrong when using afterSelection

### ISSUE THREAD

**Issue by tranvanhuan** [handsontable/handsontable#4311] opened 2017-06-14 02:49 UTC
Dear Handsontable community,

we are facing with the issue when using afterSelection function, the checkboxs in filter have been unchecked.
The code like this:
==============================================
<link rel="stylesheet" type="text/css" href="./handsontable.full.min.css">
<script src="./handsontable.full.min.js"></script>
<div id='handsontable' style="width: 100%; height: 100%;">
</div>
<script>
	let container = document.getElementById('handsontable');
	let hot = new Handsontable(container, {
		colHeaders: true,
		data: [
			['', 'Ford', 'Volvo', 'Toyota', 'Honda'],
			['2016', 10, 11, 12, 13],
			['2017', 20, 11, 14, 13],
			['2018', 30, 15, 12, 13]
		],
		filters: true,
		dropdownMenu: {
			items: {
				'filter_by_condition': {},
				'filter_by_value': {},
				'filter_action_bar': {}
			}
		},
		beforeFilter: function () {
		},
		afterFilter: function (obj) {
			console.log('afterFilter', JSON.stringify(obj));
		},
		afterSelection: function (obj) {
			hot.setDataAtCell(0, 0, 'new');
		}
	});

</script>
========================================

Steps to reproduce:
- 1 Click on the filter button, untick on the checkbok 13:
![afterselection](https://user-images.githubusercontent.com/28914946/27115226-78d80b80-50f3-11e7-94f0-1036be562931.png)

- 2 The result showed as expected but click on the filter button, all checkboxs were been unchecked like this:
![afterselection2](https://user-images.githubusercontent.com/28914946/27115236-870e1942-50f3-11e7-93bb-04cee194d942.png)

------------------------------------------------------------------------------------------------------------ 

How to fix this issue, could you please give us the advice to fix it.

Many thanks,
Huan

**Comment by AMBudnik** [comment] 2017-06-19 08:31
Hi @tranvanhuan 

can you share a code via JSFiddle? You can use this demo http://jsfiddle.net/z19fLby0/ as a template if you wish,

thanks in advance

**Comment by tranvanhuan** [comment] 2017-06-19 11:18
Hi AMBudnik,

The code was added into http://jsfiddle.net/z19fLby0/17/
Thank you, look forward to hearing from you.

Sincerely,
Huan

**Comment by AMBudnik** [comment] 2017-06-20 10:00
I can see that actually, the 25th line with `setDataAtCell` erases the filters.  It is a pretty interesting case as literally when you filter a dataset in the same time you change it by 

`hot.setDataAtCell(0, 0, 'new');`

still, I am not sure if this should clear the `filter by value` list.

**Comment by tranvanhuan** [comment] 2017-06-23 06:13
Hi @AMBudnik ,

Thank for your response, so you mean that is recently behavior? do you have any ideas to fix that issue?
Could you share, or any processes to fix the issue, could you let me know!!!

Thanks

**Comment by AMBudnik** [comment] 2017-06-23 07:23
Hi @tranvanhuan 

I have reported the following issue to our developer who is currently fixing some issues related to filters on Tuesday. I will ask him to provide me some more information today and I'll get back to you.

Thank you for your patience.

**Comment by AMBudnik** [comment] 2017-06-23 08:55
Hi again @tranvanhuan 

Our developer has checked the subject, and we know that surely there is a bug. However, he was not able to create a quick fix. I am marking this issue as a bug.

**Comment by tranvanhuan** [comment] 2017-06-26 05:36
Hi @AMBudnik, 
Thank you, we are waiting for the fix version.

**Comment by AmartyaMishra** [comment] 2018-06-01 09:21
Any timeline to get a fix for this?

**Comment by AMBudnik** [comment] 2018-06-01 09:27
We usually fix the `regression` bugs first but now the milestone is already closed. Here's a list of issues that we'd like to solve in June https://github.com/handsontable/handsontable/milestone/100

**Comment by AMBudnik** [comment] 2018-07-13 12:02
The issue is no longer replicable in v5.0.0 http://jsfiddle.net/cjzhn396/

**Closed** 2018-07-13 12:03 UTC
Labels: PRO: filtering, Regression, Type: Bug

**Comment by AmartyaMishra** [comment] 2018-07-13 13:06
Thank you for the update.  Will let you know how things looks at our end.
Regards,
Rakesh
