### ISSUE TITLE
Cell editor show the previous value while the table is showing the new value!

### ISSUE THREAD

**Issue by mcevikce** [handsontable/handsontable#2214] opened 2015-03-03 16:00 UTC
I am using handsontable 0.12.6. I have a table with 1 column and 3 rows. Row 3 is the total of the values of row 1 and 2. So when row 1 or 2 is changes, through callback methods I calculate the total of row 3 and update it using table.setDataAtCell() method. This works perfectly. 

Step 1: Type numeric value 10 to row 1 then PRESS ENTER. Cursor moves the row the and editor is opened. Row three is showing 10
Step 2: Type numeric value 15 to row 2 then PRESS ENTER.  Cursor moves to row 3 and row 3 value is 25.
Step 3: I press enter on row 3. Editor open and the value of 10 is showing. When I press enter again the calculated total (25) is now overwritten by 10. Is this a bug or intended functionality?

**Comment by Lukazar** [comment] 2015-03-04 01:50
It would be helpful to see your example code.  If you're able, create something on http://jsfiddle.net/.
Also, is row 3 meant to be editable to begin with?  You could make that cell readOnly.

**Comment by mcevikce** [comment] 2015-03-04 16:58
Thank you for the quick response. I have created a example at http://jsfiddle.net/55nfbc72/8/
After further investigation, I have narrowed down the issue to setting cellProperty.type to numeric. You can see it in my example. If you remove setting the type to numeric then it works fine. Let me know if you need more information.

**Comment by Lukazar** [comment] 2015-03-04 17:39
That is weird.  It appears to be a timing issue.  Because numeric has a default validator the validateChanges is taking just long enough to call the applyChanges that your value is being applied to the datamap AFTER the textarea is prepared with its known (previous) value.

In your example, if you do 10, ENTER, 15, ENTER, ARROW UP, ARROW DOWN, ENTER you'll see you have the proper 25 value.  This is because by reselecting the cell, we're re calling the prepare function which should have the proper data at that point in time.

You can work around this limitation, though it might not be the most elegant solution.  `getData` returns a reference to the tables data source.  Making changes to it directly will update the data without it going through the validation.  I've modified your example here to show this:  http://jsfiddle.net/paaxrzbx/2/

**Comment by mcevikce** [comment] 2015-03-04 18:43
I have tried your suggestion on the example I provided and it works great but when I try this on the actual code it is still a problem. There some some differences between the example table and the actual table that I am experiencing problem with. One difference is that actual table is using array of array as the data source for each cell. I am handling the setting the value by: data[11][colName]['mld_curr_val'] = other_tax;
And I can see the value changed. So I am not sure why still not working.
If we are updating the table data directly, why do we still need to call table.setDataAtCell(update_data);?
Any suggestions will be appreciated.

**Comment by Lukazar** [comment] 2015-03-05 00:32
You do not actually need to call `setDataAtCell`, but you do need to tell the table to render since modifying the reference to the data will not cause that to happen:  http://jsfiddle.net/paaxrzbx/4/

**Comment by mcevikce** [comment] 2015-03-05 14:51
I have updated the code to only set the data directly from the getData() then call table.render(). But some reason still not working. I can see the total row updating when table.render() is called. Is this still a timing issue?

**Comment by Lukazar** [comment] 2015-03-05 17:52
Hmm.  I'm sorry, I'm not really sure beyond the code sample you provided.

**Comment by mcevikce** [comment] 2015-03-05 20:31
Is there a bug # for this issue that I should follow? We would like to get the fix when it is available.

Thank you for your help.

**Comment by Lukazar** [comment] 2015-03-05 20:54
I would think this is the # to follow when it gets picked up.

**Comment by AMBudnik** [comment] 2015-09-25 13:38
Confirmed with 0.18.0 [example](http://jsfiddle.net/55nfbc72/10/)

**Comment by AMBudnik** [comment] 2016-03-16 15:40
in 0.24.1 we're getting `NaN`

**Comment by swistach** [comment] 2017-02-20 13:48
Hi @mcevikce, after 0.30.0 your example should work properly: http://jsfiddle.net/55nfbc72/12/. Could you confirm this?

**Comment by AMBudnik** [comment] 2017-02-27 08:13
I guess we can close this issue as there's no reply for a week.

**Closed by AMBudnik** 2017-02-27 08:13 UTC
Labels: Status: Answered
