### ISSUE TITLE
Misalignment when scroll to right if has fixedColumnsLeft

### ISSUE THREAD

**Issue by bellcliff** [handsontable/handsontable#4202] opened 2017-04-17 19:07 UTC
### Description
Use this demo http://jsfiddle.net/bellcliff/9pj5go16/, try scroll to right, the cell will all shift up
![capture](https://cloud.githubusercontent.com/assets/535209/25100821/a5bbc4d0-237f-11e7-94d5-1386f3dec59c.PNG)

### Steps to reproduce
1. launch jsfiddle demo, http://jsfiddle.net/bellcliff/9pj5go16/
2. scroll table to most right

### Demo
http://jsfiddle.net/bellcliff/9pj5go16/

### Your environment
* Handsontable version: 0.31.2
* Browser Name and version: Chrome 57.0.2987.133
* Operating System: Windows 7

**Comment by AMBudnik** [comment] 2017-04-18 06:42
Hi @bellcliff 

I have added `autoRowSize: true` to settings. Please test it http://jsfiddle.net/v9jfxpqu/ I think that is solves the issue.

**Comment by bellcliff** [comment] 2017-04-18 12:39
Thanks for the quick reply!

I did a try in our project, with autoRowSize true, it still doesn't work, I will try to reproduce it in this demo.

Here are some different 
1. we have a self defined renderer, we call render whenever we update the data
2. we have a max-width css style on td
3. inside each cell, it has some html tags.

**Comment by AMBudnik** [comment] 2017-04-18 13:05
You still face the same issue after adding `autoRowSize: true`? I was also testing it on Chrome 57 on Windows and it looks like this

![gi22f](https://cloud.githubusercontent.com/assets/10757813/25132012/4f154092-2448-11e7-9e74-339354cdc075.gif)

Please take your time to test it and check if the settings are not overwritten anywhere in your code.

**Comment by bellcliff** [comment] 2017-04-18 17:53
Reproduce demo:
http://jsfiddle.net/bellcliff/9pj5go16/7/

The usage here may not correct, due to the content changed inside renderer method.

**Comment by bellcliff** [comment] 2017-04-18 17:55
Through this case, I think, to our case, the solution can be, update data through outside render method, can do not change data inside render method.

**Comment by AMBudnik** [comment] 2017-04-19 11:06
Hi @bellcliff 

Please check if adding [`viewportColumnRenderingOffset`](https://docs.handsontable.com/pro/1.10.2/Options.html#viewportColumnRenderingOffset) option solves the issue. It works for the demo http://jsfiddle.net/zqxzeecj/ 

![66gif](https://cloud.githubusercontent.com/assets/10757813/25177072/d3a5f816-2500-11e7-9c06-f76c9bb1c5b3.gif)

**Comment by bellcliff** [comment] 2017-04-19 11:45
Hi @AMBudnik ,

Does this mean both viewportColumnRenderingOffset and viewportRowRenderingOffset both need to be set as the full size of table?

I did a quick check, if scroll down, the shift happens again, http://jsfiddle.net/bellcliff/9pj5go16/8/

![capture](https://cloud.githubusercontent.com/assets/535209/25178521/177c46f8-24d4-11e7-8709-9a0fd76d6f29.PNG)

**Comment by bellcliff** [comment] 2017-04-19 11:46
Just confirmed, viewportRowRenderingOffset doesn't help when scroll down

**Comment by AMBudnik** [comment] 2017-04-19 11:56
I am not able to get the same effect like you did 

![image](https://cloud.githubusercontent.com/assets/10757813/25178855/d666c63c-2507-11e7-8cd2-86a772bd193b.png)

but basically, rows and columns can misalign while they have unusual height/width and do not have headers (for columns or rows). So `viewportColumnRenderingOffset` / `viewportRowRenderingOffset` is more like a workaround.

**Comment by bellcliff** [comment] 2017-04-19 12:00
Try scroll down to the bottom on this demo, http://jsfiddle.net/bellcliff/9pj5go16/8/

**Comment by AMBudnik** [comment] 2017-04-19 12:31
Still, I do not get the same effect in Chrome or Firefox. However, the issue is gone when you add `viewportRowRenderingOffset`?

**Comment by bellcliff** [comment] 2017-04-19 12:33
Yes, I believe we can close the ticket now, thank you @AMBudnik !

**Comment by AMBudnik** [comment] 2017-04-19 12:37
Great. Thanks for the confirmation. I am closing this issue.

**Closed by AMBudnik** 2017-04-19 12:37 UTC
Labels: Status: Answered

**Comment by chearon** [comment] 2017-05-08 16:38
I think this issue is the same as #2218 and possibly several others. Just wanted to post my solution somewhere for anyone who might be looking. IMO this is better than `viewportColumnRenderingOffset` for larger datasets:

Handsontable only checks the height of header cells once, and when it does so, it only checks rendered headers, not ones that are out of view. 

So any header cells not visible when the table is first rendered that are taller than the cells at render time will cause this offsetting issue when scrolled into view.

Handsontable should be remembering which cells it hasn't checked. I didn't get familiar enough with the code to make a PR but here's my solution (assuming `hot` is an instance of `Handsontable`):

```javascript
var maxRenderedColumn = -1;

hot.addHook('afterScrollHorizontally', function () {
  var renderedColumns = hot.view.wt.wtTable.getRenderedColumnsCount();
  var column = hot.view.wt.wtTable.columnFilter.renderedToSource(renderedColumns - 1);
  var renderer;

  // Optimization: we only need to do the operations below if they are
  // columns not seen before
  if (column <= maxRenderedColumn) return;

  maxRenderedColumn = column;

  renderer = new WalkontableTableRenderer(hot.view.wt.wtTable);

  // Taken from WalkonTableRenderer#render(). Avoids having to call the whole fn
  renderer.columnHeaders = renderer.wot.getSetting('columnHeaders');
  renderer.columnHeaderCount = renderer.columnHeaders.length;
  renderer.rowHeaders = renderer.wot.getSetting('rowHeaders');
  renderer.rowHeaderCount = renderer.rowHeaders.length;

  // Delete the cache and force HOT to recalculate the heights of the column
  // headers.
  renderer.wot.wtViewport.hasOversizedColumnHeadersMarked['master'] = false;
  renderer.markOversizedColumnHeaders();

  // Re-render the top left corner
  renderer = new WalkontableTableRenderer(hot.view.wt.wtOverlays.topLeftCornerOverlay.clone.wtTable)
  renderer.adjustColumnHeaderHeights();
  hot.view.wt.wtOverlays.topLeftCornerOverlay.resetFixedPosition();
});
```
