### ISSUE TITLE
angular ,tabs component , display:none , handsontable can't be render 

### ISSUE THREAD

**Issue by fingercoder** [handsontable/handsontable#7444] opened 2020-12-22 02:12 UTC
### Description

Handsontable display:none It can not be used normally after wrapping,
### Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/29332312/102840336-98ab7780-443d-11eb-8fdc-dd00b8ad9569.png)
![image](https://user-images.githubusercontent.com/29332312/102840368-ad880b00-443d-11eb-8638-c683917e3b53.png)

2.
![image](https://user-images.githubusercontent.com/29332312/102840425-d1e3e780-443d-11eb-96b9-d8078591e3c4.png)
3.
![image](https://user-images.githubusercontent.com/29332312/102840776-8b42bd00-443e-11eb-85cc-71f8b3e14628.png)

### Your environment
* Handsontable version:8.2.0
* Browser Name and version:chrome (87.0.4280.88)
* Operating System:macpro
* Frame:angular7.0

**Comment by AMBudnik** [comment] 2020-12-22 09:21
Hi @fingercoder 

does it help when you define height/width for the Handsontable container?

**Comment by fingercoder** [comment] 2020-12-22 10:15
> Hi @fingercoder
> 
> does it help when you define height/width for the Handsontable container?

yes, this is my configation    

When you use display: none and  display: block  to control the hiding and display of this table，ht_clone value will be 0

**Comment by AMBudnik** [comment] 2020-12-22 10:26
Could you send me a demo where I will be able to replicate the issue on my email support@handsontable.com, @fingercoder ?

**Comment by fingercoder** [comment] 2020-12-23 01:34
> Could you send me a demo where I will be able to replicate the issue on my email [support@handsontable.com](mailto:support@handsontable.com), @fingercoder ?

**Comment by fingercoder** [comment] 2020-12-23 01:39
> Could you send me a demo where I will be able to replicate the issue on my email [support@handsontable.com](mailto:support@handsontable.com), @fingercoder ?

Excuse me, can you give me a demo link

**Comment by AMBudnik** [comment] 2020-12-23 09:12
Hey @fingercoder 

I've made a sample demo using Angular Material and Handsontable and even though I was able to run render() to show something more than the headers.

Without render
![material-tab-slider](https://user-images.githubusercontent.com/10757813/102979782-d7f1cb00-4506-11eb-9f55-7bf2b48d3236.gif)


With render
![material-tab-slider-rerender](https://user-images.githubusercontent.com/10757813/102979789-da542500-4506-11eb-9943-7a84419ce7bf.gif)

The table does not scroll correctly
![material-scroll-issue](https://user-images.githubusercontent.com/10757813/102979946-17b8b280-4507-11eb-9643-7bc8a9a3ad98.gif)

It seems that some of the CSS settings of Material are not cooperating well with what's needed in Handsontable.
I will check it once again after the Christmas break.

**Comment by fingercoder** [comment] 2020-12-23 10:48
> Hey @fingercoder
> 
> I've made a sample demo using Angular Material and Handsontable and even though I was able to run render() to show something more than the headers.
> 
> Without render
> ![material-tab-slider](https://user-images.githubusercontent.com/10757813/102979782-d7f1cb00-4506-11eb-9f55-7bf2b48d3236.gif)
> 
> With render
> ![material-tab-slider-rerender](https://user-images.githubusercontent.com/10757813/102979789-da542500-4506-11eb-9943-7a84419ce7bf.gif)
> 
> The table does not scroll correctly
> ![material-scroll-issue](https://user-images.githubusercontent.com/10757813/102979946-17b8b280-4507-11eb-9643-7bc8a9a3ad98.gif)
> 
> It seems that some of the CSS settings of Material are not cooperating well with what's needed in Handsontable.
> I will check it once again after the Christmas break.

bro, thank you for tracking this problem. I found that I couldn't scroll when using the material tabs component,So I can render normally by using the lazyload function of tab, but the whole table will not be displayed,So I read the tabs source code of material, and through making the tabs component myself, I found that when using display: none and display: black, there was a problem with the rendering of the table. So you can directly try to use display to control the hiding and displaying of tables，I guess it's the rendering function of the table，Happy Christmas to you at the end

**Comment by AMBudnik** [comment] 2020-12-23 11:18
True. Doing what they've proposed

> Tab contents can be lazy loaded by declaring the body in a ng-template with the matTabContent attribute.

did the job.

![material-lazy-loading](https://user-images.githubusercontent.com/10757813/102991102-d92bf380-4518-11eb-8fd3-e313864037d2.gif)

Cool! Thanks for sharing @fingercoder and Happy Christmas 🎄 !

**Comment by fingercoder** [comment] 2020-12-23 11:36
Oh, bro, this bug can't be closed yet,The real problem is not using lazyload, 
Please take a closer look at the tab switch

**Comment by AMBudnik** [comment] 2020-12-23 11:43
>Please take a closer look at the tab switch

What happens to the tab switch? Besides the fact that my table scroll is glued to right (`right: 0` for the tab space), I do not see anything suspicious.

**Comment by fingercoder** [comment] 2020-12-23 11:56
Please use display: none and display: block to control the hiding and showing of handsontable. Bro, just like switching tabs, thank you very much

**Comment by AMBudnik** [comment] 2020-12-23 13:10
When I use `display: none` on the `.handsontable` className is basically the same as I would add `className: 'hide'` to my Handsontable settings.
As a result, I am left with headers, and the cells are gone.

![image](https://user-images.githubusercontent.com/10757813/102998032-a25cda00-4526-11eb-83c2-9ac53ff1ef3a.png)

But I do not know what could be a scenario for having tabs and at the same time keeping Handsontable on `display: none`. 

Can you share the screen recording/snapshot of (if it's not the same as mine cell-less table)
> You will find strange phenomena.

**Comment by fingercoder** [comment] 2020-12-23 13:41
https://user-images.githubusercontent.com/29332312/103001240-888fb700-4567-11eb-8d6a-1b0f4e4e68df.mp4

**Comment by AMBudnik** [comment] 2021-01-04 14:09
Hi @fingercoder 

It's hard for me to replicate the same results as yours. Besides the already defined issue with settings up fixed height and then using lazy loading I do not know is there something more we can do.
Have you made any updated to that project since the last comment?

**Comment by wojciechczerniak** [comment] 2021-01-04 14:28
`display: none` is a common problem with JS components that need container size to place all elements correctly. We have a `refreshDimensions()` method for that case.

Duplicate of #5322, see my comment https://github.com/handsontable/handsontable/issues/5322#issuecomment-472367150, you can use `setTimeout`, `MutationObserver` or `selectedTabChange` event form Angular Material tabs API.

**Comment by fingercoder** [comment] 2021-01-05 12:11
> Hi @fingercoder
> 
> It's hard for me to replicate the same results as yours. Besides the already defined issue with settings up fixed height and then using lazy loading I do not know is there something more we can do.
> Have you made any updated to that project since the last comment?

use ng-if, render dom tree again,

**Comment by AMBudnik** [comment] 2021-01-08 08:55
Ahh yes. Thank you @wojciechczerniak I know that we had a corresponding issue on the GH issue board.
@fingercoder we will keep #5322 as the issue describing the mentioned behavior but you can also leave your comment there. Nevertheless, I will update this topic when anything changes to #5322

**Closed by AMBudnik** 2021-01-08 08:55 UTC
Labels: Core: alignment/height/width, Type: Bug

**Comment by AMBudnik** [comment] 2022-12-14 13:00
Hi @fingercoder 

we just fixed the origin issue at https://github.com/handsontable/handsontable/issues/5322

Could you please update to Handsontable v12.3.0 and tell me if the issue still remains?
