### ISSUE TITLE
When I click (with a single click) on an editable cell, instead to remain just selected, cell enter in editable mode, value in the cell disappear and cursor start blinking

### ISSUE THREAD

**Issue by frahub** [handsontable/handsontable#3575] opened 2016-06-14 12:29 UTC
I create this issue to report the same problem described here: https://github.com/handsontable/handsontable.com-v1/issues/3
because I've the same problem, but I think that this is the right project where it should be opened.
Please delete this, if I'm wrong.

I cut&paste below the original issue description and integrate it with my infos:

I have the bug also in the table that is in http://handsontable.com/ main page.
When I click (with a single click) on an editable cell, instead to remain just selected, cell enter in editable mode, value in the cell disappears and cursor start blinking.
So, I'm not able to drag the cell to copy the value in others cells, or just copy the value from the selected cell.
With both Firefox and with Chrome I had the error on my computer.
I tried with many computers: working properly for some computers, but not others.
Let me know if I can help you providing some other information.

Reproduced on Google Chrome Version 51.0.2704.84 m, Firefox 47.0 and IE 11.

**Comment by AMBudnik** [comment] 2016-06-15 14:07
Hi @frahub that issue before is related to the main page where currently there's no grid and I wasn't able to reproduce it with the other demo, for example the numeric one: https://docs.handsontable.com/pro/1.4.1/demo-numeric.html

Can you guide me on how to reproduce the behavior?

**Comment by frahub** [comment] 2016-06-15 15:02
Hi @AMBudnik. Thank you for your answer. I really appreciate your interest.
I can reproduce the bug here: https://handsontable.com/examples.html?headers and also in the numeric demo you linked above.
The way to reproduce is:
* click on a cell and wait some seconds (from 2 to 30) 
sometimes automatically and without doing other clicks the cell switch from selected state to edit mode and the text inside it disappears.
The bug can be reproduced only on some environment and I couldn't understand why. For example I've two distinct pc with same so, browser version, plug-ins, etc. in one I can reproduce the bug in the other no.
I'm doing tests on every notebook and pc available to me and the only fact is that:
* where the bug can be reproduced, it can be reproduced always with every browser and every time
* where the bug cannot be reproduced, it **never** can be reproduced
(I tried also in browser incognito mode, same result).
So it seems to be related also on the machine, but I really cannot understand why.
You say that you cannot reproduce on the numeric demo, so I think that you will never reproduce it using the same machine. So if you could, in order to reproduce it, I think you should use another machine.
Thank you for reading. Ask me if I can help you to reproduce the bug or investigate on it in the env where I can reproduce it.

**Comment by AMBudnik** [comment] 2016-06-16 07:52
thanks for additional details @frahub this sounds serious and also very mysterious.
I gave every cell type a minute (on the numeric demo) on every browser that I have. I'll test it on other machines also.

**Comment by AMBudnik** [comment] 2016-06-16 08:03
We've just tested the case with our devs on all machines that we have and the issue doesn't occur.
Can you share the metrics of the device effected with this bug? A gif/video of it should also come in handy.

**Comment by frahub** [comment] 2016-06-16 13:25
Hi @AMBudnik. Thanks for your time and your attempts to reproduce the bug.
I reproduced the bug on 4 notebook (I tried to reproduce it on 15).
Debugging I noticed that the problem is that when I click the mouse to select a cell, a keydown event is fired. This causes the function beginEditing to be called and this causes the bug.
Using monitorEvents of "Chrome Developer Tools" I verified that keydown events are fired every time that I click with the mouse and I suppose that it is wrong.
I trying to understand why it happens, I verified that it doesn't depend on hardware (mouse/touchpad) or drivers.  
I'll try to create a video and post it in another comment.

**Comment by frahub** [comment] 2016-06-16 15:46
@AMBudnik, if this can help: when I click the mouse, the keyCode of the keydown event is always 255

**Comment by AMBudnik** [comment] 2016-06-20 09:48
so it can have something to do with http://stackoverflow.com/questions/22290526/i-always-get-a-255-value-as-keycode-of-these-characters-how-to-retrieve-the-r
I guess it can be a valuable trace but it does not help us to reproduce it so we are still two steps behide the bug.

**Comment by frahub** [comment] 2016-07-01 13:41
Hi @AMBudnik. Sorry for the delay in my response, but I did a long on investigation on this problem and it seems to be a problem related to the operating system that fires keydown events without interaction with the keyboard. These keydown events (fired without the keypress and keyup events) cause the strange behavior of the table. As thing stand I think that this issue could be closed as "not-a-bug". Thank you for your support and your attention.

**Comment by AMBudnik** [comment] 2016-07-01 13:43
and thank you for the effort and your investigation.

Have a nice weekend @frahub

**Comment by frahub** [comment] 2016-07-01 13:45
You too @AMBudnik

**Comment by Jefroz** [comment] 2018-09-28 18:04
I experienced this as well resolved by adding the following to documentKeydown

if(event.key == "Unidentified"){
        	event.stopImmediatePropagation();
            	event.preventDefault();
            	event.stopPropagation();
        }
might be overkill, but it worked

**Comment by AMBudnik** [comment] 2022-03-11 07:36
We got 3rd question about this issue. I will reopen it for further investigation.

**Comment by AMBudnik** [comment] 2022-05-27 13:25
@aninde could you check if you have the same issue as the developers above? I was not able to replicate it in any of my systems/projects.

**Comment by aninde** [comment] 2022-08-04 12:57
I couldn't reproduce it. Tested on
current Chrome  103.0.5060.134 / macOS 12.5 / MacBook Pro (Retina, 15-inch, Mid 2015) / english language -  touchpad and magic mouse
current Chrome 103.0.5060.134 / Windows 10 / Lenovo Z50 (Intel Core i7) and Asus Tuf Gaming A15 (AMD Ryzen 7 5800H) - touchpad and mouse
Chrome 51 / macOS Monterey and Windows 10 & 8 via Browserstack - touchpad and magic mouse
Firefox 41 / / macOS Monterey and Windows 10 & 8 via Browserstack  - touchpad and magic mouse 
on https://handsontable.com/docs/4.0.0/demo-numeric.html
We need more information about the environment configuration - what computer, what OS version to reproduce.

**Comment by AMBudnik** [comment] 2022-08-09 06:12
@aninde I will close this issue as there are no further details on the case and we found everything working correctly.

**Closed by AMBudnik** 2022-08-09 06:12 UTC
Labels: Type: Bug, Type: Demo needed
