### ISSUE TITLE
formulas not init with nestedRows

### ISSUE THREAD

**Issue by evvabbaran** [handsontable/handsontable#4154] opened 2017-03-27 06:44 UTC
### Description
When using nestedRows plugin formulas not working on init.

### Steps to reproduce
1.formulas not working on init
2.click formulas cell change formula and click enter
3.now formulas calculated successfull

### Demo
http://jsfiddle.net/evvabbaran/Lce36k8t/

### Your environment
* Handsontable version: 1.10.1
* Browser Name and version: Windows 10
* Operating System: 56.0.2924.87

**Comment by AMBudnik** [comment] 2017-03-27 11:45
Thank you for sharing @evvabbaran 

NestedRows is in alpha version and it does not work with most plugins like sorting, filtering or merging, however, we will get back to this issue after switching to a beta version.

**Comment by navindharmaraj** [comment] 2017-12-06 05:19
Any update on this?

**Comment by AMBudnik** [comment] 2017-12-11 09:10
Hi @navindharmaraj 

We will be updating formulas in 2018. Now, both - `nestedRows `and `Formula Support` should be considered as experimental features/betas.

**Comment by AMBudnik** [comment] 2018-01-17 13:08
Updated demo (v 1.15.0) http://jsfiddle.net/ncw2xL19/

**Comment by navindharmaraj** [comment] 2018-01-18 08:26
Hi,

Looks great, We found a workaround for this earlier will update the plugin
to the latest version. I still find that dragging only copy the value and
not the formula.


On Wed, Jan 17, 2018 at 6:38 PM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment] 2018-01-18 11:12
Hi @navindharmaraj 

we are planning to add the ability to copy the formula instead but firstly we will refactor the code (planned for the second part of 2018). It is a huge project that will cost us a lot of time, planning and an external dev team.

**Comment by GrononS** [comment] 2018-07-26 20:53
This appears to still be an issue in version 5. I updated the example with the latest version here:
[http://jsfiddle.net/ncw2xL19/5/](http://jsfiddle.net/ncw2xL19/5/)

and the formula _=SUM(2*4)_ still appears to be unparsed.

**Comment by AMBudnik** [comment] 2018-07-27 08:37
Thank you for the feedback @GrononS

**Comment by AMBudnik** [comment] 2020-05-14 09:49
@GrononS the issue is fixed in 8.0.0.-beta2-rev1 http://jsfiddle.net/eoaw57s8/
and stay fixed in rev5 http://jsfiddle.net/38r4s9cq/
![Zrzut ekranu 2020-05-14 o 11 47 18](https://user-images.githubusercontent.com/10757813/81919874-ae6bdb00-95d8-11ea-9c84-035b4488871b.png)

@evvabbaran your demo was deleted (shows 404). Can you check the demo above?

**Comment by AMBudnik** [comment] 2020-07-16 10:15
Hi @evvabbaran 

I have good news! We've just released 8.0.0-beta2 that fixes the following issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

@navindharmaraj @GrononS please share your feedback.

**Comment by pnowak** [comment] 2020-07-28 13:24
The issue is still fixed - https://jsfiddle.net/ns1fgrkz/

**Comment by AMBudnik** [comment] 2020-08-06 07:50
Hi @evvabbaran yesterday we published the stable version Handsontable 8.0.0.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable

Release Notes https://github.com/handsontable/handsontable/releases

**Closed by AMBudnik** 2020-08-06 07:50 UTC
Labels: Formulas, Nested rows, Type: Change
