### ISSUE TITLE
Old CSS classes are not removed after updateSettings

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6575] opened 2019-12-17 08:38 UTC
### Description

When the Handsontable has defined `className` property in the initialization object that CSS class later is not removed from the DOM after updating that property through `updateSettings()` method. This behavior is implemented in the core (https://github.com/handsontable/handsontable/blob/master/src/core.js#L1798) but doesn't work as it suggests. 

### Steps to reproduce

1. Go to https://jsfiddle.net/dver40s6/;
2. After calling `updateSettings` with new `className` value an old CSS class is not removed from the DOM.

### Demo

https://jsfiddle.net/dver40s6/

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: any
* Operating System: any

**Comment by wojciechczerniak** [comment] 2019-12-17 10:47
I think that @pnowak was working on this in  #6425

**Comment by wojciechczerniak** [comment] 2020-07-02 11:54
Fixed in #6425 and #6425. Adding to v8 release

https://jsfiddle.net/L9rmsyo2/

**Comment by AMBudnik** [comment] 2020-08-05 13:35
The issue is fixed in Handsontable v8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage anyone to test the new version and leave some feedback.

**Closed by AMBudnik** 2020-08-05 13:35 UTC
Labels: Core: handsontable, Core: update settings, Guess: few hours, Status: Released, Type: Bug
