### ISSUE TITLE
Nodes that hold autocomplete markup are not cleaned up

### ISSUE THREAD

**Issue by betalb** [handsontable/handsontable#4503] opened 2017-09-07 12:03 UTC
### Description

After opening and closing dropdown in autocomplete cell type, nodes with class `handsontableInputHolder` are not removed from DOM and keep polluting. This issue can be reproduced easily on documentation page https://docs.handsontable.com/0.34.1/demo-dropdown.html

### Steps to reproduce

1. Open https://docs.handsontable.com/0.34.1/demo-dropdown.html
2. Open web developer tools
3. Execute `document.querySelectorAll('.handsontableInputHolder').length`, record the number
4. Open any dropdown several times on the same node
5. Go to step 3, see that number keeps increasing after every iteration

### Your environment
* Handsontable version: 0.34.1
* Browser Name and version: Version 60.0.3112.113 (Official Build) (64-bit)
* Operating System: macOS Sierra, version 10.12.6

**Comment by AMBudnik** [comment] 2017-09-11 13:21
Thank you for sharing your investigation result @betalb 
We need to check it.

**Comment by swistach** [comment] 2017-12-12 16:30
Hi @betalb,
you are right! Thank you!
This issue occurs in each editors based on `HandsontableEditor`.

**Comment by AMBudnik** [comment] 2018-01-31 10:13
Stays the same in v 0.35.1

**Comment by krzysztofspilka** [comment] 2018-04-05 09:52
This will be fixed within the project that is to replace the current context menu, dropdown menu, autocomplete etc. with the Handsontable-free solution.

**Comment by budnix** [comment] 2018-05-23 09:08
While developing another issue I've spotted similar problems with editors. I don't want to fix this issue while developing another task so if anyone will start developing this issue, changes below should resolve the bug:
 * https://github.com/handsontable/handsontable/blob/master/src/editors/index.js#L56, replace `instances = {};` to `instances[this.guid] = null;`
 * Add tests.

**Comment by swistach** [comment] 2018-06-01 11:02
#4551 should resolve this issue.

**Comment by AMBudnik** [comment] 2018-08-17 11:05
The issue is no longer replicable. I have tested v 5.0.1. within this demo https://docs.handsontable.com/5.0.1/demo-dropdown.html

**Closed by AMBudnik** 2018-08-17 11:05 UTC
Labels: Cell type: autocomplete / dropdown / handsontable, Type: Bug
