### ISSUE TITLE
Method alter does not support null as an index as stated in the documentation

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3617] opened 2016-06-28 14:18 UTC
Meta data, e.g. regarding the cells' validation is being moved to the wrong cells if the new rows are added.

**Steps to reproduce the problem:**
1. Go to http://jsfiddle.net/hx54mcrq/1/
2. Click "Add 10 rows"

Result: the meta data is being attached to the wrong cells

:information_source:

> Handsontable 0.26.0
> Windows 8.1
> Chrome

**Comment by AMBudnik** [comment] 2016-06-28 14:26
maybe the solution will also work for (https://github.com/handsontable/handsontable/issues/3296) - same situation for borders.

**Comment by jansiegel** [comment] 2016-09-16 10:24
I'm not sure if providing `null` to the `alter` method is supported. If a number is provided, the cell meta shifting seems to work fine.

Borders seem to not work properly though, but it's reported in #3617.

**Comment by AMBudnik** [comment] 2018-01-22 12:37
The issue remains the same in version 0.35.0

**Comment by AMBudnik** [comment] 2018-03-20 10:52
Version 1.18.1 (CE 0.38.0)

![GIF.gif](https://images.zenhubusercontent.com/5a96b5784b5806bc2bc8c7df/4a2ceadb-d700-470d-bef7-f6dc23280fbd)

**Comment by wszymanski** [comment] 2018-03-30 14:52
Providing `null` to the `alter` method isn't supported. After calling the `alter` method with `undefined` everything works properly: http://jsfiddle.net/qcdzbwgd.

**Comment by wojciechczerniak** [comment] 2018-05-14 13:44
According to documentation `null` should be supported: "Insert new row(s) above the row with a given index. If index is **null or undefined**, the new row will be added after the last row." Source: https://docs.handsontable.com/pro/2.0.0/Core.html#alter

I'm changing the subject because the issue is not about cell meta.

**Comment by wojciechczerniak** [comment] 2019-02-20 08:36
Duplicate of #4448

**Closed by wojciechczerniak** 2019-02-20 08:36 UTC
Labels: Type: Bug
