### ISSUE TITLE
[Urgent] Filtering with custom search input does not find anything on the lowercase letter of Turkish character capital İ

### ISSUE THREAD

**Issue by senniksoft** [handsontable/handsontable#6095] opened 2019-07-09 10:15 UTC
### Description
The problem occurs when supplied data to handsontable contains Turkish Capital İ letter, typing lowercase version of it to search input does not find anything. is it a bug? or any workaround?
Thank you. I am also ready to publish Turkish language translation.

### Steps to reproduce

1.  Type inanç or ibrahim into the search input. 

### Demo with a set of name and surnames
https://jsfiddle.net/fatihsennik/k1c2wezd/18/

### My environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome Latest
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2019-07-09 12:46
Thank you for sharing the bug scenario, @senniksoft 

You're right, we do not 'understand' all the letters or get `false` in the `toLowerCase()` check. I can see a similar case mentioned in [SO](https://stackoverflow.com/questions/1850232/turkish-case-conversion-in-javascript).

> I am also ready to publish Turkish language translation.

That would be more than great to have! [We don't have Turkish yet](https://github.com/handsontable/handsontable/tree/master/languages).

**Comment by senniksoft** [comment] 2019-07-23 08:19
Hi Dear Aleksandra. Thank you for the hints, doing this code solves the problem at the moment.
```
{
                        key: "onInput",
                        value: function onInput(event) {
                            var value = event.target.value.toLowerCase();
                            var filteredItems;
                            let value_girilen = value.replace(/I/g, "ı").replace(/i̇/g, "i");
                            let girilen_lowered = value_girilen.toLocaleLowerCase('tr-TR');
                            if (value === '') {
                                filteredItems = (0, _toConsumableArray2.default)(this.items);
                            } else {
                                filteredItems = (0, _array.arrayFilter)(this.items, function (item) {
                                    let tablo_dataRow = item.value.replace(/I/g, "ı").replace(/i̇/g, "i");
                                    let gelen_lowered = tablo_dataRow.toLocaleLowerCase('tr-TR');
                                    return "".concat(gelen_lowered).indexOf(girilen_lowered) >= 0;
                                });
                            }

                            this.itemsBox.loadData(filteredItems);
                        }
                        /**
                         * 'keydown' event listener for input element.
                         *
                         * @private
                         * @param {Event} event DOM event.
                         */

                    }
```

**Comment by AMBudnik** [comment] 2019-07-23 09:21
Great to hear. Thank you for the update.

**Comment by AMBudnik** [comment] 2021-01-22 10:44
We get the same result using v8.2.0 https://jsfiddle.net/handsoncode/b2xmfdek/
I've simplified the demo as the issue is also replicable then we just run the default

```js
dropdownMenu: true,
filters: true
```

and take the following scenario

1. Open dropdown menu _filter by condition_ list
2. Choose _Contains_
3. Type `İnanç` (it works well)
4. Remove that value and type `inanç` instead (it does not work even though the filter is not said to be case-sensitive)

![turkish](https://user-images.githubusercontent.com/10757813/105481337-309fb980-5ca7-11eb-868f-1cdb8d198f81.gif)

**Comment by wszymanski** [comment] 2021-09-29 09:33
Probably also other part of Handsontable need changes. We have `equalsIgnoreCase` helper which is used by the checkbox renderer for finding elements which match to template. Also plugins such as `Search`, `ColumnSorting` and more places in the `Filters` plugin use `toLowerCase` method. From my perspective it should be changed to `toLocaleLowerCase` with locale handled as function's argument.

As it is related to a few places in the code, I'd suggest some generic setting for locale. I'm not sure whether it will be good to use currently existing `language` property. I'll discuss it with @wojciechczerniak.

**Comment by aninde** [comment] 2021-11-15 08:23
This issue will be fixed by v11. 
Demo https://jsfiddle.net/aninde/0gc3zm27/.

**Comment by AMBudnik** [comment] 2021-11-18 08:00
Hi @senniksoft 

I am happy to announce that this issue was fixed and released yesterday under version 11.
If you would like to read more about the newest release here’s everything listed and described https://github.com/handsontable/handsontable/issues/8949

**Closed by AMBudnik** 2021-11-18 08:00 UTC
Labels: Type: Bug, Status: Released, Filtering
