### ISSUE TITLE
[8.3.0+] "ERROR TypeError: this.indexesSequence.addLocalHook is not a function" in Prod Module

### ISSUE THREAD

**Issue by yatinagrawal** [handsontable/handsontable#7577] opened 2021-02-11 08:08 UTC
The handsonTable works fine in the angular serve mode.

However, when I build prod module,  in the build dist, it showed "ERROR TypeError: this.indexesSequence.addLocalHook is not a function".

Environment:
Angular version:10.1.3
Handsontable version:8.3.0
Wrapper version:6.0.1
Browser: FireFox  & Chrome
Operating System:ubuntu 20.04

**Comment by JHAvanGestelDN** [comment] 2021-02-25 15:19
Experienced the same issue. An upgrade to Angular 11 fixed the problem.

**Comment by swistach** [comment] 2021-02-25 15:35
@yatinagrawal, @bioShaun, @JHAvanGestelDN
We investigated this issue. I can confirm we reproduced the error. However, it might be caused by too aggressive `dead-code elimination` by Angular's build tools. For some reasons, Angular@10 marks most of the Handsontable code as unnecessary. It's strictly related to our recent changes in the modularisation project.
Since v8.3.0, we use `exports` and `sideEffects` fields in our `package.json`. These fields define which parts of the library end-developer might import separately and what should not be optimised by bundlers.

For now, we have no other solutions than downgrade Handsontable to v8.2 or upgrade Angular to v11.

**Comment by rapelt** [comment] 2021-02-25 22:45
I downgraded to v8.2 and that worked perfectly. Thank you.

**Comment by AMBudnik** [comment] 2022-09-28 12:16
As @JHAvanGestelDN the issue no longer exists if we use Angular 11
Tested with @adrianszymanski89

**Comment by jansiegel** [comment] 2022-11-28 13:23
I re-checked the problem, and I agree with https://github.com/handsontable/handsontable/issues/7577#issuecomment-785990837.

The problem seems to occur only in Angular 10 (I also tested versions 9 and 11) and only if using `ng build` with the `--prod` flag.

As the issue seems to be caused by the [`@angular-devkit/build-optimizer`](https://www.npmjs.com/package/@angular-devkit/build-optimizer) package which is no longer maintained and marked as deprecated with an annotation:
> This package is deprecated and should not be used. It has always been experimental (never hit 1.0.0)

I think it would be best to:
1. Update Angular to 11+
2. If that's not possible, either:
   - downgrade Handsontable to `8.2`
   - or disable Angular's build optimizer by setting up a flag: `ng build --prod --buildOptimizer=false` (which results in a bigger `dist` being generated)

cc: @warpech

**Comment by warpech** [comment] 2022-12-04 23:06
I agree this should be closed as Won't fix, because this is a problem in Angular 10 (tracked here: https://github.com/angular/angular-cli/issues/11439), not in Handsontable, and can be solved with the solutions listed in the above comment.

**Comment by AMBudnik** [comment] 2022-12-05 07:38
Thank you for feedback @warpech @jansiegel 

I am closing this issue (and will update users on forum).

**Closed by AMBudnik** 2022-12-05 07:38 UTC
Labels: bug, Regression, Wontfix, Angular
