### ISSUE TITLE
colWidth will be wrong when inserting or removing column after resized, rowHeight too.

### ISSUE THREAD

**Issue by mapletower** [handsontable/handsontable#4666] opened 2017-12-12 02:34 UTC
### Description
After stretching the columns of the table, inserting or removing column on the stretched column will cause the width of the remaining columns to be wrong, not to maintain the original width, but to inherit the width of the deleted columns.
### Steps to reproduce
1. resize column.
2.  inserting or removing column on it.
### Demo
http://jsfiddle.net/95fg1qmp/1/

### Your environment
* Handsontable version: latest
* Browser Name and version: chrome latest
* Operating System: Ubuntu 16.04

**Comment by mapletower** [comment] 2017-12-12 03:33
like this[gif link](https://send.firefox.com/download/0e2e0520a1/#4845SgXjumIMDUlNztoU1Q)

**Comment by mapletower** [comment] 2017-12-12 10:17
![xxx-iloveimg-compressed](https://user-images.githubusercontent.com/19504799/33878985-fb77f264-df67-11e7-9978-0a682320c07e.gif)

**Comment by AMBudnik** [comment] 2017-12-12 13:03
Thank you for sharing this example and the video.

You're right. I have replicated the issue.

**Comment by AMBudnik** [comment] 2018-04-27 10:11
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment] 2018-08-24 09:17
Works the same in v 5.0.1

**Comment by AMBudnik** [comment] 2019-07-17 12:29
Still replicable in v `7.1.0` http://jsfiddle.net/handsoncode/ahc3n5L7/ the width of the stretched columns is inherited by the new column and the stretch of the origin column is turned to default

**Comment by aninde** [comment] 2019-09-18 15:03
Unfortunately, version `8.0.0-rc1` partially fixed the described issue. 
It fixed only `removing` the resized column and  `inserting it to left` from the resized column with index >0. It is not fixed inserting to the right from the resized column and inserting to the left, when the resized column is the first one, with index 0.  
it is interesting that

**Fixed v. `8.0.0-rc1`**
1. Removing resided column. Works good, even with a big amount of colums and a few selected, resized and removed columns.
![8 0 0 rc1-removing 2019-09-18 16_48_25](https://user-images.githubusercontent.com/30186818/65159317-2c6ce780-da34-11e9-9d00-72237369668d.gif)

2. Inserting left from resided column with index >0.
![8 0 0rc1-leftsmall 2019-09-18 16_24_45 2019-09-18 16_26_11](https://user-images.githubusercontent.com/30186818/65158913-8de08680-da33-11e9-91f5-339e6ce9467a.gif)

**Not fixed v. `8.0.0-rc1`**
1. Inserting left from the resized column at index 0 (first column in the table). The newly inserted column inherited the resized width. This is also repeated in version 7.1.1 and previous.
![8 0 0rc1 - insert-left-before-first 2019-09-18 16_21_53](https://user-images.githubusercontent.com/30186818/65158926-933dd100-da33-11e9-8d57-71c2e8525137.gif)

3. Inserting right from the resized column. Same as above. 
 ![8 0 0rc1-rightsmall 2019-09-18 16_23_16 2019-09-18 16_29_23](https://user-images.githubusercontent.com/30186818/65158878-7e613d80-da33-11e9-8628-b2f287ff587b.gif)

At version 7.1.1 bug is the same as in the oldest demo.

**Demo**
ver. 7.1.1 http://jsfiddle.net/aninde/3rjxbLw2/
ver. 8.0.0-rc1 http://jsfiddle.net/aninde/n3op2L19/

**Environment**
Handsontable version:8.0.0.rc
Browser Name and version: Google Chrome version 76.0.3809.100, but same at any other one
Operating System: macOS Mojave 10.14.6

@wszymanski I don't want to sadden you, but can you investigate this issue?

**Comment by wszymanski** [comment] 2019-09-19 14:13
Good job 👍 Its bug of course. I will check it further.

**Comment by wszymanski** [comment] 2019-09-23 07:45
It should work from now: http://jsfiddle.net/wojciech/zo7fcbuq.

**Comment by aninde** [comment] 2019-09-23 07:58
It works, great job @wszymanski.

**Demo**
ver. 8.0.0-rc1 (after changes) http://jsfiddle.net/aninde/5dg971ar/

**Comment by AMBudnik** [comment] 2019-11-15 08:51
@mapletower 

we pushed a new version that fixed the issue. It's beta so we do not recommend using it on the production but we're working on a stable version so any feedback appreciated :)
Updated demo http://jsfiddle.net/zhfw05vd/

**Comment by AMBudnik** [comment] 2020-08-07 08:11
Hi @mapletower We've published a new stable version - Handsontable v 8.0.0.
Updated demo http://jsfiddle.net/vgp50eud/

**Closed by AMBudnik** 2020-08-07 08:11 UTC
Labels: Resizing, Type: Bug
