### ISSUE TITLE
getSettings method returns empty object.

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4417] opened 2017-07-19 09:42 UTC
I'm not sure how this method should work, but it returns an empty object for me:
![image](https://user-images.githubusercontent.com/710513/28360915-9a22398a-6c7f-11e7-98c5-889c47abfff6.png)
Is there any other method that I can use to get current settings like `fillHandle`?

**Comment by AMBudnik** [comment] 2017-07-24 13:48
Hi @andrewQwer 

it should return a list of settings

![image](https://user-images.githubusercontent.com/10757813/28526126-d8303a64-7086-11e7-998c-01ed261d3aed.png)

and when we change the default settings by adding some options the object corresponds to the change. For example, the `contextMenu` by default is enabled and the option is set to `undefined` and when we enable the `contextMenu` this change is visible in the `getSettings` list

![image](https://user-images.githubusercontent.com/10757813/28526295-6a9f5916-7087-11e7-86c9-cc0839192033.png)

**Comment by leriel** [comment] 2018-11-23 16:46
Hello @AMBudnik, please find minimal reproducing issue below
https://jsfiddle.net/eLs5yhak/2/

output:
```
afterLoadData {}
afterInit {}
```
Please advise

**Comment by AMBudnik** [comment] 2018-11-26 08:10
Thank you for sharing the example @leriel 

I think that we should get the default settings of the table, not the empty object. I'm reopening the example

**Comment by andrewQwer** [comment] 2018-11-26 08:35
> Hello @AMBudnik, please find minimal reproducing issue below
> https://jsfiddle.net/eLs5yhak/2/
> code:
> 
> ```
> var example = document.getElementById('example1');
> var hot1 = new Handsontable(example, {
>   data: Handsontable.helper.createSpreadsheetData(100, 100),
>   rowHeaders: true,
>   colHeaders: true,
>   afterLoadData: function() {
>   	console.log('afterLoadData', JSON.stringify(this.getSettings()));
>   },
>   afterInit: function() {
>   	console.log('afterInit', JSON.stringify(this.getSettings()));
>   }
> });
> ```
> output:
> 
> ```
> afterLoadData {}
> afterInit {}
> ```
> Please advise

Actually if you remove `JSON.stringify` part then you will see all settings in the `_proto_` property.

**Comment by leriel** [comment] 2018-11-26 08:40
>Actually if you remove JSON.stringify part then you will see all settings in the _proto_ property.

Thanks - i found that out some time after posting here - i agree with @AMBudnik that it would make for  smoother experience to have to have settings field object as explicit fields rather than implicit.

**Comment by swistach** [comment] 2021-04-14 11:27
Hi @andrewQwer, @leriel,
`getSettings` works exactly as we planned settings architecture.
Settings levels (`GridMeta`, `TableMeta`, `ColumnMeta`, `CellMeta`) inherit properties accordingly to the following explanation:
https://github.com/handsontable/handsontable/blob/master/src/dataMap/metaManager/index.js#L11-L32

I think this issue needs only the architecture's description in our documentation.

**Comment by AMBudnik** [comment] 2022-02-09 12:44
As we already mentioned this issue in https://github.com/handsontable/handsontable/issues/8478 as the reason to correct the documentation I'm closing this topic and will update it as soon as we finish https://github.com/handsontable/handsontable/issues/8478

**Closed by AMBudnik** 2022-02-09 12:44 UTC
Labels: docs
