### ISSUE TITLE
Rows are not rendered if there is a row with bigger height than the container height

### ISSUE THREAD

**Issue by minchopm** [handsontable/handsontable#4173] opened 2017-04-06 14:12 UTC
### Description

Hi, I know why, but don't know how to fix it, so if you have a bigger content inside some row, and that row is the latest rendered in the grid then all the rows after it are not rendered. Hope that you will find a solution soon.

### Demo
[http://jsfiddle.net/minchopm/utojx2v9/5/](http://jsfiddle.net/minchopm/utojx2v9/5/)

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment] 2017-04-07 12:20
Thank you for sharing @minchopm 

What is unusual when we comment `columnSorting` and `stertchH` option demo works as expected - it shows all rows: http://jsfiddle.net/handsoncode/6vwep8b0/

**Comment by minchopm** [comment] 2017-04-07 13:05
No, your solution is now working, because when you remove both properties, the table is rendering all rows, because the rowHeights is missing and if you render more that 30 rows (more than initial load ) the problem is existing. The formula can't calculate rowHeight.
### Demo
[http://jsfiddle.net/minchopm/6vwep8b0/1/](http://jsfiddle.net/minchopm/6vwep8b0/1/)

**Comment by AMBudnik** [comment] 2017-04-07 13:10
Thank you for additional investigation @minchopm 
it will surely help our devs to solve the issue

**Comment by minchopm** [comment] 2017-04-07 13:33
Also if you trigger render when you scroll on an empty place it will calculate the rows correctly

**Comment by AMBudnik** [comment] 2018-08-28 08:44
Works the same in v `5.0.1`. The 6th row is the last one I can see without clicking on the table.

![3gif](https://user-images.githubusercontent.com/10757813/44711267-409f1900-aaae-11e8-89a6-1c3bf0453bc5.gif)

**Comment by wojciechczerniak** [comment] 2019-01-31 13:11
Duplicate of #3448

**Closed by wojciechczerniak** 2019-01-31 13:11 UTC
Labels: Core: alignment/height/width, Type: Bug
