### ISSUE TITLE
Split `loadData` into `updateData` and `setData`

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#7263] opened 2020-09-09 21:47 UTC
### Background

- `loadData` is reinitializing all states kept internally in Handsontable
- `updateSettings` is using `loadData` when `data` key is present. Therefore this is not an "update" at all, but a state reset.

This creates a problem where "update" is not really an update, everything is overwritten and the user state (moved rows, sorted columns, filtered data, operations in undo stack) is lost. Especially visible when used with framework wrappers where data reactivity is based on `updateSettings`.

Some users expect us to keep the state, some to reset it. We have two main use cases here that's why I propose to split this method into two.

Reference:
- #6552
    - ✅  &nbsp; resolved with #8972
- #5859 
    - ⭕️  &nbsp; still active, but open cases seem unrelated
- #7165 
    - ⭕️ &nbsp; out of scope, related to #6806
- #5616
    - ⭕️ &nbsp; not related to `loadData`, but `updateSettings` with `columns`/`cell`/`cells` defined still resets the cell meta
- #4446
    - ⭕️ &nbsp; same as above, still active, because of the usage of `cells` in `updateSettings`
- #3315
    - ⭕️ &nbsp; out of scope, related to #6806
- #4375
    - ⭕️ &nbsp; out of scope, not sure if it's a bug or a known behavior

### Introducing `updateData` and `setData`

To distinguish two different developer intentions I propose to create an `updateData` method next to the `loadData` that will do what the name suggests, only update cell values without touching the current state of Handsontable. This is currently possible with `populateFromArray` or `setSourceDataAtCell` used in a loop but without `batch` support those trigger a lot more operations than necessary.

IMO `update` / `set` naming scheme should be obvious intentions. Keep the `loadData` for backward compatibility but make it an alias to `setData`. 

### `updateSettings` case

After a new methods are introduce the `updateSettings` will use the `updateData` instead `loadData` / `setData`. This way, changing `data` key is not resetting all states and `update*` part of the name start to mean something.

### Plugins

We should verify that all plugins are correctly reacting to `updatePlugin` that is triggered by `updateSettings`. Some may reinitialize themselves from scratch. We need to check if the plugin lifecycle should be extended with `setData` event, so all states are reset correctly when new data is loaded.

Reference: 
- #6806

### Wrappers

All wrappers (React, Vue, Angular) are using `updateSettings` internally whenever components props are changed. Therefore each `data` update will reset their state and makes some features of Handsontable useless ie. undo/redo is reset each time a change is made.

Reference:
- #7258 
    - ⭕️ &nbsp; out of scope, not a wrapper nor an `updateSettings` issue
- [https://github.com/handsontable/vue-handsontable-official/issues/185](https://github.com/handsontable/vue-handsontable-official/issues/185)
    - ✅ ❓  &nbsp; change in [#8697](https://github.com/handsontable/handsontable/issues/8697) might make a fix/workaround from [vue-handsontable-official#180](https://github.com/handsontable/vue-handsontable-official/pull/180) redundant - needs further investigation
- https://github.com/handsontable/vue-handsontable-official/issues/181
    - ⭕️ ❓&nbsp; removing the previous fix/workaround from the vue wrapper makes the problem reappear, probably because of #6806
- https://github.com/handsontable/vue-handsontable-official/issues/182
    - ⭕️ ❓&nbsp; removing the previous fix/workaround from the vue wrapper makes the problem reappear, probably because of #6806
- #7538
    - ✅  &nbsp; resolved with ~#8972~, already working correctly in `11.0`

### Hooks
Currently we have `beforeLoadData` and `afterLoadData` hooks. We need to consider using them or introducing new ones for the new methods and use cases.

**Comment by Guobacai** [comment] 2021-07-26 13:40
Hello, 

This issue has a bigger impact. Is there any plan scheduled for fixing this issue?

Thanks,

**Comment by AMBudnik** [comment] 2021-08-02 10:08
Hey @Guobacai the following topic hasn't been scheduled yet. 

However, I will make sure to update you as soon as we release a new version of Handsontable where those changes are included.

**Comment by warpech** [comment] 2021-11-25 16:17
@jansiegel can you clarify what problems listed in the OP are fixed by the PR #8972? 

If, in your opinion they are out of scope of this issue, please mark them as such, ideally by editing the OP.

**Comment by jansiegel** [comment] 2021-12-01 12:04
> @jansiegel can you clarify what problems listed in the OP are fixed by the PR #8972?
> 
> If, in your opinion they are out of scope of this issue, please mark them as such, ideally by editing the OP.

I updated the OP, but here's a quick summary:
- 2 of the issues linked in the OP seem to be fixed with #8972.
- The wrappers need to be re-checked to check if the previously-done fixes/workarounds are still needed.
- Many of the issues seem to be caused by the plugins resetting their internal configs after calling `updateSettings` (problem described in #6806)

**Comment by AMBudnik** [comment] 2022-01-17 12:12
@Guobacai @andreafonso @blockmonkey @justinThompson 
I just wanted to send you an update that we've released a new method called [`updateData()`](https://handsontable.com/docs/api/core/#updatedata) that allows you to update your dataset without resetting your states.

**Comment by aninde** [comment] 2022-03-10 08:18
Tested during code freeze of v12.0.0.

**Comment by AMBudnik** [comment] 2022-04-28 13:17
Fixed in Handsontable v12. Here https://handsontable.com/docs/release-notes/#_12-0-0 is the full list of changes for the version.

@Guobacai @andreafonso @blockmonkey @justinThompson I think that you might be interested in those changes. Please contact us at support@handsontable.com if you would have any questions regarding the changes.

**Closed by AMBudnik** 2022-04-28 13:17 UTC
Labels: Core: handsontable, Status: Released, Core: update settings
