### ISSUE TITLE
Using read-only and alignment from the context menu when all columns are selected is disabled

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7114] opened 2020-07-13 13:00 UTC
### Description

Using read-only and alignment from the context menu when all columns are selected is disabled.

**Important!**: Issue fixed in beta2.

### Steps to reproduce

1. Select both column
2. Use RMB to open context menu

**Result**
![742](https://user-images.githubusercontent.com/10757813/87306985-255e1b00-c519-11ea-89d2-ab51c36633cc.png)

**Expect result**
![pre-beta](https://user-images.githubusercontent.com/10757813/87306993-28f1a200-c519-11ea-878a-576d6c0dc9fa.png)

### Demo

https://jsfiddle.net/g41xrzpm/ 7.4.2 (broken)
https://jsfiddle.net/g41xrzpm/1/ pre 8.0.0-beta2 (**working**)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 83
* Operating System: Windows 10

**Comment by aninde** [comment] 2020-07-22 15:43
This issue is still fixed with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/y1djmwfa/. 
<img width="360" alt="Screenshot 2020-07-22 at 17 40 54" src="https://user-images.githubusercontent.com/30186818/88197316-92249400-cc42-11ea-80ba-66a1b2cd4c57.png">.

I'm not sure if it was a bug at all, because after opening the demo in version 7.4.2 I have a different result in Firefox 78 
<img width="377" alt="Screenshot 2020-07-22 at 17 39 20" src="https://user-images.githubusercontent.com/30186818/88197456-cef08b00-cc42-11ea-9577-a8ac5c4bffde.png">

**Comment by AMBudnik** [comment] 2020-08-06 09:23
Demo updated to v 8.0.0 https://jsfiddle.net/n0uhtfvw/

**Comment by aninde** [comment] 2020-08-06 09:44
> Demo updated to v 8.0.0 https://jsfiddle.net/n0uhtfvw/
Still works well. I couldn't reproduce this bug on the original demos. Closing it as solved by `v8`.

**Closed by aninde** 2020-08-06 09:44 UTC
Labels: Context menu, Core: selection, Read-only, Type: Bug
