### ISSUE TITLE
error on /dist/handsontable.css page (around line 442)- the fix for IE9

### ISSUE THREAD

**Issue by marenwoodruff** [handsontable/handsontable#6221] opened 2019-08-20 21:55 UTC
### Description

when you npm i, you get an error because of the fix for IE9.

### Steps to reproduce

1. npm i the latest version- 7.1.1
2. npm start
3. error- 

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

![Screen Shot 2019-08-20 at 11 22 42 AM](https://user-images.githubusercontent.com/6202683/63387214-b8b6bc80-c359-11e9-8695-c15dc2cf77cb.png)
![Screen Shot 2019-08-20 at 11 23 26 AM](https://user-images.githubusercontent.com/6202683/63387599-b6089700-c35a-11e9-96a7-7ab5c0a8eaf8.png)

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: chrome 75.0.3
* Operating System: Mac )S High Sierra 10.13.6

**Comment by wojciechczerniak** [comment] 2019-08-21 10:44
Thanks for the report @marenwoodruff and the PR but this is not a bug in Handsontable. There were already an issue here #4896 with few solutions to the issue with `css-loader`. The problem is within the 3rd party tool. Browsers will ignore invalid properties and values, that's how backward compatybility works.

Duplicate of #4896

**Closed** 2019-12-06 14:16 UTC
Labels: Type: Duplicate
