### ISSUE TITLE
renderer called sooo many times

### ISSUE THREAD

**Issue by marcok** [handsontable/handsontable#2152] opened 2015-02-12 13:36 UTC
Hi

The renders are called for each cell in the col if you change only one singe cell, regardless which one.

You can reproduce on jsfiddle, if you change a cell, regardless which one, the yellowRenderer is called 10 times.
I have a quite resource intensive renderer (convert a date into a ISO Week notation). If I copy/paste a lot of data, it takes minutes. With each row, all the already existing gets checked again...

Do I have to change my approach, or is something wrong with hot?

http://jsfiddle.net/tw9ec3bx/

**Comment by warpech** [comment] 2015-02-12 14:50
Do you realy mean it takes minutes to paste the data? Then I think the bottleneck is something else than our approach to triggering the renderers. Could you reproduce this in a JSFiddle?

Handsontable renders only the visible part of the grid (+10 rows/cols that are nearest to the visible edge on all sides) so the overhead of that is not be that big.

The reason for full render is that you can have a renderer which displays a computed value (total, etc) of other cells. So, when a single cell changes, all renderers should retriggered.

There is place for improvement though... A simple solution could be to create a parameter that enables/disables full rerender.

**Comment by marcok** [comment] 2015-02-12 14:59
I figured out why it takes so long.

Actually I want to replace 21.12.2005 in something like 2015-W49. If somebody put in 2015-W49 direct, nothing happens. If somebody put in xyz, it has to get invalid.

So my renderer looks like:

{code}
if (!/^([0-9]{4})\-W([0-9]{1,2})$/.test(value)) {
....
instance.setDataAtCell(row, col, susWeek);
....
}
{code}

so when I paste 400 rows with dates, it checks it many times, because after setDataAtCell() each row is checked again. It's not an endless loop, because if its 2005-W49 already, it doesn't change again. But it takes long.. Not 20 minutes, but 1-2 Minutes.

So its a issue only affects people who use setDataAtCell(). Is there another, more efficient, way to re-format something onChange?

**Comment by warpech** [comment] 2015-02-12 15:09
Aha! This is because each time `setDataAtCell` is called, a full render gets triggered.

Try to use `getData()` which returns a reference to the full data object without rerendering. If you need, you can then trigger the render using `render()` method.

**Comment by marcok** [comment] 2015-02-12 15:13
I try, thanks.
One idea for the future would be to have the information available which cell was changed when the renderers is called. So you can decide in the render if you wanna skip processing/rendering (e.g. in my case the expansive regexp), or if you really want to re-render all cells.

**Comment by marcok** [comment] 2015-02-19 12:26
I tried it.
I change now the referenced data object and now its FAST!
But visualization is quite strange, 80% of the cells reflect the new formated string, when I scroll up and down I comes to 100%. Actually I expected 0%.
For sure it works, if I make a render() call after copy paste is finished.

**Comment by marcok** [comment] 2015-02-19 13:27
Unfortunatly it does not work. In the Renderer i do this:
```javascript
dataRef = instance.getData();
dataRef[row][prop] = susWeek;
```
On save, I do this:
```javascript
var data = this.handsontable.getData();
var method = $.ajax({
  url: App.config.envUrl + 'hotCrud/updateCollection/' + this.options.getMethod + '/'  + this.options.masterEntity + '/' + (this.currentId || App.viewState.planningSet.id),
            type: 'POST',
            data: JSON.stringify(data),
            processData: false
        })  
```

But data contains the old, not converted, format. Why, I thought all is by reference?

**Comment by marcok** [comment] 2015-02-19 13:45
Renderer is not called for copy/paste set, so data is not converted, as long as the cell is invisible. That's the new problem.

Can you give my any advise, where i should put in my conversion logic if I wanna paste >500 rows?

**Comment by varun-dev** [comment] 2016-02-10 13:16
Hi, are there any plans for these render improvements ???

**Comment by budnix** [comment] 2016-03-04 10:52
I mark this as a performance improvements.

**Comment by AMBudnik** [comment] 2016-03-07 11:26
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Closed by AMBudnik** 2016-03-07 11:26 UTC
Labels: Core: performance, Improvement suggestion, Priority: normal

**Comment by sportfort** [comment] 2016-10-24 21:30
I ended up with using the dirtiest hack, I've ever created. I modified **dist/handsontable.js** file and now my "edition" of ht works almost perfectly. The idea is to constrain cells, that will be rerendered after cell modification. So after all changes (actually **beforeChange** event is used to capture changes), changes are saved in field **lastChanges** of HT. Each change contains information about row and prop of changed cell. So, only these "last changes" will be rerendered. It works dramatically faster, than original ht, assuming you don't need to compute widths after edits etc.

I'm not sure this hack is worth creating a pull request. But the idea behind it probably should be considered and implemented as introducing a configuration parameter **"forceFullTableRerenderAfterAnyChange"**. BTW, without this hack handsontable become not usable for me, although it is really amazing).

I have not fully tested this solution and anyway, I'm sure it can be done better.

In order to repeat my "achievements" you should do the following things:

1) Modify **renderCells** function:
```
renderCells: function(sourceRowIndex, TR, columnsToRender) {
    var TD;
    var sourceColIndex;
    for (var visibleColIndex = 0; visibleColIndex < columnsToRender; visibleColIndex++) {
      sourceColIndex = this.columnFilter.renderedToSource(visibleColIndex);
      if (visibleColIndex === 0) {
        TD = TR.childNodes[this.columnFilter.sourceColumnToVisibleRowHeadedColumn(sourceColIndex)];
      } else {
        TD = TD.nextSibling;
      }
      if (TD.nodeName == 'TH') {
        TD = replaceThWithTd(TD, TR);
      }
      //todo: Handsontable performance hack start
      //if (!hasClass(TD, 'hide')) {
      //  TD.className = '';
      //}
      //TD.removeAttribute('style');
      //todo: Handsontable performance hack end
      this.wot.wtSettings.settings.cellRenderer(sourceRowIndex, sourceColIndex, TD);
    }
    return TD;
  }
```

2) Modify **cellRenderer** function:
```
cellRenderer: function(row, col, TD) {
      var cellProperties = that.instance.getCellMeta(row, col);
      var prop = that.instance.colToProp(col);

      //todo: handsontable performance hack start
      var neverEdited = !instance.lastChanges;
      var justEdited = false;
      if (instance.lastChanges) {
          for (var i = 0; i < instance.lastChanges.length; i++) {
              var item = instance.lastChanges[i];
              if (row === item[0] && prop === item[1])
              {
                  console.log("detected: " + JSON.stringify(item));
                  justEdited = true;
                  break;
              }
          }
      }

      if (!neverEdited && !justEdited)
          return;

      if (!hasClass(TD, 'hide')) {
        TD.className = '';
      }
      TD.removeAttribute('style');
      //todo: handsontable performance hack end

      var value = that.instance.getDataAtRowProp(row, prop);
      if (that.instance.hasHook('beforeValueRender')) {
        value = that.instance.runHooks('beforeValueRender', value);
      }
      that.instance.runHooks('beforeRenderer', TD, row, col, prop, value, cellProperties);
      that.instance.getCellRenderer(cellProperties)(that.instance, TD, row, col, prop, value, cellProperties);
      that.instance.runHooks('afterRenderer', TD, row, col, prop, value, cellProperties);
    }
```

3) Add hook to any place, where HT initializes:
```
Handsontable.hooks.add("beforeChange", function (changes, source) {
            if (!changes)
                return;
            this.lastChanges = changes;
            console.log("afterChanges: " + JSON.stringify(changes));
        });
```

**Comment by krzysztofspilka** [comment] 2016-10-24 21:40
@budnix check this out!
@sportfort do you have some online examples before/after your change?

**Comment by sportfort** [comment] 2016-10-24 23:01
@krzysztofspilka 
Here it is http://jsfiddle.net/adykep4d/
Original is http://jsfiddle.net/tw9ec3bx/

The difference is seen when you modify any not yellow cell. In original fiddle it will cause multiple yellowrenderer alerts. In modified fiddle, no alerts will be produced after changes.

However when you will modify yellow cells, multiple alerts will be triggered (not single). This is strange behavior, because actual rendering is not performed (can be checked by modifying background and inner text of tds). This is ok for me.

**Comment by varun-dev** [comment] 2016-10-25 15:38
When I need to render few cells in the table, I use the following non hacky method

```
function renderCell(instance, td, prop, value) {
  const coords = instance.getCoords(td)
  const renderer = instance.getCellRenderer(coords.row, coords.col)
  const cellProperties = instance.getCellMeta(coords.row, coords.col)

  renderer(instance, td, coords.row, coords.col, prop, value, cellProperties)
}

```

Now how you get that td depends on you. I have created my own handsontable plugins for high performance data updates on the table and light-weight cell renderers. I hope to make them open source as soon as my legal team allows, lol :)

**Comment by sportfort** [comment] 2016-10-26 08:39
@varun-dev Can you please provide more details?
I don't understand how do you use the function **renderCell**. And how it is related to this thread.

**Comment by varun-dev** [comment] 2016-10-26 10:57
@sportfort 

Apologies for lack of details in my previous post. If we want to update one cell or few cells, HT goes and re-renders every cell in the viewport even if the cell you wanted to update is not even in the viewport. If this becomes repetitive with few thousand rows then the performance of the table gets really messed up. In my case, I am using the table where I show prices and these prices keep ticking.

If you can manage to select the td of the cell you want to re-render or update the value, then you can get the renderer of that cell by passing the td to api `getCoords(td)`. Once you have this, then its really straight forward to get the renderer and cellProperties and then manually call the renderer which will only update that specific cell.

**Comment by gabovanlugo** [comment] 2017-05-22 06:07
@varun-dev A little example or playground would be really appreciated because I think I'm not following you at all.

**Comment by krzysztofspilka** [comment] 2018-01-08 11:52
![](https://github.trello.services/images/mini-trello-icon.png) [Rewrite renderers to improve performance](https://trello.com/c/m9KTygSV/80-rewrite-renderers-to-improve-performance)

**Comment by AMBudnik** [comment] 2018-06-11 06:46
Hi @coljung 
we are very slowly moving to the renderers subject. There are some other issues that we need to fix before moving on to the new renderer logic.

**Comment by AMBudnik** [comment] 2021-05-19 13:14
Related subject https://github.com/handsontable/handsontable/issues/5769
