### ISSUE TITLE
three are worong when add minSpareRows in vue.

### ISSUE THREAD

**Issue by leavky** [handsontable/handsontable#8592] opened 2021-07-28 08:46 UTC
### Description
when i add minSpareRows: 1 in hotSettings,

### Steps to reproduce

1. add minSpareRows in hotSettings;
2.  edit table in last row, there are two rows add auto, adfter edit the last row,there are wrong.

### Demo

https://jsfiddle.net/1z5g764s/2/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

![image](https://user-images.githubusercontent.com/46547390/127292743-92e4f827-3517-4daa-8574-3e5f1eb11113.png)

**Comment by swistach** [comment] 2021-07-28 14:40
Hi @leavky,
Thank you for your reporting. I'm closing this issue because it's a duplicate of the discussion you can find in #7787.

**Closed by swistach** 2021-07-28 14:40 UTC
Labels: vue
