### ISSUE TITLE
[8.0.0-beta2-rev1/rev7] Undo of removed columns/rows covers too many columns/rows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6964] opened 2020-05-29 13:17 UTC
### Description

I thought that this issue got broken with https://github.com/handsontable/handsontable/issues/6963, however, it got broken before rev7 (just a different way), in rev1 so it might originate somewhere else.

### Steps to reproduce
**Steps**
1. Go to (rev10 https://jsfiddle.net/AMBudnik/m6dL1xoa/)
2. Select columns, `B`, `D`, and `F`
3. Remove them by context menu
4. Use <kbd>CMD/CTRL</kbd> + <kbd>Z</kbd> to undo

**Result** _from 8.0.0.-beta2-rev1 till 8.0.0-beta2-rev6_ 
https://jsfiddle.net/AMBudnik/c2ajkhrm/
Selection moves from  `F` to `I`.
![rev1](https://user-images.githubusercontent.com/10757813/83263189-7eb6f880-a1be-11ea-816f-75d2d078f407.gif)

**Result** _from 8.0.0.-beta2-rev7 till 8.0.0-beta2-rev10_ 
https://jsfiddle.net/AMBudnik/azkboj4h/
Selection is added to previously selected cells and newly selected.
![issue](https://user-images.githubusercontent.com/10757813/83261854-53330e80-a1bc-11ea-89e1-67f258e37f83.gif)

**Expected result** _till 8.0.0-beta2-rev1_
https://jsfiddle.net/AMBudnik/vdk0mt7L/
Selection works well.
![ok742](https://user-images.githubusercontent.com/10757813/83263557-1a486900-a1bf-11ea-91a8-811f2cd0a8b6.gif)

### Demo

https://jsfiddle.net/AMBudnik/k20ztcux/ 8.0.0-beta1 (works well)
https://jsfiddle.net/AMBudnik/59wq1gkv/ 8.0.0-beta2-rev1 (broken)

### Related issues
* https://github.com/handsontable/handsontable/issues/6963

### Your environment
* Handsontable version: 8.0.0-beta2-rev1
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by aninde** [comment] 2020-06-08 13:04
**Another case**
Select two adjacent columns, remove them using a context menu and undo it. 

https://jsfiddle.net/aninde/1tLvgd63/ rev7 - `8.0.0-beta2-rev7 (**broken**)
https://jsfiddle.net/aninde/vmxdfrho/ - `8.0.0-beta2-rev6` (fixed)


![rem2-rev7](https://user-images.githubusercontent.com/30186818/84033191-c72d9d80-a998-11ea-8063-22a49060e1e1.gif)
![rev6-fixed](https://user-images.githubusercontent.com/30186818/84033513-3f945e80-a999-11ea-94a5-90ceea5fd27f.gif)

**Comment by aninde** [comment] 2020-06-17 15:04
Sadly this bug is still replicable in `8.0.0-beta2-rev15` https://jsfiddle.net/aninde/6ztu1q3L/
![6964-rev15](https://user-images.githubusercontent.com/30186818/84914945-7dd9fe00-b0bc-11ea-9dd9-350523c54baa.gif)

**Comment by AMBudnik** [comment] 2020-06-18 06:02
Hey @aninde 

Revision 15th brings back the behavior from 

_8.0.0.-beta2-rev1 till 8.0.0-beta2-rev6_ 
https://jsfiddle.net/AMBudnik/c2ajkhrm/
Selection moves from  `F` to `I`.
![rev1](https://user-images.githubusercontent.com/10757813/83263189-7eb6f880-a1be-11ea-816f-75d2d078f407.gif)

which is **the desired result**, as the team wanted to follow the same rules as they are for rows to avoid inconsistency.

I wasn't aware of that plan before constructing this message, but I guess that @wojciechczerniak can agree that this was intended.

![rows](https://user-images.githubusercontent.com/10757813/84983766-bbc93780-b139-11ea-8657-44eb83ec3713.gif)

**Comment by aninde** [comment] 2020-06-30 13:05
If this was to be the intended effect, should we not close this issue?

**Comment by wojciechczerniak** [comment] 2020-06-30 14:17
If you're waiting for me then yes, this is the intended behavior. Only the last selection is fully supported. The non-contiguous selection was not taken to the next stage yet.

**Closed** 2020-06-30 14:17 UTC
Labels: Core: selection, Regression, Type: Bug, Undo-redo
