### ISSUE TITLE
Double scroll on resize

### ISSUE THREAD

**Issue by fbrussa** [handsontable/handsontable#2970] opened 2015-11-10 11:33 UTC
Hi, this occurs when you resize the table in chrome. It seems to be a bug.

http://jsfiddle.net/0xdnwf82/2/

**Comment by AMBudnik** [comment] 2015-11-10 17:56
Hi, what exactly you would like to achieve? I think that we can find a solution.

**Comment by fbrussa** [comment] 2015-11-10 18:53
Hello.
I use handsontable within a resizable area. So when resizing the container, I need to adjust the size of the table.

Look at this picture so you see better.
http://share.pho.to/9rr8b

Thank you

**Comment by AMBudnik** [comment] 2015-11-16 13:12
Hi @fbrussa did you tried to add another div with `overflow: hidden`?

**Comment by fbrussa** [comment] 2015-11-16 13:30
Hi, I tried this: http://jsfiddle.net/0xdnwf82/4/

But I still see strange behavior, especially in chrome.

**Comment by AMBudnik** [comment] 2015-11-16 14:44
Yes, when the area for instance is too small it's impossible to use scroll. It occurs on Windows (OSX not affected). There is only a ability to move by arrow navigation.

**Comment by fbrussa** [comment] 2015-11-16 14:56
It does not happen only with small area. This occurs also in a big area
http://jsfiddle.net/0xdnwf82/5/
This resize action working fine in version 0.13 (my prior version). 
I update to 0.20 and look this strange behavior,

**Comment by AMBudnik** [comment] 2016-03-22 12:49
confirmed with 0.24.1 http://jsfiddle.net/0xdnwf82/6/
There's an extra vertical transparent scroll after choosing `resize 2` button

**Comment by AMBudnik** [comment] 2018-04-23 12:06
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by wojciechczerniak** [comment] 2019-04-04 11:05
@AMBudnik Can you replicate this issue in `v7.0.0` http://jsfiddle.net/p0Lc9nfa/ ?

**Comment by AMBudnik** [comment] 2019-04-04 11:16
Works well for me in 7.0.0 @wojciechczerniak 
I think that we can close the issue.

@fbrussa please update and let us know if it works for you. If not, we'll reopen the ticket.

**Closed by AMBudnik** 2019-04-04 11:16 UTC
Labels: Type: Bug
