### ISSUE TITLE
[8.0.0-svg] Selection on printed Handsontable

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6626] opened 2020-01-10 15:14 UTC
### Description
Found during testing https://github.com/handsontable/handsontable/issues/6467.

Selection does print without fillHandle.
Excel does not print selection. 
@wojciechczerniak agreed it should not be visible on the print in Handsontable.
![Screenshot 2020-01-08 at 14 09 31](https://user-images.githubusercontent.com/30186818/71981194-22106c80-3222-11ea-8182-1558206d42a3.png)

Probably this bug occurs since the beginning but was hide on prints. Borders and selection were part of the background. Changes related to a new way of drawing SVG borders discover it.
This occur on every SVG PR 
https://github.com/handsontable/handsontable/pull/6157
[testing svg-stage1-#6157.pdf](https://github.com/handsontable/handsontable/files/4040026/testing.svg-stage1-.6157.pdf)
https://github.com/handsontable/handsontable/pull/6593 
[testing svg-stage2-#6593.pdf](https://github.com/handsontable/handsontable/files/4040010/testing.svg-stage2-.6593.pdf)
https://github.com/handsontable/handsontable/pull/6594
[testing svg-stage2-#6594.pdf](https://github.com/handsontable/handsontable/files/4040011/testing.svg-stage2-.6594.pdf)

### Your environment
* Handsontable version: 8.0.0-svg
* Browser Name and version: any
* Operating System: macOS Catalina, but shouldn't be related

**Comment by warpech** [comment] 2020-01-13 10:52
We discussed on Slack: https://handsoncode.slack.com/archives/C4PV4S33Q/p1578566904004800

The desicion made by @krzysztofspilka is to hide all SVG borders using CSS until a better solution is specified and implemented.

Unfortunately, this solution is against what was suggested here https://github.com/handsontable/handsontable/issues/5298#issuecomment-561202955, but I guess we will have to do it at least for now.

I think that the long-term solution will require adding a new border setting `printable`, which custom borders would set to `true` and selections would set to `false`.

**Comment by warpech** [comment] 2020-01-14 11:54
Fixed according to the solution described above in the commit cd42f84a3f676899e97b02fa24a27fdf9f32ea38, part of the PR https://github.com/handsontable/handsontable/pull/6157

**Comment by aninde** [comment] 2020-01-16 10:45
Ok, it works beautifully, according to the assumptions. No customBorders or selection can be seen on the print, but there is an empty space after square of fillHandle.  This is regression, because it wasn't there on 7+ versions. This square didn't belong to scope, but in my opinion it doesn't look good.  What you think about it @wojciechczerniak ?

`Print screen from browser`
<img width="325" alt="Screenshot 2020-01-16 at 11 38 22" src="https://user-images.githubusercontent.com/30186818/72518406-94520400-3855-11ea-8ec3-d33f69fe8eda.png">

`Print screen from print`
<img width="410" alt="Screenshot 2020-01-16 at 11 38 13" src="https://user-images.githubusercontent.com/30186818/72518414-9a47e500-3855-11ea-8cae-0322a4dd87d5.png">

**Comment by wojciechczerniak** [comment] 2020-01-16 13:21
> This square didn't belong to scope, but in my opinion it doesn't look good. What you think about it @wojciechczerniak ?

Looks like the fix in https://github.com/handsontable/handsontable/commit/cd42f84a3f676899e97b02fa24a27fdf9f32ea38 wasn't complete. This square is a part of fill handle which should be hidden in print as well.

**Comment by warpech** [comment] 2020-01-16 14:38
> Looks like the fix in cd42f84 wasn't complete. This square is a part of fill handle which should be hidden in print as well.

The fix was complete in that regard. As @aninde says, the empty hole insted of the fill handle is not a regression, because:

- the same hole exists in 7.x
- the hole is not rendered using SVG

I can make a fix for that in my branch, but I wanted to double confirm with you, because fixing the visual glitch that exists in 7.x is both a breaking change and not in scope of SVG borders.

**Comment by wojciechczerniak** [comment] 2020-01-16 14:49
Sorry, I thought I've read it wasn't there before.

I did a check myself in v7. It IS the fill handle. The web browser changed the background color to white. The default browser setting for "print background color" is `no` to limit ink waste.

You're right it's out of scope for this PR.

**Comment by aninde** [comment] 2020-01-16 15:29
Thank you so much for double checking, the bug is actually on version 7+. Is reported https://github.com/handsontable/handsontable/issues/6650. So, IMO we should close this issue, cause fix in https://github.com/handsontable/handsontable/commit/cd42f84a3f676899e97b02fa24a27fdf9f32ea38 was complete and correct with assumptions and scope.

**Closed** 2020-01-30 17:19 UTC
Labels: Core: selection, Custom borders, Type: Bug
