### ISSUE TITLE
set a bottom border for one cell

### ISSUE THREAD

**Issue by yilongzhou** [handsontable/handsontable#3296] opened 2016-03-04 10:42 UTC
Hello:
       I have been updated to the latest version（0.23.0）.As the realease note:
          Fixed shifting cell meta when user wants to insert a new row or a column #1823

```
   In my case, I found another problem: [ notes  is a problem description]
   (http://jsfiddle.net/zq5fzegx/6/)
```

  Looking forward to your help.

  frank

**Comment by AMBudnik** [comment] 2016-03-04 11:56
Hi @yilongzhou could you share more details about what's the unwanted behavior in this case?

**Comment by yilongzhou** [comment] 2016-03-06 03:08
@AMBudnik 
First of all, thank you for your warm reply. I describe my problem in detail as follows：
1.set a bottom border for one cell(row:0, col: 0)
2.insert a new row above(row: 0, which one has the bottom border)
3.question: I expect the bottom border to the next row(row:1, col:0) ，but still in the first row(row:0, col: 0)
Can you understand me now?

**Comment by AMBudnik** [comment] 2016-03-07 10:20
Reproduced. Border should be transfered with the cell (it should move to 2nd row)

result
![pp](https://cloud.githubusercontent.com/assets/10757813/13566454/fbef827a-e455-11e5-88cf-e04679d17d52.png)

related to https://github.com/handsontable/handsontable/issues/1823

**Comment by yilongzhou** [comment] 2016-03-24 03:02
@AMBudnik 
Hello, I have updated to the version 0.24.1. please confirm whether #3296  has been resolved.
It is still wrong.

**Comment by AMBudnik** [comment] 2016-03-24 08:45
Hi @yilongzhou 
Yes, unfortunately this bug is still present. It stays open.

**Comment by yilongzhou** [comment] 2016-04-12 10:14
@AMBudnik 
Hello, #3296 is ok ?

**Comment by AMBudnik** [comment] 2016-04-12 10:34
Hi @yilongzhou 
Yes, this bug still occurs for rows and columns.
Please check this demo: http://jsfiddle.net/7809snmh/
It's set to always use the newest version of Handsontable (currently 0.24.2).

If you want to be up-to-date with bug fixes you can track our release notes:  https://github.com/handsontable/handsontable/releases

Also if this issue stops you from achieving your goal you can order a quick bug-fix - to do so write us at hello@handsontable.com

**Comment by AMBudnik** [comment] 2018-01-19 11:40
Still replicable in version 0.35.0
![shift](https://user-images.githubusercontent.com/10757813/35149297-dd386484-fd15-11e7-8bf8-0ebf477443cf.gif)

**Comment by AMBudnik** [comment] 2018-04-23 11:57
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment] 2018-07-10 08:55
The behavior did not change in v 4.0.0

**Comment by AMBudnik** [comment] 2018-07-13 11:41
The issue is fixed in v 5.0.0. Again thanks for sharing @yilongzhou

**Closed by AMBudnik** 2018-07-13 11:41 UTC
Labels: Plugin: custom borders, Priority: normal, Type: Bug

**Comment by lindanni** [comment] 2024-06-14 09:51
Hello, this problem seems to still exist in the latest version

**Comment by adrianszymanski89** [comment] 2024-06-14 10:06
Hi @lindanni 

Thank you for pointing that out. I checked, and indeed, it's replicable again in 14.4.0: https://jsfiddle.net/handsoncode/qwk1yxrp/. I'll report it again.
