### ISSUE TITLE
IE when the drop down is visible the mouse down event is not triggering on specific section

### ISSUE THREAD

**Issue by AronRidgway** [handsontable/handsontable#6366] opened 2019-10-21 15:20 UTC
### Description
when the drop down is visible the mouse down event is not triggering on specific section when using IE. The section seems the be class wtHolder.

### Steps to reproduce
This can be recreated on the demos on your website using IE https://handsontable.com/docs/7.2.1/demo-dropdown.html 

when you click on the section to the right the drop down close event does not trigger.
![image](https://user-images.githubusercontent.com/56836288/67218118-bdf9bb80-f41d-11e9-9ae8-cc8c36d765bc.png)

This does work in both Edge and Chrome though.

The section is below the grid in our case, but this is because the grid is 100% width. But the class name is the same in both cases.

### Your environment
* Handsontable version: 7.2.1
* Browser Name and version: IE 11
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2019-10-22 08:41
Thank you for sharing the issue @AronRidgway 

I replicated this on IE. To confirm it works well on Chrome, Edge, and Firefox.
The issue is replicable for any cell type with a list of options: dropdown, autocomplete, date and hot-in-hot. Works well for select cell type which looks a bit more different on IE.

![GIF](https://user-images.githubusercontent.com/10757813/67269337-db2e9880-f4b6-11e9-9224-a7bad8e8e0df.gif)

The issue is not related to any previous version (not a regression).

**Comment by AMBudnik** [comment] 2020-06-19 09:51
As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them. And as this issue has never been replicable on other browsers that IE we need to close it.

**Closed by AMBudnik** 2020-06-19 09:51 UTC
Labels: Cell type: autocomplete / dropdown / handsontable, Edge, Type: Bug
