### ISSUE TITLE
Bug when the grid is wider than the screen

### ISSUE THREAD

**Issue by Erlaunis** [handsontable/handsontable#2704] opened 2015-08-03 14:05 UTC
Hi, I think I found a bug when you create a grid with a lot of fields and you need a scroll bar to navigate through every cells.
Here is a pic to illustrate what I'm talking about : 
![sans titre](https://cloud.githubusercontent.com/assets/13066551/9038749/03b4484c-39f7-11e5-9295-73ab95a99cd5.png)

I made a code to color some cells of this grid : 
                                $(cells).eq(1).css("background-color","red");
				$(cells).eq(6).css("background-color","red");
				$(cells).eq(10).css("background-color","red");
				$(cells).eq(15).css("background-color","red");
				$(cells).eq(27).css("background-color","red");
				$(cells).eq(30).css("background-color","red");
				$(cells).eq(33).css("background-color","red");
				$(cells).eq(36).css("background-color","red");
				$(cells).eq(39).css("background-color","red");
				$(cells).eq(42).css("background-color","red");
				$(cells).eq(45).css("background-color","red");

When I run this code with the scroll bar to the left, I have this result, with some colored cells : 

![sans titre](https://cloud.githubusercontent.com/assets/13066551/9038952/6a46fac2-39f8-11e5-97a8-cfc5327641f4.png)

When I move a little the scroll bar and I run a second time the code, the colored cells aren't the same : 
![sans titre](https://cloud.githubusercontent.com/assets/13066551/9038985/9b075062-39f8-11e5-9ffd-d855ed6ff1c5.png)
For exemple, the cell with "profondeur travail sol (cm)" that we can see on both captures, is colored on the first but not on the second.

I feel that the indexes of the cells are created with the position of the screen but not with the grid itself.

**Comment by AMBudnik** [comment] 2015-08-03 18:45
Could you please create a demo of your code where you found this behaviour?

**Comment by Erlaunis** [comment] 2015-08-03 19:29
Here is a fiddle with a demo : http://jsfiddle.net/hU6Kz/3810/ 
So, you need to try to submit at different positions of the scrollbar and you'll see that the colored cells are never the same.

**Comment by Erlaunis** [comment] 2015-08-04 07:22
Sorry if you saw the last comment, I forgot to update the fiddle. Here is the good fiddle : http://jsfiddle.net/hU6Kz/3811/
As I said, try to submit at different positions of the scroll bar and the colored cells aren't never the same.
Sorry again !

**Comment by AMBudnik** [comment] 2016-03-22 10:56
I couldn't reproduce it with latest 0.24.1 version.
Am I missing something or this doesn't occur anymore? 
@Erlaunis I really appreciate any help you can provide.

**Comment by AMBudnik** [comment] 2016-04-12 11:06
Also couldn't reproduce with 0.24.2
I'm closing this issue as solved.

**Closed by AMBudnik** 2016-04-12 11:06 UTC
Labels: Answered
