### ISSUE TITLE
Error on setupHandlePosition event

### ISSUE THREAD

**Issue by GregorioF2** [handsontable/handsontable#7972] opened 2021-05-05 16:52 UTC
### Description
Related issue: https://github.com/handsontable/handsontable/issues/5959.

The problem I have is that when I set the `manualColumnResize` option to `true` in the Handsontable constructor, I get the following error when I hover on my column headers:

![Screenshot from 2021-05-05 13-46-08](https://user-images.githubusercontent.com/21204940/117178293-45144780-ada8-11eb-8561-66c58ec247bd.png)

I followed the code and I saw that the error is due to this line 
https://github.com/handsontable/handsontable/blob/master/src/plugins/manualColumnResize/manualColumnResize.js#L284
where the variable `relativeHeaderPosition` is `undefined`.

### Environment
* Handsontable version: 8.3.2
* Browser Name and version: Chrome 87 on Linux
* Operating System: ubuntu 18

**Comment by AMBudnik** [comment] 2021-05-06 07:02
Hi @GregorioF2 

The related issue has already been closed as fixed and released. The issue should not be replicable in v8.3.2.
Could you share a demo and possibly a video that shows the error? I wasn't able to replicate the same on my Windows 10.

**Closed** 2021-05-10 11:46 UTC
Labels: Type: Demo needed

**Comment by GregorioF2** [comment] 2021-05-14 03:30
I cannot replicate the issue on a `jsfiddle` sry. But is like what I described. When I do a hover on the column headers i get the error that prompts on the video.
I debugged on the lib, and is generated  because the object `relativeHeaderPosition` is undefined  when it reaches the line https://github.com/handsontable/handsontable/blob/master/src/plugins/manualColumnResize/manualColumnResize.js#L284.
https://user-images.githubusercontent.com/21204940/118216567-236f2c00-b44a-11eb-98eb-6a8c6c4e5e00.mp4

I cant find anything strange on the declaration. I let here an extract of the code where we create the tables:
```
new Handsontable(this.$el.firstElementChild, {
        data: this.storedData,
        height: this.height || (Number(this.perPage) < 5 ? Number(this.perPage) : 5) * 46 + 50,
        colHeaders: this.colHeaders,
        columns: this.colTargets,
        columnSorting: true,
        fillHandle: false,
        fragmentSelection: true,
        copyPaste: true,
        readOnlyCellClassName: '',
        beforeRender: this.destroyPopups,
        autoColumnSize: {
          samplingRatio: 10,
          syncLimit: 4
        },
        manualColumnResize: this.calcWidths(),
        autoRowSize: true,
        stretchH: 'all',
        className: 'htLeft',
        isEmptyRow: this.isEmptyRow,
        search: {
          queryMethod: this.searchMethod
        }
      });
      ````
And the HTML is 
```
<template lang="HTML">
 <div class="advanced-table"> </div>
</template>
```

**Comment by AMBudnik** [comment] 2021-05-14 12:43
Hi @GregorioF2 

I have also found the same case here https://github.com/handsontable/handsontable/issues/6885 where the issue is also fixed.
I have also tested the code in the sandbox. Maybe some other settings or libraries are causing Handsontable to function incorrectly. Would you be able to send me access to a repository or any platform that I could debug in real-time? ps. If you prefer we can also discuss the subject by email (support@handsontable.com)

**Comment by GregorioF2** [comment] 2021-05-20 13:12
Hi, just wanted to come by to say that this is fixed now. The issue was generated because on a part of the code we were recreating a new Handsontable over the same div. On previous versions, this didn't generate an error but seems that on the current one it does.
For future people that might have this problem I suggest to use `updateSettings` to update the current table configuration instead of destroying and creating one.

Thanks a ton for the help

**Comment by AMBudnik** [comment] 2021-05-20 13:18
Thank you for the feedback @GregorioF2 
I'm glad to hear that the issue is solved.
