### ISSUE TITLE
[0.27.0+] Data not render when use manualRowMove and minSpareRows

### ISSUE THREAD

**Issue by gamevnlc** [handsontable/handsontable#4576] opened 2017-10-26 06:43 UTC
### Description
data is not render when use loadData and render method. Only row is render 

### Steps to reproduce

1. create handsontable with setting manualRowMove is true and minSpareRows : 1 , load 10 data
2. set timeout and load more 40 data

### Demo
http://jsfiddle.net/nt7aq2Lg/

### Your environment
* Handsontable version: 1.14.3 pro
* Browser Name and version: Chrome 62.0.3202.62
* Operating System: Windows 10  64 bit

**Comment by AMBudnik** [comment] 2017-10-26 11:38
Thank you for sharing @gamevnlc 

I have replicated the issue. You're right. When we define

`
manualRowMove: true,
minSpareRows: 1
`

the newly added rows are blank.

It seems like the issue is old as I wasn't able to find a version where it worked as expected.

I am not sure if this https://github.com/handsontable/handsontable/issues/3568 is the same issue but surely it's connected.

**Comment by AMBudnik** [comment] 2018-04-24 08:27
Last working [version was `0.26.1`](http://jsfiddle.net/6yw3n7kL/). In `0.27.0` the bug was created (it did not load the data at all) and [in `0.31.1` ](http://jsfiddle.net/abtfvzL7/)the bug changed to what we have here - rows are added but blank.

**Comment by AMBudnik** [comment] 2018-08-24 13:03
Works the same in v 5.0.1. We still get empty rows

**Comment by jeremy-smith-maco** [comment] 2019-03-27 01:58
This issue is very old. I am surprised it hasn't been fixed yet but the team is still bringing out new features. I encountered this today. I have found a workaround for the given example: http://jsfiddle.net/5pf1hjdk/1/

Disable minSpareRows before loading the new data and then enable them again. Should be fixed though especially with the prices for this library going up ridiculously.

**Comment by AMBudnik** [comment] 2019-03-27 11:39
To be honest we were planning to rebuilt logic of minSpareRows/Cols and make them a separate table rather than a part of the dataset so most of the issues related to spare rows aren't on the to-do list.

**Comment by wojciechczerniak** [comment] 2019-09-23 13:00
Might be fixed in 8.0.0-rc @AMBudnik @aninde 

https://jsfiddle.net/93eor6m2/

**Comment by AMBudnik** [comment] 2019-11-15 08:55
Hey @gamevnlc  Here's an offical 8.0.0-beta1 demo http://jsfiddle.net/1ran4qLh/ where the issue is solved.

Thank you for your active support @jeremy-smith-maco

**Comment by AMBudnik** [comment] 2020-08-07 08:17
Hi @gamevnlc @jeremy-smith-maco 

This issue is also fixed by the stable v 8.0.0 http://jsfiddle.net/bpjhr8q7/

**Closed by AMBudnik** 2020-08-07 08:17 UTC
Labels: Core: spare rows/columns, Moving, Regression, Type: Bug
