### ISSUE TITLE
handsontable disappears on firefox after upgrading to version 93

### ISSUE THREAD

**Issue by JuanjoArmellino** [handsontable/handsontable#9545] opened 2022-05-30 14:29 UTC
hello, I have a problem with HT, it worked fine in firefox until version 92, starting version 93 the table goes white on scroll or window resize.. im not sure if its a firefox problem or something they changed is causing this.
i have to admit it only happens on a very rare case of having a table inside a bootstrap card with the card resizing automaticly to the windows size.. but it happens every time.
works fine on chrome

### Steps to reproduce
load the sample file and scroll the table with the mouse or maximize / restore / resize the window

### Demo
https://jsfiddle.net/p4u7mt0f/

### Your environment
* Handsontable version: HT 7.4, HT10 or HT12 
* Browser name and version: firefox after version 93
* Operating system: windows 10 21h2

**Comment by AMBudnik** [comment] 2022-05-31 06:40
Thank you for sharing the report @JuanjoArmellino 

I'm already on FF 100. But you are right. Chrome opens the demo and it works well, while Firefox does not show the table. I tested the CSS settings and by commenting our the `overflow` I got the table working on Firefox.

![Screenshot 2022-05-31 at 08 39 00](https://user-images.githubusercontent.com/10757813/171108577-da7e8383-1674-4fa3-a25b-c920457e7867.png)

We'll investigate it further and check what are the connections to https://github.com/handsontable/handsontable/issues/2806

**Comment by AMBudnik** [comment] 2022-08-26 10:55
Minified demo: https://jsfiddle.net/6r7kvdwj/10/ (still contains a lot of DIVs with `flex` settings)
I've added comments on what changes the behavior between Firefox and Chrome in the comments
Tested with Handsontable v12.1.2 on Chrome 103 / macOS Monterey

**Comment by wszymanski** [comment] 2022-10-04 17:53
I've done investigation by myself to determine why the problem occurs. I've found that node created as clone sometimes has height set as `0`. The first call to `alignOverlaysWithTrimmingContainer` methid is done from `Table` element's constructor and it's calculated properly, while the second one (called from `draw` method) isn't calculated properly on FF.

https://github.com/handsontable/handsontable/blob/a2033859014e4e115cf54e638b23727f91c07f29/handsontable/src/3rdparty/walkontable/src/table.js#L108-L110

https://github.com/handsontable/handsontable/blob/a2033859014e4e115cf54e638b23727f91c07f29/handsontable/src/3rdparty/walkontable/src/table.js#L308-L309

https://github.com/handsontable/handsontable/blob/0fbd127c2bff75a787034cdbec60b1f3826f4261/handsontable/src/3rdparty/walkontable/src/table/master.js#L67-L73

Deep clone of DOM element (currently a flag is set to `false`) for purpose of calculation fixes the problem, but it isn't definitely a solution.

https://github.com/handsontable/handsontable/blob/0fbd127c2bff75a787034cdbec60b1f3826f4261/handsontable/src/3rdparty/walkontable/src/table/master.js#L49-L50

The problem is happening even though Firefox and Chrome draw flex elements properly. At first, I thought, that there may be some problems related to flex as changing `flex-direction` fixed the problem on FF.  I also found that not setting `height` option for Handsontable, but setting `width` to `100%` value also broke the table. However, after a research, I conclude that it may be strictly related to the `overflow` property as @AMBudnik suggested in the above comment. I can see that https://github.com/handsontable/handsontable/issues/3432 issue shown similar case, although it seems that the other issue is related also to Chrome. What's more I tried to understand complex user's example and its compliance with CSS principles. Even if it has some redundant stuff, the table should insert itself to a container.

I experimented a little bit with changing a way how height for master element is calculated (I'm not sure whether trimming container is chosen properly), but I need a moment more time for finding the best solution.

**Comment by aninde** [comment] 2022-10-20 14:31
The original demo works with the upcoming  Handsontable version 12.2 https://jsfiddle.net/aninde/g527ehv9/1/ on Firefox 83 via Browserstack on Firefox 93 / macOS and Windows 11.

**Comment by warpech** [comment] 2022-10-24 10:23
The problem is fixed in PR https://github.com/handsontable/handsontable/issues/9545. We agreed on the today's planning meeting that the PR is missing a test. One or two tests will be added by @wszymanski.

**Comment by aninde** [comment] 2022-10-26 07:37
I opened a new issue to create a test https://github.com/handsontable/handsontable/issues/10061.

**Comment by AMBudnik** [comment] 2022-10-26 08:07
Hi @JuanjoArmellino.

We just released Handsontable v12.2.0 where the reported issue is fixed. Please update and let me know if it works for you.
I'm closing the issue as done. But if you'd have any additional questions or concerns, please leave a comment.

**Closed by AMBudnik** 2022-10-26 08:07 UTC
Labels: Firefox
