### ISSUE TITLE
[Bug]: Custom rendering not working as expected on Handsontable upgrade from 11.0.0 to 13.0.0

### ISSUE THREAD

**Issue by HiraSMahambre** [handsontable/handsontable#10451] opened 2023-07-19 10:26 UTC
### Describe the bug

Hi team,

When we upgraded the handsontable version from 11.0.0 to 13.0.0, the custom renderers stopped working properly.

In some of our some cases, the renderer can change based on what else is going on in that row. So we have set the it at the cell level, not at column level with - 
“cellProperties.renderer = renderer;”

On debugging, I noticed that sometimes the custom renderer is not at all getting triggered. I downgraded the version and found this issue happening from version 12.2.0.

One workaround I could think of for the above issue is setting the renderer on both column & cell level. However, it does not sound correct to set the same renderer in two places.

Found a similar issue reported here - https://github.com/handsontable/handsontable/issues/10116 .

As of now, we have downgraded the version to 12.1.0 until we have a fix for this issue. 

Thanks.

### Handsontable version

13.0.0

### Your environment

Browser name and version: Chrome, Operating system: Mac OS, Windows

**Comment by adrianszymanski89** [comment] 2023-07-19 10:39
Closed as duplicate of: https://github.com/handsontable/handsontable/issues/10450

**Closed by adrianszymanski89** 2023-07-19 10:39 UTC
Labels: bug
