### ISSUE TITLE
[8.1] Transform property issue

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9054] opened 2021-12-21 12:55 UTC
### Description
While using the transform CSS property the highlight isn't rendered correctly. It's a regression to version 8.0.0 and occurs since version 8.1.0.

### Steps to reproduce
1. Select any row to see the issue.

### Demo

Wrong behaviour:

https://jsfiddle.net/6kux9ewg/ v8.1

![Nagranie z ekranu 2021-12-21 o 13 48 47](https://user-images.githubusercontent.com/92314130/146933436-ce8ac65f-05f3-4c16-a492-900dc360a2ba.gif)

Correct behaviour:

https://jsfiddle.net/aszymanski/84swqhnk/ v.8.0.0

![Nagranie z ekranu 2021-12-21 o 13 49 47](https://user-images.githubusercontent.com/92314130/146933460-a54b161b-310a-4f62-8540-cc194556b246.gif)

### Your environment
* Handsontable version: 11.0.1
* Browser Name and version: Chrome 96.0.4664.110
* Operating System: MacOS Monterey 12.0.1

**Comment by wangyapeng** [comment] 2021-12-22 07:41
how long this issue can close? can you merge it to version 11.0?

**Comment by AMBudnik** [comment] 2021-12-23 12:52
Hi @wangyapeng 

This issue hasn't been scheduled to fix yet. I will keep you updated via Github as soon as we fix it.

**Comment by AMBudnik** [comment] 2023-01-23 07:39
Hi @wangyapeng 

We tested this issue with the latest version of Handsontable - 12.3.0 and the issue is in longer replicable. I tested Chrome and Firefox, and on both of the browsers, we get the desired result

![Zrzut ekranu 2023-01-23 o 08 33 33](https://user-images.githubusercontent.com/10757813/213987564-a0b5be73-f728-42c0-a3fd-85a300901bdb.png)
cell selection

![Zrzut ekranu 2023-01-23 o 08 35 48](https://user-images.githubusercontent.com/10757813/213987566-56961dbd-9e78-4419-b25b-8fe114be9c5a.png)
cell and header selection

so I am closing this issue as solved.

**Closed by AMBudnik** 2023-01-23 07:39 UTC
Labels: bug, Regression, Reported
