### ISSUE TITLE
[8.0.0+] HiddenColumns plugin causes unintended scrolling when some cells are hidden

### ISSUE THREAD

**Issue by sinbino** [handsontable/handsontable#7322] opened 2020-10-07 18:39 UTC
### Description

After hiding some columns with the "HiddenColumns" plugin, when starting to edit a cell to the right of the hidden column, the editor becomes invisible due to unnecessary scrolling.

### Steps to reproduce

1. see jsfiddle
2. The F~J columns are hidden.
3. Move the cursor over the cell in column K and press enter or type in the appropriate characters to start editing.
4. The table will scroll to the left and you won't see the cell you are editing.

### Demo

https://jsfiddle.net/sinbino/x8vej6og/132/

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Chrome  85.0.4183.121
* Operating System: MacOS Catalina 10.15.7

**Comment by AMBudnik** [comment] 2020-10-08 06:59
Thank you for sharing the issue report @sinbino 

#### testing
I have replicated the scenario and got the same unwanted scroll. 
It works the same on Chrome 85, Firefox 81, and Safari 14 on my macOS Catalina 10.15.6.

#### versions
https://jsfiddle.net/AMBudnik/gc67durb/ - 7.4.2 - doesn't seem to be affected
https://jsfiddle.net/AMBudnik/z9prga2n/ - 8.0.0 - was the first one to show the difference
This issue is a regression of v 8.0.0.

#### additional notes
The scroll seems to be triggered only when we type value is a cell that is on the right of the hidden columns group. If I fix `3` columns and type anything in `D` or `E` columns I'm not scrolled.

Interestingly, when I comment out `rowHeaders` I get the scroll on `L` column, `K` is not effected https://jsfiddle.net/AMBudnik/amx7zgon/ so it seems that the number of elements matters.

The presence of `colHeaders` and the number of rows or columns totally doesn't seem to change anything.

**Comment by aninde** [comment] 2020-11-03 15:27
@sinbino I'm glad to see that this issue will be fixed by the upcoming v8.2.0 https://jsfiddle.net/voufkh42/

![8 2 0fix](https://user-images.githubusercontent.com/30186818/98005455-55e00280-1df1-11eb-8a9e-498c87f41274.gif)

Tested on macOS Catalina 10.15.7

- Chrome Beta 87 and stable 86
- FF 83.0b7 and stable 82
- Safari 14 and Safari Technology Prev 14.1

Windows 10
- Chrome 86
- Edge 86
- Edge Dev 88

**Comment by sinbino** [comment] 2020-11-04 01:26
@AMBudnik @aninde
Thank you!

**Comment by AMBudnik** [comment] 2020-11-05 13:14
I'm reopening this ticket as we should close it after confirming that it works with the officially deployed v 8.2.0

**Comment by sinbino** [comment] 2020-11-09 16:39
When will handsontable 8.2.0 be released?
Please let me know if you can give me a rough estimate.

**Comment by AMBudnik** [comment] 2020-11-10 06:52
Hi @sinbino we are doing a code freeze. We plan to publish v8.2.0 this week if everything goes well.

**Comment by AMBudnik** [comment] 2020-11-16 10:10
Hi @sinbino We've updated Hansontable to v.8.2.0 on Thursday. Please let me know if it works for you well after updating.

**Closed by AMBudnik** 2020-11-16 10:10 UTC
Labels: Fixing, Hiding, Regression, Type: Bug, scroll

**Comment by sinbino** [comment] 2021-01-28 01:11
I apologize for the very late reply.
I have confirmed that the problem has been resolved in 8.2.0.
Thank you.

**Comment by AMBudnik** [comment] 2021-01-28 07:00
Thank you for the confirmation @sinbino
