### ISSUE TITLE
jquery and prototype conflict in 0.24.x

### ISSUE THREAD

**Issue by mkprz** [handsontable/handsontable#3511] opened 2016-05-17 20:43 UTC
When upgrading from 0.23.0 to 0.24.3, I was getting the following error in javascript console:
Uncaught TypeError: Cannot set property 'handsontable' of undefined
in file handsontable.full.js, line 68

At line handsontable.full.js line 68 there is the following:

```
if (window.jQuery) {
  $.fn.handsontable = function (action) {

```

Unfortunately, we are in  transition from prototype to jquery, so both frameworks are loaded into the system. $ is calling the prototype version of this function, and not the jquery version as expected in the handsontable library.

The following single change seems to work for me.
```
if (window.jQuery) {
  jQuery.fn.handsontable = function (action) {
```

**Comment by AMBudnik** [comment] 2016-05-19 12:23
Hi @mkprz thanks for sharing.
Could you also share a demo where we can reproduce the error logs?

**Comment by TobiasBg** [comment] 2016-06-01 08:57
This is a duplicate of #3403, which also contains a link to a demo.
The suggested fix is what works for me as well.

**Comment by AMBudnik** [comment] 2016-06-01 08:59
OK, thanks @TobiasBg 
so I'm closing this issue and we'll stick to #3403

**Closed by AMBudnik** 2016-06-01 08:59 UTC
Labels: Demo needed
