### ISSUE TITLE
Carriage return inserted inside string when pasting from Excel, but not from text

### ISSUE THREAD

**Issue by rvictordelta** [handsontable/handsontable#5647] opened 2018-12-07 13:55 UTC
### Description
When pasting a long string that contains a space from Excel into Handontable, a carriage return character is inserted next to the space.  This does not happen when pasting text from other sources.

I could not find a pattern for the length of the string, but it seems to occur if the string is longer.

It appears this was not an issue in 6.0.1, but is an issue in 6.2.0

### Steps to reproduce
1. Input string with length greater than ~22 and containing a space into an Excel cell
2. Copy the cell from Excel into a handsontable
3. Note that a carriage return is inserted next to the space

### Demo

http://jsfiddle.net/gbL6mj4v/

### Your environment
* Handsontable version: 6.2.0
* Browser Name and version: Chrome 70
* Operating System: Windows 7

**Comment by AMBudnik** [comment] 2018-12-07 14:32
Thank you for sharing @rvictordelta 

this issue should be fixed with https://github.com/handsontable/handsontable/issues/5477

**Comment by AMBudnik** [comment] 2018-12-12 13:56
It looks like it works the same in v `6.2.1` so #5477 did not fix it.

@rvictordelta do you get the same result?

Excel
![image 1](https://user-images.githubusercontent.com/10757813/49874155-091a6980-fe1e-11e8-8359-363af113104d.png)

Handsontable
![image](https://user-images.githubusercontent.com/10757813/49874160-0cadf080-fe1e-11e8-8c5d-e82eace12ce5.png)

**Comment by gregiare** [comment] 2018-12-13 16:13
I also get the same results with 6.2.1 if I paste lines like this from Excel.

Bridge Drawing 1
Bridge Drawing 2
Bridge Drawing 3
Bridge Drawing 4
Bridge Drawing 1
Bridge Drawing 2
Bridge Drawing 3
Bridge Drawing 4
Bridge Drawing 1
Bridge Drawing 2

**Comment by AMBudnik** [comment] 2018-12-14 14:19
Thank you for feedback @gregiare 

I thought that it might be related to what we had here https://github.com/handsontable/handsontable/issues/5477 but after fixing https://github.com/handsontable/handsontable/issues/5477 this issue still remains.

**Comment by andrewQwer** [comment] 2019-02-07 07:44
This happens because when cell is copied its data looks like html content with `table/td` tags. Something like this:
```
<large html>
<table>
<td>Text copied
             from Excel</td>
<large html>
```
For some reason copied text has line breaks inside `<td>` even if there are no any line breaks in original text entered to the Excel cell. For html it is not considered as line break, but when `CopyPaste` plugin parses it using `tableToArray(textHTML);` there is a row inside `tableToArray` function: `cell.innerHTML = cell.innerHTML.trim().replace(/<br(.|)>(\n?)/, '\n');` So as you may see all `<br/>` tags **and** `\n` occurrences are converted to `\n`

**Comment by gregiare** [comment] 2019-02-22 14:15
This is caused by the way Excel puts data into the html clipboard. It also has a problem when a column of data has repeating number sequences. In some cases it will replace the repeating values with #. I have fixed this in my copy of hansontable.full.js by commenting out the following block;

`var textHTML = event.clipboardData.getData('text/html');

if (textHTML && /(<table)|(<TABLE)/.test(textHTML)) {
  pastedData = (0, _utils.tableToArray)(textHTML);
} else {
  pastedData = event.clipboardData.getData('text/plain');
}`

And adding the following line;

`pastedData = event.clipboardData.getData('text/plain');`

This basically stops it from getting the pasted data from the html clipboard and gets it from the plain text clipboard instead. I have seen no issues with pasting from Excel after doing this. I can't say whether it will cause issues when pasting from other applications because the bulk of my users want to paste from Excel.

**Comment by AMBudnik** [comment] 2019-06-12 07:40
This issue has been solved with https://github.com/handsontable/handsontable/issues/5684 in v `7.1.0`. Again, thank you for sharing :)

**Closed by AMBudnik** 2019-06-12 07:40 UTC
Labels: Copy-paste, Type: Bug
