### ISSUE TITLE
Cell type cannot be changed via setCellMeta

### ISSUE THREAD

**Issue by indiecollin** [handsontable/handsontable#4793] opened 2018-02-10 00:28 UTC
I'm currently trying to get my cell types to update dynamically using getCellMeta and updating the object that is passed back. I see that it works the first time, but any subsequent calls leaves the cell type as what it was changed to the first time. Is there a way around this? I've tried to use cells functions too, but that causes a bigger issue with my dropdown sources not updating properly so I'd rather get it to work this way as it requires a lot less reworking on my part.

It seems like a straightforward issue so I hope this suffices, but I can a fiddle or codepen if really needed.

//Initiate the handsontable, all the cells are of type text
//set specific cell to be of type dropdown
let cellProperties = instance.getCellMeta(0, 0);
cellProperties.type = 'dropdown';
cellProperties.source = [''value1,'value2'];

//now set specific cell to type text
let cellProperties = instance.getCellMeta(0, 0);
cellProperties.type = 'text';

ng-handsontable 0.13.0
Google Chrome 64.0.3282.119 (Official Build) (64-bit)
Windows 10

I appreciate any help available!
Thanks

**Comment by indiecollin** [comment] 2018-02-12 22:22
Hello @AMBudnik 

Thanks for responding to my issue.

Is there a possible workaround I can use in the meantime? I know it might not be easy to estimate, but how long do bugs typically take to get patched?

**Comment by AMBudnik** [comment] 2018-02-13 08:12
Hi @indiecollin 

it looks like we can't change the type as a whole scheme, but we can change the `renderer`. Here's an updated demo

http://jsfiddle.net/43j99mbs/
![gif](https://user-images.githubusercontent.com/10757813/36139298-3e62cb2e-109d-11e8-9908-4f5563b9af08.gif)

FYI:
dropdown cell type uses: [`DropdownEditor`, `autocompleteRenderer` and `autocompleteValidator`.](http://jsfiddle.net/yhnm366q/)
Let me know if you need anything more than that to continue.

**Comment by indiecollin** [comment] 2018-02-14 18:02
Hello @AMBudnik 

Thank you so much for your help with this. I was able to get it working with changing the renderers and another minor workaround I figured out. I also would like to thank you for being so active in supporting development with Handsontable in general. While I was browsing through google results your responses came up frequently and were very helpful for my research and development.

 People like you making development great and please know you are appreciated!

**Comment by AMBudnik** [comment] 2018-02-15 07:43
Hi @indiecollin 

Thank you so much for your kind words. You made my day :)

**Comment by AMBudnik** [comment] 2018-08-23 12:46
The issue is still replicable in v5.0.1 http://jsfiddle.net/1qhzugL9/

**Comment by AMBudnik** [comment] 2020-07-07 12:24
**Works** well in 8.0.0-beta1-rev19 http://jsfiddle.net/th2cjvw4/ - we get the blue `***` (cell type changed to password).

It **did not work** in 8.0.0-beta1 http://jsfiddle.net/Lx7y1vp9/ and 7.4.2 http://jsfiddle.net/Lx7y1vp9/1/

**Comment by pnowak** [comment] 2020-07-16 10:39
Hi @indiecollin 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment] 2020-08-06 06:40
Hi @indiecollin I have good news! Handsontable v8.0.0 that solves this issue was just released.

I highly encourage you to test the new version and leave some feedback. I hope that the amount of work that we put on the v8 will help you to improve your project.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases

**Closed by AMBudnik** 2020-08-06 06:40 UTC
Labels: Type: Bug
