### ISSUE TITLE
Rows with large height do not render on scroll until resize

### ISSUE THREAD

**Issue by pthurlow** [handsontable/handsontable#2731] opened 2015-08-14 21:20 UTC
It appears the new autoRowSize module has introduced weird rendering issues when row heights are larger than the table window.  [in this example](http://jsfiddle.net/utojx2v9/1/) on initial load, if you scroll the table the rows beyond the first row do not render.  If you resize the window they will then appear.  This does not happen with any handsontable version before 0.16. [Here is the same code](http://jsfiddle.net/47m4cfr6/2/) from 0.15.1

**Comment by AMBudnik** [comment] 2015-08-15 14:18
Hello @pthurlow thank you, I confirm that there's no visible rows other than first one in latest version.

**Comment by AMBudnik** [comment] 2016-03-03 13:15
replicable in 0.23.0, demo: http://jsfiddle.net/utojx2v9/4/

**Comment by AMBudnik** [comment] 2018-04-16 11:16
The issue is still replicable in v `2.0.0` http://jsfiddle.net/jr07z1cm/
This issue is old. It doesn't seem to work in any of previous versions of Handsontable.

**Comment by wojciechczerniak** [comment] 2019-01-31 13:11
Duplicate of #3448

**Closed by wojciechczerniak** 2019-01-31 13:11 UTC
Labels: Core: alignment/height/width, Type: Bug
