### ISSUE TITLE
 Scrolling is not possible when "preventOverflow" is used in FireFox, IE 11, Edge

### ISSUE THREAD

**Issue by sho-srvno1** [handsontable/handsontable#4971] opened 2018-03-28 06:57 UTC
### Description
When "preventOverflow" is used, if there is a mouse pointer on the area of HOT, scrolling is impossible.
Chrome works normally, but I tried it with IE11, FireFox, Edge, but I could not scroll.
Do you have any workarounds?

### Steps to reproduce
1.Please use the IE 11 to access the URL of the demo.
2.Move the mouse cursor to the area of ​​Hot and scroll the mouse
IE 11: Does not work
Chrome: Can scroll

### Demo
[jsfiddle](https://jsfiddle.net/handsoncode/xugydsf4/?utm_source=website&utm_medium=embed&utm_campaign=xugydsf4)

### Your environment
* Handsontable version:0.38.1
* Browser Name and version:IE11,FireFox 59.0,Edge
* Operating System:Windows10

**Comment by AMBudnik** [comment] 2018-03-28 07:10
Thank you for sharing the issue report @sho-srvno1 

I have tested Chrome, FF, Edge and IE and it only works on Chrome. On Edge it scrolls only a border of a header?

![gif](https://user-images.githubusercontent.com/10757813/38014100-c2232df0-3267-11e8-95a8-b1341e1ff56d.gif)

**Comment by sho-srvno1** [comment] 2018-03-28 07:24
Thank you for replying @AMBudnik 

> On Edge it scrolls only a border of a header?

Yes. It works just like a Gif you stretched.

Is [#4930](https://github.com/handsontable/handsontable/pull/4930) another problem?
Is it also possible to avoid it with some setting?

**Comment by AMBudnik** [comment] 2018-03-28 07:42
I've tested #4930 but this PR doesn't fix the behavior with the above demo

**Comment by AMBudnik** [comment] 2018-12-28 09:39
Still replicable in v `6.2.2` on FF

**Comment by phaibin** [comment] 2019-04-15 11:38
Newest handsontable 7.0.2, tested on all browsers on Win10 and Mac, only Chrome on Mac works. The stranger thing is Chrome on Win10 has the same version as Mac's: 73.0.3683.103, but can't work either.

Is there some other way to fix this? Like using JS to pass the mouse wheel event to outer page. Please help!

**Comment by AMBudnik** [comment] 2019-04-15 12:17
Hey. What's your configuration @phaibin ? You can use this demo as a base https://jsfiddle.net/handsoncode/xugydsf4/175/ to create a demo

**Comment by phaibin** [comment] 2019-04-15 13:14
@AMBudnik Please reference this demo: https://jsfiddle.net/t8735mg4/.

This demo is just like sho-srvno1's. When mouse is in hot table section. You can scroll horizontal, but you can't scroll the whole page.

This happens in every browser except Chrome in macOS.

**Comment by AMBudnik** [comment] 2019-04-16 11:47
You're right. Thank you for sharing the demo. I may imagine that this happens cause Handsontable is stealing the events. Maybe there will be a chance to set the focus on a different element when the last row is visible but I haven't tried it.

**Comment by wojciechczerniak** [comment] 2019-04-30 09:00
Duplicate of #5212

**Closed by wojciechczerniak** 2019-04-30 09:00 UTC
Labels: Core: compatibility, Type: Bug
