### ISSUE TITLE
when set `stretchH: 'all'`, how to support auto width with css padding

### ISSUE THREAD

**Issue by dx0eu** [handsontable/handsontable#6927] opened 2020-05-24 02:27 UTC
### Description

How to set auto width when I use padding. Now in a container with padding, the width of handsontable will not change automatically, the right side will be hidden.
And the height not use auto, will calc parent dom height. But when my container is full height, the handsontable height is wrong.

### Steps to reproduce

1. Set parent dom css:   padding: 50px; min-height: calc(100vh - 50px); position: relative; overflow: hidden;
2. Add body { height: 100% }

### Demo

https://jsfiddle.net/jtgf316v/9/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Firefox 77.0b7 (64-bit)
* Operating System: Win 10

**Comment by AMBudnik** [comment] 2020-05-25 10:42
HI @dx0eu 

thank you for sharing your concerns and mentioning this subject.

This

![Zrzut ekranu 2020-05-25 o 12 35 09](https://user-images.githubusercontent.com/10757813/82805355-30cf8700-9e84-11ea-9552-0424837e86f3.png)

is what I get in Chrome, and it's definitely not the desired result. I believe that this happens, as we add different z-indexes to layers of Handsontable.
The issue is also replicable of we use `colWidths` instead of `stretchH` https://jsfiddle.net/AMBudnik/2qaejd74/

**Comment by AMBudnik** [comment] 2020-05-26 06:23
@dx0eu reasonable 👍 , Handsontable does not fully support overflows, when it displays all the layers (headers, fixed rows/columns). But that subject has been already raised here https://github.com/handsontable/handsontable/issues/6744 so I think that we can close this topic. What do you think?

**Closed** 2020-05-26 06:27 UTC
Labels: Core: alignment/height/width, Type: Bug
