### ISSUE TITLE
Autocomplete doesn't update list on paste

### ISSUE THREAD

**Issue by lulezi** [handsontable/handsontable#4800] opened 2018-02-14 09:29 UTC
### Description
If I paste a value into the opened autocomplete editor, the paste event is not recognized and thus the list is not filtered.

### Steps to reproduce
1. Double click cell with type autocomplete
2. Paste something

### Demo
![2018-02-14 10_24_20](https://user-images.githubusercontent.com/870062/36196706-dea1419a-1171-11e8-9ab2-d7ae8c19b64f.gif)

### Your environment
* Handsontable version: 1.15.1
* Browser Name and version: Chrome 60
* Operating System: macOS Sierra

**Comment by AMBudnik** [comment] 2018-02-14 14:34
Hi @lulezi 

It seems to work fine on higher versions of the browser. 

I'm using Chrome 64 and with this demo https://docs.handsontable.com/pro/1.15.1/demo-autocomplete.html it looks like well for `Paste` menu option and the <kbd>CTRL/CMD</kbd> + <kbd>V</kbd> key combination.

![gif](https://user-images.githubusercontent.com/10757813/36209603-6cc4a85c-119c-11e8-8a39-fd9945a224ed.gif)

Am I missing anything? Can you update the browser and check it again?

**Comment by AMBudnik** [comment] 2018-02-20 08:57
I am closing the issue as there is no reply for a week but feel free to let me know if I've missed anything crucial.

**Comment by lulezi** [comment] 2018-02-20 16:38
Hi @AMBudnik 

Sorry for the late reply, I missed the notification.

I just tested in the newest version of Chrome (64.0.3282.167) and seems to persist.

In the «Bumper Color» field, if you type "bl" manually it filters the suggestions correctly and only shows «black» and «blue». However, if you paste «bl» with right click the suggestions are not filtered at all.

**Comment by AMBudnik** [comment] 2018-02-21 08:13
Oh OK. I can see what you mean now. It does not happen for the key combination, only for the menu paste.

**Comment by swistach** [comment] 2018-05-17 10:15
Thank you @lulezi for your report.
I figured out the problem. The bug is in line 81 of `autocompleteEditor`:
https://github.com/handsontable/handsontable/blob/master/src/editors/autocompleteEditor.js#L81

We listen to only `beforeKeyDown` event. I think we should add a listener for `input` event instead. Of course with a polyfill for IE.

**Comment by AMBudnik** [comment] 2018-08-17 09:46
Hi @lulezi please update the library. The issue is no longer replicable in v 5.0.1
https://docs.handsontable.com/pro/5.0.1/demo-autocomplete.html

**Closed by AMBudnik** 2018-08-17 09:46 UTC
Labels: Cell type: autocomplete / dropdown / handsontable, Type: Bug
