### ISSUE TITLE
Frozen Header, Input Element Data is Lost on Scroll

### ISSUE THREAD

**Issue by KirsteenJewell** [handsontable/handsontable#3886] opened 2016-11-14 10:52 UTC
### Description

I have added input text elements to HoT headers to allow my users to search (server side/AJAX). I have implemented this search, however upon scroll down the data is intermittently cleared from the input box. HoT manipulates the header upon scroll and seems to display an alternate and empty version of the element. 

The user's text in the search input box should be maintained in the frozen header regardless of page scroll action.   

### Steps to reproduce

1. HoT container with some data and colHeaders. Include HTML input text element in colHeaders for each/any column 
2. Enter some text into the input text box
3. Scroll down the page until data is cleared. If the effect is not seen reload the page and try again until behaviour is observed. 
Note you may need to reduce the page size to facilitate an adequate scroll to observe the data being cleared.

### Demo

[http://jsfiddle.net/Jewell/bumphwc9/](http://jsfiddle.net/Jewell/bumphwc9/)

### Your environment
* Version: 0.29.0
* Browser Name and version: Chrome Version 53.0.2785.143 (64-bit)
* Operating System: Linux Mint 17 Qiana

**Comment by AMBudnik** [comment] 2016-11-14 13:31
Hi @KirsteenJewell 
Can you record a short video where this issue happens? I tried Chrome 54 with Hot v0.29.0 on Win 10 several times with no luck.

**Comment by KirsteenJewell** [comment] 2016-11-14 14:48
Hi @AMBudnik 
A short screencast for you to see the issue:
[Screencast 2016-11-14 14:46:46.mp4.zip](https://github.com/handsontable/handsontable/files/589577/Screencast.2016-11-14.14.46.46.mp4.zip)

**Comment by AMBudnik** [comment] 2016-11-15 07:24
Thanks for sharing,
I've added more rows to the example and got the same result.

When we add `renderAllRows: true` the issue stops so I guess that this has something to do with the viewport. 

I'm setting this issue as a bug. Thanks for sharing @KirsteenJewell

**Comment by KirsteenJewell** [comment] 2016-11-16 07:20
Using `renderAllRows: true` solves the issue for me. Thanks @AMBudnik

**Comment by AMBudnik** [comment] 2016-11-16 10:22
you're welcome @KirsteenJewell

**Comment by nadim** [comment] 2017-07-19 21:37
`renderAllRows: true` fixes the issue for me for vertical scrolling, but if my table needs to scroll horizontally, when i scroll back over to the header with the `<input>` it has been cleared.

Any update on this issue?

**Comment by AMBudnik** [comment] 2017-07-20 08:34
As mentioned in another ticket, for some project using `viewportColumnRenderingOffset` can be a workaround. However, you should remember that rendering all your data at once can lower the overall performance.

**Comment by swistach** [comment] 2018-07-12 08:20
Duplicate of #1540.

**Closed by swistach** 2018-07-12 08:20 UTC
Labels: Type: Bug
