### ISSUE TITLE
Ctrl+click to deselect cell

### ISSUE THREAD

**Issue by Xenorage** [handsontable/handsontable#7154] opened 2020-07-29 03:53 UTC
Description
Behavior:
So when I use ctrl+click to select a cell fist it selects it then every click on it will make it darker blue.
hot2.getSelected(); returns an array with the same cell id as many times I clicked it.

What I want it to do:
When I use ctrl+click on an unselected cell it should select it next click on it should deslecet only that cell.
hot2.getSelected(); should return only one id from a selected cell doesn't matter how many times it was ctrl+cliked.

Steps to reproduce
https://jsfiddle.net/b81u4m3f/
Ctrl+Click on one cell many times slowly so you wont enter editor.
Click on Get data to see selected array contains the same cell as many times you clicked.

Your environment
Handsontable version: 7.4.2
Browser Name and version: chrome 83.0.4103.116
Operating System: win 7

**Comment by pnowak** [comment] 2020-07-29 12:31
Hi @Xenorage 

This is an interesting case and definitely unexpected behaviour. 

Thank you @Xenorage for reporting.

**Comment by pnowak** [comment] 2020-07-29 13:14
I change my mind.
`getSelected` returns all non-contigious selection layers. If you only want them once it's `getSelectedLast` method. Additionally, if you don't want multiple selections you can switch `selectionMode` to `range`.

Furthermore, I found a such feature request - https://github.com/handsontable/handsontable/issues/5737 

So I close the issue as a duplicate, not a bug.
Thank you @Xenorage again.

**Closed by pnowak** 2020-07-29 13:14 UTC
Labels: Core: selection, Type: Bug

**Comment by Xenorage** [comment] 2020-07-30 08:53
> I change my mind.
> 
> `getSelected` returns all non-contigious selection layers. If you only want them once it's `getSelectedLast` method. Additionally, if you don't want multiple selections you can switch `selectionMode` to `range`.
So its a feature that you can select the same cell many time but you cant deselect it? 
And you dont want to provide a feature to unselect a single cell?
> 
> Furthermore, I found a such feature request - #5737
> So I close the issue as a duplicate, not a bug.
> 
> Thank you @Xenorage again.

**Comment by AMBudnik** [comment] 2020-08-04 11:46
Hi @Xenorage 

> When I use ctrl+click on an unselected cell it should select it next click on it should deslecet only that cell.
> hot2.getSelected(); should return only one id from a selected cell doesn't matter how many times it was ctrl+cliked.

In the demo you use the multi-layer selection **line 13** `selectionMode: 'multiple', // 'single', 'range' or 'multiple'`. When you change 'multiple' to 'range' the background does not change. Then when you use `getSelected()` method it always returns a single array https://jsfiddle.net/sbm3degc/.

Let me know if it meets your requirements.
