### ISSUE TITLE
 Tapping on a header or a cell on some iOS devices causes the onscreen keyboard to show up

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#7414] opened 2020-11-26 11:11 UTC
### Description
On several (but not all) iOS devices, there are unwanted results when tapping on a header or a cell - the on-screen keyboard pops up and the editor shows up.

This problem only appears on some iOS devices (see below). It does not happen on Android/Chrome.

This was originally reported in https://github.com/handsontable/spreadsheet-viewer-dev/issues/875, but we found a workaround there (configure `copyPaste: false` on mobile devices).

### Steps to reproduce

1. Go to https://handsontable.com/examples
2. Repeat some of the below actions:
   - tap on a read-only cell:
      - expected: the cell becomes selected
      - actual: the cell becomes selected + the keyboard pops up
   - tap on an editable cell:
      - expected: the cell becomes selected
      - actual: the cell becomes selected + the keyboard pops up + the editor shows
   - tap on a column or row header:
      - expected: the row or column becomes selected
      - actual: the row or column becomes selected + the keyboard pops up

### Demo
https://handsontable.com/examples

### Your environment
* Handsontable version: 8.2.0 (also seen in earlier versions)
* Browser Name and version: Safari
* Operating System:
   - physical iPad Air 2019 (with iOS 13.3.1)
   - physical iPad 6 gen (with iOS 14.0.1)
   - BrowserStack iPad Pro 12.9 2020

![IMG_0017](https://user-images.githubusercontent.com/566463/100344011-73fbe580-2fe0-11eb-98d7-142a3d40846e.PNG)

**Comment by warpech** [comment] 2020-11-26 11:12
@nikersify made some investigation in https://github.com/handsontable/spreadsheet-viewer-dev/issues/875 and this is what he wrote: 

------

Quick investigation shows that this is a problem with the `textarea.HandsontableCopyPaste` element that gets added to the DOM upon the first cell selection.

Setting `display: none` on it with CSS stops the keyboard from popping up on the iPad, however it also breaks the copy functionality for the desktop.

---

Seems like it's possible to retrieve the added element with JS:

```js
hotInstance.getPlugin('copyPaste').focusableElement.mainElement;
```

But I'm not sure how much would that help, since Handsontable seems to rely on `execCommand` which requires `.focus()` so disabling that element would probably not work properly for both cases.

**Comment by nikersify** [comment] 2020-11-30 13:40
This might be happening because the user agents on (new?) iPadOS versions are the same as on macOS (as opposed to before when iPad's were running plain iOS and were providing iPad specific user agents). Adding an additional check and disabling the copy paste plugin fixed our problem (https://github.com/handsontable/spreadsheet-viewer-dev/pull/887/files#diff-8aec3b525cf30f4e549b52bedee45e9be074e3bd74982550e25cf6d70926be7e).

**Comment by eribean** [comment] 2021-01-29 04:18
Is there a solution to this, the original links are no longer functioning?

**Comment by AMBudnik** [comment] 2021-01-29 09:24
Hi @eribean this issue hasn't been officially fixed yet. I will ping you up when it does.

**Comment by eribean** [comment] 2021-01-29 12:49
@AMBudnik any eta on this? Would it be useful to add this to the Forum on the website?

**Comment by AMBudnik** [comment] 2021-02-08 14:20
This issue is closed temporarily. It will be reopened for development as it became a part of **Interoperability problems using Mobile devices and some core features** task reported at https://github.com/handsontable/handsontable/issues/7520

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment] 2024-02-19 09:10
Hi @eribean We just made some checks on iPhone and iPad, and it seems that the issue is no longer replicable. I will close it as solved. however, would love to hear your feedback if there's anything we missed.

**Closed** 2024-02-19 09:10 UTC
Labels: Headers, Mobile, Part of scope, Reported
