### ISSUE TITLE
Table not aligned after CSS modifications

### ISSUE THREAD

**Issue by amoghmalik** [handsontable/handsontable#3642] opened 2016-07-07 11:34 UTC
The table is not aligned at the bottom. While scrolling (Left and Right) there is a noticeable difference in the height. 

Demo: https://jsfiddle.net/wg37sw51/9/
GIF: 
 ![demo](https://cloud.githubusercontent.com/assets/15077731/16651671/d16ea634-4445-11e6-973f-785eccc4e440.gif)

This occurs when I modify the border in CSS (particularly the border-style within border). The issue does not occur when I only use border-style or any other border property. 

Tested Version: 51.0.2704.103 (64-bit) (Chrome)

**Comment by amoghmalik** [comment] 2016-07-07 11:43
#3459

**Comment by swistach** [comment] 2016-10-11 08:26
It's duplicate of #3546

**Closed by swistach** 2016-10-11 08:26 UTC
Labels: Priority: normal, Type: Bug
