### ISSUE TITLE
[8.0.0.-beta2-rev1] nestedHeaders and hiddenColumns don't work together

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6879] opened 2020-05-13 12:50 UTC
### Description
If we set both plugins, not all column headers are displayed.
<img width="376" alt="Zrzut ekranu 2020-05-13 o 14 44 31" src="https://user-images.githubusercontent.com/1555809/81814372-fb907400-9528-11ea-8f69-c66d42aa0526.png">

7.4.2 - https://jsfiddle.net/53dmngb7/1/
<img width="372" alt="Zrzut ekranu 2020-05-13 o 14 44 48" src="https://user-images.githubusercontent.com/1555809/81814429-119e3480-9529-11ea-99a3-1e457010314c.png">

8.0.0. beta-1 - https://jsfiddle.net/7a4obtck/
<img width="374" alt="Zrzut ekranu 2020-05-13 o 14 44 39" src="https://user-images.githubusercontent.com/1555809/81814442-15ca5200-9529-11ea-95ff-a20db3a8ce40.png">

### Demo

https://jsfiddle.net/ep069nqy/1/

### Your environment
* Handsontable version: 8.0.0. beta-2-rev3
* Browser Name and version: Chrome 80
* Operating System: macOS Mojave

**Comment by AMBudnik** [comment] 2020-05-26 11:57
This was broken in 8.0.0-beta-rev1 https://jsfiddle.net/AMBudnik/dcohnzvu/

Here's a second case to check.

### Steps to reproduce

1. Click <kbd>Hide columns</kbd>
2. Scroll right to check the state of `nestedHeaders`.
3. Click <kbd>Show columns</kbd>

**Result**
There are `nestedHeaders` missing when we hide columns with the button.
![hide_bug_beta2rev1](https://user-images.githubusercontent.com/10757813/82896445-3f866e80-9f56-11ea-95f5-6e98242c2fed.gif)
_8.0.0-beta2-rev1 - 8.0.0-beta2-rev8 hiding issue_

### Demos
https://jsfiddle.net/AMBudnik/5c82p1xL/ 7.4.2 (works well)
https://jsfiddle.net/AMBudnik/0vfL8tm3/ (works well)
https://jsfiddle.net/AMBudnik/6cawp8n4/ **8.0.0-beta2-rev1 (broken)**
https://jsfiddle.net/AMBudnik/xa7ckLyh/ 8.0.0-beta2-rev8 (broken)

**Comment by aninde** [comment] 2020-07-06 12:03
Still broken on latest rev `8.0.-beta2-rev18` https://jsfiddle.net/ep069nqy/1/

**Comment by AMBudnik** [comment] 2020-08-04 08:48
We should also test cases reported here https://github.com/handsontable/handsontable/issues/7160 after fixing this issue.

**Comment by AMBudnik** [comment] 2020-08-28 13:29
stable v8.0.0 https://jsfiddle.net/AMBudnik/z87h1v2g/ looks like the mentioned revision

![Zrzut ekranu 2020-08-28 o 15 29 45](https://user-images.githubusercontent.com/10757813/91565999-51a3ee80-e943-11ea-8e7a-69810689597e.png)

**Comment by m4m4m4** [comment] 2020-09-23 09:11
Any ETA on this? Would love to upgrade to v.8 but this affects us heavily

**Comment by AMBudnik** [comment] 2020-09-29 11:08
Hi @m4m4m4 the issue is currently in development

**Comment by budnix** [comment] 2020-10-05 08:25
I add so that it does not disappear a PoC (unfinished) https://github.com/handsontable/handsontable/tree/feature/issue-6839

**Comment by aninde** [comment] 2021-05-05 13:10
This issue will be fixed by the v.8.4.0 
<img width="387" alt="Screenshot 2021-05-05 at 15 10 05" src="https://user-images.githubusercontent.com/30186818/117146000-08e6e400-adb4-11eb-9ccd-c32be24f608d.png">

Demo: https://jsfiddle.net/t01naufr/

**Closed** 2021-05-12 07:14 UTC
Labels: Hiding, Nested Headers, Regression, Status: Released, Type: Bug, focus/blur
