### ISSUE TITLE
column width size issue when freeze a paricular column.

### ISSUE THREAD

**Issue by basrita** [handsontable/handsontable#3331] opened 2016-03-16 15:48 UTC
Hi,

I am facing column width issue when freeze a column.The width of the freezed column will set to left most non freezable column.

Please help me in this regard.

Thanks in advance.

**Comment by krzysztofspilka** [comment] 2016-03-16 23:18
@basrita couldn't reproduce that. Can you create a create a simple jsfiddle and share it here? Thanks!

**Comment by basrita** [comment] 2016-03-17 06:32
hi,

Here is the js fiddle example http://jsfiddle.net/bosfLdht/3/ please try to
freeze the column D you can observe the width difference.

Thanks.

**Comment by AMBudnik** [comment] 2016-03-17 09:42
I got:
![bez tytulu](https://cloud.githubusercontent.com/assets/10757813/13842104/b8b9ad30-ec2c-11e5-8408-f2b712d47d1f.png)

The issue here is the fact that new positions of columns doesn't correspond the width of its content, right?

**Comment by basrita** [comment] 2016-03-17 09:48
yes  @AMBudnik

On Thu, Mar 17, 2016 at 3:12 PM, Aleksandra Budnik <notifications@github.com

**Comment by AMBudnik** [comment] 2016-03-17 11:03
I'm marking this as a bug.

**Comment by AMBudnik** [comment] 2016-09-09 09:43
Still present in 0.27.0

**Comment by AMBudnik** [comment] 2018-01-19 09:46
The behavior is not replicable in version 0.35.0. 
![zrzut ekranu 2018-01-19 o 10 46 12](https://user-images.githubusercontent.com/10757813/35144820-014ec1ac-fd06-11e7-9296-89afc62de152.png)

Updated demo http://jsfiddle.net/vhto61jp/

**Closed by AMBudnik** 2018-01-19 09:46 UTC
Labels: Core: alignment/height/width, Priority: normal, Type: Bug
