### ISSUE TITLE
Not able to change the name of the sub menus of the context menu 'alignment'

### ISSUE THREAD

**Issue by sunpc** [handsontable/handsontable#3807] opened 2016-10-12 13:48 UTC
### Description

I'm trying to use the custom configurations to assign new names of the context menu items.
It's ok for all of the items except the sub menus of 'alignment'
### Steps to reproduce

The code is as below:

``` javascript
"alignment": {
            name: 'Alignment',
          submenu: {
            items: [
                {key: 'alignment:left', name: 'Align to LEFT'},
              {key: 'alignment:right', name: 'Align to RIGHT'},
            ]
          }
         },
```

The sub menu items can be displayed on the context, but the functionality doesn't work.
### Demo

JSFiddle: http://jsfiddle.net/sunpc/pnt0ju01/
### Your environment
- Version: 0.28.3
- Browser Name and version: Firefox 49.0
- Operating System: Windows 7, 10 & Mac OS X

**Comment by AMBudnik** [comment] 2016-10-12 13:58
Thanks for sharing @sunpc 
I think that this issue is strongly related to https://github.com/handsontable/handsontable/issues/3533

**Comment by sunpc** [comment] 2016-10-13 02:01
Thanks for your prompt response @AMBudnik 
My case has only one level of the submenu though it could share the same RCA of #3533.
I'm actually trying to match the submenu with the predefined items in contextMenu plugin so I'm afraid the reason is that the custom configuration happens at the context menu only but the submenu is not considered by alignment.js.

**Comment by setWan** [comment] 2018-01-04 05:04
@sunpc Hello!left the name does not take effect to solve the problem?

**Comment by AMBudnik** [comment] 2018-01-04 07:43
Hi @setWan 
we have added [internationalization ](https://docs.handsontable.com/pro/1.15.0/tutorial-internationalization.html)which you can test. It allows you to change all labels in the same file. However, this issue is related to this one https://github.com/handsontable/handsontable/issues/3550 - a general submenu issue.

**Comment by AMBudnik** [comment] 2018-04-23 08:43
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by pnowak** [comment] 2020-09-02 11:17
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/um4ksheb/

**Comment by AMBudnik** [comment] 2021-04-09 07:55
It looks like we have the same issue here https://github.com/handsontable/handsontable/issues/3550 so we can close this issue.

I will notify everyone interested in the topic after fixing https://github.com/handsontable/handsontable/issues/3550

**Closed by AMBudnik** 2021-04-09 07:55 UTC
Labels: Context menu, Type: Bug
