### ISSUE TITLE
Calling getCellsMeta fails when called after copying cells while using hiddenColumns

### ISSUE THREAD

**Issue by john-swallow-cenduit** [handsontable/handsontable#7616] opened 2021-03-09 16:33 UTC
### Description
Take a grid and hide one of the columns. 
Use copy and paste to force the grid to add a new row.
Now call hot.updateSettings() - in the example given I update the readonly status of the grid. I am not even changing the value. It is sufficient to make the updateSettings call with hiddenColumns mentioned at all.

What should happen: updateSettings should run without error.
What actually happens: the updateSettings call blows with the error:

handsontable.full.min.js:34 Uncaught TypeError: Cannot read property 'values' of undefined
    at e.value (handsontable.full.min.js:34)
    at e.value (handsontable.full.min.js:34)
    at t.default.getCellsMeta (handsontable.full.min.js:34)
    at n.value (handsontable.full.min.js:46)
    at n.value (handsontable.full.min.js:46)
    at n.value (handsontable.full.min.js:46)
    at n.value (handsontable.full.min.js:40)
    at t.default.<anonymous> (handsontable.full.min.js:40)
    at e.value (handsontable.full.min.js:34)
    at t.default.runHooks (handsontable.full.min.js:34)

within my actual app (not in the jsfiddle) I get the fuller error:

'TypeError: Cannot read property 'values' of undefined
    at CellMeta.getMetas (http://localhost:4200/vendor.js:177540:62)
    at MetaManager.getCellsMeta (http://localhost:4200/vendor.js:176763:28)
    at Core.getCellsMeta (http://localhost:4200/vendor.js:174113:24)
    at HiddenColumns.resetCellsMeta (http://localhost:4200/vendor.js:222832:82)
    at HiddenColumns.disablePlugin (http://localhost:4200/vendor.js:222672:12)
    at HiddenColumns.updatePlugin (http://localhost:4200/vendor.js:222654:12)
    at HiddenColumns.onUpdateSettings (http://localhost:4200/vendor.js:194164:16)
    at Core.<anonymous> (http://localhost:4200/vendor.js:194016:20)
    at Hooks.run (http://localhost:4200/vendor.js:193645:46)
    at Core.runHooks (http://localhost:4200/vendor.js:175298:81)'

If you remove the hiddenColumns and repeat the test steps the issue does NOT occur.

The very presence of the hiddenColumns attribute within the settings is sufficient to produce the bug. You can set hiddenColumns to an empty array thereby hiding no columns in fact but the presence of hiddenColumns in the settings is enough to kick the hiddenColumns plugin in and have it break.

### Steps to reproduce
1. Open the jsfiddle below
2. Take a copy into the clipboard of two cells from a single column - it doesn't matter which.
3. Copy the clipboard in the bottom row forcing the grid to make a NEW row.
4. Click the "Go" button to run the updateSettings call.
5. Check the console output to see the error.

### Demo

https://jsfiddle.net/4pdjsex9/10/

### Your environment
* Handsontable version: 8.3.1. Also observed on 8.0.0
* Browser Name and version: Chrome Version 88.0.4324.190 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by john-swallow-cenduit** [comment] 2021-03-10 09:27
https://user-images.githubusercontent.com/58601615/110607040-b5c12e00-8182-11eb-9b6a-79e07483cb48.mp4

**Comment by AMBudnik** [comment] 2021-03-11 09:10
Thank you for sharing the video @john-swallow-cenduit 

I've replicated the behavior and simplified the demo https://jsfiddle.net/yk51pwsu/

Additional notes
1. Issue is replicable only when copy part data without the hidden column (using CTRL + A doesn't trigger the issues)
2. The number of created new rows doesn't matter
3. I've tested it with versions v7+ on Chrome 89 and Firefox 86 on Windows 10
4. Adding `contextMenu` to copy data doesn't change the behavior
5. The `afterPaste` is not triggered but we can type after getting the error ad data is pasted correctly
6. `updateSettings` is not needed. We get the error when we want to read the `cellsMeta` https://jsfiddle.net/yk51pwsu/3/. That's why I need to change the title to include `cellsMeta`. (Calling `getCellMeta` per cell works well even when called for a hidden column index)

**Comment by mb-ca** [comment] 2021-05-24 23:08
I have also come across this bug in Angular and reproduced with the following:
1. Copy the following:
```
1
2
3
```
2. Click into the only cell and paste.
3. Click "Update Settings"

Code:
```
@Component({
  selector: 'app-root',
  template: `
    <button (click)="updateSettings()" style="margin-bottom: 48px;">Update Settings</button>
    <hot-table [hotId]="tableId" [settings]="tableSettings">
      <hot-column data="hiddenColumn" title="Hidden Column"></hot-column>
      <hot-column data="visibleColumn" title="Visible Column"></hot-column>
    </hot-table>
  `,
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  hotRegisterer = new HotTableRegisterer();
  tableId = 'hotInstance';

  tableSettings: any = {
    data: [],
    licenseKey: 'non-commercial-and-evaluation',
    hiddenColumns: {
      columns: [0]
    },
    minSpareRows: 1
  };

  updateSettings() {
    this.hotRegisterer.getInstance(this.tableId).updateSettings({
      readOnly: true
    });
  }
}
```

Error:
```
TypeError: Cannot read property 'values' of undefined
    at CellMeta.getMetas (cellMeta.mjs:224)
    at MetaManager.getCellsMeta (index.mjs:212)
    at Core.getCellsMeta (core.mjs:3188)
    at HiddenColumns.resetCellsMeta (hiddenColumns.mjs:423)
    at HiddenColumns.disablePlugin (hiddenColumns.mjs:249)
    at HiddenColumns.updatePlugin (hiddenColumns.mjs:231)
    at HiddenColumns.onUpdateSettings (base.mjs:275)
    at Core.<anonymous> (base.mjs:84)
    at Hooks.run (pluginHooks.mjs:2182)
    at Core.runHooks (core.mjs:4407)
```

**Comment by AMBudnik** [comment] 2021-05-25 06:58
Thank you for your feedback @mb-ca 

I will update you as soon as we fix this issue.

**Comment by maxxxxxdlp** [comment] 2021-06-10 16:57
I looked into the code and it seems like this issue occurs because metaData row is created twice for each added row.

metaData row is created the first time when calling getCellMeta from inside of validateChanges - https://github.com/handsontable/handsontable/blob/f9420a22e272df9cf37d54abb75bdb47db1149e0/src/core.js#L1118

After validateChanges validated all rows (and created metaData for each), applyChanges calls createRow for each row - https://github.com/handsontable/handsontable/blob/f9420a22e272df9cf37d54abb75bdb47db1149e0/src/core.js#L1190

createRow later calls this function which inserts an "undefined" metaData row at the end - https://github.com/handsontable/handsontable/blob/f9420a22e272df9cf37d54abb75bdb47db1149e0/src/dataMap/metaManager/lazyFactoryMap.js#L207

Later, when getCellsMeta is called, it throws up on those "undefined" values

Workarrounds:
- Don't use `hot.getCellsMeta()`. Instead, call `hot.getCellMetaAtRow()` for each row in `hot.countRows()` (though this causes performance problems for me when I have 7k+ rows)
- Make sure not to call setDataAtCell with more than 1 new row at a time (call it separately for each row you want to create)
   Example implementation:
   ```js
     beforePaste(data) {  // add the following hook to your HOT config object
        const currentRowCount = this.hot.countRows();
        const newRowCount = Math.max(
          currentRowCount,
          this.hot.getSelectedRangeLast().getTopLeftCorner().row + data.length
        );
        if (newRowCount > currentRowCount)
          Array.from({ length: newRowCount - currentRowCount }, (_, index) =>
            this.hot.setDataAtCell(currentRowCount + index, 0, '')
          );
      },
   ```

**Comment by maxxxxxdlp** [comment] 2021-06-10 17:05
Also, it seems to happen even when you are not using `hiddenColumns` as evident by this demo - https://jsfiddle.net/maxxxxxdlp/f3gze47m/13/

Thus, you should probably rename the title of this issue.

**Comment by AMBudnik** [comment] 2023-01-03 10:54
Hi @john-swallow-cenduit @maxxxxxdlp  This issue seems to no longer exist in Handsontable v12.3.0 so I am closing this issue as done. 

If it does not work for you please let me know.

**Closed by AMBudnik** 2023-01-03 10:54 UTC
Labels: bug, Hiding, Reported
