### ISSUE TITLE
Hidden Column and Column Freeze Conflict.

### ISSUE THREAD

**Issue by clgerhardt** [handsontable/handsontable#5440] opened 2018-10-03 13:13 UTC
### Description
I'm attempting to use freeze column and hidden columns however when I use both features at the same time there is an issue in the rendering (I think). In the demo, I have the first column I in the table hidden, then I go and freeze the second column. When that happens the column header changed to the hidden column header and all the content disappears from the column.

### Steps to reproduce
1.open demo
2.notice, first column (A) is hidden
3.Then click column B and freeze it

### Demo
https://jsfiddle.net/y2cpbjx0/1/

### Your environment
* Handsontable version: Pro 6.0.0
* Browser Name and version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System:  Windows 10

**Comment by wojciechczerniak** [comment] 2019-01-30 09:59
Duplicate of #5456. Please subscribe to issue #5456 for updates. Thansk @wszymanski for investigating.

**Closed by wojciechczerniak** 2019-01-30 09:59 UTC
Labels: PRO: hiding, Plugin: freeze / resize / move, Type: Bug
