### ISSUE TITLE
Edge doesn't format dates properly

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6662] opened 2020-01-27 07:51 UTC
### Description

Below is a set of data that we add to the `Registration date` column.
``` js
"2020/01/10"
"2020/1/10"
"2020/01/01"
"2020/1/1"
```
and here are the settings for the columns

```js
dateFormat: 'M/D',
correctFormat: true,
defaultDate: '01/01/1900',
```

### Steps to reproduce

1. Open demo on Chrome

**Result**
![image](https://user-images.githubusercontent.com/10757813/73156957-caa64380-40df-11ea-8781-da0630b5a387.png)

It means that we only expect to get month/day value. Strangely, in Edge, we get a day before the defined date.

2. Open demo on Edge

**Result**
![image](https://user-images.githubusercontent.com/10757813/73156981-dc87e680-40df-11ea-8e43-c7b1512f52f3.png)

![image](https://user-images.githubusercontent.com/10757813/73157410-28875b00-40e1-11ea-96d9-85dd91d6bede.png)

### Demo

http://jsfiddle.net/handsoncode/eju7mLgv/

### Your environment
* Handsontable version: 7.3.0
_Works the same way on all version of Handsontable 2+_
* Browser Name and version: Edge
* Operating System: Windows 10

Inform [forum](https://forum.handsontable.com/t/gh-6662-ie-edge-if-you-enter-the-date-directly-it-will-be-converted-one-day-ago/4077)

**Comment by aninde** [comment] 2020-06-19 10:31
The issue is still replicable with latest stable `v7.4.2` https://jsfiddle.net/eaw4dmgn/ and on `8.0.0-beta2-rev15` https://jsfiddle.net/dep98162/ on demo from [forum](https://forum.handsontable.com/t/gh-6662-ie-edge-if-you-enter-the-date-directly-it-will-be-converted-one-day-ago/4077) on Edge v.44 (without Chromium). 
![image](https://user-images.githubusercontent.com/30186818/85123462-9b2bdb00-b228-11ea-8bac-ea1d7b63bf3f.png)


It's solved on Chromium-based Edge.  
Interestingly, the dates display correctly for a second, and then the month is moved back by -1.

After changing the configuration of demo to the one in @AMBudnik [report](https://github.com/handsontable/handsontable/issues/6662#issue-555408856) http://jsfiddle.net/Lm2xkvpw/, it turns out that after opening the demo, this error no longer occurs. Maybe that config is broken. The date is displaying correctly on Edge v44 and Edge Devs 85 / Windows 10.

<img width="364" alt="Screenshot 2020-06-19 at 12 10 05" src="https://user-images.githubusercontent.com/30186818/85122296-9b2adb80-b226-11ea-8401-126662a2cf48.png">

**Comment by aninde** [comment] 2022-08-04 14:01
This issue is no longer reproducible on the current Chromium-based LTS Edge 103.0.1264.77 (x86_64) on macOS 12.5 (21G72) and Windows 10. Hence [legacy Edge is no longer supported](https://www.theverge.com/2021/3/9/22321779/microsoft-edge-legacy-spartan-browser-support-ended), I'm closing this issue.

**Closed by aninde** 2022-08-04 14:01 UTC
Labels: Type: Bug, Cell type: date, Edge
