### ISSUE TITLE
manualColumnMove does not work for small object data source

### ISSUE THREAD

**Issue by ohtomi** [handsontable/handsontable#5931] opened 2019-03-30 12:44 UTC
### Description
When the number of fields of object of data source is less than columns, users cannot move columns.

### Steps to reproduce
1. `data` is an array of small object, which has 3 fields, and `columns` is an array of 7 items.
2. Initialize a table with the options `data`, `columns` and `manualColumnMove: true`.
3. Then try to move last column.

#### workaround
Add 4 dummy fields to the first small object of `data`.

### Demo
https://jsfiddle.net/d8r91znt/1/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Safari 12.0.3
* Operating System: Mac

**Comment by AMBudnik** [comment] 2019-04-01 09:16
Thank you for reporting this issue. You're right, once we add a new column, we cannot move the rest of the column after this added one.
I thought that it might be related to datatypes or `data` definition for the `columns`, but it works the same for an array of arrays https://jsfiddle.net/1bpvcLx6/ and doesn't seem to work fine in any previous version of Handsontable.

**Comment by RichTeaTime** [comment] 2019-05-31 10:26
This appears to be linked to the fact that the columnMapper is built from the source data, not any specified columns.
As an extreme case, column moving will not work at all if ```hot.data``` is empty, e.g.
https://jsfiddle.net/2ekp6cot/

The column map is built in:
```
function updateColumnsMapper() {
      var countCols = this.hot.countSourceCols();
```
where countSourceCols expects the source data to be an array of at least one row.
Should this be
``` var countcols = this.hot.countCols()```
instead?

This appears to completely break any code that relies on the columnMapper, i.e. any sitauation where the physical column index != visual column index.

**WORKAROUND:** After updateSettings, manually rebuild the columnMapper

**Comment by RichTeaTime** [comment] 2019-05-31 10:35
Workaround e.g.
```
hot.getPlugin('manualColumnMove').columnsMapper._arrayMap = [... columns.length];
```

**Comment by AMBudnik** [comment] 2019-05-31 10:54
Thank you for doing and sharing the investigation 👍

**Comment by imageslr** [comment] 2019-07-26 11:28
This indeed solved my problem when using `manualColumnMove` with `manualColumnResize`. 

```
const plugin = this.hot.getPlugin('manualColumnMove')

// before moving
plugin.columnsMapper.__arrayMap
> (20) [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

// after moving column 1 to 2
> (20) [0, 2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

// rebuild columnMapper
plugin.columnsMapper.__arrayMap = [...Array(columns.length).keys()]
(20) [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```

**Comment by AMBudnik** [comment] 2019-09-13 13:07
The issue stays the same after introducing changes to #5751 on the branch https://github.com/handsontable/handsontable/tree/feature/issue-5751.
Tested on Chrome 76/ macOS Mojave / local server.

We aren't able to move 'ID' column further than to index 2.

**Comment by wojciechczerniak** [comment] 2019-09-16 07:00
@AMBudnik I'm testing v8.0-rc1 and looks like the issue is solved:
Example from the original issue: https://jsfiddle.net/6kp5w0f1/
And an example where `data` is empty: https://jsfiddle.net/a7kmovtg/

Both move any column I want. Am I doing something wrong? With 8.0-rc1 I can move columns correctly where I couldn't do it with v7

**Comment by AMBudnik** [comment] 2019-09-16 09:23
Hey @wojciechczerniak @wszymanski 
the https://jsfiddle.net/6kp5w0f1/ works well on my Windows 10 (Chrome 77).
The Chrome 76/ macOS Mojave test was made locally on a device that I do not have access to now.

I have also checked https://jsfiddle.net/6kp5w0f1/ on Windows 10 (Chrome 77) (local server, blank browser) and it works well. 
I guess that I've might have used the wrong branch for tests. Will check the remaining issues as well.

**Comment by aninde** [comment] 2019-09-16 09:29
This problem will be fixed by the new `index mapper`. It will be released soon.

We are currently testing a version with many breaking changes, I recommend observing information from issue [#5751](https://github.com/handsontable/handsontable/issues/5751).

**Comment by AMBudnik** [comment] 2019-11-14 14:16
Hey @ohtomi @RichTeaTime @imageslr 

We've just released version 8.0.0-beta1 where this issue is fixed 
As this is only a beta now we do not recommend using it on the production. 
However, we wanted to share the version for you to test so any comment highly appreciated 👍

**Comment by AMBudnik** [comment] 2020-08-06 13:32
Hi @ohtomi @RichTeaTime @imageslr 

this issue works well in v 8.0.0 https://jsfiddle.net/9sgawm74/ (released yesterday).

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. ✍️

**Closed by AMBudnik** 2020-08-06 13:32 UTC
Labels: Moving, Type: Bug

**Comment by imageslr** [comment] 2020-08-06 13:36
Thanks for your work! @AMBudnik
