### ISSUE TITLE
Resizing first column past the container boundary result in blank space of size of the next column.

### ISSUE THREAD

**Issue by jurisv** [handsontable/handsontable#5165] opened 2018-06-08 17:14 UTC
### Description
Resizing first column past the container boundary result in blank space of size of the next column.

### Steps to reproduce

1. Go to https://docs.handsontable.com/3.0.0/demo-resizing.html
2. Resize column B
3. Resize column A past the screen boundaries
4. Scroll column B in to the view

### Expected result: 
Adjacent column should scroll in to the view without blank gap.

### Actual result:
Blank space followed the Column A.

### Demo video

![empty_space](https://user-images.githubusercontent.com/643535/41171227-c67c6ce2-6b1d-11e8-8416-fc95e5e2b7cf.gif)

### Your environment
* Handsontable version: All versions including 3.0.0
* Browser Name and version: All
* Operating System: All

**Comment by AMBudnik** [comment] 2018-06-11 06:36
Thank you for sharing @jurisv 
I have replicated the issue.

**Comment by wojciechczerniak** [comment] 2019-03-05 14:02
Duplicate of #3448

**Closed by wojciechczerniak** 2019-03-05 14:02 UTC
Labels: Plugin: freeze / resize / move, Type: Bug
