### ISSUE TITLE
Some column get shown while using `hiddenColumns` and moving columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5456] opened 2018-10-05 07:54 UTC
### Description

Some column get shown while using `hiddenColumns` and moving columns

### Steps to reproduce

1. When we move column `M` between `P` and `Q` the `O` column is shown

### Demo

https://jsfiddle.net/handsoncode/dtqzr4jL/

### Your environment
* Handsontable version: `6.0.1`
doesn't seem to be version related
* Browser Name and version: Chrome 69
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2018-10-11 06:55
I just got a hint from our user

> seems that when ever a column is moved or frozen, the hidden column indexes are not updated.

**Comment by wojciechczerniak** [comment] 2019-01-31 11:24
#5598 has a better example. The column is not shown, our dynamic titles make that confusion. It's clearer with #5598 screencast.

Duplicate of #5598

**Closed by wojciechczerniak** 2019-01-31 11:24 UTC
Labels: PRO: hiding, Plugin: Moving, Status: To be discussed, Type: Bug

**Comment by AMBudnik** [comment] 2020-08-06 11:15
Referenced issue solved in v 8.0.0
