### ISSUE TITLE
Deselection of few cells after selection of a range is not working

### ISSUE THREAD

**Issue by RahulBadenkal** [handsontable/handsontable#5426] opened 2018-09-28 06:23 UTC
### Description

After selecting a range of cells, If we try to unselect few of them (by pressing ctrl and selecting the cells we want to unselect), it is still considering them in the selection.

### Steps to reproduce

1. Select a range of cells via keypad/mouse (let's say A1: B5)
2. Unselect one cell (say B1), by pressing ctrl and selecting B1
3. Call the hot.getSelected() method and print in console
4. It returns [[0, 0, 4, 1],
                    [0, 1, 0, 1]]
   It considers B1 to be selected twice.
  
### Demo

https://jsfiddle.net/8ffpsqt6/295/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment] 2018-09-28 07:54
Hi @RahulBadenkal 

the `getSelected()` method returns an array of areas. Each array returns a start and end index of a row and column. 

If we get `[0, 1, 0, 1]` it means that the start row index is `0`, start column index is `1` end index of a row is `0` and end index of the column is `1` so we only have one cell selected. That is an intended behavior.

**Comment by RahulBadenkal** [comment] 2018-09-28 08:13
> Hi @RahulBadenkal
> 
> the `getSelected()` method returns an array of areas. Each array returns a start and end index of a row and column.
> 
> If we get `[0, 1, 0, 1]` it means that the start row index is `0`, start column index is `1` end index of a row is `0` and end index of the column is `1` so we only have one cell selected. That is an intended behavior.

Ok, but usually in spreadsheet programs (like excel) when anyone (ctrl) selects an already selected cell, the end result is: that particular cell is unselected.
So if I select A1:B5 and ctrl select B1 and apply say Bold Formatting, Then ideally all cells except B1 should get bold.

![screenshot from 2018-09-28 13-42-23](https://user-images.githubusercontent.com/30529904/46196326-5b221780-c324-11e8-95e3-558e74372906.png)

**Comment by AMBudnik** [comment] 2018-09-28 08:20
Yes, it works a little bit different than Excel in this case. In Excel when I selected `A1:B5` and click `B1` the area contains all cells from `A1` to `B5` without `B1`.
I'll discuss that with the team. There's a [Stage 2](https://github.com/handsontable/handsontable/issues/4817) of the multi-selection option but this subject is not included.

**Comment by RahulBadenkal** [comment] 2018-09-28 08:37
> Yes, it works a little bit different than Excel in this case. In Excel when I selected `A1:B5` and click `B1` the area contains all cells from `A1` to `B5` without `B1`.
> I'll discuss that with the team. There's a [Stage 2](https://github.com/handsontable/handsontable/issues/4817) of the multi-selection option but this subject is not included.

Ok, Thanks

**Comment by wojciechczerniak** [comment] 2020-07-15 15:52
Duplicate of #5737

**Closed by wojciechczerniak** 2020-07-15 15:52 UTC
Labels: Core: selection, Status: To be discussed, Type: Change
