### ISSUE TITLE
[Bug]: when minSpareRows is set, an error occurs in spliceData

### ISSUE THREAD

**Issue by mainstreetmark** [handsontable/handsontable#10518] opened 2023-09-20 19:21 UTC
### Describe the bug

I have a settings object 

```javascript
export const default_settings = {
	columnSorting: true,
	filters: true,
	fixedColumnsStart: 1,
	dropdownMenu: ["filter_by_condition", "filter_by_value", "filter_action_bar"],
	height: "calc(100vh - 220px)",
	licenseKey: "non-commercial-and-evaluation",
	minSpareRows: 5, // <-----------------------
	rowHeaders: true,
}
```
When `minSpareRows` is included, the table crashes in `dataMap.mjs`, specifically on the following line:

```javascript
...
// We try not to change the reference.
this.dataSource.length = 0;
...
```

The error is: 
```
TypeError: Cannot assign to read only property 'length' of object '[object Array]'
```

### Handsontable version

13.1.0

### Your environment

node/chome/osx

**Comment by adrianszymanski89** [comment] 2023-09-21 08:03
Hi @mainstreetmark 

I tried to recreate the issue with the settings you provided, but I can't get the same results.

Can you please modify this example so the issue is replicable? https://jsfiddle.net/handsoncode/1m0xqb8f/

**Comment by mainstreetmark** [comment] 2023-09-21 16:19
Well, I can't reproduce it.  I've spent about an hour trying to boil it down to an issue, and it's mysterious.

What I think is happening is the data that I'm passing into HotTable is almost directly from my GQL backend, via a Vue computed property.  I think there's some shenanigans going on there with protecting the data from modifications.  For example:

This fails (this is a Vue computed property...).  It cannot zero `this.dataSource`:
```vue
const data = computed(() => (!loading.value ? result.value?.data : undefined))
```

This works:
```vue
const data = computed(() =>
   !loading.value ? JSON.parse(JSON.stringify(result.value?.data)) : undefined
)
```
However, in both cases, I am able to write `data.value.length = 0` in my own code without incident.  So... I dunno.  I'll use the JSON trick for now.

**Comment by adrianszymanski89** [comment] 2023-09-22 08:33
@mainstreetmark 

All right, thank you for the update. I'm glad that you did find a solution for this. I will need to close this issue now, but if you find the source of the problem, feel free to post an update.

**Closed by adrianszymanski89** 2023-09-22 08:33 UTC
Labels: bug, Status: Answered
