### ISSUE TITLE
Maximum call stack size exceeded when using Parse.Collection as data source

### ISSUE THREAD

**Issue by jpravetz** [handsontable/handsontable#3065] opened 2015-12-13 22:40 UTC
This issue is relevant if you are using Parse.com's Parse Javascript library version 1.5.0, which was based on Backbone and still implemented Parse.Collection. Parse's newer libraries no longer support Backbone.

I am writing up this issue in case anyone else encounters it. There is an easy workaround.

When using the Parse.com Parse.Collection as a data source, you will get a "Maximum call stack size exceeded" exception. I isolated the problem to the fact that Parse.Collection does not implement push and splice methods, whereas Backbone.Collection does implement these methods. 

HandsonTable has a loadData method that checks to see if these two methods are implemented. If they are not, it puts your data within an array as shown here, which results in recursion.

```javascript
  this.loadData = function(data) {
    if (typeof data === 'object' && data !== null) {
      if (!(data.push && data.splice)) {
        data = [data];
      }
    }
```

The workaround is to add the push and splice methods to your Parse.Collection object. Simply copy these implementations from Backbone.Collection. I haven't yet encountered any side effects of doing this.

**Comment by AMBudnik** [comment] 2016-03-04 14:34
Hi @jpravetz I couldn't reproduce this one. Can you check if it is still accurate for 0.23.0?

**Comment by jpravetz** [comment] 2016-03-04 16:06
I've made a note to check this, but it will be a few weeks before I can come back to the code base that uses handsontable. Thanks.

**Comment by AMBudnik** [comment] 2016-03-07 11:40
OK, so I will close this issue till you get back.

**Closed by AMBudnik** 2016-03-07 11:40 UTC
Labels: Answered
