### ISSUE TITLE
[Bug]: At the same page,copy handsontable then cannot copy anything

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#11017] opened 2024-06-11 07:43 UTC
### Describe the bug

 At the same page,copy handsontable then cannot copy anything

### Handsontable version

14.0.0

### Your environment

geogle

**Comment by adrianszymanski89** [comment] 2024-06-11 10:33
Closed as duplicate of: https://github.com/handsontable/handsontable/issues/11016

**Closed by adrianszymanski89** 2024-06-11 10:33 UTC
Labels: bug
