### ISSUE TITLE
problem using other language

### ISSUE THREAD

**Issue by Hokwang** [handsontable/handsontable#839] opened 2013-06-27 04:12 UTC
Hello.

First of all, I am Korean.
I am trying to using this cool plugin.
When I input Korean in a cell, first character presents English always.

For example, I wanna write "한글", but the cell present "gㅏㄴ글".
                                            "아이"       ->                         "dㅏ이".
                                            "도시"       ->                         "eㅗ시".

Please fix it or answer to me how solve this problem.
Thank you.

**Comment by xshadows** [comment] 2015-01-09 01:45
@christchan this solve the IME problem ,but copy and paste function won't work well,it's weird

**Comment by awsp** [comment] 2015-04-15 20:53
Is there any follow-up on this issue? 
For Japanese IME at least, I think if it does beginEditing() opening up the textarea before keydown will solve the problem of having unintended ASCII character from appearing. Since IME input works no problem when editor textarea is opened. 
The problem seems to me is that the first "key" that triggers the editor to open incorrectly. Should open with empty textarea first basically. :D

**Comment by teegh** [comment] 2015-07-23 02:09
It seems not fixed in 0.16.0.

I think the following problems can be solved.
 * A problem that occurs when i use the ime in google chrome.
 * A problem that occurs when i use the ime in handsontable's autocomplete.

In order to avoid the bug, i changed the code below. handsontable.full.js

line 6509

```javascript
function init() {
    instance.addHook('afterDocumentKeyDown', onKeyDown);
    //eventManager.addEventListener(document.documentElement, 'keydown', function(event) {
    eventManager.addEventListener(document.documentElement, 'keyup', function(event) { //keydown -> keyup
      instance.runHooks('afterDocumentKeyDown', event);
    });
```


line 6902

```javascript
AutocompleteEditor.prototype.open = function() {
...
  //this.focus(); //off
```

line 6967

```javascript
AutocompleteEditor.prototype.updateChoicesList= function() {
...

  // this.instance.listen(); //off
  // this.TEXTAREA.focus(); //off
```

**Comment by awsp** [comment] 2015-07-23 03:20
@teegh Thanks for the fix! 

I have tried it, at least the Japanese IME opens up.
It is sort of working but not completely, the first character I typed was omitted. 
There is also some problem with the "enter" key after changed from keyup to keydown. 
Still waiting this to be fixed. :(

**Comment by teegh** [comment] 2015-07-24 01:16
@awsp I'm sorry. As you mention, there are some issues. I hope to be fixed. I think maybe it able to solve the problem in the kecode 299. Is there something good way?

http://www.w3.org/TR/2012/WD-DOM-Level-3-Events-20120906/#determine-keydown-keyup-keyCode
> ### B.2.1 How to determine keyCode for keydown and keyup events
> If an Input Method Editor is processing key input and the event is keydown, return 229.

**Comment by awsp** [comment] 2015-07-24 01:25
@teegh 

Yea, I used to quick fix this issue in the old jQuery version by detecting if it is IME mode using keyCode 229 at issue #1448. It worked for Japanese and Chinese IME, but didn't work for Korean IME tho. 

It's gotta be somehow doing with keyCode 229, not so sure how it could get it fix in the non jQuery version tho.

**Comment by teegh** [comment] 2015-07-28 02:16
@awsp 
Thank you. Issue #1448 has become a great help.  Korean IME is regrettable. I hope problem is solved soon.

**Comment by zhouxiaoping** [comment] 2015-11-20 08:46
whatever in which version, focus the editor before editing will fix this issuse. For example: focus the editor in afterSelectionEnd function.

**Comment by ChouGary** [comment] 2016-07-21 03:37
short term solution
don't use display = 'none'  or visibility = 'hidden'
￼
![image](https://cloud.githubusercontent.com/assets/8294943/17010313/49754580-4f35-11e6-8ebf-1d255022b698.png)

**Comment by ruzia** [comment] 2016-08-03 04:06
I've created a patch for this problem.
It's seems working well in japanese ime.

https://github.com/ruzia/handsontable/commit/88ca0a373d61002390d91e155c66274f1ad2d3d3

**Comment by pansinm** [comment] 2016-09-19 07:58
@ruzia The patch works well, but  can't copy & paste cells anymore when I use it.

**Comment by cqcn1991** [comment] 2016-11-10 10:26
@zhouxiaoping Do you solve this problem now? I still got the same problem under Chrome with chinese, and in some Firefox as well.

**Comment by cqcn1991** [comment] 2016-11-10 12:05
@pansinm and how is your result? Is there any way to make it work?

**Comment by ChouGary** [comment] 2016-11-21 03:49
fix the short term solution
don't use display = 'none' or visibility = 'hidden'
and afterSelectionEnd set focus on TEXTAREA
￼￼http://jsfiddle.net/wvLLvmbd/

![image](https://cloud.githubusercontent.com/assets/8294943/20470100/537ec9e6-afe0-11e6-967f-b50696f03b1c.png)
![image](https://cloud.githubusercontent.com/assets/8294943/20470122/7ebd7c60-afe0-11e6-9ae5-65d6eddec43b.png)

**Comment by cqcn1991** [comment] 2016-11-21 03:59
@ChouGary Just tried the fiddle, seems performs differently under Firefox and Chrome
In firefox, I need to double click a cell to activate it. In Chrome, a single click is OK.

**Comment by ChouGary** [comment] 2016-11-21 04:09
@cqcn1991 
this is original jsfiddle
http://jsfiddle.net/warpech/hU6Kz/
In original sample , my firefox need to double click a cell to activate too.

**Comment by minipai** [comment] 2017-06-19 09:59
@swistach @budnix 
Can this issue be reopened? It's not fixed yet.
1. Correct behavior by Google sheet
https://drive.google.com/open?id=0BxjLMnWZ26-zZFVVNmpUWG1QcEE

2. Current behavior of handsontable
https://drive.google.com/open?id=0BxjLMnWZ26-zN0ZrVHRPWTBFc00

**Comment by AMBudnik** [comment] 2017-06-19 10:01
Hi @minipai 

the issue is still opened. Unfortunately, we did not start to work on language handling yet.

**Comment by ChouGary** [comment] 2017-06-28 02:32
hi @minipai
root cause
when .handsontableInputHolder  display none, 中文 IME will lostFocus.
you can try my short term solution
http://jsfiddle.net/9jqfe0up/1/
https://drive.google.com/uc?export=download&id=0B4gB_bMISBp2SU10MGVOZFV1MVE

**Comment by AMBudnik** [comment] 2017-06-28 08:14
Thank you very much for your effort to investigate this issue and share a solution @ChouGary

**Comment by minipai** [comment] 2017-06-28 21:46
@ChouGary  Thanks for your fix, it's awesome. Hope handsontable officially use the fix.

**Comment by awsp** [comment] 2017-06-29 08:15
@ChouGary 
I could confirm Japanese IME and Cangjie (Traditional Chinese IME) are both working on both Mac and Windows. Finally a fix in many years!!

**Comment by AMBudnik** [comment] 2017-08-16 07:12
Related topic https://github.com/handsontable/handsontable/issues/4457

**Comment by minteliuwm** [comment] 2017-09-28 02:36
I still got the same problem under Chrome with the latest version, and I want to know when to solve.

**Comment by AMBudnik** [comment] 2017-09-28 06:49
Hi @minteliuwm our developer @wszymanski is currently working on the [localization](https://trello.com/c/NaDXS5Y6/51-handsontable-localization) and we will surely check the following issue.

**Comment by Zneiat** [comment] 2017-10-13 15:56
Thank you so much for  your help! @ChouGary

**Comment by budnix** [comment] 2017-11-24 07:43
Hi Guys! I need more information about how to reproduce this bug. I don't know anything about Korean, Japanise or Chinese language and I need a step-by-step scenario on how to reproduce this problem.

Right now I've seen that original issue related to 
> first character presents English always

is resolved. For now, there is a problem with "unstable" Handsontable editor (textarea element) which breaks IME which causes the wrong symbol merging into another one? Please correct me if I'm in wrong. 

Anyway, I need an information about what keyboard language I have to choose (I'm using macOS).
![zrzut ekranu 2017-11-24 o 08 09 28](https://user-images.githubusercontent.com/571316/33199048-d8c1fa58-d0ee-11e7-84c3-f3114b36344a.png)
Also what letters should I type to get a valid symbol that should be merged into a Handsontable editor?

@minipai Thanks for sharing the video screens. They are very helpful. Please let me know which language do you use and what letters I need to type (using English US keyboard) to reproduce this issue?

**Comment by farthinker** [comment] 2017-11-24 09:52
Hi, @budnix , here is the reproduce steps:

1. Choose 'Pinyin' as your IME
2. Select a dropdown cell and enter editor mode：
    
![image](https://user-images.githubusercontent.com/184323/33204500-b6cdfef6-d13e-11e7-9f5e-02aa92dca9ea.png)

3. Try to type a Chinese word '测试'(means test): type following charactors in sequence: c e s h i，then select the first candidate word:

![image](https://user-images.githubusercontent.com/184323/33204644-2fe74ef0-d13f-11e7-91a1-8e94a637c5e2.png)

As you can see，the result is 'ccece sce shce shi测试'，which is expected to be '测试'. The charactors before '测试' are all incorrectly inserted.

This issue is really a disaster for eastern Asia users. Hope it helps.

**Comment by budnix** [comment] 2017-11-24 10:31
Thanks, @farthinker!

This helps a lot! I've successfully reproduced the issue in my local environment, that's great! So this is happening only in `autocomplete` and `dropdown` editors? I've checked other types editors and it seems that they working well.

**Comment by farthinker** [comment] 2017-11-24 10:41
@budnix , yes, this issue only exists in `autocomplete` and `dropdown` editors，and it seems to be related to these code in autocomplete editor:
```
    this.instance.listen();
    this.TEXTAREA.focus();
    (0, _element.setCaretPosition)(this.TEXTAREA, pos, pos === endPos ? void 0 : endPos);
```

**Comment by budnix** [comment] 2017-11-24 13:27
Ok, I've prepared a patch and to be sure if this works for Asia users I've prepared demo at http://jsfiddle.net/budnix/4q3rtmax/1/. Can I ask you guys to test that demo?

**Comment by farthinker** [comment] 2017-11-25 02:41
@budnix ，it definitely works for Chinese，and I think it also works for Korean and Japanese too. Hope the patch to be released soon. Thank you!

**Comment by AMBudnik** [comment] 2017-11-27 08:57
Thank you for your feedback @farthinker 
I am happy that this issue is finally fixed

**Comment by kazuma1989** [comment] 2017-11-28 06:08
@budnix @farthinker The patch worked fine for Japanese too. Thank you

**Comment by gwajanara** [comment] 2017-12-04 01:00
@budnix @farthinker The patch worked fine for Korean too. Thank you.

**Comment by AMBudnik** [comment] 2017-12-06 12:32
I am really happy to have this old issue solved!

Can I count on your feedback regarding testing the fix 
@Hokwang @okjesse @lauzi @skyand96 @jimmykwong @hyvaa @christchan @ustb-zz @xshadows @pansinm @cqcn1991 @minteliuwm @Zneiat 

@awsp @teegh @zhouxiaoping @ruzia @minipai please also try the original fix

@ChouGary @farthinker @kazuma1989 @gwajanara thank you for your feedback

**Comment by ChouGary** [comment] 2017-12-07 03:30
thank your hard work ,test with 0.35.0 
i want to correct the error press **esc**, first word is english.

here is my steps to reproduce issue
1.use chinese IME type word 中文字
2.press 「esc」 because i want to correct chinese word
3.use chinese IME type word 中文輸入法

here is video for reference 
https://drive.google.com/file/d/1sSxFrZ91TZHSEBlC5y_MyoxHy0L4awbR/view

**Comment by awsp** [comment] 2017-12-07 06:00
@AMBudnik 
I could verify Japanese IME works on the new release, 0.35.0, on both macOS and Windows' Chrome. 

For Chinese IME (Cangjie), it only works on Chrome 62/63 but does not work on Safari 11. 
First character disappeared in Safari 11, therefore the Chinese word was input incomplete.

**Comment by AMBudnik** [comment] 2017-12-08 07:42
Thank you very much for feedback @ChouGary and @awsp 
we'll investigate it

**Comment by AMBudnik** [comment] 2017-12-08 08:15
@ChouGary Can you tell me the English letter formula for the two of the words `中文字` and `中文輸入法`?

**Comment by ChouGary** [comment] 2017-12-08 08:43
@AMBudnik 
i can use esc to reproduce issue in Chinese IME  (Pinyin Cangije)
1 enter editing mode
![image](https://user-images.githubusercontent.com/8294943/33757488-5c6a81c6-dc35-11e7-93d2-60f4d2a27a94.png)
2 press 「esc」key for exit editing mode
![image](https://user-images.githubusercontent.com/8294943/33757541-9b238584-dc35-11e7-8d77-9038c74098d3.png)
3,use Chinese IME  (Pinyin Cangije)
first word is english,second word is Cangije code
![image](https://user-images.githubusercontent.com/8294943/33757738-65614a5c-dc36-11e7-98fd-53170f55fb9a.png)

**Comment by budnix** [comment] 2017-12-08 09:14
@ChouGary I've reproduced the bug, thanks. I've created a separated issue about this at https://github.com/handsontable/handsontable/issues/4662.

**Comment by AMBudnik** [comment] 2017-12-08 12:03
Hi guys! I have one request for you.

Yesterday we have added [Internationalization ](https://docs.handsontable.com/pro/1.15.0/tutorial-internationalization.html)and it would be great if you could share us some feedback. I'd be more than happy to see transactions for Chinese, Korean and Japanese.

**Comment by tacnoma** [comment] 2017-12-25 10:50
Hi guys, I tried ver. 0.35.0 to solve this issue and it seems working well.
I am so grateful for the many efforts. 

But unfortunately, I found that this issue reproduced with `copyPaste: false` option.
To confirm, try this jsfiddle. https://jsfiddle.net/tacnoma/ux9at5wx

My environment is
- Handsontable: 0.35.0
-  browser: Chrome 63
-  OS: Mac OS X 10.12.6
-  IME: Google Japanese Input 2.20

This is just a report, and I have not found the cause of this problem, sorry.

**Comment by AMBudnik** [comment] 2018-01-02 07:20
Hi @tacnoma 

thank you for reporting., Can I ask you to create a new issue for this bug? It will be much easier to attach new commits to it.

**Closed** 2018-01-02 07:21 UTC
Labels: Priority: normal, Status: Released, Tested, Type: Bug

**Comment by tacnoma** [comment] 2018-01-06 13:37
@AMBudnik 
thank you, I created #4704.

**Comment by AMBudnik** [comment] 2018-01-08 09:48
Thanks @tacnoma 
I saw that @budnix has already connected it to another issue.

**Comment by AMBudnik** [comment] 2018-08-20 07:06
Hi Guys! 
@Hokwang @skyand96 @hyvaa @gwajanara

We've just got a translation for Korean. If you could share your opinion on the translation that would be able to pull the Korean language to our official version of Handsontable! You can find it at https://github.com/handsontable/handsontable/pull/5355

**Comment by moonjoungyoung** [comment] 2020-11-17 02:35
@AMBudnik 

Hello.
It seems not fixed in mobile. (or chrome inspect mobile version)
In official demo, desktop works fine, but mobile is not.

https://handsontable.com/examples?headers

**Comment by AMBudnik** [comment] 2020-11-17 07:02
Hi @moonjoungyoung could you please paste a screen recording where this issue is replicable?
