### ISSUE TITLE
fixedColumnsLeft with rowHeaders hidden creates a 1px shift

### ISSUE THREAD

**Issue by Maxoudela** [handsontable/handsontable#7332] opened 2020-10-12 13:56 UTC
### Description
When there are :
- some frozen columns (fixed columns on the left)
- row header not shown
- some content that enlarge the rows a bit

Actual result:
The row height of some rows in the fixed column panel are 1 pixel shorter than the row height of the normal table. 

Expected result:
Row heights should be the same.

### Demo
https://jsfiddle.net/SamHa/d2rL9mtj/

**Problem 1** : Opening the given fiddle in private mode (or by wiping the cache) is first rendered incorrectly :
![image](https://user-images.githubusercontent.com/8961645/95754032-be303e00-0ca2-11eb-99a5-789ef9ca83d6.png)

**Problem 2** : Scrolling a bit will then cause a render (I guess) and the result is improved but the 1 pixel shift is therefore observed:
![image](https://user-images.githubusercontent.com/8961645/95754112-db650c80-0ca2-11eb-94f8-5f51e633117e.png)

Cell E1 has an height of 51 pixels but cell A1 has an height of 52 pixels. In my environment, this shift is observed multiple times, therefore creating a greater gap for each new row (Cannot reproduce the issue on a fiddle yet).

Activating **autoRowSize** makes the thing even worse because scrolling does not fix the issue observed in step 1.

### Your environment
* Handsontable version: 8.1.0
* Browser Name and version: Firefox 81.0.1 (64 bits)
* Operating System: Windows 10

### Workaround
It seems that always activating the rowHeader and giving it a width of 0 pixel when it should be hidden is resolving the issue.

**Comment by Maxoudela** [comment] 2020-10-13 09:53
Related to #2218

**Comment by AMBudnik** [comment] 2020-10-13 11:05
Hi @Maxoudela 

if you define the height for your `IMG` the issue should be gone https://jsfiddle.net/L9k2dvbc/

**Comment by AMBudnik** [comment] 2020-10-13 11:31
Thanks to @aninde we discussed that it is OK on Chrome but is not working well on Firefox

![Zrzut ekranu 2020-10-13 o 13 29 44](https://user-images.githubusercontent.com/10757813/95855180-49b7d680-0d58-11eb-97e7-e281cfd6bc4e.png)
(effect on scrolling to the bottom, then left)

**Comment by Maxoudela** [comment] 2020-10-14 08:36
Hi,

Regarding **Problem 1**, it's happening on Chrome and Firefox. Should I open a separate issue ?

> if you define the height for your IMG the issue should be gone https://jsfiddle.net/L9k2dvbc/
> Please confirm if it works for you.

This is not a possible work-around for at least two reasons:

- I use the **manualRowResize** option and setting an height arbitrarily like that prevent the user to resize the row shorter.
- The image has not been loaded and its size is unknown. I have managed to add an **EventListener** to the **load** event of the image, then set the **maxHeight** on the image (even tried on the first **td**). However, the row height is not reported back to the fixed columns.



Regarding **Problem 2**, I have the 1px shift appearing on both Firefox and Chrome (Version 86.0.4240.75 64bits on Windows 10).

**Comment by AMBudnik** [comment] 2020-10-14 10:51
Those issues might be related. I would prefer to keep them in one place. Nevertheless, we may end up separating them after doing the investigation.

**Comment by am21** [comment] 2020-11-12 17:44
I'm experiencing similar issue with both Firefox and Edge. I don't have pictures in the table, but some HTML converted from Markdown format. If `fixedColumnsLeft=1` I see the 1px misalignement, when `fixedColumnsLeft=0` the table displays correctly.

**Comment by Kento97** [comment] 2023-11-18 01:38
> I'm experiencing similar issue with both Firefox and Edge. I don't have pictures in the table, but some HTML converted from Markdown format. If `fixedColumnsLeft=1` I see the 1px misalignement, when `fixedColumnsLeft=0` the table displays correctly.

how to fix this issue?

**Comment by adrianszymanski89** [comment] 2023-11-20 13:10
Hi @Kento97 

We don't have a fix for this issue yet. We will surely update this thread once it's fixed.

**Comment by AMBudnik** [comment] 2024-07-03 10:24
Hi @Maxoudela @Kento97 @am21 

It retested the scenario, and the issue is no longer replicable using v14.4.0 https://jsfiddle.net/13r9n4x7/

Please update and let me know if it works for you as well.

**Closed by AMBudnik** 2024-07-03 10:24 UTC
Labels: bug, Fixing / Freezing, Reported
