### ISSUE TITLE
How to save the folded state when updating data using  Row parent-child

### ISSUE THREAD

**Issue by superzmb** [handsontable/handsontable#11215] opened 2024-10-08 08:58 UTC
Example: https://stackblitz.com/edit/react-qdravp-atmwc9?file=src%2FExampleComponent.jsx

I collapsed the first row of data, clicked the "data1", rendered the data1 data, and expanded the first row; I hope the first row remains in its original collapsed state

**Comment by AMBudnik** [comment] 2024-10-08 09:29
Hi @superzmb 

We have a bug report opened for this use case when `children` array width is different on initialization from what is called within the `updateData()` method.

It was reported at https://github.com/handsontable/handsontable/issues/10239

I will close this issue as a duplicate of https://github.com/handsontable/handsontable/issues/10239, but I will internally make a note to notify you here on GitHub once the issue is fixed.

**Closed by AMBudnik** 2024-10-08 09:29 UTC
