### ISSUE TITLE
When delete many rows after sorting , some rows disappear.

### ISSUE THREAD

**Issue by YongChanKim** [handsontable/handsontable#2234] opened 2015-03-08 10:17 UTC
HI. 
Thank you for making this awesome library.

The reason why I write this  is reporting a bug and  suggesting a function.

bug ,

![bug](https://cloud.githubusercontent.com/assets/11374011/6545379/d6c13fe6-c5c7-11e4-88ad-e5b514990b0e.png)

 1. sort a column
 2. delete many rows ( I am not  sure this is related with row count.)
 3. some rows disappear.
 4. resort any column -> appear disappeared rows.

suggestion
I wish that multi rows selection is possible using Shift + Click row header .

Thank you for reading . I am a foreigner , so not good at writing in English.

**Comment by krzysztofspilka** [comment] 2015-03-09 11:39
Hi @YongChanKim I couldn't reproduce this issue in our demo http://handsontable.com/demo/sorting.html 

Could you prepare a JSFiddle on that?

**Comment by AMBudnik** [comment] 2015-04-20 08:07
Issue closed in lack of demo for more than a month.

**Closed by AMBudnik** 2015-04-20 08:07 UTC
Labels: Demo needed
