### ISSUE TITLE
[Bug]: paste string is 

### ISSUE THREAD

**Issue by King2321658209** [handsontable/handsontable#10435] opened 2023-07-03 03:03 UTC
### Describe the bug

Want to paste strings like  [ "mchtMcc": "5814", "mchtSprtPayWay": "0010", "actvSngTranLmt": "111", "actvDayAccLmt": "222", "h5ActvSngTranLmt": "5333", "h5ActvDayAccLmt": "5444" ] ，just click cell  not dbclick and textarea does not appear
results is 'mchtMcc:5814,mchtSprtPayWay:0010,actvSngTranLmt:111,actvDayAccLmt:222,h5ActvSngTranLmt:5333,h5ActvDayAccLmt:5444’

want to like this    ' "mchtMcc": "5814", "mchtSprtPayWay": "0010", "actvSngTranLmt": "111", "actvDayAccLmt": "222", "h5ActvSngTranLmt": "5333", "h5ActvDayAccLmt": "5444" '

### Handsontable version

13

### Your environment

Chrome  103.0.5060.134

**Comment by AMBudnik** [comment] 2023-07-03 06:59
Hi @King2321658209 

It might be caused by the browser and system settings. When I run Browserstack to test pasting `[ "mchtMcc": "5814", "mchtSprtPayWay": "0010", "actvSngTranLmt": "111", "actvDayAccLmt": "222", "h5ActvSngTranLmt": "5333", "h5ActvDayAccLmt": "5444" ]` onto https://handsontable.com/docs/javascript-data-grid/numeric-cell-type/ on Chrome 103 it works the same as the newest one. But it might be a mix of an older browser & older system.

On Chrome 114 /macOS Ventura when I use this demo https://handsontable.com/docs/javascript-data-grid/numeric-cell-type/ to paste your data in both cases (in the editor or on selection) I get the same result

![Zrzut ekranu 2023-07-3 o 08 52 13](https://github.com/handsontable/handsontable/assets/10757813/d0abe1b1-c57a-45ef-9dcd-37314ba85540)

**Comment by King2321658209** [comment] 2023-07-03 09:05
Maybe my expression is wrong，I just want to paste   "mchtMcc": "5814", "mchtSprtPayWay": "0010", "actvSngTranLmt": "111", "actvDayAccLmt": "222", "h5ActvSngTranLmt": "5333", "h5ActvDayAccLmt": "5444"

**Comment by AMBudnik** [comment] 2023-07-03 11:11
Ah, I see. The issue with missing quotes is already reported here https://github.com/handsontable/handsontable/issues/7532
I believe this is the same case. Is it correct?

**Comment by King2321658209** [comment] 2023-07-03 12:38
Yes, this question is the same as #7532,  I'm trying to convert to single quotes, the results is  correct ,but in our project some user just want to quickly copy and paste. Is there any good way to solve this problem?

**Comment by AMBudnik** [comment] 2023-07-04 10:01
Thank you for the confirmation @King2321658209 

I need to close this issue as a duplicate, but will update you as soon as we fix https://github.com/handsontable/handsontable/issues/7532

When it comes to workaround it might be hard as the `beforePaste` hook already has the quotes removed, so if the copying of cells is not based on the cell data origin (you copy data outside Handsontable) we do not have an option to get "into" that process and alter the content in the clipboard. But fear not, we will debug this use case and hopefully there is something we can do to fix it.

**Closed** 2023-07-04 10:02 UTC
Labels: Status: Answered

**Comment by King2321658209** [comment] 2023-07-04 12:43
Ok, thanks for your reply
