### ISSUE TITLE
[7.2.0] The dropdown cell type doesn't work on Safari

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7413] opened 2020-11-26 09:06 UTC
### Description

The dropdown menu is not showing since 7.2.0. The Handsontable 7.1.1 was the last working version.

Works on Safari 12.1.2, 13.1.2;
Doesn't work on Safari 14 and higher;

### Steps to reproduce

1. Go to https://handsontable.com/docs/7.2.0/demo-dropdown.html;
2. Open the dropdown type editor;
3. In results, nothing appears;

### Demo

https://handsontable.com/docs/7.2.0/demo-dropdown.html

### Your environment
* Handsontable version: -
* Browser Name and version: Safari 14.0 - 14.1
* Operating System: macOS Catalina

**Comment by wszymanski** [comment] 2020-12-21 13:47
@budnix Are you sure that the problem is noticeable only for Safari? The only problem I've encountered is the one related to the fact that `DOMPurify` maybe not defined (and as an effect, an editor isn't opened). Error `TypeError: undefined is not an object (evaluating '_dompurify.sanitize')` is thrown.

Since https://github.com/handsontable/handsontable/commit/e18ac91a4b13c50886d197454f02d2280c3d2f7c, after your fix, it's excluded from the build. Maybe you haven't included the library on your own?

I will fix the problem for https://handsontable.com/docs.

**Comment by budnix** [comment] 2020-12-21 13:55
Yes, I'm sure. Starting from 7.2.0 the Dropdown cell type doesn't work for me.
![Kapture 2020-12-21 at 14 54 53](https://user-images.githubusercontent.com/571316/102784332-89282200-439c-11eb-9cc9-5c2d870ee912.gif)

**Comment by wszymanski** [comment] 2020-12-21 14:26
Sorry! I've thought that problem is related to hot >= `8.2.0` and thought that it may be related to the described library lack. The issue describes the problem starting from Handsontable `7.2.0`, not `8.2.0` 🤯 I'm investigating further.

**Comment by AMBudnik** [comment] 2021-02-03 10:37
Update [forum](https://forum.handsontable.com/t/dropdown-cell-dose-not-work-on-safari-14/4971)

**Comment by aninde** [comment] 2021-03-10 15:36
This issue has been fixed by v8.3.2
https://jsfiddle.net/g1yszn20/

Tested on macOS 11.2.2 (20D80) on Safari `Version 14.0.3 (16610.4.3.1.4)`, Safari Technology Preview 121 `(Safari 14.2, WebKit 16612.1.4.3)` and on some older version on Safari via BrowserStack (13.1 and 12.1).

**Comment by AMBudnik** [comment] 2021-03-16 13:53
I'm closing this issue as solved and released for Handsontable v8.3.2

**Closed by AMBudnik** 2021-03-16 13:53 UTC
Labels: Cell type: autocomplete / dropdown / handsontable, Regression, Status: Released, Type: Bug
