### ISSUE TITLE
toHTML() issues

### ISSUE THREAD

**Issue by azal-io** [handsontable/handsontable#7016] opened 2020-06-16 07:46 UTC
### Description

toHTML() doesn't show formatted cells. It should show renderers modified cells. For example if I add alignment then item should show up in HTML output. 
### Steps to reproduce

1. toHTML()

**Comment by azal-io** [comment] 2020-06-16 07:51
I just checked, it doesn't even shop numeric type as dollars or euro, just a plan number. It is useless to just output plain data to HTML table, if I add numeric type USD, then I need it to be present on the HTML table as well, otherwise the meaning get losts.

I hope you can see my point.

Thanks

**Comment by AMBudnik** [comment] 2020-06-16 08:57
HI @azal-io 

Formatting is only made for the eyes. You should get the same data result by calling `getData()`. However, I can see that we should get the classes but we don't https://jsfiddle.net/AMBudnik/nhjosau1/

Calling outerHTML on a `p` element with a class shows the class. When we add a class to `TDs` of Handsontable that class is gone. So we are not able to pass the needed formatting when we want to reconstruct the table.

**Comment by AMBudnik** [comment] 2020-06-16 08:59
@wojciechczerniak is that a bug (that classes are gone) or a missing description of the `toHTML` function.

**Comment by azal-io** [comment] 2020-06-16 12:19
@AMBudnik sure. But don't you think we should have an option to render to that pure HTML? I had high hopes for it since I don't want to load handsontable on Front End but just let users view the table data. Because of this issue and others I have to consider other options, like https://github.com/myliang/x-spreadsheet

I had several issues with Handsontable one of which is about Forumla and merged cells, when it is used together somehow formulas gets invalidated, I checked the source code it seems, merged cells use getData() but to keep the formulas we need getSourceData I think.

Thanks

**Comment by AMBudnik** [comment] 2020-06-16 12:38
We should consider that as an option - but that is a feature request. I wouldn't call it a bug of that option. However, the description is a one-line sentence so I will wait for @wojciechczerniak suggestions to proceed with this subject.

**Comment by azal-io** [comment] 2020-06-16 12:59
@AMBudnik but I think it is not a feature. If I call toHTML() I guess the intention is to get whatever I see on HandsonTable to HTML on page. It is like ordering a pizza and getting it without toppings, but toppings was on the picture, I saw it and asked the same but somehow I didn't get what expected. I hope you can see what I mean.

Thanks

**Comment by wojciechczerniak** [comment] 2020-06-16 15:04
`toHTML` is just an alias to `helpers.instanceToHTML` which is complementary helper for `helpers.htmlToGridSettings`. Both work together to serialize and deserialize Handsontable with HTMLTableElement as a data store. It's used by our copy/paste plugin for clipboard's `text/html` mime type. CKEditor is using it to serialize/deserialize HoT to save editor content to a database. That is the intention of this feature.

We were planning an extension to provide a callback for each row/cell to customize the output and store additional attributes, cssClass, style, formula. I guess it would be possible then to copy the styles and value formatting, but it was never designed to render the exact copy of Handsontable.

**Comment by codecourse-cc** [comment] 2020-06-16 17:19
@wojciechczerniak thanks for the explanation.
Does this mean we will get the extension on version 8?
I mean, in my case also, I need to provide an HTML based table with the formats. I think by getData we can get the data and then with maybe getMeta or getFormatMeta smth like that to then add to view?

Thanks

**Comment by wojciechczerniak** [comment] 2020-06-16 19:13
@codecourse-cc No, version 8th focuses on different things. This is a new feature, that had no use cases until now. Have to go through a new feature planning process first.

Adding styles may be quite easy. HTMLTableElement can be traversed and for each TD element knowing row and column we can `getCellMeta` for the cell and use cell properties, classNames etc. to add required attributes. Value formatting may be more challenging, but doable as well.

**Comment by wojciechczerniak** [comment] 2020-07-01 20:50
Duplicate of #6242

**Closed by wojciechczerniak** 2020-07-01 20:50 UTC
Labels: Type: Feature
