### ISSUE TITLE
[7.1.0+] Undo via Ctrl+Z does not work when columns are configured as functions

### ISSUE THREAD

**Issue by gpavlovych** [handsontable/handsontable#6147] opened 2019-07-24 22:27 UTC
### Description
Undo via Ctrl+Z does not work when columns are configured as functions

### Steps to reproduce
1. Configure Handsontable settings columns in same way as in JSFiddle example  below (columns data is function)
2. Enter some value in any of editable cells
3. Press Ctrl+Z
Expected result: The value in last edited cell is successfully reverted, no errors
Actual result: The value is not reverted, error in the console:
```
handsontable.full.js:69366 Uncaught Error: Unsupported format of the selection ranges was passed. To select cells pass the coordinates as an array of arrays ([[rowStart, columnStart/columnPropStart, rowEnd, columnEnd/columnPropEnd]]) or as an array of CellRange objects.
    at Selection.selectCells (handsontable.full.js:69366)
    at Core.selectCells (handsontable.full.js:39023)
    at UndoRedo.ChangeAction.undo (handsontable.full.js:88396)
    at UndoRedo.undo (handsontable.full.js:88274)
    at Core.onBeforeKeyDown (handsontable.full.js:88812)
    at Hooks.run (handsontable.full.js:6691)
    at Core.runHooks (handsontable.full.js:39366)
    at EditorManager.onAfterDocumentKeyDown (handsontable.full.js:66784)
    at Core.<anonymous> (handsontable.full.js:66510)
    at Hooks.run (handsontable.full.js:6691)
```

### Demo
https://jsfiddle.net/pavlheo/kh5z06gr/4/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version:  Google Chrome | 75.0.3770.142 (Official Build) (64-bit) (cohort: Stable)
* Operating System: Windows 10 OS Version 1803 (Build 17134.885)

**Comment by gpavlovych** [comment] 2019-07-24 22:29
Might be related to https://github.com/handsontable/handsontable/issues/4057

**Comment by wojciechczerniak** [comment] 2019-07-25 09:10
`selectCells` call was added in #6017. If we've missed something then we have a regression @AMBudnik @swistach

**Comment by AMBudnik** [comment] 2019-07-25 10:08
Hey @gpavlovych 

Thank you for sharing. I've replicated the issue and got the same error message.

As @wojciechczerniak suggested I've checked a version before `selectCells` has been added > `6.2.2` and the issue is still there https://jsfiddle.net/handsoncode/4smg7zuo/te%C5%BC we just don't get the bug.

Besides, the `beforeUndo` is triggered and it returns correct values.

**Comment by aninde** [comment] 2019-10-10 12:09
@gpavlovych this bug will be fixed in `7.1.2` version. The new version will be released next week.

In `7.1.2` in your reproduction the error is no longer exist and it is possible to revert edition by <kbd>ctrl</kbd>+ <kbd>z</kbd> and `Undo` from `contexMenu`.

**Fixed result in `7.1.2` v.**
![6147 2 2019-10-10 at 12 10 36 2019-10-10 14_04_05](https://user-images.githubusercontent.com/30186818/66567183-f4eee800-eb66-11e9-875a-447be4e24d5e.gif)

**Demo**
fixed `7.1.2` https://jsfiddle.net/aninde/b3Lau149/

By the way, I found that your condition doubled `minSpareRow` and when you are using columns you can not use `minSpareCols`. I don't know why you use this design, so I can't suggest a correct solution.

**Comment by AMBudnik** [comment] 2019-10-15 10:11
Hey @gpavlovych 

Please update to 7.2.0. The issue should be gone.

**Closed by AMBudnik** 2019-10-15 10:11 UTC
Labels: Regression, Status: Released, Type: Bug, Undo-redo

**Comment by aashayamballi** [comment] 2019-11-13 17:30
I'm using handsontable's react wrapper and I'm facing this issue. I'm on the latest versions of both handsontable react wrapper and handsontable. The issue is when i do ctrl + z only previously edited cell will be get undo and no other row/column/cell get undone.

**Comment by AMBudnik** [comment] 2019-11-14 10:26
Hey @aashayamballi 

can you .zip the project and send it over to support@handsontable.com?
