### ISSUE TITLE
side-by-side HOT tables in modal

### ISSUE THREAD

**Issue by mewalig** [handsontable/handsontable#5867] opened 2019-03-11 17:54 UTC
### Description
What happens: Using bootbox to show a dialog and then place a non-hot table holding a single TR and two TDs, each containing a HOT table, only one HOT table shows up. In addition, it is not visible until clicking on the blank white space
What should happen: 2 HOT tables are side-by-side, and are visible without clicking

### Steps to reproduce
1. open bootbox dialog
2. add a table with a tr and two tds, each containing a hot

### Demo
Please see http://jsfiddle.net/c398zxod/17/

### Your environment
* Handsontable version: see fiddle
* Browser Name and version: latest Chrome (72)
* Operating System: OSX

**Comment by mewalig** [comment] 2019-03-11 18:50
Updated demo fixing width by hardcoding into hot config settings.
http://jsfiddle.net/c398zxod/21/

However, two issues remain:
1. Tables don't appear until after clicking on blank area
2. When selecting a cell, the border highlighting is off, and an extraneous white element outside of the table appears with outline styling (see below image)

The hot table also are not vertically aligned but I'm not sure if that's a hot issue or a bootbox dialog one.
![image](https://user-images.githubusercontent.com/8260442/54149667-09baa000-440d-11e9-9ff2-4ff9c79b4e78.png)

**Comment by AMBudnik** [comment] 2019-03-12 09:26
Hey @mewalig 

it looks like a duplicate of https://github.com/handsontable/handsontable/issues/5322 where a table refreshment (hot.render()) solves the issue.

**Comment by mewalig** [comment] 2019-03-12 16:06
Thank you, I can use hot.render() to resolve the tables not showing up (updated demo: http://jsfiddle.net/25kjz0on/10/). However, the selection issue still remains and is actually a bit more problematic than I realized before because not only is the display off (see image from prior comment), but none of the cells other than the upper-left one can be selected at all. Would you have any suggestions as to how to resolve that?

**Comment by mewalig** [comment] 2019-03-12 16:25
Updated demo: http://jsfiddle.net/25kjz0on/12/ to differentiate between hot1 and hot2. 

Seeing this, part of the problem seems to be the second table's ht_clone_top being misplaced: it is in the upper-left but should be on the right, and further down

![image](https://user-images.githubusercontent.com/8260442/54217362-db4acc80-44c1-11e9-9362-1aca38fbd611.png)

**Comment by mewalig** [comment] 2019-03-12 17:02
Looks like I can solve part of the problem if I do the following:

['ht_clone_top', 'ht_clone_left', 'ht_clone_bottom'].forEach(ht_class_name => {
  container2.querySelectorAll('.' + ht_class_name)[0].style.top = container2.querySelectorAll('.ht_master')[0].offsetTop + 'px';
  container2.querySelectorAll('.' + ht_class_name)[0].style.left = container2.querySelectorAll('.ht_master')[0].offsetLeft + 'px';
});

However, I'm not sure this _actually_ solves that portion of the problem, and even so, there is still the remaining problem of a misplaced ```handsontableInputHolder```...

http://jsfiddle.net/v5u9wc8n/1/

**Comment by mewalig** [comment] 2019-03-12 17:25
Another update: the selection issue is separate from the ```handsontableInputHolder``` issue. When I set the tables to read-only, ```handsontableInputHolder``` no longer appears anywhere (as expected), but selecting cells other than the upper-left one still does not work, and for that one cell that does, the borders are still misdrawn.

So it looks like several issues are at play:
1. ht_clone_top, ht_clone_left and ht_clone_bottom are misplaced
2. handsontableInputHolder is misplaced
3. Cell selection doesn't work

For 1, the brute-force method I described in the prior post might be a feasible workaround. Any suggestions for 2 or 3?

**Comment by mewalig** [comment] 2019-03-12 18:17
Good news! other than the render() issue, these issues seem to only show up on jsfiddle! I will do some more testing to confirm before closing this.

**Comment by wojciechczerniak** [comment] 2019-03-13 10:38
You've forgot to load `handsontable.css`: http://jsfiddle.net/bhve3qgj/1/ or I'm missing some other issue?

Thanks for reporting problem with `handsontableInputHolder`. We will track it in #5886

**Comment by mewalig** [comment] 2019-03-14 17:43
Thank you, had overlooked that css import! That solves the scrolling issue for small tables. However, scrolling still fails for larger tables. Only the first few rows display, and scrolling down, the remaining rows never appear: http://jsfiddle.net/wspzo0hv/17/

I've tried forcing the tables to re-render but to no avail. Any suggestions?

**Comment by mewalig** [comment] 2019-03-14 17:53
Actually it looks like both vertical and horizontal scroll are still not working properly. In the below image from the above fiddle, both tables have more than 100 rows, and you can see the horizontal scrolling out of sync in the left table

![image](https://user-images.githubusercontent.com/8260442/54379782-6feb3100-4660-11e9-957c-89a067c879d3.png)

**Comment by wojciechczerniak** [comment] 2019-03-17 21:09
I think that the problem is that you initialize Handsontable before its container was appended to the DOM. Check this fiddle: http://jsfiddle.net/ot1L2k6h/ I don't recommend `setTimeout` but it shows that you should rebuild the logic how modal with Handsontable is created and attached to the DOM tree.

**Comment by mewalig** [comment] 2019-03-18 01:41
Thank you, changed the order-- see http://jsfiddle.net/uhw6y2bm/2/-- and that does at least fix the vertical scrolling issues. Was hoping that the misplaced input element would be the only remaining issue but tried ```manualColumnResize: true``` and that isn't working either-- any ideas?

**Comment by wojciechczerniak** [comment] 2019-03-18 08:36
Browsers started to think that `position: fixed` is not `fixed` 🤷‍♂️ More details here: #5050. And you can track that issue, we're working on it and will have a PR soon. We want to have fixes for both issues with `transform: translate(...)` in the next release.

**Closed** 2019-03-22 12:27 UTC
Labels: Status: Answered
