### ISSUE TITLE
We're not able to use handsontable.js (not full) cause of the formulas plugin

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7297] opened 2020-09-28 07:31 UTC
### Description

We're not able to use `handsontable.js` (not `full`) cause of the formulas plugin. The table does not load.

### Steps to reproduce

1. Open the console

![image](https://user-images.githubusercontent.com/10757813/94402441-5b03bf00-016c-11eb-9caa-9eae3537af61.png)

### Demo

https://jsfiddle.net/y5hkL379/ - 8.0.0 (broken)
https://jsfiddle.net/y5hkL379/1/ - 7.0.0 (broken)

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Chrome 85
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment] 2020-09-28 08:10
Duplicate of #4693

**Closed by wojciechczerniak** 2020-09-28 08:10 UTC
Labels: Formulas, Type: Bug

**Comment by AMBudnik** [comment] 2020-09-28 08:17
Thanks @wojciechczerniak 
I was looking for it under the 'bug' label 👍 and couldn't find it.

**Comment by AMBudnik** [comment] 2021-06-01 13:36
This issue is fixed with https://github.com/handsontable/handsontable/issues/4693 in v9 http://jsfiddle.net/8m4nvbp3/
