### ISSUE TITLE
 HandsonTable Cannot read properties of undefined (reading 'startRow') at get startRowRendered (_base.mjs:336:52)

### ISSUE THREAD

**Issue by WadeCai** [handsontable/handsontable#11239] opened 2024-10-29 14:38 UTC
### Describe the bug

There has two hansontables in one page with el-tab, so the first one(sheet1) is visible and second one(sheet2) is invisible, and there has a button.

first time, I click the button and trigger execLoad, did not have any error, then click the button again, the execLoad will be triggered again, but it will appear above error.

second time, I click the button and trigger execLoad, did not have any error,  then I click the second tab, make the sheet2 visible, continue to click button, the execLoad will be triggered, and this time did not appear any error, and run perfectly.

after multiple test, if there defined mergeCells, it will appear error Cannot read properties of undefined (reading 'startRow') at get startRowRendered (_base.mjs:336:52).

<script>
const execLoad=()=>{
sheet1.value.hotInstance.updateSettings({
      data:[["","",""]],
      mergeCells:[{row:0,col:0,colspan:2]
    });
sheet2.value.hotInstance.updateSettings({
      data:[["","",""]],
      mergeCells:[{row:0,col:0,colspan:2]
    });
}
</script>

### Handsontable version

14.6.1

### Framework version

Vue3

### Your environment

Win11 and chrome or edge

**Comment by adrianszymanski89** [comment] 2024-10-29 15:51
Hi @WadeCai 

Thank you for contacting us. Please send a code example in the chosen sandbox where we can reproduce the issue. That way, it will be easier to identify and solve the problem.

**Comment by WadeCai** [comment] 2024-10-29 23:57
Thanks @adrianszymanski89 , 
below is my coding in vue3, when load the page, it is ok, then I change the group to group B, it appear error, then disable this line mergeCells: settings.cell.merges in tonnageSheet, it is ok also.
<template>
    <div class="flex flex-wrap">
    <div class="m-4">
      <p>Review Year</p>
      <el-select v-model="reviewYear" placeholder="Review Year" @change="reviewYearChanged">
        <el-option
          v-for="item in reviewYearList"
          :key="item.value"
          :label="item.label"
          :value="item.value">
        </el-option>
      </el-select>
    </div>
    <div class="m-4">
      <p>Review Group</p>
      <el-select v-model="reviewGroup" placeholder="Review Group" @change="reviewGroupChanged">
        <el-option
          v-for="item in reviewGroupList"
          :key="item.value"
          :label="item.label"
          :value="item.value">
        </el-option>
      </el-select>
    </div>
  </div>

    <el-tabs tab-position="bottom" type="card" :width="`${hwidth}px`">
      <el-tab-pane :label="groupSheetName" :height="`${hheight}px`" :width="`${hwidth}px`">        
        <hot-table ref="groupSheet" className="htLeft" minCols="40"
          minRows="100" :rowHeaders="true" :height="`${hheight}px`"
          :width="`${hwidth}px`" ></hot-table>
      </el-tab-pane>
      <el-tab-pane :label="tonnageSheetName" :height="`${hheight}px`">
        <hot-table ref="tonnageSheet" className="htCenter" minCols="40"
          minRows="100" :rowHeaders="true" :height="`${hheight}px`" :width="`${hwidth}px`"
          ></hot-table>
      </el-tab-pane>
    </el-tabs>


</template>

<script setup>
import { onMounted, reactive, ref, watch } from "vue";

//newest
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import 'handsontable/dist/handsontable.full.css';
registerAllModules();
//newest

const modal = reactive({
  isOpenAlertModel: false,
  title: "",
  text: "",
  primaryBtnText: "Login",
});

const groupSheet = ref(null);
const groupSheetName = ref("Group Name");
const tonnageSheet = ref(null);
const tonnageSheetName = ref("Tonnage");
const financeSheet = ref(null);
const financeSheetName = ref("Finance");
const arDaysSheet = ref(null);
const arDaysSheetName = ref("Ar Over Days");

const reviewYearList = ref([])
const reviewGroupList = ref([])

const hheight = ref(100);
const hwidth = ref(900);

const reviewYear = ref(0);
const reviewGroup = ref(0);

const executeLoading=()=>{
  console.log("loading");
    const years = {data:[2024]} ;
    reviewYear.value = years.data[0];
    reviewYearList.value = years.data.map((data)=>{
        return {value:data, label:data};
      });
    executeGroup();
  
};

const executeGroup=() => {
  console.log("group");
    const myGroups = {data:[{id:1,name:"group a"},{id:2,name:"group b"}]} ;
      reviewGroup.value = myGroups.data[0].id;
      reviewGroupList.value = myGroups.data.map((data)=>{
        return {value:data.id, label:data.name};
      });

};

const executeReview=() => {
  const reviewData = {
    "isSuccess": true,
    "code": "",
    "message": "success",
    "data": {
        "groupSheet": {
            "name": "Group A",
            "column": {
                "minCols": 12,
                "fixedStart": 0,
                "headers": [
                    "A",
                    "B",
                    "C",
                    "D",
                    "E",
                    "F"
                ],
                "widths": [
                    100,
                    800,
                    100,
                    100,
                    100,
                    100,
                    100
                ]
            },
            "cell": {
                "aligns": [
                    {
                        "row": 0,
                        "col": 0,
                        "className": "htLeft"
                    }                    
                ],
                "merges": [
                    {
                        "row": 0,
                        "col": 0,
                        "rowspan": 1,
                        "colspan": 2
                    }                    
                ]
            },
            "data": [
                [
                    "September 2024 performance",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""
                ],
                [
                    ""
                ],
                [
                    "1. Failed to achieve/Exceed the operating budget either in sales revenue, GP or net profit more than 10%"
                ],
            ]
        },
        "tonnageSheet": {
            "name": "1. 2024 Performance-Tonnage",
            "column": {
                "minCols": 50,
                "fixedStart": 1,
                "headers": [
                    "A",
                    "B",
                    "C",
                    "D",
                    "E",
                    "F"
                ],
                "widths": [
                    100,
                    80,
                    80,
                    90,
                    140,
                    130,
                    80,
                    80,
                    90,
                    140,
                    130,
                    80,
                    80,
                    90,
                    140,
                    130,
                    80,
                    80,
                    90,
                    140,
                    130,
                    80,
                    80,
                    90,
                    140,
                    130,
                    80,
                    80,
                    90,
                    140,
                    130,
                    80,
                    80,
                    90,
                    140,
                    130,
                    80,
                    80,
                    90,
                    140,
                    130,
                    80,
                    80,
                    90,
                    140,
                    130
                ]
            },
            "cell": {
                "aligns": [
                    {
                        "row": 0,
                        "col": 0,
                        "className": "htLeft"
                    }
                ],
                "merges": [
                    {
                        "row": 4,
                        "col": 1,
                        "rowspan": 1,
                        "colspan": 10
                    },
                    {
                        "row": 4,
                        "col": 11,
                        "rowspan": 1,
                        "colspan": 10
                    },
                    
                ]
            },
            "data": [
                [
                    
                    "","Y2024 BUDGET REVIEW",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""
                ],
                [
                    "Group A"
                ],
            ]
        }
    }
};
  if (reviewData.isSuccess) {
    var settings = reviewData.data.groupSheet;
    groupSheetName.value = settings.name;
      groupSheet.value.hotInstance.updateSettings({
      data: settings.data,
      cell: settings.cell.aligns,
      mergeCells: settings.cell.merges,
      colWidths: settings.column.widths,
      fixedColumnsStart: settings.column.fixedStart,
      minCols: settings.column.minCols,
      colHeaders: settings.column.headers
    });
    settings = reviewData.data.tonnageSheet;
    tonnageSheetName.value = settings.name;
    
    tonnageSheet.value.hotInstance.updateSettings({
      fixedRowsTop : 1,
      data: settings.data,
      cell: settings.cell.aligns,
      mergeCells: settings.cell.merges,
      colWidths: settings.column.widths,
      fixedColumnsStart: settings.column.fixedStart,
      minCols: settings.column.minCols,
      colHeaders: settings.column.headers,
      manualColumnFreeze: true,
    });
  }
};

const floatWidth = 120;
const floatHeight = 320;
onMounted(() => {
  hwidth.value = (window.innerWidth - floatWidth);
  hheight.value = (window.innerHeight - floatHeight);
  executeLoading();
});

window.onresize = function () {
  hwidth.value = (window.innerWidth - floatWidth);
  hheight.value = (window.innerHeight - floatHeight);
};



const reviewYearChanged = (data) => {
  reviewGroup.value = 0;
  reviewYear.value = data;
  executeGroup();
};
const reviewGroupChanged = (data) => {
  reviewGroup.value = data;
};

watch([reviewYear,reviewGroup], () => {
  if(reviewGroup.value!=0 && reviewYear.value!=0){
    executeReview();
  }    
});
</script>

**Comment by adrianszymanski89** [comment] 2024-10-30 08:22
Hi @WadeCai 

Please use a sandbox like CodeSandbox or StackBlitz to show the issue.

**Comment by AMBudnik** [comment] 2024-11-21 07:59
Hi @WadeCai 

Due to the lack of a demo where the issue can be replicated, I am closing this ticket.

If you do not want to share a demo publicly. You can also send it to us at support@handsontable.com

**Closed by AMBudnik** 2024-11-21 07:59 UTC
Labels: bug, Status: Answered
