### ISSUE TITLE
[0.31.1+]Opening a context menu with allowInvalid set to false breaks table

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4834] opened 2018-02-22 05:36 UTC
### Description

If you are attempting to enter an invalid value for a cell and then open a context menu, it will keep the editor open for that cell but will allow you to move around the grid like normal.

### Steps to reproduce

1. Go to http://jsfiddle.net/Lp4qn55v/888/
2. Attempt to put a string into any cell (numeric validation)
3. Open the context menu
4. Can now navigate the table with the editor open

### Demo

http://jsfiddle.net/Lp4qn55v/888/

### Your environment
* Handsontable version: 1.15.0 (pro)
* Browser Name and version: Google Chrome 64.0.3282.140
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2018-02-22 07:43
Thank you for sharing @jeremy-smith-maco 

Here's the same issue for autocomplete cell type https://github.com/handsontable/handsontable/issues/4551

**Comment by AMBudnik** [comment] 2018-04-05 06:59
This issue has been made in [v`0.31.1`](http://jsfiddle.net/handsoncode/jjz4frds/). [Here is v `0.31.0`](http://jsfiddle.net/handsoncode/8dwhfcrm/) that work correctly.

**Comment by swistach** [comment] 2018-06-01 11:00
#4551 should resolve this issue.

**Comment by budnix** [comment] 2018-07-18 13:52
I can't reproduce this bug anymore using PRO v5.0.0 (http://jsfiddle.net/Lp4qn55v/1221/). Fixed within https://github.com/handsontable/handsontable/issues/4551.

**Closed by budnix** 2018-07-18 13:52 UTC
Labels: Cell type: numeric, Regression, Type: Bug
