### ISSUE TITLE
autoRowSize is causing a misalignment of rows

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3618] opened 2016-06-28 14:30 UTC
`autoRowSize` breaks the cells containing multiple lines of text.

![image](https://cloud.githubusercontent.com/assets/8048526/16419323/8b550b38-3d4d-11e6-850d-5f815a73e0f5.png)

**Steps to reproduce the problem:**
1. Go to http://jsfiddle.net/fn8dg18r/
2. Open cell `D4` and enter two lines there (e.g. "A" <kbd>ALT</kbd>+<kbd>Enter</kbd> "B"). Confirm change.
3. Click on cell `D4`, open context menu and click on 'Insert row above'

Result: Rows are misaligned. If the "autoRowSize" option is turned off then it works fine.

:information_source:

> Handsontable 0.26.0
> Windows 8.1
> Chrome

**Comment by AMBudnik** [comment] 2016-06-28 14:43
We're missing one rendering in this case. 

Button in [this example](http://jsfiddle.net/yyw6vwp5/) does the same job as you described and if we comment the `hot.render()` we get the same result as in your image.

**Comment by krzysztofspilka** [comment] 2016-08-30 08:51
It will be fixed right after a new formula plugin is released, probably at end of September, 2016.

**Comment by budnix** [comment] 2016-09-06 14:01
This issue is strongly related with translating visual rows into physical. I think that it should be fixed after prepared object for managing this translations aka. `RowsMapper`.

**Comment by AMBudnik** [comment] 2016-12-13 07:12
Still replicable in 0.29.0

**Comment by michaelkrnac** [comment] 2018-01-29 14:30
The same Problem here with Pro Version 1.15.1

**Comment by ruzia** [comment] 2018-11-07 10:01
@AMBudnik 

I faced above insert bug.
Any workaround exist?

**Comment by AMBudnik** [comment] 2019-03-11 14:33
The same issue @swistach mentioned here https://github.com/handsontable/handsontable-pro/issues/26 which is solved by disabling the `autoRowSize`

**Comment by AMBudnik** [comment] 2019-07-17 11:37
Works the same in v `7.1.0` http://jsfiddle.net/handsoncode/3740h5ux/ with the `autoRowSize` being responsible for the misalignment.

**Comment by AMBudnik** [comment] 2020-07-07 13:30
The issue is no longer replicable in v `7.4.2` http://jsfiddle.net/fcvsx1y6/ (`autoRowSize: true`)

![Zrzut ekranu 2020-07-7 o 15 30 28](https://user-images.githubusercontent.com/10757813/86788769-d02c9000-c066-11ea-855a-4b793727be38.png)

**Closed by AMBudnik** 2020-07-07 13:30 UTC
Labels: Core: alignment/height/width, Guess: few hours, Type: Bug
