### ISSUE TITLE
Copy / Paste Issue - Html tags not removed when pasting the content that contains html tag from handsontable to Excel sheet

### ISSUE THREAD

**Issue by sudar2495** [handsontable/handsontable#9965] opened 2022-09-29 11:30 UTC
**Hello** @aleksandra_budnik 

**Html tags not removed when pasting the content that contains html tag from handsontable to Excel sheet. 
Recently, I have upgraded the angular version and handsontable version from 6.x to 12.x. I am facing this issue in this latest version (12.x) but it was working in older version (6.x) handsontable.**

**Please refer the screenshot below:**

**Handsontable : Rendered dynamic content from server side.**

![image](https://user-images.githubusercontent.com/47984976/193017722-2a0ea747-0d9e-4981-bb99-d07c4f538ab3.png)

**Excel sheet : after paste in to excel sheet**
![image](https://user-images.githubusercontent.com/47984976/193018202-9d0bd9dc-44cc-41ab-b678-071f4a277ec7.png)

**My Expected Output should be :** 
![image](https://user-images.githubusercontent.com/47984976/193018694-eddb1b8e-660d-4946-9616-f41a19a2ed97.png)

**Html tag should be removed automatically before paste the content to excel sheet.**

****Current Version :** 
**Angular - 12.2.17**
Handsontable - 12.1.2**

Please respond as soon as possible.

**Comment by adrianszymanski89** [comment] 2022-09-29 11:46
Duplicate of [Forum](https://forum.handsontable.com/t/copy-paste-issue-html-tags-not-removed-when-pasting-the-content-that-contains-html-tag-from-handsontable-to-excel-sheet/6461)

**Closed by adrianszymanski89** 2022-09-29 11:46 UTC
Labels: angular
