### ISSUE TITLE
Nested data in handsontable cell type

### ISSUE THREAD

**Issue by 57even** [handsontable/handsontable#2371] opened 2015-04-15 09:21 UTC
Are there any plans making a nested data feature? I need to click a cell and see nested data related to that specific cell. I guess it would be a great feature and the handsontable cell type is perfect for such feature.

**Comment by AMBudnik** [comment] 2015-04-20 14:19
Thank you for that feature suggestion. Now we're focusing on fixing some issues but we'll see what we can do.

**Comment by AMBudnik** [comment] 2015-05-11 08:18
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Closed by AMBudnik** 2015-05-11 08:18 UTC
Labels: Feature, Priority: normal

**Comment by mewalig** [comment] 2018-08-20 02:44
This looks like a partial or maybe full dupe of #1924 and #651. I may start working on a simplified custom solution for this in a few weeks. It would basically be a combination of i) a modRow function that would skip hidden rows (or not skip them when the parent is opened) and ii) a renderer function that would x) add a toggle for parent items to be opened/closed and y) indent the first column's content based on how nested that row is. 

I'm not planning to do anything but bare bones, but I do expect to do the above in a way that supports additional layered-on filters. I see that tree-based functionality is "approved" for release already, so if anyone is already working on this and would like to collaborate, please lmk. thx
