### ISSUE TITLE
mergeCells & fixedColumnsLeft,  fix table can't align

### ISSUE THREAD

**Issue by ccmiaomiao** [handsontable/handsontable#4670] opened 2017-12-12 09:20 UTC
### Description
when i used fixedColumnsLeft and mergeCells at the same time ,
the fix table tds can't align the source table

### Steps
1. open the demo and scroll x

### Demo
http://jsfiddle.net/dacq3o77/

thx very much for helping~

**Comment by AMBudnik** [comment] 2017-12-12 09:41
Thank you for sharing the demo @ccmiaomiao 

I have seen this before. If you add `rowHeaders` it works as expected http://jsfiddle.net/kxpe83nw/

**Comment by ccmiaomiao** [comment] 2017-12-12 09:48
@AMBudnik Thank you for helping~

**Comment by AMBudnik** [comment] 2017-12-12 09:56
You're welcome @ccmiaomiao 

We need to fix this in the future. That's why I am reopening the issue.

**Comment by ccmiaomiao** [comment] 2017-12-12 09:59
@AMBudnik 
It's My pleasure ,waiting for your good news

**Comment by AMBudnik** [comment] 2018-04-23 12:11
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment] 2018-08-24 09:14
Works the same in v 5.0.1

**Comment by AMBudnik** [comment] 2019-10-18 11:51
Updated the example to 7.2.1 http://jsfiddle.net/cL60t4xn/

![record](https://user-images.githubusercontent.com/10757813/67091926-3d815380-f1ae-11e9-95ff-619944a439a0.gif)

**Comment by AMBudnik** [comment] 2020-04-29 11:36
Works the same in 8.0.0.-beta1 http://jsfiddle.net/fep5agwm/

**Comment by pnowak** [comment] 2020-08-28 13:16
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/ktsdLueg/

**Comment by lyqeyes** [comment] 2020-11-18 08:58
As what @AMBudnik said,  it works well with  `rowHeaders: true`.  Meanwhile, If u don't want the default rowHeaders, u can set `rowHeadersWidth: 0` at the same time to hide rowHeaders.

In some degree: 
>  `rowHeaders: true` + `rowHeadersWidth: 0` =  `rowHeaders: false`

**Comment by AMBudnik** [comment] 2021-01-12 08:41
Works the same in v8.2.0 https://jsfiddle.net/handsoncode/aytpzed6/

**Comment by nntai** [comment] 2021-10-04 04:59
> As what @AMBudnik said, it works well with `rowHeaders: true`. Meanwhile, If u don't want the default rowHeaders, u can set `rowHeadersWidth: 0` at the same time to hide rowHeaders.
> 
> In some degree:
> 
> > `rowHeaders: true` + `rowHeadersWidth: 0` =  `rowHeaders: false`

Thank you, your solution works but I think it should `rowHeaderWidth` instead of `rowHeadersWidth` 😂 joy

**Comment by AMBudnik** [comment] 2021-10-04 11:56
That is true @nntai 
it is `rowHeaderWidth` (singular form) - ref: https://handsontable.com/docs/api/options/#rowheaderwidth

ps. I'm glad that it helped. I will make sure to notify you once we provide an official fix for this issue.

**Comment by AMBudnik** [comment] 2024-08-06 13:21
Hi @ccmiaomiao @nntai @lyqeyes 

we just released Handsontable v14.5.0 where this issue is fixed.

Thank you again for your feedback.

**Closed by AMBudnik** 2024-08-06 13:21 UTC
Labels: bug, Merge cells, Fixing / Freezing, Reported
