### ISSUE TITLE
After inserting a row above a cell with comment, the comment doesn't stay with the original cell

### ISSUE THREAD

**Issue by edmlin** [handsontable/handsontable#2727] opened 2015-08-13 19:04 UTC
Hi,
First of all thanks for developing such a great project.
Here's an issue I have when I use cell comments. When I insert a row above a cell with a comment, the comment stays on the same row number, instead of moving down with the cell it was created on.
Thanks,

Edmund

**Comment by AMBudnik** [comment] 2015-08-14 08:40
It's a duplicate of https://github.com/handsontable/handsontable/issues/2278 please track changes to that issue.

**Closed by AMBudnik** 2015-08-14 08:40 UTC
