### ISSUE TITLE
Collapse not working correctly when using custom cell rendrers

### ISSUE THREAD

**Issue by Bartaf83** [handsontable/handsontable#4716] opened 2018-01-11 16:07 UTC
I used the handsontable nestedRows feature (as in [this example](http://jsfiddle.net/handsoncode/nfh0a9mq/) ) also with several types of custom cell rendrers.

This is how it looks and how the group collapse works on it currently [DEMO](https://i.imgur.com/YAZisNC.gifv). and this is the [jsfiddle](https://jsfiddle.net/bardelman/2kujc8r9/2/) reproducing it.

As you can see in the demo, the collapse handler (the dash) is placed on the first collapsed group row (the one directly below the group header row) in which only the cell in the first column has changed as the entire first column group collapsed and the second group in that first column is placed directly below that first group row and get its header on its bottom. Only the last group collapse works good.

Would you please tell me what could have caused this strange behaviour ? 

Best Regards

*********************************  UPDATE **************************************
It seems rendrers are what make the collapse not working : when i removed them from the code, the collapse now works fine [DEMO2 ](https://i.imgur.com/dDTxMAq.gifv) / [jsfiddle2](https://jsfiddle.net/bardelman/jcwfbdh2/)

### My environment
* Handsontable version: 1.14.3
* Browser Name and version: chrome 63.0.3239.132 (Official Build) (64-bit)
* Operating System: windows 10 Pro

**Comment by AMBudnik** [comment] 2018-01-12 08:44
Hi @Bartaf83 

Can you share a scenario on how to replicate the issue?

ps. I remember this demo. We have written about the case scenario earlier before.

**Comment by Bartaf83** [comment] 2018-01-12 08:46
i did share the [jsfiddle](https://jsfiddle.net/bardelman/2kujc8r9/2/) reproducing it. Isn't that what you'are looking for ?

**Comment by AMBudnik** [comment] 2018-01-12 08:52
Sorry, it's just a label. What I've meant is a .gif/video. I just do not know what is the odd behavior that you would like to change/fix. Can you explain it a little more? Step by step scenario would definitely help.

**Comment by Bartaf83** [comment] 2018-01-12 09:05
yes man please take your time! i firstly sent this [video demo](https://imgur.com/YAZisNC) and the [jsfiddle](https://jsfiddle.net/bardelman/2kujc8r9/2/) reproducing it then later i've tested the collapse without any rendrers ([demo2](https://imgur.com/dDTxMAq) / [jsfiddle2](https://jsfiddle.net/bardelman/jcwfbdh2/)) and i found that it works like charm without them. The conclusion was that the collapse doesn't work correctly when rendrers are used.

**Comment by AMBudnik** [comment] 2018-01-12 09:07
Hi again @Bartaf83 

the issue is caused by the mergeCells option. It does not respect hiddenRows indexes (something definitely to add in the future).
The first demo http://jsfiddle.net/handsoncode/nfh0a9mq/ does not use merging to create parent rows it just changes the color of border/background.

**Comment by Bartaf83** [comment] 2018-01-12 09:17
i get rid of the mergeCells option but the same collapse bug remains ([demo3](https://i.imgur.com/rX3Uvpq.gifv) / [jsfiddle3](https://jsfiddle.net/bardelman/7ss636nL/1/))

**Comment by AMBudnik** [comment] 2018-01-12 09:30
My bad! You're right. Adding the custom renderers causes the issue.
It looks like some `nestedRows `properties might be lost while adding custom renderers. I guess it's related to `updateSettings`.

Sorry, but I need to leave it for further investigation by for devs. I did not find any possible workaround.

**Comment by Bartaf83** [comment] 2018-01-12 09:32
thanks that you tried , i'm looking forward for a fix :)

**Comment by AMBudnik** [comment] 2018-04-10 12:48
The issue is still replicable.  I have tested easier example here http://jsfiddle.net/handsoncode/kcww1gfy/

And tried `toPhysicalRow` to define a `row` value for the image to be attached but got the images doubled. 

![2gif](https://user-images.githubusercontent.com/10757813/38557562-b6170c8c-3ccd-11e8-8387-f46ed0f89953.gif)


When I wanted to erase the context to `value` for other cases that (row = 1 and col = 0) I got the image jumping (demo: http://jsfiddle.net/handsoncode/xer0dmqx/)

![gif](https://user-images.githubusercontent.com/10757813/38557520-90e3b4ec-3ccd-11e8-8785-81c14b292ba1.gif)

It looks like this issue is not connected to any version of Handsontable PRO and is present from 1.7.0 where nestedRows has been firstly presented.

**Comment by wojciechczerniak** [comment] 2019-09-27 07:11
First of all, the condition`row === instance.toPhysicalRow(1)` is wrong. Renderer gets visual index, so it should be other way round: `1 === instance.toPhysicalRow(row)`.

Then the `else` is missing to set other values than the image:
```
else {
    td.innerHTML = value;
}
```

And everything works just fine:

✅ v1.14.3: https://jsfiddle.net/konc346r/1/
✅ v7.1.1: https://jsfiddle.net/konc346r/
✅ v8.0.0-rc1: https://jsfiddle.net/2758xwvm/

With `updateSettings`: https://jsfiddle.net/konc346r/2/

Did I've missed something @AMBudnik  ?

**Comment by AMBudnik** [comment] 2019-09-27 09:38
Hey @wojciechczerniak 

the chicken is hidden when we close the first parent so it works well in `8.0.0-rc1` in 1 case https://jsfiddle.net/0m1pv8yh/

![chicken](https://user-images.githubusercontent.com/10757813/65758610-a62e6080-e119-11e9-8ed4-49a077ee6ef7.gif)

It also works for the case 2 http://jsfiddle.net/jcn7vyLm/ (`8.0.0-rc1` - from your demo)

![chicken_jumping](https://user-images.githubusercontent.com/10757813/65758974-48e6df00-e11a-11e9-8226-5e8d9877ed48.gif)

Parent 2 is in the 4th position in the first place. After collapsing parent 1 it becomes the index 1 visually which is used to position the chicken here `hot.toPhysicalRow(1)`

**Comment by wojciechczerniak** [comment] 2019-09-27 10:42
Chicken! 😍 

So can we close this ticket? IMO there is nothing to fix

**Comment by AMBudnik** [comment] 2019-09-27 10:55
Sure. We're already exchanging emails with @Bartaf83 so if there's something we're missing here please let me know.

**Comment by AMBudnik** [comment] 2020-05-08 08:21
### Case 1

solved in 8.0.0-beta1 https://jsfiddle.net/ka4Lerwv/

Still works well in 8.0.0-beta2-rev1 https://jsfiddle.net/ka4Lerwv/1/

### Case 2

broken with console error in the console http://jsfiddle.net/9ojdywh5/ with 8.0.0-beta2-rev1.  
Reported and blocked by #6855

**Comment by wojciechczerniak** [comment] 2020-06-15 11:20
> ### Case 2
> 
> broken with console error in the demo http://jsfiddle.net/9ojdywh5/ with 8.0.0-beta2-rev1.
> Reported and blocked by #6855

@AMBudnik #6855 is fixed now. We can retest this issue

**Comment by AMBudnik** [comment] 2020-06-15 11:27
@wojciechczerniak  **Case 1** remains solved https://jsfiddle.net/AMBudnik/35cxeusz/ as well as **Case 2** http://jsfiddle.net/AMBudnik/rw8hdx3m/ I'm adding the release beta2 and 8.0.0.

**Comment by pnowak** [comment] 2020-07-16 10:53
Hi @Bartaf83 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment] 2020-08-06 11:27
Case 1 solved in v 8.0.0 https://jsfiddle.net/g0jxr9ns/
Case 2 solved in v 8.0.0 http://jsfiddle.net/j5p6q1x2/

Thank you for sharing @Bartaf83 

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback.

**Closed by AMBudnik** 2020-08-06 11:27 UTC
Labels: Nested rows, Type: Bug
