### ISSUE TITLE
Incorrect row heights for merged cells in fixed column

### ISSUE THREAD

**Issue by oshibka404** [handsontable/handsontable#4016] opened 2017-01-24 14:31 UTC
### Description
Incorrect row heights in a fixed column when there are merged cells in first column and rowHeaders are disabled

### Steps to reproduce
1. Fix first column (`fixedColumnsLeft: 1`)
2. Disable row headers (`rowHeaders: false`, but they are actually disabled by default)
3. Merge some cells in first column vertically:
```
mergeCells: [
  {row: 0, col: 0, rowspan: 3, colspan:1},
]
```

### Demo
http://jsfiddle.net/h3z0yw50/1/

### Your environment
* Handsontable version: 0.30.0
* Browser Name and version: Chrome 55.0.2883.95
* Operating System: macOS Sierra

**Comment by AMBudnik** [comment] 2017-01-25 09:32
Hi @oshibka404 ,
Thanks for sharing. I got the same odd behavior.
Related issue https://github.com/handsontable/handsontable/issues/3837

**Comment by AMBudnik** [comment] 2018-04-23 12:58
![image](https://user-images.githubusercontent.com/10757813/39127960-d2a8ab92-4706-11e8-9d61-06ad318adcd0.png)

The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by pnowak** [comment] 2020-08-28 12:21
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/8x1umz7n/

**Comment by swistach** [comment] 2021-02-23 11:19
This issue is closed temporarily. We will reopen it for development as it became a part of **Interoperability problems between MergeCells and some core features** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behaviour, feel free to contact me at support@handsontable.com.

**Comment by AMBudnik** [comment] 2024-08-06 13:20
Hi @oshibka404 

the following issue should be fixed with https://github.com/handsontable/handsontable/pull/11007 in Handsontable v14.5.0.

**Closed by AMBudnik** 2024-08-06 13:20 UTC
Labels: bug, Merge cells, Fixing / Freezing, Part of scope, Reported
