### ISSUE TITLE
ContextMenu position after page scroll vertically is off

### ISSUE THREAD

**Issue by troddick** [handsontable/handsontable#3860] opened 2016-11-04 19:56 UTC
### Description

When page loads, if I right-click rowHeader, contextMenu appears next to cursor. If I scroll down in the table, and right-click, again, contextMenu appears next to cursor. If I instead scroll down on the page and not in the table, then right-click, the contextMenu is higher up on the page instead of at the cursor.
### Steps to reproduce

1. Using angular with ngHandsontable. hot-table is sitting within div: 
<div class="col-md-12" style="padding:0;margin:0;height:600px;overflow:hidden">
2. Scroll down the browser window, and right-click on the row number heading
3. ContextMenu appears higher up on the page

I don't think I can create a demo as I have a lot of data manipulation involved in populating the table. I have included a screenshot of my issue.
![image](https://cloud.githubusercontent.com/assets/1580076/20020354/e03c5e4c-a29e-11e6-893e-9570e14d29d7.png)

### Your environment
* Version: angular: '1.4.7', handsontable: '^0.28.4', and handsontable.full.js
* Browser Name and version: issue present in Firefox 49.0.2 and Chrome 54.0.2840.59 m
* Operating System: Windows 7

**Comment by AMBudnik** [comment] 2016-11-08 10:05
Hi @troddick 
ngHandsontable issues should be reported at https://github.com/handsontable/ngHandsontable/issues additionally I wasn't able to replicate the same bug. Can you create a simplified JSFiddle?

**Comment by troddick** [comment] 2016-11-08 19:16
I will try to make a jsfiddle. Alternatively, I can paste the links to my html and controller.js files. I have this project as a public repo on github. Not sure if that would be helpful or not. There's some routing going on also to show this page. It is a child page with the table within it.

**Comment by AMBudnik** [comment] 2016-11-09 08:24
It could be helpful but the most important step to find a solution is to simplify the code and isolate only those settings that causes the issue. That's why it's better to create a Fiddle

**Comment by AMBudnik** [comment] 2016-11-15 13:46
Hi @troddick 
How is your progress?

**Comment by troddick** [comment] 2016-11-15 15:07
Hi there,
Thanks for checking in. I am not able to reproduce it in a Fiddle. It must be due to my set up. 
My application is using angular 1.4.7 and I have a parent page with children within. This table sits within a child page:
https://github.com/troddick/SiGLDMS/blob/master/src/component/projSite/projMultiSiteEditView.html#L69
and has it's setting specified in the controller:
https://github.com/troddick/SiGLDMS/blob/master/src/component/projSite/projMultiSiteEditCtrl.js#L1200

I guess this seems to be more of a me-issue rather than a handsontable library-issue.

Thanks!

**Comment by AMBudnik** [comment] 2016-11-16 11:16
Oh I see. OK, so if you will have any concerns that it can be caused by Handsontable - give me a hint.
I'm closing this issue.

**Closed by AMBudnik** 2016-11-16 11:16 UTC
Labels: Type: Demo needed

**Comment by kleinph** [comment] 2017-03-01 14:45
Hi @troddick 
Did you solve this issue in some other way?

**Comment by AMBudnik** [comment] 2017-03-16 13:56
Hi @kleinph 
If you experience the same issue please share a JSFiddle, CodePen od JSBin example where I will be able to replicate the mentioned issue.

**Comment by kleinph** [comment] 2017-03-17 07:30
@AMBudnik thanks, but we already solved the issue. A CSS rule `height: 100%;` on certain container was the prolbem.

**Comment by AMBudnik** [comment] 2017-03-17 10:46
Ohh I see @kleinph thanks for a quick update and happy to know that it works fine now.
