### ISSUE TITLE
Cut command works not as expected

### ISSUE THREAD

**Issue by baderfall** [handsontable/handsontable#5405] opened 2018-09-14 16:56 UTC
### Description

Currently when I hit cut button value from the cell deletes immediately. I expect value to be deleted only when I paste it to the new cell.

### Steps to reproduce

1. Select cell
2. Click paste in context menu or hit ctrl+x
3. Value deletes immediatly

### Demo
How it works now:
![2](https://user-images.githubusercontent.com/16905445/45564133-2c05a380-b858-11e8-95a4-d08088b5e8ff.gif)
How it should work:
![pmihieu5up](https://user-images.githubusercontent.com/16905445/45564147-3c1d8300-b858-11e8-9517-6e686f5c7236.gif)

### Your environment
* Handsontable version: 5.0.2
* Browser Name and version: Chrome 68
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2018-09-17 11:56
Oh, I see. Yes, that is an inconsistency with Google Sheets and Excel.

**Comment by baderfall** [comment] 2018-09-17 12:07
Cool, do you plan to implement it anytime soon?

**Comment by AMBudnik** [comment] 2018-09-17 12:13
We would need to change the selection plugin or/and turn on the `outsideClickDeselects` so that is not an easy thing to add. We will discuss this possibility on next dev meeting.

**Comment by wojciechczerniak** [comment] 2020-07-01 20:41
This will be implemented with our new formula plugin that is based on [HyperFormula](https://github.com/handsontable/hyperformula) engine. To support fully the new engine copy/cut/paste and relative formulas we will have to redo the cut functionality. More details in #6767

Duplicate of #6767

**Closed by wojciechczerniak** 2020-07-01 20:41 UTC
Labels: Copy-paste, Type: Change
