### ISSUE TITLE
Thousand Separator Changed Into Decimal Separator When Pasting Numeric Value < 1000000

### ISSUE THREAD

**Issue by taribowo** [handsontable/handsontable#7617] opened 2021-03-10 04:57 UTC
### Description
What Happened: I copy pasted a formatted numeric value < 1000000, e.g. 475,962 read as 'four hundred seventy five thousand, nine hundred sixty two', from Excel to Handson table column with type 'numeric' and numericFormat of pattern '0,0' and it got pasted as 475.962, read as 'four hundred seventy five point nine six two'

What Should have happened: it got pasted as 475,962 read as 'four hundred seventy five thousand, nine hundred sixty two'

### Steps to reproduce

1. set a column with the option
```javascript
{
    type: 'numeric',
    numericFormat: { pattern: '0,0' }
}
```
2. paste a formatted numeric value < 1000000 with ',' as the thousand separator, e.g.  '475,962', to a cell in that column
3. the column will read it as 475.962

### Demo

https://jsfiddle.net/1bzta4n3

### Your environment
* Handsontable version: 8.3.1
* Used with wrapper for React
* Browser Name and version: Google Chrome Version 88.0.4324.190 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2021-03-10 08:00
Hi @taribowo 

Thank you for sharing but it seems to be the same issue like this one https://github.com/handsontable/handsontable/issues/4396 
My reproduction https://github.com/handsontable/handsontable/issues/4396#issuecomment-581816255 shows how the comma changes to a dot.

Can please add your feedback to https://github.com/handsontable/handsontable/issues/4396 if you feel that's missing any important note or a scenario? I will close this issue as a duplicate.

**Closed** 2021-03-10 08:00 UTC
Labels: Type: Duplicate

**Comment by taribowo** [comment] 2021-03-10 08:24
Hi @AMBudnik 

thanks for the reply. I've added my comments on #4396 . hope there will be a solution to this weird behaviour
