### ISSUE TITLE
copy paste issue in firefox for % value

### ISSUE THREAD

**Issue by sonamsdiwate** [handsontable/handsontable#2257] opened 2015-03-13 06:59 UTC
For version 0.12 and 0.13 I am facing once issue which is specific to Firefox browser
When we copy percentage data from excel and paste firefox stop working and need to close browser

**Comment by AMBudnik** [comment] 2015-03-13 09:34
I couldn't reproduce it, can you prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/)?

**Comment by sonamsdiwate** [comment] 2015-03-17 07:18
This is specific to Firefox and only for percentage values only

**Comment by AMBudnik** [comment] 2015-05-06 14:23
Do you still face this issue after updating to 0.14.1?

**Comment by AMBudnik** [comment] 2015-07-29 07:37
Issue closed in lack of author's reply.

**Closed by AMBudnik** 2015-07-29 07:37 UTC
Labels: Answered, Demo needed
