### ISSUE TITLE
Numeric cell type doesn't accept an array of a class name

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6800] opened 2020-04-02 11:54 UTC
### Description
If `className` settings option is in an array and some cells are numeric type an error occurs - `Uncaught TypeError: className.split is not a function`. 

### Steps to reproduce

1. Go to https://jsfiddle.net/9mrhybv4/
2. Open a console.

### Demo

https://jsfiddle.net/9mrhybv4/

### Your environment
* Handsontable version: it doesn't seem to be related to any version
* Browser Name and version: Chrome 80
* Operating System: OS Mojave

**Comment by swistach** [comment] 2021-09-02 15:59
Duplicate of #8059

**Closed by swistach** 2021-09-02 15:59 UTC
Labels: Type: Bug, Cell type: numeric
