### ISSUE TITLE
[12.0.0] Error by set borders via updateSettings

### ISSUE THREAD

**Issue by OlgaIOn** [handsontable/handsontable#9455] opened 2022-05-05 16:04 UTC
### Description
Setting the borders is correct the first time. The second time we get an exception in method **checkSettingsCohesion()**

hot.updateSettings({customBorders}); // OK
hot.updateSettings({customBorders}); // Exception

### Steps to reproduce
1. Click 'set borders red' -> OK
2.  Click 'set borders green' -> Exception "Uncaught Error: The "left"/"right" and "start"/"end" options should not be used together. Please use only the option "start"/"end"."

### Demo
https://jsfiddle.net/f7uneyro/

### Your environment
* Handsontable version: 12.0.0

**Comment by adrianszymanski89** [comment] 2022-05-06 07:58
Hi @OlgaIOn 

Thank you for reporting the issue. It looks like it's a regression as it (partially) worked in version 11.1.0: https://jsfiddle.net/aszymanski/54uhjkdy/

**Comment by AMBudnik** [comment] 2022-05-11 12:20
This demo uses Handsontable v12 but `customBorders` use the pre v12 settings of `left`/`right` keys. In v12 we changed that to `start`/`end`. Ref: https://handsontable.com/docs/formatting-cells/#custom-cell-borders

![Zrzut ekranu 2022-05-11 o 14 18 18](https://user-images.githubusercontent.com/10757813/167847922-4f904daa-df65-42c6-98fa-12980d1f9295.png)

Here https://jsfiddle.net/061b8psg/ is the updated demo that changes `left` to `start` and `right` to `end`.

We forgot to add that part to the migration guide for the v11 - v12 switch https://handsontable.com/docs/migration-from-11.1-to-12.0/ 

@OlgaIOn please let me know if it works for you after the changes

**Comment by warpech** [comment] 2022-05-11 14:37
> We forgot to add that part to the migration guide for the v11 - v12 switch https://handsontable.com/docs/migration-from-11.1-to-12.0/

It was not mentioned in the Migration Guide, because the `left`/`right` property names are supposed to continue working if the user does not use `layoutDirection` for backwards compatibility. The problem is when the user executes the method `updateSettings` more than once. It is a regression and we will fix it.

@OlgaIOn sorry about the trouble. As a mitigation, you can replace `left` with `start`, and `right` with `end`, as explained on the page https://handsontable.com/docs/formatting-cells/#custom-cell-borders

**Comment by aninde** [comment] 2022-05-12 13:55
This issue is fixed by v12.0.1 https://jsfiddle.net/3g8fe6na/

**Comment by AMBudnik** [comment] 2022-05-16 12:47
Hi @OlgaIOn 

I'm more than happy to announce that we just released Handsontable v12.0.1 where this issue is fixed. Thank you again for reporting! Here https://handsontable.com/docs/release-notes/ is the full list of changes for the lastest patch.

**Closed by AMBudnik** 2022-05-16 12:47 UTC
Labels: Type: Bug, Custom borders, Regression
