### ISSUE TITLE
Right clicking the table when no cell is selected while context menu is enabled throws error

### ISSUE THREAD

**Issue by toresenneseth** [handsontable/handsontable#2314] opened 2015-03-27 09:19 UTC
When context menu is enabled, right clicking the empty area below the last row when no cell is selected, throws an error.
I've prepared this jsfiddle to demo the problem : http://jsfiddle.net/5hzc9Ltc/4/

This issue might be somewhat related to #2294, I guess?

Workaround for now is to implement the default behavior as a custom context menu, but it would be nice to avoid that.

Great work, by the way!

Thanks!

**Comment by AMBudnik** [comment] 2015-03-27 09:27
Thank you for that report, I got the log also.

**Comment by budnix** [comment] 2015-07-20 13:32
Fixed in 0.16.0

**Comment by toresenneseth** [comment] 2015-08-31 17:54
Hmm...I see that the error is not thrown any more, but the fix as it is implemented now (0.16) has the side effect that you cannot execute a context menu action when the table is empty. So for example, when the table is empty, you cannot insert a new row from the context menu (custom) or initiate a data import of some sort. 
It would be better if the context menu action callback was called anyway, passing 'undefined' (or some other token) as the selRange argument, and then handling that state in the callback itself.

What do you think? I would suggest something like this; (had to use an image, the formatting gets messed up when I paste it in...I've added comments where I suggest the changes should go.) I can prepare a PR if you all agree.

![image](https://cloud.githubusercontent.com/assets/3868635/9585856/a56dfbbe-5019-11e5-8abc-6395c14c0784.png)

**Comment by AMBudnik** [comment] 2016-03-16 15:10
Hi @toresenneseth I tried to check it with 0.24.1 and couldn't reproduce the issue - could you check it please?

**Comment by toresenneseth** [comment] 2016-03-16 19:01
Confirmed that an error is not thrown, but the side effect remains. No context menu is show if you click below the last row (or the table is empty). Why do I want to show the context menu? For example if you accidentally deleted the last row and want to undo (yes, I know ctrl-z will work), or more importantly, if you want to insert a new row when your table is empty.

My "hack" for doing this right now is to listen for the mousedow and mouseup event on the HOT container element, get the contextMenu plugin, build the menu items dynamically, and then showing the context menu by calling .open(..) on the plugin.

Don't know if that's the best solution, but it works...:)

**Comment by AMBudnik** [comment] 2016-03-17 10:01
Thanks for sharing additional information @toresenneseth

**Comment by budnix** [comment] 2016-07-05 11:36
Hi @toresenneseth We changed context menu behavior in 0.26. Could you check it?

**Comment by AMBudnik** [comment] 2016-09-02 07:57
As there was no reply since few months I guess we can close this issue.
Big thanks for anyone who've shared their feedback.

**Closed by AMBudnik** 2016-09-02 07:57 UTC
Labels: Bug, Guess: few hours, Plugin: context menu, Priority: normal
