### ISSUE TITLE
Scrollbar height isn't calculated properly

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4000] opened 2017-01-17 13:06 UTC
### Description

Scrolling isn't smooth, because scrollbar isn't correctly calculated when the rows are of different height.

### Steps to reproduce

1. Open demo: https://jsfiddle.net/wojciech/mL49z9tk/8
2. Scroll down

### Demo

https://jsfiddle.net/wojciech/mL49z9tk/8

![gif](https://cloud.githubusercontent.com/assets/141330/22021126/d02ffbc4-dcbb-11e6-9a02-24a4a074ff41.gif)

### Your environment
* Handsontable version: 0.30 (~~probably works on < 0.20~~)
* Browser Name and version: Chrome  55.0.2883.95 (64-bit)
* Operating System: macOS Sierra 10.12.2

**Comment by wszymanski** [comment] 2017-01-18 09:18
One more example: https://jsfiddle.net/wojciech/bbdgbj1o (cell height set to 50px in CSS)

**Comment by krzysztofspilka** [comment] 2017-01-19 09:10
@wszymanski Could extend the description?  I think that the problem is not the scroll is not smooth, rather that it is not correctly calculated when the rows are of different height. That leads to the issue reported here - the scrollbar doesn't allow you to properly get to the bottom of the grid after initialization. You need to "grab" the scroll several times while it adjusts on its way down. That also gives us the "flickering" effect.

**Comment by Eragra3** [comment] 2017-01-19 11:09
I would like to broaden this problem a bit. I need to lazy load something to my HOT and doing so breaks both scrollbars (they act strange, I can't even say why exactly this happens).

There is my fiddle [http://jsfiddle.net/e5qqvoL0/](http://jsfiddle.net/e5qqvoL0/)
Clicking on table just adds more rows and columns to it. Notice how scrollbars are not updated, especially in the corner.
![hot_bug](https://cloud.githubusercontent.com/assets/9082983/22104481/a2e8b982-de3f-11e6-8828-ae6b1c8019a6.gif)

I tried using hot.render() function, but it didn't help. What I would expect from calling it, is to recalculate scrollbars, so they again resemble real worksheet size.

I hope it's kept as high priority, I think lazy loading data (fetching from server) might be very requested feature.

**Comment by wszymanski** [comment] 2017-01-27 08:31
Within this ticket was fixed **only the situation** when **autoRowSize** is set to true. We need documentation change (#4014). 

Updated examples for tests (just change served libraries):

Rows with fixed size set by `colWitdth` attribute: https://jsfiddle.net/0mofdvwo/1
Rows with fixed size set by CSS: https://jsfiddle.net/bbdgbj1o/1

**Comment by AMBudnik** [comment] 2017-02-15 13:07
Thanks for the clarification @wszymanski 
We can close this issue.

**Closed by AMBudnik** 2017-02-15 13:07 UTC
Labels: Core: alignment/height/width, Priority: high, Status: Released, Tested, Type: Bug
