### ISSUE TITLE
Copy and Paste using the keyboard shortcut is broken on the latest build

### ISSUE THREAD

**Issue by gimansour** [handsontable/handsontable#2534] opened 2015-06-05 01:32 UTC
Uncaught ReferenceError: helper is not defined
CopyPasteClass.onKeyDown @ handsontable.full.min.js:formatted:14741

**Comment by jansiegel** [comment] 2015-06-05 08:20
@gimansour, thanks a lot for reporting this - we've just released a fix for this as [0.15.0-beta6](https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta6)

(duplicate of #2530)

**Closed by jansiegel** 2015-06-05 08:20 UTC
