### ISSUE TITLE
getRowHeight doesn't update its value

### ISSUE THREAD

**Issue by duccoder** [handsontable/handsontable#2822] opened 2015-09-18 03:21 UTC
Hi, I found http://docs.handsontable.com/0.18.0/Core.html#getRowHeight and I apply this but not work. I create sample fiddle here, it's return `undefined`

http://jsfiddle.net/duccoder/u9pe4qdk/

**Comment by AMBudnik** [comment] 2016-02-11 16:00
Hi, I couldn't reproduce this issue. Is it still present in newest version?

**Comment by AMBudnik** [comment] 2016-03-07 13:41
I'm closing this issue but please feel free to update in any time.

**Comment by isiddhant** [comment] 2016-03-09 06:44
Yes this issue is still there, please see the attached screenshot.

http://jsfiddle.net/duccoder/u9pe4qdk/

 I have highlighted the "Undefined"
![capture](https://cloud.githubusercontent.com/assets/17636666/13627420/5fe3fd74-e5f0-11e5-8e24-e629faee6a5b.PNG)

**Comment by AMBudnik** [comment] 2016-03-09 08:59
Thanks for sharing @isiddhant

**Comment by AMBudnik** [comment] 2016-10-11 07:00
updated demo: http://jsfiddle.net/pdf7m7op/
this method works when you enable `autoRowSize` or set `rowHeights` but it does not return correct value if data breaks into few lines (type anything longer in the B1 cell to see)

**Comment by swistach** [comment] 2017-01-04 08:44
Definitely we should improve `getRowHeight()`, but at present you can to use `view.wt.wtTable.getRowHeight()`.
Example: http://jsfiddle.net/wcyrgmf3/

**Comment by AMBudnik** [comment] 2017-01-30 10:14
We should add an information that it returns only what we've typed in `rowHeights` cause we will get `undefined` if we won't use `rowHeights`.

**Comment by AMBudnik** [comment] 2018-04-24 10:15
I think that we should add `documentation needed` label as turning on the `autoRowSize` plugin enables us to call `getRowHeight` but it's not the same method as the `getRowHeight` from the core. 

![image](https://user-images.githubusercontent.com/10757813/39181059-c766095c-47b8-11e8-82f1-4d62d2a82dbf.png)

As far as it's mentioned in the docs the core method returns values set by `rowHeights` and the plugin's method returns actual height in pixels.

**Comment by kirszenbaum** [comment] 2021-09-14 11:50
The documentation aspect of this issue will be dealt with in #8721. I'm removing the `documentation` label.

**Comment by AMBudnik** [comment] 2022-10-18 08:02
Simplified demo: http://jsfiddle.net/2qxwdpuk/. It works the same in v12.1.3 - the `getRowHeight()` method returns `undefined`, as it copies what is defined in the `rowHeights`. @kirszenbaum the information that `getRowHeight()` Core method returns the `rowHeights` value is not specified. But at the same time, I'm not sure if that's the original intention. I've raised the question internally and will update the thread once I get the feedback.

**Comment by warpech** [comment] 2022-11-05 22:44
Yesterday, we discussed with @krzysztofspilka that the Core `getRowHeight` is a poorly understood method mainly due to confusing name and misleading docs. This issue should be relabelled from `Bug` to `Docs`.

The docs say that `getRowHeight` returns a `number`, which is the row height. This is very incomplete information.

The reality is a bit more complex:
- The return types of `getRowHeight` are: `number` or `undefined`
- When `getRowHeight` returns `undefined`, it means that Handsontable does not have information about the row height from the configuration options nor the plugins (AutoRowSize, ManualRowResize). In that case, the default row height is to be assumed.
- What is row height actually
   - The default row height is 23 pixels.
   - If you know that your rows will have a different height than the default (because you use multiline text or custom renderers or custom styles), you should either:
      - populate `rowHeights` configuration option with your row height. This requires preparation on your end to know that numbers, but results in the best runtime performance.
      - or, turn on `autoRowSize: true` to tell Handsontable that the row size should not be assumed to be default, but rather that it should be measured in DOM. It impacts the runtime performance but is accurate.
- `rowHeights` has priority over AutoRowSize plugin. ManualRowResize plugin has priority over all.
- The row height used by `getRowHeight` method, `rowHeights` configuration option, etc, includes 1 pixel for the border.

It is quite analogous for the `getColWidth`, but not fully, because that one always returns a number, even when a column has a default width.

**Comment by kirszenbaum** [comment] 2022-11-09 13:28
I'm expanding the API ref of `getRowHeight()` in #10099.

**Closed** 2022-11-16 09:15 UTC
Labels: Docs: Content, Core: Alignment / height / width
