### ISSUE TITLE
[7.3.0] Filter component scrolls by itself

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6497] opened 2019-11-25 11:44 UTC
### Description

While testing 8.0.0-beta.1 version I've spotted an issue which results in scrolling the "Filter by value" item list component. The component scrolls by itself when we try for example deselect the first item and while we move the cursor around the component scrolls.

### Steps to reproduce

1. Prepare the demo where the filter item list is higher than the component (to make scrollbar visible);
2. Deselect the first item and move the mouse around the component;
3. As a result, You'll see that the list component scrolls by itself.

It seems that the bug doesn't occur when I use fiddle (related to iframes?).

![Kapture 2019-11-25 at 12 23 11](https://user-images.githubusercontent.com/571316/69536578-8206c880-0f7e-11ea-89d0-28677620ff2a.gif)

### Your environment
* Handsontable version: 8.0.0-beta.1 & 7.3.0
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by aninde** [comment] 2019-11-25 11:57
Probably this bug was caused by changes from `7.3.0` v. It occurs in `7.3.0` v. without merged `8.0.0-beta1`.

**Comment by jansiegel** [comment] 2019-11-25 11:59
> * Handsontable version: 8.0.0-beta.1 & 7.3.0

**Comment by AMBudnik** [comment] 2019-12-06 12:05
Works well with the latest build (6.12) https://jsfiddle.net/AMBudnik/jkt25eha/

Tested on Catalina and Chrome 78/ FF 70 / Safari

**Comment by aninde** [comment] 2019-12-10 12:01
The latest build (6.12) https://jsfiddle.net/AMBudnik/jkt25eha/ also works well on IE 11, Edge / Windows.

**Comment by AMBudnik** [comment] 2020-05-11 12:46
It does not scroll down itself but scrolls up. Fortunately, it works well (does not scroll automatically) in 8.0.0.-beta2-rev2

8.0.0.-beta1 https://jsfiddle.net/gkd7of59/ (broken)
8.0.0.-beta2-rev2 https://jsfiddle.net/9phsmtrL/3/ (OK)

**Comment by aninde** [comment] 2020-07-10 12:28
Still works with latest `8.0.0-beta2-rev21` https://jsfiddle.net/aninde/dL8w20un/

**Comment by wojciechczerniak** [comment] 2020-07-10 12:43
This issue was already released and is a part of HoT since around 7.3.0? 
@aninde @AMBudnik Please double check and remove from v8 list if that's true

![Screenshot 2020-07-10 at 14 41 00](https://user-images.githubusercontent.com/4718998/87155571-6fe25c00-c2bb-11ea-9a33-9e740b79cbb3.png)

**Comment by aninde** [comment] 2020-07-13 08:20
Yes, it is fixed by `7.4.2` https://jsfiddle.net/aninde/uhcan1yk/ so I'm removing it from 8.0.0 scope and I'm closing it.

**Closed by aninde** 2020-07-13 08:20 UTC
Labels: Filtering, Guess: few hours, Regression, Status: Merged (ready for release), Type: Bug, scroll
