### ISSUE TITLE
handsontable headers do not scroll when initialized into detached container 

### ISSUE THREAD

**Issue by warrenspe** [handsontable/handsontable#7627] opened 2021-03-11 17:20 UTC
### Description
When a handsontable is initialized into an element which is not yet attached to the DOM, the cloned headers do not follow the table on scroll.

### Steps to reproduce
See Demo below - try to scroll horizontally

### Demo
https://codesandbox.io/s/vanilla-handsontable-pr-forked-61obk

### Your environment
* Handsontable version: 8.3.1 & 8.3.0
* Browser Name and version: Chrome 88
* Operating System: Windows

**Comment by swistach** [comment] 2021-03-18 11:12
Hi @warrenspe,
We know about this issue. We requested that in #5633.
In the meantime, you can use the workaround suggested there. You can use `updateSettings({})` instead of `render()`.

Modified demo: https://codesandbox.io/s/vanilla-handsontable-pr-forked-une7t?file=/src/index.js:837-860

Close due to duplicate of #5633 - please track work progress there.

**Closed by swistach** 2021-03-18 11:12 UTC
