### ISSUE TITLE
Possibly a bug: autoRowSize option doesn't render cells (v0.28.4)

### ISSUE THREAD

**Issue by andrewQwer** [handsontable/handsontable#4008] opened 2017-01-19 11:35 UTC
Hi, I am trying to use `autoRowSize` option but with no luck.
When I don't use this options HTML markup for HOT looks like this:

![image](https://cloud.githubusercontent.com/assets/710513/22105080/69909e3e-de53-11e6-8d4f-a454c1603a30.png)

`thead` and `tbody` tags have rows.
But when I turn on `autoRowSize` option markup looks like this:

![image](https://cloud.githubusercontent.com/assets/710513/22105099/837341da-de53-11e6-8f3e-a22c84100617.png)

![image](https://cloud.githubusercontent.com/assets/710513/22105231/230702c2-de54-11e6-8356-bb26201a0981.png)

`thead` and `tbody` tags are empty and HOT area is blank

Options that I use for HOT configuration:

```
                              data={this.props.rowsData}                            
                              dataSchema={this.props.dataSchema}
                              columns={mappedColumns}
                              colHeaders={this.props.colHeaders}
                              cells={this.renderCells}
                              commentedCellClassName='htCommentCell o-hot-cell-error'
                              stretchH="all"
                              height={500}
                              minSpareRows={minSpareRows}
                              colWidths={200}
                              fillHandle={{
                                  autoInsertRow: this.props.mode == BulkEditorModes.General,
                                  direction: 'vertical'
                              }}
                              wordWrap={true}
                              contextMenu={['remove_row']}                             
                              autoRowSize
                              comments
                              manualColumnResize
                              columnSorting
                              sortIndicator                              
```

**Comment by andrewQwer** [comment] 2017-01-19 12:50
UPDATE: after investigating properties one by one I figured out that problem is in `cells` property.
Take a look at this example: http://jsfiddle.net/andrewQwer/s6t768pq/461/ I print `prop` argument and it always shows `id, name` values that is good.
But if you turn on `autoRowSize` option extra value `-1` is printed: http://jsfiddle.net/andrewQwer/s6t768pq/462/ This breaks my internal logic that parses `prop`

**Comment by AMBudnik** [comment] 2017-01-23 10:52
I do not think that it was intended, especially if it's changed after switching on/off the `autoRowSize`.

Thanks for sharing @andrewQwer

**Comment by aninde** [comment] 2019-09-30 12:54
Sadly, a bug is still replicable in `7.1.1` v. http://jsfiddle.net/aninde/hpf1duqs/. 
Behaviour is defferent in latest, release-candidate. 

In v. `8.0.0-rc1` instead of `-1` we receive `undefined`
 http://jsfiddle.net/aninde/y81bz30L/

We are currently testing a version `8.0.0-rc1` with many breaking changes, I recommend observing information from issue #5751. More about changes in the PR #5945.
Changes will be released soon.

**Comment by swistach** [comment] 2021-01-11 18:45
Hi @andrewQwer,
We fixed it in v8: https://jsfiddle.net/jhcvzpwt/ 🎉
Thank you for your help and detailed investigation!

**Closed by swistach** 2021-01-11 18:45 UTC
Labels: Type: Bug
