### ISSUE TITLE
Nested Header's colspanArray creates a duplicate at the end

### ISSUE THREAD

**Issue by chhinendu** [handsontable/handsontable#5654] opened 2018-12-12 06:58 UTC
### Description
Nested Header's colspanArray should have same headers as given in the settings. Currently it creates a duplicate at the end.

### Steps to reproduce
1. assign your nestedHeaders property in table
2. Create the hot instance
3. check the plugin nestedHeaders -> colspanArray

### Demo
![image](https://user-images.githubusercontent.com/16325417/49852141-49232180-fe09-11e8-9cb1-8fcd5937056c.png)

### Your environment
* Handsontable version: 6.2.0 
* Browser Name and version: Chrome v70
* Operating System: Windows

**Comment by AMBudnik** [comment] 2018-12-12 07:48
Hey @chhinendu 

Thank you for sharing. I have replicated the same result here https://jsfiddle.net/gbv9azch/

I think that this can actually by the cause of this issue

![last_col2](https://user-images.githubusercontent.com/10757813/49854515-a5c31400-fdea-11e8-9bd3-785cdf765ceb.gif)

**Comment by AMBudnik** [comment] 2019-12-30 10:47
Related to https://github.com/handsontable/handsontable/issues/5882

**Comment by AMBudnik** [comment] 2019-12-30 10:49
Duplicate of https://github.com/handsontable/handsontable/issues/5015

**Closed by AMBudnik** 2019-12-30 10:49 UTC
Labels: Nested Headers, Type: Bug
