### ISSUE TITLE
ManualColumnMove dragging breaks after updateSettings()

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#6004] opened 2019-05-08 14:29 UTC
### Description
I ran into an odd issue in my app where after the first column drag with `manualColumnMove` then subsequent drags of columns would not appear correctly or let you drag all the way to the right. After some debugging I think I isolated it to the fact that we call `updateSettings()` after the drag, but not right away (its a server round-trip response). It doesn't seem to matter *what* we update, just the call to `updateSettings()` makes the column dragging get weird.

Demo: https://jsfiddle.net/tkob1frw/

### Steps to reproduce

1. Open demo: https://jsfiddle.net/tkob1frw/ (which has `manualColumnMove: true` and `setTimeout(() => hot.updateSettings({}))` from `afterColumnMove` hook)
2. Drag the "Name" to between "Value" and "Start"
3. Try to drag the "Description" column to the right. Notice you can't drag past "Name" and the drag indicator is not aligned correctly.

![img](http://g.recordit.co/63AA9UGl5L.gif)

Note that:
- The first drag always works. The second drag (after `updateSettings()`) has issues. 
- If you comment out `setTimeout(() => hot.updateSettings({}))` there's no problem with the second (or any) drag.
- If you remove the `setTimeout` so it's just `hot.updateSettings({})` from `afterColumnMove` there's also no problems with the second drag. Somehow it only happens if the `updateSettings()` is some time later.
- In the demo I pass `{}` but it doesn't seem to matter what you pass to `updateSettings()`, I tried a lot of different things including `hot.updateSettings(hot.getSettings())`.

### Demo

https://jsfiddle.net/tkob1frw/

### Your environment
* Handsontable version: 7.0.2
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment] 2019-05-13 12:39
Thank you for sharing. I can't see this working in any version before. But what's surprising is the fact the only UI is broken.

**Comment by aninde** [comment] 2019-09-29 08:02
`8.0.0rc-1` doesn’t fix described here bug. 
 It is related to #6292.

As @AMBudnik mentioned this bug only applies to UI. The feature works correctly. You can move the column to make it last in the table. However, it renders incorrectly.
 
A thick line marking the place of pasting a new column is stopped at the place where the last column started previously. This is caused by incorrectly calculating the width of the columns after moving.  This is described in issue #6292.

![Screenshot 2019-09-29 at 10 02 11](https://user-images.githubusercontent.com/30186818/65828908-4910e700-e2a0-11e9-821b-3a7d6aa2bd18.png)


**Demo**
v `8.0.0-rc1` https://jsfiddle.net/aninde/u3joafed/

**Comment by aninde** [comment] 2019-10-08 10:10
Sadly the issue is still replicable in the newer version of `8.0.0-rc1` that fixed  #6292 
The second move still got broken UI. 

`updatteSetting` is a separate problem, that will be fixed in the future.

Demo
v. latest on 8.10.19 `8.0.0-rc1` https://jsfiddle.net/aninde/nz59jgqr/

**Comment by AMBudnik** [comment] 2020-06-16 09:29
UI of moving is still broken - tested with 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/rmjLu3dz/

![issue](https://user-images.githubusercontent.com/10757813/84757506-8818d100-afc4-11ea-9a98-da670fe5c545.gif)

**Comment by wojciechczerniak** [comment] 2020-06-17 13:43
@wszymanski We've missed something? Ghost div is not reading from indexMap?

**Comment by wszymanski** [comment] 2020-06-17 15:12
The `updateSettings` don't work stable in some cases. Maybe it's a problem related to resetting some states.

https://github.com/handsontable/handsontable/blob/5ec680c6315d6f0cc35926807fc77a81b098a1e7/src/plugins/manualColumnMove/manualColumnMove.js#L123-L133

**Comment by pnowak** [comment] 2020-08-26 10:17
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/97uwqo8v/

**Comment by aninde** [comment] 2020-09-29 12:40
@aaronbeall I'm glad to see that this issue will be fixed by the upcoming `v8.1.0` https://jsfiddle.net/aninde/ax3Lt95e/
We plan to release it this week (Oct 1), as long as everything goes well.

![fized-6004](https://user-images.githubusercontent.com/30186818/94559529-acda4100-0261-11eb-85a1-e6278c91bc1b.gif)
![Screenshot 2020-09-29 at 14 40 24](https://user-images.githubusercontent.com/30186818/94559565-bb285d00-0261-11eb-956a-c5ae8c131c8a.png)

**Comment by AMBudnik** [comment] 2020-10-01 13:21
Hey @aaronbeall we've just released Handsontable 8.1.0. 
Thank you for sharing the issue and making Handsontable better 👍 🥇

**Closed by AMBudnik** 2020-10-01 13:21 UTC
Labels: Core: update settings, Moving, Type: Bug
