### ISSUE TITLE
Rendering and Scrolling Slow for Large Tables

### ISSUE THREAD

**Issue by tympollack** [handsontable/handsontable#3591] opened 2016-06-20 17:52 UTC
https://jsfiddle.net/vatexx36/7/

This fiddle creates a basic instance with 2.5 million rows. The table takes 4-6 seconds to render, and scrolling is very slow. I've also noticed that the farther you scroll down, the slower the scroll render function becomes. Also, if you're near the bottom of the table, just selecting a cell can take a long time, but this is different than at the top of the table.

Are there any ways to increase performance for tables with many rows? Why does it take longer the more I scroll? Why does it matter what position I'm at in the table if it's only rendering a portion of it?

Thanks.

**Comment by tympollack** [comment] 2016-06-20 19:31
Worth a mention, if I up it to 7.5 million, I can't really even scroll around. 10 mil just breaks the page before it renders.

**Comment by LarsVonQualen** [comment] 2016-06-20 20:15
I'm seeing similar sluggishness in Internet Explorer, i've created a fork of @tympollack 's fiddle (https://jsfiddle.net/larsvonqualen/a2xdff5n/3/), that illustrates the use case i'm currently working on, about 90 columns and 300 rows with virtual rendering. The performance difference between Chrome and Internet Explorer 11 is remarkable. Now I do understand that Internet Explorer is kind of slow, but after some light profiling, it seems to me that the main problem is lots and lots of reflows during rendering, which could be caused by lots of offset requests on elements. Here's a great list of things that triggers reflows: https://gist.github.com/paulirish/5d52fb081b3570c81e3a 

It's a shame that the Handsontable team apparently won't optimize for Internet Explorer. I can't be the only one working with this grid in an enterprise business where most users still rely on Internet Explorer 11?

It would be great if the Handsontable team would acknowledge the IE problems, and actually try and fix it. Fingers crossed :smiley: 

In @tympollack 's case i would suggest adding a fixed size to make sure Handsontable uses virtual rendering.

**Comment by tympollack** [comment] 2016-06-20 21:00
@LarsVonQualen I set column widths and row heights manually on table creation so they don't need to be individually calculated, but the Handsontable still calculates the full size of the table on all render calls (which happens during scroll and on selection end).

**Comment by LarsVonQualen** [comment] 2016-06-21 06:39
I'm referring to this https://docs.handsontable.com/0.25.1/demo-scrolling.html 😃 

I just noticed that the vertical scrollbar gets quite small in your example, and i think the sluggishness you experience is related to the fact that there's actually create more than 7.5 million HTML Dom Elements in your example. Virtual scrolling will mitigate this by only creating those elements that are actually visible to the user, which greatly improves performance.

**Comment by tympollack** [comment] 2016-06-21 13:03
@LarsVonQualen Thanks for your suggestion, but if you put too many rows in that demo, the table still breaks. And we already set width/height of the table as well.

**Comment by AMBudnik** [comment] 2016-07-20 12:30
We're closing all improvement suggestions topics and uploading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Issue will be reopened with the first update.
All comments, investigation results or suggestions are welcome.

**Closed by AMBudnik** 2016-07-20 12:30 UTC
Labels: Core: performance, Improvement suggestion

**Comment by tkane2000** [comment] 2019-03-06 16:43
Hi!  It looks like there are a number of tkts related to scroll performance and most have been closed and moved to the wiki.  I'm not sure exactly what's meant by that?  If they're haven't been addressed then they should still be opened, no?

We're seeing major issues with scrolling and jankiness.  Can you please give an update on the state of scrolling/rendering performance?  Is this something that's being worked on or does HOT just have it's limits?

Here is a list:
- https://github.com/handsontable/handsontable/issues/4947
- https://github.com/handsontable/handsontable/issues/3591
- https://github.com/handsontable/handsontable/issues/3370
- https://github.com/handsontable/handsontable/issues/4779
- https://github.com/handsontable/handsontable/issues/1944
- https://github.com/handsontable/handsontable/issues/4970

Thanks!

**Comment by AMBudnik** [comment] 2019-03-07 13:56
Hey @tkane2000 

some of the issues that are closed and labeled as 'Improvement suggestion' are those who mention the subject however the tips aren't suitable for our library.

Currently, the issue that I recommend to follow is the one that I've sent you in the previous post https://github.com/handsontable/handsontable/issues/5769
