### ISSUE TITLE
Copy/Paste in Safari on a mac

### ISSUE THREAD

**Issue by isaacdcm** [handsontable/handsontable#2220] opened 2015-03-04 16:50 UTC
This is similar to issue #1930 but some differences.  Primarily when 1930 was made, copy and paste did work although it did strange things sometimes; now its not working at all.

For some reason, the callback for copy/paste doesn't trigger at all and I get the feeling that the events being attached to are being caught by some other event handler but I don't know which one and don't know how to debug.  It is definitely not an issue on firefox for the mac.

The right click menu copy and paste do work as expected, only the one gotten by hitting command-c and command-v

**Comment by isaacdcm** [comment] 2015-03-04 16:51
Some additional info, this is on the latest version of hands on table released Feb 19

**Comment by isaacdcm** [comment] 2015-03-04 17:32
It seems that the copy/paste buttons on the edit menu ate grayed out; and occasionally it will work and the edit menu flashes.  All of this is telling me that safari is probably blocking the copy/paste event because when I have clicked on the grid it is not telling safari that the document is currently in a mode where copy/paste would make sense.  

Another thing I found is that when it does work, it inserts an extra empty line at then of the copied text.  This is an issue when I go to paste because it ends up clearing out one row below the intended range.

**Comment by iaefai** [comment] 2015-03-07 09:20
I seem to be having a similar issue, works in other browsers but not safari.

**Comment by AMBudnik** [comment] 2015-03-09 15:30
Added to milestone 0.13.1

**Comment by sonamsdiwate** [comment] 2015-03-17 07:17
same issue I am able to reproduce but specific to Firefox browser and for percentage values only

**Comment by kevintynfron** [comment] 2015-04-23 10:36
I have the same issue and it's a bit of a showstopper. 

Looking at it using the callbacks demo at http://handsontable.com/demo/callbacks.html,  I've got some more info.

1. Load the page
1. Click "select all" twice to clear all of the events
1. Click on "Clear" to clear the event log
1. Select the "beforeChange"  event
1. Go to the data table and copy the "Maserati" cell
1. Attempt to paste it over the cell below (which currently contains "0")

On IE 11, Chrome 42, FF 37 on windows and FF and Chrome on mac, you get 
>157 @9.393 [beforeChange] [[1,1,0,"Maserati"]], "paste",
i.e. pasting into row 1, column 1, previous value 0, new value "Maserati"

Using Safari on the mac, you get 
>103 @635.614 [beforeChange] [[1,1,"0","0"]], "paste",
i.e. pasting into row 1, column 1, old value 0 (string this time, not numeric value), **new value = "0", not "Maserati"**

You can repeat this on any cell, and what seems to be happening is that it's pasting in the existing contents of the cell which makes it look it's not working at all.

**Comment by krzysztofspilka** [comment] 2015-06-03 13:03
Released in https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5

**Comment by isaacdcm** [comment] 2015-06-04 18:07
Still seeing the issue.
The copy seems to be working, but paste is not on a mac using safari.

**Comment by weigruf** [comment] 2015-06-05 08:59
I worked on a possible solution and I will list my findings here:

I managed to solve the paste safari issue by having a event listener such as:

		$(document).bind('paste', function(e) {
                    var val = e.originalEvent.clipboardData.getData('Text');
                    if (val) {
                         ...
                    }
                 });

Now, you can pass that value on the triggerPaste CopyPasteClass prototype method. I used localStorage to do that but this is not necessary.

N.B: A localStorage approach implies that you can have up to 5MB worth of clipboard data at any given time.

Another listener that helps:

(function(b){
                var browserName = '';
                if (b.hasOwnProperty("name")) {
                    browserName = b.name;
                }
                $('body').on('click', 'table.htCore tbody tr:not(:first-child) td', function(e) {
                    // Only for Safari - need to refocus and add the contentEditable attribute
                    if (browserName === "Safari") {
                        var $el = $(this);
                        if (!$el.attr('contentEditable')) {
                            $el.prop('contentEditable', 'true');
                        }
                        $el.focus();
                    }
                });
}(window.bowser || {}));

This example uses browser detection plugin bowser.

Even better you can pass that contentEditable attribute on the element in the plugin.

Related WebKit paste bug: https://bugs.webkit.org/show_bug.cgi?id=75891

On the plugin, on CopyPasteClass prototype method passed the value directly on the setTimeout fn:

_this.triggerPaste(event, _this.elTextarea.value);

Hope my findings help a bit.

**Comment by isaacdcm** [comment] 2015-06-05 17:16
Working perfect on my end; Thanks for the fix :-)

**Comment by trestrantham** [comment] 2015-07-09 00:41
This does not seem to be working for me on `v0.15.1` (or `v0.15.0-beta6`). I am trying to paste from Excel a single column with 2 or more rows. When I paste in, the first cell value is blank and the other rows are ignored.

**Comment by AMBudnik** [comment] 2015-07-09 07:29
@trestrantham is right. I tested it with google drive spreadsheets and when I copy for example 3 rows of data only second and third row is actually pasted in HOT. Works fine with Chrome but not in Safari.

Check example [demo](https://jsfiddle.net/vzzn6w3p/4/)

**Comment by trestrantham** [comment] 2015-07-09 16:28
Thank you for confirming this. I did want to note that I'm seeing similar results with pasting from Numbers to HOT. However, I'm seeing N-1 rows being pasted (both with Numbers and in your Google Spreadsheet to HOT example). As in, selecting "first", "second", and "third" only pastes in "first" and "second".

However, my actual use case is pasting from Excel for Mac to HOT where *no* rows are pasted in and the first target cell is blanked out. So attempting to paste "first", "second", and "third" will case the target HOT cell to be empty (blanking out any existing value) and target HOT rows 2 and 3 will be unaffected.

I am also seeing the expected results in Chrome without issue.

This is mission critical to my use case so please let me know if there's anything I do can do to assist in resolving this--even if that's just pointing me to the relevant section of code to start debugging.  Thanks!

**Comment by trestrantham** [comment] 2015-07-09 16:46
After talking with a colleague I discovered they were using a version (`v0.12.3`) that pasting from Excel for Mac to HOT was working. I've downgraded to that for now. Hopefully that will provide a valid reference point for a working commit to `git bisect` from.

**Comment by trestrantham** [comment] 2015-07-09 17:39
As a followup, this works as expected through `v0.15.0-beta3` and seems to break in `v0.15.0-beta5`.

**Comment by budnix** [comment] 2015-07-14 14:26
Hi @trestrantham What exactly Excel for Mac software do you use? This is Apple Numbers or another vendor?

**Comment by tikitikifoofoo** [comment] 2015-07-15 18:32
+1 on this issue. I cannot copy/paste from either Google Sheets or Excel into the sheet on the HOT homepage (which presumably uses 0.16.0).

**Comment by AMBudnik** [comment] 2015-07-15 19:05
Thanks for support, it's under development so it will be fixed in no time.

**Closed** 2015-07-24 09:38 UTC
Labels: Bug, Guess: few hours, Plugin: copy-paste, Priority: high, Released, Tested
