### ISSUE TITLE
[8.0.0-beta.2] Selection does not work properly with hiddenColumns/hiddenRows and copy/paste functionality

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7120] opened 2020-07-14 11:51 UTC
### Description
If you copy data from two columns, while there are any hidden columns between them, the selection is incorrect when pasting.
![Jul-14-2020 13-43-05](https://user-images.githubusercontent.com/1555809/87422519-0d4dd080-c5d9-11ea-9272-147aced2adcb.gif)

### Steps to reproduce

1. Select `A` and `D` column.
2. Copy data from both columns.
3. Select `A1` and paste.

### Expected behaviour
Selected both columns.
 
### Currently behaviour
Selected only the first column

### Demo

https://jsfiddle.net/ov1b4yaj/ `8.0.0-beta.2` broken
https://jsfiddle.net/9xu8y3sr/ `8.0.0-beta.1` works well
https://jsfiddle.net/yhLnogmd/ `7.4.2` works well

### Your environment
* Handsontable version: 8.0.0-beta.2
* Browser Name and version:
* Operating System:

**Comment by aninde** [comment] 2020-07-14 11:55
Occurs since `8.0.0-beta2-rev1` https://jsfiddle.net/aninde/6ydxacor/

**Comment by pnowak** [comment] 2020-07-14 12:27
With the hiddenRows behaves the same - https://jsfiddle.net/7tvxok16/

**Comment by budnix** [comment] 2020-07-15 01:08
I've looked into the code and it seems that this is desired behavior. Demo attached to the issue uses `copyPasteEnabled: false` option which disables copy/paste functionality for hidden indexes. That's why while pasting the data you've got only two columns. I've compared that with 7.4.2 and it works the same. Please correct me if I'm wrong.

**Comment by aninde** [comment] 2020-07-16 13:45
This issue is solved by `pre-8.0.0-rev1`. 
Selection works good while pasting `hiddenColumns`/`hiddenRows` with headers and cells.
Hidden Columns https://jsfiddle.net/aninde/oq4ntz9h/, hidden rows https://jsfiddle.net/aninde/yco4mpr3/


![cp-hidden](https://user-images.githubusercontent.com/30186818/87678400-2db59080-c77b-11ea-88d9-a78e8508a8a6.gif)

**Comment by aninde** [comment] 2020-07-17 06:30
I am closing it as a regression on version `8.0.0-beta.2`. Cannot be reproduced on the stable `7+` version.

**Closed by aninde** 2020-07-17 06:30 UTC
Labels: Copy-paste, Hiding, Status: Merged (ready for release), Type: Bug
