### ISSUE TITLE
Formulas does not apply for some cells

### ISSUE THREAD

**Issue by igor-tvardyi** [handsontable/handsontable#4430] opened 2017-07-26 12:32 UTC
Formulas in some cells look like text.

### Demo
http://jsfiddle.net/74v7f2ht/3/

### Your environment
* Handsontable version: 1.12.0

Solution: Add in the first row 7th element.
But it still a bug

**Comment by AMBudnik** [comment] 2017-07-26 12:40
Thank you for sharing @d-aven

**Comment by AMBudnik** [comment] 2017-10-27 06:31
Still the same using 1.14.3 http://jsfiddle.net/handsoncode/vopegrfq/

**Comment by AMBudnik** [comment] 2018-08-27 09:55
The formulas are still not being counted properly.

Curerent version http://jsfiddle.net/c4n5p3mz/ (`5.0.1`)

![image](https://user-images.githubusercontent.com/10757813/44652143-73340d80-a9eb-11e8-8ce1-25cef99d1ca4.png)

The issue doesn't seem to be related to any formula type. I have tried `SUM`, `AVERAGE` and `MIN`.

**Comment by AMBudnik** [comment] 2021-02-11 14:19
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by aninde** [comment] 2021-05-21 09:43
Updated demo 
Same result v8.4.0 (http://jsfiddle.net/aninde/nxfu4bzm/) 

Behavior is different on currently tested v9.0.0 with [HyperFormula](https://handsontable.github.io/hyperformula/) as the engine. 
Seems that the new engine solves this problem. 
v9.0.0 + HF http://jsfiddle.net/aninde/p83vbn6e/

<img width="418" alt="Screenshot 2021-05-21 at 11 39 40" src="https://user-images.githubusercontent.com/30186818/119117331-6cfede80-ba29-11eb-8c98-e24965620e7b.png">

**Comment by aninde** [comment] 2021-05-26 12:54
Still work well with v9.0.0 http://jsfiddle.net/aninde/2vf7q56a/.

**Comment by AMBudnik** [comment] 2021-05-26 12:57
It works as expected, so I'm temporarily open the topic to close it after the official version of v9 is released.

**Comment by AMBudnik** [comment] 2021-06-01 07:28
@aninde the following scenario is covered with the new freeze http://jsfiddle.net/nze6oc1g/ (**works well**)

**Comment by AMBudnik** [comment] 2021-06-01 12:15
Hi @igor-tvardyi 

The issue is finally solved in v9. It's been a while but I hope you can still benefit from this fix.

For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)

**Closed** 2021-06-01 12:15 UTC
Labels: Formulas, Status: Released, Type: Bug
