### ISSUE TITLE
HOT scrolling breaks in flexbox

### ISSUE THREAD

**Issue by c-dante** [handsontable/handsontable#2806] opened 2015-09-08 15:32 UTC
In our application, we have a large data set and some cell renderers configured.

The table looked good and worked well enough for a while, but after a design change that moved some flex boxes around, the scrollbars have incredible inconsistency. Sometimes both scroll bars are there and line up, sometimes the table stretches below the DOM should allow it. In our more complex usage, the header row even break out of the flex box and stretch on top of the sidebar element.

The handle on the right toggles a sidebar which affects the table size. This has also introduced inconsistencies in how HOT renders.

Any help with getting a handsontable instance sitting nicely into a section of the DOM, have its own scrolling, and filling the space in which it occupies would be greatly helpful.

**Comment by toresenneseth** [comment] 2015-09-10 10:32
Hi,

We have the same issue, and we got it working by putting an absolutely positioned div inside the flex-item, and then putting the hot element inside the absolutely positioned div. Then we have to measure the size of the absolutely positioned div when the browser size changes and manually set the size of the hot element (elem.style.width + height) AND set the width and height properties of the hot settings ( hot.updateSettings({width:www, height:hhh}) )

This is a snippet of the HTML (with some comments I've added here)

```
<div style="overflow:hidden">
    <div class="flex-container-vertical-stretched size-align">        
	... We have a heading here...removed
	
        <div class="flex-item-vertical-content>
		
            We measure the size of this one when the window resizes. We apply the size to the "hotContainer" (child) by setting its style.width and style.height
            <div style="position:absolute; top:0; left:0; bottom:0; right:0">

                This is the HOT container. We set its style.width and style.height by measuring the actual size of the parent when the window resizes.
                <div id="hotContainer" style="position:relative; overflow:hidden"></div> 
            </div>
        </div>
    </div>
</div>
```
The css looks like this;
```
.size-align {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}

#.flex-container-vertical-stretched {
    display: flex;    
    flex-direction: column;
    height: 100%;
    width: 100%;
}

.flex-item-vertical-content {    
    flex: 1 1 auto; /*flex-grow flex-shrink flex-basis*/
    padding: 0;
    margin-bottom: 2px;
}
```

The resize code is pretty much a hack, but it works OK for us. I've listed the important parts below (it's TypeScript, in case you're wondering about the syntax and type annotations). FYI, jquery and underscore is used. In case you're wondering about why I'm setting the size twice in the setSize() function, it's because of a bug (I think) in the scrolling feature of Handsontable when fixedColumnsLeft is enabled that occurs when the window size is shrinked (increased works fine). The workaround that seems to work is to set the width twice, the first time one pixel smaller than the desired width, and then apply the actual size, making handsontable think the size was increased...which makes the scrolling work.

```
class HotResizerService{
	private _elem:HTMLElement; // the hotContainer (div id="hotContainer" from the HTML snippet above)
	private hotInstance : ht.Handsontable; // a reference to the Handsontable instance
	private _prevWidth: number;

	public init(elem : HTMLElement, hotInstance : ht.Handsontable) : void{
		this._elem = elem;
		this.hotInstance = hotInstance;
		...some code
		$(window).on('resize', _.debounce(this.scheduleUpdateSize.bind(this), 100));
	}
	
	private scheduleUpdateSize(timeout: number = 300): void {
            setTimeout(() => {
                var width = this.calcGridWidth();
                if (width < 1) {
                    this.scheduleUpdateSize();
                } else {
                    this.setSize();
                }
            }, timeout);
        }

	private setSize(): void {
            var height = this.calcGridHeight(),
                width = this.calcGridWidth();

            if (!this._prevWidth || this._prevWidth > width) {
                // first time or window was shrinked...hack...
                // need to set the size twice because scrolling gets messed up when fixedColumnsLeft is enabled after a window size decrease (increase works fine)
                this.__setSize(width - 1, height);
                this.__setSize(width, height);
            } else {
                this.__setSize(width, height);
            }

            if (this.hotInstance) {
                setTimeout(() => this.hotInstance.render(), 0);
            }
        }

        private __setSize(availableWidth: number, availableHeight: number): void {
            this._elem.style.width = availableWidth + "px";
            this._elem.style.height = availableHeight + "px";
            var opts: ht.Options = {
                width: availableWidth,
                height: availableHeight
            };
	
            this._prevWidth = availableWidth;

            if (this.hotInstance) {
                this.hotInstance.updateSettings(opts);
            }
        }

	private calcGridWidth(): number {
	    // elem.parentElement is the absolutely positioned div (parent of the hotContainer)
            return Handsontable.Dom.innerWidth(this._elem.parentElement);            
        }

        private calcGridHeight(): number {
	    // elem.parentElement is the absolutely positioned div (parent of the hotContainer)	
            return Handsontable.Dom.innerHeight(this._elem.parentElement);            
        }

}
```

Note that this is just something we've come up with...I don't know if it's totally wrong or if there is a better way of doing it, and I don't know if it will work for you, but it might give you some ideas to get you started.

**Comment by mscreenie** [comment] 2016-04-14 13:24
This should be open as it still exist in latest (0.24.2).

**Comment by AMBudnik** [comment] 2016-04-14 14:18
Hi @mscreenie 
Could you create a simple demo where this issue can be replicable?

**Comment by AMBudnik** [comment] 2016-05-06 08:41
Issue will be reopened with a demo/reply

**Comment by marc-antoinepelletier** [comment] 2016-06-07 14:50
I am using handsontable with angular material and I can confirm that it's completely broken with flexbox.. Specially when settings max-width, width as a parent container.

**Comment by AMBudnik** [comment] 2016-06-07 15:10
Hi @marc-antoinepelletier Can you create a demo where we'll be able to test it?
There was a demo in the first post but it's broken.

**Comment by ekevoo** [comment] 2016-09-30 14:12
@AMBudnik Here's one: jsfiddle.net/ekevoo/93n95uhg/

**Comment by AMBudnik** [comment] 2016-10-06 12:35
thank you @ekevoo 
I've tested this example and we can load all rows by adding viewport offset (updated: http://jsfiddle.net/8pqxpw1b/) but still headers won't move

**Comment by samsfisher** [comment] 2017-09-24 21:18
@marc-antoinepelletier did you figure out a solution for using handsontable within material flexbox. I am stuck!

**Comment by kwent** [comment] 2018-03-10 08:16
This is still an issue for as well. Anyone figured out a solution ?

**Comment by AMBudnik** [comment] 2018-05-10 09:54
Hi @hugepanda 

Sorry, we do not have any fix or workaround yet

**Comment by marcelodive** [comment] 2019-01-08 19:12
Any news?

**Comment by AMBudnik** [comment] 2022-08-03 10:31
@c-dante @marcelodive @toresenneseth @mscreenie @ekevoo @samsfisher @kwent @hugepanda 

Could you please tell me if the issue is still replicable? I was testing this example https://jsfiddle.net/2rmg1zf5/8/ and it seems correct. but I guess you might have different container settings, so before closing, I wanted to double-check it with you.

**Comment by c-dante** [comment] 2022-08-17 02:45
Hey-o -- it's been ~7 years so feel free to close it from my end :B

**Comment by toresenneseth** [comment] 2022-08-18 06:14
Haven't seen any scrolling issues for years, so not an issue for us any more.

**Comment by AMBudnik** [comment] 2022-08-18 06:18
That sounds promising. Thank you @toresenneseth

**Comment by ekevoo** [comment] 2022-11-29 20:00
Unfortunately I'm no longer involved in that project and I tried to contact the people who still are and they didn't write back to me.

**Comment by AMBudnik** [comment] 2023-12-11 09:54
Closing as solved with https://github.com/handsontable/handsontable/issues/2806#issuecomment-1203770370

**Closed by AMBudnik** 2023-12-11 09:54 UTC
Labels: bug, Scroll, Core: Alignment / height / width, Reported

**Comment by marcelodive** [comment] 2024-01-19 20:33
> @c-dante @marcelodive @toresenneseth @mscreenie @ekevoo @samsfisher @kwent @hugepanda
> 
> Could you please tell me if the issue is still replicable? I was testing this example https://jsfiddle.net/2rmg1zf5/8/ and it seems correct. but I guess you might have different container settings, so before closing, I wanted to double-check it with you.

Unfortunately, I no longer have access to the project code as it happened a long time ago.

**Comment by AMBudnik** [comment] 2024-02-02 11:11
Understood, @marcelodive 
Thank you for the update.
