### ISSUE TITLE
Numeric column no longer accepts formatted number input

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5031] opened 2018-04-13 15:42 UTC
### Description
Somewhere between upgrading from CE to Pro the behavior of numeric columns changed. Before, when you entered in a formatted number like `1,000` or `$50.00` it would accept it as the correct number value `1000` and `50`, now it is flagged as an error. This broke a bunch of existing behavior, our users are often copy/pasting formatted numbers.

### Steps to reproduce

1. Create a column with `{ type: "numeric", numericFormat: { pattern: "0,0.00" }}`
2. Type into a cell the value `1,000`
3. Result: cell is marked as invalid, rather than valid with `1,000.00`

### Demo

Previous version `0.33.0` allows formatted number input: https://jsfiddle.net/52txq109/1/
Latest version `2.0.0` doesn't allow formatted number input: https://jsfiddle.net/8ffpsqt6/7/

### Your environment
* Handsontable version: pro `1.18.1`
* Browser Name and version: Chrome 65
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment] 2018-04-16 07:27
Hi @aaronbeall 

I've tested the scenario on High Sierra and Win10 but did not get an `invalid` result. 

However is both systems  I get `1.00` as a result of demo in v`2.0.0` (which is different for the v`0.33.0` where I get `1,000.00`).

Can you please record the situation when cell becomes `invalid`?

ps. I'm marking this topic as a regression bug (bug produced in v `0.35.1`) for the format changes.

**Comment by aaronbeall** [comment] 2018-04-16 16:54
Yeah, I guess the changed behavior is to treat comma as a decimal. Currency symbol causes the invalid state:

With the `0.33.0`:
![img](http://g.recordit.co/MaQJoOH5Et.gif)
- `9,999` becomes `9,999.00` as desired
- `$100` becomes `100.00` as desired

With the `2.0.0`:
![img](http://g.recordit.co/xh80xzDuyO.gif)
- `9,999` becomes `2.00`
- `$100` becomes invalid cell

**Comment by aaronbeall** [comment] 2018-04-17 20:54
I tried to remove non-numeric characters (using regexp `[^-09.]`) in `beforeValidate` and `beforeChange` but it appears the conversion of comma to decimal places happens before that point. Any idea?

**Comment by AMBudnik** [comment] 2018-04-18 11:25
I'm not sure but maybe it's a part of the Numbro and if it is we would need to ask them to change that. We usually create a PR and wait for them to pull the changes.

**Comment by aaronbeall** [comment] 2018-04-18 14:13
Yes, seems the behavior changed, whether intentional or not isn't clear. I would consider it a bug that in `en-US` it would convert comma to decimal, since that is not what comma means in that locale, but maybe there's some reason.

I guess my question since this issue is within Handsontable is whether there's a way to work around it? Like I said I tried handling `beforeValidate` and `beforeChange` but in both cases the value has already been converted. Is there a hook at a lower level that I can use before the conversion would take place? Can it be worked around with a custom editor without losing all the other numeric editor functionality?

**Comment by aaronbeall** [comment] 2018-04-18 15:44
Handsontable 2.0 [depends on Numbro 1.11.0](https://github.com/handsontable/handsontable/blob/master/package.json#L61). But when I try Numbro 1.11.0 it doesn't exhibit the behavior in this issue:

    numbro("1,999").format("0,0.00")

> 1,999.00

**Comment by AMBudnik** [comment] 2018-04-19 07:43
Here https://docs.handsontable.com/pro/2.0.0/tutorial-using-callbacks.html there's a list of callbacks that you can test and check which one fires before.

**Comment by aaronbeall** [comment] 2018-04-19 13:12
This seems to be the problem: https://github.com/handsontable/handsontable/blob/7476f640754c49cd395d2c966a161540802c95b8/src/core.js#L867-L877

I've been digging to figure out where the the raw input text gets converted to a number and that seems to be it, though I haven't debugged it. But the comment describes my problem exactly. I do **not** want it to convert comma to decimal place. In my view this isn't the right behavior, unless you are in a locale that acts that way. It seems this code should take locale into consideration.

**Comment by aaronbeall** [comment] 2018-04-19 20:03
> Here https://docs.handsontable.com/pro/2.0.0/tutorial-using-callbacks.html there's a list of callbacks that you can test and check which one fires before.

Thanks, that helps. The problem doesn't exist in that demo because they are all text columns, and the problematic `getParsedNumber` only gets called for numeric columns:

https://github.com/handsontable/handsontable/blob/7476f640754c49cd395d2c966a161540802c95b8/src/core.js#L893-L895

But that demo pointed me in the right direction. I made [this demo](http://jsfiddle.net/wpoybhsc/10/) and found that `afterSetDataAtCell` will run right before this parsing happens in `validateChanges` (and before `beforeChange` and `beforeValidate`), so I can just remove the comma and currency symbols there and get the old behavior back:

```js
afterSetDataAtCell(changes, source) {
  changes && changes.forEach(change => change[3] = change[3].replace(/[^0-9.]/g, ""));
}
```

I still think that `getParsedNumber` should take locale into consideration, as well as formatting (ex `$100` should be valid input)

**Comment by AMBudnik** [comment] 2018-04-20 06:14
I'll ask our CTO to discuss this subject. In one hand someone put there the comment to accept that we want it to work this way but on another, it breaks some logic that we present via languages.

**Comment by jgbishop** [comment] 2018-09-13 00:47
Any ETA on this bug? This causes lots of issues with currency values, which seems pretty substantial.

**Comment by AMBudnik** [comment] 2018-10-17 12:45
I just had a meeting with our CTO and I need to share a very important update on this topic.

We have tracked down the issue to the roots and apparently it is not a bug at all. The functionality that we discuss here is actually a side effect of creating the `numeric` cell type itself. The format feature needed an adjustment to fix this issue https://github.com/handsontable/handsontable/issues/4706. However that action caused our positive side effect do disappear. 

The only I can do now is to mark this topic as a pull request.

**Comment by AMBudnik** [comment] 2018-12-07 14:52
As mentioned in the https://github.com/handsontable/handsontable/issues/5424 I am temporarily closing this issue

**Closed by AMBudnik** 2018-12-07 14:52 UTC
Labels: Cell type: numeric, Type: Feature
