### ISSUE TITLE
FillHandle on last column, overflows table

### ISSUE THREAD

**Issue by pedrofsantoscom** [handsontable/handsontable#2373] opened 2015-04-15 17:54 UTC
1. Select any cell (besides last column)
2. Select a cell on the last column (column "F")
3. Watch table overflowing on the X axis

http://jsfiddle.net/hU6Kz/3358/

**Comment by AMBudnik** [comment] 2015-04-16 07:14
Which OS/Broweser are you using? I tried it on Chrome 41, Safari 8 and FF 37 and everything seems to work fine.

**Comment by ledjdm** [comment] 2015-04-16 09:54
Windows 7 Pro 64bit
Chrome 41.0.2272.118 m
Firefox 36.0.4

I wasn't able to set the jsfiddle panes the way i wanted to repoduce the error to the others (it seems their position is only saved on my pc and not on the fiddle itself). 

(1., 2.) As i can see, the table overflows only when you have a vertical scrollbar, as when theres no vertical scrollbar it works ok.
(3.) Made a quick debug on the css of the fill handle ".wtBorder.current.corner" and if i adjust the "left" propriety, i can get the handle positioned to not overflow the table.

1. Without the bug: http://codepen.io/anon/pen/qEevVG
2. With the bug: http://codepen.io/anon/pen/RNXdZP
3. Quick fix: http://codepen.io/anon/pen/gbVEew

**Comment by AMBudnik** [comment] 2015-04-16 13:02
I see what you mean. It does not occur on on a mac but I can see that my virtual Win7 face this issue. I tried your 3 point (with a fix), but it acts like point 2 as well.

**Comment by yuwong** [comment] 2015-04-24 08:34
Thanks @ledjdm I've used the above fix for the overflowing of rows rather than columns. When any cell of the last row is selected in a scrollable table, the fill handle introduces extra pixels to cause mis-alignment, very clearly if you also have fixed columns.

To see what I mean, go to http://handsontable.com/demo/column_resize.html selecting any cell on row 1001(last row), then try to scroll down with mouse wheel or touch pad, and the row headers will be misaligned with the row. @AMBudnik this issue is observed in all browsers I have access to, and I'm using a Mac.

I've also replicated the fix to cover for .wtBorder.area.corner as well, for the fill handle after selection of multiple cells.

**Comment by AMBudnik** [comment] 2015-05-21 07:52
Please check the newest hot version. I tried to reproduce the issue but it does not occur.

**Comment by ledjdm** [comment] 2015-05-21 09:41
Tried on http://codepen.io/anon/pen/RNXdZP and it's still happening. The pen is using the http://handsontable.com/dist/handsontable.full.js version, so i guess its the newest?

Recorded a video of what i get on chrome:
https://www.dropbox.com/s/8vb1p4bgnc8i8de/hot_fillhandle.mp4?dl=0

**Comment by AMBudnik** [comment] 2015-05-21 10:20
Yes, http://handsontable.com/dist/handsontable.full.js it's the latest version. Tried it few times and it occurs. Do you get this behavior every time?

**Comment by ledjdm** [comment] 2015-05-21 10:39
Only with __stretchH: "all"__, so that the columns fill all the width of the hot container and the fillhandle overflows it.

**Comment by yuwong** [comment] 2015-05-21 15:21
Assuming the website uses the latest version, go to http://handsontable.com/demo/column_resize.html selecting any cell on row 200(last row in the updated page), then try to scroll down with mouse wheel or touch pad, and the row headers will be misaligned with the row. @AMBudnik this issue is observed in all browsers I have access to, and I'm using a Mac.

Not really urgent as I am using @ledjdm's fix on the other axis.

**Comment by AMBudnik** [comment] 2016-03-21 15:15
Hi @yuwong I checked it with https://docs.handsontable.com/0.24.1/demo-resizing.html demo and 0.24.1 version and couldn't reproduce. Can you check it also?

**Comment by pedrofsantoscom** [comment] 2016-03-22 09:25
I'm currently using 0.23.0 on a project and can't reproduce the issue.

**Comment by AMBudnik** [comment] 2016-03-22 09:40
Thank you @pedrofsantoscom for feedback. I assume I can close this issue.

**Closed by AMBudnik** 2016-03-22 09:40 UTC
Labels: Answered
