### ISSUE TITLE
[7.1.1+] Can not clear column when first cell is readOnly

### ISSUE THREAD

**Issue by mbrainiac** [handsontable/handsontable#6246] opened 2019-09-05 05:21 UTC
### Description

Error throw when clear column with readOnly cell in the first row

```
Uncaught TypeError: Cannot read property 'removeEventListener' of undefined
    at unObserve (autoResize.js:24)
    at Object.unObserve (autoResize.js:165)
    at TextEditor.close (textEditor.js:180)
    at TextEditor.discardEditor (_baseEditor.js:411)
    at TextEditor.cancelChanges (_baseEditor.js:388)
    at Object.waitingForValidator.onQueueEmpty (core.js:1037)
    at Object.checkIfQueueIsEmpty (core.js:984)
    at validateChanges (core.js:1090)
    at Core.setDataAtCell (core.js:1288)
    at Core.emptySelectedCells (core.js:1589)
```

### Steps to reproduce

1. Create table with some data
2. Make cell on row 0, column 0 readOnly
3. Click on Header to select first column (do not click on any cell)
4. Press Delete

### Demo

https://jsfiddle.net/n10vx5cy/1/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome latest
* Operating System: MacOS 10.14.6

**Comment by AMBudnik** [comment] 2019-09-05 11:41
Thank you for sharing the issue @mbrainiac 

It's a regression bug (introduced in v `7.1.1`). `7.1.0.` works well https://jsfiddle.net/uepwc7sh/ (keeps only the `0, 0` cell.

**Comment by aninde** [comment] 2019-10-09 12:38
@mbrainiac this bug will be fixed in `7.1.2` version.  In `7.1.2` v. there is no error in console and deleting data by clicking <kbd>Delete</kbd> works. 

The new version will be released next week.

Result of original reproduction in `7.1.2`
![Screenshot 2019-10-09 at 14 33 55](https://user-images.githubusercontent.com/30186818/66482052-66b12e00-eaa2-11e9-8d12-a07f4d42242f.png)
**Demo:**
v. `7.1.2` https://jsfiddle.net/aninde/wys3d04p/

**Comment by AMBudnik** [comment] 2019-10-15 10:07
I'm glad to announce that the regression got fixed in `7.2.0`. The new version was published today.

@mbrainiac 
Please update.

**Closed by AMBudnik** 2019-10-15 10:07 UTC
Labels: Regression, Type: Bug

**Comment by ChandraAdapa10** [comment] 2021-03-31 04:15
HI AMBudnik,

we are facing similar kind of issue in 8.3.0 version while merging the two rows for select column,.

Thanks,
Chandra

**Comment by ChandraAdapa10** [comment] 2021-03-31 17:47
HI AMBudnik,

you can find the example here (https://codesandbox.io/s/tags-renderer-and-editor-forked-mju5w?file=/src/app/hello.component.ts )  , in the same code please add below properties in the settings , while trying to merge tags column you will see the issue ( _Cannot read property 'removeEventListener' of undefined_).
    **contextMenu:["mergeCells"],
    mergeCells:true,**
![image](https://user-images.githubusercontent.com/64519906/113188003-24bc0f00-9277-11eb-9e7f-7a5e4eaf7ac3.png)



Thanks,
Chandra

**Comment by AMBudnik** [comment] 2021-04-01 09:21
Thank you for sharing the code @ChandraAdapa10 
The error that you get is related to your custom editor

```js
columns: [
      { data: "id", type: "numeric" },
      { data: "name", type: "text" },
      {
        data: "tags",
        renderer: tagsRenderer,
        //editor: TagsEditor,
        //source: tags,
        strict: true
      }
```

When I comment it out then the issue is not replicable. The error is not related to the issue https://github.com/handsontable/handsontable/issues/6246

**Comment by Prasant38** [comment] 2022-11-24 11:43
Hi AMBudnik, I am also getting this issue .Is there anyway we can get this resolved without commenting the custom editor?
![image](https://user-images.githubusercontent.com/9193645/203776175-6b89a1c9-2e6b-48e9-b93a-6204d79a9fa4.png)

**Comment by AMBudnik** [comment] 2022-11-28 09:27
Hi @Prasant38 as @adrianszymanski89 mentioned at https://github.com/handsontable/handsontable/issues/10124 - it's related to the implementation. Here https://jsfiddle.net/osz04j3e/ we have a demo with a custom editor and renderer, and we are able to clear the column without any issues (tested with v12.2.0).
