### ISSUE TITLE
formula contain each other, then remove one row ,cause  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by iaminvictus1993** [handsontable/handsontable#5796] opened 2019-02-16 10:12 UTC
### Steps to reproduce

1. check C4  and C12, their formula contain each other
2. remove row 7
3. try to input data in two any cells
4. check the console

![bugformula](https://user-images.githubusercontent.com/22359049/52924801-3b3dcf80-3369-11e9-9ae2-7763a94d303a.gif)

### Demo

https://jsfiddle.net/vzku1cbL/6/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment] 2019-02-18 08:43
There's an issue in the console

>Uncaught RangeError: Maximum call stack size exceeded 

that tells us that we've entered an infinite loop. You need to check the formulas. It looks like one formula calls another one and the lopp never ends.

**Comment by iaminvictus1993** [comment] 2019-02-18 08:49
> There's an issue in the console
> 
> > Uncaught RangeError: Maximum call stack size exceeded
> 
> that tells us that we've entered an infinite loop. You need to check the formulas. It looks like one formula calls another one and the lopp never ends.

@AMBudnik  if don't remove row, I can input data correctly,that means my init formulas are right?I think its remove_row cause a loop formula,but I check the formulas are right

**Comment by AMBudnik** [comment] 2019-02-18 08:57
Removing the row, trigger recalculation of the formulas.

**Comment by iaminvictus1993** [comment] 2019-02-18 08:59
> Removing the row, trigger recalculation of the formulas.

after remove row the formulas are right,but it run not as my expect

**Comment by AMBudnik** [comment] 2019-02-18 09:04
The issue is here

> ["c", "0.00", "=SUM(C5:C11)", "=SUM(D5:D11)", "=SUM(E5:E11)"],

you can track down what formulas of those 3 above send another calls and start the loop

**Comment by iaminvictus1993** [comment] 2019-02-18 09:13
c12 formula contain  c4 formula ,  cant support this?

**Comment by AMBudnik** [comment] 2019-02-18 09:30
I have found a reference error https://github.com/handsontable/handsontable/issues/4357

**Comment by iaminvictus1993** [comment] 2019-02-18 09:35
😂so is there any way to solve this now?  only way to disable formula?

**Comment by AMBudnik** [comment] 2019-02-18 09:43
Only the circular formulas cause issues, not all the formulas, But yes, until this issue gets fixed you will get the error in the console.
Please notice that the formula plugin is still in alpha stage of development. 

![zrzut ekranu 2019-02-18 o 10 42 24](https://user-images.githubusercontent.com/10757813/52941824-fcf4e000-3369-11e9-9ea2-27b1ede0d1f5.png)

**Comment by AMBudnik** [comment] 2019-02-18 09:44
As this topic covers the same issue as #4357 I will close it. But if we're missing anything crucial in #4357 please leave a comment .

**Closed by AMBudnik** 2019-02-18 09:44 UTC
Labels: Status: Answered

**Comment by iaminvictus1993** [comment] 2019-02-18 14:30
@AMBudnik  but I found not only  circular formulas cause this issue, but also the same formula.
eg: https://jsfiddle.net/1vzdoeua/

**Comment by AMBudnik** [comment] 2019-02-19 09:26
It is a circular formula if you add "=SUM(C5:C11)", in a C4 cell (it counts itself).

**Comment by sundar1994** [comment] 2019-11-26 13:26
I have encountered the same problems in handsontable 7.1.1 version,
And I can't solve it。
Is there a solution to this problem now？
Thank You

**Comment by AMBudnik** [comment] 2019-12-03 08:25
Hey @sundar1994 this issue was closed as this is a duplicate for this one https://github.com/handsontable/handsontable/issues/4357 that is still unsolved
