### ISSUE TITLE
Scrolling with mac trackpad over fixed columns

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#4532] opened 2017-09-21 11:58 UTC
### Description
I'm using the track pad of a Macbook Pro (I guess it's the same for any Apple trackpad). When I'm holding my mouse cursor over a fixed column (fixedColumnsLeft) and sroll, the rendering of the table is messed up in Firefox and extremely janky/buggy in Chrome and Safari (I've noticed that fast scrolling shows the problem more in text-columns and slow in picture columns).

Edit: Seems to be same with any mouse, just easier to get the effect with Apple track pad =)

### Steps to reproduce

1. Set fixedColumnsLeft to 1 or more.
2. Use an Apple trackpad (with accelerated scrolling?)
3. Hold mouse cursor over a cell in the locked column.
4. Scroll really fast! or slow to see how the rendering of the table is affected. Looks like the rows are not loaded, or the scrolling should be really janky / almost not work at all.

### Demo

https://jsfiddle.net/guhjw23f/

Chrome:
![hot-scroll-chrome](https://user-images.githubusercontent.com/3355320/30694471-6dd5e2fa-9ed4-11e7-8213-5cc0d2a50564.gif)

Firefox:
![hot-scroll-firefox](https://user-images.githubusercontent.com/3355320/30694571-df957284-9ed4-11e7-835e-d459e77c8265.gif)

### Your environment
* Handsontable version: 0.34.4
* Browser Name and version: Firefox 57, Chrome 60, Safari 11
* Operating System: MacOS Sierra

**Comment by AMBudnik** [comment] 2017-09-25 12:22
We have replicated it with el Captain as well. Thank you for sharing @ottosson

**Comment by swistach** [comment] 2018-03-07 13:41
It's present since 0.32.0.
Basic example:
![scroll-issue-ffox](https://user-images.githubusercontent.com/11849621/37095260-a3fb8dc0-2215-11e8-9c37-b97a950639b7.gif)

**Comment by swistach** [comment] 2018-04-10 14:51
This issue should be fixed in next release (2.0.0)

**Comment by AMBudnik** [comment] 2018-04-23 13:18
The issue is no longer replicable in v `2.0.0`.

Please update @ottosson and let me know if it also works for you.

**Closed by AMBudnik** 2018-04-23 13:18 UTC
Labels: Plugin: Fixing, Type: Bug
