### ISSUE TITLE
manualColumnMove only works for leftmost eight columns

### ISSUE THREAD

**Issue by emilschutte** [handsontable/handsontable#6604] opened 2020-01-09 06:31 UTC
### Description
When the table has more than eight columns and `manualColumnMove` is enabled, dragging the ninth column causes it to disappear and the column to the right of the target drop point to appear duplicated.  Dragging columns that are originally to the right of the ninth column does nothing (column is not moved).

### Steps to reproduce
1. Turn on `manualColumnMove`
2. Have more than eight columns (not counting row header)
3. Try to drag the ninth column, or one farther right.  The problem described above should happen.

### Demo
https://jsfiddle.net/54L8hmbu/

The above demo is the fiddle linked from https://handsontable.com/examples with the following changes:

1. `manualColumnMove: true` in config
2. The last column ("Change") is duplicated three more times in `columns` and `colHeaders`, so that there are enough columns to show the issue.  Here in our app where we're seeing the bug, the columns involved are all unique, so I don't think the fact that these are copy-pasted matters.

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Google Chrome 80.0.3987.16 (Official Build) beta (64-bit)
* Operating System: macOS Mojave 10.14.6

**Comment by AMBudnik** [comment] 2020-01-09 10:43
Hey @emilschutte 

this issue is fixed with 8.0.0-beta1. Update demo https://jsfiddle.net/t95k1cu2/
The issue is related to incorrect index translation and is fixed in the beta with the [index mapper](https://github.com/handsontable/handsontable/issues/5112).

This issue was also mentioned here https://github.com/handsontable/handsontable/issues/4470 and stays open so please track updates to https://github.com/handsontable/handsontable/issues/4470 for information about stable 8.0.0 version.

**Closed by AMBudnik** 2020-01-09 10:43 UTC

**Comment by emilschutte** [comment] 2020-01-09 17:51
Thanks!

**Comment by AMBudnik** [comment] 2020-08-07 08:31
Hi @emilschutte 

we've just released the stable version with a fix for this issue - v 8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases

**Comment by emilschutte** [comment] 2020-08-07 16:04
@AMBudnik Wonderful! Thank you.
