### ISSUE TITLE
[7.1.0+] Characters & < > ' " being converted to &amp; &lt; &gt; &#39; &quo; 

### ISSUE THREAD

**Issue by davekos** [handsontable/handsontable#1535] opened 2014-06-17 22:43 UTC
I am using Handsontable 0.10.5 version.

When I type in a Handsontable cell a text string which contains ( & < > ' " ) and save the data, the next time I edit the cell they are converted into ( &amp; &lt; &gt; &#39; &quo;) respectively.  I noticed this issue was addressed previously in 0.6.0 Beta version (Sep 2012) but now I am seeing it in this version.  

Is the Data being filtered before being displayed to the screen or do I need to set a parameter when I create my instance of Handsontable?

**Comment by AMBudnik** [comment] 2015-03-31 10:46
This issue should not occur any more. Please update your HOT to [0.13.1](https://github.com/handsontable/handsontable/releases/tag/0.13.1) and try it out. In case of any sumilar issues give us a feedback.

**Comment by fengjac** [comment] 2019-10-08 04:18
@AMBudnik Any update? Thanks

**Comment by AMBudnik** [comment] 2019-10-08 09:07
Hey @fengjac since September we are working on a new major version 8.0.0-rc1 so all the tasks were held. Also, it seems like the latest build doesn't change anything in this matter https://jsfiddle.net/handsoncode/tuwzL6pd/.
We are preparing a new index mapper described here https://github.com/handsontable/handsontable/issues/5751

**Comment by h0jeZvgoxFepBQ2C** [comment] 2019-10-16 09:03
Do you think this will be fixed soon? 

This is a total blocker for us, since our customers can't use it safely to import data from excel.
Right now we stopped the implementation of handontable in our product due to this bug.

**Comment by wojciechczerniak** [comment] 2019-10-16 09:29
It's an HTML sanitizer. Safety first. We will work on adding whitelist/blacklist capability.

But this shouldn't be a blocker @h0jeZvgoxFepBQ2C. You can decode HTML in beforePaste hook: https://jsfiddle.net/v0yn73dm/

**Comment by h0jeZvgoxFepBQ2C** [comment] 2019-10-16 09:31
Ah ok great, thanks for this @wojciechczerniak ! ❤️

**Comment by AMBudnik** [comment] 2019-10-30 09:36
It also works well when you use the predefined `html` renderer https://jsfiddle.net/4x9fr0ps/1/

**Comment by dandcrooks** [comment] 2019-11-11 21:57
Any update on what release a fix will be included in?

**Comment by AMBudnik** [comment] 2019-11-12 07:13
Hey @davekos 

`7.3.0` is planned for 18/11

**Comment by aninde** [comment] 2019-11-15 10:14
@davekos @dandcrooks @h0jeZvgoxFepBQ2C @fengjac this bug will be fixed in `7.3.0` v. We plan to release it in next week.

It will be possible to paste different characters

Demo
`7.3.0` https://jsfiddle.net/aninde/oj5n3fr9/
![Screenshot 2019-11-15 at 11 06 55](https://user-images.githubusercontent.com/30186818/68935549-0c8a4380-0799-11ea-8c78-a7731e9e0a08.png)

**Comment by AMBudnik** [comment] 2019-11-18 13:43
Works on Windows for Chrome 78 and FF 70

**Comment by vincent-cm** [comment] 2019-11-18 17:13
> Hey @dandcrooks
> 
> The release of `7.3.0` is planned for 18/11
@AMBudnik 
Is it ready?

**Comment by dandcrooks** [comment] 2019-11-18 17:21
@vincent-cm Thank you for letting me know. I'll grab it as soon as I can and test it out.

Any idea if this has been tested in older browser versions?

**Comment by AMBudnik** [comment] 2019-11-19 07:59
We wanted to release it on 18th of Nov. but we found out that it does not work when you use iframes in some cases mentioned here https://github.com/handsontable/handsontable/issues/6478 so we're doing a quick fix. We didn't want to push a version that will block all our demos on Edge.
Till Thursday (planned release with the Edge fix) is now Thursday. I hope that we won't find any showstoppers and will be able to update you on time :)

**Comment by aninde** [comment] 2019-11-25 15:22
Still fixed on latest `7.3.0` https://jsfiddle.net/d9bLtx75/1/

**Comment by dandcrooks** [comment] 2019-11-25 15:23
@AMBudnik Any update of when the release is planned? Thanks for keeping me in the loop.

**Comment by AMBudnik** [comment] 2019-12-02 09:18
Sorry for keeping you waiting @dandcrooks we test this new feature from `7.3.0` very extensively and find [one regression](https://github.com/handsontable/handsontable/issues/6505) after [another](https://github.com/handsontable/handsontable/issues/6497). As our internal policy does not allow us to push a version with a regression we need to fix them before the release.

**Comment by dandcrooks** [comment] 2019-12-03 15:08
@AMBudnik I appreciate the attention to fixing those before release. Thanks again for the update.

**Comment by aninde** [comment] 2019-12-09 20:42
Still works well during testing `7.3.0  v.` (6.12) on Chrome 78, Firefox 70, Safari 13, Microsoft Dev Edge / Mac OS Catalina and IE, Edge, Edge Dev / Windows 11
https://jsfiddle.net/3z5fct4g/

**Comment by AMBudnik** [comment] 2019-12-13 07:28
I'm really glad to see this issue solved! It is a pleasure to close this as solved :)

**Closed by AMBudnik** 2019-12-13 07:28 UTC
Labels: Copy-paste, Regression, Type: Bug
