### ISSUE TITLE
[7.4.0/8.0.0] editor doesn't work on iPhone 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7142] opened 2020-07-21 08:51 UTC
### Description
The editor doesn't work on any browser on iPhone OS 13.5.1.

Interestingly, the editor works on examples from documentation and demos, but not when I check it locally (Visual Studio + GhostLab). It's broken in that case.

The editor always works, even tested locally by GhostLab on a real device with version 7.3.0 and earlier.
It works on Safari and Firefox on iPad 13.3.1 Model: MR7F2FD/A and on Android-based smartphones.

![video-1595319613](https://user-images.githubusercontent.com/30186818/88033517-c4010200-cb3f-11ea-931d-b76d3783f18e.gif)

### Your environment
* Handsontable version: 7.4.0, 8.0.0-beta.1, 8.0.0-beta.2, 8.0.0
* Browser Name and version: any (Safari, Chrome, all browsers on iPhone render over Safari)
* Operating System: iOS 13.5.1.

**Comment by nikersify** [comment] 2021-01-15 11:09
This problem is caused by the double tap to zoom gesture on iOS devices - the second tap event isn't being emitted as it's interpreted as the gesture, breaking the editor.

Setting [`touch-action: manipulation`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) on the whole `table` element disables the gesture and fixes the problem on iOS 13 where the editor wouldn't open at all.

The editor only opens on a double tap, though, which makes sense on devices with a mouse pointer, but doesn't quite make sense on mobile where you preferably would have it open after a single tap.

The solution would be either to use `touch-action` (dead simple), or also change the above behavior so that the editor would open with `touch*` events (more prone to bugs, though).

wdyt? @wojciechczerniak

**Comment by nikersify** [comment] 2021-01-15 11:22
Related https://github.com/handsontable/handsontable/issues/6961

**Comment by wojciechczerniak** [comment] 2021-01-15 15:41
@nikersify `touch-action: manipulation` sounds like the current intended behavior. Changing when the editor opens would be a breaking change and should be discussed with the UI/UX first. I would focus on fixing the bug only.

**Comment by nikersify** [comment] 2021-01-21 09:05
Closed in #7470

**Comment by AMBudnik** [comment] 2021-03-16 13:45
I'm closing this issue as solved and released for Handsontable v8.3.2

**Closed by AMBudnik** 2021-03-16 13:45 UTC
Labels: Editor, Mobile, Regression, Status: Released, Type: Bug
