### ISSUE TITLE
columnsRenderCalculator Error

### ISSUE THREAD

**Issue by micheleriva** [handsontable/handsontable#5825] opened 2019-02-27 16:56 UTC
### Description
When I create the table, I run in a series of `columnsRenderCalculator` errors.

Here it is my configuration in Vue.js, it's a computed property.
`this.getTableColumns` and `this.getTableRows` are two Vuex getters:

```js
    tableSettings() {
      return {
        colHeaders: this.getTableColumns,
        data: this.getTableRows,
        width: 960,
        height: 540,
        fixedColumnsLeft: 3,
        rowHeaders: true,

        cells: (row, col) => {
          const cellProperties = {};
          const disabledColumns = [0, 1, 2];

          if (disabledColumns.indexOf(col) > -1) {
            // Is the last readOnly column? Used for adding right shadow class
            const isLast = disabledColumns.indexOf(col) === disabledColumns.length - 1;
            // Enable readOnly feature for this specific column
            cellProperties.readOnly = true;
            // Add custom class for this specific column
            cellProperties.renderer = (_, td, row, col, prop, value) => {
              td.innerHTML = value;
              td.className = `table-cell-disabled ${isLast && "table-cell-shadow"}`;
            };
          }

          return cellProperties;
        },

        afterChange: (changes, source) => {
          console.log(changes);
          console.log(source);
        }
      };
    }
```

The errors I get:

<img width="455" alt="schermata 2019-02-27 alle 17 53 57" src="https://user-images.githubusercontent.com/14977595/53507823-e0b71880-3ab8-11e9-8793-b592e4b5d667.png">

### Your environment
* Handsontable version: 0.10.5
* Browser Name and version: Chrome
* Operating System: OSX

**Comment by wojciechczerniak** [comment] 2019-02-28 10:10
Duplicate of https://github.com/handsontable/vue-handsontable-official/issues/108

**Closed by wojciechczerniak** 2019-02-28 10:10 UTC
