### ISSUE TITLE
Col / Row selection selects multiple if merged cells are within selection

### ISSUE THREAD

**Issue by rbarato** [handsontable/handsontable#4022] opened 2017-01-25 18:06 UTC
### Description
When working with merged cells, I click to select a col or row and all rows/cols within that merged cell get selected at once.

### Steps to reproduce
1. Access provided jsfiddle (not my fiddle)
2. Click to select col B
3. Cols B to P get selected

### Demo
taken from Docs page: http://jsfiddle.net/cm9fspv6/

### Your environment
* Handsontable version: 1.9.1
* Browser Name and version: Chrome 55
* Operating System: MacOS 10.12

**Comment by AMBudnik** [comment] 2017-01-31 14:07
Hi @rbarato 
we have tested the Fiddle in Chrome 55 on MacOS and Windows and we're getting expected result.

![example2](https://cloud.githubusercontent.com/assets/10757813/22467896/b6e8f4b6-e7c6-11e6-9dbe-07b39978c743.gif)

Hm... I really do not know what we are doing differently. One of our colleagues has the same OS/Browser settings and got the same result.

**Comment by AMBudnik** [comment] 2017-01-31 14:31
I was testing your demo and found a bug.

When we select row 2 we should get a selection for rows: 2, 3 and 4 but the 5th row is also selected.

![image](https://cloud.githubusercontent.com/assets/10757813/22468867/3f9c7294-e7ca-11e6-90c5-d3ec81c1935c.png)

**Comment by madoar** [comment] 2017-01-31 15:16
@AMBudnik In my opinion this is the correct result.
As far as I understand merged cells, all rows/columns need to be selected that contain a part of a merged cell. If multiple merged cells share a row/column this means that all rows/columns, containing at least one of the merged cells that "overlap", need to be selected.

If you use this understanding it leads to the conclusion that row 5 must be selected, because if row 5 wouldn't get selected, merged cell E4 would only be "half" selected.

**Comment by AMBudnik** [comment] 2017-02-03 14:37
Hm... I guess you're right @madoar there's also the `E4`.

Thanks for sharing that with me - you're right. It would be better to keep in as it works now.

However still I am not able to get the same selection as @rbarato maybe you can reproduce it @madoar? I am trying various complications of features and browsers.

**Comment by madoar** [comment] 2017-02-03 23:22
@AMBudnik I believe that he suggests an alternative approach, of how to handle the selection of rows and columns with merged cells.
I thinks he suggests, that if you select a row or a column, only the cells at least partially inside the selected row or column should be selected, independent of them being merged cells or not.

If you take the given jsfiddle as an example this would mean, that if you select column "B", all fields containing a letter with "B" (B1, B2, B3, B4, B5, ...) would be selected. If you alternatively select column "C", the fields C1, B2, C3, C4, C5 and so on are selected.

**Comment by AMBudnik** [comment] 2017-02-06 09:01
@rbarato Can you confirm that? I am really not sure what you mean by getting the columns from `B` to `P` selected when you click only the `B` column.

**Comment by rbarato** [comment] 2017-02-08 17:38
Hi @AMBudnik, yes that is exactly it. If I select col B, only cells on col B get selected, regardless if in the array exists a merged col. In the original post, I mentioned cols B to P, but it was a typo, the correct is B to D. Sorry about that.

**Comment by AMBudnik** [comment] 2017-02-13 09:52
If 

>  only cells on col B get selected, regardless if in the array exists a merged col

it sounds like a bug. However I would need some tips on how to replicate it. I have tested it on few devices and browsers and couldn't replicate it. Can you share any .gif of the results that you're getting?

**Comment by rbarato** [comment] 2017-07-20 14:48
@AMBudnik in the first gif you posted, you clicking to select B, and you're getting B to D selected because B2:D4 are merged. My goal is to get ONLY column B cells in this selection, the merged cell (range B2:D4) and none of the cells from column C & D.

**Comment by AMBudnik** [comment] 2017-07-21 12:02
Thank you for sharing additional details @rbarato 
We'd be doing a `mergeCells `refactor soon so I think that we should also investigate this case.

**Comment by jansiegel** [comment] 2018-03-01 13:31
Should work fine in `0.37.0`.

**Closed by jansiegel** 2018-03-01 13:31 UTC
Labels: Plugin: merge cells, Priority: normal, Type: Bug
