### ISSUE TITLE
scrollToCell Method

### ISSUE THREAD

**Issue by gillius** [handsontable/handsontable#2814] opened 2015-09-14 21:23 UTC
A scrollToCell method would be useful to show a cell on the screen without having to select it. I want to use this functionality with the search plugin so that the HOT scrolls to the first found cell. However, selectCell selects the cell and blurs the search box input and puts focus in the table. Therefore, I have to workaround by doing (e = document.activeElement) + selectCell + deselectCell + e.focus().

**Comment by AMBudnik** [comment] 2015-09-14 21:35
Thank you for that idea @gillius
We will definitely take it under consider. Currently search does not trigger scrolling.

**Comment by AMBudnik** [comment] 2016-03-02 15:14
I'm transferring this issue to ones that are approved in our [feature request list](https://github.com/handsontable/handsontable/wiki/Feature-requests)

Issue will stay closed till it is picked by a developer to work on. In the same time we encourage to send related pull requests and/or add additional suggestions.

**Closed by AMBudnik** 2016-03-02 15:14 UTC
Labels: Feature

**Comment by AMBudnik** [comment] 2017-02-28 12:24
Duplicate of https://github.com/handsontable/handsontable/issues/1986
