### ISSUE TITLE
sort plugin has a issue when remove rows from sorted table

### ISSUE THREAD

**Issue by zhangmq** [handsontable/handsontable#1499] opened 2014-05-26 12:53 UTC
I modified codes in afterRmoveRow function

this.afterRemoveRow = function(index, amount){
    var instance = this;

    if(!isSorted(instance)){
      return;
    }

//    var physicalRemovedIndex = plugin.translateRow.call(instance, index);

//    instance.sortIndex.splice(index, amount);

//    for(var i = 0; i < instance.sortIndex.length; i++){

//      if (instance.sortIndex[i][0] > physicalRemovedIndex){
//        instance.sortIndex[i][0] -= amount;
//      }
//    }

    instance.sortIndex.splice(index, amount);

    var indexMap = [];

    for(var i = 0; i < instance.sortIndex.length; i++){
        indexMap.push([i,instance.sortIndex[i][0]]);
    }

    indexMap.sort(function(a,b){ return a[1] - b[1] });

    for (var i = 0; i < indexMap.length; i ++){
        instance.sortIndex[indexMap[i][0]][0] = i;
    }

    saveSortingState.call(instance);

  };

**Comment by AMBudnik** [comment] 2016-03-03 15:05
Hi @zhangmq can you check this please with 0.23.0 I couldn't reproduce it.

**Comment by AMBudnik** [comment] 2016-03-22 10:03
I'm closing this issue as it wasn't updated for more than 2 weeks but if you would have any details that might come in handy please leave a comment.

**Closed by AMBudnik** 2016-03-22 10:03 UTC
Labels: Answered
