### ISSUE TITLE
Undo-redo should be improved to work better with merged cells

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4864] opened 2018-02-28 10:34 UTC
### Description

Undoing changes using CMD/CTRL+Z doesn't work for merged cells, but (most probably) only when:

- Merged cells have been created using an autofill option

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.16.0/demo-merged-cells.html
2. Merge some cells either by using an autofill
3. Press CMD/CTRL+Z

### Demo

https://docs.handsontable.com/pro/demo-merged-cells.html

### Your environment
* Handsontable version: Pro 1.17.0 / CE 0.37.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by AMBudnik** [comment] 2018-04-27 11:42
The issue is no longer replicable in v `2.0.0`. Undo works now for mergeCells. Please check the following example https://docs.handsontable.com/pro/2.0.0/demo-merged-cells.html

**Closed by AMBudnik** 2018-04-27 11:42 UTC
Labels: Plugin: undo-redo, Priority: normal, Type: Bug
