### ISSUE TITLE
Firefox and IE don't allow to scroll over page while focusing table

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4521] opened 2017-09-18 12:47 UTC
### Description

We cannot scroll a page while focusing Handsontable on Firefox and IE

### Steps to reproduce

1. Go to demo page
2. Place the cursor anywhere in the table
3. Scroll to the bottom of the table

Result: Chrome - page scrolls after we reach the end of the table, Firefox - page doesn't scroll at all.

### Demo

https://docs.handsontable.com/pro/1.14.2/demo-scrolling.html

### Your environment
* Handsontable version: 0.34.3
* Browser Name and version: Firefox (works on Chrome)
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2018-02-01 12:40
Replicated with version 0.35.1 of Handsontable

**Comment by swistach** [comment] 2018-07-10 16:14
The `wheel` event prevents scroll. Probably we have to implement a mechanism to switch of preventing if a user scrolled to the end of the table (vertically and horizontally).

**Comment by wojciechczerniak** [comment] 2019-03-01 12:44
Duplicate of #5212

**Closed by wojciechczerniak** 2019-03-01 12:44 UTC
Labels: Core: compatibility, Type: Bug
