### ISSUE TITLE
[8.0.0+] Keyboard "left" key does not scroll the viewport with there are fixed columns and window scroll is used

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#7451] opened 2020-12-28 12:40 UTC
### Description

Keyboard "left" key does not scroll the viewport with there are fixed columns and window scroll is used

### Steps to reproduce

1. Configure Handsontable to have more columns that can fit in the viewport, do not provide dimensions (use window scroll)
2. Select a cell far to the right
3. Press the "left" key on the keyboard several times
4. Notice that when the current cell selection goes under the left overlay, the window is not scrolled unless you press the "left" key several times

### Demo

7.4.2 https://jsfiddle.net/warpech/5w49vjpa/20/
8.2.0 https://jsfiddle.net/warpech/5w49vjpa/21/
7.4.2 - problem fixed by using a different scrollable container than the window: https://jsfiddle.net/warpech/5w49vjpa/24/

### Your environment
* Handsontable version: 7.4.2 (also exists in 3.0.0-8.20, does not exist in 2.0.0)
* Browser Name and version: Firefox 84 and others
* Operating System: macOS Catalina and others

Zen #25845

**Comment by Osky772** [comment] 2021-02-25 09:34
At first sight, this issue seems to be a duplicate of #5093 so I picked up these two issues to work on.

**Comment by Osky772** [comment] 2021-03-01 15:44
@warpech I noticed that the problem exists in `2.0.0` also, so it's not a regression: 
![keynavigation](https://user-images.githubusercontent.com/33433795/109521131-445fec00-7aad-11eb-9e88-e991a0bc76c4.gif)

**Comment by AMBudnik** [comment] 2021-05-13 12:28
Closed as a duplicate of https://github.com/handsontable/handsontable/issues/5093

**Closed by AMBudnik** 2021-05-13 12:28 UTC
Labels: Type: Duplicate
