### ISSUE TITLE
columnMove and rowMove will become invalid after context insert column or insert row

### ISSUE THREAD

**Issue by zhyage** [handsontable/handsontable#2015] opened 2014-12-31 08:08 UTC
columnMove and rowMove will become invalid after context insert column or insert row.
actually, after any action of context will cause columnMove and rowMove become incalid

**Comment by PassHours** [comment] 2015-01-02 08:34
https://github.com/handsontable/handsontable/issues/1990#issuecomment-68335450

**Comment by jansiegel** [comment] 2015-01-20 11:51
Closing as a duplicate of #2028

**Closed by jansiegel** 2015-01-20 11:51 UTC
