### ISSUE TITLE
CSS changes cause far right cell to get cutoff

### ISSUE THREAD

**Issue by stevebooks** [handsontable/handsontable#1167] opened 2013-11-13 23:59 UTC
This is a problem on 9.9.19 and 0.10.0-beta3 

Here is the JSFiddle: http://jsfiddle.net/X4vuL/

To duplicate, click on the first cell (top left) and then use your keyboard's arrows to scroll right. You will notice that the far right cell gets cutoff.

This problem doesn't happen when using the mouse to scroll by clicking on the scroll bars.

The only css changes are adding some padding and text-align: right

**Comment by AMBudnik** [comment] 2015-03-31 13:47
I couldn't reproduce it. Can you check if it still occurs after updating to [0.13.1](https://github.com/handsontable/handsontable/releases/tag/0.13.1). If so, please provide your OS/Browser information.

**Comment by AMBudnik** [comment] 2015-05-13 08:42
Issue closed in lack of author's reply for more than a month.

**Closed by AMBudnik** 2015-05-13 08:42 UTC
Labels: Answered
