### ISSUE TITLE
IE9+ scrolling causes the column headers to bounce around 

### ISSUE THREAD

**Issue by mburbea** [handsontable/handsontable#2144] opened 2015-02-09 21:20 UTC
When you scroll in IE9+ the row header will bounce around when scrolling occurs making it look awkward and hard to interact with the site.
![image](https://cloud.githubusercontent.com/assets/213233/6115981/8739a720-b077-11e4-8684-b4652fa2cc0b.png)

It will also cause the grid to flash white.

**Comment by Berus** [comment] 2015-02-09 22:41
@mburbea Which version ht are you using? Please prepare some jsfiddle demo

**Comment by mburbea** [comment] 2015-02-09 22:46
I am using the latest version. This can be done with IE11. On this demo page here:
http://handsontable.com/demo/column_freeze.html

Just perform a mouse wheel scroll down. I could do it with a fiddle if you need more data. I don't have a fixed columns but none of the demos seem to have a lot of data and scrolling any more.

**Comment by gstenson** [comment] 2015-02-10 11:15
Scrolling really is very poor in IE. Seems all versions. As @mburbea said no need for fiddle just use the examples with scrolling. You get jumpiness/white spaces etc. 

From the profilers it does seems to be around get widths and heights on redraw
![hotissue](https://cloud.githubusercontent.com/assets/289664/6126202/1b68a04e-b0ec-11e4-99f4-29dd84646397.png)

**Comment by gstenson** [comment] 2015-02-11 12:12
This behaviour was introduced in release 0.11.0. I am trying to isolate the exact change but I am wondering is it related to scrolling problem mentioned in the release notes  (#1614)?

**Comment by ConanMan** [comment] 2015-03-12 15:44
this is happening now (today) and it happens in Chrome and FF as well if it is included in a dialog (jquery ui dialog) as IE it is incredibly easy to show it happening http://hands.cbtservices.net/test.php

**Comment by jansiegel** [comment] 2015-03-27 12:44
The fix for header/overlay jumpiness on IE9+ is in the final phase of development and should be released soon! (probably with v.0.14)

**Comment by ConanMan** [comment] 2015-03-27 12:47
Yeah but it jumps in ALL browsers if you put the handsontable is a jquery ui dialog :-/ I think just to blame IE9 (which I have litterally almost never used) is a major major red herring..

It is not IE9 being lame, it is something overriding something improperly.. 

On 27 March 2015 12:44:51 GMT+00:00, Jan Siegel <notifications@github.com> wrote:
>The fix for header/overlay jumpiness on IE9+ is in the final phase of
>development and should be released soon! (probably with v.0.14)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/handsontable/handsontable/issues/2144#issuecomment-86929976

-- 
Sent from my Android device

**Comment by jansiegel** [comment] 2015-03-27 15:05
@ConanMan do you experience it in this example? http://codepen.io/js-ziggle/pen/dPrXGR

It had the issue of a 'floating' header, caused by jQuery UI dialog's padding, but once i set it to `0`, it looks good to me.

If you do experience it, could you prepare a simplified example of your problem on jsfiddle or codepen? That would really help us specify the problem.

**Comment by ConanMan** [comment] 2015-03-27 15:21
it is here

http://hands.cbtservices.net/

I made a demo of it

**Comment by AMBudnik** [comment] 2017-05-18 13:04
The issue has been fixed in v0.32.0-beta1.

Can you confirm that @mburbea ?

**Comment by AMBudnik** [comment] 2017-05-22 09:34
I assume that it is fixed, however, @mburbea if you still get the same behavior please let me know

**Closed by AMBudnik** 2017-05-22 09:34 UTC
Labels: Status: Answered
