### ISSUE TITLE
Not showing multiple continuous spaces

### ISSUE THREAD

**Issue by lewisjb** [handsontable/handsontable#4404] opened 2017-07-14 01:43 UTC
### Description
If you enter 'foo&nbsp;bar' into a cell, it shows correctly; however if you enter 'foo&nbsp;&nbsp;bar'  (notice the two spaces), it will only show 'foo bar' (single space). This is due to not using non-breaking spaces (`&nbsp;`).

### Steps to reproduce

1. Enter "foo&nbsp;&nbsp;&nbsp;bar" into a cell
2. See that it only shows "foo bar"

**Comment by AMBudnik** [comment] 2017-07-14 11:17
You're right. The renderer is showing a single space while the editor holds two spaces.

**Comment by AMBudnik** [comment] 2020-07-07 12:59
Demo for tests - https://jsfiddle.net/pzL67d28/ (7.4.2) we also get a single space when the value is just used as a paragraph (in the document).

**Comment by AMBudnik** [comment] 2020-10-08 10:49
Demo updated to v 8.1.0 https://jsfiddle.net/AMBudnik/35xhe6mz/
The renderer is showing 'foo bar' while editor and data shows the value with two spaces.

**Comment by wojciechczerniak** [comment] 2021-03-23 09:39
@AMBudnik @aninde I think that @Osky772 fixed this in v8.3.2

**Comment by aninde** [comment] 2021-03-23 09:51
@lewisjb this issue is a duplicate of https://github.com/handsontable/handsontable/issues/7458 and was fixed by v8.3.2.

![Kapture 2021-03-23 at 10 47 54](https://user-images.githubusercontent.com/30186818/112127185-756fa000-8bc5-11eb-90bc-3d02b448e5d4.gif)

Working demo
https://jsfiddle.net/np7s23jm/ v8.3.2

Closing https://github.com/handsontable/handsontable/issues/4404  because it has been fixed.

**Closed by aninde** 2021-03-23 09:51 UTC
Labels: Type: Change
