### ISSUE TITLE
Scrolling is reversed on Microsoft Edge

### ISSUE THREAD

**Issue by NiLSPACE** [handsontable/handsontable#4771] opened 2018-02-01 13:40 UTC
### Description
When scrolling up or down in Microsoft Edge it does the opposite.

### Steps to reproduce
1. Create a HandsOnTable spreadsheet. (This one also works: https://fiddle.jshell.net/handsoncode/3gas9z6q/show/ )
2. Set overflow to hidden (I'm not sure if this is required)
3. Use your mouse to scroll down or up.

### Your environment
* Handsontable version: 0.35.1
* Browser Name and version: Microsoft Edge 41.16299.15.0 / Microsoft EdgeHTML 16.16299
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2018-02-06 12:47
Hi @NiLSPACE 

Thank you for sharing, This issue is actually reported here https://github.com/handsontable/handsontable/issues/4276 so please share any comment/reports/questions about the subject at https://github.com/handsontable/handsontable/issues/4276

**Comment by NiLSPACE** [comment] 2018-02-12 11:56
Hi @AMBudnik 

#4276 seems to be about scrolling with shift. The issue I'm talking about is that on Edge scrolling up means you're going to the bottom.

**Comment by AMBudnik** [comment] 2018-02-12 12:04
Hi @NiLSPACE 

Sorry, I thought that this is the same case. You're right - on Edge it is reversed without using SHIFT.

**Comment by watnab** [comment] 2018-02-26 11:21
#4320 seems to have relation with this issue.
> Microsoft Edge
> vertical scrolling on any table is inverted

**Comment by wojciechczerniak** [comment] 2018-03-01 15:37
I'm closing this as a duplicate of #4320

**Closed by wojciechczerniak** 2018-03-01 15:37 UTC
Labels: IE/Edge, Status: In development, Type: Bug
