### ISSUE TITLE
[Bug]: custom rendorer called multiple times and did dom manipulation creating a slow performance and row misalignment

### ISSUE THREAD

**Issue by prathmeshgogte** [handsontable/handsontable#10897] opened 2024-04-07 16:56 UTC
### Describe the bug

I am using handsontable and I ahve custom renderer which gets called multiple times and does dom manipulation thereby causing jumpy scroll and row page unresponsiveness and cpu utilization to 100 along with that rows gets misaligned in right side non fixed columns.

### Handsontable version

13

### Your environment

chrome  ,microsoft edge

**Comment by adrianszymanski89** [comment] 2024-04-08 08:19
Hi @prathmeshgogte 

Thank you for contacting us. In order to check what might cause such an impact on the performance, we will need to see your current implementation in the form of a code demo, where the issue is replicable. Please prepare one in a chosen sandbox.

**Comment by AMBudnik** [comment] 2024-06-06 09:45
Hi @prathmeshgogte 

I need to close this issue, as there have been no updates for two months now.

Please contact us at support@handsontable.com if you need any help.

**Closed by AMBudnik** 2024-06-06 09:45 UTC
Labels: bug, Status: Answered
