### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by KSandweb** [handsontable/handsontable#4206] opened 2017-04-20 09:51 UTC
### Description
When you scroll with keyboard and mouse wheel on fixed column, the rest of the table wont follow scrolling. This issue occurs in IE and Safari.
![screen capture](https://goo.gl/j4oQb9)
### Steps to reproduce
1. Select cell in fixed column
2. Roll up and/or down with keyboard
3. Scroll with mouse wheel

### Demo
http://jsfiddle.net/wLr350k5/

### Your environment
* Handsontable version: 1.10.1
* Browser Name and version: IE 11, Safari 10.1
* Operating System: Windows 10, OS X

**Comment by AMBudnik** [comment] 2017-04-21 13:24
Thank you @KSandweb I have replicated the issue as well.

**Comment by jakever** [comment] 2017-06-21 06:06
I also have this problem.

**Comment by AMBudnik** [comment] 2017-08-04 08:37
The issue is not replicable in version 0.34.0/1.13.0 ( I have tested the demo above on IE11/Windows 10)
I am closing the issue but feel free to let me know if you have any problems with the code.

**Closed by AMBudnik** 2017-08-04 08:37 UTC
Labels: Plugin: Fixing, Priority: normal, Type: Bug
