### ISSUE TITLE
Scrollbar for autocomplete editor disappears 

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6379] opened 2019-10-23 13:21 UTC
### Description

The vertical scrollbar for autocomplete and dropdown cell types disappears after it's triggered by the user a second time. 

### Steps to reproduce

1. Click on the arrow of the "gray" value to show the autocomplete list;
2. Click adjacent cell that with "white" value and delete value by pressing <kbd>DEL</kbd>;
2. Then click on the arrow;
4. As a result, the list doesn't have a scrollbar.

### Demo

Working demo (`6.2.2`) https://jsfiddle.net/xna2k7ho/3/.
![Kapture 2019-10-23 at 15 19 59](https://user-images.githubusercontent.com/571316/67396876-9d11a180-f5a8-11e9-8371-5c316dc0fe5a.gif)

Not working demo (`7.0.0`) https://jsfiddle.net/xna2k7ho/1/.
Not working demo (`7.2.2`) https://jsfiddle.net/xna2k7ho/2/.

![Kapture 2019-10-23 at 15 20 35](https://user-images.githubusercontent.com/571316/67396908-b0bd0800-f5a8-11e9-86b6-5c9dd02c6069.gif)

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by swistach** [comment] 2019-10-23 13:52
Steps to reproduce are a little bit different, but this issue is a duplicate of #6076.

**Closed by swistach** 2019-10-23 13:52 UTC
Labels: Cell type: autocomplete / dropdown / handsontable, Guess: a day or more, Regression, Type: Bug
