### ISSUE TITLE
File uploader inside handsontable

### ISSUE THREAD

**Issue by jbourassa** [handsontable/handsontable#1380] opened 2014-03-22 16:14 UTC
Hi,

Our team created a new `file` data type for Handonstable. We added a new Editor, a new Renderer and made some minor changes to Handonstable core to make all of this possible.

Merging back the feature wouldn't be too bad, but still requires some effort. Before working on it I wanted to know what your thoughts are on this feature?

Thanks!

**Comment by AMBudnik** [comment] 2015-05-11 08:06
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Closed by AMBudnik** 2015-05-11 08:06 UTC
Labels: Feature

**Comment by vergel-mercado** [comment] 2016-05-25 01:32
Is this already added in new version? thanks

**Comment by AMBudnik** [comment] 2016-05-25 11:18
Hi @vergel-mercado 
It is not ready yet. 

The issue is closed as we currently gather all ideas on our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests) and serve those which is under development of Trello at: https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-login-to-vote-for-features where (if you have a trello account) you can vote for listed features.

**Comment by rparikh-argus** [comment] 2017-04-11 06:09
Hi ,

Any updates about file upload feature ?

**Comment by AMBudnik** [comment] 2017-04-11 06:41
Hi @rparikh-argus 

the issue's not yet on our [Roadmap](https://trello.com/b/PztR4hpj/handsontable-roadmap-2017-login-to-vote).

**Comment by imtrobin** [comment] 2017-06-09 03:38
+1 for this (even if it's Pro feature). 
Would be great to display uploaded images like google spreadsheet
Didn't see this in roadmap.

**Comment by jacobsee** [comment] 2017-08-07 21:50
@jbourassa Do you still have this fork around? I would like to poke around with the editor and renderer if possible. Thanks.

**Comment by jbourassa** [comment] 2017-08-07 22:06
@jacobsee Unfortunately, I do not. It was part of a client project that I'm no longer working on.

**Comment by jacobsee** [comment] 2017-08-07 22:15
@jbourassa Ah, sounds good, thanks anyway!

**Comment by AMBudnik** [comment] 2021-04-28 12:23
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
