### ISSUE TITLE
Failed cell validation automatically clears from previous row when editing a new row

### ISSUE THREAD

**Issue by patrickryan79** [handsontable/handsontable#7541] opened 2020-06-17 17:37 UTC
### Description
I'm not sure if this is an intended feature, but I attempted to reproduce this without the wrapper and was unsuccessful. If I have a validator on a particular field, and trigger that validation, when I jump to a new row (i.e. `minSpareRows: 1`) the validation error clears from the previous row.

### Steps to reproduce
1. Open fiddle
2. Fill out name and tab to the next cell, which will trigger the population of a new row.
3. Delete name to show validation error
4. Type a value in the second row that was auto-created and the previous error will vanish.

### Demo
With vue wrapper (validation disappears): https://jsfiddle.net/dw1jry39/2/
Without (works as expected): https://jsfiddle.net/xpk0vajb/

### Your environment
* @handsontable/vue: "^4.1.1"
*  handsontable: "^7.4.2"

**Comment by AMBudnik** [comment] 2021-12-09 07:08
The issue is still replicable using the latest version (v11.0.1) - once we add a value to the 2nd-row validation status of the `0,0 `cell is erased

![Kapture 2021-12-09 at 08 06 56](https://user-images.githubusercontent.com/10757813/145349943-dff827d2-6ee9-44db-a031-1793ac070165.gif)
Updated demo: https://jsfiddle.net/n6r97haz/2/

**Comment by aninde** [comment] 2022-03-29 13:36
This issue will be fixed by the upcoming v12 https://jsfiddle.net/xhj8svmy/
![Kapture 2022-03-29 at 15 34 49](https://user-images.githubusercontent.com/30186818/160623659-9a548c19-0a19-448a-ae30-c1e59b09fddd.gif)

**Comment by AMBudnik** [comment] 2022-04-29 07:14
Thank you for checking that, @aninde 

@patrickryan79 Please update and let us know if it works for you as well

For everyone who is tracking changes to this topic please check our release notes https://handsontable.com/docs/release-notes/#_12-0-0 and the migration guide https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls

**Closed by AMBudnik** 2022-04-29 07:14 UTC
Labels: Type: Bug, vue
