### ISSUE TITLE
Filled cell data erases when cursor passes it via arrow keys

### ISSUE THREAD

**Issue by DaemonOfHell** [handsontable/handsontable#9520] opened 2022-05-24 12:35 UTC
### Description
what happened: Filled cell data erases when cursor passes it on some PCs ( not all )
what should happen: Filled cell data shouldn't erase when cursor passes it regardless the type of PC / platform 

### Steps to reproduce
Steps to reproduce ( occurred unexpectedly on some PCs - not all )
1. open (handsontable) table
2. enter value on an cell
3. move the cursor with arrow keys to the already filled cell.
4. leave the cell - the data in it should erase

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 12
* Browser name and version: Microsoft Edge - Version 101.0.1210.53 (Official build) (64-bit) (working fine)
* Operating system: windows10

**Comment by adrianszymanski89** [comment] 2022-05-26 12:17
Hi @DaemonOfHell 

I was trying to recreate your issue in the environment you described but I think I'm doing something wrong following your steps because I don't get the same result. If you could show me the steps on gif or short video it would be great.

**Comment by AMBudnik** [comment] 2022-08-16 13:58
Hi @DaemonOfHell 

Could you please share any detail regarding this case?

**Comment by AMBudnik** [comment] 2022-08-22 13:10
I think that we can close this issue report as there are no updates, and we are not able to replicate the issue.
@DaemonOfHell if it still does network for you please send us a video reproduction at support@handsontable.com

**Closed by AMBudnik** 2022-08-22 13:10 UTC
Labels: Status: Answered
