### ISSUE TITLE
sorting interferes with validation

### ISSUE THREAD

**Issue by ryan-chambers** [handsontable/handsontable#1526] opened 2014-06-09 18:31 UTC
I have a use case where I want to validate all data in the table after the data is loaded, rather than waiting for one of the cells to change view user input. To do this, I invoke validateCells() after creating the handsontable instance. For a working example that slightly tweaks the standard validation sample, see http://jsfiddle.net/eFGdN/1/

But if I enable column sorting, the invalid cells are not highlighted. See http://jsfiddle.net/eFGdN/2/.

**Comment by Areson** [comment] 2015-05-06 14:31
I'd like to add some additional info on this bug. I believe it is related to this commit: 07cbcc86c616c792611aa827fce8a9067dc7fcdc

A wrapper for the callback passed to *validateCell* was added that render each individual cell after validation has finished, before calling the original callback passed to *validateCell*. The line `td = instance.getCell(row, col, true)` interprets the row/col coordinates as visual coordinates in the table, but the *getCellMeta* function, which is used to get the *cellProperties* passed into *validateCell* sets *cellProperties.row* and *cellProperties.col* using the source coordinates. This results in the wrong td element being retrieved when sorting has been applied.

A work-around for the time being is to supply your own callback to *validateCells* which calls the render method to redraw the entire table after validation is complete.

**Comment by AMBudnik** [comment] 2016-03-16 09:42
Hi @ryan-chambers @Areson I couln't reproduce it with the latest version 0.24.0 - could you check it also?
My demo: http://jsfiddle.net/handsoncode/ujgne7on/

**Comment by ryan-chambers** [comment] 2016-03-16 22:37
That's great to hear. But the project using it was cancelled, so no way to test.

**Comment by Areson** [comment] 2016-03-16 22:56
I'll try and take a look when I get a chance.

**Comment by AMBudnik** [comment] 2016-03-17 09:44
Thank you both

**Comment by Areson** [comment] 2016-03-21 17:00
@AMBudnik I took a look at your fiddle and took a look at the latest source. It looks like this may be resolved as far as I can tell. The added properties of `visualCol` and `visualRow` resolve the issue of having the wrong coordinates when calling `getCell`. Thanks!

**Comment by AMBudnik** [comment] 2016-03-22 08:31
@Areson thank you for taking the time to check this one.
I assume this issue can be closed.

**Comment by wc-matteo** [comment] 2016-07-12 12:02
I'm using v0.26.0 and there's still something wrong with validation combined with sorting:
as an example, there's a cell in a specific row that doesn't get updated visually with the right format (type time) when trying to insert wrong values, but has the right value reported by afterChange (source timeValidator), at the same time this correct values updates the visually a cell in the same column in the row immediatly above. Disabling columns sorting, fixes these issues...

**Comment by AMBudnik** [comment] 2016-07-12 12:35
Can you guide me on how to replicate the issue @wc-matteo or maybe you can create a video to show the problem?

**Comment by wc-matteo** [comment] 2016-07-12 13:00
http://jsfiddle.net/wm2pjyha/

### Steps

- add `3` in the empty cell and change focus (e.g. click outside the table)

> `3` gets auto corrected in `03.00`

- sort the column

- repeat the first step in the first cell this time (replacing the entire cell)

> now first the value of the first cell is `3`, that of the second cell is `03.00`

**Comment by AMBudnik** [comment] 2016-07-12 13:19
I've reproduced the issue. Thank you @wc-matteo 

![ie-bug](https://cloud.githubusercontent.com/assets/10757813/16768294/090c5fda-4844-11e6-93bd-9d5b6b977ec9.gif)

**Comment by swistach** [comment] 2017-01-05 13:48
That should be fixed in: #3953

**Comment by AMBudnik** [comment] 2017-01-11 12:18
Hi guys, we have done some changes to meta data in 0.30.0.
The example should work as expected (demo: http://jsfiddle.net/opa1raxf/) 
Please test it in your projects.

Origin: https://github.com/handsontable/handsontable/issues/3953

**Comment by AMBudnik** [comment] 2017-02-06 14:37
I am closing this issue as there is no reply since nearly a month. However feel free to comment if needed.

**Closed by AMBudnik** 2017-02-06 14:37 UTC
Labels: Status: Answered
