### ISSUE TITLE
custom menus with react? 

### ISSUE THREAD

**Issue by mx2323** [handsontable/handsontable#6811] opened 2020-04-09 17:00 UTC
hi there -

is there a way to use my own react component as a menu? as much as i like the dropdown and context menus functionality currently, i would like to be able to use my own menus that are written in react ( as i already have this code written and don't want to have to maintain two different types of menus, ones for handsontable and one for other parts of my app. 

thanks!

**Comment by pnowak** [comment] 2020-04-10 07:54
Hi @mx2323 

I'm not sure that I fully understand your issue.

Could you look at our tutorial about Custom Context Menu example - https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-react-custom-context-menu-example.html
Is it something similar you want to achieve?

It would be great if you could share a demo where the issue is replicable.

**Comment by mx2323** [comment] 2020-04-10 15:19
this is a feature request. i am actually currently using that example you sent - but if i wanted to use my own react dropdown menu.

instead of this part of the example 
```code
 - contextMenu: {
          items: {
            'row_above': {
              name: 'Insert row above this one (custom name)'
            },
            'row_below': {},
            'separator': Handsontable.plugins.ContextMenu.SEPARATOR,
            'clear_custom': {
              name: 'Clear all cells (custom)',
              callback: function() {
                this.clear();
              }
            }
          }
```
i would like to be able to use my own react component menu in the window that pops up.

**Comment by pnowak** [comment] 2020-04-15 09:40
Hi @mx2323 

It's an interesting idea, but we don't have resources to do it in the near future. 
Nevertheless, I created an issue on our react-handstonable repo. 
Here is a link - https://github.com/handsontable/react-handsontable/issues/180

So I close this issue. 
You will be able to follow all the arrangement and progress in the react issue given above.

**Closed by pnowak** 2020-04-15 09:40 UTC
Labels: Type: Demo needed
