### ISSUE TITLE
Problems to make specific cells readonly when one or more columns are hidden

### ISSUE THREAD

**Issue by andrescardona** [handsontable/handsontable#349] opened 2013-01-08 22:03 UTC
Normally the method that is provided to hide a column is using the columns property to specify the rendering of one or another element from a dataset; this is ok, but for instance when you want to make a cell readonly based on the position in the **dataset**, the cells callback function doesn't help to much, it returns the relative row and column to the actual rendered table, and you only have handsontable('getData') that returns the original dataset, so in the visible table you can not point to the right cell to make it readonly. 

It might be handy to have a method that returns the object from the dataset based on their new relative position, that is if i have the following dataset

    [
        [{budget: 1, isReadOnly: true}, {budget: 2, isReadOnly: false}, {budget: 3, isReadOnly: true}],
        [{budget: 4, isReadOnly: fa;se}, {budget: 5, isReadOnly: false}, {budget: 6, isReadOnly: false}]
    ]

And i have the following columns

    [{data: '0.budget'}, {data: '2.budget'}]

Having **handsontable('getObject', relativeRow, relativeCol)** 
**handsontable('getObject', 0, 1)**  might return   **{budget: 3, isReadOnly: true}**

What do you think ?

**Comment by AMBudnik** [comment] 2015-05-06 13:34
Please prepare a demo of your code and we'll see where the issue is.

**Comment by AMBudnik** [comment] 2015-07-07 15:17
Issue closed in lack of needed demo.

**Closed by AMBudnik** 2015-07-07 15:17 UTC
Labels: Demo needed
