### ISSUE TITLE
[8.0.0-beta.2] Script error when using hiddenColumns with nestedHeaders

### ISSUE THREAD

**Issue by mbrainiac** [handsontable/handsontable#7160] opened 2020-07-31 15:07 UTC
### Steps to reproduce
Case 1:
1. Create table with hiddenColumns and nestedHeaders enabled
2. Hide first column of group (A1 below A, or B21 below B...)
3. Group header A, B... disappear

Case 2:
1. Create table with hiddenColumns and nestedHeaders enabled 
2. Hide first column of group (A1 below A, or B21 below B...)
3. Scroll to right
4. Rows/columns disappear and "Script error." throw in console
 

### Demo
https://jsfiddle.net/z7jt1wda

![Kapture 2020-07-31 at 22 27 30](https://user-images.githubusercontent.com/1453038/89050528-154d9480-d37d-11ea-90db-985bfa21de07.gif)

### Your environment
* Handsontable version: 8.0.0-beta.2
* Browser Name and version: Chrome
* Operating System: Mac OS

**Comment by AMBudnik** [comment] 2020-08-04 08:48
Thank you for sharing this issue @mbrainiac 

7.4.2 - working well https://jsfiddle.net/qpmkbuLc/
![742](https://user-images.githubusercontent.com/10757813/89272518-94252480-d63e-11ea-963b-533f6c5ec77a.gif)

8.0.0- broken https://jsfiddle.net/yjb4L2uv/ (frozen 8.0.0)
![bug](https://user-images.githubusercontent.com/10757813/89272584-a69f5e00-d63e-11ea-8a85-af9defa06c75.gif)
![Zrzut ekranu 2020-08-4 o 10 40 02](https://user-images.githubusercontent.com/10757813/89272737-e108fb00-d63e-11ea-855e-22f3f7b4a915.png)


Tested on macOS Catalina 10.15.3 / Chrome 84

As the issue does not happen for our official demo https://jsfiddle.net/yjb4L2uv/1/ it seems that the structure of `nestedHeaders` is crucial to narrow the issue down. 
Here https://jsfiddle.net/yjb4L2uv/2/ I used `colspan: 20` for the 1st lvl header and the issue is replicable. When I had 10 columns instead of 20 the issue with missing content was not replicable. It means that it might be related to the viewport. 

A similar issue has been reported here https://github.com/handsontable/handsontable/issues/6879 so after fixing this regression we need to test all the reported scenarios.

**Comment by eduardoalvara2** [comment] 2020-11-16 16:41
I am facing this same issue as well

**Comment by Surecom** [comment] 2021-03-10 19:08
How much time we must wait until it get fixed? 8.3.1 - BROKEN!!!

**Comment by AMBudnik** [comment] 2021-03-11 08:13
This issue hasn't been fixed yet. But there is a temporary workaround with adding a blank column and hiding it https://jsfiddle.net/uya1bsc8/ (you'd only need to adjust the `nestedHeaders` titles)

**Comment by Surecom** [comment] 2021-03-11 08:17
it doesnt work properly.
no errors is not works well
![image](https://user-images.githubusercontent.com/7001010/110756432-3ce1d500-825b-11eb-8b48-055e906d4e0c.png)
after hide set of columns, why B-s showed under "a" column ??

**Comment by AMBudnik** [comment] 2021-03-11 09:40
That's the second part of the issue, @Surecom 
However, you can use the `updateSettings` to change the `nestedHeaders` configuration. The `beforeHideColumns` hook returns the indexes of hidden columns so you know what indexes are hidden within the action and what was already hidden before.

**Comment by Surecom** [comment] 2021-03-11 09:45
it will not work :) i tried almost everything you could have in your mind :)

btw, even with your work-a-round errors happens, because i d like to hide multiple set of columns.

i have decided to "remove" columns, and using undo-redo hacks and nestedHeaders fields' configuration avoid this issue, but it is disgusted.

with last 7x version everything worked fine, but with 8x nope... it is disappointing

**Comment by AMBudnik** [comment] 2021-03-11 09:49
Yes, each idea is only a half-workaround. We definitely need to officially fix it as soon as possible.
I will make sure to notify you when it happens.

**Comment by AMBudnik** [comment] 2021-03-11 12:04
Related: https://github.com/handsontable/handsontable/issues/6879

**Comment by Surecom** [comment] 2021-03-20 16:14
Its fine, I have already work-a-rounded this error with recalculation nested headers :) and updateSettings :)

**Comment by aninde** [comment] 2021-04-26 11:39
The [PR](https://github.com/handsontable/handsontable/pull/7528) assigned to this issue only fixed the first use of the [reproduction](https://github.com/handsontable/handsontable/issues/7160#issue-669913012). The error still persists when doing reproduction twice.

**Comment by Surecom** [comment] 2021-04-26 12:48
dynamically re-calculation nested headers - helps me with no issues :)
we know what headers we are hiding, we know whole structure of nested headers.
I just recalculate them dynamically and update settings in my project :)

**Comment by wojciechczerniak** [comment] 2021-05-11 12:49
> This reproduction works better with the new v8.4.0, but an error in the console is still reproducible after a few uses.
> Demo: https://jsfiddle.net/ynzbtfL1/

Can't reproduce. Can you provide the detailed steps?

**Comment by aninde** [comment] 2021-05-11 13:00
> Can't reproduce. Can you provide the detailed steps?

It seems to me that the speed of the operation is important.
Scrolling should be done without clicking.
After each scroll, more columns should be hidden than before.

![Kapture 2021-05-11 at 14 58 28](https://user-images.githubusercontent.com/30186818/117819037-7211a000-b269-11eb-9a1a-4c684f4ecf4f.gif)

Reproduction:
1. Hide column A1.
2. Scroll horizontally into the right edge of the table by mouse wheel or touchpad.
3. Scroll horizontally into the left edge (to the start of the table).
4. Hide two columns, eg. A2 & A3.
5. Repeat steps 2 & 3.
6. Hide columns A4, A5, A6.
7. Repeat steps 2 & 3.
Result: error.

**Comment by aninde** [comment] 2021-07-20 14:19
I'm glad to see that upcoming, currently tested v9.0.2 fixes this problem even after a few repetitions.
Demo v9.0.2-RC https://jsfiddle.net/3roe10kp/.

**Comment by swistach** [comment] 2021-07-28 13:27
Hi @mbrainiac, @Surecom, @eduardoalvara2,
I'm happy to announce we just released v9.0.2 with the fix to this bug.

**Closed by swistach** 2021-07-28 13:27 UTC
Labels: Hiding, Nested Headers, Regression, Type: Bug
