### ISSUE TITLE
Right clicking the corner of handsontable for context menu throws error

### ISSUE THREAD

**Issue by GitHubStig** [handsontable/handsontable#2099] opened 2015-01-26 07:08 UTC
![screen shot 2015-01-26 at 2 58 10 pm 2](https://cloud.githubusercontent.com/assets/9544391/5896245/b27bbfec-a56c-11e4-8015-84cdb1a33a00.png)

If a user clicks on the corner of handsontable for context menu, an error is throwned. But it doesn't occur if the context menu has been 'created' from clicking anywhere other than the corner first.

**Comment by mkcor** [comment] 2015-02-02 23:08
Indeed. Does the corner have row index equal to `-1` (like it has column index equal to `-1`)?

Right-clicking the corner errors because variable `selected` (https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L9502) is `undefined` for the corner, so you cannot access `selected[1]`. For 'regular' rows, `selected` is a proper array.

So there should either be a check here for the 'truthiness' of `selected` or, as a better/stronger approach, the whole `contextMenu` event should only apply to actual rows (row index `>= 0`) -- it should be unavailable/disabled for the corner, which is not a proper row header.

/cc @jansiegel

**Comment by jansiegel** [comment] 2015-02-03 08:56
@GitHubStig, @mkcor Confirmed, thanks for reporting!

**Comment by krzysztofspilka** [comment] 2015-02-05 15:25
Fixed and released in v 0.12.5
See the release notes for it: https://github.com/handsontable/handsontable/releases/tag/0.12.5

**Closed by krzysztofspilka** 2015-02-05 15:25 UTC
Labels: Bug, Plugin: context menu, Released
