### ISSUE TITLE
before/afterOnCellMouseOver does not run when entering a border cell from the outside

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4634] opened 2017-11-28 22:56 UTC
### Description

When entering a border cell (one of the cells on the very outside of the table) from the outside of the table after leaving the table through that cell (if that makes sense) then it will not trigger but the `before/afterOnCellMouseOut` event does trigger. May be related to #4296.

### Steps to reproduce

1. http://jsfiddle.net/Lp4qn55v/859/
2. Hover over any outside border (B10 for example)
3. Leave the table (Move mouse down for example)
4. Hover over the same cell (B10 for example)
5. Leave cell again

The `afterOnCellMouseOver` will be called when initially hovering over B10. When you exit the table `afterOnCellMouseOut` will be called. Upon entering the table again `afterOnCellMouseOver` will not be called even though it should be. When leaving the cell a second time `afterOnCellMouseOut` will be called.

### Demo

http://jsfiddle.net/Lp4qn55v/859/

### Your environment
* Handsontable version: 1.14.1
* Browser Name and version: Chrome 62.0.3202.94 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2017-12-01 14:13
Thank you @jeremy-smith-maco 

I have replicated the issue, the one `beforeOnCellMouseOver` call is gone.

**Comment by AMBudnik** [comment] 2018-04-30 11:27
It doesn't seem to work from the `0.31.1` publication when the hooks were added.

**Comment by bitwolfe** [comment] 2020-07-01 13:17
Any news on this getting a fix? Seems to still be an issue.

**Comment by AMBudnik** [comment] 2020-07-01 13:30
Hi @bitwolfe 
this issue has been marked as 'To be discussed' so we had some discussion and haven't come to an agreement on the desired result. The following case is out of the scope of 8.0.0-beta2 (upcoming version)

**Comment by bitwolfe** [comment] 2020-07-01 13:33
That's unfortunate, I was hoping for a pre-8.0 fix.

**Comment by AMBudnik** [comment] 2020-07-01 13:54
@bitwolfe it was more about the way we should handle the case - the result is clear. 
However, as there is are no details on **why** the label was added I'm removing it.

**Comment by pnowak** [comment] 2020-09-10 12:50
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/b5um24vj/

**Comment by LeTranAnhVu** [comment] 2020-10-27 11:19
Any updating from now? Or does anyone know how to workaround with it? I used Hansontable version 6.2.2.

**Comment by AMBudnik** [comment] 2020-10-27 11:40
Hi @LeTranAnhVu This issue hasn't been scheduled yet. 
I will make sure to inform you once it gets fixed.

**Comment by LeTranAnhVu** [comment] 2020-10-27 12:47
I have found the problem is from the image below (red line). It is dist/handsontable.js
![hansonBug](https://user-images.githubusercontent.com/26917283/97303373-fc149100-1862-11eb-93f9-65938df48d11.PNG)

So that when I remove the middle condition `td !== mainWOT.lastMouseOver`. It works. I have no idea any side effect to do that. Hopefully it can help maintain team somehow.

**Closed** 2021-01-14 15:39 UTC
Labels: Core: callbacks, Type: Bug

**Comment by AMBudnik** [comment] 2023-05-23 11:23
Hi @jeremy-smith-maco, @bitwolfe, @LeTranAnhVu,

I have good news! I've just closed https://github.com/handsontable/handsontable/issues/4296 as we fixed it in the latest version. Please update and let me know if everything works for you as well.
