### ISSUE TITLE
Checkbox to be rendered outside the label tag

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3172] opened 2016-01-29 10:54 UTC
It refers to: http://docs.handsontable.com/0.21.0/demo-checkbox.html

At the moment we can decide whether a label is rendered before/after checkbox but it's still all happening inside the `label` tag, which means we can't use that famous and well known CSS hack to customize the design of a checkbox. We could add a new property to the pile:

**Current:**
label: {
          position: 'after' /\* or before */
         }

**New:**
label: {
          **separated: 'false', /\* default value, if true = label will be a separated tag positioned before or after the checkbox */**
          position: 'after',
         }

**Comment by bud-e** [comment] 2019-01-02 02:54
@AMBudnik 
Ok, But I already open PR(https://github.com/handsontable/handsontable/pull/5539) for this one. So, Whenever you open this Issue again consider above PR.

Thanks

**Comment by AMBudnik** [comment] 2021-03-26 08:44
Related PR https://github.com/handsontable/handsontable/pull/5539 has been accepted. This issue will be tested and released under the next Handsontable version.

**Comment by aninde** [comment] 2021-05-05 12:06
This issue will be fixed by v8.4.0.
Demo: https://jsfiddle.net/j53z8fk0/

**Comment by AMBudnik** [comment] 2021-05-11 13:30
The issue is officially solved in [v8.4.0](https://github.com/handsontable/handsontable/issues/7998)

**Closed by AMBudnik** 2021-05-11 13:30 UTC
Labels: Cell type: checkbox, Guess: few hours, Type: Feature
