### ISSUE TITLE
Column sorting is broken on large data sets with many null values

### ISSUE THREAD

**Issue by dbishai** [handsontable/handsontable#2770] opened 2015-08-28 16:47 UTC
http://jsfiddle.net/YpaR7/7/

**Comment by AMBudnik** [comment] 2015-08-31 08:00
There's no need to use larga datasets, [here's](https://jsfiddle.net/g2kxymy9/1/) the example with broken sorting. Thanks for reporting.

**Comment by stesix** [comment] 2015-10-06 16:29
Here's another example: http://jsfiddle.net/tqbkgsq2/

**Comment by dbishai** [comment] 2015-10-08 15:15
@stesix, that is interesting how the sorting stops working

**Comment by dbishai** [comment] 2015-10-08 22:50
I made a pull request #2881 to fix this

**Comment by stesix** [comment] 2015-10-13 11:40
@dbishai: thanx for your fix. My issue was different from the one you solved. There was a misplaced column offset when part of the table is hidden. So when you try to sort a value in the 10th column and have 3 hidden columns, you end up sorting the column 13.
 
Anyway, I discovered later that this was a known issue (#542) for which I prepared a pull request (#2890)

**Comment by krzysztofspilka** [comment] 2016-02-19 13:06
@dbishai @stesix can you still reproduce the bug in the latest version of Handsontable?

**Comment by dbishai** [comment] 2016-02-19 15:41
I haven't tried it but considering the responsible code does not look to have changed, I would think the bug is still there. I am using my own build of handsontable with my pull request included.

**Comment by AMBudnik** [comment] 2016-02-19 17:01
Hi @dbishai please check the @stesix example above and the same one in 0.23.0 http://jsfiddle.net/tqbkgsq2/1/ seems to be fixed.

**Comment by dbishai** [comment] 2016-02-19 17:23
@AMBudnik, the issue @stesix had was different than mine. However, it does look like my sorting issue has been fixed in 0.23.0. You can confirm this by comparing the jsfiddles from the first and second posts which use handsontable 0.23.0 and 0.17.0 respectively. Not sure if you have tests for this or not but I wrote some in my pull request.

**Comment by dbishai** [comment] 2016-04-21 19:12
This ticket needs to be reopened as the bug has not been fixed. I tried upgrading to 0.24.2 and the bug is still present. I went back to using my patched version containing the fix in my pull request.

**Comment by dbishai** [comment] 2016-04-21 19:17
Is there a reason why my fix will not be pulled? It is only 3 lines of code and ensures that this bug will not pop up again.

**Comment by AMBudnik** [comment] 2016-04-22 08:06
Here's an example with the latest version - 0.24.2 https://jsfiddle.net/xfgo22qt/
It seams like we never bring the null data at the top it always stays at the bottom of the column

**Comment by dbishai** [comment] 2016-04-22 14:27
@AMBudnik Try this: https://jsfiddle.net/xfgo22qt/1/

**Comment by budnix** [comment] 2016-06-20 09:55
PR https://github.com/handsontable/handsontable/pull/2881 was merged into develop. Marking as "merged".

**Comment by dbishai** [comment] 2016-06-20 14:56
Thanks for merging but I haven't received any credit for my commit. You basically took my changes and pushed them as your own. That's really dishonest. If you needed me to change something I could've easily modified the pull request. The fact that this took 9 months too is ridiculous.

**Comment by budnix** [comment] 2016-06-20 15:16
Hi @dbishai, It wasn't my intension to take your changes and push it as mine. I simply reviewed your code and pushed this changes which I agree with. I'm sorry if you feel that I'm dishonest.

In most cases developers make PR in not recommended way (merge into `master` instead to `develop`) so in almost every case I need to merge them manually which causes a change to be pushed under reviewer nickname.

**Closed** 2016-06-27 15:36 UTC
Labels: Bug, Plugin: column sorting, Priority: normal, Released
