### ISSUE TITLE
Context menu not closing on last row removal

### ISSUE THREAD

**Issue by johanneseschrig** [handsontable/handsontable#4168] opened 2017-04-05 12:54 UTC
### Description
The context menu should close after the last row was removed

### Steps to reproduce
1. Right click -> "remove row" on last existing row
2. Row is removed, but context menu is still there. Only disappears on clicking outside of it.

### Demo
http://jsfiddle.net/rgxzmyxn/

### Your environment
* Handsontable version: 0.24.1
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: Win10

**Comment by ankushgoel** [comment] 2017-04-06 05:26
Hi @johanneseschrig 
Please update your version of Handsontable

**Comment by AMBudnik** [comment] 2017-04-06 06:39
Thanks for sharing the updated demo @ankushgoel 

@johanneseschrig when you update your code to newest version the issue is different - the same as reported by @ankushgoel at https://github.com/handsontable/handsontable/issues/4169 so I am closing this issue.

**Closed by AMBudnik** 2017-04-06 06:39 UTC
