### ISSUE TITLE
The ContextMenu selection for `Alignment` disappears

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6508] opened 2019-11-29 12:56 UTC
### Description

This issue #6304 changed behavior on how the context menu items are executed. Since 7.3.0 (and beta 8.0.0) the ContextMenu triggers action on `mouseup` event. This change showed a visual bug/glitch which revealed as disappearing selection of submenu when the LMB is pressed.

### Steps to reproduce

1. Go to https://jsfiddle.net/9c7kp14n/;
2. Trigger context menu and go to "Alignment" submenu;
3. Click but not release LMB on "Justify" item;
4. As a result, the submenu loses his selection.

![Kapture 2019-11-29 at 13 54 20](https://user-images.githubusercontent.com/571316/69870311-c90ef980-12af-11ea-8cdc-05395e8e0404.gif)

### Demo

https://jsfiddle.net/9c7kp14n/;

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by aninde** [comment] 2019-12-10 14:02
I changed the issue title because the mistake was that the selection from Alignment in the main contextMenu disappeared after holding LMB on submenu.

This issue will be fixed thanks to new build of `7.3.0 v.` https://jsfiddle.net/aninde/4ykesm76/

**Comment by aninde** [comment] 2020-07-10 12:33
This issue is still solved in `8.0.0-beta2-rev21` https://jsfiddle.net/aninde/jkqgd1sb/

**Comment by aninde** [comment] 2020-07-10 12:40
Can not be reproduced in the latest stable version of `v7.4.2`https://jsfiddle.net/aninde/0sd1rb8u/, so I'm closing it and remove from the scope of v8.

**Closed by aninde** 2020-07-10 12:40 UTC
Labels: Context menu, Core: alignment/height/width, Guess: a day or more, Status: Merged (ready for release), Type: Bug
