### ISSUE TITLE
Context menu not working with mobiles

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4833] opened 2018-02-22 05:25 UTC
### Description

Cannot use a context menu on a mobile device

### Steps to reproduce

1. Open http://jsfiddle.net/Lp4qn55v/887/ on a mobile device
2. Tap and hold on any cell
3. Try and use any function of the context menu

### Demo

http://jsfiddle.net/Lp4qn55v/887/

### Your environment
* Handsontable version: 1.15.0 (pro)
* Browser Name and version: Google Chrome 64.0.3282.137
* Operating System: Android 7.0.0; SM-G955F

**Comment by AMBudnik** [comment] 2018-02-22 07:48
You're right. We are lacking an event that will differ if we want to open a menu or edit a cell. I am not quite sure how we can achieve it (for newer iPhones it could be a long click).

**Comment by wojciechczerniak** [comment] 2019-01-31 09:50
I will close this as a duplicate of #5171 because we have there a discussion and an idea how we can handle this.

**Closed by wojciechczerniak** 2019-01-31 09:50 UTC
Labels: Mobile, Plugin: context menu, Type: Bug
