### ISSUE TITLE
Can't import the named export 'ERROR_REF' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by pabloimrik17** [handsontable/handsontable#7650] opened 2021-03-24 13:19 UTC
### Description
After installed both packages i tried to render the component and i am getting this error via webpack:

> ERROR in ./node_modules/handsontable/plugins/formulas/sheet.mjs 280:20-29
Can't import the named export 'ERROR_REF' from non EcmaScript module (only default export is available)
 @ ./node_modules/handsontable/plugins/formulas/formulas.mjs
 @ ./node_modules/handsontable/plugins/formulas/index.mjs
 @ ./node_modules/handsontable/plugins/index.mjs
 @ ./node_modules/handsontable/index.mjs
 @ ./node_modules/@handsontable/react/es/react-handsontable.js
 @ ./src/components/spreadsheet/gv-spreadsheet.component.tsx
 @ ./src/views/masivos/propiedad/ficheros/EditarFicheroView.tsx
 @ ./src/views/masivos/propiedad/ficheros/FicherosGeneralView.tsx
 @ ./src/views/masivos/propiedad/ficheros/MasivosPropiedadFicherosView.tsx
 @ ./src/views/masivos/propiedad/MasivosPropiedadView.tsx
 @ ./src/components/Molecules/ViewBuilder.js
 @ ./src/components/Organisms/Form.js
 @ ./src/ProductLoader.js

Could this be related to the monorepo change after 8.3.2?

### Steps to reproduce
1. Install the packages
2. Run a very basic example of the component

![image](https://user-images.githubusercontent.com/5611863/112316825-c22da680-8cab-11eb-8de6-ac105c580b7f.png)
![image](https://user-images.githubusercontent.com/5611863/112316849-c6f25a80-8cab-11eb-93c5-1f0d4370068f.png)

### Demo

https://jsfiddle.net/handsoncode/c6rgz08x/

### Your environment
* React wrapper version: 5.0.0
* Handsontable version: 8.3.2
* Browser Name and version: Chrome
* Operating System: Windows
* Webpack: 4.44.2
* Typescript: 4.0.3

**Comment by AMBudnik** [comment] 2021-03-25 14:05
Hi @pabloimrik17 

Can you please add your webpack configuration?

**Comment by pabloimrik17** [comment] 2021-03-26 08:32
Hi, our webpack config:

![image](https://user-images.githubusercontent.com/5611863/112603958-f3c28100-8e15-11eb-8ab6-986b18385338.png)

![image](https://user-images.githubusercontent.com/5611863/112604020-03da6080-8e16-11eb-96d1-55121c233150.png)


![image](https://user-images.githubusercontent.com/5611863/112603733-b0681280-8e15-11eb-8bdc-2a2a7667436b.png)

![image](https://user-images.githubusercontent.com/5611863/112603858-d68db280-8e15-11eb-8f03-00893ac1dfd5.png)

![image](https://user-images.githubusercontent.com/5611863/112603892-e1484780-8e15-11eb-9e25-51a46094cdc6.png)


I excluded mode, entry, output, devServer and resolve keys.

Also tsconfig.json

![image](https://user-images.githubusercontent.com/5611863/112604129-1ce31180-8e16-11eb-9710-602a766516b5.png)

**Comment by swistach** [comment] 2021-03-30 14:25
Hi @pabloimrik17,
I tested the latest `create-react-app` with `--template typescript`.
There is no error like that. Monorepo doesn't change npm package content.
Changes that might interfere with the way how webpack uses handsontable was introduced within modularization changes.

Due to the many possible reasons that error occurs, might I ask you to prepare an example repository with a configuration, as simple as possible, to reproduce the error? It will help us a lot and definitely speed up the investigation.

**Comment by miracleDD** [comment] 2021-04-06 10:35
Hi @pabloimrik17,  I also encountered this problem. You can try this:
`module: {
      rules: [
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: 'javascript/auto',
        },
        ...
      ]
    }`

**Comment by pabloimrik17** [comment] 2021-04-12 13:24
@miracleDD You made my day, its working.

I have to ask, what exactly does `type: "javascript/auto"` and what kind of files are asociated with .mjs extension?

**Comment by pabloimrik17** [comment] 2021-04-22 10:26
Hi @swistach, based on the webpack configuracion change to solve the issue, do you still need a clean repo similar to my project or this fix guides you to the root of the problem?

**Comment by swistach** [comment] 2021-04-26 07:21
@pabloimrik17, that's great you solved it in your project!
However, if you can share your configuration, it might help us verify if we can improve Handsontable.

**Comment by AMBudnik** [comment] 2021-05-17 07:22
I'm closing this topic as we did not get updates for more than 3 weeks. 
But if anyone would like to participate in this conversation and share details on how to set up the environment to replicate the issue, please feel free to leave a comment.

**Closed by AMBudnik** 2021-05-17 07:22 UTC
Labels: Type: Demo needed, react
