### ISSUE TITLE
object.observe deprecated in Chrome Version 50

### ISSUE THREAD

**Issue by michaelkochhugobosscom** [handsontable/handsontable#3163] opened 2016-01-27 11:36 UTC
Hi, 

i found a deprecated Message in Chrome Version 50.0.2631.0 canary (64-bit) :

'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.

handsontable.full.js line 20054.

Please tell me more about the Roadmap and a possible Solution .

Kind Regards

**Comment by AMBudnik** [comment] 2016-01-27 11:47
@michaelkochhugobosscom thanks for sharing.

**Comment by krzysztofspilka** [comment] 2016-02-12 09:12
Hi @michaelkochhugobosscom we'll provide a backward compatibility based on an interval function observing changes in all the objects after April 2016.

**Comment by JamesHenry** [comment] 2016-03-10 16:05
Please can we revisit this now that Chrome 50 is latest stable release? I was going to report it as an issue but fortunately found this existing one.

Every app that uses handsontable in Chrome 50 will receive this message:
![unspecified](https://cloud.githubusercontent.com/assets/900523/13675429/75068a5c-e6d9-11e5-8751-25fa7f9ee0d9.png)

Obviously it is totally up to you guys how you manage your issues, but it would have been easier to find this had it not been closed and marked as a question. IMHO it is neither of those things :)

Many thanks for handsontable!

**Comment by budnix** [comment] 2016-03-11 09:22
I think that this is not a bug. We provide fallback (feature detection) for this functionality, if the judgment day comes Handsontable will still be working. In the feature we can try to switch to ES2015 proxies or getters/setters to achieve similar functionality.

Currently i suggest to mark this issue as low priority and not a bug but rather as a change.

**Comment by JamesHenry** [comment] 2016-03-11 10:21
I agree :+1:

**Comment by ModestGenius** [comment] 2016-04-13 16:29
@budnix What is the oldest version that provides this fallback? I have a client using 0.10.0. When this times come will their app crash? Thank you for your help.

**Comment by budnix** [comment] 2016-04-22 07:50
Hi @ModestGenius, sorry for delayed response. I looked into the source code and I can confirm that since 0.9.12 - when plugin `observeChanges` was added, it was added with proper fallback. Your client version should work as earlier without any issues.

**Comment by jdmcnair** [comment] 2016-04-28 18:15
I think this may have been an issue afterall. We're seeing huge UI issues with handsontable for anyone with chrome version 50.0.2661.87. I think they finally removed `Object.observe` because we're no longer seeing that deprecation. I found a way to reproduce *one* of the underlying issues that we're seeing on your examples page. 

If you go to: https://handsontable.com/examples.html?column-summary&sorting (those column-summary and sorting options are important), then toggle on/off the "Export to CSV" option with chrome version 50.0.2661.87. You'll get this error: **Uncaught TypeError: Cannot read property 'isPaused' of null**.  Note that you will not see this with previous versions.

If you trace this error down, it's on line 18276 of **handsontable.full.js**, inside `onDataChange`, on a line with `this.observer.isPaused()`. Seems related... I don't think your fallback is working in all cases.

**Comment by AMBudnik** [comment] 2016-04-29 09:44
related [pro: Chrome 50](https://forum.handsontable.com/t/major-handsontable-ui-issues-in-chrome-50-0-2661-87/314)

**Comment by budnix** [comment] 2016-04-29 15:15
In fact, there is a problem. 

Thanks to @tyschroed [PR's](https://github.com/handsontable/handsontable/pull/3442) it fixes issue with fallback code.

**Comment by timwis** [comment] 2016-05-02 10:08
I've seen this warning as well and I'm assuming the fix isn't merged into the released version yet. In the meantime, I have a question: I'm using React, which can tell when changes have taken place to the data. Is it just as performant to call `.render()` every time a change is observed? Or is the `observeChanges: true` approach more efficient?

**Comment by budnix** [comment] 2016-05-06 08:05
@timwis Yes, fix was merged into develop and it is waiting for release. About your question: I think that both approaches are correct. Looking into `ObserveChanges` [code](https://github.com/handsontable/handsontable/blob/master/src/plugins/observeChanges/observeChanges.js#L92) Handsontable is re-render on every detected data change the same as you are doing it manually way. 

Problem lays in `ColumnSorting` plugin which internally enables `ObserveChanges` (even when you set `observeChanges: false` https://github.com/handsontable/handsontable/issues/2688) which can cause a double re-rendering when you want to call `.render()` manually. In this case I suggest to rely on Handsontable internal detecting system.

**Closed** 2016-05-23 10:20 UTC
Labels: Answered
