### ISSUE TITLE
Rendering issue on column udpate with updateSettings

### ISSUE THREAD

**Issue by varun-dev** [handsontable/handsontable#3770] opened 2016-09-22 15:46 UTC
Hi,

I need to hide and show columns in my view. When I call update settings with new column list, I see some rendering issues.

Here is a fiddle
http://jsfiddle.net/34grf5qs/2/

step 1 - removes a column from the table
step 2 - calls render on the instance in a hope that the columns widths and the number of rows in the viewport will be recalculated but it doesn't

Can you think of any work around to fix this ??

Thanks
Varun

**Comment by AMBudnik** [comment] 2016-09-23 11:16
I @varun-dev 
Can you explain a little more how you would like the columns to recalculate their width? What the end result should look like? Currently only width settings in your table refers to `width: 500`

**Comment by varun-dev** [comment] 2016-09-23 23:46
Hi, 

Did you notice the issue in my demo? 
There are two buttons in the demo below the table labeled Step 1 and Step 2.
When you will press the first button, you will the alignment issue and wrong column widths
When you will press the second button, you will see that the column widths are calculated but the number of rows in the viewport are wrong.

Thanks

**Comment by AMBudnik** [comment] 2016-09-27 07:32
I think that here we may have 2 bugs not only one.
Thanks for sharing @varun-dev

**Comment by varun-dev** [comment] 2016-09-27 09:28
Yes there are two bugs

1. The column resize on updating columns. As a result of wrong column resize, the row height gets messed up.
2. The 2nd issue is related to the first issue of row height getting messed up and ends up rendering only those rows which were already in the viewport.

**Comment by AMBudnik** [comment] 2016-09-27 10:17
I've tried to check if we can do something about any of this two unwanted behaviors but unfortunately I haven't found any solution yet.

**Comment by varun-dev** [comment] 2016-10-11 13:43
Please find me a workaround for this. My project soon gong live :(

**Comment by AMBudnik** [comment] 2016-10-12 12:34
Hi @varun-dev did you try to simplify the example? It usually helps to isolate the issue

**Comment by varun-dev** [comment] 2016-10-13 16:06
I don't understand what you mean?
In my project, we want show and hide columns for which I do column update using updateSettings()
Step 1 of above demo is what I am doing
Step 2 of above example was a solution I was trying to implement to fix it and found out that there was a bug in that too

**Comment by AMBudnik** [comment] 2016-10-24 11:38
hi @varun-dev 
unfortunately I wasn't able to find a workaround. However the issue is marked as a bug to be checked by our developers.

**Comment by koolmoo** [comment] 2017-05-02 23:15
Unfortunately, I am experiencing the same issue. While the workaround @raethlo suggested works for rendering the correct number of rows, it does not fix the issue of a miscalculated scroll height for the viewport.

When I scroll to the bottom of the table, there is sometimes extra white space below the last row. If I scroll back to the top and then back down, the scroll height is calculated correctly and the end of the scroll bar aligns with the last row.

I've tried programmatically scrolling the viewport down (several times) and back up, but it only works if there's enough time for the table to recalculate between each scroll down. Here's the code I tried nonetheless:

`var scrollWindow = $("#tableName div.wtHolder")[0];
scrollWindow.scrollTop = scrollWindow.scrollHeight;
scrollWindow.scrollTop = scrollWindow.scrollHeight;
scrollWindow.scrollTop = scrollWindow.scrollHeight;
scrollWindow.scrollTop = 0;`

Is this bugfix on the roadmap somewhere?

**Comment by wojciechczerniak** [comment] 2019-09-26 13:35
Updated demo `1.15.0`: https://jsfiddle.net/5vnkdzor/
Latest release `7.1.1`: https://jsfiddle.net/t8sbv573/
With `8.0.0-rc`: https://jsfiddle.net/t8sbv573/1/

Unfortunately doesn't work. I hoped that recent `loadData` fix would help here. 

But it's weird that additional `render` can break the output, while `updateSettings` rerendered table correctly @wszymanski , we might have missed something?

**Comment by AMBudnik** [comment] 2020-05-21 08:40
In 8.0.0-beta2-rev6 the example http://jsfiddle.net/AMBudnik/6y50qmh9/ after steps 1, 2 shows all the rows.


> Yes there are two bugs
> 
> 1. The column resize on updating columns. As a result of wrong column resize, the row height gets messed up.
> 2. The 2nd issue is related to the first issue of row height getting messed up and ends up rendering only those rows which were already in the viewport.

Both of those issues aren't replicable in the newer version.

**Comment by wojciechczerniak** [comment] 2020-05-21 09:55
@AMBudnik Should we add it to the releases then?

**Comment by AMBudnik** [comment] 2020-05-21 10:00
@wojciechczerniak I'm waiting for @aninde test on that topic and then **yes**, if she confirms we will add it to the 8.0.0 epic 👍

**Comment by AMBudnik** [comment] 2020-05-29 12:15
Hi @varun-dev we've just pushed a new revision (10th) where we see a huge improvement http://jsfiddle.net/AMBudnik/qpg04utm/

**Comment by AMBudnik** [comment] 2020-07-16 09:54
Hi @varun-dev 

I have good news! We've just released 8.0.0-beta2 that fixes the following issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

Can you check it, please? All feedback's appreciated. Thank you for your input.

@raethlo @koolmoo does it work for you as well?

**Comment by AMBudnik** [comment] 2020-08-06 08:08
Hi @varun-dev here's the last update for this issue (hopefully) - it is officially solved in v 8.0.0.
I'd be grateful for your feedback.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases

**Closed by AMBudnik** 2020-08-06 08:08 UTC
Labels: Core: alignment/height/width, Type: Bug
