### ISSUE TITLE
Removing a row from the data set with sorting on renders a blank row in place of actual row

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#5609] opened 2018-11-23 03:08 UTC
### Description

If you remove a row from the data source with sorting on it will render a blank row where an actual row is meant to be. It seems to be that in the example case the data gets removed from the source data fine which makes it 9 in length but the cell meta does not get updated which means that there are still 10 cell meta objects and one of them has an incorrect `row` property which renders in null values since it doesn't exist in the data.

### Steps to reproduce

1. Add `columnSorting` option
2. Remove a row from the data
3. Render

### Demo

http://jsfiddle.net/ksmr16dn/

### Your environment
* Handsontable version: 6.0.1
* Browser Name and version: Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2018-11-23 07:15
Thank you for reporting @jeremy-smith-maco

**Comment by AMBudnik** [comment] 2018-11-29 08:48
>  (without observeChanges disabled) 
if you enable sorting the `observeChange` should also be enabled. We had a discussion about this topic not so long time ago. Not sure if any changes were made though.

**Comment by jeremy-smith-maco** [comment] 2018-11-29 22:12
We currently use sorting without observeChanges on in our project and nothing seems to be wrong. Previously when we did this I think the vertical scrolling failed but it works fine now. We turned it off because of the memory leak issue.

**Comment by wojciechczerniak** [comment] 2018-12-20 15:33
> Not sure how they are tracked or anything.

That was the purpose of `observe-changes` plugin. 

When you modify `sourceData` through `Array.splice` our options to notice the change are limited. One of them was to observe the data for changes (aka `observe-changes`), which wasn't fully implemented. On the other hand we've got various hooks ie. `afterRemoveRow` which are recognized and handled by most of our plugins. So when you call our API `.alter('remove_row', ...)`, instead of modifying data yourself, plugins will be notified about the change and the nature of it so they can recalculate and refresh all meta.

I wouldn't mark this as a bug either. If `data` is altered outside of Handsontable API then the developer should be responsible for updating all connected meta data. Without `observe-changes` it works as intended.

**Comment by jeremy-smith-maco** [comment] 2018-12-20 22:12
Even with the observe changes plugin enabled it still displays the blank row but I guess that's because it isn't fully implemented as you said.

One would assume that when the `render()` happens it would check the data and detect that the length of the array has changed therefore it needs to do something else? 

Like if I have `observeChanges` off and I edit a cell and call `render()` it detects that I have altered the source data directly and displays the correct value be. Or even adding a new row it detects that (although the row header doesn't get generated in the example). That's why it seems like a bug. If it can detect changes and added rows without `observeChanges` or with it for that matter it should be able to detect that a row has been removed and take appropriate action when the table is re-rendered.

That's just what I would expect from my perspective given the behaviour of the other actions. I mean we have a workaround in our code but it's a bit ugly and would be easier if Handsontable just picked up on the removed row and rendered it correctly.

**Comment by wojciechczerniak** [comment] 2019-01-07 14:16
That's true. It seems like a bug because it's mostly working. Unfortunately it isn't. Adding a new row have less side effects or they are harder to notice, but meta is not updated either.

`render()` doesn't know which row was added or removed. It would have to take `data` as is and apply all the filters and sorting every cycle, an expensive solution. That's why `observe-changes` has `json-patch` as a dependency, to watch the changes and find the difference to update them only on change. Still not the most efficient way. Thanks to you, a it's little better now. 

But we want `render()` to be as fast as possible, so all the `data` should be already pre-processed and ready. The best approach here is to talk to the Handsontable API directly and precisely say what and when should change with `.alter('remove_row, ...')` method. All plugins will listen for an event and update the meta. No watching, no diffing, no magic.

I see your point. It would be great to meet those expectations but I'm afraid we've reached the JS limitations here (it's impossible to watch array for changes efficiently, ie. Vue.js had to implement `Vue.set()` method for arrays) and `observe-changes` isn't a good solution as we already know it. 

Can I ask why won't you use Handsontable API to alter the data? Is it because it was mostly working the other way or we're missing something in our APIs? Does it work with `hot.alter('remove_row', 1)`: http://jsfiddle.net/ay2mdgqf/ as expected?

**Comment by jeremy-smith-maco** [comment] 2019-01-07 22:15
Well we didn't use that because it was mostly working in our current implementation. We have some diffing logic that goes through the current data set and a new data set and removes the row from the current data set if we notice it is no longer in the new data set. We also update data and add new rows  and just expect it to reflect in the table which works except for the removing rows so just assumed it was a bug.

We could probably store which rows need deleting and then do it using the API which would fix it, just requires refactoring our code to do so. It just seemed like it wasn't working as intended but I suppose as you just explained it's just a limitation of JS for the library.

**Comment by wojciechczerniak** [comment] 2019-01-08 12:55
And using the API is future proof. If anything changes on how we update meta your implementation shouldn't change. I will mark this issue as WontFix since we're not proud of `observe-changes` and we should encourage using our API.

Thanks for the insight about your use case and expectations. They were very helpful. I think we have some work to do on explaining those limitations in our documentation.

**Closed by wojciechczerniak** 2019-01-08 12:55 UTC
Labels: Plugin: column sorting, Plugin: observe changes, Type: Bug
