### ISSUE TITLE
[Bug]: Cannot open filter/dropdown menu of last column if it is very large

### ISSUE THREAD

**Issue by gl-aagostino** [handsontable/handsontable#10612] opened 2023-11-27 17:25 UTC
### Describe the bug

I have a table that requires horizontal scrolling (using stetchH="all"). The last column itself is also super wide, maybe 100s of pixels. Now when I go to click on the dropdown button for that header, it unfortunately re-centers the entire column and therefore makes it impossible to select.

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/gLwuxmke/

### Handsontable version

13

### Framework version

React

### Your environment

Chrome, Windows

**Comment by adrianszymanski89** [comment] 2023-11-28 09:20
Hi @gl-aagostino 

Thank you for contacting us and reporting this issue. I'll report it internally for further investigation and update you once the fix gets on our roadmap.

**Comment by vzotov** [comment] 2023-11-29 14:51
I found similar bug: the links does not work also (seems all clicks are prevented), but I think it caused by the same problem

https://jsfiddle.net/7jes49g0/

The column content does not have to be long. Seems the behavior here is that if we click on partially visible column HOT scrolls to the start of the column to make this column fully visible, but in case when column width is larger than the table size, the column will be still partially visible after scrolling and clicks are still ignored. Hope it will help to track down the issue.

And there is more. If I fix columns to the left, leaving just that long column in the scrollable area - NONE of the links will work

https://jsfiddle.net/7jes49g0/1/

**Comment by adrianszymanski89** [comment] 2023-11-29 15:03
Hi @vzotov 

Thank you for your input and additional examples. Indeed, the reason for this behavior seems to be the same as in the first case.

**Comment by adrianszymanski89** [comment] 2023-12-01 09:42
Hi @vzotov 

Thank you for your input. Both reported issues are connected to recalculating the table's dimensions. That's, in general, a known issue for us and is broadly discussed here: https://github.com/handsontable/handsontable/issues/5769.

**Comment by AMBudnik** [comment] 2024-03-06 10:47
Hi @gl-aagostino @vzotov 

I have a good news. We just fixed the corresponding issue with PR https://github.com/handsontable/handsontable/pull/10724 in Handsontable v14.2.0.

I will close this issue as solved. However, if you find anything that does not work, please let us know.

ps. here you can read more about the changes presented in this version https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-2-0

**Closed by AMBudnik** 2024-03-06 10:47 UTC
Labels: bug, Core: Alignment / height / width, Dropdown menu, Reported
