### ISSUE TITLE
[7.2.0] The cell meta is being retrieved using the wrong coordinates

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6703] opened 2020-02-11 14:17 UTC
### Description

The cell meta is being retrieved using the wrong coordinates. Hence, the cell meta manager throws an assert exception `Assertion failed: Expecting an unsigned number.`. I think that this only happens when the bottom overlay is enabled.

### Steps to reproduce

1. Apply the filtering on column `B` and using "filter by value" deselect all checkboxes (click on the "clear" link) and accept an action;
2. Open again the dropdown menu under column `B` and check the first value from the "filter by value" component and accept the filter;
3. As a result, the assert exception is thrown (`Error: Assertion failed: Expecting an unsigned number.`).

### Demo

https://jsfiddle.net/budnix/updet50k/

### Your environment
* Handsontable version: `develop` branch (as of February 11, 2020)
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment] 2020-02-12 09:00
I just wanted to add a video for easier reproduction
![sample](https://user-images.githubusercontent.com/10757813/74318573-cfc0ef00-4d7d-11ea-9882-c867e3c33196.gif)
We can see that the first step is also removing a bottom border of column headers.

We get
![Zrzut ekranu 2020-02-12 o 09 56 59](https://user-images.githubusercontent.com/10757813/74318801-2fb79580-4d7e-11ea-94de-67f7defe40b2.png)


instead of
![Zrzut ekranu 2020-02-12 o 09 57 23](https://user-images.githubusercontent.com/10757813/74318794-2d553b80-4d7e-11ea-9543-0c96ffdfe93b.png)

**Comment by aninde** [comment] 2020-06-16 15:30
Demo from original report is broken, so here is a new one with curenty stable `v7.4.2` https://jsfiddle.net/aninde/fnht6uzs/
**Result of reprodution on `7.4.2`**
broken table and some errors in console.
<img width="517" alt="Screenshot 2020-06-16 at 17 24 07" src="https://user-images.githubusercontent.com/30186818/84794583-b7483600-aff6-11ea-8974-78a1c1422152.png">


I'm glad to see that this issue is **solved by `8.0.0-beta2-rev14`** 
https://jsfiddle.net/aninde/12ojsmxL/ we received proper rows without errors in console
![rev14-fix](https://user-images.githubusercontent.com/30186818/84794724-e52d7a80-aff6-11ea-82ae-d12a1d1b1716.gif)

**Comment by wojciechczerniak** [comment] 2020-06-17 12:51
Removing `[8.0.0]` tag from the title as this bug existet prior v8 and we should consider it solved in the next release notes.

**Comment by aninde** [comment] 2020-06-17 14:12
Adding `[7.2.0]` tag to the title, because it is the latest version in which this error can be reproduced. 
https://jsfiddle.net/9faox28k/ - (bugsy) demo `v7.2.0`

**Comment by aninde** [comment] 2020-07-20 10:45
This issue is still solved with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/q9rw3nkp/. There is no error in the browser's console and headers render correctly. 

![fixed](https://user-images.githubusercontent.com/30186818/87929500-ca7f7300-ca86-11ea-9980-6072c701b44b.gif)

**Comment by AMBudnik** [comment] 2020-08-06 07:37
Issue officially fixed in v 8.0.0
Updated demo https://jsfiddle.net/5xL1a9kb/

**Closed by AMBudnik** 2020-08-06 07:37 UTC
Labels: Core: walkontable, Type: Bug
