### ISSUE TITLE
Filter as you type

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/handsontable#5030] opened 2018-04-13 15:26 UTC
### Description
The default behavior of `filter_by_value` is that when you type in the search value it does not filter anything. You have to press "Clear" first, then search, then filter. I know this is the behavior of Google Sheets but it has come up in user testing as confusing. Excel, by contrast, will filter out items immediately as you type -- basically it automatically deselects items that don't match what you've searched for. Is there a way to modify the `filter_by_value` to behave this way to implement a `filter_by_search` that does this?

### Steps to reproduce

1. Turn on `filter_by_value`
2. Open dropdown, enter search term, press OK
3. No filter is applied

### Demo

http://jsfiddle.net/upo1uLgs/

### Your environment
* Handsontable version: pro-1.18.1
* Browser Name and version: Chrome 65
* Operating System: MacOS High Sierra

**Comment by AMBudnik** [comment] 2018-04-16 07:36
Hi,

yes, that is an intended behavior as all the data is visible in the table they are also visible/checked in the `filter_by_value` list. 

If you would like to clear the values here's how to do it http://jsfiddle.net/handsoncode/3gz93neb/ but still, you'll need to check the checkbox of a searched/result query.


![3gif](https://user-images.githubusercontent.com/10757813/38795684-4cc30b6a-4159-11e8-83de-9b1d82bbb1f5.gif)

I will add this topic to the `feature request` list. Thanks for sharing the idea @aaronbeall

**Comment by aaronbeall** [comment] 2018-04-16 13:42
Thanks. That's pretty close but if you don't interact with the filter and press OK then it actually clears everything. 

The desired behavior would be like Excel:
![img](http://g.recordit.co/iXu7quXWm5.gif)

Even if it didn't update the filter live and you still had to press OK to apply the filter, the main difference is that if you type a search value it automatically down-filters to items that match the search value. This is a lot easier to use that the current implementation, which we got confused feedback from users during testing (users who are used to Excel).

It'd be awesome if there was an option that made the `filter_by_value` to act this way.

**Comment by AMBudnik** [comment] 2018-04-17 08:57
That is definitely a cool idea. There's something similar here http://jsfiddle.net/rjb9p8b3/ when we use column headers.

**Comment by AMBudnik** [comment] 2018-12-07 14:52
As mentioned in the https://github.com/handsontable/handsontable/issues/5424 I am temporarily closing this issue

**Closed by AMBudnik** 2018-12-07 14:52 UTC
Labels: PRO: filtering, Type: Feature
