### ISSUE TITLE
vue wrapper handsontable production build is not displaying table

### ISSUE THREAD

**Issue by subbiahbb** [handsontable/handsontable#7294] opened 2020-09-26 02:11 UTC
### Description

its workign in development mode but after build is not displying table
throwing error:
vue.runtime.esm.js:1888 DOMException: Failed to execute 'insertBefore' on 'Node': This node type does not support this method.

### Steps to reproduce

1. npm run build
2.
3.

### Your environment
* Handsontable version:8.0.0
* Browser Name and version: chrome
* Operating System: ubuntu18.o4
* Vue wrapper version: 5.0.1
* Handsontable version: 8.0.0
* vuejs :  2.6.11

**Comment by SmallJune** [comment] 2020-09-27 03:14
I have the same problem
when I use 
Handsontable version:7.4.2
@handsontable/vue version:4.1.1

the  version:8.0.0 maybe a problem @subbiahbb

**Comment by subbiahbb** [comment] 2020-09-28 09:04
> I have the same problem
> but when I use
> Handsontable version:7.4.2
> @handsontable/vue version:4.1.1
> is ok
> 
> the version:8.0.0 maybe a problem @subbiahbb

with this not working in dev also
error:
element.js?5cd0:579 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

**Comment by AMBudnik** [comment] 2020-09-28 09:14
Hi @SmallJune @subbiahbb 

Do you use the same settings with webpack's minimize https://github.com/handsontable/vue-handsontable-official/issues/188 ?

**Comment by subbiahbb** [comment] 2020-09-28 09:23
i tried that also even not working for me

**Comment by AMBudnik** [comment] 2020-09-28 11:53
Hi @subbiahbb 

we've 
1) created a project using CLI https://cli.vuejs.org/guide/creating-a-project.html#vue-create 
2) installed Handsontable using https://handsontable.com/docs/8.0.0/frameworks-wrapper-for-vue-installation.html
3) run `npm run build`
4) run `npm run serve`

and it is working as expected.

It has been tested on macOS Catalina and Windows 10.

![image](https://user-images.githubusercontent.com/10757813/94428945-db88e680-0191-11eb-83a5-46047c8bd5cf.png)

**Comment by wojciechczerniak** [comment] 2020-09-28 12:40
Duplicate of https://github.com/handsontable/vue-handsontable-official/issues/190 ?

**Comment by AMBudnik** [comment] 2020-09-29 07:02
@wojciechczerniak #190 and #188 are both related to the use of 'minimize'. @subbiahbb already tried it.
@SmallJune how about you?

**Comment by AMBudnik** [comment] 2020-10-05 07:25
Hi @subbiahbb @SmallJune are you able to run the build using the steps I've mentioned above?

**Comment by mormone** [comment] 2020-10-06 23:50
> Hi @subbiahbb
> 
> we've
> 
> 1. created a project using CLI https://cli.vuejs.org/guide/creating-a-project.html#vue-create
> 2. installed Handsontable using https://handsontable.com/docs/8.0.0/frameworks-wrapper-for-vue-installation.html
> 3. run `npm run build`
> 4. run `npm run serve`
> 
> and it is working as expected.
> 
> It has been tested on macOS Catalina and Windows 10.
> 
> ![image](https://user-images.githubusercontent.com/10757813/94428945-db88e680-0191-11eb-83a5-46047c8bd5cf.png)

It is NOT working here as well. I tried it with exact this settings.
`npm run build` is working
 `npm run serve` is working
But running on a server I get this message as well: DOMException: Failed to execute 'insertBefore' on 'Node':

**Comment by AMBudnik** [comment] 2020-10-07 08:04
Would you be able to share the project zipped, @mormone ? I'd like to run it on my device.

**Comment by subbiahbb** [comment] 2020-10-07 08:08
> Hi @subbiahbb @SmallJune are you able to run the build using the steps I've mentioned above?

working fine after follwed this https://github.com/handsontable/vue-handsontable-official/issues/188

**Comment by AMBudnik** [comment] 2020-10-08 11:06
Hi @subbiahbb @SmallJune we've just released v5.1.0 that solves the issue https://github.com/handsontable/vue-handsontable-official/issues/188 Please let me know if it works well for you.
@mormone do we have any updates here?

**Comment by AMBudnik** [comment] 2020-10-13 11:38
If anyone would have the same issue with the newest wrapper for Vue please send me a message at support@handsontable.com

**Closed by AMBudnik** 2020-10-13 11:38 UTC
Labels: Status: Answered
