### ISSUE TITLE
[Bug]: How can the handsonTable component freeze columns on both sides

### ISSUE THREAD

**Issue by flamingoTwoWings** [handsontable/handsontable#10951] opened 2024-04-28 08:19 UTC
### Describe the bug

So far I have only found the fixedColumnsStart and fixedColumnsLeft properties. Now I want to implement fixed columns on the left and right sides of the table. It is relatively common to have fixed columns on both sides of the table, for example, the column showing the project name on the left needs to be fixed, and the column showing the operation on the right needs to be fixed

### Video/Screenshots

![image](https://github.com/handsontable/handsontable/assets/74237022/2075be53-65e6-4edb-a4c1-56d7cec05310)

### Handsontable version

14.0.0

### Your environment

谷歌浏览器（ 124.0.6367.60） windows操作系统

**Comment by AMBudnik** [comment] 2024-04-29 08:47
Hi @flamingoTwoWings 

The `fixedColumnsRight` option is not yet available. To track progress on this functionality please visit the main thread at https://github.com/handsontable/handsontable/issues/1428.

**Comment by wiexin** [comment] 2024-05-08 07:33
@AMBudnik I've gone through the issues and found that this problem has been raised by several people over the past few years. What are the considerations behind the official's decision not to support this feature?

**Comment by AMBudnik** [comment] 2024-05-08 08:36
Hi, @wiexin, we did not make a decision not to support the fixed column on the right side. We accepted the idea for the feature request and the issue is in the Backlog. It just hasn't been prioritized.

**Comment by AMBudnik** [comment] 2024-06-06 09:41
I will close this issue for now and will update it once the https://github.com/handsontable/handsontable/issues/1428 is ready.

**Closed by AMBudnik** 2024-06-06 09:41 UTC
Labels: Status: Answered
