### ISSUE TITLE
The HiddenColumns plugin inconsistently interprets column indices

### ISSUE THREAD

**Issue by wingzero00W0** [handsontable/handsontable#5909] opened 2019-03-24 06:50 UTC
### Description
The `HiddenColumns` plugin inconsistently interprets column indices. Most of the time it handles column indices as _visual_ indices, but sometimes it treats it as a _physical_ index.

Due to this inconsistency, there are at least 2 bugs when used in conjunction with the `ManualColumnMove` plugin:
1. The incorrect column appears to be hidden
2. The data of an entire column becomes blank

### Analysis
Firstly, we need to establish that `HiddenColumns.hiddenColumns` ([src](https://github.com/handsontable/handsontable/blob/7.0.0/src/plugins/hiddenColumns/hiddenColumns.js#L85)) is an array of _visual_ indices (as opposed to _physical_ indices). This can be shown by the various API documentation for `showColumn()` ([doc](https://handsontable.com/docs/7.0.0/HiddenColumns.html#showColumn)) and  `hideColumn()` ([doc](https://handsontable.com/docs/7.0.0/HiddenColumns.html#hideColumn)) etc.

In the method `HiddenColumns.isHidden()` ([src](https://github.com/handsontable/handsontable/blob/7.0.0/src/plugins/hiddenColumns/hiddenColumns.js#L250)), the code utilizes `HiddenColumns.hiddenColumns` as _physical_ indices, which is incorrect. The _visual_ column index should be used instead. 

In the method `HiddenColumns.onAfterGetCellMeta()` ([src](https://github.com/handsontable/handsontable/blob/7.0.0/src/plugins/hiddenColumns/hiddenColumns.js#L335)), `HiddenColumns.isHidden()` is invoked with a _physical_ index when the method is expecting a _visual_ index (since the optional parameter `isPhysicalIndex` defaults to `false`). Also note that just [a couple lines prior](https://github.com/handsontable/handsontable/blob/7.0.0/src/plugins/hiddenColumns/hiddenColumns.js#L331) the same method is used with a _visual_ index.

### Steps to reproduce

1. Use `ManualColumnMove` plugin to reorder columns
2. Use `HiddenColumns` to hide a column

### Demo
https://jsfiddle.net/vndocfLs/6/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Firefox 65
* Operating System: MacOS

**Comment by wingzero00W0** [comment] 2019-03-24 07:06
I have no verified this, but perhaps a similar bug resides in the `HiddenRows` plugin

**Comment by AMBudnik** [comment] 2019-03-26 10:11
Hey @wingzero00W0 

thank you for investigating this case. We have a[ list of issue related to row and column hiding functionality](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3AHiding+label%3A%22Type%3A+Bug%22).

This issue sounds like it fits into the description https://github.com/handsontable/handsontable/issues/5598. Doesn't it? 
Maybe there are some other issues on the list that are harmed by the same corrupted index logic. Nevertheless, one of our programmers is currently working on a complex idea of index mapping. After adding the new logic we'll be able to get rid of the misleading indexes translation. That's why I highly encourage to check this subject out https://github.com/handsontable/handsontable/issues/5112 and waiting for our next release.

**Comment by wingzero00W0** [comment] 2019-03-26 10:39
You're right, #5598 is probably demonstrating the same root problem that I am reporting. Sorry I'm still fairly new to this and didn't realize there's already a list of issues reported regarding the same/similar problem.

I would like to point out, though, that my jsfiddle shows an additional display bug with the column headers that is not shown in #5598. Though I'm sure a comprehensive fix for #5598 would also catch it.

**Comment by AMBudnik** [comment] 2019-03-26 10:46
Can I ask you to mention the missing case in #5598 (perfectly with a .gif)? Then we'll have the two similar cases under one address and be able to check them one after another without additional exploration.

**Comment by AMBudnik** [comment] 2019-09-17 09:21
#### Previously (`7.1.1.`)

![image](https://user-images.githubusercontent.com/10757813/65028474-65c22c00-d93c-11e9-9113-549c868893b5.png)

#### Test on 8.0.0-rc2
https://jsfiddle.net/handsoncode/vgpzj18h/
![image](https://user-images.githubusercontent.com/10757813/65028689-b89be380-d93c-11e9-8b08-0fd466863be9.png)

In both cases some borders are gone 🐛 
And in 8.0.0.-rc1 data from the first column is empty, while we should expect `2` in first (left) column as a value. Previously we were missing `3` in the right column.

Unfortunately, we need to reopen this topic. 
As the behavior changed in 8.0.0-r1 I'm attaching the `regression` label.

**Comment by wojciechczerniak** [comment] 2019-09-17 09:26
Hidden Column #6179 are not yet merged to 8.0.0-rc but this should be added to our checklist.

**Comment by AMBudnik** [comment] 2020-05-08 10:23
Whatever I do with the example in 8.0.0-beta2-rev2 the issues are gone https://jsfiddle.net/cutg61jp/

*   columns are not blank
*   moving columns works well
*   all borders are present

I call it **solved**.

**Comment by AMBudnik** [comment] 2020-07-16 09:29
Hi @wingzero00W0 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment] 2020-08-06 10:20
Hi @wingzero00W0 

here's a demo updated to v 8.0.0 https://jsfiddle.net/grxak298/1/. We are glad to announce that the issue is fixed.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. I hope that the amount of work that we put on the v8 will help you to improve your project.

**Closed by AMBudnik** 2020-08-06 10:20 UTC
Labels: Hiding, Regression, Type: Bug
