### ISSUE TITLE
Numeric Type Does Not Work with Expected to Decimal

### ISSUE THREAD

**Issue by lucashtc** [handsontable/handsontable#5569] opened 2018-11-06 19:31 UTC
### Description
When using culture pt_BR, values ​​after comma are rounded

### Demo
[Demo](https://jsfiddle.net/j5z9uhtL/1/)

### Your environment
* Handsontable version: 6.1.1
* Browser Name and version: Google Chrome 69.0.3497.81
* Operating System: Windows 10

One detail is that the default pt-BR uses "," to separate decimal places

**Comment by lucashtc** [comment] 2018-11-06 20:29
One detail is that the default pt-BR uses "," to separate decimal places

**Comment by AMBudnik** [comment] 2018-11-09 12:11
Thank you for sharing even when I use this pattern `pattern: '$0.0,000',` and place more decimal places in my data I still have only 1 decimal (rounded) place.

**Comment by lucashtc** [comment] 2019-05-15 12:05
Hello,
After some analysis I got a certain success in the format,
using more updated versions the number appears with $ with the decimal places,
But when copying the number and paste the number appears in the format not expected.
[New Exemple](https://jsfiddle.net/lucas_henrique/qatv1jmg/2/)
If I change the format of `{
        data: 'price_usd',
        type: 'numeric',
        numericFormat: {
          pattern: 'R$0,0.00', // Changed
          culture: 'pt-BR'
        },
        allowEmpty: false
      },`


for `{
        data: 'price_usd',
        type: 'numeric',
        numericFormat: {
          pattern: 'R$0,0,00', // Changed
          culture: 'pt-BR'
        },
        allowEmpty: false
      },` copy and paste it will appear the correct value, but the view of it in the handsontable is incorrect .

**Comment by lucashtc** [comment] 2019-05-15 12:07
When editing the line the format is also incorrect

**Comment by AMBudnik** [comment] 2019-05-15 12:36
Thank you for doing the investigation and setting up an example.

**Comment by aninde** [comment] 2020-02-07 14:22
@lucashtc this issue will be fixed with new release of 7.4.0 v. Where we updated numbro. 
Brazilian real will render correctly.
https://jsfiddle.net/aninde/5qpexj3b/

**Comment by aninde** [comment] 2020-02-12 10:52
Still fixed on updated `7.4.0 v.` https://jsfiddle.net/aninde/nL16epx0/

**Comment by AMBudnik** [comment] 2020-02-12 12:51
Hey @lucashtc 

the issue is gone in v 7.4.0 - published 10 minutes ago. Please update and share feedback if possible :-) Thanks!

**Closed by AMBudnik** 2020-02-12 12:51 UTC
Labels: Cell type: numeric, Type: Bug
