### ISSUE TITLE
UpdateSettings works very slow for hiddenColumns and Rows

### ISSUE THREAD

**Issue by arrdev** [handsontable/handsontable#4381] opened 2017-07-07 13:09 UTC
### Description
UpdateSettings works very slow on certain conditions:
- significant amount of data (100k rows * 50 columns, some of which are hidden)
- the following plugins are used: hidden columns, trim rows, filters
- updating anything (e.g. height of the sheet) takes 10-15 seconds.

Destroying and recreating the sheet with the same data takes significantly less time (up to 3 seconds).

### Your environment
* Handsontable version: latest pro
* Browser Name and version:  Google Chrome 58.0.3029.110 (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2017-07-07 13:31
Hi @arrdev 

100k rows is a pretty large dataset. Have you experienced the lower performance only in the latest version or it has been like this since you stated to test it?

**Comment by arrdev** [comment] 2017-07-07 14:23
We started development using handsontable only recently, so I am not sure about this being version related.

**Comment by AMBudnik** [comment] 2017-07-10 10:52
I think you won't be able to see differences between latest versions. However, the bigger change would be to load data with server-side pagination.

**Comment by arrdev** [comment] 2017-07-12 10:17
Hi @AMBudnik 
This issue with update settings happens only with big data sets.
Are there any workarounds to change sheet height without calling updateSettings?
We need to have an ability to update height dynamically.

**Comment by AMBudnik** [comment] 2017-07-12 12:33
Hi @arrdev 
unfortunately, only `updateSettings `is able to change table height.

**Comment by arrdev** [comment] 2017-07-12 12:41
Hi @AMBudnik 
Thanks for the reply.
I am now trying to set the height via jQuery and then render sheet. Seems like it is working and performance is great. What are the possible issues with this approach?

**Comment by AMBudnik** [comment] 2017-07-12 12:44
Hi @arrdev 

Nice! I am glad you've found a solution.

I haven't tried it but if you do not see any issues while scrolling and editing data (and moving rows if you use it) you shouldn't experience any other bugs.

**Comment by jeanmarc78** [comment] 2018-07-20 16:21
hello,
i reproduce a similar behavior 
http://jsfiddle.net/jeanmarc/7mh8ow59/27/

![image](https://user-images.githubusercontent.com/11042160/43013485-5414cb98-8c49-11e8-9ebd-c460866faba0.png)


if i remove comment on hidden settings, it take 16 seconds

![image](https://user-images.githubusercontent.com/11042160/43013558-91a3aa4c-8c49-11e8-8b5d-99585fda802c.png)



regards
jm

**Comment by AMBudnik** [comment] 2018-07-23 11:51
Thank you @jeanmarc78 
you're right - the difference it noticeable.

**Comment by AMBudnik** [comment] 2018-08-14 06:36
Hi @RishabhRanjanKesarwani haven't we start a discussion on this subject on our forum?

**Comment by nilsm0hr** [comment] 2018-12-12 14:39
Is there any progress made on this one? its a fairly annoying one for us. 

Or is there a recommend workaround?

**Comment by RishabhRanjanKesarwani** [comment] 2018-12-13 04:57
> Is there any progress made on this one? its a fairly annoying one for us.
> 
> Or is there a recommend workaround?

Hey @nilsm0hr!
Later, I found that formulas library was taking a lot of time. After I stopped using it, performance was improved drastically. This may be the problem with your app too.

**Comment by nilsm0hr** [comment] 2018-12-13 10:49
Hi @RishabhRanjanKesarwani  we are not using the formulas. I have a large dataset of maybe 50k x 10 or so and I just want to show and hide columns and apply a format to the data (just adjust the decimal places). So I am kinda stuck with a very basic example

**Comment by eason123deng** [comment] 2019-01-23 13:56
I have already left a comment in #5733, I'm just going to leave a similar comment just in case... After hiding a fair amount of columns, vertical scrolling becomes an issue because the DOM will be flooded with zero-width `th` elements. Please refer to the jsfiddle below for an example (in which 100 columns was hidden): http://jsfiddle.net/vh4mbz5n/

**Comment by AMBudnik** [comment] 2019-01-24 10:55
Thank you for sharing @eason123deng

**Comment by tkane2000** [comment] 2019-03-07 14:26
We've run into the same problem as @eason123deng Btw, adding more rows in your jsfiddle helps see the issue and note that horizontal scrolling is also effected.

Here are my findings (copied from #5839):

### Description
In large tables, with large groups of hidden columns, vertical and horizontal scroll performance is very choppy/janky.  For instance, if you have 100 columns and 10 - 60 are hidden, as you scroll to the right hot will stutter as it the hidden columns cross into the viewport and it will stutter continuously as you scroll vertically.

Note: the hiddenColumns plugin hides columns by setting their widget to 0, so each hidden column still has to be rendered by hot.  This is the the cause of the problem because if we set all columns to visible, performance improves, with the exception of being on a 4k monitor in which you can display a large number of columns at the same time at a high resolution.

I've played around with setting viewportColumnRenderingOffset and viewportRowRenderingOffset, but that hasn't solved the problem. Setting viewportColumnRenderingOffset to the full length of columns improves horiz scroll, but makes vertical scrolling a bit worse.  Setting viewportColumnRenderingOffset to auto and not setting viewportColumnRenderingOffset seems to be best, but as I said, not enough to fix the issue.

When scrolling vertically, we're seeing the following warning repeatedly in the console:
"[Violation] Forced reflow while executing JavaScript took 644ms"
It looks like this was brought up in Improve forced reflow and layout #3370, but was not resolved.

Major clients are complaining so we're hoping to fix it within the next 2 weeks.  With that in mind, if you have any suggestions for hacks please share!  For instance, is there a way to NOT render hidden columns while you're scrolling?

We're also interested in a longterm fix.

### Steps to reproduce
1. Go to https://jsfiddle.net/tkane2000/s1qc8gu3/17/
2. Scroll by dragging scroll bar horizontally and notice jankiness as the hidden columns next to column 13 come into view.
3. Scroll  horizontally so that column 13 in is view.  Scroll by dragging scroll bar vertically and notice jank.

Note: the problem is MUCH worse on our site probably because of custom rendering and the fact that the viewport can be bigger displaying more columns and rows than it can on jsfiddle.  I've tried disabling our custom renderers, etc.  We see a bit of improvement, but the problem still exists.  Unhiding all columns helps significantly.

### Demo

https://jsfiddle.net/tkane2000/s1qc8gu3/17/

### Your environment
* Handsontable version: "handsontable-pro": "3.0.0"
* Browser Name and version: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* Operating System: Mac OS, Mojave

Please investigate!

**Comment by AMBudnik** [comment] 2019-03-07 14:30
Thanks for copying @tkane2000

**Comment by tkane2000** [comment] 2019-03-07 14:36
Np!  Btw, to be clear, the issue I'm seeing is a bit different than the one mentioned by @jeanmarc78.  I'm seeing that the more hidden columns present in the viewport, the worse performance is.  For @jeanmarc78, the problem is caused by just turning on the hiddenColumns plugin.

**Comment by AMBudnik** [comment] 2019-03-07 14:50
The case is connected to the presence of the hidden columns in table calculations. That is a part of the divagations that we're doing in the eco-renderers topic. We're finding a way to skip those columns if after scroll/change they do not alter in any way.

**Comment by lohithmv019** [comment] 2019-08-19 14:46
@AMBudnik any timeline for fixing this issue?

**Comment by AMBudnik** [comment] 2019-08-20 08:52
Please track changes to #5751, as referenced by @wszymanski these two issues are connected  and #5751 is already in progress

**Comment by aninde** [comment] 2019-09-23 06:28
The first bug described here it is not fixed by the new `index mapper` (`8.0.0-rc1 `v.). 

**Demo**
forkedjeanmarc78 demo
 http://jsfiddle.net/aninde/r5qeuwos/ 8.0.rc2
Performance time without `hiddenColumns` - 43.636ms, with enabled plugin  16270.612ms

**Environment**
Handsontable version: 8.0.0-rc1
Browser version: Safari Version  12.1.2
MacBook Pro macOs Mojave ver. 10.14.6

**Comment by AMBudnik** [comment] 2020-05-08 07:42
I do not see any improvement with 8.0.0-beta2-rev1 http://jsfiddle.net/rf3pbckq/

![](https://user-images.githubusercontent.com/10757813/81383379-3b61f080-9110-11ea-9889-4fda7aa98bad.png)

**Comment by tkane2000** [comment] 2020-05-08 15:11
In my original fiddle: https://jsfiddle.net/tkane2000/s1qc8gu3/17/
If I turn the new jsfiddle console feature off, I can see the horizontal scrollbar.  At some point, as I scroll, it just stops trying to render the cells and the table is just white, but it's super fast!
I'm a bit confused though because I haven't updated the HT version.  I'm still including:
https://handsontable.com/docs/3.0.0/components/handsontable-pro/dist/handsontable.full.js

**Comment by AMBudnik** [comment] 2020-05-11 06:14
@tkane2000 Thank you for the feedback. 
Your original JSfiddle was made a year ago. If you do not dump the Handsontable version but demo works differently it might be a browser thing. When we provide changes we usually test those on the latest browser version. Can you update Handsontable to beta2 and show me how it works for you?

**Comment by AMBudnik** [comment] 2020-07-16 09:46
Hi @arrdev 

I have good news! We've just released 8.0.0-beta2 that fixes the following issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

@tkane2000 @lohithmv019 @eason123deng @nilsm0hr @RishabhRanjanKesarwani @jeanmarc78 

All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment] 2020-08-10 12:57
Hi @arrdev, @lohithmv019 @tkane2000 @eason123deng @nilsm0hr @RishabhRanjanKesarwani 

@jeanmarc78 your demo using v8.0.0 https://codesandbox.io/s/loving-grothendieck-2bp1g gives me result 0.05 - 0.09

Have you had time to test the `updateSettings` performance after updating to v 8.0.0? We just released it before the weekend. I have got great results with @jeanmarc78 's example ensuing me that the case can be closed as solved. 
All feedback is appreciated so feel free to leave a comment.

Release Notes https://github.com/handsontable/handsontable/releases/tag/8.0.0

**Closed by AMBudnik** 2020-08-10 12:57 UTC
Labels: Core: performance, Core: update settings, Hiding, Type: Change
