### ISSUE TITLE
persistentState not working after columnSorting is enabled

### ISSUE THREAD

**Issue by ereboucas** [handsontable/handsontable#2847] opened 2015-09-29 07:37 UTC
Hi guys,

using this simple example:

```javascript
$("#hot").handsontable({
  colHeaders: ['A', 'B'],
  data: [
    [1, 'C'],
    [2, 'E'],
    [3, 'A'],
    [4, 'B'],
    [5, 'D']
  ],
  manualColumnResize: true,
  persistentState: true
});
```

It works fine by saving columns width between page reloading.

But after adding columnSorting: true it does not get saved column widths anymore.

Can you help?

Tks!

**Comment by AMBudnik** [comment] 2015-09-29 07:59
Confirmed. [Demo](http://jsfiddle.net/63v3bj8L/3/) for this example.
`columnSorting: true` erases changed width made by `manualColumnResize: true`

**Comment by cgatesman** [comment] 2015-09-30 16:38
I'm seeing this problem, too, but I'm not using columnSorting.  I've debugged into the regression I'm seeing with 0.18.0 down to it breaking when you call `updateSettings()`.  If you ever call `updateSettings()` on your table, it will no longer use the persisted column widths.

You can see this behavior, here: http://jsfiddle.net/cgatesman/gnb00g8k/
If you comment out the updateSettings() call, it uses the persisted widths.

It looks like the problem stems down to the `updatePlugin()` implementation of `ManualColumnResize` is incorrectly clearing out the `manualColumnWidths`.

**Comment by AMBudnik** [comment] 2015-09-30 17:15
Thank you @cgatesman indeed `//hot.updateSettings(settings);` turns back on `persistentState`

**Comment by AMBudnik** [comment] 2016-06-09 12:56
Works as expected with Handsontable 0.25.1, demo: http://jsfiddle.net/7dozo368/
Columns and order stays the same.
I'm closing this issue but I would really appreciate your confirmation @cgatesman

**Closed by AMBudnik** 2016-06-09 12:56 UTC
Labels: Bug, Plugin: persistent state

**Comment by cgatesman** [comment] 2016-06-09 13:43
> I'm closing this issue but I would really appreciate your confirmation @cgatesman

This has not been fixed in 0.25.1.  I am still seeing the problem.  I've updated my sample to use 0.25.1, and the problem still occurs:

http://jsfiddle.net/gnb00g8k/4/

1. Make one of the columns wider.
2. Rerun...it should reload using the persisted manual column width, but it does not.
3. Comment out the `hot.updateSettings(settings)`
4. Rerun, and you'll find that it will use the larger persisted manual column width.

**Comment by AMBudnik** [comment] 2016-06-10 08:35
in your example .css and language file is 0.25.1 but the .js is 0.18.0 @cgatesman

**Comment by cgatesman** [comment] 2016-06-10 13:15
So it is!  Sorry about that!  Yep.  Looks good! 👍

**Comment by AMBudnik** [comment] 2016-06-10 13:17
Yep @cgatesman one issue less :)
