### ISSUE TITLE
[9.0.0+] Formula gets incorrect reference when data is sorted

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8242] opened 2021-06-18 07:51 UTC
### Description

Once we sort a column the formula that refers to any cell in that column uses physical row index instead of the visual index.

It's also worth mentioning that sorting of formulas that have been already defined did not work in pre v9 but in v9 it is fixed - that's the issue reported at https://github.com/handsontable/handsontable/issues/6336 

### Steps to reproduce

1. Sort column `B`
2. Type `=B1` in the `D1` cell

**Expected result**
![image](https://user-images.githubusercontent.com/10757813/122525654-bf77ee80-d019-11eb-9066-e1d9888daedf.png)

**Actual result**
![image](https://user-images.githubusercontent.com/10757813/122526035-272e3980-d01a-11eb-8d53-d23944269ef6.png)

### Demo

https://jsfiddle.net/handsoncode/vzak9gju/ 8.0.0 - works well
https://jsfiddle.net/handsoncode/tgqyr2j5/ 9.0.0 - gets the wrong reference 

### Your environment
* Handsontable version: 9+
* Browser Name and version: Chrome 91
* Operating System: Windows 10

_Inform Zen 26623_

**Comment by sequba** [comment] 2022-06-24 15:55
## My investigation

### Cause of the bug

Handsontable applies the sorting to data and updates the UI but does not "inform" HyperFormula about it. HyperFormula interprets cell addresses in the formulas as if there was no sorting.

### Recommended solution

If data contains at least one formula, use HyperFormula sorting feature instead of the default one; then read the data from HyperFormula and update Handsontable internal state and UI accordingly. HyperFormula updates all the addresses in the formulas properly. In my opinion, it is the only way to maintain data consistency between Handsontable and HyperFormula.

Relevant methods from HyperFormula API: [setRowOrder](https://handsontable.github.io/hyperformula/api/classes/crudoperations.html#setroworder), [setColumnOrder](https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#setcolumnorder)

### Alternative solution

Update HyperFormula state to reflect the sorted data
On sorting event Handsontable calls [HyperFormula.setSheetContent](https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#setsheetcontent) with the new data. 

A problem with that:
```
[ 2, "=A1"],  becomes  [ 1, "=A2"],   instead of  [ 1, "=A1"],
[ 1, "=A2"]            [ 2, "=A1"]                [ 2, "=A2"]
```

**Comment by warpech** [comment] 2022-07-01 13:08
I don't agree with the above explanation, at least not at this point. For me, it seems that this is a misunderstood feature, not a bug.

Before you sorted by column B, physical row 1 is rendered as the visual row 1:

<img width="247" alt="Screen Shot 2022-07-01 at 3 01 19 PM" src="https://user-images.githubusercontent.com/566463/176900432-a6263ef0-07b3-4405-b574-145a741e1e59.png">

Before you sorted by column B, physical row 1 is rendered as the visual row 5.

<img width="255" alt="Screen Shot 2022-07-01 at 3 01 50 PM" src="https://user-images.githubusercontent.com/566463/176900414-685a63e4-1c9a-41b3-beb2-000c242e1f29.png">

In the formulas, you need to use the physical row number.

In the error report, the screenshot shows that you entered the formula to the cell D2, not D1.

 Maybe we should change the feature, but for now, it looks that it works as intended - not a bug.

**Comment by sequba** [comment] 2022-07-04 10:37
@warpech You're right, it can be interpreted as the intended behavior of the sorting feature, but in my opinion, it's very confusing for the end-users.

HyperFormula uses visual row/column indexing in formulas for the data sorted using [setRowOrder](https://handsontable.github.io/hyperformula/api/classes/crudoperations.html#setroworder)/[setColumnOrder](https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#setcolumnorder). Same as the other popular spreadsheet software. In my opinion, we should maintain consistency in the behavior of our products.

**Comment by AMBudnik** [comment] 2022-09-28 11:42
> Maybe we should change the feature, but for now, it looks that it works as intended - not a bug.

I'm changing the label from `bug` to `feature`.

**Comment by adrianszymanski89** [comment] 2024-08-12 12:43
This issue is fixed in v. 14.5: https://jsfiddle.net/handsoncode/kmtherLu/

**Closed by adrianszymanski89** 2024-08-12 12:43 UTC
Labels: Type: Feature, Column sorting, Formulas, Reported
