### ISSUE TITLE
Row in validator function returning zero after filtering

### ISSUE THREAD

**Issue by clopez1winsupply** [handsontable/handsontable#10264] opened 2023-02-28 14:51 UTC
### Description
this.row in validator function is set to zero for first row after applying a filter, after first row other rows retrieve the correct row number for the filtered information.

### Steps to reproduce

1.  clone this git project: https://github.com/chr1soscl/handsontableIssue
2. npm install and start
3. open second row "Last Name" filters, filter by condition and select "Is Empty" and OK, this will filter the table results. You should see a change of number in the first column "First Name", please do not pay attention to the dummy data.
4. Open your inspect browser tool.
5. Edit the Street column in the first row (remove or change the text), you will see the following message in the inspect console: validator>this.row> 0
7. Edit the Street column in the second row, you will see something like this in the inspect console: 
validator>this.row> 201

this is how the code looks like, you can also find it in app.components.ts
`{data:'street',type:'text',readOnly:false,
          validator: function(value,callback){
              console.log("validator>this.row>",this.row);
              console.log("validator>this.instance.getData>",this.instance.getData(this.row));
              callback(true);
          }
        },`
as you can tell editing the first row after filtering is giving you the first row of the non-filtered information, when it should return the first row of the filtered information. I know this project is created in Angular, but I don't think it might be related to the Angular wrapper, but the actual handsontable.

### Demo

https://github.com/chr1soscl/handsontableIssue

### Your environment
* Handsontable version: 12.3.1
* Browser name and version: using Chrome, but the issue is also replicable on FireFox and Edge.
* Operating system: MACOS Ventura, the issue is replicable also on Windows.

**Comment by adrianszymanski89** [comment] 2023-02-28 15:21
Hi @clopez1winsupply 

Thank you for this detailed report. We might have something related already reported internally, but I need to do more testing. I'll get back to you tomorrow with more information on that.

**Comment by adrianszymanski89** [comment] 2023-03-01 09:42
Hi @clopez1winsupply 

After further investigation, I can confirm that this issue is related to the one we have reported internally. In general, it's caused by the incorrect rows indexes transformation due to trimming rows, which is an integral part of the filtering plugin. I'll give the former issue a higher priority, and I'll let you know when it gets on our roadmap.

**Comment by clopez1winsupply** [comment] 2023-03-01 11:57
> Hi @clopez1winsupply 
> 
> After further investigation, I can confirm that this issue is related to the one we have reported internally. In general, it's caused by the incorrect rows indexes transformation due to trimming rows, which is an integral part of the filtering plugin. I'll give the former issue a higher priority, and I'll let you know when it gets on our roadmap.

Is there any workaround or another way to get to the first row while you work on this issue? Any suggestions?

**Comment by adrianszymanski89** [comment] 2023-03-01 13:03
We don't have any workaround for this issue, but you might try using our indexMapper: https://handsontable.com/docs/javascript-data-grid/api/index-mapper/ to manage the indexes and re-assign them after the filtering operation.

**Comment by adrianszymanski89** [comment] 2024-06-11 13:48
Hi, @clopez1winsupply @panesofglass  @tomalec @archit  I am happy to announce that this issue is fixed in v14.4.0.

Related pull request: https://github.com/handsontable/handsontable/pull/10961

Release notes: https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-4-0

Thank you again for sharing the report!

**Closed by adrianszymanski89** 2024-06-11 13:48 UTC
Labels: bug, Core: Validation, Filtering, Reported
