### ISSUE TITLE
[7.1.0+]Can't paste from Excel

### ISSUE THREAD

**Issue by Esorakouki** [handsontable/handsontable#6217] opened 2019-08-20 06:57 UTC
### Description

In 7.1.0+, when i paste data from Excel, the following error will occur.

![image](https://user-images.githubusercontent.com/15276351/63323577-b738c480-c358-11e9-8704-39e171ab0833.png)

It's ok in Versions below 7.1.0.

### Steps to reproduce

sorry, i can't reproduce this error in browsers, only in safari in Sketch app.

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version:  safari in Sketch
* Operating System: Mac OS 10.14.5

**Comment by AMBudnik** [comment] 2019-08-20 07:36
I am sorry but I wasn't able to replicate the issue. It seems to be related to your implementation.
Handsontable doesn't throw this error message.

**Comment by Esorakouki** [comment] 2019-08-21 03:19
@AMBudnik  the error is on this piece of code (get the CSSRules from the Excel content).
![image](https://user-images.githubusercontent.com/15276351/63399193-667da600-c402-11e9-86b3-d763737faef5.png)

There is a CSSPageRule which has an unmatchable selectorText "@page".
![image](https://user-images.githubusercontent.com/15276351/63399282-a5136080-c402-11e9-8c0a-7a199a27baca.png)

I think it's a special Safari version in Sketch.

**Comment by wojciechczerniak** [comment] 2019-08-21 10:19
In Firefox:
![Screenshot 2019-08-21 at 11 30 31](https://user-images.githubusercontent.com/4718998/63423722-338cdf80-c40d-11e9-85c7-461f9c2d1b07.png)

Same would happen in FF if there would be `@page` selectorText, which is not a selector but looks like one. We haven't encounter `@page` rule before in copied clipboard.

We should check if the `cssRule` has supported `type` or is the instance of `CSSStyleRule`, not `CSSPageRule`:

https://github.com/handsontable/handsontable/blob/98878a6bb6edbed065b7961bc97d4b799e908503/src/utils/parseTable.js#L308

Might be a good idea to check remaining types as well.

**Comment by aninde** [comment] 2019-11-15 13:24
This issue should be fixed by `7.3.0` - I tested change in code locally https://github.com/handsontable/handsontable/pull/6409#issuecomment-554355622 

I would like to test is on original reproduction, using Sketch with WebView founded by @swistach to be 100% sure, but I need some time to prepare the testing environment.

**Comment by aninde** [comment] 2019-12-09 20:39
Testing locally latest build of `7.3.0 v.` (6.12) - still fixed.

**Comment by AMBudnik** [comment] 2019-12-13 07:24
Hey @Esorakouki 

we're finally here with the official fix. Please update to 7.3.0 and let me know if it fixes the issue in your application as well.

**Closed** 2019-12-13 07:24 UTC
Labels: Copy-paste, Status: Released, Type: Bug
