### ISSUE TITLE
Additional row added during copy/paste operations and with hidden rows/columns enabled

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5961] opened 2019-04-15 08:11 UTC
### Description
![kwi-15-2019 10-03-29](https://user-images.githubusercontent.com/1555809/56116532-5a6e6d00-5f66-11e9-8f77-d1c6a5942fe5.gif)

### Steps to reproduce

1. Select first column and copy them
2. Select the rest of table and use paste operation

### Demo

https://jsfiddle.net/Lehfr78d/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by aninde** [comment] 2019-09-25 14:34
Bugs are replicable in `7.1.1` and  `8.0.0-rc1`. Sadly new `index mapper` doesn't fix it.

**Bug 1 - improper row** 
It is described in original demo.
Truly, adding a new row is caused by pasting  data on `hiddenRows` when `copyPasteEnabled: false` in `hiddenRows` plugin.

**Bug 2 - improper columns**
There is an analogical bug with `hiddenColumns`, when `copyPaste` in `hiddenColumns` plugin is disabled. 
![#5961-7 1 1-col 2019-09-25 15_54_06](https://user-images.githubusercontent.com/30186818/65609115-8b3fdd00-dfaf-11e9-8e64-0da90294fe4e.gif)

Maybe those bugs are related with [that line](https://github.com/handsontable/handsontable/blob/db069ba1ebea815da0375f69244361cfe13eab98/src/plugins/hiddenRows/hiddenRows.js#L618-L620) and analogical from [hiddenRows plugin](https://github.com/handsontable/handsontable/blob/db069ba1ebea815da0375f69244361cfe13eab98/src/plugins/hiddenRows/hiddenRows.js#L618-L620). @wszymanski, @wojciechczerniak  WDYT?

**Demo**
ver. `7.1.1` https://jsfiddle.net/aninde/14qtnfhg/
ver. `8.0.0-rc1` https://jsfiddle.net/aninde/5cergv7h/

**Environment**
Browser: any
Operating system: any

**Comment by AMBudnik** [comment] 2020-05-08 10:27
7.4.2 https://jsfiddle.net/18nv6ph0/ (broken)

8.0.0.-beta1 https://jsfiddle.net/k51rqms2/ (broken)

8.0.0.-beta2-rev2 https://jsfiddle.net/17Loj8dg/ (still broken)

**Comment by aninde** [comment] 2020-08-11 11:04
Update with stable `v8.0.0` https://jsfiddle.net/aninde/2juzwgdh/. A bug is still valid.   
Functionality has not changed compared to `v7.4.2.`

**Comment by aninde** [comment] 2020-09-28 13:43
This issue will be fixed by the upcoming `v8.1.0` 
**Case 1** - no row is added on pasting
https://jsfiddle.net/aninde/o8t30kec/

![5961-fixed-ff81](https://user-images.githubusercontent.com/30186818/94439827-2f4efc00-01a1-11eb-9037-09c044d4c8b9.gif)

**Case 2** - no column is added on pasting

https://jsfiddle.net/aninde/mLr8c7fs/

**Comment by AMBudnik** [comment] 2020-10-01 12:59
Issue closed as solved for v 8.1.0 of Handsontable 👍

**Closed by AMBudnik** 2020-10-01 12:59 UTC
Labels: Copy-paste, Hiding, Type: Bug
