### ISSUE TITLE
Clicking bottom row when preventOverflow is enabled adds scrollbars

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3246] opened 2016-02-18 09:47 UTC
#http://jsfiddle.net/e0jsgxv4/3/

Create a Handsontable with `preventOverflow: 'horizontal'`. Make sure there is no horizontal overflow after initialization. Click on any cell in the bottom row. Two scrollbars immediately appear.

![image](https://cloud.githubusercontent.com/assets/7578355/13139475/cf59967c-d63d-11e5-8dec-e07744635567.png)

OSX Yosemite, Chrome 48

**Comment by AMBudnik** [comment] 2016-02-18 10:58
Hi @gstanislav I'm working on the same system and browser as you and couldn't reproduce this one. Could guide me how to do that?

**Comment by budnix** [comment] 2016-02-18 11:02
I've the same bad behavior on OSX + chrome and safari in FF it seems to be ok. I mark this as a bug :)

**Comment by AMBudnik** [comment] 2016-09-09 11:32
@budnix 
Can you check it with the [0.27.0](http://jsfiddle.net/e0jsgxv4/3/)? It seems to work well.

**Comment by budnix** [comment] 2016-09-09 11:37
@AMBudnik It seams to be working now. I think that you can close the issue.

**Comment by AMBudnik** [comment] 2016-09-09 11:38
thanks.

**Closed by AMBudnik** 2016-09-09 11:38 UTC
Labels: Bug, Core: walkontable, Guess: few hours, Priority: normal
