### ISSUE TITLE
Cell meta disappears after updating settings

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#6552] opened 2019-12-11 10:02 UTC
### Description
When I update the table settings using the updateSettings method all custom metadata is cleared from the table. Am I doing something wrong or is this a bug?

I'm using updateSettings to set the maxRows + 1 before adding a row. So I have to update the settings object for the change to take effect.

### Steps to reproduce

1. Add meta to cells
2. Update settings using table.updateSettings(...)
3. Now metadata is gone!

### Demo
https://stackblitz.com/edit/handsontable-metadata-removed

**Comment by wojciechczerniak** [comment] 2019-12-11 13:41
Hi @ottosson 

If `updateSettings` has a data set then `loadData` will be called and all the data replaced. When data is replaced the metadata is cleared with it. Like you would have completly new data set.

**Comment by ottosson** [comment] 2019-12-11 16:19
Thanks, that makes sense. But it also seems that if the column property is set in the settings object the metadata will be reset as well.

But I guess I was using the updateSettings a bit wrong. I thought I needed to pass the whole settings object and not just the updated properties.

**Comment by jansiegel** [comment] 2021-12-01 09:02
Seems to be resolved in #7263.
https://codesandbox.io/s/angular-handsontable-pr-forked-3v6o0

**Comment by AMBudnik** [comment] 2021-12-23 08:50
Since v11.1.0 is not tested and merged yet I would prefer to keep the issues opened and close it after we confirm that everything works well.

**Comment by jansiegel** [comment] 2021-12-23 08:54
@AMBudnik As the plans changed and #9037 was merged, the effects of #7263 won't be visible until the release of `12.0.0`.

**Comment by AMBudnik** [comment] 2021-12-23 08:56
Thanks for the prompt update @jansiegel Let's wait for v12 then.

**Comment by aninde** [comment] 2022-03-10 08:40
Work as expected with v12.0.0. Tested locally.

**Comment by AMBudnik** [comment] 2022-04-28 13:18
Hi @ottosson 

I'm more than happy to announce that Handsontable v12 is not online. I will not close the topic till I get the confirmation that the issue is gone on your side.

**Comment by warpech** [comment] 2022-05-11 15:57
Closing this issue as I believe the issue is now solved. @ottoson please reopen if that is not the case.

**Closed by warpech** 2022-05-11 15:57 UTC
Labels: Type: Change, Status: Released
