### ISSUE TITLE
[6.1.0+] The native selection deselects when fragmentSelection is enabled

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6372] opened 2019-10-22 11:07 UTC
### Description

It seems that `fragmentSelection` option changed its behavior since 6.1.0. The native selection is automatically deselected on `mouseup` event.

### Steps to reproduce

1. Try to select D5 value;
2. After releasing LMB the selection disappear;

### Demo

Working demo (`6.0.1`) https://jsfiddle.net/xd8n0sL1/;
Not working demo (`6.1.0`) https://jsfiddle.net/xd8n0sL1/1/
Not working demo (`7.2.1`) https://jsfiddle.net/xd8n0sL1/2/

### Your environment
* Handsontable version: 7.2.1
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by AMBudnik** [comment] 2020-03-23 14:10
Demo updated to the official `8.0.0-beta1` https://jsfiddle.net/5q3zp7su/

**Comment by AMBudnik** [comment] 2020-09-10 10:28
I've also got the same behavior with v8.0.0 (stable) while testing https://github.com/handsontable/handsontable/issues/6083

**Comment by wszymanski** [comment] 2021-02-23 15:24
Duplicate of https://github.com/handsontable/handsontable/issues/6083.

**Closed by wszymanski** 2021-02-23 15:24 UTC
Labels: Core: selection, Guess: a day or more, Regression, Type: Bug
