### ISSUE TITLE
Virtual rendering bug

### ISSUE THREAD

**Issue by electrikaLaszlo** [handsontable/handsontable#4507] opened 2017-09-08 11:11 UTC
### Description
Virtual rendering does not work in special circumstances.

### Steps to reproduce

1. Add the option to the handsontable: preventOverflow: 'horizontal'
2. Use the updateSettings method to update anything (I tried with data and column)
3. The rows out of the screen is not rendered when you scroll down.

### Demo
http://jsfiddle.net/Lp4qn55v/836/

### Your environment
* Handsontable version: Latest
* Browser Name and version: Internet explorer 11, Chrome 60
* Operating System: Wondows 10

**Comment by AMBudnik** [comment] 2017-09-08 11:17
Thank you for sharing @electrikaLaszlo 

I have replicated the issue. The data is missing and I got doubled headers

![image](https://user-images.githubusercontent.com/10757813/30209359-fc43f67c-9497-11e7-86d5-4a48072eb505.png)

Testing on Windows 10/ Chrome 60

**Comment by AMBudnik** [comment] 2017-09-08 11:19
Might be related to https://github.com/handsontable/handsontable/issues/4303

**Comment by AMBudnik** [comment] 2017-10-03 10:50
In some cases adding `renderAllRows: true` fixes the issue

**Comment by abcau** [comment] 2017-11-24 02:42
Hi, we using handsontable pro in our company. We faced similar bug with double heading and missing styles on the vertical scroll (we using custom styles for cells). We can't use renderAllRows because we render more than 2k rows.

**Comment by AMBudnik** [comment] 2017-11-24 09:58
As diagnosed the issue lays in the Walkontable. We did not find and overnight workaround.

**Comment by wojciechczerniak** [comment] 2019-02-14 09:19
Duplicate of  #4303

**Closed by wojciechczerniak** 2019-02-14 09:19 UTC
Labels: Core: walkontable, Type: Bug
