### ISSUE TITLE
Pasting Text in Numeric Columns throwing Error

### ISSUE THREAD

**Issue by agokulravikumar** [handsontable/handsontable#5258] opened 2018-07-13 07:55 UTC
### Description
Text is pasted in a numeric type column and the text is skipped if pasted in small number of rows. But when more number of rows is pasted, it throws error.

### Steps to reproduce
In the Columns, Give the following,
**type: 'numeric',
allowInvalid: false**

### Demo
Recorded a small video to replicate the issue in the Demo Js Fiddle
https://wetransfer.com/downloads/563e3798cd46e336b2ef3cce4adb989420180713075018/82ffa7

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment] 2018-07-13 08:13
HI @agokulravikumar 

Thank you for sharing. I have replicated the issue using Win 1/ Chrome 67 and MS Excel 2016

**Comment by wojciechczerniak** [comment] 2018-09-11 14:09
Probably a duplicate of #5119. Please track #5119 for updates.

**Closed by wojciechczerniak** 2018-09-11 14:09 UTC
Labels: Plugin: copy-paste, Type: Bug

**Comment by AMBudnik** [comment] 2018-10-18 07:32
Hi @agokulravikumar 

please update to 6.1.0 and let me know if everything works fine now.

We've fixed this issue within this one https://github.com/handsontable/handsontable/issues/5119
