### ISSUE TITLE
[8.0.0-rc1] Cells in Handsontable Editor no longer contain 'listbox' class.

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6322] opened 2019-10-07 23:21 UTC
### Description
When a cell is part of an autocomplete HoT, it should have the `listbox` class added to it's class list. It was present in 7.1.1 but is now gone in 8.0.0.

Without that class, it's extremely difficult (or expensive) to target a single cell in a dropdown list for special styling. Is there a workaround to this?

### Steps to reproduce
7.1.1: https://jsfiddle.net/L16xemn3/
![Screen Shot 2019-10-07 at 6 17 26 PM](https://user-images.githubusercontent.com/881931/66356039-23827e00-e92f-11e9-804c-fea1263c65a5.jpg)

RC1: https://jsfiddle.net/2Le0yz3w/
![Screen Shot 2019-10-07 at 6 15 33 PM](https://user-images.githubusercontent.com/881931/66356042-27160500-e92f-11e9-9b35-27ce1e993975.jpg)

**Comment by AMBudnik** [comment] 2019-10-08 07:53
Confirmed with yesterday's build https://jsfiddle.net/handsoncode/ejtmsn4L/

Thank you for sharing @wszymanski is that intended?

**Comment by wojciechczerniak** [comment] 2019-10-08 08:10
`listbox` is the class added to the Handsontable cell type **editor**. A cell doesn't have this class in either of the examples.

@AMBudnik where did you found the difference between v7 and v8? Please add more details.

**Comment by AMBudnik** [comment] 2019-10-08 08:33
I've build develop locally and the class in there

![image](https://user-images.githubusercontent.com/10757813/66380148-1a3cf400-e9b7-11e9-9798-e2415938910b.png)

**Comment by wszymanski** [comment] 2019-10-08 09:23
@aarondfrancis Thanks for the information. I will check that.

**Comment by aninde** [comment] 2019-10-08 13:41
@wszymanski checked it and fixed it in the newest build of `8.0.0-rc1`.  Thank you.
Class `lightbox` is restored. 

![Screenshot 2019-10-08 at 15 37 41](https://user-images.githubusercontent.com/30186818/66400512-e5926200-e9e1-11e9-8ea8-6c50847e9fa5.png)


**Demo**
latest - 8.10.19 `8.0.0-rc1` . https://jsfiddle.net/aninde/7ye1xvsr/

**Comment by aninde** [comment] 2019-11-13 08:45
The latest build of `8.0.0-beta.1` still fixed described here issue. 

Demo
`v. 8.0.0-beta.1` https://jsfiddle.net/aninde/kfq2porc/ forked from [AMBudnik](https://github.com/handsontable/handsontable/issues/6322#issuecomment-539410734)'s demo
`v. 8.0.0-beta1` https://jsfiddle.net/aninde/1p2h5os0/ forked from [my](https://github.com/handsontable/handsontable/issues/6322#issuecomment-539519305) demo

**Comment by wojciechczerniak** [comment] 2019-12-30 09:55
This issue was introduced in v8-beta and fixed in v8-beta. We don't have to track it any longer so I'm closing it.

**Closed by wojciechczerniak** 2019-12-30 09:55 UTC
Labels: Type: Bug
