### ISSUE TITLE
columnSummary ignore 0 in min options

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6385] opened 2019-10-25 13:36 UTC
### Description
It seems that value `0` isn't considered in `min` options. Just like `0` wasn't a value. Thanks `count` option - https://jsfiddle.net/y85grszo/2/ -  we can see that `0` doesn't belong to a non-empty value. 
But if edit `0` the calculation `min` is correct to `0`. 

### Demo

https://jsfiddle.net/y85grszo

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment] 2019-10-28 09:38
If we type only `0` we get the `Not enough data` return for both `min` and `max`. `Sum` works well and all `min/max` work well for negative numbers.

![image](https://user-images.githubusercontent.com/10757813/67667195-95b61380-f96d-11e9-8132-ecdab4fe09f1.png)
https://jsfiddle.net/d1jLvupk/1/

**Comment by AMBudnik** [comment] 2020-08-18 11:23
The issue is still replicable after updating to v8.0.0 https://jsfiddle.net/zxk6nghr/

**Comment by krzysztofspilka** [comment] 2022-06-09 23:11
@AMBudnik is it still reproducible?

**Comment by AMBudnik** [comment] 2022-06-10 06:42
@krzysztofspilka, yes it is. I've updated the demo to v12.0.1 and still `7` is considered the lowest number from the `0, 7, 14` array.

![Screenshot 2022-06-10 at 08 43 01](https://user-images.githubusercontent.com/10757813/173006382-7bd92b65-a7e7-4a89-889c-48d2facf7ddd.png)


Demo https://jsfiddle.net/s8mefgkp/1/

**Comment by aninde** [comment] 2022-09-21 13:19
This issue will be fixed by the upcoming v12.1.3 https://jsfiddle.net/ocshdk2m/

**Comment by AMBudnik** [comment] 2022-09-22 09:45
I'm closing this issue as fixed in Handsontable v12.1.3

**Closed** 2022-09-22 09:46 UTC
Labels: Type: Bug, Status: Released, Summary calculations
