### ISSUE TITLE
manualColumnFreeze: colToProp/propToCol issue

### ISSUE THREAD

**Issue by gaussian1** [handsontable/handsontable#2292] opened 2015-03-22 11:35 UTC
I have an issue when using manualColumnFreeze feature with a handsontable based on an object data source  and then using the propToCol function.

I've added the steps to reproduce the issue in the following jsfiddle:
http://jsfiddle.net/mabd91/a0n4Lp4p/

The way I understand the propToCol and colToProp functions is that they must mirror each other, propToCol('id')=2 <-> colToProp(2)='id', if this is true, then the manualColumnFreeze plugin is failing to update the dataMap correctly.

**Comment by jansiegel** [comment] 2015-04-07 13:40
@mabd91, confirmed, we'll look into it!

**Comment by AMBudnik** [comment] 2015-09-09 14:31
Confirmed with [0.17.0 version example](https://jsfiddle.net/a0n4Lp4p/2/)

**Comment by AMBudnik** [comment] 2016-03-16 15:23
Still present in 0.24.1 demo: https://jsfiddle.net/a0n4Lp4p/3/

**Comment by mabd91** [comment] 2016-06-04 05:40
Since this issue is pretty old I just wanted to share how I got it to work eventually, it seems that the manualColumnFreeze plugin is secretly linked to the manualColumnMove Plugin because it uses the "changeColumnPositions" function defined inside the manualColumnMove plugin.

Basically, as it currently stands you can't use the manualColumnFreeze plugin without having the manualColumnMove plugin enabled.
```
{
manualColumnFreeze:true,
manualColumnMove:true
}
```
Hope this helps someone out there!

**Comment by AMBudnik** [comment] 2016-06-06 09:32
thanks for sharing @mabd91 
sure it will help our devs

**Comment by AMBudnik** [comment] 2018-01-22 13:37
The issue evolved. In version 0.35.0 we get an empty context menu while doing the 2nd step

**Comment by AMBudnik** [comment] 2018-04-16 12:13
I've changed the `` as I wasn't able to take the step 2 but here's an updated demo https://jsfiddle.net/yptsh7uo/ where we get proper results.

Can you check that, please @gaussian1 ?

I'll keep this issue closed as I'm not able to replicate it.

**Closed by AMBudnik** 2018-04-16 12:13 UTC
Labels: Core: callbacks, Plugin: Fixing, Priority: normal, Type: Bug

**Comment by gaussian1** [comment] 2018-04-18 21:57
@AMBudnik 
Sorry for not responding faster, here is the code updated, In addition to the previous bug, I can **no longer use the context menu**.
[https://jsfiddle.net/mabd91/yptsh7uo/48/](https://jsfiddle.net/mabd91/yptsh7uo/48/)

**Comment by AMBudnik** [comment] 2018-04-19 07:28
You're not able to use the contextMenu? Wow. What browser are you using?

Here's how it looks in Chrome 65 on Windows 10

![gif](https://user-images.githubusercontent.com/10757813/38977215-fa46f498-43b3-11e8-8c7f-3f14b9109ea2.gif)

**Comment by gaussian1** [comment] 2018-04-24 19:43
@AMBudnik Okay I've tested it again and it is working 🎉 
Thanks for the fix! It **took 3 years** but better late than never 😄

**Comment by AMBudnik** [comment] 2018-04-25 07:51
Thank you for confirmation :)
