### ISSUE TITLE
[0.25.0+] Links/click events with from custom renderers not working under 0.25

### ISSUE THREAD

**Issue by scottadmi** [handsontable/handsontable#3567] opened 2016-06-07 20:51 UTC
In tests, I have a grid which contains a cell with a custom renderer which builds a link for a given cell. In this case the link has an onclick event which for the sake of discussion could just show an alert such as <a href="#" onclick="alert('hi'); return false;">My Link</a>

In Handsontable version 0.24.3, this worked perfectly, however when I updated to the last distribution, this behavior broke. After much debugging in Chrome, it became clear the reason it broke is that when mousedown on the link occurred, an unnecessary re-render of the whole table was triggered. This caused the cell to dump the link DOM which had been pressed and replace it with a newly generated DOM element, and so the "click" event never fired since it was a different element on the way down from up.

Looking at the stack trace to the renderer reveals this:

deviceManageDialogLinkFormatHOT (devices?type=&g…89E43879ED:717)
cellRenderer (handsontable.full.js:20021)
renderCells (handsontable.full.js:3721)
renderRows (handsontable.full.js:3589)
render (handsontable.full.js:3520)
_doDraw (handsontable.full.js:3253)
draw (handsontable.full.js:3232)
draw (handsontable.full.js:1180)
TableView.render (handsontable.full.js:20267)
refreshBorders (handsontable.full.js:4915)
Core.render (handsontable.full.js:5308)
onDataChange (handsontable.full.js:18159)
(anonymous function) (handsontable.full.js:18102)
(anonymous function) (handsontable.full.js:11107)
arrayEach (handsontable.full.js:9309)
runLocalHooks (handsontable.full.js:11106)
onChange (handsontable.full.js:18050)
(anonymous function) (handsontable.full.js:18037)
generate (handsontable.full.js:22255)
dirtyCheck (handsontable.full.js:22186)
(anonymous function) (handsontable.full.js:22191)

It seems that a dirtyCheck is now being performed, and triggering onChange events despite the fact that the underlying data model remained untouched. In stack trace, it appears the onChange is directly triggered by this dirtyCheck with no actual evaluation. This is triggered on a zero timer. I don't have the expertise to know why this is triggering a re-render when it seemingly shouldn't. If this is an intentional change to re-render anytime a mouse event occurs, I would like to understand what the preferred way of addressing this situation is. At the moment, no links work properly unless they are clicked rapidly such that it beats out the timer based dirty check.

Thank you.

**Comment by scottadmi** [comment] 2016-06-09 06:17
Included is a simple example of this. When the included Handsontable version is 0.24.3, this works as expected, in which clicking "Alert Me" displays an on alert via onclick event. When updating to 0.25.x it no longer does (as the cells get re-rendered mid-cycle). Based on some additional investigation it seems that the presence of a standard javascript Date object is a factor, as is the inclusion of the columnSorting option.

`<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Handsontable Link Problem Demo</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<link href="handsontable.full.min.css" media="screen" rel="stylesheet" type="text/css" />
<script src="handsontable.full.js" type="text/javascript"></script>

<script type="text/javascript">
	var colHeaders = ['ID',"Time",'Alert']
	var hotColumns = [
		{data:"serial", readOnly: true},
		{data:"time", renderer: dateFormatRenderer, readOnly: true},
		{data:"name", renderer: alertFormatRendered, readOnly: true}
	]
	var colWidths = [200, 200, 200];

	function initializeHandsOn() {
		var handsOnContainer = document.getElementById('handsOnArea');
    	
    	var handsOnTable = new Handsontable(handsOnContainer,{
			columnSorting: {
				column: 0,
				sortOrder: true
			},
			data: [],
			disableVisualSelection: true,
			colHeaders: colHeaders,
			colWidths: colWidths,
			columns: hotColumns
		});
		handsOnTable.loadData([{"serial":"A","name":"A","time":new Date(1465451486941)},{"serial":"B","name":"B","time":new Date(1465451496941)}]);
	}
	
    document.addEventListener('DOMContentLoaded', initializeHandsOn, false);

    function dateFormatRenderer(instance, td, row, col, prop, value, cellProperties) {
    	var cellValue = value == null? "&mdash;" : value + "";
    	td.innerHTML = cellValue;
        return td;
    }
    
    function alertFormatRendered(instance, td, row, col, prop, value, cellProperties) {
		var cellValue = "<a onclick='alert(\"" + value + "\");return false;' href='#'>Alert Me</a>";
        td.innerHTML = cellValue;
        return td;
    }
</script>
</head>
<body>
	<div id="handsOnArea" style='width:600px;height:400px;overflow:hidden'> </div>
</body>
</html>`

Please let me know if this would be helpful in an alternative format.

**Comment by AMBudnik** [comment] 2016-06-09 10:15
I tried to upload your code into JSFiddle to test it but with no luck. Can you create a demo using JSFiddle? I think it will be the easiest way for our developers to test this issue.

**Comment by scottadmi** [comment] 2016-06-09 12:26
https://jsfiddle.net/f57zr187/

The example is against 25.1. If you swap out the External Resource of the "handsontable.full.js" for the 24.3 version, it shows the prior behavior with the alert link working. (If you want an alternate link for this, I can provide that - just a swapped url.)

**Comment by AMBudnik** [comment] 2016-06-09 12:35
Thanks for sharing demo @scottadmi 

You're right - the last version when it was working is 0.24.3 and since 0.25.0 it's not showing the window.

[0.25.0](https://github.com/handsontable/handsontable/releases/tag/0.25.0) added only one change that can cause incompatibility but it's not related with the subject.

**Comment by brendonboshell** [comment] 2018-04-06 14:31
I am using the following option as a temporary workaround to this problem:

```js
beforeOnCellMouseDown: function (event) {
  var $target = $(event.target);

  if ($target.closest('a[href]').length) {
    event.stopImmediatePropagation();
  }
},
```

**Comment by AMBudnik** [comment] 2019-03-04 13:53
The issue is still replicable in v `6.2.2`

**Comment by bchoddny** [comment] 2019-03-14 02:08
Any idea when this will be fixed? In our case, we've an icon with click handler, as cell content. I did notice the re-render happening, when the icon is clicked, so the click handler never get fired. On clicking the second time it does.

**Comment by bchoddny** [comment] 2019-03-14 20:03
Is this related to the issue below. From the stacktrace, I see the rendering is triggered by observechanges :
https://github.com/handsontable/handsontable/issues/2630

**Comment by AMBudnik** [comment] 2019-03-21 13:51
I am sorry @bchoddny but we did not investigate the subject yet. It hasn't been scheduled for March

**Comment by aerogt3** [comment] 2019-03-28 09:44
@brendonboshell appreciate the workaround :+1:

**Comment by imageslr** [comment] 2019-07-17 03:08
Still have this problem. Custom link cannot be opened when click.

**Comment by AMBudnik** [comment] 2020-09-10 13:31
This issue seems to be gone when I test the same demo https://jsfiddle.net/AMBudnik/v841jd3y/ using v8.0.0
@imageslr do you still get the same issue?

**Comment by swistach** [comment] 2021-01-11 16:14
Hi @scottadmi, @brendonboshell, @bchoddny, @aerogt3, @imageslr,
In v8.0.0 we solved an issue with clicking on `<a>` elements.
Due to it's a while since the release I close this issue. If you will face a similar problem after upgrade to v8 let us know.

**Closed by swistach** 2021-01-11 16:14 UTC
Labels: Core: callbacks, Regression, Type: Bug

**Comment by imageslr** [comment] 2021-01-11 16:23
Thank you for your contribute. @swistach
