### ISSUE TITLE
Command select still active after switching window

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#10062] opened 2022-10-26 08:37 UTC
### Description
Multiselect ranges is still active after switching window using the mouse, then release Command and switch back to browser using mouse click.

### Steps to reproduce
1. Hold down the Command button
2. Select a few ranges / make sure the grid is active
3. While still holding down Command, press Tab to select another window.
4. Use mouse to select another window.
5. Release Command
6. Click the browser window with mouse to activate it again.
7. Select ranges
8. Grid behaves as if Command is still pressed
9. Press and release Command to return to normal behavior

### Demo

https://user-images.githubusercontent.com/3355320/197976173-f6351f1f-466f-468f-95a1-38f2ca7d775e.mov

### Your environment
* Handsontable version: 12.2.0
* Browser name and version: Firefox (105)
* Operating system: Mac OS 12.6

**Comment by ben-carmichael-dentsu** [comment] 2022-10-26 10:40
I've just noticed a similar issue.

### Steps to reproduce

- Select a spreadsheet cell
- Capture a screenshot using the macOS keyboard shortcut CMD+SHIFT+4
- Select another cell
- Grid behaves as if Command is still pressed

### Your environment
Handsontable version: 12.1.0
Browser name and version: Chrome (106)
Operating system: macOS 12.6

**Comment by AMBudnik** [comment] 2022-10-26 12:43
Thank you @ottosson and @ben-carmichael-dentsu I replicated both issues on Chrome 106. And it seems to be the same issue as https://github.com/handsontable/handsontable/issues/6441. Could you please post your cases in https://github.com/handsontable/handsontable/issues/6441 as I need to close this issue as a duplicate?

**Closed** 2022-10-31 08:16 UTC
Labels: Type: Duplicate

**Comment by AMBudnik** [comment] 2022-11-10 10:56
We also got a notification to test the fix with the following steps.

> 1. Click on the cell
> 2. ⌘ + C
> 3. Click on another cell
