### ISSUE TITLE
options "cell" and "columns" seem to be incompatible

### ISSUE THREAD

**Issue by markusp72** [handsontable/handsontable#3175] opened 2016-02-01 17:12 UTC
see this fiddle:

http://jsfiddle.net/rseq9jyr/1/

The table is only shown if either "cell" or "columns" property is defined. If both options are given, an error is thrown.

Firebug:
`TypeError: priv.columnSettings[col] is not a constructor
priv.cellSettings[row][col] = new priv.columnSettings[col]();
handson...full.js (Zeile 5370, Spalte 1)`

**Comment by AMBudnik** [comment] 2016-02-01 17:35
Confirmed. Thanks for sharing @markusp72

**Comment by AMBudnik** [comment] 2016-09-09 11:22
Still replicable.

**Comment by AMBudnik** [comment] 2017-01-25 13:42
Still doesn't work in 0.30.1, demo: http://jsfiddle.net/handsoncode/4wrqdwx3/

**Comment by thgh** [comment] 2017-03-09 08:53
It's possible to get it working by moving the `cell` option to `hot.updateSettings`.
http://jsfiddle.net/opwy99yb/

But I couldn't get it to work reliably afterwards...

**Comment by AMBudnik** [comment] 2017-03-09 09:03
Thanks for your investigation @thgh

**Comment by apatton724** [comment] 2017-05-10 02:00
Thanks @thgh  for the work around. Like you said, it's not really consistent. 

Any other updates here?

**Comment by AMBudnik** [comment] 2017-05-10 05:51
I think it may be changed while developing this task https://github.com/handsontable/handsontable/issues/4055, but it looks like a plan for Q3.
If you would like to check what our devs are doing you can visit our Roadmap https://trello.com/b/PztR4hpj/handsontable-roadmap-2017-login-to-vote

You can also leave your vote there for your favorite or most needed tasks.

**Comment by apatton724** [comment] 2017-05-10 17:36
Can you think of another work around with the columns property? 

I'm using the columns property to setup what columns need to be calculated. Is there a way to do that after the table has been initialized?

**Comment by AMBudnik** [comment] 2017-05-11 07:14
@apatton724 
Can you describe your case? Maybe there's a way to do it differently.

**Comment by apatton724** [comment] 2017-05-12 11:47
Sure. It's nothing really custom. 

I'm  trying to make each column use the column summary plugin so we can add up all of the rows and each of those cell should be able to have comments on them. I'm persisting those comments. So onLoad of the handsontable, I want to be able to populate those comments in the "cell" section of the handsontable initialization.

**Comment by AMBudnik** [comment] 2017-05-15 13:01
Hi @apatton724 
Can you share a demo with your recent progress? I can take a look for a workaround. I think you may just load the comments inside an array fo arrays via [`getCommentAtCell`](https://docs.handsontable.com/pro/1.10.2/Comments.html#getCommentAtCell) but I would need to see the table structure.

**Comment by AMBudnik** [comment] 2018-04-16 12:48
It doesn't seem to be an issue anymore. I've just tested it on v `2.0.0` here http://jsfiddle.net/etppmzod/

I'm closing this issue but if anyone has any problems that sound similar let me know.

**Closed by AMBudnik** 2018-04-16 12:48 UTC
Labels: Core: handsontable, Type: Bug
