### ISSUE TITLE
help header colspan

### ISSUE THREAD

**Issue by gbelmm** [handsontable/handsontable#1077] opened 2013-10-03 13:51 UTC
see example
view numbrer 99 

move the slider to the right and 99 column changes

http://jsfiddle.net/Ckw9b/695/

![99](https://f.cloud.github.com/assets/731936/1246684/977e94c2-2ab0-11e3-93c5-737afadb13ad.png)
![99 2](https://f.cloud.github.com/assets/731936/1246685/97808e26-2ab0-11e3-9b0e-642517966d2b.png)

**Comment by krzysztofspilka** [comment] 2015-01-22 16:12
@gbelmm Couldn't reproduce this, seems to be an outdated problem. I'm closing the issue but if you can provide us with more details or JSFiddle demo, please do so by opening the new issue.

**Closed by krzysztofspilka** 2015-01-22 16:12 UTC
