### ISSUE TITLE
Angular13 Dropdown Not Working

### ISSUE THREAD

**Issue by Petahwil** [handsontable/handsontable#9452] opened 2022-05-02 17:20 UTC
I have a handsontable in my componet.ts and when I try to use the dropdown list and click the down arrow it is just turning into a text editor. Just wondering how I get the dropdown to work properly.

componet.ts

```
dateToday: number = Date.now();
private hotRegisterer = new HotTableRegisterer();
id = 'hotInstance';
hotSettings: Handsontable.GridSettings = {
  maxRows: 22,
  startRows: 2,
  startCols: 2,
  contextMenu : true,
  height: 'auto',
  width: 'auto',
  minSpareRows: 1,
  columns: [
  {
  type: 'dropdown',
  source: ['sn', 'st']
  },
  {
    editor: 'text'
  },
  {
    type: 'date',
    dateFormat: 'MM/DD/YYYY',
    correctFormat: true,
    defaultDate: this.dateToday+'',
    
  }
],
colHeaders: ['Asset Type','Serial Number','Shipdate'],
rowHeaders: true,
colWidths: 300,
licenseKey: 'non-commercial-and-evaluation'
}
```
html
```

<div class="hot">
   <hot-table [hotId]="id" [settings]="hotSettings"></hot-table>
</div>
```

**Comment by adrianszymanski89** [comment] 2022-05-04 08:22
Hi @Petahwil 

I recreated a simple demo with your settings and dropdown menu is working properly. Can you please confirm if that's your expected result?

https://jsfiddle.net/aszymanski/p7s63nw9/3/

**Comment by Petahwil** [comment] 2022-05-04 13:45
yes it is but this isn't even TS

**Comment by adrianszymanski89** [comment] 2022-05-04 14:03
Ok, I see. Here is the version with Angular + TS, and indeed, when there is no data provided, the dropdown cell type isn't working correctly. I will mark it as a bug and consult with the development team.

https://jsfiddle.net/aszymanski/j0qk7fc1/

**Comment by adrianszymanski89** [comment] 2022-05-04 14:43
If you want to use placeholder data in your Angular project you need to just import Handsontable and then declare it as follows in your grid settings:

`data: Handsontable.helper.createSpreadsheetData(10, 10)`

**Comment by Petahwil** [comment] 2022-05-04 14:46
Like I said before this wont load it says Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'createEmptySpreadsheetData')

**Comment by Petahwil** [comment] 2022-05-04 18:48
Just for anyone that might have this issue as well the work around is add
import { createEmptySpreadsheetData } from 'handsontable/helpers';  
in the below
hotSettings: Handsontable.GridSettings = {} 
add 
data: createEmptySpreadsheetData(4, 4),

This has to be 4 or greater or the dropdown wouldn't work. Then in packages.json under exports you have to add     

"./helpers/data.d.ts": "./helpers/data.d.ts",
    "./helpers": {
      "require": "./helpers/data.js",
      "import": "./helpers/data.mjs"
    },

**Comment by ngingihy** [comment] 2022-05-10 11:31
@adrianszymanski89 
I tried 
`data: Handsontable.helper.createSpreadsheetData(10, 10)`

but i keep getting this error, i think the createSpreadsheetData mess up the activated routes, any clue how to fix this?

> "core.mjs:6485 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'createSpreadsheetData')
> TypeError: Cannot read properties of undefined (reading 'createSpreadsheetData')"

**Comment by ngingihy** [comment] 2022-05-10 11:35
also when do you think this bug will be fixed? @adrianszymanski89

**Comment by AMBudnik** [comment] 2022-05-10 12:18
Thank you for your feedback @ngingihy @Petahwil we will check both of the cases and come back to you shortly.

**Comment by AMBudnik** [comment] 2022-05-11 12:08
I can confirm that `helpers` are not a module, they are meant to be used only internally by Handsontable developers and they were never added to the official API. As the issue with dropdown is already closed I need to close the whole issue as solved.

**Comment by Petahwil** [comment] 2022-05-11 14:05
how is this closed was it fixed

**Comment by Petahwil** [comment] 2022-05-12 20:14
Consultation? @AMBudnik

**Comment by AMBudnik** [comment] 2022-05-13 07:35
@Petahwil we've mentioned

>I will mark it as a bug and consult with the development team.

so I assumed that you will try the tips provided by @adrianszymanski89 with your development team and come back to us (me and @adrianszymanski89) if there will still be some issues with the implementation.

We can also schedule a quick checkout via call. If you are interested please contact me at support@handsontable.com and we'll schedule the meeting.

**Comment by adrianszymanski89** [comment] 2022-08-31 10:29
Hi @Petahwil 

I was rechecking this issue, and I found out that this issue is possibly gone. When I set the table without any data in it, the dropdown menu still works correctly. Can you please confirm if the issue is gone? Here's an example:

https://jsfiddle.net/aszymanski/j0qk7fc1/2/

**Comment by AMBudnik** [comment] 2022-09-19 13:27
Hi @Petahwil 

As we did not get any feedback for more than 2 weeks, we need to close the issue. However, if there's any scenario where the issue is still replicable please leave a comment.

**Closed by AMBudnik** 2022-09-19 13:27 UTC
Labels: Status: Answered
