### ISSUE TITLE
Ability to set column type while retaining the use of minSpareCols

### ISSUE THREAD

**Issue by etsimber** [handsontable/handsontable#1536] opened 2014-06-18 20:46 UTC
I would like the user to be able to dynamically add columns via the use of minSpareCols.  At the same time because I know the type of the already existing columns I would like to set it.  Unfortunately it appears that the only way to set the type is via the use of the columns option which overwrites the minSpareCols behavior.  Would you consider adding this as a feature, perhaps allow the columns to be a function so that only certain columns can be returned.

Thanks.

**Comment by AMBudnik** [comment] 2015-05-11 08:13
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by ichiriac** [comment] 2016-05-27 13:13
Hi,

To me it's not a feature request but rather an buggy behaviour unless this limitation is not clearly explained in documentation.

A link to reproduce the behaviour : http://jsfiddle.net/64hxdftw/1/

For me this feature is important because I'm actually allocating the maximum number of columns I could use and I can't use this feature to improve performances or I should mimic myself the same behaviour.

Please could you tell when you plan to fix it ?

**Comment by AMBudnik** [comment] 2016-05-30 09:53
Hi @ichiriac 
In `columns` description it's written:
`Notice: Using this option sets a fixed number of columns (options startCols, minCols, maxCols will be ignored).`, [docs](https://docs.handsontable.com/pro/1.4.0/Options.html#columns) so it's rather a feature but I understand it can be frustrating. 

ps. there could be a workaround for it, here http://jsbin.com/vemeqivife/1/edit?js,output I'm adding a new empty object to `columns` settings when any cell in last column was edited. It fires for every change that is not a `loadData`.

**Comment by ichiriac** [comment] 2016-05-30 15:11
Hi @AMBudnik,

Thanks for your reply, I will use something similar to your workaround.

**Comment by pmunin** [comment] 2018-01-22 13:45
@AMBudnik the example provided does not work if you do autofill the last column - dragging the corner of the cells from the left to the last empty column. Apparently afterChange event does not trigger in autofill. Can you please update the example?

**Comment by AMBudnik** [comment] 2018-01-22 14:10
Thanks for spotting that @pmunin 
You're right. Even when I update the version to latest (v0.35.0) we do not trigger the `afterChange`. Maybe the `beforeAutofill` is a better choice here.
Although, we should open a new issue for that behavior. Here's a demo of the latest version http://jsfiddle.net/5m3dh8f9/
The `afterChange` is called if we start at cell in the column `E` and proceed to copy the value to column `F` but does not work for columns that are before `E`.

**Comment by AMBudnik** [comment] 2018-12-07 14:44
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for sharing. I hope that we'll be able to publish it soon.

**Closed by AMBudnik** 2018-12-07 14:44 UTC
Labels: Guess: few hours, Priority: normal, Type: Feature

**Comment by AMBudnik** [comment] 2021-04-28 12:27
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
