### ISSUE TITLE
using 'hiddenColumns' and 'stretchH' shows a unnecessary horizontal scrollbar when there is enough space

### ISSUE THREAD

**Issue by HaroldStruwig** [handsontable/handsontable#4181] opened 2017-04-10 11:43 UTC
### Your environment
* Handsontable version: PRO 1.10.2

**Comment by AMBudnik** [comment] 2017-04-10 13:22
Hi @HaroldStruwig 

Please create a demo or share any video/screenshot where we will be able to see how it looks.

I tried to replicate it with this demo http://jsfiddle.net/handsoncode/mtyjmft4/ by changing the window's width but it does not act unexpectedly.

**Comment by HaroldStruwig** [comment] 2017-04-10 14:17
Hi @AMBudnik 

Please see: http://jsfiddle.net/mtyjmft4/2/

Seems like it only happens when setting ```indicators``` to ```false```

**Comment by HaroldStruwig** [comment] 2017-04-10 14:20
@AMBudnik sorry last statement in previous comment was not entirely correct (although it seems to work better when setting it to ```false```) since it also happens after editing a cell

**Comment by AMBudnik** [comment] 2017-04-10 14:28
Thank you for sharing. I have got the same result - an unnecessary scroll.

**Comment by AMBudnik** [comment] 2018-04-27 13:28
The issue is still replicable in v `2.0.0`

**Comment by AMBudnik** [comment] 2019-10-22 09:04
The issue is gone if we remove the `overflow: hidden` Updated example http://jsfiddle.net/qxzLne8r/ (`7.2.1`).

However, we get an additional layer? (right side of the table)

![image](https://user-images.githubusercontent.com/10757813/67271396-b5a38e00-f4ba-11e9-8ebf-f046b2574091.png)

Tested on Chrome 77, Firefox,  on Windows 10

With Edge is even worse (+ additional scroll gone after grabbing)

![image](https://user-images.githubusercontent.com/10757813/67271514-f3a0b200-f4ba-11e9-82e4-fed6263b6dd2.png)

but it is looks the (nearly) same if we click the table

![image](https://user-images.githubusercontent.com/10757813/67271616-221e8d00-f4bb-11e9-8ac1-0aea125784e5.png)

but `C`'s and `E`'s border is doubled.

![GIF](https://user-images.githubusercontent.com/10757813/67271834-a3761f80-f4bb-11e9-9c50-e4149e8085b2.gif)

**Comment by AMBudnik** [comment] 2020-05-07 13:07
I'm glad to finally announce that the **issue is solved** in 8.0.0.-beta2-rev1 http://jsfiddle.net/5bt1dLkh/

**Comment by AMBudnik** [comment] 2020-07-16 10:16
Hi @HaroldStruwig 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment] 2020-08-06 11:37
Hi @HaroldStruwig 

here's a demo updated to v 8.0.0 http://jsfiddle.net/vh2r9w65/

Please confirm if it works for you as well.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback.

**Closed by AMBudnik** 2020-08-06 11:37 UTC
Labels: Core: alignment/height/width, Hiding, Type: Bug
