### ISSUE TITLE
Saving data with persistentState

### ISSUE THREAD

**Issue by Newwer21** [handsontable/handsontable#2113] opened 2015-01-27 13:58 UTC
Hello :)

I have a problem to use persistentState with handsontable. See below my code.
When I click on the button "Sauvegarder", I should save the data with persistentStateSave function.
I have followed https://github.com/handsontable/handsontable/wiki/Options#how-to-save-data-locally
I put persistentState : true, at the initialization of handsontable but it is not working...

I saw, in the article there are **persistantState** and **persistentState**, i tried both but still nothing.

```
<!DOCTYPE html>
<html lang="fr">
    <head>
       <script type="text/javascript" src="js/jquery.js"></script>
       <script type="text/javascript" src="js/jquery-ui.js"></script>
       <script type="text/javascript" src="js/handsontable.js"></script>

       <link rel="stylesheet" type="text/css" href="css/jquery-ui.css">
       <link rel="stylesheet" type="text/css" href="css/handsontable.full.css">
       <meta charset="UTF-8">
       <title>Handsontable</title>
    </head>
<script>
$(document).ready(function() {

    $('.save').click(function() {
        var instance = container.handsontable('getInstance');
        console.log(instance);
        instance.persistentStateSave('variable', instance.getData());
    });

    var data = [
                    [ "a", "b", "c", 1, 2 ], 
                    [ "x", "y", "z", 3, 4 ] 
               ]

    var container = $('#table');
    var hot = container.handsontable({
        persistentState: true,
        data: data,
        startRows: 5,
        startCols: 5,
        minRows: 5,
        minCols: 5,
        maxRows: 10,
        maxCols: 10,
        rowHeaders: true,
        colHeaders: true,
        minSpareRows: 1,
        contextMenu: true,
        colWidths: [100, 150, 150, 150, 150],
        columns: [
            {
                type: 'date', dateFormat: 'dd/mm/yy'
            },
            {

            },
            {
                type: 'autocomplete', 
                allowInvalid: true,
                source: function (query, process) {
                    var val = container.handsontable('getDataAtCell', this.row, 0);
                    if(val)
                        process(['black', 'blue', 'blanc', 'beurre', 'vache', 'beer', 'goods']);

                }               
            },
            {
                type: 'autocomplete', 
                allowInvalid: true,
                source: function (query, process) {
                    var val = container.handsontable('getDataAtCell', this.row, 2);
                    if(val)
                        process(['Souris', 'Baleine', 'Bat', 'Bot', 'vache', 'Bear', 'Girafe']);
                }       
            },
            {

            }
        ],
        className: "htCenter",

        cells: function(row, col, prop) {
            var cellProperties = {};
            // console.log(prop);
            // console.log(container.handsontable('getInstance'));
            // var metaCell = this.instance.getCellMeta(row, col);
            // if (metaCell.readOnly)
            // {
            //  console.log('readOnly');
            //  cellProperties.readOnly = true;
            // }

            return cellProperties;
        }

    });

    Handsontable.PluginHooks.add('afterSelectionEnd', function() {
        var current_row = this.getSelected();
        // alert(current_row[1]);
        if (current_row[1] == 2) // Col 2
        {
            if (!this.getDataAtCell(current_row[0], 0))
            {
                alert('Manque une date !');
                this.selectCell(current_row[0], 0);
                $(this.getCell(current_row[0], 0)).css('background-color', 'red');
                this.selectCell(1, 1);
                $(this.getCell(1,1)).css('background-color', 'grey');
                $(this.getCell(1,1)).addClass('htDimmed');

            }
        }
        else if (current_row[1] == 3) // Col 2
        {
            if (!this.getDataAtCell(current_row[0], 2))
            {
                alert('Un type est nécessaire !');
                this.selectCell(current_row[0], 2);
                $(this.getCell(current_row[0], 2)).css('background-color', 'red');
                // console.log(this.getCellMeta(1,1));
                // this.setCellMeta('setCellReadOnly',1,0);
                // console.log(this.getCellMeta(1,1));
                $(this.getCell(1,1)).prop('disabled', 'true');

            }
        }

    });
});
</script>
<body>
    <div id="table" class="handsontable"></div>
    <button class="save">Sauvegarder</button>
    <button class="load">Charger</button>

</body>
</html>
```

Thank you.

**Comment by theinventor** [comment] 2015-01-30 15:56
@Newwer21 can you put this in a jsbin or something so we can see it work/fail?

**Comment by Newwer21** [comment] 2015-02-02 09:33
I have put my code, in Jsfiddle. http://jsfiddle.net/q1mwd07f/
When I click in the button "Sauvegarder" I have a notification in the console : 
*TypeError: instance.persistentStateSave is not a function*
![Message d'erreur](https://cloud.githubusercontent.com/assets/9268540/5998322/56ac4fd8-aac6-11e4-8ef8-e72a4f8358b6.png)

**Comment by Berus** [comment] 2015-02-02 21:13
Hi @Newwer21 

Maybe try to look at source code in example http://handsontable.com/demo/column_resize.html.

**Comment by Newwer21** [comment] 2015-02-03 10:44
Hi @Berus :)
I took handonstable options from the source code and put it in my code, but still nothing.
This is my new code http://jsfiddle.net/2v5as3yy/
I have the same error *TypeError: instance.persistentStateSave is not a function*...

**Comment by AMBudnik** [comment] 2016-03-21 12:28
As this topic's activity ended a year ago I'm closing it, but @Newwer21 if you're still having any issues related to this topic please leave a comment

**Comment by chevinbrown** [comment] 2016-06-06 13:07
@AMBudnik, I think this is still an issue for many of us. persistentStateSave is not a function...

**Comment by AMBudnik** [comment] 2016-06-06 13:25
ok, reopening
simplified demo: http://jsfiddle.net/roaor4o6/

**Comment by wojciechczerniak** [comment] 2019-03-06 13:05
Looks like `persistentStateSave` was never a function. It's one of the hooks which you have to run or add a listener to https://handsontable.com/docs/tutorial-load-and-save.html#page-saving

I'm closing the issue as this is not a bug and an outdated topic.

**Closed by wojciechczerniak** 2019-03-06 13:05 UTC
Labels: Plugin: persistent state, Type: Bug

**Comment by chevinbrown** [comment] 2019-03-06 14:39
Thanks @wojciechczerniak! I was pretty junior at the time--sorry for any misinformation.
