### ISSUE TITLE
[Safari] manualRowResize e2e test does not pass on Safari 

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6602] opened 2020-01-07 11:17 UTC
### Description

Two e2e test does not pass on Safari 13.

```
Filters UI > should inherit font family and size from body
Expected '16.799999237060547px' to be '16.8px'.
```

```
MultiColumnSorting > Numbers presenting sorting sequence > should be properly hided when just one column is sorted
Expected '' to equal 'none'.
```

### Your environment
* Browser Name and version: Safari 13
* Operating System: macOs Catalina 10.15

**Comment by pnowak** [comment] 2020-08-28 10:26
The error `Filters UI > should inherit font family and size from body
Expected '16.799999237060547px' to be '16.8px'.` is still presents in version 8.0.0.

**Comment by swistach** [comment] 2020-09-09 13:18
I cannot reproduce both of the above problems (Safari 13.1.2, Retina screen)
But I found another problem related to AutoColumnSize.

Failed test: `manualRowResize > should resize appropriate rows to calculated autoRowSize height after double click on row handler after updateSettings usage with new `rowHeights` values`

If we have default column width (50px) - on Safari occurs a bug with calculating the true size of the cell's content.
The effect of setting value as `Longer\ntext` is as you can see below:
![image](https://user-images.githubusercontent.com/11849621/92603523-b2221c80-f2af-11ea-8b99-2b1a323255c8.png)

**Comment by aninde** [comment] 2020-09-09 14:04
I can confirm @swistach results. After performing tests on private windows in `Safari 13.1.2` on macOS Catalina MacBook Pro (Retina, 15-inch, Mid 2015) only one not passed.
``manualRowResize > should resize appropriate rows to calculated autoRowSize height after double click on row handler after updateSettings usage with new `rowHeights` values``

<img width="1154" alt="Screenshot 2020-09-09 at 16 02 55" src="https://user-images.githubusercontent.com/30186818/92608723-029c7880-f2b6-11ea-9386-1bd60712d287.png">

so I'm changing the title instead of closing it and creating a new issue.

**Comment by swistach** [comment] 2020-09-16 12:47
I clarified the bug with AutoColumnSize on Safari in a separated issue: #7262. I close this issue due to it's a bug in code not in an unstable test.

**Closed by swistach** 2020-09-16 12:47 UTC
Labels: Auto column size, Safari, Tests: E2E, Type: Bug
