### ISSUE TITLE
1st cell of a dropdown column gets hidden

### ISSUE THREAD

**Issue by sajjanbalar** [handsontable/handsontable#2613] opened 2015-07-07 05:25 UTC
Hi,

I have created a table with fixedColumnsLeft:2. When I try to select a value for the 1st cell of a column which is of dropdown type, the entire row gets hidden with only the bottom boundary of the 1st row seen.
![before](https://cloud.githubusercontent.com/assets/6851208/8539226/69f21808-2496-11e5-920b-5c6c2a486b75.png)
Here you see that I am changing the value of the first cell of a dropdown type column.
![during](https://cloud.githubusercontent.com/assets/6851208/8539234/87dcd2cc-2496-11e5-9f3a-48c3e93bd976.png)
And the first row gets hidden after the change is done!
![after](https://cloud.githubusercontent.com/assets/6851208/8539238/9b677b6c-2496-11e5-9c7b-17451f66b470.png)

**Comment by AMBudnik** [comment] 2015-07-07 15:36
Hi @sajjanbalar I made an example as you described [here](https://jsfiddle.net/4tnjm5zr/) but I cannot reproduce it. Can you create a demo of your code?

**Comment by AMBudnik** [comment] 2015-08-21 17:32
Issue closed in lack of demo or author's reply

**Closed by AMBudnik** 2015-08-21 17:32 UTC
Labels: Demo needed
