### ISSUE TITLE
ContextMenu "insert row above" (or below) add row twice

### ISSUE THREAD

**Issue by beppause-it** [handsontable/handsontable#8316] opened 2021-06-25 20:29 UTC
### Description
When the context menu is enabled and the insert row above or below is clicked  two rows are added the first one in the correct position and another row is added at the end of the table (and do not accept any values inside cells)

### Steps to reproduce
1. enable in settings contextMenu to true
2. open context menu end click Insert Row above (or below is the same)
3. the correct row is added, but another row is added at the end of the table
4. the seme appends calling the method hot.alter('insert_row'). 

### Demo
https://jsfiddle.net/b8j5mn3f/2/

### Your environment
* Vue wrapper version: 9.0.1
* Handsontable version: 9.0.1
* Browser Name and version: Chrome 91.0.4472.114 (Build ufficiale) (a 64 bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2021-06-28 08:37
Hi @beppause-it 

I have reported the same issue here https://github.com/handsontable/handsontable/issues/8148
It is a regression for version 8.4.0.

I am closing this issue as a duplicate of https://github.com/handsontable/handsontable/issues/8148 but will update you as soon as we fix it.

**Closed** 2021-06-28 08:37 UTC
Labels: Type: Duplicate, vue
