### ISSUE TITLE
update settings - afterScrollVertically not overrided(changed) ,but added

### ISSUE THREAD

**Issue by mainstream95** [handsontable/handsontable#3357] opened 2016-03-27 15:57 UTC
when update settings each time, old callback stays the same and new function called also

http://jsfiddle.net/co9tscsk/5/

or i miss something?

**Comment by AMBudnik** [comment] 2016-03-29 07:21
Thanks for sharing @mainstream95 
Confirmed.

**Comment by AMBudnik** [comment] 2017-01-20 08:32
Still replicable, demo http://jsfiddle.net/handsoncode/oLgv3czb/
1. `readOnly` state stays the same
2. `afterScrollVertically` is not changed

**Comment by AMBudnik** [comment] 2018-04-30 12:52
Hi @mainstream95 
It looks like now the scoll calls only the second log (updated version).
Can you check if the `afterScrollVertically` is gone in your project after updating to `2.0.0`?

**Comment by AMBudnik** [comment] 2018-05-17 12:26
I think that we can close this issue as there's no reply for more than 2 weeks

**Closed by AMBudnik** 2018-05-17 12:26 UTC
Labels: Status: Answered
