### ISSUE TITLE
The numeric cell type does not support the scientific E notation

### ISSUE THREAD

**Issue by kkrusty1** [handsontable/handsontable#2030] opened 2015-01-07 14:42 UTC
Consider this fiddle:
http://jsfiddle.net/uocqr83y/1/

At some point in the loop, the calculated value to put in the cells will be in scientific notation (e.g. 1e-7). The values in the cells are still valid but they are displayed in red. Also, if you try to enter manually the value 1e-7 in a cell, it will convert to -17.

The red cells can be confusing if you reduce the precision to 3 digits like in this other fiddle:
http://jsfiddle.net/uocqr83y/

**Comment by AMBudnik** [comment] 2015-03-13 13:35
Thank you for that report.

**Comment by AMBudnik** [comment] 2016-06-27 10:33
Still reproducible in 0.26.0 (switched to numbro), demo: http://jsfiddle.net/gk10o1Lm/

**Comment by osaingre** [comment] 2016-11-08 19:44
I came across this bug three days ago and could not believe my eyes... It's huge enough to make me move away from the library.
I think the bug has to do with the default number validator that uses an obviously wrong regex to validate numbers:
>  /^-?\d*(\.|\,)?\d*$/

I worked around it by writing a custom number validator.

**Comment by AMBudnik** [comment] 2016-11-09 08:20
Hi @osaingre 
thanks for your investigation. IF you could create a PR to develop I'd be more than happy to ask our devs to check it and merge to fix the issue.

**Comment by osaingre** [comment] 2016-11-09 09:04
Hi Aleksandra
I will gladly submit a patch.
Thanks,
Olivier

**Comment by CrackAttack** [comment] 2016-12-14 02:19
I had the same issue. In my particular case, I solved it by replacing the code taken from numeral.js at the bottom of my (0.11.4) jquery.handsontable.full.js file, with the latest code from http://numeraljs.com/ which has a numeral.js version 2.0.1, and it started working fine immediately. This should be a very easy update, no?  

For those that are stuck on older handsontable code, replacing the code as I did might be a quick option, as it seems to work so far (knock on wood)...

**Comment by jeffrey-cochran** [comment] 2017-04-13 17:43
@AMBudnik Was this ever resolved in a release?

**Comment by AMBudnik** [comment] 2017-04-14 07:58
@jeffrey-cochran the issue is opened and unfortunately, we did not published the fix yet.

**Comment by AMBudnik** [comment] 2018-01-16 12:16
Issue replicable in version 0.35.0
Updated demo: http://jsfiddle.net/Lz1td4sd/

**Comment by moodyroto** [comment] 2018-03-16 16:24
FYI, I've added a PR to address this issue (https://github.com/handsontable/handsontable/pull/4948).

**Comment by swistach** [comment] 2018-05-25 11:13
We will add support for scientific notation as a part of a migration to the latest version of the Numbro library #5081.

**Comment by JSalter02** [comment] 2018-07-11 13:06
Hey guys,

I'm working with version 4 and 5, and this is still not solved.

Note that very large or small numbers are automatically converted to scientific notation by javascript, so this can't really be avoided. You should be able to support manually-typed in scientific notation (1.5e8) or scientific notation auto-converted from a large or small number (1200000000000000000000 = 1.2e+21)

Javascript handles these numbers just fine. 

You can see this error by typing in a very small or very large number on your own docs:
https://docs.handsontable.com/pro/5.0.0/demo-numeric.html

**Comment by JSalter02** [comment] 2018-07-13 11:41
OK, here's the issue I think:

On line 66769, you use this test for numeric validation:
`/^-?\d*(\.|,)?\d*$/`
That validation does not allow for scientific notation.

Whereas on line 1908 you use a much more thorough test for determining "isNumeric" which includes this:
`/^\s*[+-]?\s*(?:(?:\d+(?:\.\d+)?(?:e[+-]?\d+)?)|(?:0x[a-f\d]+))\s*$/`

Why? Seems like you should just use your isNumeric function (or the same regexp) to determine numeric validation.

**Comment by wojciechczerniak** [comment] 2018-07-13 13:08
@JSalter02 Thanks for investigation and PR. I'm reopening issue and will queue this for review.

**Comment by AMBudnik** [comment] 2018-12-12 13:22
Thank you for feedback. I am really happy that we have finally fixed that issue.

Please update to v6.2.1 to see changes

**Closed by AMBudnik** 2018-12-12 13:22 UTC
Labels: Cell type: numeric, Status: Released, Type: Bug
