### ISSUE TITLE
Scrollbar Jumps up

### ISSUE THREAD

**Issue by kquinn45** [handsontable/handsontable#2553] opened 2015-06-16 12:59 UTC
When scrolling to the bottom of a large grid (descent amount of scrolling) the scroll bar will continually jump up about 10 lines whenever it should hit the bottom.  If I re-size my browser window the problem seems to go away.

**Comment by AMBudnik** [comment] 2015-06-18 19:48
Hi @kquinn45 which browser/OS systems are you using?

**Comment by kquinn45** [comment] 2015-06-18 19:54
I'm using Chrome 43 on Windows 7.

**Comment by AMBudnik** [comment] 2015-06-19 10:47
Thank you @kquinn45

**Comment by AMBudnik** [comment] 2016-03-21 15:41
I couldn't reproduce it with the latest 0.24.1 version. @kquinn45 can you check it please? Demo using 0.24.1:https://docs.handsontable.com/0.24.1/demo-scrolling.html

**Comment by kquinn45** [comment] 2016-03-21 19:37
I haven't experienced the issue for awhile now, it seems to be fixed.

**Comment by AMBudnik** [comment] 2016-03-22 08:15
Thanks for feedback @kquinn45 
I assume I can close this issue.

**Closed by AMBudnik** 2016-03-22 08:15 UTC
Labels: Answered
