### ISSUE TITLE
Hidden columns become visible when we run `hot.updateSettings`

### ISSUE THREAD

**Issue by ankushgoel** [handsontable/handsontable#4251] opened 2017-05-17 13:24 UTC
Description
Hidden columns become visible when we run `hot.updateSettings`

Demo
http://jsfiddle.net/ankushgoel/sj0q574z/

**Comment by ankushgoel** [comment] 2017-05-17 13:33
This issue only comes when we use hiddenColumns plugin.

http://jsfiddle.net/ankushgoel/sj0q574z/1/
Defining `hiddenColumns` in `hotSettings` works great. But we need to use plugin as it is much faster than doing the same via `updateSettings`

**Comment by AMBudnik** [comment] 2017-05-17 13:35
Yes, you are right. I just have checked the `updateSettings` at http://jsfiddle.net/handsoncode/wvt4rfey/

**Comment by ankushgoel** [comment] 2017-05-17 13:41
May I know when will this bug get fixed?

**Comment by AMBudnik** [comment] 2017-05-19 08:23
Hi @ankushgoel 

we are currently working on pushing the stable version for Handsontable PRO (just release a beta yesterday) so we cannot schedule new bug fixes before we fix the bugs that were made after the last update.

I will mark the issue as a bug to remeber about it.

**Comment by AMBudnik** [comment] 2018-01-22 14:32
Issue seems to be gone in v1.15.0
http://jsfiddle.net/8exnfyc6/

Please correct me if I'm wrong @ankushgoel

**Comment by AMBudnik** [comment] 2018-01-31 11:21
The issue is still replicable. Demo to test http://jsfiddle.net/sj0q574z/3/

**Comment by danbrenden** [comment] 2018-06-15 10:01
The problem with hiddenColumns is still a problem in version 4.0.

**Comment by toroc** [comment] 2018-09-07 21:39
@AMBudnik this should definitely be considered a bug with Handsontable in general. When I open an excel document that has 5 columns of data, if I hide the third column, i don't expect to see the third column again when I resize the first column or update a formatting setting for a cell. Why should HOT be any different? Initializing the table with hidden columns is not an option. 

`updateSettings` is way too slow. It takes `768.5ms` to hide a column, wherease hideColumns combined with render only takes `304.6ms`.

![2018-09-07_14-37-00_hot_updatesettings_hide](https://user-images.githubusercontent.com/9097432/45244193-97290600-b2ab-11e8-8d2c-306845386252.png)

![2018-09-07_14-36-32_hot_hide_col_plugin](https://user-images.githubusercontent.com/9097432/45244194-9c865080-b2ab-11e8-993e-dce983d4b7c6.png)

**Comment by AMBudnik** [comment] 2018-10-01 11:46
Sorry but this issue is content to too many other issues. We won't be able to add it to the milestone for October.

**Comment by wojciechczerniak** [comment] 2019-02-19 11:34
Duplicate of #4121

**Closed by wojciechczerniak** 2019-02-19 11:34 UTC
Labels: Core: update settings, PRO: hiding, Type: Change

**Comment by AMBudnik** [comment] 2019-11-15 11:55
Hi @ankushgoel @toroc @danbrenden 

We just fixed an issue related to yours. Please update to 8.0.0-beta1 and check if it solved for you as well.

Below are the resources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`
