### ISSUE TITLE
Remove Row and Undo-Redo actions  does not work if sorting is enabled

### ISSUE THREAD

**Issue by lkoeller** [handsontable/handsontable#1520] opened 2014-06-06 14:35 UTC
Problem found on v 0.10.5
See jsfidlle : http://jsfiddle.net/7R96Y/2/

Important: due to issue #1516 (Remove Row then Undo action corrupts the undo stack if sorting is enabled), I explicitely disable the observeChanges parameter after starting handsontable instance (see jsfiddle)

Steps to reproduce : 

1) clic twice on col A to sort descending
2) right clic on row 3 (2008), and choose remove row
3) Undo 
   NOK --> table is corrupted
2009    20  11  14  13
2009    20  11  14  13
    Kia Nissan  Toyota  Honda
2010    30  15  12  13
4) Redo
  NOK --> table is corrupted
2009    20  11  14  13
2009    20  11  14  13
2010    30  15  12  13

Pb due to logical column number that are used for undo-redo, instead of physical col number.

I will propose a fix for that.

**Comment by AMBudnik** [comment] 2015-09-09 14:24
Confirmed with [0.17.0 version example](https://jsfiddle.net/7v97rzgm/)

**Comment by marc-antoinepelletier** [comment] 2015-10-07 09:57
I have the sorting at false, and I still have the problem..

**Comment by AMBudnik** [comment] 2016-03-16 11:00
Confirmed with 0.24.0, demo sorting newest version: https://jsfiddle.net/handsoncode/7v97rzgm/1/

**Comment by AMBudnik** [comment] 2016-06-27 11:46
still in 0.26.0 **https://jsfiddle.net/pkb84emw/**

**Comment by AMBudnik** [comment] 2017-01-23 12:48
Still replicable in v0.30.1, it looks like undo/redo holds old indexes - they don't update after sorting.

**Comment by AMBudnik** [comment] 2018-04-19 09:54
The issue is still replicable in v `2.0.0`. I've also tested some older versions but `0.20.0` works even worse as undo changes all the rows, not only the 3rd row.

**Comment by IamPitchou** [comment] 2018-05-15 12:28
Hi! 
Any news on that topic? That kind of bug is very unconvienent for a user who sorts on a specific column but cannot undo a modification. And it is blocker for our project.

If you have any timeline about when do you plan to fix it, it would help us to choose the right library to use for our project. 
Thank you very much!

**Comment by jvcalahi** [comment] 2018-07-14 06:46
Hi,

Any updates on this issue? Having sorting enabled, and doing "undo" still returns the wrong value. Can be replicated on Handsontable Examples link.

**Comment by AMBudnik** [comment] 2018-07-16 06:31
Sorry @jvcalahi no updates yet

**Comment by kalugny** [comment] 2018-08-26 13:35
Is this still open?
There has been at least two "major" releases since this...

**Comment by AMBudnik** [comment] 2018-08-27 07:13
We are mainly closing the `regression` and `high` priority bugs. The undoRedo plugin needs to adjustments itself that is why the issue is still opened.

**Comment by AMBudnik** [comment] 2018-10-04 11:53
Still replicable in v `6.0.1`

**Comment by pnowak** [comment] 2018-12-06 14:19
It's seems that this issue is fixed with this one - #3188 

Can @lkoeller @IamPitchou @jvcalahi @kalugny confirm? 
Thanks.

**Comment by AMBudnik** [comment] 2019-04-17 12:56
I believe that we can close the issue as there's no response here. If you're still facing some similar cases after updating to the newest version please let me know.

**Closed by AMBudnik** 2019-04-17 12:56 UTC
Labels: Column sorting, Type: Bug, Undo-redo
