### ISSUE TITLE
Comparise cut behaving 

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6065] opened 2019-06-21 11:23 UTC
### Description
In `handsontable` almost all cell type - `numeric`, `date`, `time`, `select`, `dropdown`, `autocomplete`, `handsontable` and `text` - behave the same when we use `ctrl (cmd) + x`: value from the cell deletes immediately.
If cell type is `password` - nothing do, the value from the cell is untouched.
But when we have `checkbox` cell is only unchecked (previous was #bad-value#).

In Google Spreadsheets behaving are more consistency - when we have  `cut` actions all cell type inclusive `checkbox` created borders and value be deleted only when paste it to the new cell.

So we need to consider whether we should be like more consistency whit Google Spreadsheets (and Excel).

### Related issue(s):
https://github.com/handsontable/handsontable/issues/5405
https://github.com/handsontable/handsontable/issues/5245#issuecomment-465140479

### Demo
`cut` actions in Google Spreadsheets:
http://g.recordit.co/Y6bUxyzOXr.gif

`delete` actions in Google Spreadsheets:
http://g.recordit.co/cFpWCwTqX4.gif

`cut` and `delete` actions in Handsontable:
http://g.recordit.co/ZDbGpxWIlA.gif

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by keyserfaty** [comment] 2020-01-04 16:08
Hey :) any news on this?

**Comment by AMBudnik** [comment] 2020-01-07 14:14
The subject is marked to be discussed as there is no one right answer on how to deal with this subject.  
We'll surely update it once we pick one way to complete the goal.

**Comment by wojciechczerniak** [comment] 2020-07-01 20:42
This will be implemented with our new formula plugin that is based on HyperFormula engine. To support fully the new engine copy/cut/paste and relative formulas we will have to redo the cut functionality. More details in #6767

Duplicate of #6767

**Closed by wojciechczerniak** 2020-07-01 20:42 UTC
Labels: Cell type: checkbox, Copy-paste, Status: To be discussed
