### ISSUE TITLE
startPositions.at is not a function

### ISSUE THREAD

**Issue by jingshou** [handsontable/handsontable#10334] opened 2023-04-22 01:18 UTC
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/nL8sry9u/

### Your environment
* Vue 3 wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:
vue-router.esm-bundler.js:72 [Vue Router warn]: uncaught error during route navigation:
warn @ vue-router.esm-bundler.js:72
triggerError @ vue-router.esm-bundler.js:3300
(anonymous) @ vue-router.esm-bundler.js:3338
Promise.catch (async)
handleScroll @ vue-router.esm-bundler.js:3338
finalizeNavigation @ vue-router.esm-bundler.js:3195
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js:3038
push @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:4399
(anonymous) @ main.ts:16
vue-router.esm-bundler.js:3302 TypeError: startPositions.at is not a function
    at ViewportRowsCalculator2.calculate (viewportRows.mjs:143)
    at new ViewportRowsCalculator2 (viewportRows.mjs:86)
    at Viewport2.createRowsCalculator (viewport.mjs:319)
    at Viewport2.createRenderCalculators (viewport.mjs:397)
    at MasterTable2.draw (table.mjs:287)
    at Walkontable2.draw (_base.mjs:143)
    at WalkontableFacade2.draw (core.mjs:181)
    at TableView2.render (tableView.mjs:202)
    at Core.init (core.mjs:1107)
    at Proxy.hotInit (vue-handsontable.mjs:185)
triggerError @ vue-router.esm-bundler.js:3302
(anonymous) @ vue-router.esm-bundler.js:3338
Promise.catch (async)
handleScroll @ vue-router.esm-bundler.js:3338
finalizeNavigation @ vue-router.esm-bundler.js:3195
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js:3038
push @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:4399
(anonymous) @ main.ts:16
2viewportRows.mjs:143 Uncaught (in promise) TypeError: startPositions.at is not a function
    at ViewportRowsCalculator2.calculate (viewportRows.mjs:143)
    at new ViewportRowsCalculator2 (viewportRows.mjs:86)
    at Viewport2.createRowsCalculator (viewport.mjs:319)
    at Viewport2.createRenderCalculators (viewport.mjs:397)
    at MasterTable2.draw (table.mjs:287)
    at Walkontable2.draw (_base.mjs:143)
    at WalkontableFacade2.draw (core.mjs:181)
    at TableView2.render (tableView.mjs:202)
    at Core.init (core.mjs:1107)
    at Proxy.hotInit (vue-handsontable.mjs:185)
calculate @ viewportRows.mjs:143
ViewportRowsCalculator2 @ viewportRows.mjs:86
createRowsCalculator @ viewport.mjs:319
createRenderCalculators @ viewport.mjs:397
draw @ table.mjs:287
draw @ _base.mjs:143
draw @ core.mjs:181
render @ tableView.mjs:202
Core.init @ core.mjs:1107
hotInit @ vue-handsontable.mjs:185
mounted @ vue-handsontable.mjs:244
(anonymous) @ runtime-core.esm-bundler.js:2757
callWithErrorHandling @ runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:182
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2731
flushPostFlushCbs @ runtime-core.esm-bundler.js:359
flushJobs @ runtime-core.esm-bundler.js:413
Promise.then (async)
nextTick @ runtime-core.esm-bundler.js:260
(anonymous) @ scrollbar.vue:190
(anonymous) @ runtime-core.esm-bundler.js:2757
callWithErrorHandling @ runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:182
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2731
flushPostFlushCbs @ runtime-core.esm-bundler.js:359
flushJobs @ runtime-core.esm-bundler.js:413
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:298
queuePostFlushCb @ runtime-core.esm-bundler.js:320
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1604
scheduler @ runtime-core.esm-bundler.js:1838
triggerEffect @ reactivity.esm-bundler.js:400
triggerEffects @ reactivity.esm-bundler.js:390
triggerRefValue @ reactivity.esm-bundler.js:1021
(anonymous) @ reactivity.esm-bundler.js:1158
triggerEffect @ reactivity.esm-bundler.js:400
triggerEffects @ reactivity.esm-bundler.js:385
triggerRefValue @ reactivity.esm-bundler.js:1021
(anonymous) @ reactivity.esm-bundler.js:1158
triggerEffect @ reactivity.esm-bundler.js:400
triggerEffects @ reactivity.esm-bundler.js:385
triggerRefValue @ reactivity.esm-bundler.js:1021
set value @ reactivity.esm-bundler.js:1066
finalizeNavigation @ vue-router.esm-bundler.js:3194
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js:3038
push @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:4399
(anonymous) @ main.ts:16
viewportRows.mjs:143 Uncaught (in promise) TypeError: startPositions.at is not a function
    at ViewportRowsCalculator2.calculate (viewportRows.mjs:143)
    at new ViewportRowsCalculator2 (viewportRows.mjs:86)
    at Viewport2.createRowsCalculator (viewport.mjs:319)
    at Viewport2.createRenderCalculators (viewport.mjs:397)
    at MasterTable2.draw (table.mjs:287)
    at Walkontable2.draw (_base.mjs:143)
    at WalkontableFacade2.draw (core.mjs:181)
    at TableView2.render (tableView.mjs:202)
    at Core.init (core.mjs:1107)
    at Proxy.hotInit (vue-handsontable.mjs:185)

**Comment by AMBudnik** [comment] 2023-04-24 07:10
Hi @jingshou 

I do not see any reports in our system about `startPositions.at is not a function` error. Could you share a demo where we will be able to replicate the issue?

**Comment by xiaoshuoyiyi** [comment] 2023-04-27 02:57
I had the same problem

**Comment by AMBudnik** [comment] 2023-04-27 07:13
Hi @xiaoshuoyiyi Could you tell me when did error popped and could you point out steps for me to replicate the issue? It seems like a Core error (selection/autofill) but without a demo it would be hard to help.

**Comment by xiaoshuoyiyi** [comment] 2023-04-27 07:23
@AMBudnik The cause of this problem has been found, V12.3.3 uses the array at() method, but this is limited to the version of Google Chrome, my browser version is too low, causing this error! Lowering the version of the library or upgrading the version of Google Chrome can solve this problem!

**Comment by AMBudnik** [comment] 2023-04-27 11:02
Thank you for feedback @xiaoshuoyiyi that's really valuable.

**Comment by AMBudnik** [comment] 2023-05-11 06:43
This topic has been copied to our internal ticketing system for further investigation.

Currently, our rule is to be compatible with the last two versions of a browser, as mentioned in our documentation [here](https://handsontable.com/docs/javascript-data-grid/supported-browsers/). However, I have raised the question to determine if this rule also applies in this particular case.

@jingshou, I will close this topic and notify you if the decision differs from what was mentioned above.

**Closed by AMBudnik** 2023-05-11 06:43 UTC
Labels: Status: Answered
