### ISSUE TITLE
Memory leak: skipLengthCache and more..

### ISSUE THREAD

**Issue by tsohr** [handsontable/handsontable#5815] opened 2019-02-23 00:26 UTC
### Description

Overall performance getting slower and can observe memory leaks while calling loadData() many times. 

### Steps to reproduce

1. Fiddle here https://jsfiddle.net/4de682vw/4/ 
2. DevTools > Memory > Heap snapshot for "fiddle.jshell.net" 
3. click Repeat x1000 (loadData() 1k times)
4. Garbage collect and take the second snapshot
5. Snapshot Compare. https://imgur.com/a/sLbfGZ8
6. and seeing this bug location: 

### Demo

https://jsfiddle.net/4de682vw/4/ 

### Your environment
* Handsontable version: 6.2.2, Pro
* Browser Name and version: "5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"
* Operating System: Fedora 29

### Bug location I found: 
based on this compiled file: https://cdn.jsdelivr.net/npm/handsontable-pro/dist/handsontable.full.js

 1. add hook.. 

```
72762,72764c72765,72767
<   this.instance.addHook('skipLengthCache', function (delay) {
<     return _this.onSkipLengthCache(delay);
<   });
---
>   // this.instance.addHook('skipLengthCache', function (delay) {
>   //   return _this.onSkipLengthCache(delay);
>   // });
```

2 and the timer. Can we move this task into a sth like.. a global queue? 

```
73601,73604c73604,73607
<   this.skipCache = true;
<   setTimeout(function () {
<     _this5.skipCache = false;
<   }, delay);
---
>   // this.skipCache = true;
>   // setTimeout(function () {
>   //   _this5.skipCache = false;
>   // }, delay);
```

3. one more.. fastInnerHTML for the row header: Avoid to recreate nodes if the content was the same.
```
1311c1311,1314
<     element.innerHTML = content;
---
>     if (element.innerHTMLsrc != content) {
>       element.innerHTML = content;
>       element.innerHTMLsrc = content;
>     }

```

Works fine for me after I comment out of those location temporarily. Can't have more time to fix..

**Comment by wojciechczerniak** [comment] 2019-02-25 12:19
Issue with hook looks like a duplicate of #5727

We also have an issue for rendering only nodes that were changed  #5769

Thanks for investigating the issues and all the details, they are very helpful.

**Comment by tsohr** [comment] 2019-02-25 12:24
Cool, @wojciechczerniak . The two issues are pointing out correctly. 
Hope to see the issues solved soon. Cheers

**Comment by wojciechczerniak** [comment] 2019-02-25 12:39
#5769 is already in progress. #5727 looks like a leak so we will check it asap.

Thanks for confirmation. I'm closing this issue as a duplicate.

**Closed by wojciechczerniak** 2019-02-25 12:39 UTC

**Comment by wow-222** [comment] 2019-05-27 07:35
@wojciechczerniak 
Hello, I found this memory leak problem in IE. Is it solved now?

**Comment by AMBudnik** [comment] 2019-05-27 07:46
@wow-222 any other than this one https://github.com/handsontable/handsontable/issues/5727#issuecomment-496114174?
