### ISSUE TITLE
Bug Example changing cell type from a dropdown menu in cell header

### ISSUE THREAD

**Issue by bipholai** [handsontable/handsontable#1964] opened 2014-12-05 09:01 UTC
Hi.
This example has broken. Please check this, I suffer from a similar problem when use 0.12.1
*Chrome*
![chrome](https://cloud.githubusercontent.com/assets/7520143/5313161/a20a2926-7c97-11e4-9ff0-c5bf95ccb22d.JPG)
*Firefox*
![firefox](https://cloud.githubusercontent.com/assets/7520143/5313162/a20bc0ec-7c97-11e4-9e72-c7af1f96813b.JPG)

**Comment by konijn** [comment] 2015-01-09 19:10
This also does not work in the demo : 
http://handsontable.com/demo/renderers_html.html#dropdown

**Comment by kubak10** [comment] 2015-03-19 10:11
To check in other machine.
Works well on Safari but there is small issue in Chrome.
Maybe coused by my browser

![zrzut ekranu 2015-03-19 o 10 55 50](https://cloud.githubusercontent.com/assets/701357/6728236/bd0b6b26-ce28-11e4-9406-87869b2d949d.png)

**Comment by budnix** [comment] 2015-03-19 10:24
Everything seams to be ok. Tested on latest chrome, FF, safari on OSX and Win 8.1

**Comment by jansiegel** [comment] 2015-03-19 10:26
Maybe @kubak10's issue is caused by some Chrome extensions, or something like that?
Let's merge this, and if it keeps happening, we'll reopen.

**Comment by krzysztofspilka** [comment] 2015-03-19 14:50
Released in ver. 0.13.1, full note available here: https://github.com/handsontable/handsontable/releases/tag/0.13.1

**Closed by krzysztofspilka** 2015-03-19 14:50 UTC
Labels: Bug, Priority: high, Released
