### ISSUE TITLE
When using custom parameters, you cannot merge rows that contain custom parameters

### ISSUE THREAD

**Issue by d-yh** [handsontable/handsontable#6244] opened 2019-09-04 07:51 UTC
Cannot Cross-merge cells in rows and columns with self-defined parameters。

`var data = [
            ['Example #1 (looking for particular words in a sentence)', '', '', '', '', '', '', ''],
            ['Text', 'yellow', 'red', 'blue', 'green', 'pink', 'gray'],
            ['Yellow dog on green grass', "=IF(ISNUMBER(SEARCH(B2, A3)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A3)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A3)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A3)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A3)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A3)), G2, '')"],
            ['Gray sweater with blue stripes', "=IF(ISNUMBER(SEARCH(B2, A4)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A4)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A4)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A4)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A4)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A4)), G2, '')"],
            ['A red sun on a pink horizon', "=IF(ISNUMBER(SEARCH(B2, A5)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A5)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A5)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A5)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A5)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A5)), G2, '')"],
            ['Blue neon signs everywhere', "=IF(ISNUMBER(SEARCH(B2, A6)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A6)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A6)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A6)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A6)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A6)), G2, '')"],
            ['Waves of blue and green', "=IF(ISNUMBER(SEARCH(B2, A7)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A7)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A7)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A7)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A7)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A7)), G2, '')"],
            ['Hot pink socks and gray socks', "=IF(ISNUMBER(SEARCH(B2, A8)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A8)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A8)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A8)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A8)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A8)), G2, '')"],
            ['Deep blue eyes', "=IF(ISNUMBER(SEARCH(B2, A9)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A9)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A9)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A9)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A9)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A9)), G2, '')"],
            ['Count of colors', '=COUNTIF(B3:B9, B2)', '=COUNTIF(C3:C9, C2)', '=COUNTIF(D3:D9, D2)', '=COUNTIF(E3:E9, E2)', '=COUNTIF(F3:F9, F2)', '=COUNTIF(G3:G9, G2)', '="SUM: "&SUM(B10:G10)'],
            ['', '', '', '', '', '', ''],
            ['Example #2 (extracting domains from emails)', '', '', '', '', '', ''],
            ['Name', 'Email', 'Email domain', '', '', ''],
            ['Ann Chang', 'achang@gmailtr.com', '=RIGHT(B14, LEN(B14) - FIND(EMAIL_SPLITTER, B14))', '=EMAIL_SPLITTER', '', '', ''],
            ['Jan Siuk', 'jan@yahootr.com', '=RIGHT(B15, LEN(B15) - FIND(EMAIL_SPLITTER, B15))', '', '', '', ''],
            ['Ken Siuk', 'ken@gmailtr.com', '=RIGHT(B16, LEN(B16) - FIND(EMAIL_SPLITTER, B16))', '', '', '', ''],
            ['Marcin Kowalski', 'ken@gmailtr.pl', '=RIGHT(B17, LEN(B17) - FIND(EMAIL_SPLITTER, B17))', '', '', '', ''],
        ];
        var example3 = document.getElementById('example3');
        /*var param = {};
        for(var i = 0;i<customerParams.length;i++){
            param[""+customerParams[i]] = 0;
        }*/

        /*var data = [];
        for(var i =0;i<valueList.length;i++){
            data.push(valueList[i]);
        }*/
        console.log(mergeCells);
        //param.DB_L_CD = 0;
        var hot3 = new Handsontable(example3, {
            data:data,
            colHeaders: true,
            rowHeaders: true,
            contextMenu: true,
            mergeCells:[
                /*mergeCells[2],
                mergeCells[3],
                mergeCells[4],
                {col:0,row:0,rowspan:1,colspan:3},
                {col:0,row:1,rowspan:1,colspan:3}*/
                {row: 0, col: 0, rowspan: 1, colspan: 8},
                {row: 11, col: 0, rowspan: 1, colspan: 8},
                {row: 14, col: 0, rowspan: 2, colspan: 1},
                //mergeCells[1],
            ],
            formulas: {
               /* variables: param*/
                variables:{
                    EMAIL_SPLITTER:'@'
                }
            },

        });`

If your merged cell column contains formulas for custom parameters, and the merged cell row contains formulas for custom parameters, the formulas and parameters will fail and become fixed initial values

**Comment by d-yh** [comment] 2019-09-04 07:59
<img src=http://chuantu.xyz/t6/702/1567583917x992245975.jpg />

**Comment by AMBudnik** [comment] 2019-09-04 09:39
Hey @d-yh 

can you share a JSFiddle/CodePen example? It will be much easier to share progress and tips.

**Comment by d-yh** [comment] 2019-09-04 09:47
@AMBudnik 
this is share url  https://jsfiddle.net/o41fv79s/1/ 。 
Formulas and parameters will fail

**Comment by d-yh** [comment] 2019-09-04 09:49
`
</style>< !-- Ugly Hack due to jsFiddle issue --><script src="https://cdn.jsdelivr.net/npm/handsontable@7.1.0/dist/handsontable.full.min.js"></script><link type="text/css"rel="stylesheet"href="https://cdn.jsdelivr.net/npm/handsontable@7.1.0/dist/handsontable.full.min.css">
<div>
  <div id="example3" class="hot scroll-container handsontable htRowHeaders htColumnHeaders"></div>
</div>

  var data = [
    ['Example #1 (looking for particular words in a sentence)', '', '', '', '', '', '', ''],
    ['Text', 'yellow', 'red', 'blue', 'green', 'pink', 'gray'],
    ['Yellow dog on green grass', "=IF(ISNUMBER(SEARCH(B2, A3)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A3)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A3)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A3)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A3)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A3)), G2, '')"],
    ['Gray sweater with blue stripes', "=IF(ISNUMBER(SEARCH(B2, A4)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A4)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A4)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A4)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A4)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A4)), G2, '')"],
    ['A red sun on a pink horizon', "=IF(ISNUMBER(SEARCH(B2, A5)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A5)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A5)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A5)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A5)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A5)), G2, '')"],
    ['Blue neon signs everywhere', "=IF(ISNUMBER(SEARCH(B2, A6)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A6)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A6)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A6)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A6)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A6)), G2, '')"],
    ['Waves of blue and green', "=IF(ISNUMBER(SEARCH(B2, A7)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A7)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A7)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A7)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A7)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A7)), G2, '')"],
    ['Hot pink socks and gray socks', "=IF(ISNUMBER(SEARCH(B2, A8)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A8)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A8)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A8)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A8)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A8)), G2, '')"],
    ['Deep blue eyes', "=IF(ISNUMBER(SEARCH(B2, A9)), B2, '')", "=IF(ISNUMBER(SEARCH(C2, A9)), C2, '')", "=IF(ISNUMBER(SEARCH(D2, A9)), D2, '')", "=IF(ISNUMBER(SEARCH(E2, A9)), E2, '')", "=IF(ISNUMBER(SEARCH(F2, A9)), F2, '')", "=IF(ISNUMBER(SEARCH(G2, A9)), G2, '')"],
    ['Count of colors', '=COUNTIF(B3:B9, B2)', '=COUNTIF(C3:C9, C2)', '=COUNTIF(D3:D9, D2)', '=COUNTIF(E3:E9, E2)', '=COUNTIF(F3:F9, F2)', '=COUNTIF(G3:G9, G2)', '="SUM: "&SUM(B10:G10)'],
    ['', '', '', '', '', '', ''],
    ['Example #2 (extracting domains from emails)', '', '', '', '', '', ''],
    ['Name', 'Email', 'Email domain', '', '', ''],
    ['Ann Chang', 'achang@gmailtr.com', '=RIGHT(B14, LEN(B14) - FIND(EMAIL_SPLITTER, B14))', '', '', '', ''],
    ['Jan Siuk', 'jan@yahootr.com', '=RIGHT(B15, LEN(B15) - FIND(EMAIL_SPLITTER, B15))', '', '', '', ''],
    ['Ken Siuk', 'ken@gmailtr.com', '=RIGHT(B16, LEN(B16) - FIND(EMAIL_SPLITTER, B16))', '', '', '', ''],
    ['Marcin Kowalski', 'ken@gmailtr.pl', '=RIGHT(B17, LEN(B17) - FIND(EMAIL_SPLITTER, B17))', '', '', '', ''],
  ];
  var example3 = document.getElementById('example3');

  var hot3 = new Handsontable(example3, {
    data: data,
    colHeaders: true,
    rowHeaders: true,
    contextMenu: true,
    formulas: {
      variables: {
        EMAIL_SPLITTER: '@',
      }
    },
    mergeCells: [{
        row: 0,
        col: 0,
        rowspan: 1,
        colspan: 8
      },
      {
        row: 11,
        col: 0,
        rowspan: 1,
        colspan: 8
      },
      {
        row: 13,
        col: 0,
        rowspan: 3,
        colspan: 1
      },
    ],
  });
`
this is example. I hope you can help me. Thank you very much
@AMBudnik

**Comment by AMBudnik** [comment] 2019-09-04 11:18
I do not see anything that doesn't work here, @d-yh 

You have defined 3 ranges of merging

```
{ //yellow
           row: 0,
           col: 0,
           rowspan: 1,
           colspan: 8
},
{ // green
           row: 11,
           col: 0,
           rowspan: 1,
           colspan: 8
},
{ //blue
           row: 13,
           col: 0,
           rowspan: 3,
           colspan: 1
}
```

and they all are merged correctly

![image](https://user-images.githubusercontent.com/10757813/64250384-4677d780-cf16-11e9-9c63-3c315cf2c7bf.png)

Can you share a draft/drawing on the expected result?

**Comment by d-yh** [comment] 2019-09-04 12:46
I recorded a video, and if I did not incorporate lines with custom parameters, the program would be OK. If merged, not work。
@AMBudnik 

this is code url  https://jsfiddle.net/nhrgeaky/1/
this is video url  https://pan.baidu.com/s/1MukOZcGNf0MOq0LPLwGjsQ

When the mouse double-clicks the cell, it should be equal to ‘=RIGHT(B14, LEN(B14) - FIND(EMAIL_SPLITTER, B14))‘

**Comment by d-yh** [comment] 2019-09-04 12:58
{
        row: 0,
        col: 0,
        rowspan: 1,
        colspan: 8
      },
      {
        row: 11,
        col: 0,
        rowspan: 1,
        colspan: 8
      },

When the mouse double-clicks the cell Correct results <img src=http://chuantu.xyz/t6/702/1567601852x992245926.png /> 
@AMBudnik

**Comment by d-yh** [comment] 2019-09-04 13:03
{
        row: 0,
        col: 0,
        rowspan: 1,
        colspan: 8
      },
      {
        row: 11,
        col: 0,
        rowspan: 1,
        colspan: 8
      },
      {
        row: 13,
        col: 0,
        rowspan: 3,
        colspan: 1
      },

<img src=http://chuantu.xyz/t6/702/1567602131x992245975.png />
error result 
When the mouse double-clicks the cell
@AMBudnik

**Comment by d-yh** [comment] 2019-09-05 04:48
@AMBudnik 
Here is the steps to reproduce the issue
1. Opne the demo https://jsfiddle.net/o41fv79s/1/
2. Add follow lines 
     {
        row: 13,
        col: 0,
        rowspan: 3,
        colspan: 1
      },

   to 
  mergeCells so you will get code like this

mergeCells: [{
        row: 0,
        col: 0,
        rowspan: 1,
        colspan: 8
      },
      {
        row: 11,
        col: 0,
        rowspan: 1,
        colspan: 8
      },
      {
        row: 13,
        col: 0,
        rowspan: 3,
        colspan: 1
      },

3. Run again.
4. Double click the cell C14. You will find the formla gone. as this one
     <img src=http://chuantu.xyz/t6/702/1567658793x992245975.png />
   But We expect this one.
<img src=http://chuantu.xyz/t6/702/1567658825x992245926.png />

**Comment by AMBudnik** [comment] 2019-09-06 12:44
Can you attach the images once again, please? They did not load.

**Comment by d-yh** [comment] 2019-09-06 13:02
@AMBudnik I have updated the picture. Thank you very much for helping me to see the problem。

**Comment by AMBudnik** [comment] 2019-09-06 13:08
Thank you for sharing the images. Now it's 100% clear.
I think that this issue is connected to https://github.com/handsontable/handsontable/issues/5459 so while fixing we should check them both.

**Comment by fencygu** [comment] 2019-10-08 10:37
plugins\mergeCells\mergeCells.js  
223 line
//const dataAtRange = this.hot.getData(...populationDataRange);
modify to get sourceData:
const dataAtRange = this.hot.getSourceData(...populationDataRange);

380 line 
//clearedValue = this.hot.getDataAtCell(mergeParent.row, mergeParent.col);
modify to get sourceData:
clearedValue = this.hot.getSourceDataAtCell(mergeParent.row, mergeParent.col);

**Comment by AMBudnik** [comment] 2019-10-08 10:57
Hey @fencygu 

should we discuss something more here? https://github.com/handsontable/handsontable/issues/5459 is still opened.

**Comment by fencygu** [comment] 2019-10-09 01:02
@AMBudnik OK

**Comment by AMBudnik** [comment] 2019-10-18 08:43
Hi @d-yh 

I have created a theory on merging cells and using formulas here https://github.com/handsontable/handsontable/issues/6359
Can you check if it also works in your project the same way?
It looks like the same issue so I'm closing this one (we do not want duplicates). 

However, if I'm missing something and/or the issue is still there if you unmerge the top OR left area please share a comment.

**Closed by AMBudnik** 2019-10-18 08:43 UTC
Labels: Formulas, Merge cells, Type: Bug
