### ISSUE TITLE
Hide columns marked as collapsible

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6839] opened 2020-04-27 11:59 UTC
### Description

There is a conflict between the _CollapsibleColumns_ and _HiddenColumns_ plugin. When we try to hide column which is marked as collapsible using the _HiddenColumns_ plugin API the nested headers act wired, mainly desynchronization occurs between header layers and cells.

### Demo

https://codesandbox.io/s/fast-mountain-zbo1t

### Your environment
* Handsontable version: `feature/index-mapper-nested-headers-fix` branch
* Browser Name and version: -
* Operating System: -

**Comment by wojciechczerniak** [comment] 2020-07-01 22:05
#6879 has better examples

Duplicate of #6879

**Closed by wojciechczerniak** 2020-07-01 22:05 UTC
Labels: Collapsing, Hiding, Type: Feature
