### ISSUE TITLE
[0.35.1+] Numeric cell type percentage format not calculated

### ISSUE THREAD

**Issue by Calcimicium** [handsontable/handsontable#5344] opened 2018-08-17 08:42 UTC
### Description
From the version 0.35.1, when typing a percentage value (like "15%") in a numeric cell formatted as a percantage ("0,0.00%"), the value is not traeted as a number anymore but as a string.
Before this version (I tried with 0.35.0, 0.34.5 and 0.33.0) percentage inputs are processed to give a number (the value divided by 100).

### Steps to reproduce
1. Create a Handsontable (0.35.1+) component with at least one cell with this settings
```javascript
{
  type: "numeric",
  numericFormat: { pattern: "0,0.00%" }
}
```

2. Type a percentage value (15% for example) in the cell and validate the entry.

### Demo
The version (0.35.0) which works perfectly: http://jsfiddle.net/Calcimicium/7s85mfe9/
You can see the type of the value is a number and is corresponding to the entried value divided by 100.

The version (0.35.1) which does not work anymore: http://jsfiddle.net/Calcimicium/7n5cb2r1/
You can see the type of the value is a string and the call appear as invalid.

### Your environment
* Handsontable version: 0.35.1+
* Browser Name and version: 
  * Google Chrome 68.0.3440.106 (64 bits)
  * Mozilla Firefox 61.0.2 (64 bits)
  * Microsoft Edge 42.17134.1.0
* Operating System: Microsoft Windows 10 Enterprise 17134.228

**Comment by AMBudnik** [comment] 2018-08-17 09:12
Thank you for sharing the issue report @Calcimicium 

I have replicated the issue. It looks like it might be associated with `moment` update in v 0.35.1 but we haven't mentioned in the release notes so it is a bug

**Comment by aninde** [comment] 2020-02-07 14:32
Unfortunately, the bug still occurs in version 7.4.0, despite the moment.js update
https://codesandbox.io/s/6582-740-230mr
<img width="543" alt="Screenshot 2020-02-07 at 15 31 09" src="https://user-images.githubusercontent.com/30186818/74037642-f7e7d100-49be-11ea-84d3-18debbd790a0.png">

**Comment by Osky772** [comment] 2021-03-11 13:29
After a discussion with our devs, we decided not to "fix" this behavior. The current behavior is correct already, and I will explain why.

In our docs you can find this statement:
> Make sure your cell values are numbers and not strings as Handsontable will not parse strings to numbers. You can input float-typed values in the numeric editor only using a dot or a comma as a decimal separator. For example, both `500000.5`, `500000,5` will be accepted.

Read more: https://handsontable.com/docs/8.3.1/demo-numeric.html

You should pass numeric-like values to numeric cells. You can't pass "string" values to numeric cells. Passing a value like `15%`, `15k` or `15randomtext` etc. is passing a string value.

Furthermore, in version `0.35.0` passing a value `13%` had been causing changing a real value in data until version `0.35.1`. The Handsontable `numericFormat` option doesn't work that way anymore:

> Please keep in mind that this option is used only to format the displayed output! It has no effect on the input data provided for the cell.
The numeric data can be entered to the table only as floats (separated by a dot or a comma) or integers, and are stored in the source dataset as JavaScript numbers.

Read more: https://handsontable.com/docs/8.3.1/Options.html#numericFormat

Anyway, if you want to parse values like that you can do it inside the `beforeChange` hook and use for example `numbro`:
```js
const hot = new Handsontable(container, {
  cell: [
    {
      row: 0,
      col: 0,
      type: "numeric",
      numericFormat: { pattern: "0,0.00%" }
    }
  ],
  colHeaders: true,
  data,
  stretchH: "all",
  beforeChange(changes) {
    for (let change of changes) {
      const [col, row, oldValue, newValue] = change;
      const { type } = this.getCellMeta(row, col);

      if (type !== 'numeric') {
        return;
      }

      const parsedValue = numbro.unformat(newValue);

      if (type === 'numeric' && parsedValue !== undefined) {
        change[3] = parsedValue;
      }
    }
  }
});
```

**Comment by AMBudnik** [comment] 2021-03-12 11:11
Thank you for the explanation and the example @Osky772 
I think that we can remove the bug/regression label and leave the issue open for a week for others to share feedback.

**Comment by AMBudnik** [comment] 2021-03-23 08:15
I'm closing this issue as resolved as there are no further feedback or questions.

**Closed by AMBudnik** 2021-03-23 08:15 UTC
Labels: Status: Answered
