### ISSUE TITLE
Summary calculations and Formula support not updating with filters

### ISSUE THREAD

**Issue by tillmon** [handsontable/handsontable#5962] opened 2019-04-15 13:01 UTC
Cells with summary calculations or formula support are not updated if rows are filtered. Is this planned for development?

**Comment by AMBudnik** [comment] 2019-04-15 13:20
Hey @tillmon 

I think that the updates for formulas have already been mentioned on Github

https://github.com/handsontable/handsontable/issues/5635
https://github.com/handsontable/handsontable/issues/4675

When it comes to the summary calculations - can you share an example? Here https://handsontable.com/docs/7.0.2/demo-summary-calculations.html they work fine.

**Comment by tillmon** [comment] 2019-04-15 13:34
Example:

https://jsfiddle.net/ygbqpacv/1/

If I deselect 10 in the dropdownMenu of column A, the 3. row is hidden. However the column summary in cell A6 (i.e. last row of column A) is still 50 and not 40.

**Comment by AMBudnik** [comment] 2019-04-16 11:00
You're right. The plugin is not able to get a visible list of cells, and it goes crazy if we trim rows https://jsfiddle.net/handsoncode/mew86htr/

**Comment by tillmon** [comment] 2019-04-17 21:29
Example with formula:

https://jsfiddle.net/at8d6v2n/

If I filter out the 2. row by deselecting 2, the last row is hidden as well. The formula in the last row is `=SUBTOTAL(9,A1:A3)`, which should display the sum. It would be great if the last row remains and is updated like it works in excel.

**Comment by AMBudnik** [comment] 2019-04-19 09:51
Yes, you're right. Excel does it right. We should try to get the same effect.

**Comment by wojciechczerniak** [comment] 2019-09-26 09:08
ColumnSummary issue is a duplicate of #3658
Filters issue is a duplicate of #5455

CC @AMBudnik

**Comment by AMBudnik** [comment] 2019-09-26 09:12
Great to have those separately. @tillmon I will update you as soon as those tasks are completed.

**Closed by AMBudnik** 2019-09-26 09:12 UTC
Labels: Filtering, Summary calculations, Trimming, Type: Bug
