### ISSUE TITLE
Hide Column Header Text that Overflows Column Header and Filter Button

### ISSUE THREAD

**Issue by Joshua-W-Adams** [handsontable/handsontable#5177] opened 2018-06-13 05:23 UTC
### Description

I have the following Handsontable I have configured in JSFiddle.
https://jsfiddle.net/JoshAdams/nbLy6j04/

I want my column header names to be hidden behind the column filter symbol. So I have changed the display property of the ColHeaders to flex. Which works fine on all browsers.

However, changing this display value causes strange behavior on MS Edge and IE. Specifically it causes the Column Heights to be re-sized incorrectly on scrolling of the table. See image below.

![col-heights-bug](https://user-images.githubusercontent.com/27187174/41331656-a8f16662-6f0c-11e8-9726-cd8e8e185939.png)

Which is explainable by the fact IE and Edge do not properly support display: flex.

So my question is. Is there any changes I can make to my code to achieve the functionality I want. I.e. if the column header text overflows the column (and filter button) hide the overflowing section of the text?

### Steps to reproduce

1. Open MS Edge or IE
2. Go to https://jsfiddle.net/JoshAdams/nbLy6j04/
3. Scroll the Handsontable and watch the magic happen

### Demo

https://jsfiddle.net/JoshAdams/nbLy6j04/

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Microsoft Edge 42.17134.1.0
* Operating System: W10

**Comment by AMBudnik** [comment] 2018-06-15 08:23
Thank you for sharing @Joshua-W-Adams 
we've replicated the issue.

**Comment by AMBudnik** [comment] 2020-06-18 11:47
As[ support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

This issue has been tested with Handsontable 8.0.0-beta2-rev15 on Windows 10 and Edge browser
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85016452-09f62f00-b16a-11ea-8eae-1e273963f241.png">

where the issue is not replicable
![workswell](https://user-images.githubusercontent.com/10757813/85016485-17abb480-b16a-11ea-9c2e-77887b713a9d.png)

That is why I need to close this issue.

**Closed by AMBudnik** 2020-06-18 11:47 UTC
Labels: Edge, Headers, Type: Bug
