### ISSUE TITLE
Copy doesn't work when selected hidden column

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#6728] opened 2020-02-25 10:13 UTC
### Description
As the title says.

### Steps to reproduce

1. Open demo: https://jsfiddle.net/wojciech/wyjra6fd/
2. Select a hidden column by click on the button.
3. Copy by `cmd` + `c`.
4. Paste anywhere.

### Demo

https://jsfiddle.net/wojciech/wyjra6fd/

### Your environment
* Handsontable version: Any
* Browser Name and version: Any
* Operating System: Any

**Comment by wszymanski** [comment] 2020-02-25 10:15
Related to handling events by the `onCopy` function. An instance of the Handsontable doesn't listen and the internal flag `isTriggeredByCopy` is falsy.

**Comment by AMBudnik** [comment] 2020-06-16 11:07
previously (@wszymanski demo)
![previous](https://user-images.githubusercontent.com/10757813/84767065-1ba4ce80-afd2-11ea-8a28-00156379d204.gif)


8.0.0.-beta2-rev14 https://jsfiddle.net/AMBudnik/sejhaq1o/ selection works but it is not visible
The result of paste is still empty data
![now](https://user-images.githubusercontent.com/10757813/84767135-35461600-afd2-11ea-8f34-3f8610d6a351.gif)

**Comment by AMBudnik** [comment] 2020-06-17 11:35
As we had many questions and ideas on how this functionality works across different cases I'd like to present those here.

For testing purposes, I propose to call @wszymanski's case as **the main case**. 

### Case 2
#### Hide one column, select one column, and paste one column
 7.4.2 https://jsfiddle.net/AMBudnik/mqwxa4rp/
* selection is visible (**wrong**)
* `afterSelectionEnd` returns **wrong** incides `0, 4, 4, 3`
* `beforeCopy` is not triggered (**wrong**)
* pasted data is empty (**wrong**)

8.0.0-beta2-rev15 https://jsfiddle.net/AMBudnik/k436g91a/
* selection is not visible (**correct**)
* `afterSelectionEnd` returns **correct** incides `0, 4, 4, 4`
* `beforeCopy` is not triggered (**wrong**)
* pasted data is empty (**wrong**)

### Case 3
#### Hide one column, select two columns, and paste two columns
7.4.2 https://jsfiddle.net/AMBudnik/vf6x71zj/
* selection is partially visible (**correct**)
* `afterSelectionEnd` returns **wrong** incides `0, 3, 4, 3`
* `beforeCopy` is not triggered (**wrong**)
* pasted data is empty (**wrong**)

8.0.0-beta2-rev15 https://jsfiddle.net/AMBudnik/so38gt72/
* selection is partially visible (**correct**)
* `afterSelectionEnd` returns **correct** incides `0, 3, 4, 4`
* `beforeCopy` is not triggered (**wrong**)
* pasted data is empty (**wrong**)

**Comment by AMBudnik** [comment] 2020-07-16 07:49
Works the same in beta2 https://jsfiddle.net/hte0zcq3/

**Comment by aninde** [comment] 2020-08-05 15:11
## Working with stable v8.  

Changes compared to `v7` and `8.0.0-beta2-rev15`:
* highlight on row Headers is visible when selecting hidden (**correct**)
* the coordinates have changed due to breaking change in `v8` https://github.com/handsontable/handsontable/pull/7027 . 0 has changed to -1 after selecting a hidden row. 
* pasted data are still empty, but it's not a bug in my opinion. GS does the same, and when pasting hidden columns in Excel, the hidden column is pasted.

![pastinghiddengs](https://user-images.githubusercontent.com/30186818/89430100-aab2a500-d73e-11ea-9ff5-13a84503b41d.gif)

![pasting-hidden-excel](https://user-images.githubusercontent.com/30186818/89430109-ac7c6880-d73e-11ea-8592-ede62e88416b.gif)



### Case 2
**Select the hidden column with a button. Paste hidden column on column A. Pasting by keyboard shortcuts.**
Working as with 8.0.0-beta2-rev14 https://github.com/handsontable/handsontable/issues/6728#issuecomment-644695702
https://jsfiddle.net/aninde/zhr5dwyv/

* selection is not visible (**correct**)
* `afterSelectionEnd` returns correct incides startRow:0, startCol:0, endRow:4, endCol:0 (**correct**)
* `beforeCopy` is not triggered (**wrong**)
* pasted data is empty (**wrong?**)

![case2](https://user-images.githubusercontent.com/30186818/89429129-75598780-d73d-11ea-82a5-33786dbcaf71.gif)

### Case 3

**Select the hidden column with a button. Paste hidden column on column A and column B selected together. Pasting by keyboard shortcuts.**
https://jsfiddle.net/aninde/zhr5dwyv/

* selection is not visible (**correct**)
* `afterSelectionEnd` returns correct incides 0, 0, 4, 1 (**correct**)
* `beforeCopy` is not triggered (**wrong**)
* pasted data is empty (**wrong?**)

![case3](https://user-images.githubusercontent.com/30186818/89429022-4e02ba80-d73d-11ea-9f18-0bc8e1ec7935.gif)

**Comment by pnowak** [comment] 2020-08-28 13:38
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/8jLcs6rw/

**Comment by jansiegel** [comment] 2020-09-25 10:24
@aninde 
> pasted data are still empty, but it's not a bug in my opinion. GS does the same

I don't think you can copy the data just from the hidden column in GS. What I think you've done in your gif is copying the data from whatever cell you had selected at the time, which turned out to be empty.

> when pasting hidden columns in Excel, the hidden column is pasted

Excel _does_ copy the data, and on top of that also hides column where the pasting takes place.

**Comment by jansiegel** [comment] 2020-09-25 10:56
@wszymanski @aninde @AMBudnik 
I don't think this is a bug. In this scenario nothing gets copied, because the Handsontable instance is not listening (we're clicking on a button outside HOT, so HOT loses focus), and it has nothing to do with the column being hidden - when we change the column being selected to a visible one, the effect is exactly the same: https://jsfiddle.net/js_ziggle/56kn7owL/.

If we first focus the instance (either by selecting a cell or calling `hot.listen()`), then copying works fine: https://jsfiddle.net/js_ziggle/kbotg2mu/.

**Comment by aninde** [comment] 2020-09-28 12:43
@jansiegel thanks for the clarification. @AMBudnik therefore should we close this issue?

**Comment by AMBudnik** [comment] 2020-09-29 07:04
True @aninde 
I think that @jansiegel 's https://github.com/handsontable/handsontable/issues/7290 explains what we missed. I'm closing this issue.

**Closed by AMBudnik** 2020-09-29 07:04 UTC
Labels: Copy-paste, Type: Bug
