### ISSUE TITLE
jquery not supported ?

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#5572] opened 2018-11-08 17:14 UTC
hello,
in https://forum.handsontable.com/t/how-to-getinstance-using-0-37/1857 , 
there's a link to a jquery demo with handsontable 
https://docs.handsontable.com/pro/1.13.0/demo-jquery.html

the link is dead . Handsontable don't support jquery anymore ?

regards
jm

**Comment by AMBudnik** [comment] 2018-11-14 12:47
Thank you for sharing that @jeanmarc78 

we should check it out while doing https://github.com/handsontable/handsontable/issues/5096

**Comment by wojciechczerniak** [comment] 2018-12-18 10:33
jQuery is still there: https://github.com/handsontable/handsontable/blob/master/src/helpers/wrappers/jquery.js

Documentation is harder to find: https://github.com/handsontable/docs/blob/6.2.1/tutorials/jquery.html

We're should bring back the docs with #5096. So I'm labeling this issue as answered and closing as a duplicate of #5096.

**Closed by wojciechczerniak** 2018-12-18 10:33 UTC
Labels: Type: Improvement suggestion
