### ISSUE TITLE
[2.0.0+] Scrolls to the end when columns are updated such that the selected column is removed

### ISSUE THREAD

**Issue by chearon** [handsontable/handsontable#5849] opened 2019-03-08 19:24 UTC
### Description

Handsontable scrolls to the bottom when you delete the last column via `updateSettings` and the selection contains that column.

It's the logic in [`adjustRowsAndCols`](https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/core.js#L575-L602), I think ~if the selection would be collapsed it should just do no scrolling.~ the selection should just not scroll in this case

### Steps to reproduce

1. Create a HOT instance that uses the `columns` option
2. Select the last column
3. In code, at some point after this, call `updateSettings` so that it would remove that column
4. Selection scrolls to the end

This doesn't happen if the column is in the middle

### Demo

http://jsfiddle.net/v58Lr6np/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Firefox latest (happens on any browser)
* Operating System: macOS latest

**Comment by AMBudnik** [comment] 2019-03-11 13:31
Thank you for sharing the issue. I have replicated the scrolling while clicking the headers (updating `columns`).
The issue doesn't seem to be related to any previous commit/version.

**Comment by aninde** [comment] 2019-09-19 07:49
This issue is a regression bug. Scrolling to the last cell in the table after removing the last column occurs since 2.0.0 v. but with a different scenario. 
Setting scrolling by adding overflow does not affect the occurrence of the problem. 

## Case 2
**Steps to reproduce**
Select the last column.
Remove column by clicking `remove column ` in the context menu.

**Demo**
V. 2.0.0 http://jsfiddle.net/aninde/6Lempy1b/
![removing-last-one 2019-09-18 14_14_53](https://user-images.githubusercontent.com/30186818/65223953-81573f00-dac2-11e9-80ed-8aac0b5feee6.gif)


**Expected result:** 
`clientWidth` should not change, like in
Demo in v. 0.38.1 http://jsfiddle.net/aninde/xg8daLmn/ without bug

**Environment**
Handsontable version: since 2.0.0
Browser Name: any
Operating system: any

**Comment by aninde** [comment] 2019-09-19 09:08
I confirm that this issue is strictly connected with the logic in [adjustRowsAndCols](https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/core.js#L575-L602) and `selection` because removing the last column via API, by `alter` method doesn't cause scrolling to the last cell.

**Demo**
ver. 2.0.0. http://jsfiddle.net/aninde/ux0kf54d/

**Comment by AMBudnik** [comment] 2020-03-23 10:56
The **main issue** works the same in official `8.0.0-beta1` http://jsfiddle.net/u5k1jhod/
**Case 2** works the same in official `8.0.0-beta1` http://jsfiddle.net/ftkqdun4/

**Comment by AMBudnik** [comment] 2020-07-01 07:47
Hi @chearon 

It seems that the issue is fixed in our last revision (18th) of 8.0.0.-beta2 http://jsfiddle.net/3qm9tofh/ Can you confirm?

**Comment by chearon** [comment] 2020-07-06 13:39
@AMBudnik looks better! Although it still seems to have the headers on the left selected in 8.0.0-beta2. (Also, I've just realized this issue doesn't affect us anymore since our app always has a blank rightmost column for pasting new columns).

**Comment by AMBudnik** [comment] 2020-07-07 06:25
That's true. We need to call the `deselectCell()` to remove the `rowHeaders` selection http://jsfiddle.net/067e3rc9/

**Comment by AMBudnik** [comment] 2020-07-16 11:12
I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

@chearon All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment] 2020-08-06 06:55
Hi @chearon now it's official :-) Handsontable v 8.0.0 has just been released. I highly encourage you to test the new version and leave some feedback.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases

**Closed by AMBudnik** 2020-08-06 06:55 UTC
Labels: Core: handsontable, Regression, Type: Bug, scroll
