### ISSUE TITLE
[0.28.1+] Row moving doesn't work with column sorting when PersistentState is enabled

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4713] opened 2018-01-11 10:12 UTC
### Description

Row moving doesn't work with column sorting when `PersistentState` is enabled. Every time the user changes the row order after the page refresh Handsontable renders that rows in different order. In my observation, I saw that this is caused by enabling `ColumnSorting` plugin. If I disable that plugin everything seems works as should.

### Steps to reproduce

1. Move 10-th row to the first position;
2. Refresh the page by clicking the "run" button;
3. You'll see different row order as previously was set.

### Demo

https://jsfiddle.net/3gas9z6q/9/

### Your environment
* Handsontable version: 0.35.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment] 2018-04-10 13:16
Hi @budnix 

It looks like the last working version was 0.28.0 (demo https://jsfiddle.net/handsoncode/LmnLq8d3/) can you confirm it? Version 0.28.1 is reordering rows after we rerender the table https://jsfiddle.net/handsoncode/juebb6wk/

**Comment by AMBudnik** [comment] 2018-08-24 07:00
Now we get differnt result each time we move the row. The index of a row doesn't correspond to the number of attempts as it may seem. After performing this two attempts I got `A10` and then `A5`.

First attempt
![1gif](https://user-images.githubusercontent.com/10757813/44569767-c2740700-a77b-11e8-95a9-51c1c8a0175e.gif)

Second attempt
![2gif](https://user-images.githubusercontent.com/10757813/44569727-9eb0c100-a77b-11e8-8bdc-3494d06c30b2.gif)

**Comment by AMBudnik** [comment] 2018-10-04 08:55
works the same in v `6.0.1`

**Comment by aninde** [comment] 2019-09-23 14:09
Sadly `8.0.0-rc1` fixed only part of described here issue and broke feature even more. 
In `8.0.0-rc1` `persistanceState` works with `collumnSorting`, but not with moving columns or rows, even when `columnSorting `is disabled. @wszymanski @wojciechczerniak WDYT?

### Case 1 
**Disable columnSorting**
Reproduction as above
`7.1.1` - with `PersistanceState` works and it’s saved rows and column after moving. Works with `manualRowMove`, `manualColumnMove`.
`8.0.0-rc1 `- doesn't work, after page refresh Handsontable renders that rows in different order, like on the gif 
![4713-8 0 0-rc1](https://user-images.githubusercontent.com/30186818/65431984-aaf1cc80-de1a-11e9-95c7-7021911836c3.gif)

### Case 2 
**Enabled column Sorting**
Reproduction as above
`7.1.1` doesn’t work
`8.0.0-rc1` - sorted data are saved, but moved data doesn’t

ver.` 7.1.1` bug when columnSorting is enabled, notice that the data skips.
![4713-7 1 1 sorting](https://user-images.githubusercontent.com/30186818/65432222-1c317f80-de1b-11e9-8486-a21352669691.gif)
ver. `8.0.0-rc1` fixed columnSorting, but broken moving 
![columnsorting 8 0 0-rc1](https://user-images.githubusercontent.com/30186818/65432951-66673080-de1c-11e9-9211-b95788b0eaeb.gif)

### Demo
ver. `8.0.0-rc1` https://jsfiddle.net/aninde/kq9c85pj/
ver. `7.1.1` https://jsfiddle.net/aninde/r106dxmv/

### Environment
Handsontable: `7.1.1` and `8.0.0-rc1`
Browser: any
Operating system: any

**Comment by wszymanski** [comment] 2019-09-23 14:21
Good job, it's a bug. The `PersistentState` plugin was completely not used after some temporary changes. 

https://github.com/handsontable/handsontable/blob/f1c6c280de33c8ef2275d24dfcedfc12f87dca81/src/plugins/manualRowMove/manualRowMove.js#L642

I will fix it.

**Comment by wszymanski** [comment] 2019-09-24 09:39
It should work from now:

https://cdn.jsdelivr.net/gh/handsontable/handsontable@576c283bd0cbc1f3764ade7c68383a76d0700ffb/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@576c283bd0cbc1f3764ade7c68383a76d0700ffb/dist/handsontable.full.css

**Comment by aninde** [comment] 2019-09-24 10:10
@wszymanski thanks for the new version of `8.0.0-rc1`. Unfortunately, it still needs patches.

It fixed the working of `manualRowMove` with `persistanteState` however, `manualColumnMove` still doesn't work. Regardless of enabling `columnSorting`. 

Bug - moved column is not saved in local storage when `PersistentState` is enabled.`8.0.0-rc1`
![4713-8 0 0-rc1-delta-movColumn-not-fixed](https://user-images.githubusercontent.com/30186818/65502623-6e2de000-dec3-11e9-9b4b-fa7e6be8a424.gif)
**Demo**
ver. [latest 8.0.0-rc1](https://github.com/handsontable/handsontable/issues/4713#issuecomment-534479221) https://jsfiddle.net/aninde/d24t9fsn/

**Comment by wszymanski** [comment] 2019-09-24 11:32
You are right, thanks.

https://cdn.jsdelivr.net/gh/handsontable/handsontable@bb39a947c8dba3f8498cf63d0f98ae1925bf93ba/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@bb39a947c8dba3f8498cf63d0f98ae1925bf93ba/dist/handsontable.full.css

**Comment by wszymanski** [comment] 2019-09-25 09:14
Thanks for that!

Fix:

https://cdn.jsdelivr.net/gh/handsontable/handsontable@f919b6bf2cc604756a4c56341976cb6c3e1c58b7/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@f919b6bf2cc604756a4c56341976cb6c3e1c58b7/dist/handsontable.full.css

It may affect also how the `AutoColumnSize` plugin works.

**Comment by aninde** [comment] 2019-09-25 13:01
The newest build of `8.0.0-rc1` fixed above bug. It works like magic. @wszymanski thank you.

**Demo**
v.[ latest ](https://github.com/handsontable/handsontable/issues/4713#issuecomment-534930797 )`8.0.0-rc1` https://jsfiddle.net/aninde/6k85fstc/

**Comment by AMBudnik** [comment] 2019-11-15 08:49
Works well for beta 8.0.0-beta1 https://jsfiddle.net/g3aLkef1/

**Comment by AMBudnik** [comment] 2020-08-07 08:08
Demo updated to v 8.0.0 https://jsfiddle.net/6fLy57rd/
We can call this issue officially solved in v 8.0.0/

**Closed by AMBudnik** 2020-08-07 08:08 UTC
Labels: Column sorting, Guess: a day or more, Regression, Type: Bug
