### ISSUE TITLE
Pasting copied column, more spare rows added and first copied cell appears before additional spare rows

### ISSUE THREAD

**Issue by toroc** [handsontable/handsontable#4456] opened 2017-08-08 21:02 UTC
### Description
When pasting a copied column, additional spare rows are added, and the last row before the additional spare rows has the same value as the first copied cell in the column.

### Steps to reproduce
1. Copy first column
2. Paste into second column
3. Row 58 has the first copied cell value from the first column, and 40 spare rows were added underneath it

### Demo
http://jsfiddle.net/toroc/6gpu6q1n/
![screen shot 2017-08-08 at 2 01 23 pm](https://user-images.githubusercontent.com/9097432/29094429-2b596dfc-7c42-11e7-9b1b-45c0f963752b.png)

### Your environment
* Handsontable version: 1.13.0
* Browser Name and version: Chrome/59.0.3071.115 and "58.0.3029.110"
* Operating System: OSX 10.12.6

**Comment by AMBudnik** [comment] 2017-08-16 07:07
Thank you for sharing @toroc  I have replicated the issue and it is very odd.
It looks like the first version where it has been changed is `1.11.0-beta1` before the version we do not get the extra `1`.

**Comment by yixunx** [comment] 2017-10-30 20:26
The same issue happens in 0.34.5: https://jsfiddle.net/uzrp9gtd/1/

**Comment by toroc** [comment] 2018-03-07 00:57
Any updates on this? This is still happening on PRO 1.16.0.

**Comment by AMBudnik** [comment] 2018-03-07 07:27
We are slowly planning to change the spare rows logic to push them outside the table (logically, UI possibly won't change) and then all the issues where the rows are moving in improper positions won't happen but this process doesn't have any deadline yet and the issues are still present.
We should schedule the issue or change the `priority`.

**Comment by wojciechczerniak** [comment] 2018-05-14 12:36
Now copy column does not work on Chrome at all. In Firefox works as described.

**Comment by swistach** [comment] 2018-06-04 14:48
This issue will be resolved by #4931

**Comment by AMBudnik** [comment] 2018-08-27 08:48
The issue is still replicable in v 5.0.1 https://jsfiddle.net/wrpxve7h/1/

**Comment by swistach** [comment] 2018-09-20 07:31
This issue will be solved within #4931

**Closed** 2018-09-20 07:31 UTC
Labels: Plugin: copy-paste, Priority: high, Type: Bug
