### ISSUE TITLE
After editing a dropdown value, blue blip in the right bottom corner does not appear

### ISSUE THREAD

**Issue by gstanislav** [handsontable/handsontable#3317] opened 2016-03-11 10:45 UTC
https://docs.handsontable.com/0.23.0/demo-dropdown.html

Try editing a dropdown value via editor. After the cell is modified, the blue blip disappears:

![image](https://cloud.githubusercontent.com/assets/7578355/13700044/7dfc7a48-e78f-11e5-9251-d22087b1457f.png)

**Comment by AMBudnik** [comment] 2016-03-11 10:50
I see the case. You would like to open and close a dropdown via trigger. Now it is only available by clicking <kbd>enter</kbd>

**Comment by gstanislav** [comment] 2016-03-11 11:15
Wait, no, this is a bug. The blue blip in the right bottom corner of blue selection box doesn't appear.

**Comment by krzysztofspilka** [comment] 2016-03-11 11:43
@gstanislav @AMBudnik this is some small glitch. Indeed, when editing e.g. first cell in the "Chassis color" column and pressing enter the selection is moved to the cell below but the fill handle disappears.

**Comment by AMBudnik** [comment] 2016-03-11 11:44
If we would like it to be there after opening the list it should point to the roof - as the representation that the list is opened and could be easily closed by the same click. 

Proposition
![zrzut ekranu 2016-03-11 o 12 23 04](https://cloud.githubusercontent.com/assets/10757813/13701228/c024a106-e786-11e5-83d6-d37dc9c703a6.png)

**Comment by gstanislav** [comment] 2016-03-11 12:25
@AMBudnik  The bug is about the blue thingie in the blue selection box. This is how it should look like:

![image](https://cloud.githubusercontent.com/assets/7578355/13702118/586125dc-e79d-11e5-9487-83965cdd265c.png)

This is how it looks like:

![image](https://cloud.githubusercontent.com/assets/7578355/13700044/7dfc7a48-e78f-11e5-9251-d22087b1457f.png)

**Comment by AMBudnik** [comment] 2016-03-11 12:27
Ah... ok - thanks for details @gstanislav

**Comment by AMBudnik** [comment] 2016-09-09 12:29
Still present in 0.27.0

**Comment by swistach** [comment] 2016-10-10 14:35
It's duplicate of #2230

**Closed by swistach** 2016-10-10 14:35 UTC
Labels: Cell type: autocomplete / dropdown / handsontable, Priority: normal, Type: Bug
