### ISSUE TITLE
Bad scroll-performance when using multiple hot-tables

### ISSUE THREAD

**Issue by felixhagspiel** [handsontable/handsontable#2029] opened 2015-01-07 13:12 UTC
I am building a single-page prototype where roughly ~30 separate hot-tables are created, but only one is visible at a time, example:
![screenshot](http://content.screencast.com/users/felixhagspiel/folders/Jing/media/6e337a78-d2a4-40a1-86a6-12aab0af1b91/2015-01-07_1334.png) 
The problem is that scrolling performance is poor, especially in firefox. In chrome it is less laggy.

My Questions:
- Is there a build-in function to represent multiple tables ("pages") in one handsontable-instance? 
- And if there is none, how can I keep the table instance but remove the grid from the DOM, so that only the currently displayed table is rendered? When I call `destroy()` it removes the instance as well. 

I am also open for alternative approaches. Thanks in advance!

**Comment by AMBudnik** [comment] 2016-05-17 10:11
Sorry for the delay @felixhagspiel 
Are you still seeking an answer for the above?

**Comment by AMBudnik** [comment] 2016-06-21 14:04
I'm closing this issue as I can't reproduce it.
I made a demo with 3 tables 100x100 but it works as expected.

If you would have an example when tables are lagging feel free to add a demo.

**Closed by AMBudnik** 2016-06-21 14:04 UTC
Labels: Answered
