### ISSUE TITLE
Improve the Demo page in the docs (replace BigExample, fix iframe-related problems)

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#9209] opened 2022-02-09 15:49 UTC
### Description

We restored the demo page at https://handsontable.com/docs/demo/ but we need to put finishing touches to it.

### We can achieve that by:
- Removing tabs (.row .tab)
- Placing links to GitHub below the demo under the header "Find the code on GitHub"
- Setting the background to transparent (.bigPreviewExample>div:not(.tab))

### Before
<img width="1594" alt="Screen Shot 2022-02-09 at 16 45 39" src="https://user-images.githubusercontent.com/8048526/153236985-36b3bbfb-280a-4a51-b755-bc1ca3a25fc6.png">

### After
<img width="1530" alt="Screen Shot 2022-02-09 at 16 45 22" src="https://user-images.githubusercontent.com/8048526/153237009-7ded14d5-c50d-4cf6-9016-378f46f4cb65.png">

**Comment by warpech** [comment] 2022-05-25 08:45
There are more problems with the Demo in the Docs that need to be urgently fixed. Most of them were found in https://docs.google.com/spreadsheets/d/15q2Bv4UCIoXLktZDDqSTupTLSSO0BWvoxfJbeUbCauU/edit by @aninde and @krzysztofspilka:

1. After filtering by column Rating (stars) and vertical scrolling there is some row-headers misalignment
    - @aninde please provide steps to reproduce.
2. Autofill doesn't work
    - I can reproduce. I don't think iframe is to blame, because it works in other iframes
3. This demo isn't exact copy of the https://handsontable.com/demo. Column order is different
    - I think it is not a problem. this was done on purpose by me (https://handsoncode.slack.com/team/U4RV24US2), because the content column is narrower in the docs.
4. We missing checkbox in the rows headers.
     - I can reproduce, probably it was done by mistake
5. Column menu, context menu don't fit in the iframe.
     - Related to the iframe. If I remember correctly, there was a solution for it, but it is not documented. (Slack thread https://handsoncode.slack.com/archives/C4PV4S33Q/p1653468120335759). If not, we can solve that by incresing the container height so that it is larger than the menu height.
6. Enable numeric editor in the Stars and Chart cells.
7. Removal of the abnormally high row causes the grid to show the blank space above it instead of the remaining rows. Steps to reproduce: Edit a cell, insert multiple newline characters (ALT+ENTER), close the editor, delete the whole row.

I am removing it from the `React docs` project, because I think it can be fixed separately and quicker on `develop`.

**Comment by aninde** [comment] 2022-05-26 14:19
1. After filtering by column Rating (stars) and vertical scrolling there is some row-headers misalignment
Reproduction
1. Filter by value `3` on column Rating
2. Scroll horizontally to the right

Result:
Too much offset between cells and headers. The cells slide under the wtHolder headers
![Kapture 2022-05-26 at 16 12 02](https://user-images.githubusercontent.com/30186818/170506347-80b1bf31-9aad-49ef-aabb-f7a6037ad37c.gif)

**Comment by warpech** [comment] 2022-06-21 09:18
The PR #9531 implements the problem expressed in the first message, but not the problems implemented in the later comments.

**Comment by aninde** [comment] 2022-08-05 11:22
1. https://github.com/handsontable/handsontable/issues/9209#issuecomment-1138629639 reported as https://github.com/handsontable/handsontable/issues/9580
2. > Autofill doesn't work 

shouldn't, is not imported.

3. 3., 4., 5.all done
6. reported as https://github.com/handsontable/handsontable/issues/9581
7. resolved
8. https://github.com/handsontable/handsontable/issues/9209#issuecomment-1167999820 to check

Hence most of the above issues are resolved, I'm closing #9209.

**Closed by aninde** 2022-08-05 11:22 UTC
Labels: Docs: Content, Type: Improvement suggestion, Effort: Medium, Impact: High
