### ISSUE TITLE
Grouped problems of using updateSettings and state-managers

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#8372] opened 2021-07-06 17:29 UTC
### Description
@wojciechczerniak partially described the problem in #7263. Although, updateSettings with the `data` key is just one case. Unfortunately, updating settings is a much bigger problem and impacts setting management in end apps (both frameworks' wrappers + state manager and vanillajs + state manager).

The problem lies in the way how we resolve settings and propagate them to parts of Handsontable (plugins/index mappers/etc). Currently, to update settings in Handsontable, you have to put an object containing the necessary options as an argument of the `updateSettings()` method.
If you use state managers, in most cases, you probably want to store all your options as a state snapshot. That guides to running updateSettings with all used options, each time state manager notices that state has changed (that's the default way)
-- or --
you have to build your own logic to predict if a new state differs from the previous one and update settings using changed options only.

It touches mostly React's developers because they usually use `setState` or `use*` hooks in components. Any change in component's props or its parents component's props will "updateSettings" with all properties we initially bound to the `<HotTable>` (React has its own vDOM comparator and you can read more about it here: https://reactjs.org/docs/optimizing-performance.html#shouldcomponentupdate-in-action).

Of course, you can use `React.memo` or `PureComponent` with your own `shouldComponentUpdate` implementation, but, let's say - it's not the perfect solution.

Let's back to our `updateSettings` problem. Below you can find the list of known cases, with a short description:

1) `updateSettings({ data: ... })` which internally run `loadData()`
That case is described with details by @wojciechczerniak in #7263. I can add it affects directly the following plugins:
   - `autoColumnSize` - recalculates all column size
   - `autoRowSize` - recalculates all row size
   - `collapsibleColumns` - regenerates internal cache of collapsing settings
   - `columnSorting` - sorts columns by settings
   - `formulas` - creates a new sheet in HF or switch to the existing one, and loads serialized data (invokes `loadData()`)
   - `manualColumnMove` - moves columns by settings or loads their order from persistentState
   - `manualRowMove` - moves columns by settings or loads their order from persistentState
   - `nestedHeaders` - updates the nestedHeaders setting

   In this case, our internal indexMappers will be recreated so unexpectedly it might trash tracking any index transformation.

2) `updateSettings({ option: { initial settings } })`
This case affects each option that accepts settings other than the boolean value. That means if you do not track almost all user-base actions to the state, then the next `updateSetting` with the revalidated state will reset non-tracked user actions.
The problem is if we want to save a new state in `after*` hooks, the setting state will invoke the next `updateSettings` in the meantime what you can see in the following example:
![image](https://user-images.githubusercontent.com/11849621/124641284-d1b5b180-de8e-11eb-916c-7b7b25e40cf2.png)

### Summary
Currently, storing settings in state managers and using them to keep Handsontable "up-to-state" requires a lot of additional work and often ends with unresolvable problems.

NOTICE: Before we start fixing particular issues with dozen "if"s in each plugin and core functionality, perhaps, we should first look for a better way to manage settings in general.

### Related issues:
- #8340
- #7567
- #7554 
- #7553
- #7263 
- #7165 

But in fact, all issues from [that list](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Core%3A+update+settings%22) are related to that problem.

**Comment by AMBudnik** [comment] 2021-08-24 08:33
_Note to myself : update Client on_ [forum](https://forum.handsontable.com/t/gh-8372-on-re-render-cell-meta-data-lost/5459)

**Comment by AMBudnik** [comment] 2021-10-13 10:05
Down below we are gathering some of the cases reported by Clients. 

### Case 1 - Cell meta erase

**Demo**: https://jsfiddle.net/ztja8yvs/2/
**Version**: Handsontable v10, Handsontable for React v10, React v16

**Steps**
1. Select any cell
2. Click on “Make cells green” button.
4. Click on the <kbd>counter</kbd> button

**Result**: Counter value is updated but the cell color is erased.
**Expected result**: Counter value is updated but the cell color remains.

**Comment by adrianszymanski89** [comment] 2022-01-11 11:13
Inform user: https://forum.handsontable.com/t/drag-to-fill-and-hyper-formulas-funcitonality-is-not-working/5838/6

**Comment by jansiegel** [comment] 2022-02-23 11:00
### State for the upcoming `12.0.0` version:
- **Fixed:**
  - #7567
  - #7263 
    - Changes described in https://github.com/handsontable/handsontable/pull/9121#issuecomment-1015325860
  - #7165 
  - [Case 1](https://github.com/handsontable/handsontable/issues/8372#issuecomment-942136658)
  - [Case 2](https://github.com/handsontable/handsontable/issues/8372#issuecomment-949536320)
  - [Case 3](https://github.com/handsontable/handsontable/issues/8372#issuecomment-949540263)
  - [Case 4](https://github.com/handsontable/handsontable/issues/8372#issuecomment-949542132)
  - [Case 5](https://github.com/handsontable/handsontable/issues/8372#issuecomment-949544051)
  
- **Not fixed:**
  - #8340  
  - [Case 6](https://github.com/handsontable/handsontable/issues/8372#issuecomment-952653459)
    - This is understandable, as we're calling `setState` after resizing each of the selected columns, thus triggering `updateSettings` `n` amount of times. This could be optimized by calling `setState` only after the last of the selected columns was resized.
  
- **Can't reproduce:**
  - #7554 
  
- **Seems to not be related with the problem:**  
  - #7553 
    - Seems to be a problem with the way `afterValidate` hook is triggered - using the (undocumented) `postAfterValidate` hook seems to resole the problem.
    
@AMBudnik @adrianszymanski89

**Comment by warpech** [comment] 2022-03-09 18:21
This issue as well as linked issues #7567, #7263, #7165 should be closed as fixed by the upcoming version Handsontable 12.0.0.

**Comment by aninde** [comment] 2022-03-14 19:34
Fixed with the newest v12.0.0 https://jsfiddle.net/573h2Lam/

**Comment by adrianszymanski89** [comment] 2022-03-16 10:11
Check and inform [ZD](https://handsontable.zendesk.com/agent/tickets/28360)

**Comment by AMBudnik** [comment] 2022-04-29 07:08
All issues that were linked and described as solved within this epic were fixed by Handsontable v12.

For everyone who is tracking changes to this topic please check our release notes https://handsontable.com/docs/release-notes/#_12-0-0 and the migration guide https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls

**Closed by AMBudnik** 2022-04-29 07:08 UTC
Labels: Core: update settings, Epic
