### ISSUE TITLE
Enabling the `filters` plugin will degrade performance.

### ISSUE THREAD

**Issue by matsushita-nagatoshi** [handsontable/handsontable#4352] opened 2017-06-29 03:52 UTC
### Description

I displayed 10000 data, With the `filters` plugin of handsontable enabled.

When editing a specific cell, the screen froze.

As a result of investigation, it was found that filtering process was carried out every time the cell was changed.

And, I investigated why it takes time, and found that it takes time to sort the `unifyColumnValues` function.

This function is of the order of `O (n)` if there are n unique values for n data.

If there are 10000 cases, 10000 comparisons will be made.

```javascript
export function unifyColumnValues(values) {
  if (SUPPORT_FAST_DEDUPE) {
    values = Array.from(new Set(values));
  } else {
    values = arrayUnique(values);
  }
  values = values.sort(function(a, b) {
    if (typeof a === 'number' && typeof b === 'number') {
      return a - b;
    }

    if (a === b) {
      return 0;
    }

    return a > b ? 1 : -1;
  });

  return values;
}
```

Since I cause deterioration of performance, the following implementation was done so that the filtering process is not performed every time the cell is changed.

```javascript
function createOFiltersPlugin(hotInstance)
{
  // Get constructor from instance of `Filters`.
  const _BaseFilters = hotInstance.getPlugin('filters').__proto__.constructor;

  // Inherit the `Filters` class and create a new class.
  const OFilters = function (hotInstance) {
    _BaseFilters.call(this, hotInstance);
  };
  OFilters.prototype = Object.create(_BaseFilters.prototype);
  OFilters.prototype.constructor = OFilters;
  OFilters.prototype.__super = _BaseFilters.prototype;

  // Ovverride, not to work.
  OFilters.prototype.onAfterChange = function(changes)
  {
    return;
  };

  return OFilters;
}

// Create dummy handsontable instance, to create new filters plugin.
const dummyHotInstance = new Handsontable(element, {filters: true});
const OFiltersPlugin = createOFiltersPlugin(dummyHotInstance);
dummyHotInstance.destroy();

// Enable new filters plugin, and run handsontale.
Handsontable.plugins.registerPlugin('ofilters', OFiltersPlugin);
const hotInstance = new Handsontable(element, {ofilters: true});
```

Would not it be possible to provide a means to avoid it even if you do not implement it like the above?

For example, to make it optional.

### Steps to reproduce

None

### Demo

None

### Your environment

* Handsontable version: pro 1.11.0(free trial)
* Browser Name and version: chromium 58.0.3029.81
* Operating System: Gentoo Linux

**Comment by AMBudnik** [comment] 2017-08-04 07:57
Thank you for sharing (related GL #164)

**Comment by AMBudnik** [comment] 2018-01-17 12:44
If we create a table with 50k cells (5000 x10) and we try to delete content from all of them the table freezes browser (tested on Chrome 63). The more cells we have the bigger the lag between a table with and without filters enabled.

**Comment by alarie** [comment] 2019-04-24 20:26
@AMBudnik Deleting data is just one issue. A more frequent (for us) use case is filtering a column and then editing all remaining values in that column by clicking the column header, entering data and pressing cmd/ctrl+enter. 
If you do that without applying a filter it's usually quite fast in handsontable v6-pro/7 (though weirdly not in your 5k example here), but if you do that after applying a filter that leaves more than a few rows, that edit will take ages and freeze the browser.

**Comment by AMBudnik** [comment] 2019-04-25 13:14
Hey @alarie 

thank you for sharing the use case. Can I ask you to record the behavior with and without the filters?

**Comment by alarie** [comment] 2019-04-26 05:59
@AMBudnik see here: 
![handsontable-issue](https://user-images.githubusercontent.com/1296462/56786330-f6b33200-67f8-11e9-93f2-4735185fa3be.gif)

Steps to reproduce:

1. Load fiddle: https://jsfiddle.net/824jrnoa/2/
2. Click col header `B` ( ensure complete column `B` is highlighted)
3. Type anything, e.g. "Test" and hit cmd+enter (ctrl+enter)
4. *Watch cell content changing nice and quickly*
5. Click the dropdown in col `C`
6. In `Filters Section` remove tick for `C1`, keep everything else
7. Apply filter
8. Click col header of `C` (ensure complete column `C` is highlighted)
9. Type anything, e.g. "Test" and hit cmd+enter (ctrl+enter)
10. *Watch as browser freezes*

Tested on 
- macOS Mojave
- Vivaldi 2.4.1488.35 (Stable channel) (64-Bit) (Underlying chrome: Chrome/73.0.3683.88)

**Comment by AMBudnik** [comment] 2019-04-26 08:13
Thank you for sharing the video and this use case. You are right when I add the filter it looks a couple of seconds for the browser to respond. In response, the browser crashed.

**Comment by alarie** [comment] 2019-04-29 10:32
@AMBudnik with a modification of @matsushita-nagatoshi's fix the issue is gone, but it would be nice if this was fixed in handsontable itself. Any plans for that?

**Comment by AMBudnik** [comment] 2019-04-29 12:00
Hey Simon,

we're working on a completely different structure of renderers https://github.com/handsontable/handsontable/issues/5769 so this code may not fit into the new scheme.

**Comment by alarie** [comment] 2019-04-30 08:32
Hi Aleksandra, 

The new renderers look really promising, but I don't see how that will improve the performance when editing a filtered column yet. As @matsushita-nagatoshi wrote in his original issue at the top, the problem comes from the `onAfterChange` hook. 

Basically what's happening is, the filter plugin registers itself to get notified after changes. Once such a change happened, it tries to determine which values should remain in the "Filter by value"-list of the dropdown. For that it walks through all values in the column and creates a uniques list. 
But as in a batch-change action that `onAfterChange` hook is called for each cell (so possibly thousands of times), that slows down the browser tremendously (and eventually kills it). 

My fix does two things: 
a) it debounces calls to `onAfterChange`
b) it moves the `updateValueComponentCondition` call into a `requestIdleTimeout`-based task queue, so it's only executed once the browser has some time to do so.
The result is, that the filter may not have the right values right after editing, but should have them within a reasonable time after the editing action completed.
It's surely not the perfect solution (that's why I don't share my code here), but it's one that's working for us.

**Comment by AMBudnik** [comment] 2019-04-30 08:58
Yes, you are right - the eco-renderers may not change the filtering performance remarkably - that is why this topic is still opened and labeled.
However, the presented code, even if working great - is still a workaround (I've asked our developer to check it). That is why I did not want to waste your time with the pull requests.

After doing the changes for renderers we'll be able to get a fresh look at the way we render data and how the calls are made.

Thank you for being active on this topic. We treat Filters with the highest priority. This subject will surely be continued as soon as possible.

**Comment by AMBudnik** [comment] 2021-03-16 07:11
In the first demo, the performance of removing a column for a table with filters hang the browser.
Demo v 8.3.0 http://jsfiddle.net/731o9rbp/ seems to remove the columns with the same speed for the table with and without filters.

![filters](https://user-images.githubusercontent.com/10757813/111269572-1b079a00-862f-11eb-999f-bf1017d96cf5.gif)

I think that we can call this issue solved.

**Closed by AMBudnik** 2021-03-16 07:11 UTC
Labels: Core: performance, Filtering, Type: Change
