### ISSUE TITLE
Add Right To Left Support

### ISSUE THREAD

**Issue by mojtabakaviani** [handsontable/handsontable#83] opened 2012-07-26 13:15 UTC
please add right to left view same excel

**Comment by Nirhe** [comment] 2015-02-07 20:46
Does anyone figured it out yet? is there any better solution beside the css?

**Comment by Nirhe** [comment] 2015-02-08 20:00
Btw i figured that in line 3045 inside the method walkontableCalculateScrollbarWidth  i just comment out those two lines:
// outer.style.top = "0px";
  //  outer.style.left = "0px";
and it fixed that

**Comment by Nirhe** [comment] 2015-02-08 20:02
@elombashy - the issue is with the style inside the handsontable.js. see my previous comment

**Comment by elombashy** [comment] 2015-02-10 05:04
that's wondefull. thanks @Nirhe.

**Comment by AMBudnik** [comment] 2015-05-11 08:30
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by chennoam7** [comment] 2017-01-28 06:04
Hi,

Do you have any clue when this feature will be available?

Thanks,
Chen

**Comment by AMBudnik** [comment] 2017-01-30 09:07
Hi @chennoam7 this is a pretty complicated case. 

If we would like to add RTL support we would need to:
1. Allow adding characters from right to left in a cell editor
2. Display TD content and all labels (context menu, filers, headers) in this mode
and few more things as well. 

Currently we do not have any dead-line for this task.

**Comment by ysaadh** [comment] 2017-02-08 18:44
Please Solve This Issue ASAP

**Comment by AMBudnik** [comment] 2017-02-09 09:32
Hi @ysaadh this is not an issue. We never supported RTL. 
As I wrote in my latest post 10 days ago this task is really time consuming and we currently do not have an empty development window to put it there.

**Comment by alexlehm89** [comment] 2019-03-06 14:32
I solved this problem for myself by Styles:

`
body {
  .ht_clone_left {
  	left: unset !important;
  }
  .ht_clone_top {
  	left: unset !important;	
  }
  .ht_clone_top_left_corner {
  	left: unset !important;
  }
  /*.current {
  	box-shadow: inset 0 0 0 2px #5292f7;
  }*/
}

[dir="rtl"]{
  #rowsTable {
    direction: ltr;
    -ms-transform: scaleX(-1);
    -moz-transform: scaleX(-1); /* Gecko */
    -o-transform: scaleX(-1); /* Operah */
    -webkit-transform: scaleX(-1); /* webkit */
    transform: scaleX(-1); /* standard */
    filter: FlipH; /* IE 6/7/8 */
    td, th, textarea {
      direction: rtl;
      -ms-transform: scaleX(-1);
      -moz-transform: scaleX(-1); /* Gecko */
      -o-transform: scaleX(-1); /* Operah */
      -webkit-transform: scaleX(-1); /* webkit */
      transform: scaleX(-1); /* standard */
      filter: FlipH; /* IE 6/7/8 */
    }
  }
}`

**Comment by krzysztofspilka** [comment] 2021-09-27 17:32
@mojtabakaviani we're on it!

**Comment by Siemienik** [comment] 2021-09-28 10:28
Issue followed by #8760.

**Closed by Siemienik** 2021-09-28 10:28 UTC
Labels: Type: Feature
