### ISSUE TITLE
Paste off-by-one after show/hide column

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6742] opened 2020-02-28 21:16 UTC
### Description

I was trying to copy & paste some data on a sheet that had hidden columns and ran into an unexpected behavior. Could be related to #6728?

Expected behavior: 
- copy cell B2
- hide column B
- show column B
- paste in cell B2

Actual behavior
- copy cell B2
- hide column B
- show column B
- pastes in cell *C2*

### Steps to reproduce
See this fiddle: https://jsfiddle.net/dkamgv5y/

And this video: 

![Feb-28-2020 14-56-47](https://user-images.githubusercontent.com/881931/75586948-0748c000-5a3b-11ea-8131-9dfa39c551c5.gif)

### Your environment
* Handsontable version: I think the demo is 7.4, but it's happening to me on 8 beta.
* Browser Name and version: Chrome
* Operating System: Mac

**Comment by aarondfrancis** [comment] 2020-02-28 23:55
I *think* I traced it down to the fact that `skipColumnsOnPaste` is never set back to true after a column is hidden -> shown again.

It's only ever set to true.

https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/plugins/hiddenColumns/hiddenColumns.js#L332

If I'm understanding correctly, it should be set to true OR false there, because the true value will persist incorrectly.

I've tried this plugin and it seems to be working for me:

```js

ColumnEnhancements.prototype.afterGetCellMeta = function (row, col, cellProperties) {
    let hiddenColumns = this.hot.getPlugin('hiddenColumns');
    let copyPasteEnabled = hiddenColumns.copyPasteEnabled;
    let isHidden = hiddenColumns.isHidden(col);

    let shouldSkip;

    // C&P enabled when hidden, or the column is not hidden: don't skip.
    if (copyPasteEnabled === true || isHidden === false) {
        shouldSkip = false;
    } else {
        shouldSkip = true;
    }

    let currentValue = cellProperties.skipColumnOnPaste;

    if (currentValue !== shouldSkip) {
        cellProperties.skipColumnOnPaste = shouldSkip;
    }
}


```

**Comment by wojciechczerniak** [comment] 2020-03-02 08:45
Added to #6178, thanks @aarondfrancis, we're refactoring hidden columns in #6547 as a continuation of our work in beta1, we will check this.

**Comment by aarondfrancis** [comment] 2020-03-02 14:43
Thanks @wojciechczerniak. 

I know it's probably tough to say, but do y'all have an internal goal for merging #6547? No pressure, just curious.

**Comment by aarondfrancis** [comment] 2020-03-02 17:11
It seems like the main problem is when turning `copyPasteEnabled` off in the hidden columns plugin. If you leave that on everything pretty much works, except of course that hidden cells get copied!

Here's my temporary workaround plugin:

```js
import PluginFactory from './plugin-factory';
import {xor} from 'lodash';

// To test this in future releases:

// 1. Copy any value.
// 2. Hide a column
// 3. Show the column.
// 4. Paste the value in that column.
// The expected result should be that the value is correctly pasted into
// the column you tried to paste it into. Without this plugin, it would
// paste into the column immediately to the right of the column you tried.

// 1. Copy any value.
// 2. Hide a column e.g. B.
// 3. Select columns spanning the hidden column, e.g. A-C.
// 4. Paste.
// The expected result is that A and C will hold the pasted value. Without
// this plugin, A, C, and D will hold the pasted value.
// Also confirm that the value wasn't pasted in the previously hidden column,
// and that the previously hidden column is not read-only.

// 1. Hide a column that has a value.
// 2. Select columns spanning the hidden column.
// 3. Copy
// Ensure that the hidden column's value was not copied to the clipboard.


let CopyBugfix = PluginFactory('copyBugfix');

CopyBugfix.prototype.isEnabled = function () {
    return true;
}

CopyBugfix.prototype.enable = function () {
    // Force copy paste enabled to be on, it's the only way
    // any of this really works. We'll later make sure no
    // hidden cells get copied.
    this.hot.getPlugin('hiddenColumns').copyPasteEnabled = true;

    this.hot.addHook('beforeCopy', this.beforeCopy.bind(this));

    this.hot.addHook('beforeHideColumns', this.columnVisibilityChange.bind(this));
    this.hot.addHook('afterUnhideColumns', this.columnVisibilityChange.bind(this));
}

CopyBugfix.prototype.beforeCopy = function (data, coords) {
    // Because we force copyPasteEnabled to be on, we need to
    // manually cut out any values from hidden columns when copying.
    let splice = [];

    let hiddenColumns = this.hot.getPlugin('hiddenColumns');

    coords = coords[0];

    // Look through the coordinates of the data that we're copying
    // to see if there are any hidden columns.
    for (let c = coords.startCol, i = 0; c <= coords.endCol; c++, i++) {
        // If this column is hidden, push the index of the
        // column into an array so that we can later cut
        // that value out of the data.
        if (hiddenColumns.isHidden(c)) {
            splice.push(i);
        }
    }

    // When splicing, we need to go highest index to lowest, otherwise
    // everything will get dorked up.
    splice.reverse();

    // Loop each row and cut out the values from hidden columns.
    for (let row = 0; row < data.length; row++) {
        for (let s = 0; s < splice.length; s++) {
            data[row].splice(splice[s], 1);
        }
    }
}

CopyBugfix.prototype.columnVisibilityChange = function (currentHideConfig, destinationHideConfig) {
    let changes = xor(currentHideConfig, destinationHideConfig);

    let rows = this.hot.countRows();

    for (let c = 0; c < changes.length; c++) {
        let column = changes[c];
        let isHidden = destinationHideConfig.includes(column);

        for (let row = 0; row < rows; row++) {
            let cellProperties = this.hot.getCellMeta(row, column)

            if (isHidden) {
                // As a temporary fix for https://github.com/handsontable/handsontable/issues/6743,
                // we set all hidden cells to read only. The functional outcome is that pasting
                // doesn't happen (because it's read only) and the bug doesn't present
                // itself. We also store the actual value so we can fix it later.
                let actualReadOnly = cellProperties.readOnly;

                cellProperties.cachedReadOnlyValue = actualReadOnly;
                cellProperties.readOnly = true;

            } else {
                // If the column is visible, we need to restore the real read only value
                if (cellProperties.hasOwnProperty('cachedReadOnlyValue')) {
                    cellProperties.readOnly = cellProperties.cachedReadOnlyValue;
                    delete cellProperties.cachedReadOnlyValue;
                }
            }
        }
    }
}

export default CopyBugfix;
```

**Comment by wojciechczerniak** [comment] 2020-03-03 09:27
> Thanks @wojciechczerniak.
> 
> I know it's probably tough to say, but do y'all have an internal goal for merging #6547? No pressure, just curious.

Last month 🙈 Refactor is mostly done, we're adding more tests.

**Comment by aarondfrancis** [comment] 2020-03-03 14:59
> Last month 🙈

Boy do I know that feeling! 😂

**Comment by pnowak** [comment] 2020-05-08 11:16
The issue still hasn't resolved in 8.0.0.-beta2-rev2 - https://jsfiddle.net/Lpkf4vho/1/

**Comment by AMBudnik** [comment] 2020-06-16 11:14
**Remains the same** in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/wmy27u14/

**Comment by wszymanski** [comment] 2020-09-07 13:47
Not fixed within https://github.com/handsontable/handsontable/pull/7246.

**Comment by haraleib** [comment] 2022-03-14 12:05
Is there any activity concerning this Bug? I also reported this issue in https://github.com/handsontable/handsontable/discussions/8978

**Comment by AMBudnik** [comment] 2024-04-19 12:14
Hi @aarondfrancis @haraleib 

Could you please check the latest version if the issue is still replicable?

I tested the @aarondfrancis example https://jsfiddle.net/bpy7rwzx/ with the latest version 14.3.0, and the issue seems to be fixed.

**Closed** 2024-06-06 09:49 UTC
Labels: Status: Answered
