### ISSUE TITLE
Horizontal scroll of table causes wrong positioning of comments on table cells

### ISSUE THREAD

**Issue by Bwca** [handsontable/handsontable#9870] opened 2022-09-06 10:00 UTC
### Description
In a table that has horizontal scrollbar and comments in fixed columns, scrolling columns causes comments to be shifted to the left, which results in their wrong positioning or rendering outside of viewport if you scroll right too far.
The behavior is observed through versions 9-12.

### Steps to reproduce
1. Create a table with some some fixed columns with comments and horizontal scroll.
2. Hover over the cells with comments and note the comment window positions.
3. Scroll table to the right.
4. Hover over the cells with comments and note the comment window have shifted to the left

### Demo
demo: https://jsfiddle.net/BwcaJS/Lpamgtbc/3/

### Your environment
* Handsontable version: 9-12
* Browser name and version: Google Chrome Version 105.0.5195.53 (Official Build) (64-bit)
* Operating system: Windows

If there is a workaround to combat it, I will be as happy as the day is long :)

**Comment by adrianszymanski89** [comment] 2022-09-06 13:44
Hi @Bwca 

Thank you for reporting that issue. The problem seems to be directly linked to the `fixedColumnsLeft/Start` option.  This option is known for causing problems with alignment properties within the Handsontable. I'm afraid there's no workaround for that at the moment.

**Comment by AMBudnik** [comment] 2022-09-08 09:05
Related: https://github.com/handsontable/handsontable/issues/9645

**Comment by AMBudnik** [comment] 2022-09-28 13:30
I'm closing the issue as a duplicate of #9645 

I will notify you once we fix the main issue @Bwca

**Closed by AMBudnik** 2022-09-28 13:30 UTC
Labels: Type: Bug, Comments

**Comment by AMBudnik** [comment] 2022-12-14 13:11
Hi @Bwca 

I have good news! We just fixed the mentioned issue. Please update to Handsontable v12.3.0 - it should solve the bug in your application as well.

ps. here you can read more about the changes https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-3-0

**Comment by Bwca** [comment] 2022-12-14 13:14
Jolly good, thank you @AMBudnik!
