### ISSUE TITLE
Keydown performance in Chrome (Version 47.0.2526.73 (64-bit) - Mac OSX) + IE 9

### ISSUE THREAD

**Issue by viveksunder** [handsontable/handsontable#3039] opened 2015-12-03 22:44 UTC
Hi All,

I'm using Handsontable for a project at work and the docs have been extremely helpful in figuring out how to get my stuff accomplished. I've hit a wall with a performance issue that I'm only encountering on Chrome (Version 47.0.2526.73 (64-bit)) on a Mac and IE 9 on a Windows machine. 

The issue occurs when I press and hold a key (other than the arrow keys) in a cell. This basically causes a delay of a couple of seconds depending on how long I hold the key and there is also a delay of a couple of seconds before the key repeats show up. Not that pressing and holding a key is a valid use-case, but there is a noticeable delay with typing at a regular speed in handsontable cells.

Handsontable Version - 0.18.0 & 0.20.1

Options - {
    height:600,
    rowHeaders: true,
    colWidths:110,
    stretchH:'all',
}

Using Chrome Dev Tools Timeline I can see that there are a whole bunch of TextEditor onBeforeKeyDown's (line 8102) invoked that subsequently trigger resize (line 19221) that result in style recalculations that I suspect are slowing it down greatly. This also applies to Autocomplete cells. 

I'd be happy to provide any more information that you need in order to figure out what's happening. Appreciate any help that you can provide on this.

**Comment by viveksunder** [comment] 2015-12-03 22:48
Another thing just as an FYI that I thought was curious - this does not happen on the handsontable website with the 100k cells table.

**Comment by AMBudnik** [comment] 2015-12-04 11:18
Hi @viveksunder, how I can reproduce it? I'm on OSX Chrome 47 and I tried [numeric demo](http://docs.handsontable.com/0.20.2/demo-numeric.html) on the page and at JSFiddle and I can't get what you described.

**Comment by viveksunder** [comment] 2015-12-04 20:20
Hi @AMBudnik. I have been unable to reproduce this on jsfiddle. The fiddle is here by the way - http://jsfiddle.net/sviveksunder/txdkf3na/

This is pretty close to the actual table in terms of data, style and structure, where I'm encountering this issue. Since I've been unable to reproduce this in a jsfiddle, I've recorded a screen cast and also exported my Chrome Timeline data to a file. I've attached them both to this comment. Hope that helps. 

I'd be happy to try and provide you anything else you think might help in figuring this out. For what it's worth, I think it is some kind of weird CSS interaction + Chrome that is causing a lot of reflows/repaints that's slowing down editing on the table.


[Archive.zip](https://github.com/handsontable/handsontable/files/52464/Archive.zip)

**Comment by viveksunder** [comment] 2015-12-04 20:27
FYI - The Timeline data file was recorded while holding down the 'a' key on a Text Cell. Other non-handsontable text input fields on the page do not suffer from the same delay.

**Comment by AMBudnik** [comment] 2015-12-07 17:19
Thanks for files it really does not work smoothly. 

I made a simplified demo http://jsfiddle.net/cve6nuuh/1/ cause I saw that you get the same thing after deleting in 'edit mode' char after char and I couldn't reproduce it either. 

Is there a possibility to comment other parts of your code and try to check if there are some interferences?

**Comment by viveksunder** [comment] 2015-12-07 19:58
@AMBudnik  - Thanks very much for taking the time out to take a look at this. I realize that if I could reproduce this it would be a lot easier to narrow down the issue and figure this out. I tried doing a couple of different things on my app, but so far have been unsuccessful. 

I already tried to comment out a couple of points in my app prior to opening this ticket. But that did not help. I'll try to replicate my app's CSS. HTML and JS environment on the jsfiddle I created to see if any of that causes it. It may be a few days before I'm able to get that done. Thanks again for taking a look at this.

**Comment by AMBudnik** [comment] 2015-12-08 12:19
Alright - take your time. 

I'm closing this issue while I can't help any way now, but as soon as you'll get something do not hesitate to write me back and we'll reopen this one.

**Closed by AMBudnik** 2015-12-08 12:19 UTC
Labels: Answered

**Comment by viveksunder** [comment] 2015-12-09 22:17
Not a problem. I will write back to you as soon I have something. Thanks for all the help.

**Comment by AMBudnik** [comment] 2015-12-09 22:19
@viveksunder OK, hopefully see you soon with some clues.

**Comment by Rex90** [comment] 2017-03-28 11:42
was this ever resolved/recreated? I am seeing delay in my app when user tries to input text. There is a delay between when they start typing and when the text appears in the table.

**Comment by AMBudnik** [comment] 2017-04-03 11:13
Hi @Rex90 
the issue was closed in a lack of detailed information on how to replicate the issue. Please notice that it relates to the keyDown performance - not the general performance of IE.
