### ISSUE TITLE
with rowHeights and mergeCells options, handsontable scroll is not moving properly

### ISSUE THREAD

**Issue by violin0631** [handsontable/handsontable#3904] opened 2016-11-19 05:52 UTC
### Description
I created handsontable with rowHeights and mergeCells options.  
When i select cell, the scroll is not moving properly.

### Steps to reproduce
1. Open demo
2. Select cell (D5, D13...) -> scrollbar is moved

### Demo
http://jsfiddle.net/L43xbdx8/

### Your environment
* Version: 0.28.1
* Browser Name and version: Chrome 54.0.2840.71
* Operating System: Win 10

**Comment by AMBudnik** [comment] 2016-11-21 09:09
Hi @violin0631 

Are you getting the same situation as here?

![bug](https://cloud.githubusercontent.com/assets/10757813/20476675/747d6ad4-afd2-11e6-97a5-9a69b821d49d.gif)

(works the same in 0.29.0)

**Comment by violin0631** [comment] 2016-11-21 09:14
@AMBudnik Thankyou for reply.
Yes, the same situation as above.

**Comment by AMBudnik** [comment] 2016-11-21 09:24
OK, thanks for sharing. I've marked this issue as a bug.

**Comment by AMBudnik** [comment] 2018-04-24 12:38
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by AMBudnik** [comment] 2018-09-06 12:51
It works even worse if we select `D5`. I am instantly scrolled under the blank area. Tested on `5.0.1`

![gif](https://user-images.githubusercontent.com/10757813/45156961-f1f52b80-b1df-11e8-8d01-34727a4ceed1.gif)

As described it works fine with `rowHeights` not being set.

![gif](https://user-images.githubusercontent.com/10757813/45157162-95464080-b1e0-11e8-96c6-c0c1d21773cd.gif)

The issue starts to happen for `rowHeights` > `37`, at this settings after selection we are moved `3` pixels up

![image](https://user-images.githubusercontent.com/10757813/45157419-6c727b00-b1e1-11e8-8852-460e11fecbf6.png)

After trying some options:
With `37` `rowHeights` we are scrolled `3` pixels up (+3)
With `38` `rowHeights` we are scrolled `7` pixels up (+4)
With `39` `rowHeights` we are scrolled `12` pixels up (+5)
With `40` `rowHeights` we are scrolled `17` pixels up (+5)
With `41` `rowHeights` we are scrolled `22` pixels up (+5)

and at `42` it goes totally crazy and scroll a couple of cells further and show empty area. The `22` px is an exact default row height value so maybe it is related.

**Comment by AMBudnik** [comment] 2019-09-26 13:12
We decided to close this topic as we are covering pretty much the same case here https://github.com/handsontable/handsontable/issues/3837 and as https://github.com/handsontable/handsontable/issues/3837 was the first one published and it has more comments/followers it will be the one to keep.

I'm attaching the demo from this post to https://github.com/handsontable/handsontable/issues/3837 to be sure that both of them got tested.

**Closed by AMBudnik** 2019-09-26 13:12 UTC
Labels: Merge cells, Priority: normal, Type: Bug
