### ISSUE TITLE
merge cells fails when using fixedColumnsLeft

### ISSUE THREAD

**Issue by i255** [handsontable/handsontable#2162] opened 2015-02-16 12:21 UTC
the first column is not rendered properly. see:
http://jsfiddle.net/j84390x1/

**Comment by AMBudnik** [comment] 2015-03-11 09:15
When I added rowHeaders with 'true' value it works fine. Interesting bug, thanks for sharing.

**Comment by AMBudnik** [comment] 2015-05-05 13:09
[Here's](https://jsfiddle.net/AMBudnik/j84390x1/1/) a little example on how it looks with 0.15.0-beta2

There are two scenarios:
One with `rowHeaders: true` 
One with commented 'rowHeaders' (equal to 'rowHeaders: false`)

![qq](https://cloud.githubusercontent.com/assets/10757813/7473050/525d099e-f338-11e4-9b71-40103ec344d0.gif)

**Comment by AMBudnik** [comment] 2016-03-16 14:11
Confirmed with 0.24.1

**Comment by lucamaral** [comment] 2017-11-23 16:11
#2672

**Comment by AMBudnik** [comment] 2018-04-16 12:17
The issue is still replicable. I've just tested it using v `2.0.0` here https://jsfiddle.net/v5q788nj/

**Comment by wojciechczerniak** [comment] 2019-02-21 08:44
Duplicate of #2672

**Closed by wojciechczerniak** 2019-02-21 08:44 UTC
Labels: Plugin: merge cells, Priority: normal, Type: Bug
