### ISSUE TITLE
Wrong result of this statement in case of multiple handsontables in the page

### ISSUE THREAD

**Issue by gpavlovych** [handsontable/handsontable#5985] opened 2019-04-24 17:06 UTC
In this statement, if there is multiple handsontables in the page, overlay element of the 1st one is retrieved which leads to potential exceptions when the function **overlayContainsElement** returns **false** but should return **true**.
https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/helpers/dom/element.js#L212

**Comment by AMBudnik** [comment] 2019-04-26 10:05
Welcome @gpavlovych 

can you share a recording? Something that can show the issue 'in action'.

I also highly encourage you to create a PR with a test that will allow us to check if that is an actual cause of the issue.

**Comment by gpavlovych** [comment] 2019-04-29 00:20
https://jsfiddle.net/pavlheo/majxudog/55/ here is the example of 2 handsontables in the page where the above function might not work correctly.

**Comment by AMBudnik** [comment] 2019-04-29 07:56
Hey @gpavlovych 

it looks like the issue is reported here https://github.com/handsontable/handsontable/issues/5959

If so, it is already fixed with a PR https://github.com/handsontable/handsontable/pull/5964/files (merged, waiting for release). 

Please confirm if it is the same case.

**Closed** 2019-04-30 09:51 UTC
Labels: Status: Answered
