### ISSUE TITLE
[IE sorting bug]_removeClass called 'isSuportMultipleClassesArg' but no args.

### ISSUE THREAD

**Issue by jun109** [handsontable/handsontable#6789] opened 2020-03-31 07:20 UTC
https://github.com/handsontable/handsontable/blob/88d78a5be5e37ad703c11914c86690d2436d3024/src/helpers/dom/element.js#L329

**Comment by AMBudnik** [comment] 2020-03-31 08:11
Hi @jun109 

If you have ideas on how to alter the code please share a pull request.

The following code related to helpers (they are not a part of the official API and are not supported to use by external developers).

**Comment by jun109** [comment] 2020-04-01 02:02
dear @AMBudnik 

Thank you for your comment.
In IE11, this problem was discovered as a result of investigating the cause of the registered CSS class not being deleted when the sort was changed by the column header.
The countermeasure is to specify rootDocument as a parameter of this function as well as the _addClass function.
https://github.com/handsontable/handsontable/blob/88d78a5be5e37ad703c11914c86690d2436d3024/src/helpers/dom/element.js#L305
Thank you for your support.

**Comment by AMBudnik** [comment] 2020-04-01 11:28
> In IE11, this problem was discovered as a result of investigating the cause of the registered CSS class not being deleted when the sort was changed by the column header.

Can you record it and send over the settings where the issue can be replicable?

**Comment by jun109** [comment] 2020-04-02 02:13
Handsontable's sort feature demo, which can be reproduced by clicking the same column header three times.
[Basic plugin configuration](https://handsontable.com/docs/7.4.2/demo-sorting.html)

**Comment by AMBudnik** [comment] 2020-04-02 08:49
Thank you for sharing the description. I have replicated the issue.

### Steps to reproduce
1. Sort column 'Code Name' more than 3 times

![GIF](https://user-images.githubusercontent.com/10757813/78228809-751b5800-74cf-11ea-990c-b0b70e132e5a.gif)


**Result**
The 'arrow down' char stays the same.

### Demo 
https://handsontable.com/docs/7.4.2/demo-sorting.html (7.4.2)

### Additional info
* works well on Edge

**Comment by aninde** [comment] 2020-06-18 14:37
Hi @jun109 

As[ support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

This issue has been tested with Handsontable `8.0.0-beta2-rev15`https://jsfiddle.net/f0ws763h/ on Windows 10 and Edge browser `v16`, `v44`, `v83 (latest)`, Edge Dev `v85`.

Where the **issue is not replicable**, due to that I'm closing it.


<img width="329" alt="Screenshot 2020-06-18 at 16 35 50" src="https://user-images.githubusercontent.com/30186818/85033983-da532100-b181-11ea-8478-f9e0eab84adb.png">
<img width="345" alt="Screenshot 2020-06-18 at 16 36 00" src="https://user-images.githubusercontent.com/30186818/85033998-dfb06b80-b181-11ea-8cbd-36697b090a4b.png">

**Closed by aninde** 2020-06-18 14:37 UTC
Labels: Column sorting, Core: selection, Edge, Type: Bug

**Comment by jun109** [comment] 2020-09-11 03:42
dear @aninde 

Thank you for your comment.
Modern browsers other than IE support ClassList in the first place, so this problem does not occur.
I understand that IE is not supported in version 8.0 or later, so it is not supported, but since it is a very simple bug, I wanted you to support it including the old version.

**Comment by AMBudnik** [comment] 2020-09-11 07:55
Hi @jun109 I saw that you already mentioned code in the first comment. If you could share a pull request I will ask the team to review it. 

> I wanted you to support it including the old version.

we do not update older versions. Each fix/alteration becomes a part of a new version.
