### ISSUE TITLE
[svg] Loss of right border of rowHeader while scrolling when fixedRowsTop and fixedRowsBottom are enabled

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6646] opened 2020-01-16 11:11 UTC
### Description
During the second horizontal scrolling, we lose the right border rowHeaders when fixedRowsTop and fixedRowsBottom are enabled. Only the border that is not associated with fixed is not displayed.

I scrolled it with the Apple Magic mouse, without clicking or losing focus. That can be reproduced with TrackPad or by pressing the scrolling wheel and moving the mouse sideways in a typical mouse.

### Steps to reproduce

1. Open demo https://jsfiddle.net/aninde/eq263gvh/ `8.0.0-svg-#PR6157 v.` 
2. Scroll it horizontal two times

### Actual result:
Right rowHeader is missing
<img width="143" alt="Screenshot 2020-01-16 at 12 08 44" src="https://user-images.githubusercontent.com/30186818/72520098-ff510a00-3858-11ea-82c2-bc3ea6d3396b.png">
![right-header-border-ff-6157](https://user-images.githubusercontent.com/30186818/72520104-01b36400-3859-11ea-955c-a3f64a8669ce.gif)

### Expected result:
All rowHeaders should be visible while scrolling in each direction.
https://jsfiddle.net/aninde/q7k6cmz8/  `7.3.0 v.` fixed
<img width="94" alt="Screenshot 2020-01-16 at 12 09 35" src="https://user-images.githubusercontent.com/30186818/72520149-1bed4200-3859-11ea-9781-0ea8f7938862.png">

### Demo

https://jsfiddle.net/aninde/eq263gvh/ `8.0.0-svg-#PR6157 v.` broken
https://jsfiddle.net/aninde/q7k6cmz8/  `7.3.0 v.` fixed

### Your environment
* Handsontable version: 8.0.0-svg-PR#6157
* Browser Name and version: Firefox, Safari, Chrome
* Operating System: macOS

**Comment by aninde** [comment] 2020-01-16 11:20
This error did not appear in the first stage of testing https://github.com/handsontable/handsontable/pull/6157. It can't be replicated on my builds from late November and early December.

**Comment by warpech** [comment] 2020-01-22 09:12
The problem is quite complex. I introduced this problem as part of my refactor in https://github.com/handsontable/handsontable/pull/6594 and it was not caught by automated tests. 

Moreover, the problem seems fixed if I remove an ugly, untested 3-year old workaround (c315eaf176ec12f1cecfc43d1c4ae8c7b37ff02b), however the manual test proves that then the 3-year old problem https://github.com/handsontable/handsontable/issues/3850 returns.

The only solution I can propose is to do significant improvements to the classes `innerBorderLeft`, `innerBorderTop`. It will help if I do https://github.com/handsontable/handsontable/issues/6651 first.

**Comment by warpech** [comment] 2020-01-23 13:21
It was agreed yesterday between @wojciechczerniak, @aninde and me, that this regression will be fixed AFTER https://github.com/handsontable/handsontable/pull/6157 is merged.

**Comment by aninde** [comment] 2020-01-25 19:29
This bug also appears on mobile: iPads and smartphones ( tested on macOS and Android).

**Comment by warpech** [comment] 2020-02-18 16:46
Fixed in 59b71c2942e0784f961a31d7448900bda23f9aa6, as part of the SVG borders PR (#6157).

**Comment by krzysztofspilka** [comment] 2021-07-21 14:46
This is an issue reported for the SVG borders project, which was rejected and won't be implemented in Handsontable.

**Closed by krzysztofspilka** 2021-07-21 14:46 UTC
Labels: Fixing, Mobile, Regression, Type: Bug, scroll
