### ISSUE TITLE
All rows and columns are not rendering when Handsontable was hidden or display: none

### ISSUE THREAD

**Issue by primeO** [handsontable/handsontable#5322] opened 2018-08-10 11:09 UTC
### Description
All rows and columns are not displaying , but columns and rows are displaying only on clicking the first row [it is not displaying column names for this ] . Any solutions for this .

### Steps to reproduce

					<script type="text/javascript">
                                            var data = //DATA GOES HERE ;

                                           
                                            var cols = [{
                                                    data: 'A1',
                                                   type: 'text'
                                          
                                                }, {
                                                    data: 'A2',
                                                   type: 'text'
                                                }, {
                                                     data: 'A3',
                                                   type: 'text'
                                                },
                                               {
                                                     data: 'A4',
                                                   type: 'text'
                                                },
                                               {
                                                     data: 'A5',
                                                   type: 'text'
                                                }

                                            ];

                                            var
                                                table = document.getElementById('losttable');

                                            var lostHot = new Handsontable(table, {
                                                data: data,
                                                columns: cols,
                                                stretchH: 'all',
                                                colHeaders: [
                                                        'A1',
                                                        'A2',
                                                        'A3',
                                                        'A4',
                                                         'A5',
                                                         'A6'
   
                                                 ],
                                                autoWrapRow: true,
                                                height: 500,
                                                rowHeights: 25,
                                                manualRowResize: true,
                                                manualColumnResize: true,
                                                contextMenu: true,
                                                sortIndicator: true,
                                                autoColumnSize: true,
                                                 columnSorting: true

                                            });

                                         
                                           setTimeout(function() {
                                                lostHot.render();
                                            }, 100);
                                            
                                        </script>

**Comment by alisanguo** [comment] 2018-08-13 07:06
I have the same question,do you have any solution?

**Comment by primeO** [comment] 2018-08-13 07:35
it should work with render() . for few tables it is working fine but for few tables it is not showing up , But if we click on the row then complete table is visible . 

iam also looking for a solution for this . and as well as search option demo

**Comment by AMBudnik** [comment] 2018-08-14 09:07
> it should work with render()

That's true. Usually, it helps. If it doesn't please share a demo where the issue can be replicable. I'll check what we can do to make it work properly.

**Comment by alisanguo** [comment] 2018-08-14 12:50
I found the same question because I use "display:none or block"  to make div display or hidden.When I set display to' block' from 'none', it happens.

**Comment by rhwilburn** [comment] 2019-01-24 21:38
It doesn't render the table if its starts with display: none (ie if you use bootstrap tabs where the tabs are defaultly hidden). As you show the tab the core table is shown without headers but as you edit the table the headers are re-rendered etc.) Using visibility instead works as you would expect, it seems there is an optimization with display: none around not rendering if it shouldn't be displayed but if that changes then it stays in a kinda dead state (probably requiring a manual render() call). This feels like a bug that should be fixed as it doesn't play nicely with other components etc, and was quite unexpected behavior to me.

**Comment by AMBudnik** [comment] 2019-01-25 10:36
Hi @rhwilburn 
Could you share an example where we'd be able to replicate the issue?

**Comment by rhwilburn** [comment] 2019-01-26 01:17
The project I have where I have issues (ie complex example) is: [https://stackblitz.com/edit/wzxmev](https://stackblitz.com/edit/wzxmev) which is forked so feel free to play with it. Click on the tabs at the top of the page to see the behavior where the spreadsheet shows but without columns sized and without the headers. Once you edit any cell then that col is resized correctly and all headers show.

**Comment by AMBudnik** [comment] 2019-01-28 11:12
Thank you for sharing the demos and examples, Richard. 

I have replicated the issues. I also noticed that in the first demo the second table appears when we change the window size. We may assume that basically any action which triggers the renderer works. 

When it comes to the second example on the StackBlitz it more a header thing, so it might be a different issue. Nevertheless, I am reopening the issue for further investigation.

**Comment by Sowcott** [comment] 2019-02-05 13:21
I have the same issue, when table is in a div with "display: none" before building the table

**Comment by mewalig** [comment] 2019-03-12 16:13
@rhwilburn, in your fiddle example, if you add ```window.setTimeout(()=>{hot2.render();});``` to the end of your code, the second table will appear on load. demo: https://jsfiddle.net/286rb4fy/5/ (this is the same as https://jsfiddle.net/wafny5h4/2/ but with that one line added). 

Doesn't change this being a bug but should be a relatively painless workaround.

**Comment by wojciechczerniak** [comment] 2019-03-13 10:32
Thanks @mewalig !

Using `MutationObserver` would be even better. Should be more stable than `setTimout` but depends on the browser support you're targeting (IE11+): https://jsfiddle.net/xfzqtw3p/1/ . Various frameworks also have events for tabs and modals that can be used to rerender Handsontable. 

I'm looking for a solution that we can build into the grid itself but it looks like it's a common problem with components that depend on container visibility to do the math. 
Hope we can find a reliable solution 🤞

**Comment by aleoyakas** [comment] 2021-08-20 09:35
Is there any update on this? I have the same issue when using tables in tabs, forcing a `render()` causes the page to jump up and down as the table is rendered, but going with toggling the display is causing the table not to show. 

I'll go with forcing the render at this point, but it'd be much nicer if we could set a property that causes HOT to render the table, even if wrapped in a `display: none` div

**Comment by AMBudnik** [comment] 2021-08-20 10:02
Hi @aleoyakas at the moment there are no further updates than what @wojciechczerniak wrote

**Comment by ludoviccyril** [comment] 2022-03-22 15:49
Any updates?

**Comment by AMBudnik** [comment] 2022-08-26 11:02
Simplified demo using v12.1.2 https://jsfiddle.net/kq35w9zm/1/

Result in Chrome 103 /macOS Monterey

![Screenshot 2022-08-26 at 13 04 48](https://user-images.githubusercontent.com/10757813/186889991-4bbf9e20-c0a7-4281-9ed1-5d2578158f62.png)

* missing headers (they appear when we click any cell)
* wrong column widths

**Comment by AMBudnik** [comment] 2022-12-14 12:57
Hi @primeO @ludoviccyril @aleoyakas @mewalig @Sowcott @rhwilburn @alisanguo  

I am happy to announce that the following issue is fixed with the release we published today.
Here you can read more about the changes in Handsontable v12.3.0 https://handsontable.com/docs/javascript-data-grid/release-notes/#_12-3-0

**Closed by AMBudnik** 2022-12-14 12:57 UTC
Labels: bug, Core: Alignment / height / width
