### ISSUE TITLE
Cannot sort HOT-in-HOT tables

### ISSUE THREAD

**Issue by vkapartzianis** [handsontable/handsontable#3746] opened 2016-09-06 12:44 UTC
Clicking on a column header of a HOT-in-HOT table, with `columnSorting` enabled, will close the pop-up table and return the value of the first cell. Is there any way to prevent this from happening?

In other words, is there any way to let the user sort a HOT-in-HOT table?

**Comment by AMBudnik** [comment] 2016-09-06 13:21
Thanks for sharing Vaggelis, 

Confirmed. When we want to sort the table sorting doesn't work and the table is closing itself:
demo: http://jsfiddle.net/3cahuwgd/

result:
![hot-in-hot](https://cloud.githubusercontent.com/assets/10757813/18274654/c36fcada-7443-11e6-8e23-154c201274bc.gif)

**Comment by AMBudnik** [comment] 2019-03-01 10:37
The issue is no longer replicable. @vkapartzianis  please update to newest version of Handsontable

**Closed by AMBudnik** 2019-03-01 10:37 UTC
Labels: Core: handsontable, Type: Bug
