### ISSUE TITLE
The selection doesn't work with merged cells with fixed overlays

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#4940] opened 2018-03-15 08:18 UTC
### Description

The selection behaves weird when both overlays (left and top) are enabled and the table has applied some merged cells.

### Steps to reproduce

1. Go to https://jsfiddle.net/huL2kfmn/;
2. Make the non-contiguous selection. Select cells from A2 to C3 and by keeping <kbd>CMD</kbd> key select C3 to F6;
3. In result, the border of the selection doesn't cover the whole selection, the background color is missing and the merged cell (F6) contains wrong selection CSS class. 

![kapture 2018-03-15 at 9 14 55](https://user-images.githubusercontent.com/571316/37451259-5e765952-2831-11e8-869f-2b40551db453.gif)

### Your environment
* Handsontable version: 0.38.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment] 2018-04-24 12:47
Still looks the same in v `2.0.0`

**Comment by budnix** [comment] 2019-09-18 09:20
This will be resolved within https://github.com/handsontable/handsontable/pull/6157.

**Comment by aninde** [comment] 2019-12-03 12:35
This bug will be fixed by new border drawing method by [SVG](https://github.com/handsontable/handsontable/pull/6157), thank you for that @warpech :)

https://jsfiddle.net/52wo63a1/ `7.2.2 v. with new SVG borders`
![Screenshot 2019-12-03 at 13 16 07](https://user-images.githubusercontent.com/30186818/70051573-9fb4dd00-15d1-11ea-95cb-382b388a6120.png)

Works good on `Chrome 78` , `Firefox 70 ` and `Safari 13` on Mac OS Catalina and `IE 11`, `Edge` and `Edge Dev` on Windows 10 even while scrolling. 
There is no additional margin at the moved selection and all selected cell have CSS class `highlight`. 
 
We should add tests for this case so that the error doesn't reoccur in the future.

**Comment by AMBudnik** [comment] 2020-09-02 09:35
When we update to v8.0.0 https://jsfiddle.net/AMBudnik/swc7on5b/ the issue is no longer replicable

![Zrzut ekranu 2020-09-2 o 11 35 11](https://user-images.githubusercontent.com/10757813/91965166-69e38700-ed10-11ea-91cb-5a94d120e452.png)

**Comment by warpech** [comment] 2020-09-02 13:17
IMO it still looks bad. It should look as in https://jsfiddle.net/bryau4g6/, which shows the same kind of selection but with fixed overlays turned off.

![image](https://user-images.githubusercontent.com/566463/91988252-585da780-ed2f-11ea-9cbd-565124b96c03.png)

**Comment by AMBudnik** [comment] 2020-09-02 13:51
I just wanted to provide more details on the changes that we've made in v8.0.0.

* issue no 1
> the border of the selection doesn't cover the whole selection,

This issue is covered by https://github.com/handsontable/handsontable/issues/6628

* Issue no 2 
> the background color is missing

fixed by v8.0.0. Background `A5:B6` and `E2:F2` is blue.

* Issue no 3
> the merged cell (F6) contains wrong selection CSS class.

This issue is covered by https://github.com/handsontable/handsontable/issues/4859

**Comment by warpech** [comment] 2020-09-02 14:10
Thanks, then it's all clear that the remaining work is tracked in other issues

**Closed by warpech** 2020-09-02 14:10 UTC
Labels: Guess: a day or more, Merge cells, Type: Bug
