### ISSUE TITLE
Unable to align row

### ISSUE THREAD

**Issue by footman9988** [handsontable/handsontable#10169] opened 2022-12-15 06:52 UTC
### Steps to reproduce

1.If you wrap a line in a cell,
2.Drag the scroll bar to the far right
3.Unable to align row,
Let me know if it doesn't come back
### Demo

https://jsfiddle.net/footman8899/fh7nqge4/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment] 2022-12-15 09:08
Hi @footman9988 

I am not able to reproduce your issue. Can you please modify your demo, so it's representing your problem?

**Comment by footman9988** [comment] 2022-12-15 10:43
use https://jsfiddle.net/footman8899/fh7nqge4/
1 Enter a character into cell A1 and wrap the line.(Enter multiple lines in A1)
2 .Drag the scroll bar to the far right.
3 You'll notice that the row hight has changed.


Could you please give me your email? I can send you a picture to illustrate the problem.

**Comment by adrianszymanski89** [comment] 2022-12-15 11:02
Hi @footman9988 

I followed your steps, but I still can't see the issue. You can contact us at support@handosntable.com, but you can also upload images here.

**Comment by footman9988** [comment] 2022-12-16 01:14
hi @adrianszymanski89
Is this address correct?    I have sent to this address  [support@handsontable.com](mailto:support@handsontable.com).Please reply to me if you receive this email

**Comment by adrianszymanski89** [comment] 2022-12-16 08:50
@footman9988 

Yes, I got your message. Let's continue there. I will close this issue.

**Closed by adrianszymanski89** 2022-12-16 08:50 UTC
Labels: Status: Answered
