### ISSUE TITLE
getData() issue

### ISSUE THREAD

**Issue by leandrosuper** [handsontable/handsontable#2789] opened 2015-09-04 19:25 UTC
When i left some columns empty the data is not send with the getData() method. Example: if i have a row with 10 coluns and fills only the second one, the first and the second one are in the getData() array, and the rest not. In the same case if i fill the last column and getData() all the columns, even the empty ones, come to the array. I think this i a bug, but i can be wrong. Thanks.

**Comment by krzysztofspilka** [comment] 2015-09-09 10:19
@leandrosuper please prepare a demo (JSFiddle or Codepen). We can't reproduce it.

**Comment by AMBudnik** [comment] 2015-10-15 12:18
I'm closing this issue cause of lack of recent activity or demo, but if you still face the same issue with newest version let us know.

**Closed by AMBudnik** 2015-10-15 12:18 UTC
Labels: Demo needed
