### ISSUE TITLE
pasting from clipboard - error in afterChange hook

### ISSUE THREAD

**Issue by andrastokes** [handsontable/handsontable#888] opened 2013-07-15 17:36 UTC
Hi,
I'm trying to apply Handsontable in a project of mine, and ran into a strange possible bug.

I'm usig a pre-defined data structure, with minSpareRows set to 1.
The user should be able to enter loads of data to th etable, and I need to do some pre-validation before I pass the data to the server.

Whenever I paste in data from the clipboard, the afterChange hook does not seem to run so my pre-validation fails.
When I simply type in stuff, everything works fine.

Furthermore, as soon as my vaidated data loads back from the server using .loadData(), my table gains differnet set of extra, unwanted rows depending on the situation:
1) If no data was pasted from clipboard, then a few extra empty rows get added to the end of the table which seem to be replicating everytime when I change something in the previously filled in cells.
2) If data was pasted from clipboard, the previous effect appears plus all my original data rows get doubled.

There are no functions or commands in th eafterchange hook that would tell handsontable to add any new rows anywhere.

What could cause this issue?

**Comment by AMBudnik** [comment] 2015-04-08 10:27
Issue closed in lack of further conversation for more than a year.

**Comment by mohithg** [comment] 2016-10-28 19:51
@AMBudnik I'm facing the same problem too. Can you re open this issue.

**Comment by AMBudnik** [comment] 2016-10-31 11:37
Since this issue is more than 3 years old can you share a demo and a step-by-step scenario how to replicate the issue in the newest version?

**Comment by mohithg** [comment] 2016-10-31 17:58
The replication steps are simple, type more than two rows of data in excel, copy them and when you paste the data into handsontable, the afterChange hook will be called only for first row (especially when the setting for paste is 'shift_down'.

**Comment by AMBudnik** [comment] 2016-11-04 09:25
Hi @mohithg 
I'm getting a 1 element array if I pasted a content inside a single cell and bigger array if I pasted few rows of data.

![log](https://cloud.githubusercontent.com/assets/10757813/20000677/010fd3a4-a279-11e6-8f1b-aeac1e1b6a06.png)

you expect something different or I am missing something?

**Comment by mohithg** [comment] 2016-11-04 17:28
If I paste more than one row, then I'm getting a bigger array but with extra 2 rows with empty data. Can you see if you get the same. Please try in paste mode 'shift_down'.

**Comment by AMBudnik** [comment] 2016-11-08 11:16
you're right @mohithg with `pasteMode: 'shift_down'` the values returned via `afterChange` look more complicated a shows more than we have in our grid.

Lets examine 3 examples

**1. Example (correct)** 
Add one cell at `(0, 0)`

![1v](https://cloud.githubusercontent.com/assets/10757813/20095713/e8353b2c-a5a6-11e6-9677-e13114b32866.gif)

result: one array with 4 changes
![1](https://cloud.githubusercontent.com/assets/10757813/20095609/752af9e6-a5a6-11e6-81c3-58fa8165ac45.png)

**2. Example (correct)**
Add two cells at `(0, 0)` and at `(1, 0)`

![2v](https://cloud.githubusercontent.com/assets/10757813/20096484/5c3c5dd6-a5aa-11e6-86f5-30bd39fa3c88.gif)
result: one array with 5 changes

**3. Example (incorrect)**
Add four cells (`0, 0` to `1, 1`) 

![3v](https://cloud.githubusercontent.com/assets/10757813/20096591/dc3061ae-a5aa-11e6-9e11-99d2f39a9bba.gif)

result: 2 arrays (5 changes and 7 changes)
![3](https://cloud.githubusercontent.com/assets/10757813/20096643/1ef8481c-a5ab-11e6-83e6-9dac873af2cb.png)

Where in first array:
* `Mercedes A 160` changes to `1`
* `Citroen C4 Coupe` changes to `34`
* `Audi A4 Avant` changes to Mercedes A 160
* no value changes to `Citroen C4 Coupe`
* no value changes to `Audi A4 Avant`

And the second array of changes:
* `2011` changes to `23`
* `2012` changes to `5`
* `2013` changes to `2011`
* no value changes to `2012`
* no value changes to `2013`
* no value changes to no value, coords: `(5, 1)` **BUG**
* no value changes to no value, coords: `(6, 1)` **BUG**

**Error description:**
There is no cells with following coordinates `5, 1` and `6, 1` as we only have 5 rows.
DOM structure as shows only 5 rows:
![htcore](https://cloud.githubusercontent.com/assets/10757813/20097058/de54c8ec-a5ac-11e6-843d-f5e676dd9272.png)
`instance.countRows()` also shows only 5 rows.

**Comment by AMBudnik** [comment] 2018-01-19 12:48
Related https://github.com/handsontable/handsontable/issues/4554

**Comment by swistach** [comment] 2018-10-01 11:21
The problem is inside the `populateFromArray` method.

**Comment by AMBudnik** [comment] 2020-09-11 11:38
The v8.0.0 works the same https://jsfiddle.net/AMBudnik/evxk2bpm/1/ and as the source of changes is `spliceCol` we get as many calls as many columns where altered. That's why we get 1 call if we change cells from A1:A4 (4 cells) and 2 calls if we change A1:B1.

**Comment by AMBudnik** [comment] 2021-11-18 08:04
I'm glad to see this issue fix in the latest version!

@andrastokes @setthase @mohithg thank you for your feedback

If you would like to read more about the newest release here’s everything listed and described https://github.com/handsontable/handsontable/issues/8949
And here is the migration guide from v10 to v11 https://handsontable.com/docs/migration-from-10.0-to-11.0/

**Closed by AMBudnik** 2021-11-18 08:04 UTC
Labels: Type: Bug, Status: Released, Core: callbacks, Breaking change
