### ISSUE TITLE
Core-JS dependency

### ISSUE THREAD

**Issue by oceanapplications** [handsontable/handsontable#5922] opened 2019-03-26 22:01 UTC
### Description
Core-js 3.0 was recently released and does not fulfill the requirements.  Using core-js version 2.6.5 fixes the errors for multiple missing files such as: 

`Can't resolve 'core-js/modules/es7.object.get-own-property-descriptors'`

**Comment by wojciechczerniak** [comment] 2019-03-27 08:03
Thanks for reporting the issue @oceanapplications . You can follow the progress here #5888 and we already have a PR with the fix we're testing:  #5908. Should be released with `v7.0.1` next week.

Duplicate of #5888

**Closed by wojciechczerniak** 2019-03-27 08:03 UTC
