### ISSUE TITLE
Sorting indicator moves incorrectly when adding a column

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6397] opened 2019-10-28 16:28 UTC
### Description
Sorting indicator (arrow) moves incorrectly to the left when adding a column to the left. 
The error does not occur when adding the right column.

### Steps to reproduce

1. Open demo https://jsfiddle.net/aninde/gLzt0c2x/
2. Sort second column. 
3. Insert to the left of sorted column

### Actual result
Sorting indicator (arrow) moves to the new added header and no longer exist on previous sorted column. 
![Screen Recording 2019-10-28 at 17 16 06 2019-10-28 17_24_22](https://user-images.githubusercontent.com/30186818/67696798-cb77ee00-f9a7-11e9-97fb-2067b46f89b7.gif)

### Expected result
Sorting indicator should not move. It should stay where it is used, like when adding column on the right site. 

### Demo

v. `7.2.2` https://jsfiddle.net/aninde/gLzt0c2x/

### Your environment
* Handsontable version:  at least 6+, before, sorting was without an indicator. Can't be checked.
* Browser Name and version: any
* Operating System: any

**Comment by swistach** [comment] 2019-10-29 10:16
`multiColumnSorting` has the same bug.
Moreover, you can reproduce this issue by removing columns.

**Comment by wojciechczerniak** [comment] 2019-12-28 09:30
@aninde Please re-check this issue with `v8.0.0-beta`

**Comment by AMBudnik** [comment] 2019-12-30 07:56
it works the same on my Catalina while applying `8.0.0`'s beta https://jsfiddle.net/tybrnL50/

**Comment by aninde** [comment] 2020-01-02 11:13
@AMBudnik is right. Sadly this bug occurs also in `v8.0.0-beta`. It is possible to call it by removing the sorted column, like @swistach wrote.
https://jsfiddle.net/ymdq85rn/

`multiColumnSorting` / Firefox 71 / Catalina 10.15
![6397-8 0 0-ff](https://user-images.githubusercontent.com/30186818/71664394-196af280-2d59-11ea-8c42-34b0e4c195bc.gif)

**Comment by AMBudnik** [comment] 2020-06-16 10:12
**Remains the same** in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/Lxbrpt53/

**Comment by wszymanski** [comment] 2020-08-06 09:35
Related to the fact that a newly created row's index replaces the previous physical index. A physical index isn't really a unique value.

**Comment by AMBudnik** [comment] 2020-08-11 10:08
Demo updated to v8.0.0 https://jsfiddle.net/gb126Lre/ (works the same)

**Comment by aninde** [comment] 2020-11-03 13:47
This issue will be fixed by the version upcoming  v8.2.0 on all supported browsers except Internet Explorer 11 on Windows 10.

**Demo** https://jsfiddle.net/aninde/09edasc2/

On IE, the newly added column on the left has an additional invalid indicator. When you add a column to the right of a sorted column, the indicator is not added. Sorting pointer renders the same regardless of the Handsontable version

order of gifs:
1. v8.2.0 
2. v8.0.0 
3. v7.4.2
![8 2 0](https://user-images.githubusercontent.com/30186818/97991780-28d82380-1de2-11eb-8455-d6d7974ff60c.gif) ![8 0 0](https://user-images.githubusercontent.com/30186818/97991795-2d9cd780-1de2-11eb-8781-c44a51befecb.gif) ![7 4 2](https://user-images.githubusercontent.com/30186818/97991816-34c3e580-1de2-11eb-9e2a-740078ec7349.gif)

**Comment by aninde** [comment] 2020-11-06 09:52
Today's version of 8.2.0  works beautifully on IE 11/ Windows 10 and other supported browsers. @jansiegel well done!

This issue will be fixed by the upcoming v8.2.0.
**Demo** https://jsfiddle.net/aninde/o5ujrpnb/

**Comment by AMBudnik** [comment] 2020-11-16 09:46
The issue is closed as solved for v 8.2.0

**Closed by AMBudnik** 2020-11-16 09:46 UTC
Labels: Column sorting, Multi-column sorting, Status: Released, Type: Bug
