### ISSUE TITLE
Comments reposition with fixed rows and columns

### ISSUE THREAD

**Issue by MJHath** [handsontable/handsontable#2608] opened 2015-07-03 10:44 UTC
I have a table, with 'fixedColumnsLeft: 2'

I am also trying to add a comment to column 0 (the left most column)
At first glance, it appears that the 'fixedColumnsLeft' setting modifies the z-Index, of those columns, to a higher number than the rest of the table. The problem is that it looks to be a higher z-Index than the comments div

Therefore, the comment appears behind the fixed columns (see screenshot)
![comment](https://cloud.githubusercontent.com/assets/13164647/8497663/e5a26ac0-2176-11e5-9d3c-789be84c5465.png)
The other problem, as also seen in the screenshot, is that the comment div appears too small for the text and appears with scrollbars, making it look a bit messy

I don't know whether this is a consequence of the way I am bring the comments into the table, as it is done dynamically using a JSON input (data.comments) from a database

```
cells: function (row, col, prop) {
    var cellProperties = {}
    if (col <= 1) cellProperties.readOnly = true; 
    if (col > 0) cellProperties.className = "htCenter";

    TeamNumber = $('#handsontable).handsontable('getDataAtCell', row, 1);
    cellProperties.comment = data['comments'][TeamNumber]['general'];

     return cellProperties;
  }
```

I have found that by modifying the z-Index in the generated div class="htComments" to 999, this does resolve the overlay issue, although not the fact that the comments box appears too small

As a minimum, could the code be modified such that the default z-Index for the comments is higher than that set for the fixedLeftColumns value?
Any suggestions on why the comment box is not sizing properly?

Many thanks

**Comment by AMBudnik** [comment] 2015-07-03 15:29
Thank you for reporting.
You are right the comment is cut.
![zrzut ekranu 2015-07-03 o 16 29 08](https://cloud.githubusercontent.com/assets/10757813/8501552/e9a28b52-21a6-11e5-9b1c-e4549e16e60d.png)
([demo code](https://jsfiddle.net/avqtonz6/))
please stay tuned to this issue for further information

**Comment by AMBudnik** [comment] 2016-03-03 10:52
Confirmed with 0.23.0

**Comment by AMBudnik** [comment] 2016-09-09 11:50
Still present, updated demo to 0.27.0: https://jsfiddle.net/81zvnhc9/

**Comment by AMBudnik** [comment] 2016-10-07 08:29
Here's updated demo for rows and columns: https://jsfiddle.net/uxxjk4hd/1/

**Comment by jansiegel** [comment] 2016-11-07 11:20
Should no longer be an issue after releasing `0.29.0`.

**Comment by AMBudnik** [comment] 2016-11-08 14:18
Hi @MJHath 
We've made some huge steps to fix comments. Please take a minute to check it and confirm that they're working properly.

**Comment by AMBudnik** [comment] 2016-11-14 08:12
It's nearly a week since we've made the change so I guess we can close this issue. However if you still face any difficulties @MJHath please do not hesitate to leave a comment.

**Closed by AMBudnik** 2016-11-14 08:12 UTC
Labels: Plugin: comments, Priority: normal, Status: Released, Tested, Type: Bug

**Comment by gaoyuan121** [comment] 2017-07-07 03:32
Hi here,
I got the same problem when using fixColumnsLeft and comment, the comments' position moved with horizontal scroll. Could you please help me out?  Same usage as this example : https://jsfiddle.net/81zvnhc9/

**Comment by AMBudnik** [comment] 2017-07-11 08:53
Thank you @gaoyuan121 
I have created a new issue as this one already has a milestone attached: https://github.com/handsontable/handsontable/issues/4389
