### ISSUE TITLE
handsontableInputHolder div created outside of wtHolder div

### ISSUE THREAD

**Issue by jwboardman** [handsontable/handsontable#1444] opened 2014-04-24 03:38 UTC
I'm using handsontable inside of jquery dialogs. When I double-clicked on a cell to edit it, the editor div appeared below the handsontable. A little debugging with Chrome showed that the handsontableInputHolder div was below the wtHolder div.

I changed line 5017 of jquery.handsontable.full.js from this:
this.instance.rootElement[0].appendChild(this.TEXTAREA_PARENT);
to this:
this.instance.rootElement[0].firstChild.appendChild(this.TEXTAREA_PARENT);
and now the editor div appears in the correct place. I re-tested with Chrome, IE10, and Firefox.

Sorry I don't have time to properly put the fix in the codebase and prepare a test case. Lots of deadlines and all that.

**Comment by AMBudnik** [comment] 2015-03-23 14:57
Please prepare a [JSFiddle demo](http://jsfiddle.net/api/post/library/pure/) and browser information. I couldn't reproduce this issue on Chrome 41.0.2272.89 (64-bit) with latest HOT version (0.13.1)

**Comment by AMBudnik** [comment] 2015-04-20 12:34
Issue had to be closed in lack of needed demo.

**Closed by AMBudnik** 2015-04-20 12:34 UTC
Labels: Demo needed

**Comment by sundagy** [comment] 2018-03-20 11:28
Here the worked example with this bug:
https://jsfiddle.net/4a8wa7pf/1/
Just scroll and try to edit any cell, the edit box were apeared in wrong place.
This is tupical situation when using Bootstrap Modal.

In my fork I am tried fix it, but not sure I am done right:
https://github.com/sundagy/handsontable/commit/f2c857bd857b4ff785f2267922bb2094f6c84a5f#diff-98f90d21bf56b1d907718a5459541bc1
Although it works.

Browser: latest Chrome 64.0.3282.186

**Comment by AMBudnik** [comment] 2018-03-21 12:36
Sorry, but I cannot replicate the issue. I am using Chrome on Windows 10. CAn you provide a video and your OS/Browser settings?

**Comment by sundagy** [comment] 2018-03-22 12:54
Here video:
https://drive.google.com/file/d/1v4MsMgS9skoWe6H_IPN4FH17rLGIGZ7r/view

Windows 10 Pro x64

Последняя версия Google Chrome уже установлена
Версия 65.0.3325.181 (Официальная сборка), (64 бит)

**Comment by AMBudnik** [comment] 2018-03-22 13:44
OK. Now I see what I have been missing (the scrolling between click and edit)
