### ISSUE TITLE
AutoFill plugin doesn't support multiple instances

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#3257] opened 2016-02-19 14:50 UTC
After updating documentation about new functionality for AutoFill plugin (`autoInsertRow`) I saw that there is a bug which occurs when 2 instances of Handsontable are using this plugin at the same time.

Second demo at the page https://docs.handsontable.com/0.23.0/demo-drag-down.html overwrites settings of the first Handsontable instance.

This plugin is still waiting to be refactored, so this is a good opportunity to do it now. After rewriting to a new architecture bug should automatically disappear.

**Comment by zoladkow** [comment] 2016-08-23 12:21
Hi,

We are currently facing this in our project. Interestingly I cannot reproduce it currently on pure Handsontable using demo fiddles. 
For us the problem is happening because we are using ngHandsontable where something else is happening: setting fillHandle on second hot instance( fillHandle: false) resets the fillHandle state of initial instance.

http://jsbin.com/texosupuqi/1/edit?html,js,output

**Comment by ponticello** [comment] 2016-09-15 19:28
I'm looking for a workaround. I hoped that updating the settings would help, but this unfortunately doesn't work. 
`$inflationRatesTable.handsontable('getInstance').updateSettings({
		      fillHandle: {
				  autoInsertRow: false,
				  direction: true // 'vertical' or 'horizontal'
				}
		      });`
Any other ideas?

**Comment by nidu** [comment] 2016-11-17 10:26
Not only `autoInsertRow` doesnt work for multiple instances but `fillHandle` as well. For example see [this](http://jsfiddle.net/zkw3evz5/).

**Comment by AMBudnik** [comment] 2017-01-11 12:29
Hi @zoladkow  @ponticello @nidu 
We have made some changes and it should work as expected in 0.30.0.
Please test it in your projects.

**Comment by zoladkow** [comment] 2017-01-11 16:14
Hi,

Seems fine at first try: http://jsbin.com/sapazupoma/1/edit?html,js,output

Will also check with actual project some time later...

In any case - thanks!

**Comment by AMBudnik** [comment] 2017-01-12 08:56
Thanks for an investigation @zoladkow 
I've made a demo http://jsfiddle.net/5q5L0etp/ with the Vanilla version which works as expected. 
ng is running on 0.28.4 as far as I know.

However if there still an issue for ng, we can close this issue and create one on the ng board.

**Closed by AMBudnik** 2017-01-12 08:56 UTC
Labels: Breaking change, Guess: a day or more, Plugin: auto fill, Priority: high, Status: Released, Tested, Type: Bug

**Comment by zoladkow** [comment] 2017-03-06 07:34
Hi, no such problem with 0.31.0.
Thanks for your work!

**Comment by AMBudnik** [comment] 2017-03-06 14:25
Great!

Thank you for your update @zoladkow 
I'm glad it works.
