### ISSUE TITLE
Freezing columns do not work with nestedHeaders

### ISSUE THREAD

**Issue by hutiantian04** [handsontable/handsontable#6001] opened 2019-05-08 12:48 UTC
### Description

Cannot read property 'sourceColumnToVisibleRowHeadedColumn' of null
### Steps to reproduce

1.rowHeaders: false,
2.manualColumnFreeze: true,
contextMenu: true,
3.
![fixxloumn](https://user-images.githubusercontent.com/39802580/57376332-4cf97b00-71d2-11e9-82e2-61a9961e20cc.png)
![fixerror](https://user-images.githubusercontent.com/39802580/57376391-73b7b180-71d2-11e9-8880-917950de4e51.png)

### Demo

http://jsrun.net/mSXKp/edit

### Your environment
* Handsontable version:7.0.2
* Browser Name and version:Google Chrome version: 73.0.3683.86
* Operating System:win10

**Comment by AMBudnik** [comment] 2019-05-14 12:42
It looks like it is connected to `nestedHeaders`

Simplified example https://jsfiddle.net/handsoncode/ytkm2p8d/ even when we have only one row of them https://jsfiddle.net/handsoncode/qoLnfz07/

It doesn't seem to work well in any of the previous versions.

**Comment by AMBudnik** [comment] 2019-09-25 09:01
The issue still looks the same with the latest build (24/09) of `8.0.0-rc1`
Demo https://jsfiddle.net/gx5fq7nh/

I've tested it on Chrome 77 on macOS Mojave. 

**Scenario**
1) Freeze column `B`
2) Open editor of `A3`

**Issues**

1. We get the console error
![Zrzut ekranu 2019-09-25 o 10 51 54](https://user-images.githubusercontent.com/10757813/65585284-831d7880-df82-11e9-9bdf-a412756245ed.png)

2. Editor is misaligned and wrong value appears in the cell
![Zrzut ekranu 2019-09-25 o 10 53 35](https://user-images.githubusercontent.com/10757813/65585457-c8da4100-df82-11e9-8c8f-25f9ad8c6604.png)
I clicked `A3` but `A6` has been opened (editor) which get a value of `B6`.

3. We're not able to exit selection
![Zrzut ekranu 2019-09-25 o 10 49 13](https://user-images.githubusercontent.com/10757813/65585327-96c8df00-df82-11e9-9c4b-d242c6998ade.png)

**Comment by AMBudnik** [comment] 2019-09-25 10:13
Please do not close the bug report. It hasn't been fixed yet.

**Comment by AMBudnik** [comment] 2019-12-30 09:14
I guess that it's even worse with the newer beta https://jsfiddle.net/kus7z5ca/ as now we're not even able to select a cell and when we scroll `B-` data is not frozen in a column even if it moved to the `0` index. 

But that's not all. If you move the scrollbar a bit down the `nestedHeaders` are placed incorrectly and some rows aren't rendered.

![issue](https://user-images.githubusercontent.com/10757813/71575333-d99fd300-2aec-11ea-9adf-35ae0a4249aa.gif)

**Comment by AMBudnik** [comment] 2020-06-16 09:24
**Remains broken** in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/hz8sk6yx/

**Comment by miracleDD** [comment] 2021-04-15 08:53
Is this bug fixed now ?

**Comment by AMBudnik** [comment] 2021-04-15 08:58
Hi @miracleDD 

This issue hasn't been scheduled yet. I will update you as soon as we fix it.

**Comment by andraz-podobnik** [comment] 2023-01-03 06:38
Hi there,
is it known when this bug will be fixed?

**Comment by adrianszymanski89** [comment] 2023-01-03 08:37
Hi @andraz-podobnik 

This issue isn't on our roadmap yet, and we don't have an estimation for it.

**Comment by SamJonesUK** [comment] 2023-07-19 14:49
@adrianszymanski89 is this on the roadmap yet?

**Comment by adrianszymanski89** [comment] 2023-07-20 07:42
Hi @SamJonesUK 

Unfortunately, it isn't there yet. Currently, we are focusing on an A11Y project. I'll update this issue once it gets on a roadmap.

**Comment by adrianszymanski89** [comment] 2024-03-13 08:52
Hi @SamJonesUK  @andraz-podobnik 

I just wanted to let you know that this issue is fixed now. The fix is available with Handsontable 14.2.

**Closed** 2024-04-03 09:57 UTC
Labels: bug, Nested headers, Fixing / Freezing, Reported

**Comment by amadoridamiano** [comment] 2026-03-17 08:57
Hi team,
We're building a data entry grid using Handsontable v17 with the following plugin combination:                                                                                
   
  - nestedHeaders (two-level headers: spreadsheet-style A/B/C + field names)                                                                                                    
  - hiddenColumns (hiding the ID column)                    
  - ManualColumnFreeze                                                                                                                                                          
                                                                                                                                                                                
  When freezing a column via the context menu, the data visually swaps between columns — the values shift to adjacent columns incorrectly. This is reproducible and also happens on the official Handsontable demo page.                                                                                                                                      
                                                                                                                                                                                
  We had to disable ManualColumnFreeze entirely and fall back to the static fixedColumnsStart option as a workaround.                                                           
   
  Questions:                                                                                                                                                                    
  1. Is this a known regression or is it the same root cause as the original #6001?
  2. Is there a timeline or roadmap for fixing ManualColumnFreeze with nestedHeaders + hiddenColumns?                                                                           
  3. Are there any recommended workarounds beyond fixedColumnsStart?                                 
                                                                                                                                                                                
  Environment:                                                                                                                                                                  
  - Handsontable v17                                                                                                                                                            
  - React wrapper (@handsontable/react-wrapper)                                                                                                                                 
  - Plugins active: nestedHeaders, hiddenColumns, hiddenRows, multiColumnSorting, filters, formulas (HyperFormula), copyPaste, contextMenu
                                                                                                                                                                                
  Thanks for your time.
