### ISSUE TITLE
Sheet doesn't show all data after multiple calls to loadData() while trim rows plugin is enabled

### ISSUE THREAD

**Issue by arrdev** [handsontable/handsontable#4383] opened 2017-07-07 14:51 UTC
### Description
Due to large amount of data we need to display in our sheet we load it in chunks. For each chunk we add data from current chunk to everything loaded before:
currentData = currentData.concat(newChunk);
sheet.loadData(currentData);
sheet.render();

The problem is that sometimes there is less (significantly at times) records shown to the user than number of records in data array. For some reason some rows are not shown. We've found similar issue (https://github.com/handsontable/handsontable/issues/3799) and it was related to usage of trim rows plugin. We also use that plugin.

Temporary disabling that plugin before calling loadData() helps, but we would like to find more reliable solution to the problem. Besides, the original issue is already closed.

### Steps to reproduce
1. Create a handsontable instance and initiate it with some data and trim rows plugin enabled
2. After some time add more data to the array and call loadData() followed by render(). Do it multiple times
3. There is less records shown in the sheet than there are records in source array

### Your environment
* Handsontable version: latest pro
* Browser Name and version: Google Chrome 58.0.3029.110 (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2017-07-10 10:47
Hi @arrdev 

https://github.com/handsontable/handsontable/issues/3799 has been closed as we have created a fix for the issue in version 0.31.2. As you are using the latest version (based on 0.32.0) and the issue is back we need to investigate it more.
Can you check if by switching to 0.32.2 / PRO 1.10.2 the issue is gone.

**Comment by AMBudnik** [comment] 2017-08-17 11:58
Hi @arrdev 

Can you guide me on how to replicate the issue?

I have tried with with demo http://jsfiddle.net/1xhnd4fr/1/ but failed to get any odd behavior.

**Comment by AMBudnik** [comment] 2017-08-24 08:50
I am closing the issue as there is no reply for a week. If you still experience any issues with Handsontable please let me know.

**Closed by AMBudnik** 2017-08-24 08:50 UTC
Labels: Type: Demo needed
