### ISSUE TITLE
Dropdown red validation error when source value contains blank space at end or begin of the string

### ISSUE THREAD

**Issue by LoveraSantiago** [handsontable/handsontable#4159] opened 2017-03-28 17:15 UTC
### Description

When using a type column dropdown if source contains values with blank space at beggining or at the end of string a red validation appears on cell when that value is selected. 

### Steps to reproduce

1. The last jsfidle on [OnChange Event Issue #973](url). On third column select the PM option.  Wich in code is line 38. 
2.  If you remove the blank space at line 38 red validation doesnt appear anymore.

I know that a trim can resolve this. But it took some time for me to find out the reason. 
If this should not be considered a mistake, sorry to have opened an unnecessary issue.

Handsontable its a great tool!

### Demo

-no demo

### Your environment
* Handsontable version: -
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment] 2017-04-03 09:31
Thanks for sharing @LoveraSantiago 

I have replicated the issue here http://jsfiddle.net/handsoncode/dxckfj0x/ 

My dropdown source is `source: [' yellow', ' red ', 'orange ', 'green', 'blue', 'gray', 'black', 'white']`
(`yellow` has a space before word, `orange` has a space after word and `red` has them both).

As mentioned when we pick `yellow`, `red` or `orange` option does not pass validation.

**Comment by AMBudnik** [comment] 2018-08-17 11:14
Currently, there is an option to[ trim whitespaces](https://docs.handsontable.com/pro/5.0.1/Options.html#trimWhitespace), by default, it is set to trim them (true), but if you change the option to `false` the issue is gone. I guess that we can close this subject

**Closed by AMBudnik** 2018-08-17 11:14 UTC
Labels: Cell type: autocomplete / dropdown / handsontable, Type: Bug
