### ISSUE TITLE
сolumnSummary does not work with columnSorting  and context menu

### ISSUE THREAD

**Issue by FominS** [handsontable/handsontable#3924] opened 2016-12-01 20:25 UTC
Hello!

I have some problems with using columnSorting and columnSummary:
1. If I use columnSummary with columnSorting, then the dynamic change data in a table does not change, and the error appears in the console: Uncaught TypeError: Cannot read property '2' of null. Changes appear in the table only after editing of the cell
2. If I disabled columnSummary, dynamic change of the data is not problem. With disabled columnSorting - data is not dynamically updated
3. When handsontable to use the context menu and add a new row last row superimposed on the summary column. When you delete the row value summary column does not change
[example](https://jsfiddle.net/yg2cu9zh/7/)

There are ways to solve my problems?

**Comment by AMBudnik** [comment] 2016-12-02 09:25
Hi @FominS 

1. **If I use columnSummary with columnSorting, then the dynamic change data in a table does not change, and the error appears in the console: Uncaught TypeError: Cannot read property '2' of null. Changes appear in the table only after editing of the cell**
I think that this issue can be related https://github.com/handsontable/handsontable/issues/3658

2. **If I disabled columnSummary, dynamic change of the data is not problem. With disabled columnSorting - data is not dynamically updated**
Here I would need a demo and scenario on how to replicate the issue.

3. **When handsontable to use the context menu and add a new row last row superimposed on the summary column. When you delete the row value summary column does not change
example**
There is definitely something going wrong. I will investigate this issue further. Here's a working example for this task: http://jsfiddle.net/vaes0fbk/**

**Comment by FominS** [comment] 2016-12-02 21:11
Hi @AMBudnik !

> Here I would need a demo and scenario on how to replicate the issue.

In my project, I can't use the **hot.loadData(data)** and **hot.render()** always.
So sometimes I just need to change the datasource array.

[demo](http://jsfiddle.net/94ezr9f4/)

On demo the first and second examples of render data without any problem, but the third-with columnSorting:false does not render the data. For a fourth example not render, not help even hot.render() and arise an error in console.
Do I need to use **hot.render()** always, if first and second example work without **hot.render()**?

**Comment by AMBudnik** [comment] 2016-12-09 11:19
Hi @FominS 
Of course you do not need to rerender the table if you only need to load new data and the data is visible in the table. It is the last step to rerender the view and most of processes in Handsontable is calling render() internally.

**Comment by aninde** [comment] 2019-09-29 08:00
The main issue described here wrong calculation in `columnSummary` after adding a row with context menu - will be fixed in `8.0.0-rc1`

Minimalistic demo v. `8.0.0-rc1` https://jsfiddle.net/aninde/rke47Lzd/
![3924 2019-09-29 09_59_21](https://user-images.githubusercontent.com/30186818/65828863-de5fab80-e29f-11e9-9a69-2a15a917d2fc.gif)

**Comment by aninde** [comment] 2019-09-30 12:01
However, swapping the [demo](https://github.com/handsontable/handsontable/issues/3924#issuecomment-264563682) version to the latest `8.0.0-rc1` causes a console error that did not appear in version `7.1.1`. A bug is reported here #6300

**Comment by AMBudnik** [comment] 2019-10-10 05:41
Please do not close the issue. We'll close them after pushing the official release.

**Comment by AMBudnik** [comment] 2019-11-15 09:43
Hey @FominS 

have you already had time to check the latest version which should fix this issue?
```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```
`npm i handsontable@beta`

**Comment by AMBudnik** [comment] 2020-04-06 06:52
Here's another case solved in 8.0.0-beta1
![Zrzut ekranu 2020-04-6 o 08 51 20](https://user-images.githubusercontent.com/10757813/78530389-d7cc6680-77e3-11ea-9ef0-55009c18ec7f.png)

https://jsfiddle.net/AMBudnik/r1nq3hs9/

![Zrzut ekranu 2020-04-6 o 08 51 02](https://user-images.githubusercontent.com/10757813/78530380-d438df80-77e3-11ea-9d28-ad18609aea80.png)

Version 7.4.2 - broken (C5 is duplicated from `D5`)
https://jsfiddle.net/AMBudnik/b9vyeLrz/

**Comment by aninde** [comment] 2020-08-06 13:18
The updated demo with `v8.0.0` still works well. https://jsfiddle.net/aninde/xjnzdt9g/

@AMBudnik case https://github.com/handsontable/handsontable/issues/3924#issuecomment-609599138 also works well https://jsfiddle.net/aninde/pfa2mty6/.

Closing as solved by v8.

**Comment by aninde** [comment] 2020-08-06 13:19
The updated demo with `v8.0.0` still works well. https://jsfiddle.net/aninde/xjnzdt9g/

@AMBudnik case https://github.com/handsontable/handsontable/issues/3924#issuecomment-609599138 also works well https://jsfiddle.net/aninde/pfa2mty6/.

Closing as solved by v8.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases

**Closed by aninde** 2020-08-06 13:18 UTC
Labels: Column sorting, Status: Released, Summary calculations, Type: Bug

**Comment by AMBudnik** [comment] 2020-08-07 08:38
@FominS I hope that you're still using Handsontable in your project. If so please update and let me know if the issue is solved for you as well.
