### ISSUE TITLE
checkbox wrong alignement

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#2985] opened 2015-11-16 11:58 UTC
hello,
a column with a checkbox gives a wrong alignment with row number
![misalign](https://cloud.githubusercontent.com/assets/11042160/11181311/57d95414-8c61-11e5-809d-45072e05e572.png)

http://jsfiddle.net/jeanmarc/bemLpv22/

regards
jm

**Comment by AMBudnik** [comment] 2015-11-16 12:43
Hi @jeanmarc78 which OS/Browser are you using?
I tried it with OSX (Chrome, Firefox) and Windows 7(Chrome, IE) and couldn't reproduce it.

**Comment by jeanmarc78** [comment] 2015-11-16 13:28
sorry it's with firefox 42 and windows 7.
it works with chrome.
regards
jm

**Comment by AMBudnik** [comment] 2015-11-16 14:18
Confirmed with Firefox 42 on Windows (OSX not effected).

**Comment by AMBudnik** [comment] 2016-03-18 11:15
Couldn't reproduce with v0.24.1 on Window8 - FF 45
Could you check this one @jeanmarc78?

Thanks in advance!

**Comment by jeanmarc78** [comment] 2016-03-21 16:25
hello,
yes it works , but i don't know if it's a browser version or handsontable version.

regards
jean marc

**Comment by AMBudnik** [comment] 2016-03-22 08:33
I couldn't reproduce this issue in any browser. I'm closing it.

**Closed by AMBudnik** 2016-03-22 08:33 UTC
Labels: Answered
