### ISSUE TITLE
Overloaded pluginHookBucket because of updateSettings or loadData

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#5727] opened 2019-01-18 16:28 UTC
### Description
When an instance of Handsontable is alive for a long period of time and to react with rest of the application, developer use "updateSettings()" - then Handsontable's response noticeably slows down.
If it's a complex configuration, even after a few `updateSettings` calls could be a reason of low performance.

### Steps to reproduce

1. Go to the demo.
2. Wait for a few minutes (try to reach 5/6k by callbacks counter).
3. Try to select cells.

### Demo
https://jsfiddle.net/znvx5hcg/

### Your environment
* Handsontable version: any
* Browser Name and version: any
* Operating System: any

**Comment by wojciechczerniak** [comment] 2019-02-25 12:16
`updateSettings` calls `loadData` where `dataMap` is destroyed and recreated:

https://github.com/handsontable/handsontable/blob/65dc03147e411df27e6c2699b93fdc7ade9bad67/src/core.js#L1446-L1449

`dataMap` adds hook `skipLengthCache`:

https://github.com/handsontable/handsontable/blob/c2ba2dc02e3eb883a58f976ef5944fa629dc981d/src/dataMap.js#L47

but never destroys it:

https://github.com/handsontable/handsontable/blob/c2ba2dc02e3eb883a58f976ef5944fa629dc981d/src/dataMap.js#L851-L861


Details from #5815

**Comment by wow-222** [comment] 2019-05-27 07:39
I found this memory leak problem in IE. Is it solved now?

**Comment by AMBudnik** [comment] 2019-05-27 07:45
@wow-222 it is scheduled for this milestone. We'll do our best to fix it

**Comment by aninde** [comment] 2019-09-17 12:23
A new `index mapper` at `8.0.0rc` version very gently improves performance during the above restore.  In my opinion, the new `index mapper`  is not a solution to the problem described here.

In the new version, the `skipLengthCache` was removed, however, this has not significantly improved performance.
@wojciechczerniak  @wszymanski what is your opinion on this subject?

**Context** 
In the version for original 6.0.0 tests, performance dropped after reaching around 5500 by callbacks counter.

**Result with new  index mapper `8.0.0rc1` version**
In the new version 8.0.0. a similar level of performance degradation occurs with a higher result - around 6,500 counter. With higher results of counter- above 8000 performance is at a similar level on both versions.

Fast performance - low counter. ver. 8.0.0rc1.
![chrome-fast-1300-8 0 0](https://user-images.githubusercontent.com/30186818/65041179-6a93d980-d956-11e9-8ce8-f1bf912f69e8.gif)

Slower performance after few minutes ver. 8.0.0rc1.
![chrome-8 0 0 rc- slow - 8400](https://user-images.githubusercontent.com/30186818/65041187-6ebff700-d956-11e9-8bea-6c09ded727d2.gif)

**Demo:**
version 8.0.0rc https://jsfiddle.net/aninde/fayngmkz/
same behavior at v. 7.1.1. like in original demo

**Environment**
Handsontable version:8.0.0.rc
Browser Name and version: Google Chrome version 76.0.3809.100 and Microsoft Edge Dev Version 78.0.262.0 (same results)
Operating System: macOS Mojave 10.14.6

**Comment by wszymanski** [comment] 2019-09-18 07:28
I agree with you @aninde. Even if this is faster, it seems that still there is a problem. Anyway, thanks for deep investigation!

**Comment by wojciechczerniak** [comment] 2019-09-18 07:46
Looks like `skipLengthCache` wasn't the only leak we have.

To check all hooks in the bucket I've made this: https://jsfiddle.net/1v5boxep/

Here's the list of hooks which number is growing with each `updateSettings`:
afterContextMenuDefaultOptions
afterOnCellCornerMouseDown
afterOnCellCornerDblClick
afterOnCellMouseDown
afterOnCellMouseUp
afterSelectionEnd
beforeKeyDown
beforeOnCellMouseOver

Which parts of Handsontable could be responsible? Rings any bells @budnix @jansiegel @wszymanski @swistach @pnowak ? Our memory leak test somehow didn't catched this

**Comment by budnix** [comment] 2019-09-18 08:07
@wojciechczerniak This line probably https://github.com/handsontable/handsontable/blob/master/src/pluginHooks.js#L1990 which causes that bucket contains all removed callback which shouldn't.

**Comment by wojciechczerniak** [comment] 2019-09-18 10:20
Ok. If I understood our discussion correctly this is by design. It's not a common use case to run `updateSettings` every second as we did in the examples above. 

But we can do better and improve memory usage. For example by using https://github.com/handsontable/handsontable/blob/master/src/utils/dataStructures/linkedList.js data structure as our hooks bucket storage instead of plain arrays. And definitely should check it, but with special attention to overall hooks performance (`addHook`, `removeHook` and `runHooks`).

Thanks all!

**Comment by AMBudnik** [comment] 2022-11-24 12:45
Inform [forum](https://forum.handsontable.com/t/gh-5727-contextmenu-callback-the-runhooks-method-cannot-be-called/4134/12)

**Comment by AMBudnik** [comment] 2023-01-16 14:40
@aninde yup, the `length` of the `afterContextMenuDefaultOptions` in the Piotr's demo stays at `1` in the latest version so it seems that the issue is solved.

**Comment by aninde** [comment] 2023-01-17 08:02
Well, I guess we can close this and this double https://github.com/handsontable/dev-handsontable/issues/780.

**Comment by AMBudnik** [comment] 2023-01-17 08:05
Closing as solved.

**Closed by AMBudnik** 2023-01-17 08:05 UTC
Labels: Core: Performance, enhancement, Core: Update settings, Reported
