### ISSUE TITLE
[9.0.0+]  Formula does not calculate if `setSourceDataAtCell` is given a certain column coordinate

### ISSUE THREAD

**Issue by zblust** [handsontable/handsontable#8722] opened 2021-09-15 14:53 UTC
Running into an issue where when using formulas, if you call setSourceDataAtCell using property names after calling setDataAtCell then the first column of data will show the formula instead of the calculated value.  If you click into and then out of the problem cell(s) they will rerender correctly.

I created a simple html page with a reproduction
https://jsfiddle.net/sx3108wk/

**Comment by AMBudnik** [comment] 2021-09-16 12:23
Thank you for sharing the code and explanation of the use case @zblust 

I reproduced the result you got and it seems that we do not calculate the formula if  `setSourceDataAtCell` is given a column coordinate with 
* a new (unexciting key)
* key that does not exist in the `columns` declaration

I will update the topic after some further investigation.

**Comment by AMBudnik** [comment] 2021-09-16 13:15
I can confirm that with that given scenario formula does not update in v 9+ https://jsfiddle.net/6bjdgszt/2/ but it does in v8.4.0 (with a different formula engine) https://jsfiddle.net/8sabyLvk/ 

@zblust I will update you as soon as we alter this behavior to the one we had before v9.

**Comment by AMBudnik** [comment] 2022-06-23 07:41
Yes, @sequba you're right. @zblust demo uses the @latest version where the formulas are correctly reclaculated. And here https://jsfiddle.net/6bjdgszt/2/ (v9) we can see what was the issue).

We can close this issue as solved.

@zblust please let us know if the issue is still present after updating to v12.

**Closed by AMBudnik** 2022-06-23 07:41 UTC
Labels: Type: Bug, Formulas, Regression
