### ISSUE TITLE
when scrolling is not on the left, open the editor, drag the scroller to the left, then keydown some word, the whole view will jump to the left

### ISSUE THREAD

**Issue by zuan336** [handsontable/handsontable#4832] opened 2018-02-22 03:01 UTC
### Description
when scrolling is not on the left, open the editor, drag the scroller to the left, then keydown some word, the whole view will jump to the left

### Steps to reproduce
1.keydown to open the editor
2.drag the scroller to the left
3.then keydown some word
4.the whole view will jump to the left, Layout error

### Demo
Just your official example. Any case can has this problem.
https://handsontable.com/features

![qq20180222-105750](https://user-images.githubusercontent.com/28526494/36518022-aabb3774-17bf-11e8-9505-ce192b012ae4.gif)

**Comment by zuan336** [comment] 2018-02-22 03:10
At first, you should keydown some word to open the editor on the cell. Then drag the scroller to the left. At last you should keydown some word one more. And you can see the whole view jump to the left.

**Comment by AMBudnik** [comment] 2018-02-22 06:46
Thank you for sharing an issue report with a demo. As it may sound silly in an example where the issue is replicable on the main project site the template and our methodology requires it.

Of course, I have replicated the issue on our demos as well and it does not look pleasant. It is definitely a bug.

**Comment by AMBudnik** [comment] 2018-04-05 07:07
The issue is still replicable in v `0.38.1`

**Comment by AMBudnik** [comment] 2018-12-28 09:55
The >features site changed. The example does not contain a table.
I am closing this issue but if you're able to replicate this bug in any other example please share.

**Closed by AMBudnik** 2018-12-28 09:55 UTC
Labels: Type: Bug
