### ISSUE TITLE
[7.4.0] Key navigation doesn't work for ContextMenu in iframes

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6505] opened 2019-11-29 11:35 UTC
### Description

Key navigation doesn't work for ContextMenu in iframes. This happens when I use a new option of the ContextMenu plugin `uiContainer` pointed to element which belongs to the top window frame.

### Steps to reproduce

1. Prepare demo where Handsontable is in the iframe and `uiContainer` points to the element of the top frame;
2. Click RMB and try to navigate by arrow keys;
3. As a result, nothing happens.

### Your environment
* Handsontable version: 7.3.0 & 8.0.0-beta.1
* Browser Name and version: Chrome 
* Operating System: macOs

**Comment by aninde** [comment] 2019-11-29 11:44
Demo https://jsfiddle.net/u1dw3y4h/1/ 7.3.0 v. It is hard to reproduce, mouse need to be still and focus have to be above contextMenu.

**Comment by budnix** [comment] 2019-11-29 12:08
@aninde I think that we can remove the "regression" label. This feature (`uiContainer`) was not released officially yet. I would call it a "regular" bug.

**Comment by swistach** [comment] 2019-12-03 22:30
That was a deliberate decision what we made together with  @wojciechczerniak. At that point, it was acceptable. I suppose that something changed in the meantime and now it's a blocker - let me know if you need any details - I'll try to help.
@aninde it's simpler to reproduce than it seems to be. All that you have to do is to release <kbd>RMB</kbd> out of context menu's container - I guess it's because `mouseup` might change listening of HOT instances.

**Comment by aninde** [comment] 2019-12-04 08:46
@swistach that's true. Thank you for  the clarification and completion of reproduction.

**Comment by aninde** [comment] 2019-12-11 11:12
A similar error also occurred without iframe, https://github.com/handsontable/handsontable/issues/6549 fortunately, @budnix  quickly repaired it.

Described here bug will be fixed by the latest build of `7.3.0` (11.12)
https://jsfiddle.net/aninde/3cLpr4gs/

**Comment by aninde** [comment] 2020-05-13 17:51
This bug still appears in `v8.0.0.-beta2-rev3` https://jsfiddle.net/aninde/nzg3j6ks/

**Comment by AMBudnik** [comment] 2020-07-06 12:53
Still replicable in `8.0.0-beta2-rev18` https://jsfiddle.net/a2yv7r1p/1/

**Comment by pnowak** [comment] 2020-09-02 10:54
When I using v8.0.0, I can't use `contextMenu` because immediately disappears.
![Sep-02-2020 12-51-55](https://user-images.githubusercontent.com/1555809/91972613-3f4afb80-ed1b-11ea-88bf-4dea9b69858c.gif)

**Comment by swistach** [comment] 2021-01-25 18:11
@pnowak - that behaviour will be fixed in a next release v8.3.0 by (https://github.com/handsontable/handsontable/pull/7372)

This issue was solved in v8.0.0-beta2 and works stable in v8+

**Comment by aninde** [comment] 2021-02-16 12:14
Unfortunately this bug still occurs as a regression as of version 7.4.0+ and still on v8.
https://jsfiddle.net/6tkr14nL/ - v7.4.0 bug occurs on Chrome 88 & 89 / macOS Big Sur.
https://jsfiddle.net/xoqt1u2k/ v8.0.0

I'm reopening it as a regression and I'm changing the title.

**Comment by aninde** [comment] 2021-02-16 13:05
T.his issue was checked on windows and it was rightly closed, because keyboard navigation works.

**Closed by aninde** 2021-02-16 13:05 UTC
Labels: Context menu, Regression, Type: Bug, focus/blur
