### ISSUE TITLE
Add a `modifySourceData` hook.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#6546] opened 2019-12-10 08:40 UTC
### Description
In order for #6512 to work properly, we need to add a `modifySourceData` hook, to make injecting the editor with an external value possible.

For the `modifySourceData` hook to be analogous to `modifyData`, there needs to be a `set` and `get` `ioMode` implemented. It makes sense then to add a `setSourceDataAtRow` and `setSourceDataAtCell` methods as well.

**Note:** Because after this change, the `get-` methods for source data will no longer return a reference to the source data object, but a clone modified with values received from the new hook, this will be a **breaking change**.

**Comment by wojciechczerniak** [comment] 2020-07-03 08:25
Duplicate of #6664

**Closed by wojciechczerniak** 2020-07-03 08:25 UTC
Labels: Breaking change, Core: callbacks, Type: Feature
