### ISSUE TITLE
Limit cell formation for coumnSummary

### ISSUE THREAD

**Issue by anagas** [handsontable/handsontable#3516] opened 2016-05-18 10:11 UTC
Hello,

is it possible to limit a cell formation for a row? I try to use columnSummary but the formation overrides the summary.

`        columns: [
            {

                readOnly: true
            },
            {
                type: 'time',
                timeFormat: 'HH:mm',
                correctFormat: true,
                allowInvalid: true

            },
            {
                type: 'time',
                timeFormat: 'HH:mm',
                correctFormat: true
            },
            {
                type: 'time',
                timeFormat: 'HH:mm',
                correctFormat: true
            },
            {
                type: 'time',
                timeFormat: 'HH:mm',
                correctFormat: true
            },
            {
                type: 'time',
                timeFormat: 'HH:mm',
                correctFormat: true
            },
            {
                type: 'time',
                timeFormat: 'HH:mm',
                correctFormat: true
            },
            {
                type: 'time',
                timeFormat: 'HH:mm',
                correctFormat: true
            },
            {
                type: 'time',
                timeFormat: 'HH:mm',
                correctFormat: true
            },
            {
                type : { renderer : function (instance, TD, row, col, prop, value, cellProperties) {
                    Handsontable.TextCell.renderer.apply(this, arguments);
                    var cell1, cell2, cell3, cell4, cell5, cell6, cell7, cell8;
                    var field1, field2, field3, field4;
                    cell1 = instance.getDataAtCell(row, 1);
                    cell2 = instance.getDataAtCell(row, 2);
                    cell3 = instance.getDataAtCell(row, 3);
                    cell4 = instance.getDataAtCell(row, 4);
                    cell5 = instance.getDataAtCell(row, 5);
                    cell6 = instance.getDataAtCell(row, 6);
                    cell7 = instance.getDataAtCell(row, 7);
                    cell8 = instance.getDataAtCell(row, 8);

                    field1 = gettimeDiff(cell1, cell2);
                    field2 = gettimeDiff(cell3, cell4);
                    field3 = gettimeDiff(cell5, cell6);
                    field4 = gettimeDiff(cell7, cell8);

                    var sum = field1 + field2 + field3 + field4;

                    sum = parseFloat(sum.toFixed(2));
                    if(sum > 0) {
                        if(row < 31) {
                            TD.innerHTML = sum;
                        }
                    }
                }},
                forceNumeric: true,
                readOnly: true
            }
        ],
        dropdownMenu: false,
        colWidths: [100, 85, 85, 85, 85, 85, 85, 85, 85, 85]
        columnSummary: [
           {
               destinationColumn: 8,
               destinationRow: 0,
               reversedRowCoords: true,
                type: 'sum'

           }
        ]
    });`

Regards,

anagas

**Comment by AMBudnik** [comment] 2016-05-18 10:45
Hi @anagas 
Can you create a demo using JSFiddle to illustrate the example?
I made one using your settings: http://jsfiddle.net/handsoncode/meevqpk8/ but I think we're missing some crucial data.

**Comment by anagas** [comment] 2016-05-18 11:35
Hi,

thanks for your answer.

https://jsfiddle.net/x6no90ea/

**Comment by AMBudnik** [comment] 2016-05-19 09:30
Thanks, can you also share a scenario how to reproduce the issue? At the first glance the table looks as expected.

**Comment by anagas** [comment] 2016-05-19 09:38
Hello,

the 9 column in the last row should have the total value of tageswert see columnSummary. I think the reason why it does not work is that the last column is overrided by an another value.

**Comment by swistach** [comment] 2016-05-20 11:59
Hi @anagas,
I've updated your example: https://jsfiddle.net/x6no90ea/1/
Generally,  the custom renderer should not to be used for calculations on data. Custom renderer was designed for apply visual changes, and we reccomend this way of use.
You have to pay attention using afterChange and beforeChange hooks, becouse never ending loop is possible when you launch method which uses setDataAtCell. First you have to check source.

**Comment by anagas** [comment] 2016-05-24 08:45
Thanks.

**Comment by anagas** [comment] 2016-06-10 12:16
Hello,

when i use your example some of the main function are not working anymore. 

One of them is:

When i add a value to Beginn and Ende i will get a the calculated value at Tageswert.
When i mark now Beginn and Ende and drag-down to the last row only the first selected row will be calculated.

Like this:
![image](https://cloud.githubusercontent.com/assets/12841639/15963868/78317bcc-2f15-11e6-9b2d-33e07abbd034.png)
My old version:
![image](https://cloud.githubusercontent.com/assets/12841639/15963899/aef24768-2f15-11e6-94a7-c4f82a5fcf33.png)

I think the problem is that afterchange appears only on time. Is there a possible to get the old version with afterchange?

**Comment by AMBudnik** [comment] 2016-06-27 13:32
@swistach if I see as @anagas correctly stated there's a bug - data at the last column doesn't recalculate (we're missing some callbacks or render) when we copy/paste data using fill handle?

**Comment by swistach** [comment] 2016-07-20 09:08
@AMBudnik Fortunately it's not a bug. :)
@anagas In the example, I used afterChange only on the first change from `changes`.
`changes` is an array of arrays, so you have to do loop to apply many changes (number of modified cells is equal number of changes in `changes`).
Here is an example with console.log from `changes`: https://jsfiddle.net/x6no90ea/3/

**Comment by AMBudnik** [comment] 2016-08-29 13:30
I'm closing this issue due to lack of recent activity but feel free to leave a comment or create a new topic if needed.

**Closed by AMBudnik** 2016-08-29 13:30 UTC
Labels: Answered
