### ISSUE TITLE
colWidths do not work for nestedHeaders

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6589] opened 2019-12-30 12:18 UTC
### Description

Once we set up nestedHeaders we're not able to use `colWidths`. They do not apply but they remove the ability of a column to expand to data length. The header is as wide as its name.

### Steps to reproduce

1. Use `nestedHeaders` like here https://jsfiddle.net/apdeg7L6/
2. Check the widths of columns

![Zrzut ekranu 2019-12-30 o 13 12 40](https://user-images.githubusercontent.com/10757813/71581570-1a581600-2b06-11ea-9e53-a4c85beab294.png)

3. Replace them with the same set of `colHeaders` https://jsfiddle.net/h1eb3tgp/1/

![Zrzut ekranu 2019-12-30 o 13 12 50](https://user-images.githubusercontent.com/10757813/71581583-28a63200-2b06-11ea-8feb-1101305b9975.png)

remove the `colWidths` to check what is the actual width for this amount of data
![Zrzut ekranu 2019-12-30 o 13 15 01](https://user-images.githubusercontent.com/10757813/71581652-7cb11680-2b06-11ea-8e38-fe33e36bec66.png)

### Demo

https://jsfiddle.net/h1eb3tgp/

### Your environment
* Handsontable version: 7.3.0
It doesn't seem to be related to any version back.
* Browser Name and version: Chrome 79
* Operating System: macOS Catalina

Related https://github.com/handsontable/handsontable/issues/5981 , https://github.com/handsontable/handsontable/issues/6587

Inform [forum](https://forum.handsontable.com/t/gh-6587-nested-header-with-width/3992)

**Comment by swistach** [comment] 2021-01-26 14:41
Duplicate of #6587

**Closed by swistach** 2021-01-26 14:41 UTC
Labels: Core: alignment/height/width, Nested Headers, Type: Bug
