### ISSUE TITLE
"Plugins" menu item doesn't work

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#9689] opened 2022-07-20 12:45 UTC
To reproduce:

1. Switch to the `feature/react-docs` branch.
2. From the `/docs` directory, run `npm run docs:api`.
3. From the `/docs` directory, run `DOCS_VERSION="next" npm run docs:start`.
4. Open the local URL.
5. In the browser, in the upper-right corner, select **API Reference**.
6. From the left-hand menu, select **Plugins**:

<img width="1256" alt="1" src="https://user-images.githubusercontent.com/29247866/179985116-18ab5d16-7ab2-4f78-80d7-eb66cbc4979f.png">

The resulting URL is `http://localhost:8080/docs/.watch-tmp/react-data-grid/next/api/plugins`, which gives a 404.

<img width="504" alt="2" src="https://user-images.githubusercontent.com/29247866/179985219-b8a46be6-d318-40b9-87b7-a6a15f7e2787.png">

**Comment by budnix** [comment] 2022-08-08 12:00
The issue is already fixed in the `feature/react-docs` branch.

**Closed by budnix** 2022-08-08 12:00 UTC
Labels: Docs: Tools
