### ISSUE TITLE
bindRowsWithHeaders generates inconsistent row headers

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3367] opened 2016-04-01 10:22 UTC
When using the `bindRowsWithHeaders` plugin with no data source defined, all the row headers contain `1`, or `NaN` and `1` in a different scenario.
- https://jsfiddle.net/Lkpfq3jc/
- https://jsfiddle.net/Lkpfq3jc/1/

**Comment by AMBudnik** [comment] 2017-01-20 08:34
Still present in 1.9.1 https://jsfiddle.net/handsoncode/dtLjo12L/

**Comment by AMBudnik** [comment] 2018-01-22 12:11
Works the same in version 1.15.1

**Comment by AMBudnik** [comment] 2018-04-27 12:02
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by adamdehaven** [comment] 2019-05-15 17:53
Issue is still present in version `7.0.3`

**Comment by swistach** [comment] 2021-01-11 15:35
Fixed in v8.

**Comment by swistach** [comment] 2021-01-11 15:36
Hi @adamdehaven,
we fixed this issue in v8: https://jsfiddle.net/e35sbokt/

**Closed by swistach** 2021-01-11 15:35 UTC
Labels: BindRowsWithHeaders, Type: Bug
