### ISSUE TITLE
TypeError: out is null when nested data object member is null

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#2202] opened 2015-02-26 16:53 UTC
If you have a column setting defined as:

```json
{
  "data" : "foo.bar",
  "header" : "Foo Bar"
}
```

If the row being inserted has a member `foo = null`, you get a TypeError:

```
TypeError: out is null
```

I've tracked the problem down to `Handsontable.DataMap.prototype.get()`.  I believe its if check on `(typeof out === 'undefined')` should actually be `(typeof out === 'undefined' || out === null)`.

**Comment by AMBudnik** [comment] 2016-03-03 15:06
Hi @cgatesman does it still occur? I couldn't reproduce it.

**Comment by AMBudnik** [comment] 2016-03-22 10:03
I'm closing this issue as it wasn't updated for more than 2 weeks but if you would have any details that might come in handy please leave a comment.

**Closed by AMBudnik** 2016-03-22 10:03 UTC
Labels: Answered
