### ISSUE TITLE
Plugins using arrayMapper may don't work properly

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4567] opened 2017-10-23 10:30 UTC
### Description
At the moment arrayMapper may return `nullable` values. When we extend dataset, mappers are not replenished immediately. As the result, when we asking for not existing at start mapper indexes it returns `null`. 

We have some plugins which react on `modifyRow`/ `modifyCol` and inside those listeners uses the mapper (for example `manualColumnMove`, `manualRowMove`, `trimRows` and all other plugins using `trimRows`). Enabling a plugin and updating dataset can cause problems.

### Several related tasks

- #3811
- #3849
- [#11](https://github.com/handsontable/handsontable-pro/issues/11)

Can be also connected with https://github.com/handsontable/handsontable-pro/issues/57 and #3809.

### Your environment
* Handsontable version: 1.14.3, replicated also on <= 1.6.0
* Browser Name and version: Chrome 61.0.3163.100
* Operating System: macOS 10.12.6

**Comment by wszymanski** [comment] 2017-10-23 12:10
This part of [commit](https://github.com/handsontable/handsontable/commit/a04a9038e907cf7f14b85f255a77deebb9d67bb4#diff-465cdd97d8f0ae2205fa43963b7149acR663) may be helpful.

**Comment by AMBudnik** [comment] 2019-01-31 13:19
inform [forum](https://forum.handsontable.com/t/nested-rows-with-drag-and-drop-feature/2894)

**Comment by wojciechczerniak** [comment] 2019-08-14 09:57
Closing as duplicate of #5751

**Closed by wojciechczerniak** 2019-08-14 09:57 UTC
Labels: Filtering, Moving, Nested rows, Trimming, Type: Bug

**Comment by aninde** [comment] 2019-09-23 10:44
Described here issue are fixed by new` index mapper`.

#3811  is fixed in `7.1.1` and still fixed in `8.0.0-rc1`.
ver. `8.0.0-rc1` http://jsfiddle.net/aninde/72x8ow3t/

#3849 works well in `7.1.1` and `8.0.0-rc1`
ver. `8.0.0-rc1` http://jsfiddle.net/aninde/1obLg7jk/

#5860 is fixed by `8.0.0-rc1`
#3809 is fixed by `8.0.0-rc1 `
