### ISSUE TITLE
OSX Safari copy does not work

### ISSUE THREAD

**Issue by nicholascarroll** [handsontable/handsontable#2438] opened 2015-05-06 05:43 UTC
On Safari, Mavericks, copy cell does nothing. Neither as cmd-c or context menu with the flash hack. Paste cell does work.

**Comment by Lukazar** [comment] 2015-05-06 06:21
This is a duplicate of #2220

**Comment by AMBudnik** [comment] 2015-05-06 11:12
@Lukazar is right, please follow changes to https://github.com/handsontable/handsontable/issues/2220

**Closed by AMBudnik** 2015-05-06 11:12 UTC
