### ISSUE TITLE
Copy-paste to excel break text to multiple rows

### ISSUE THREAD

**Issue by formulajp60** [handsontable/handsontable#5622] opened 2018-11-28 03:38 UTC
### Description
When I try to copy any cell with multiple line text and paste to excel.. it breaks into multiple rows

### Steps to reproduce

1. Add cell values with line breaks.
2. Copy using CTRL + C
3. Paste into Excel

### Demo
![image](https://user-images.githubusercontent.com/22278846/49127345-d5264b00-f32b-11e8-8ca1-44b4cdafb9e9.png)

![image](https://user-images.githubusercontent.com/22278846/49127358-e8d1b180-f32b-11e8-87ad-955fd1db3ccd.png)

### Your environment
* Handsontable version: Version: 6.2.0
* Browser Name and version: Chrome  70.0.3538.102 
* Operating System: Windows 7

**Comment by AMBudnik** [comment] 2018-11-28 14:18
Yes, it looks like each <kbd>Enter</kbd> is a new row. Plus we get an empty row between the lines of text.

Not sure if that is what a user would expect, so I'll mark it as a thing to be `changed`.

**Comment by andrewQwer** [comment] 2018-11-29 13:02
Could this be affected by the fix for [this bug](https://github.com/handsontable/handsontable/issues/4308)?

**Comment by AMBudnik** [comment] 2018-11-29 13:40
Hey @andrewQwer 

that issue has been fixed in v `1.12.0` (`0.33.0`) but I can be a regression.
We'd need to investigate it more

**Comment by AMBudnik** [comment] 2019-06-12 07:42
Hey @formulajp60 @andrewQwer this issue has been fixed within https://github.com/handsontable/handsontable/issues/5684 in v`7.1.0` released yesterday.

**Closed by AMBudnik** 2019-06-12 07:42 UTC
Labels: Copy-paste, Type: Change
