### ISSUE TITLE
strechH causes table body to be narrower than the table header

### ISSUE THREAD

**Issue by Zukeh** [handsontable/handsontable#2831] opened 2015-09-21 16:02 UTC
Even though in my application this happens all the time, in jsfiddle it's a bit harder to replicate it.

Here: http://jsfiddle.net/29o6tsjL/

- Reduce the width of the right side of the screen until it shows scrollbars in the output "window"
- For a brief moment it will also show a vertical scrollbar (that means you're close)
- If you make it narrower just a bit more you will see that the table body got narrower than the table header.

If this sounds confusing I can record a video.

![Demo](http://i.imgur.com/doQJf5s.png)

**Comment by AMBudnik** [comment] 2015-09-21 17:11
Hi @Zukeh could you provide more information about OS/Brower+addons? I tried it with OSX Chrome, Firefox and Win7 Chrome

**Comment by Zukeh** [comment] 2015-09-21 17:28
Just tried it in Firefox v40, Windows 10, x64

![Demo](http://i.imgur.com/r8iolB0.gif)

**Comment by AMBudnik** [comment] 2015-09-21 19:50
Thank you for this video, I can confirm it at Windows 7 and 8.1 with all major browsers. I couldn't reproduce it with OSX.

I seems that scroll appears under `colHeaders` and it causes other rows to shrink. It gets back to normal after stretching result window, but it can look unpleasant - I agree.

**Comment by mlms13** [comment] 2015-09-30 16:16
I saw this in OS X (not with this example, but in my own project) as well. If I can reproduce a simpler example that consistently happens on OS X, I'll be sure to post it here.

**Comment by AMBudnik** [comment] 2016-03-16 15:56
Still in 0.24.1, demo: http://jsfiddle.net/29o6tsjL/4/

**Comment by mathiasconradt** [comment] 2016-08-22 12:11
@AMBudnik The demo on http://jsfiddle.net/29o6tsjL/4/ works fine for me on OS X, latest Chrome version as well as Firefox.

**Comment by AMBudnik** [comment] 2016-08-31 09:20
thanks for your feedback @mathiasconradt 
I'm still facing the exact behavior at Win 10 and there's actually the same issue reported and already reviewed by @jansiegel here: https://github.com/handsontable/handsontable/issues/3732
It will be fixed on 1st of Sept.

**Closed by AMBudnik** 2016-08-31 09:20 UTC
Labels: Bug, Core: alignment/height/width, Priority: normal
