### ISSUE TITLE
Setting rowHeaders to false leaves first column cells without left border when fixedColumnsLeft > 0

### ISSUE THREAD

**Issue by softicnermin** [handsontable/handsontable#5735] opened 2019-01-23 14:44 UTC
### Description
Switching **rowHeaders** to false on a table with fixed first (one or more) column leaves the first column cells without left border.

### Steps to reproduce
1. Set initial table to have **rowHeaders** to true and **fixedColumnsLeft** to 1 or more
2. update settings to set **rowHeaders** to false 

### Demo
https://jsfiddle.net/nerkosofta/vhj2aLqu/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome latest
* Operating System: Ubuntu 16.04

**Comment by AMBudnik** [comment] 2019-01-24 11:01
Thank you for sharing @softicnermin 

I have replicated the issue.

Previously the rows were misaligned https://github.com/handsontable/handsontable/issues/2909 but now we have no border

**Comment by AMBudnik** [comment] 2020-01-17 09:56
Works the same in 8.0.0-beta1

![Zrzut ekranu 2020-01-17 o 10 55 50](https://user-images.githubusercontent.com/10757813/72602716-fe32e200-3917-11ea-97a5-dd3ef73303d7.png)

https://jsfiddle.net/mru6pLwx/

**Comment by pnowak** [comment] 2020-08-28 07:48
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/uge7Lt38/

**Comment by aninde** [comment] 2020-09-28 14:46
@softicnermin  this issue will be fixed by the upcoming `v8.1.0` https://jsfiddle.net/aninde/mae1y0b4/.
The left border is restored. We plan to release it this week (Oct 1), as long as everything goes well.

<img width="319" alt="Screenshot 2020-09-28 at 16 44 16" src="https://user-images.githubusercontent.com/30186818/94447322-ecdded00-01a9-11eb-9ba8-344074a5e939.png">

**Comment by AMBudnik** [comment] 2020-10-01 13:14
Hi @softicnermin 

I'm more than happy to announce that the issue is no longer replicable after updating to Handsontable v 8.1.0.

**Closed by AMBudnik** 2020-10-01 13:14 UTC
Labels: Fixing, Headers, Type: Bug

**Comment by ElixirMike** [comment] 2020-10-02 19:21
the issue of row alignment is still showing up for me with the 8.1.0 version. This happens when first row is frozne, turn off the row headers and have a different height.

![image](https://user-images.githubusercontent.com/34098742/94961623-fd040e00-04c2-11eb-9c87-96b5e5dcd406.png)

**Comment by AMBudnik** [comment] 2020-10-05 07:23
Hi @ElixirMike I do not see a missing border in your image. 
Can you send me a demo where the issue can be replicable to support@handsontable.com

**Comment by ElixirMike** [comment] 2020-10-05 12:41
It's not a missing border, it's that the row /cell header is slightly off. Here is a zoomed in look at what I mean.
![image](https://user-images.githubusercontent.com/34098742/95080703-7e87b600-06e6-11eb-8577-bb6cf53c5287.png)

**Comment by AMBudnik** [comment] 2020-10-06 06:27
Does it change anything when you switch on the [autoRowSize](https://handsontable.com/docs/8.1.0/Options.html#autoRowSize), @ElixirMike ? 
If not please send a demo where the issue can be replicable to support@handsontable.com
