### ISSUE TITLE
Merge cells plugin does not work in the initial render

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#7164] opened 2020-08-03 13:00 UTC
### Description
Merge cells plugin does not work in the initial render. Instead, it runs after the `afterInit` hook and causes a rerender. This is bad for a few reasons:

- Bad performance: There are two full renders of Handsontable if the merged cells plugin is used
- If another plugin uses `afterRender` during the initial rendering, it will be confused about cells not being merged, because they will only be merged in the second render.

### Steps to reproduce

1. Use merged cells plugin to merge some cells in your config
2. Use `afterRender` hook to observe that it is triggered more than once on initialization and that the first render does not include merged cells

### Demo
https://jsfiddle.net/drm5Lfo3/1/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: any
* Operating System: any

### Screenshot

![image](https://user-images.githubusercontent.com/566463/89185023-da747800-d599-11ea-9a90-44adfe1af7ee.png)

**Comment by AMBudnik** [comment] 2020-09-02 10:46
This issue remains the same for v 8.0.0 https://jsfiddle.net/AMBudnik/yo4gpxjs/

**Comment by warpech** [comment] 2020-09-07 20:29
Labelling this also as "Core: Performance", because the double render causes noticeable slowdown on full screen grids, especially on a laptop CPU.

**Comment by warpech** [comment] 2020-11-18 20:52
This issue is a duplicate of https://github.com/handsontable/handsontable/issues/5687.

**Comment by AMBudnik** [comment] 2020-12-03 11:56
I guess that we can close the issue as it is a duplicate of #5687

**Closed by AMBudnik** 2020-12-03 11:56 UTC
Labels: Core: performance, Merge cells, Type: Bug
