### ISSUE TITLE
Error thrown on cell scroll (scrollViewport) if the last columns are hidden

### ISSUE THREAD

**Issue by arrdev** [handsontable/handsontable#4380] opened 2017-07-07 12:49 UTC
### Description
The error "column does not exist" is seen in the console, if you are navigating the sheet to the far right and the last two or more columns are hidden.

### Steps to reproduce

1. Set columns config for the last columns (two or more) to be hidden.
2. Navigate to the far right cell of any row in the sheet.
3. Hit right arrow key one more time.
Result: error is seen in console.

### Demo
https://jsfiddle.net/8qz0hb3a/7/

### Your environment
* Handsontable version: latest pro
* Browser Name and version: Chrome 58.0.3029.110 (64-bit)
* Operating System: windows 10

**Comment by AMBudnik** [comment] 2017-07-07 13:38
Thank you for sharing this issue. You're right we got an error after trying to select another column. The issue is gone when we do not set a fixed amount of columns via `columns` option.
Besides the issue already reported here https://github.com/handsontable/handsontable/issues/4370 we get the error.

If the columns will be set to `7` the issue is gone.

**Comment by arrdev** [comment] 2017-07-07 14:19
Could you please elaborate?
Which config settings should be changed?

**Comment by AMBudnik** [comment] 2017-07-10 11:03
Hi @arrdev 

the `columns` settings are the case. (lines: 48-87). Of course, this is still an issue as the `columns` have been set properly and the issue also is replicable by doing the same operations using `cells` method.
Unfortunately, I do not see any workaround for this issue yet.

**Comment by AMBudnik** [comment] 2018-04-27 13:30
This issue is replicable in v `2.0.0` and all PRO versions before that.

**Comment by wojciechczerniak** [comment] 2019-02-21 14:55
Fixed in v5.0.1: https://jsfiddle.net/u5gwrbaL/3/

**Closed by wojciechczerniak** 2019-02-21 14:55 UTC
Labels: PRO: hiding, Type: Bug
