### ISSUE TITLE
If the last column is a hidden column and stretchH is enabled, last column is being displayed

### ISSUE THREAD

**Issue by nulayuhz** [handsontable/handsontable#4370] opened 2017-07-05 21:03 UTC
### Description
If the last column is a hidden column and stretchH is enabled, last column is being displayed.

### Demo
taken from https://docs.handsontable.com/pro/1.11.0/demo-hiding-rows.html, and with the additional settings hiddenColumns and stretchH: 'last'

http://jsfiddle.net/c49j6w8r/

**Comment by AMBudnik** [comment] 2017-07-07 13:04
Thank you for sharing the issue @ahlunju 

I have got the same result.

Testing on: Chrome 59, Windows 10.

**Comment by Cuiyansong** [comment] 2018-03-01 13:18
We met the same issue, is there any work around? Thanks

**Comment by AMBudnik** [comment] 2018-03-01 13:31
Hm.. I can see that the issue is still replicable in version 1.17.0 http://jsfiddle.net/3kpmgmkm/
I do not see any fast workaround. It looks like the issue is not gone after rerendering.

**Comment by Cuiyansong** [comment] 2018-03-01 15:56
One way to work around is re-calculation some column width if these column width is set to percentage style. Before init hot table, we get the table client width and total column width which is not percentage style, so we get reality width of the percentage column.

**Comment by Cuiyansong** [comment] 2018-03-01 17:53
And another way to control column displaying is to update hot setting for columns.

**Comment by AMBudnik** [comment] 2018-04-27 12:53
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by dosaki** [comment] 2018-10-16 15:46
Is there an ETA on this issue?

**Comment by AMBudnik** [comment] 2018-10-17 13:31
Sorry @dosaki but it hasn't been scheduled yet

**Comment by dosaki** [comment] 2018-10-17 13:40
Thanks for letting me know @AMBudnik 
This may be a problem for some of our users as they can choose to hide whichever column they want.

I'm not very familiar with the handson codebase but if someone pointed me in the right direction I might have a look at this and see if I can fix it.

**Comment by mallory-eaton** [comment] 2019-05-10 20:50
This is still an issue in 7.0.0.

**Comment by meta-rohit-singhavi** [comment] 2019-05-22 09:06
@AMBudnik Please provide any solution for this issue asap.

**Comment by dosaki** [comment] 2019-05-22 14:22
@meta-rohit-singhavi The work-around that I have is to check what columns are hidden and move them to be the first items in the table.

Would that work for you?

**Comment by meta-rohit-singhavi** [comment] 2019-05-30 11:05
@dosaki It worked for me. Thanks.

**Comment by AMBudnik** [comment] 2020-05-08 07:39
7.4.2 https://jsfiddle.net/wr72cu49/1/ (broken)  
8.0.0.-beta1 https://jsfiddle.net/wr72cu49/2/ (broken)  
**8.0.0.-beta2** https://jsfiddle.net/wr72cu49/3/ (**issue solved**)

![](https://user-images.githubusercontent.com/10757813/81383130-cb536a80-910f-11ea-9458-85f3721cfa0d.png)

**Comment by AMBudnik** [comment] 2020-07-16 10:18
Hi @nulayuhz 

I have good news! We've just released 8.0.0-beta2 that fixes the following issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

@dosaki @meta-rohit-singhavi @Cuiyansong @mallory-eaton 

All feedback's appreciated. Thank you for your input.

**Comment by dosaki** [comment] 2020-07-16 10:24
That's pretty good news!
Thank you!

**Comment by AMBudnik** [comment] 2020-08-06 11:35
Demo updated to the official (stable) v8.0.0 https://jsfiddle.net/cwa56r7f/. I hope that it works for you as well @dosaki @nulayuhz @meta-rohit-singhavi @Cuiyansong @mallory-eaton 

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback.

**Closed by AMBudnik** 2020-08-06 11:35 UTC
Labels: Hiding, Type: Bug
