### ISSUE TITLE
Backlight isn't correctly positioned when moving a row

### ISSUE THREAD

**Issue by MuresanIoana** [handsontable/handsontable#9432] opened 2022-04-28 08:16 UTC
If we have the table placed into a scrollable content and the content is scrolled, the backlight isn't correctly positioned when moving a row.
You can see the issue reproducing in the fiddle bellow. The version used in the fiddle is 7.4.2 but it also reproduces on 11.2, which is the last version.
https://jsfiddle.net/8at3d2wv/

Always when the content is scrolled and we try to move a row the backlight is positioned on the first row of the table.
It is very difficult to find a workaround because the rootElementOffset does not take into account that the content is scrolled.

**Comment by adrianszymanski89** [comment] 2022-04-28 08:51
Hi @MuresanIoana 

I have tested your example on MacOS with Google Chrome 100 and on Windows 10 with Edge and I couldn't recreate the issue you are describing, everything worked as intended. Can you tell me what is your configuration?

**Comment by MuresanIoana** [comment] 2022-04-28 08:59
Yes, indeed the fiddle was incorect, now you should be able to reproduce the issue, I've fixed the fiddle https://jsfiddle.net/8at3d2wv/

**Comment by adrianszymanski89** [comment] 2022-04-28 12:54
Thank you, now the issue is replicable in both versions of Handosntable. I will mark it as a bug, as there is no internal options that could prevent such behavior.

**Comment by adrianszymanski89** [comment] 2023-08-23 11:41
Hi @MuresanIoana 

I'm happy to inform you that this issue was fixed in Handsontable 13.0. Here's an example: https://jsfiddle.net/handsoncode/12ycxut3/

**Closed by adrianszymanski89** 2023-08-23 11:41 UTC
Labels: bug, Scroll, Moving, Reported
