### ISSUE TITLE
Scroll amount of selectCell is too few

### ISSUE THREAD

**Issue by maxwildgrube** [handsontable/handsontable#2572] opened 2015-06-19 22:05 UTC
I want to scroll to a specific row in my table and I use the HOT method "selectCell" (with parameter scrollToCell==true) for that purpose.
But it does not work as expected.
It works well if the rows have a constant height of 1 line.

But with rows of heights > 1 the scrolling get out of sync. It stops several lines before the selected row. The selected row is then not visible on the triggered section.
The difference grows with the scroll amount.

Tested with HOT 0.15.0 on IE, Chrome and FF.
(added on 2015-07-26: just to say that I tested it also with 0.16.0)
(added on 2015-09-01: just to say that I tested it also with 0.17.0)
(added on 2015-09-19: just to say that I tested it also with 0.18.0 on FF)
Demo is shown on http://jsfiddle.net/qvLr4Ly5/6/

For a counter-example (1-line rows) you can set
var split = false;
The triggered row is shown as the last row on the page. This may be as designed, but somehow questionable: Why not on top of page or even in the middle? (But this is not essential yet)

**Comment by AMBudnik** [comment] 2015-06-21 13:50
You are right, I tested a simple `selectCell` with css row given height and it acts the same as you described.

**Comment by AMBudnik** [comment] 2016-03-03 12:45
Confirmed with 0.23.0
using `autoRowSize: true` which fixes scrolling horizontally doesn'r effect bug described above.

**Comment by AMBudnik** [comment] 2017-08-28 09:04
Replicable in v0.34.0 as well.

Might be related to https://github.com/handsontable/handsontable/issues/3263

**Comment by AMBudnik** [comment] 2018-04-16 11:26
The issue is still replicable in v `2.0.0.`. Updated and simplified demo http://jsfiddle.net/4vcynquL/. This issue is old. It doesn't seem to work in any of previous versions of Handsontable.

**Comment by AMBudnik** [comment] 2019-09-26 12:43
I'm closing this issue as a duplicate of https://github.com/handsontable/handsontable/issues/6256

**Closed by AMBudnik** 2019-09-26 12:43 UTC
Labels: Type: Bug
