### ISSUE TITLE
Improper selection after insert column/row when mergeCells is enabled.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4897] opened 2018-03-05 14:18 UTC
### Description
If you enable `mergeCells` plugin, then selection works improperly.
![mergecells_true](https://user-images.githubusercontent.com/11849621/36980962-2390d792-208c-11e8-9251-9fac59d35188.gif)
![mergecells_arr](https://user-images.githubusercontent.com/11849621/36981036-51ba464e-208c-11e8-8dfa-e236b98b0cd4.gif)

When mergeCells is disabled, then selection works as we expected.
![mergecells_false](https://user-images.githubusercontent.com/11849621/36980988-324a013c-208c-11e8-8b8c-d4314a89fd0c.gif)

### Steps to reproduce
1. Select `B2`
2. Add row above or column left from context menu

### Demo
https://jsfiddle.net/yfmcqcy7/

### Your environment
* Handsontable version: 0.15.0+
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment] 2018-04-27 09:15
The issue is no longer replicable

![gif](https://user-images.githubusercontent.com/10757813/39355024-58734f2c-4a0c-11e8-9322-19b28e9f0254.gif)

**Comment by aninde** [comment] 2019-09-19 10:31
| 1st (left) -> 2nd (right) action | insert row above                                     | insert column right               | insert row below | insert row below
| -------------------------------- |:--------------------------------------:|:---------------------------:|:---------------------------------------:| :---------------------------------------:|
| ver. 1.17.0                              | -                                                     | ✓¹                                   |  ✓²                                                   |
| ver. 2.0.0.                    | ✓³                                                  | -                                      | [✘](http://jsfiddle.net/8o4qkaLo)⁴    | 
| ver. 7.1.1.                | [✘](https://jsfiddle.net/2fvc15gu)⁵ | ✓⁶                                   | -                                                       | ostatnia

**Comment by aninde** [comment] 2019-09-19 12:18
Sadly, v. `8.0.0-rc1` doesn't fix described here issue. Bugs are still there, regardless of version. Interestingly, the bug occurs even when `selectionMode` is set: `single`. It was described in [#5181](https://github.com/handsontable/handsontable/issues/5181)

@AMBudnik I couldn’t reproduce your demo. When I tested this issue at [2.0.0](https://jsfiddle.net/aninde/zwdgv5b1/) v. behavior was the same as another.

|   version   | insert row above | insert col. right  | insert row below | insert col. left
| ----- |:-----:|:-----:|:-----:|:-----:|
| `1.10.0`  | bug   | works | works   | bug
| `2.0.0.`    | bug  | works | works| bug
| `7.1.1` | bug | works | works   | bug
| `8.0.0-rc1` | bug   | works | works | bug


**After inserting row above**
The Visual index of selection is moving down.
![insert row above 8 0 0-rc1](https://user-images.githubusercontent.com/30186818/65241906-0fdcb800-dae5-11e9-83f3-e92044a839b2.png)

**After inserting column on the left**
The visual index of selection is moving to the left.
![insert col left 8 0 0-rc1](https://user-images.githubusercontent.com/30186818/65241900-0a7f6d80-dae5-11e9-964c-56fbed357d0e.png)

**Demo**
v. 1.17.0 https://jsfiddle.net/aninde/4botwn70/ forked original demo
v 2.0.0. https://jsfiddle.net/aninde/zwdgv5b1/
v. 7.1.1. https://jsfiddle.net/aninde/mwvauxhd/
v. 8.0.0-rc1 https://jsfiddle.net/aninde/qLenwabp/

**Environment**
Browser Name and version: Google Chrome version 76.0.3809.100, but same at any other one
Operating System: macOS Mojave 10.14.6

**Comment by AMBudnik** [comment] 2020-04-24 13:21
Related https://github.com/handsontable/handsontable/issues/4859

**Comment by AMBudnik** [comment] 2020-07-10 11:40
The issue **solved** in beta2 of 8.0.0. https://jsfiddle.net/wkL4s82h/ (rev21).

**Before**
![Zrzut ekranu 2020-07-10 o 13 39 47](https://user-images.githubusercontent.com/10757813/87150737-f0508f00-c2b2-11ea-94ba-7130fff3c5eb.png)


**After**
![Zrzut ekranu 2020-07-10 o 13 40 01](https://user-images.githubusercontent.com/10757813/87150739-f34b7f80-c2b2-11ea-9b3f-c907855f5069.png)

**Comment by AMBudnik** [comment] 2020-08-06 06:25
This issue is fixed in Handsontable v8.0.0 released yesterday.

For anyone following this subject. Feel free to leave your feedback.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases

**Closed by AMBudnik** 2020-08-06 06:25 UTC
Labels: Core: selection, Merge cells, Type: Bug
