### ISSUE TITLE
Custom text editor, copy/paste issue

### ISSUE THREAD

**Issue by avmalyutin** [handsontable/handsontable#4222] opened 2017-05-01 12:21 UTC
### Description
I have a table with two columns: name and code. I have created a simple custom editor for code column. The idea is, when user double clicks on the cell, the custom dialog with code editor opens. I have implemented it and posted the simplified example. (Link is below).

However, I have one issue with copy/paste functionality: if I use my editor, edit some code for the cell, press “Save”, the "code" column value seems to be correctly saved. But when I select this cell and press Ctrl+C, the value is not copied.

I read the tutorial of implementing the custom editor, but seems that I have missed something there. Of there is a bug in handsontable.

Thank you in advance.

### Steps to reproduce
1. Double click on the cell of row 0 and column 1.
2. Edit the text the appeared dialog. Press save button. Dialog dissappers
3. Select the cell of row 0 and column 1. Press Ctrl+C
4. Select the cell of row 1 and column 1. Press Ctrl+V
5. Wrong value is pasted.

### Demo
[Link to plunker](http://plnkr.co/edit/vVbo2jcM1yeuX7mlii9U?p=preview)

### My environment
* Handsontable version:  0.31.2
* Browser Name and version: Chrome 58.0.3029.81
* Operating System: Windows 7 SP1 x64.

**Comment by AMBudnik** [comment] 2017-05-05 12:03
That's an interesting case. I have reproduced the issue - the content cannot be copied.

**Comment by jansiegel** [comment] 2017-05-08 08:09
@avmalyutin The edited value doesn't get copied, because Handsontable thinks that the editor is still opened, even after the user closes it. This is caused by calling 
```js
this.instance.deselectCell();
```
in the `ScriptEditor.prototype.open` method. The `deselectCell` method marks the editor as closed, and then the editor marks itself as opened again. After commenting this line out, it seems to work fine: http://plnkr.co/edit/ycGqH5R1SM8U2A8PHnuM?p=preview

**Comment by avmalyutin** [comment] 2017-05-08 14:00
@jansiegel Thank you for response. Unfortunately, with your solution there is one minor issue: if the 

  `this.instance.deselectCell();`

is not called and after the code editor dialog is opened I can press **Enter** key. However, the new line is not inserted in code editor but the next row is handsontable is selected. Then I wrapped the function invocation into setTimeout and it seems to work. I will test it a little. Here is the link to the solution:
[Link to plunker](http://plnkr.co/edit/32rUrQ?p=preview)

Hope somebody this will help in the future.

Thank you for help. :-)

**Comment by swistach** [comment] 2017-06-13 13:43
@avmalyutin, thanks for your plunker. I'll close this issue now.
Feel free to reopen if necessary.

**Closed by swistach** 2017-06-13 13:43 UTC
Labels: Plugin: copy-paste, Status: Answered

**Comment by godshades** [comment] 2020-02-24 08:12
hi I have similar problem
i'm using select2js for custom editor
I just can't copy paste any cell use custom editor
please help
