### ISSUE TITLE
AutoRowSize plugin breaks table view when option rowHeaders is enabled

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#3971] opened 2017-01-02 09:15 UTC
### Description

Table looks like on the below image.

![table](https://cloud.githubusercontent.com/assets/141330/21586720/48b165d6-d0d4-11e6-9d65-f325da2713fa.PNG)

### Steps to reproduce

1. Set `rowHeaders` and `autoRowSize` options to `true`

### Demo
http://jsfiddle.net/kq0g508j/3/

### Your environment
* Handsontable version: 0.29.2
* Browser Name and version: Google Chrome 55.0.2883.87 m (64-bit)
* Operating System: Windows 7

**Comment by AMBudnik** [comment] 2018-01-22 06:41
Hi @wszymanski 
I've tested the same version (1.8.2) on OSX and Windows 10 in Chrome (v63) and get the expected result

![image](https://user-images.githubusercontent.com/10757813/35208234-8e6d86f2-ff47-11e7-8a10-feab4b1bee50.png)

Maybe we should also try Windows 7 before closing.

**Comment by wszymanski** [comment] 2018-01-22 07:00
Maybe it can be also recreated on Windows 10 + Chrome `55` :)

**Comment by AMBudnik** [comment] 2018-04-20 08:49
We've tried it on Windows 7 (VM) with latest Chrome 66 and the issue is no longer replicable.

**Closed by AMBudnik** 2018-04-20 08:49 UTC
Labels: Headers, Plugin: auto row size, Priority: normal, Type: Bug
