### ISSUE TITLE
Usage of Column and Row Index during Event Handling

### ISSUE THREAD

**Issue by sapreuss** [handsontable/handsontable#1165] opened 2013-11-13 11:14 UTC
Hi,

ot looks like there is a different handling of the row und column index during event handling.

The 'changes' array in the afterChange Event seems to provide a mixture of a physical  row and a logical column index.The mixture of metadata (logical) row and change array column is pointing to the correct data row and column.
But - is the addressing of the meta data correct this way?

Using the context menue 'clone', the row / column index provided by 'getSelected' are pointing to the physical cell (shown on the screen). The cell metadata are pointing to the correct data row and column.

pls refer to: http://jsfiddle.net/sapreuss/Lkaxe/

Change the column order and sort by any column. Now the events will evaluate the given coordinates and show the results generated by a cell change or the context menu 'Clone'.

Is this meant to work like this or is there a misinterpretation of the coordinates?

Thx for information

**Comment by AMBudnik** [comment] 2016-03-21 12:42
Hi @sapreuss 
Could you check the issue with the latest (0.24.1) version?
I couldn't reproduce it.

**Comment by sapreuss** [comment] 2016-03-28 16:58
Hi Aleksandra,

 

I have not updated Handsome Table since more than a year (0.13.).

 

Sorry, I can not check the current version

 

 

Freundliche Grüße

Sebastian Preuß



 

Von: Aleksandra Budnik [mailto:notifications@github.com] 
Gesendet: Montag, 21. März 2016 13:43
An: handsontable/handsontable <handsontable@noreply.github.com>
Cc: sapreuss <sapreuss@input98.de>
Betreff: Re: [handsontable] Usage of Column and Row Index during Event Handling (#1165)

 

Hi @sapreuss <https://github.com/sapreuss>  
Could you check the issue with the latest (0.24.1) version?
I couldn't reproduce it.

**Comment by AMBudnik** [comment] 2016-03-29 07:26
Thanks for your prompt reply @sapreuss 
since I couldn't reproduce the issue I'm closing this topic.

**Closed by AMBudnik** 2016-03-29 07:26 UTC
Labels: Answered
