### ISSUE TITLE
the row height too large when  autoRowSize enable

### ISSUE THREAD

**Issue by wangdingwei** [handsontable/handsontable#9536] opened 2022-05-26 10:59 UTC
### Description

the row height too large when autoRowSize enable

### Demo

https://jsfiddle.net/k6pu7dfj/2/

### wrong result
<img width="534" alt="image" src="https://user-images.githubusercontent.com/6716895/170475392-53149a2c-01a0-48b7-9a2f-fbbfef7f3fde.png">

### expect/correct result
when scroll right, the row height become correct.
<img width="493" alt="image" src="https://user-images.githubusercontent.com/6716895/170475502-3aa8689a-6840-4926-b823-50ecdcc8b959.png">

**Comment by adrianszymanski89** [comment] 2022-05-26 12:50
Hi @wangdingwei 

Thank you for reporting the issue. I have tested it and it's definitely a bug caused by data items with spaces.

Case #1, random data object with string (lorem ipsum) with space:

https://jsfiddle.net/aszymanski/7sj1f08g/2/

Case #2, the same data object but with space removed in lorem ipsum, works correctly:

https://jsfiddle.net/aszymanski/7sj1f08g/3/

**Comment by gianadrias** [comment] 2022-07-07 00:51
Is there any update on this issue? I also experience this scenario

**Comment by wfcwoody** [comment] 2023-10-20 13:28
Any news on when this can be expected to be fixed? It's been over a year since the last update and it's causing us significant problems

**Comment by adrianszymanski89** [comment] 2023-10-20 13:30
@wfcwoody 

Not yet. I just answered your topic on our forum.

**Comment by wfcwoody** [comment] 2023-10-20 13:35
I'm new to using Handsontable. Do bugs usually take this long to fix?

**Comment by adrianszymanski89** [comment] 2023-10-20 13:48
We are a relatively small team, and we must prioritize our tasks according to our goals. That's why some things might take longer to be done. Also, some issues that seem easily fixed lie deep within the core and touch other functionalities. This is also the case here.

The good news is that we have plans to refactor the whole dimensions calculation engine, so the problems like this will be fixed. We don't have any timeline for this yet, but I'll update you once it is done.

**Comment by wfcwoody** [comment] 2023-10-20 13:53
Thanks

**Comment by adrianszymanski89** [comment] 2024-08-12 13:15
Hi @wangdingwei  @gianadrias  @wfcwoody 

In the latest release, 14.5, we made some improvements to the dimensions calculations. I rechecked the original example, and the issue is no longer present: https://jsfiddle.net/handsoncode/ofc613qv/

Can you please confirm the fix?

**Comment by AMBudnik** [comment] 2024-12-16 08:24
Hi @wangdingwei @gianadrias @wfcwoody 

Could you please check if the issue is still replicable in your application? 

I was doing a test, and apparently, the issue is solved. I was testing the @wangdingwei demo on Chrome 131, macOS Ventura, and got the expected result.
![Zrzut ekranu 2024-12-16 o 09 20 45](https://github.com/user-attachments/assets/d04bb7d0-7401-4d4f-9899-7272acd3e87d)

I will close this issue as solved. However, if you would get any other result using the latest version of Handsontable (v14.6.1) please let me know,

**Closed by AMBudnik** 2024-12-16 08:24 UTC
Labels: bug, Auto row size, Reported
