### ISSUE TITLE
[7.1.1] Table doesn't render in `overflow:scroll` container without `min-height`

### ISSUE THREAD

**Issue by aarondfrancis** [handsontable/handsontable#6213] opened 2019-08-19 17:41 UTC
### Description
When the table is in an `overflow:scroll` container, it renders blank. If you add a `min-height: 1px` rule to it, it works as expected. This behavior is different than 7.1.0.

(I've added tailwind css to the fiddle as an easy way to isolate the important css)

### Steps to reproduce
1. Go to fiddle
2. Toggle CSS `min-height` declaration on and off

### Demo
https://jsfiddle.net/mg5xrocq/6/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome
* Operating System: OS X

**Comment by krzysztofspilka** [comment] 2019-08-20 09:57
Works fine for me @aarondfrancis 

macOS Mojave
Version: 10.14.5 (18F132)
Chrome (latest)

**Comment by AMBudnik** [comment] 2019-08-20 10:27
Sorry, I've tested 7.1.1, 6.2.2 and 4.0.0 with and without the `min-height: 1px;` line and got exactly the same (correct) result. I've tested it on Chrome (as well) on Windows 10.

@aarondfrancis 
Do you have any zoom or additional settings turned on? 
What is your Chrome version?
Do you get any errors in the console?

It would also help if you could share a snapshot of the DOM structure for the 'blank container'.

**Comment by aarondfrancis** [comment] 2019-08-20 14:11
How strange!

I've taken screenshots with the fiddle with the CSS toggled on and off so you can see exactly what I'm seeing. This was done in a private browser, so no plugins were loaded. I've also included the Chrome (76.0.3809.100 (Official Build) (64-bit)) and OS X (10.14.4) versions there

![Screen_Shot_2019-08-20_at_9_06_48_AM](https://user-images.githubusercontent.com/881931/63354512-2fd45c80-c32a-11e9-9ca9-2ddaa181f580.jpg)
![Screen_Shot_2019-08-20_at_9_06_55_AM](https://user-images.githubusercontent.com/881931/63354513-2fd45c80-c32a-11e9-8a8b-32fbfe2aedff.jpg)

**Comment by aarondfrancis** [comment] 2019-08-20 14:12
Also confirmed it does not work on Safari.

![Screen Shot 2019-08-20 at 9 12 16 AM](https://user-images.githubusercontent.com/881931/63354761-ab360e00-c32a-11e9-828c-4816dbef8eb3.jpg)

**Comment by AMBudnik** [comment] 2019-08-21 12:56
I tried incognito using this demo https://jsfiddle.net/yx1bufn8/ (fixing styles removed) on two different screens with a fullscreen and resize windows. Still got the table.

Can you share the DOM tree structure and check it calling `hot.render()` changes anything?

**Comment by aarondfrancis** [comment] 2019-08-21 14:14
Well this is certainly odd isn't it?

Here is a screenshot of the dom structure with computed heights visible.

Resizing the browser causes the table to re-render, at which point it becomes visible.

![Screen Shot 2019-08-21 at 9 13 00 AM](https://user-images.githubusercontent.com/881931/63439605-fb2cd780-c3f3-11e9-9920-06840e086f29.jpg)
![Screen Shot 2019-08-21 at 9 12 54 AM](https://user-images.githubusercontent.com/881931/63439606-fb2cd780-c3f3-11e9-93ea-1177355bd192.jpg)

**Comment by aarondfrancis** [comment] 2019-08-21 14:41
Trying to get to the bottom of this... I fired up browserstack.com and ran it through a few. Here's what I got:

|             | macOS Mojave | Windows 10 | Windows 8.1 |
|-------------|:------------:|:----------:|:-----------:|
| Chrome 76   |       ✗      |      ✓     |      ✓      |
| Chrome 78   |       ✗      |      ✓     |      -      |
| Firefox 68  |       ✓      |      ✓     |      -      |
| Safari 12.1 |       ✗      |      -     |      -      |
| Opera 62    |       ✗      |      -     |      -      |

**Comment by wojciechczerniak** [comment] 2019-08-21 15:28
Thanks @aarondfrancis, that gave me an idea:

![Screenshot 2019-08-21 at 17 16 08](https://user-images.githubusercontent.com/4718998/63444728-71066280-c437-11e9-82e9-0d3d4636aac9.png)

Most of us have scrollbars set to "always" and we couldn't reproduce what you see.

**Comment by aarondfrancis** [comment] 2019-08-21 15:36
@wojciechczerniak interesting thought! Mine was set to "automatic", but even when I change it it still doesn't seem to work...

![image](https://user-images.githubusercontent.com/881931/63446267-82337d00-c3ff-11e9-95c4-3bd1147af955.png)

**Comment by wojciechczerniak** [comment] 2019-08-21 15:40
If I set to "when scrolling" I can reproduce what you see. With "always" everything works as expected. With "automatic" it looked like it's working for me but now you said it was your setting.

**Comment by aarondfrancis** [comment] 2019-08-21 15:43
Boom. When set to `always` the issue goes away completely. So at least we've reproduced it! Good thinking.

**Comment by wojciechczerniak** [comment] 2019-08-21 15:52
Awesome! Thank you very much for the effort you put into tracing it. Now we know what to do.

@AMBudnik bug was reproduced by me, @aarondfrancis and @swistach

**Comment by AMBudnik** [comment] 2019-08-22 06:44
What an investigation that was! Well done guys.

**Comment by AMBudnik** [comment] 2019-08-22 06:45
Ah and one more (important) question. Does it break in the latest version?

**Comment by AMBudnik** [comment] 2019-10-15 10:32
@aninde can you check this one? I'm on Windows today

**Comment by aninde** [comment] 2019-10-15 10:51
@aarondfrancis I've got good news, this bug will be fixed in `7.2.0` v. which will be released today.
I tested it on Chrome 77/MacOs  with all scroll bar settings. 

![Screenshot 2019-10-15 at 12 46 46](https://user-images.githubusercontent.com/30186818/66825326-5c7fab80-ef4a-11e9-9f15-e6dafbfd6f3c.png)
![Screenshot 2019-10-15 at 12 46 30](https://user-images.githubusercontent.com/30186818/66825333-5d184200-ef4a-11e9-9431-b267dab9be42.png)
![Screenshot 2019-10-15 at 12 46 13](https://user-images.githubusercontent.com/30186818/66825345-62758c80-ef4a-11e9-8ab0-72d9a7f167c7.png)



**Demo**
fixed in `7.2.0` https://jsfiddle.net/aninde/2pehgr8L/

**Comment by AMBudnik** [comment] 2019-10-15 10:54
Cool! Thanks @aninde 

Aaron, I guess that we can close this issue but if you'd encounter any difficulties with 7.2.0 please let me know.

**Closed by AMBudnik** 2019-10-15 10:54 UTC
Labels: Type: Bug

**Comment by aarondfrancis** [comment] 2019-10-15 14:04
This was a sneaky bug, nice job sorting it all out!
