### ISSUE TITLE
A submenu overlaps the context menu

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3251] opened 2016-02-19 11:01 UTC
A submenu is overlaping the context menu which results in user not being able to hover the context menu items near their left edges when the submenu is opened.

It happens only when the submenu is opened to the left.

Browser: Chrome (latest)
OS: Windows 8.1

![image](https://cloud.githubusercontent.com/assets/8048526/13173812/eaca2ff8-d6ff-11e5-8b2e-425ce199414e.png)

**Comment by AMBudnik** [comment] 2017-01-19 14:34
Still present in 0.30.1

**Comment by AMBudnik** [comment] 2018-04-23 09:02
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by wojciechczerniak** [comment] 2019-02-21 15:04
Duplicate of #4658

**Closed by wojciechczerniak** 2019-02-21 15:04 UTC
Labels: Guess: few hours, Plugin: context menu, Priority: normal, Type: Bug
