### ISSUE TITLE
updateSettings in afterColumnMove error

### ISSUE THREAD

**Issue by NateMoeller** [handsontable/handsontable#4480] opened 2017-08-24 22:46 UTC
### Description

Calling updateSettings with data and columnHeader parameters in afterColumnMove results in no change to the grid. 

### Steps to reproduce

1. Move column 1 to the right of column 2
2. The grid remains the same when column 1 should have moved to the right of column 2

### Demo
This fiddle is hard coded to update settings after moving column 1 to the right of column 2

https://jsfiddle.net/y3dcdjxk/5/

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment] 2017-08-25 08:36
Hi @NateMoeller 

is the Fiddle the one you wanted to share? It doesn't have the `updateSettings` added and we are able to move columns.

**Comment by NateMoeller** [comment] 2017-08-25 17:21
@AMBudnik Sorry! Fiddle link updated

**Comment by AMBudnik** [comment] 2017-08-28 08:18
Thank you @NateMoeller 

I think that the fact that we cannot change `colHeaders` is related to this issue https://github.com/handsontable/handsontable/issues/4136

and when it comes to data the same issue - the `updateSettings`.

What is a good news is that we can use `addHook` and it works https://jsfiddle.net/d2rqf05o/
even when we use the `updateSettings` to set the values deeper in the code. 

There is also one more bug related to this case scenario (reported on Github some time ago) that when we use the handle too close to the edge of a cell the movement doesn't occur but the callback gets called.

![gif](https://user-images.githubusercontent.com/10757813/29765096-13b07388-8bda-11e7-843a-78344bbd7985.gif)

**Comment by NateMoeller** [comment] 2017-08-31 18:53
@AMBudnik it seems moving column on the jsfiddle link you posted works, but not the first time. It looks like the gif is behaving the same way as well

**Comment by AMBudnik** [comment] 2017-09-01 08:38
We should investigate the case. There are several related issues so maybe we will find a way to fix them all.

**Comment by AMBudnik** [comment] 2018-01-22 09:27
Might be related to https://github.com/handsontable/handsontable/issues/4470

**Comment by AMBudnik** [comment] 2018-04-24 09:13
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by NateMoeller** [comment] 2018-05-01 23:33
Is there an update on this? Or a workaround so updateSettings doesn't mess up the previously moved column?

**Comment by AMBudnik** [comment] 2018-05-08 10:02
Hi @NateMoeller 

I do not see any ETA for that but if it is related (caused by ) https://github.com/handsontable/handsontable/issues/4470 (regression bug) we should get our hands on that one in June.

**Comment by AMBudnik** [comment] 2018-08-24 13:31
It still doesn't work for the first attempt in v 5.0.1

**Comment by AMBudnik** [comment] 2019-09-25 12:47
Issue solved in 8.0.0-rc1 (build from 25/09/19)
Updated example https://jsfiddle.net/bp2k7cng/

**Comment by wszymanski** [comment] 2019-09-26 10:41
@AMBudnik Please check for me if the bug was fixed by mu last build.

https://cdn.jsdelivr.net/gh/handsontable/handsontable@a4995f0c804b7fe87d03b9c698bf66f4dfa746dd/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@a4995f0c804b7fe87d03b9c698bf66f4dfa746dd/dist/handsontable.full.css

**Comment by AMBudnik** [comment] 2019-09-26 10:45
I am able to move 1 after 2, but after doing this step I tried to move 1 after 3 and it does not work

Updated demo https://jsfiddle.net/yutkqbvp/

![bug](https://user-images.githubusercontent.com/10757813/65682608-8c2e4880-e05b-11e9-95a5-e4a7453a7799.gif)

Tested on macOS Mojave, Chrome 77 (like the last one).

**Comment by wszymanski** [comment] 2019-09-26 11:47
Ahhh, my fault. Sorry. Now, the duplicated shadow should be fixed.

https://cdn.jsdelivr.net/gh/handsontable/handsontable@293f30429d37fea2add8a9c3df5917b2684ce02a/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@293f30429d37fea2add8a9c3df5917b2684ce02a/dist/handsontable.full.css

However, there will be a problem with this `updateSettings`. After each column move, the `data` **shouldn't be updated**.

Please keep in mind that `updateSettings` with `data` key will load data and reset the sequence of indexes. I would suggest to avoid using the `updateSettings`.

What effect would you like to get, @NateMoeller? Why did you update data?

**Comment by AMBudnik** [comment] 2019-09-26 11:49
@wszymanski 

you're right, with the latest build the double shadow is gone
https://jsfiddle.net/fh4Luzxw/

![shadow](https://user-images.githubusercontent.com/10757813/65686336-707b7000-e064-11e9-9290-f698d557d037.gif)

**Comment by wojciechczerniak** [comment] 2019-10-04 07:29
@aninde our list in #5751 marks this as solved partially, but if I understood correctly this works as intended? Isn't it fixed then?

**Comment by aninde** [comment] 2019-10-04 08:14
@wojciechczerniak, true, now it fixed. I  forgot to update the description in the comment.

**Comment by AMBudnik** [comment] 2019-11-14 14:02
Hi @NateMoeller 

We've just released version 8.0.0-beta1 
As this is only a beta now we do not recommend using it on the production. However, we wanted to share the version for you to test so any comment highly appreciated 👍

**Comment by aninde** [comment] 2020-08-06 11:15
Updated demo with `v8.0.0` https://jsfiddle.net/aninde/2q51d3sj/
<img width="314" alt="Screenshot 2020-08-06 at 13 10 28" src="https://user-images.githubusercontent.com/30186818/89525306-4519f380-d7e6-11ea-8065-dda80ab492a6.png">

as in the previous demos, we can:
* only move the column once,
* the selection on the moved column is shifted by 1px,

IMO this issue needs more testing as there are more bugs here. I am adding it to the list to verify it again.

**Comment by AMBudnik** [comment] 2020-08-26 10:52
I'm removing this issue from the v8.0.0 Release list as it was not solved by v8.0.0

**Closed** 2020-08-27 09:55 UTC
Labels: Moving, Type: Bug
