### ISSUE TITLE
Docs: React-docs: Link to Guides looks constantly active

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#9727] opened 2022-08-02 11:52 UTC
### Description

```
<a href="/docs/next/react-data-grid/" class="nav-link router-link-active">
  Guides
</a>
```
The above link to Guides has an invalid `active` class. Hence it constantly looks active, even when I click on another item. 
It's placed at the main horizontal navigation at the top of the page. 

<img width="1404" alt="Screenshot 2022-08-02 at 13 46 14" src="https://user-images.githubusercontent.com/30186818/182367951-c7864a69-f085-410c-8b6e-b0261bff9437.png">

### Links

http://localhost:8080/docs/next/javascript-data-grid/
http://localhost:8080/docs/next/javascript-data-grid/

### Version
9e633a176b1b2afc5341a382d1c9e986c8103e91

**Comment by jansiegel** [comment] 2022-08-02 12:19
Duplicate of 
- #9715.

**Closed** 2022-08-02 12:30 UTC
Labels: Type: Bug, Docs: Content
