### ISSUE TITLE
Sorting a column display sort icon over the column name

### ISSUE THREAD

**Issue by realtebo** [handsontable/handsontable#2510] opened 2015-05-28 14:01 UTC
As you can see in the picture above, with Firefox 38.0.1 and with IE 11and with lastest Chrome on Windows 7 I've the sort icon placed over and not at a side of the column header:

![cattura](https://cloud.githubusercontent.com/assets/1268699/7861784/6e6bb5be-0552-11e5-83df-589f0951dc84.JPG)

i'm using the version **0.15.0-beta3** actually available at these urls: 
- http://handsontable.com/bower_components/handsontable/dist/handsontable.full.js
- http://handsontable.com/bower_components/handsontable/dist/handsontable.full.css

This bug is 100% repllicable: see this jsFiddle: http://jsfiddle.net/realtebo/ar8msbba/

**Comment by AMBudnik** [comment] 2015-05-29 07:48
It's a duplicate of https://github.com/handsontable/handsontable/issues/2486

**Closed by AMBudnik** 2015-05-29 07:48 UTC
