### ISSUE TITLE
Undo after removing a row doesn't fire afterChange

### ISSUE THREAD

**Issue by mscodemonkey** [handsontable/handsontable#1587] opened 2014-07-10 00:34 UTC
I am using an Ajax dataset, so when I remove a row I also then fire off (using the beforeRemoveRow event) an Ajax call to delete the corresponding record from the database.  However, if I then undo that remove row, it appears back in the table like it should, but doesn't fire any events so I can't send another request to re-add it to the database.

Ideally it would fire an afterChange event for all the cells in the row, so that I can use the autocommit function to then send the entire row back to the database.

**Comment by AMBudnik** [comment] 2015-05-11 08:33
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by asafusan** [comment] 2015-10-07 14:04
A small fix for now in order to add an event on undo. Here's the original code, search for it in handsontable.full.js (for me it was line 15320+-):


    Handsontable.UndoRedo.prototype.undo = function() {
      if (this.isUndoAvailable()) {
        var action = this.doneActions.pop();
        his.ignoreNewActions = true;

Change to this code:

    Handsontable.UndoRedo.prototype.undo = function() {
      if (this.isUndoAvailable()) {
        window.dispatchEvent(undoCustomEvent); // A.D. - fire custom event
        var action = this.doneActions.pop();
        undoCustomEvent.e = action; //A.D. - add data to event
        his.ignoreNewActions = true;

Then you can simply add your eventListener wherever you want:

    window.addEventListener('undoCustomEvent', function(e) {
      // place code to invoke when event is fired
    });

**Comment by karellm** [comment] 2016-08-17 11:47
Any update on that issue? I'm experiencing it too and I would really like to get the undo feature back while using `afterChange`

**Comment by jansiegel** [comment] 2016-08-25 09:00
Hi!

Instead of creating an `afterChange` hook after undoing the `remove_row` action (`remove_row` action itself doesn't fire the `afterChange` hook either), I've added the following hooks:

* `beforeUndo`
* `afterUndo`
* `beforeRedo`
* `afterRedo`

in similar fashion to the one suggested by @tmichel in his pull request in #1922 from 2014. Unfortunately, it didn't make much sense to use the pull request itself, as our code changed quite a bit since 2014.

As for the new hooks - they are fired before or after the "Undo" or "Redo" actions, as their names suggest. Each of them carries a `action` argument. This argument contains information about the action being undone/redone. As the "undoable" actions are different, the `action` argument will have different properties depending on what the user has been doing.

You can differentiate the types of the undone/redone actions by checking the `action.actionType` property, which specifies the type of action in string format. (e.g. `remove_row`).

To show this mechanism better I've created a simple demo: http://jsfiddle.net/js_ziggle/ebezgog5/. 

For example - undoing a `remove_row` action sets the `action` argument to:
![image](https://cloud.githubusercontent.com/assets/7397134/17962809/c692c6a8-6ab2-11e6-985e-31fbaa48af78.png)

where the `data` property is:
![image](https://cloud.githubusercontent.com/assets/7397134/17962826/de36928a-6ab2-11e6-9eea-2473f8de63b6.png)

I hope it makes sense :)

**Comment by karellm** [comment] 2016-08-25 11:35
@jansiegel thanks for the details. Is this in a release version yet? I'd love to play with it.

**Comment by jansiegel** [comment] 2016-08-25 12:10
It should be released with the next version (scheduled for Thursday, September 1st).

**Closed** 2016-09-01 13:54 UTC
Labels: Bug, Core: callbacks, Priority: normal, Released, Tested

**Comment by karellm** [comment] 2016-09-14 14:40
@jansiegel It looks like if a `afterChange` hook is defined, undo simply stops working. Is that intended by design? I can get the `afterUndo` hook to work, but it is simply never called if I have a `afterChange` at the same time.

**Comment by AMBudnik** [comment] 2016-09-15 09:11
Hi @karellm 
Can you share a demo where we'll be able to replicate it?

I've made a simple one (just logging some data) http://jsfiddle.net/4ce6qp3k/ and it seams to work as expected. If I edit any value and use the context menu or a <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> the `afterUndo` hook is fired and after it the `afterChange`

**Comment by lucashtc** [comment] 2018-08-29 14:18
HI @karellm 
Thank you, your example helped me in solving my problem.
