### ISSUE TITLE
Lost readonly property if I ask confirm in beforeRemoveCol or beforeRemoverow

### ISSUE THREAD

**Issue by giorgitus** [handsontable/handsontable#6332] opened 2019-10-10 10:28 UTC
### Description
In beforeRemoveCol or beforeRemoverow if I ask confirm and than say no the row/columns remain but If there was a cell in readonly I lost that property.

http://jsfiddle.net/2b6kL2dg/

### Steps to reproduce
1.set a cell to readonly
2.try to remove the row 
3.not confirm
4.Rightclik on the cell and the readonly is gone

### Demo
http://jsfiddle.net/2b6kL2dg/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: chrome 77.0.3865.90 (Build ufficiale) (a 64 bit)
* Operating System:Macos

**Comment by AMBudnik** [comment] 2019-10-10 12:11
Hey @giorgitus 

we've tried the `7.1.1` demo on Windows 10 and Mac (with Chrome) and the row is not removed if we click `Cancel` in the confirmation window.

Can you record the behavior?

**Comment by giorgitus** [comment] 2019-10-10 12:58
yes if you press cancel the row it's not removed (correct) but cells are not read-only anymore. 
https://youtu.be/HHjbGbh9tMI

**Comment by giorgitus** [comment] 2019-10-10 13:07
you loose alignment property too.

Same problem with beforeRemoveCol
https://youtu.be/bvwhrh2IStk

**Comment by AMBudnik** [comment] 2019-10-10 13:33
Thank you for the video. I replicated it wrong. What I did is set `readOnly: true` in the initialization settings.
If we change the readOnly by the context menu, then yes, it got erased.

**Comment by AMBudnik** [comment] 2019-10-18 12:00
I just wanted to add that it doesn't seem to be related to any version (not a regression) or a browser.

**Comment by wojciechczerniak** [comment] 2019-10-18 12:21
It's related to #6274. Works this way, because `before*Remove` doesn't block cell meta operations. They will just go out of sync. 

@AMBudnik We can link to this issue in #6274 or close it as a duplicate.

https://jsfiddle.net/omx6zf54/

**Comment by AMBudnik** [comment] 2019-10-18 12:32
OK, we'll test this case after doing #6274

**Comment by AMBudnik** [comment] 2019-11-07 07:43
It is also replicable with `7.2.2` http://jsfiddle.net/b6s95gap/

### Case 2
#### Make more cells `readOnly`

1. Select `A3:A7`
2. Make them read-only via context menu
3. Select rows `3:7`
4. Click remove but cancel the operation 
5. Select the `3:7` rows again
6. Click <kbd>DEL</kbd>

![readOnly](https://user-images.githubusercontent.com/10757813/68368300-0d3b2e00-0138-11ea-8781-77fa4e9993b8.gif)

**Result**
Only the value of `A7` is erased while it shouldn't.

### Case 3
#### While sorting

1. Sort column `A`
2. Select `A10` and `A100`
3. Make them read-only via context menu
4. Select rows `2:3`
5. Click remove but cancel the operation 
6. Select the `2:3` rows again
7. Click <kbd>DEL</kbd>

![7 2 2 bad sorting example](https://user-images.githubusercontent.com/10757813/68368640-ca2d8a80-0138-11ea-839b-89bfa9e97352.gif)

**Result**
Both readOnly values are gone, but when we scroll down we can see that other cells were made readOnly.

Case 3 also work the same using 8.0.0-rc1 build from 31/10 http://jsfiddle.net/sq0fce3a/

### Case 4
#### Filtering

1. Filter column `A` to remove `A1`
2. Select `A2:A3`
3. Make them read-only via context menu
4. Select rows `1:2`
5. Click remove but cancel the operation 
6. Select the `1:2` rows again
7. Click <kbd>DEL</kbd>
8. Bring back `A1` while adding it in the `filter by value`

![issue filtering](https://user-images.githubusercontent.com/10757813/68369284-365cbe00-013a-11ea-991b-b2b478c5d71d.gif)
(loaded version 8.0.0-rc1 from 31/10/19)

**Result**
There's no `A3`

### Doubts
Not sure if cases 3 and 4 should stay here or end up as a part of the index mapper issue list.

**Comment by aninde** [comment] 2019-11-07 09:38
Case 2 `8.0.0-rc1` http://jsfiddle.net/aninde/e7fx52Lh/ same improper working like in `7.2.2`.

Case 3 `8.0.0-rc1` http://jsfiddle.net/aninde/tgbmxeyc/ same improper working like in `7.2.2`.

Case 4 `7.2.2` http://jsfiddle.net/aninde/8cuwg46r/ same improper working like in `8.0.0-rc1`.

**Comment by aninde** [comment] 2019-12-15 15:57
This issue will be fixed by[ feature/issue-6233](https://github.com/handsontable/handsontable/pull/6254). Thank you @budnix :)
 We are currently testing the release of version `8.0.0.` We are not able to predict the release date of this version at this stage.

**Demos**
http://jsfiddle.net/aninde/q42x57b6/
http://jsfiddle.net/aninde/k9ra47z5/ filters

**Case 2**
![6332-case2-fixed](https://user-images.githubusercontent.com/30186818/70865267-b0fbd300-1f5b-11ea-9ec3-170467e053f6.gif)

**Case 3**
![6332-case3-fixed](https://user-images.githubusercontent.com/30186818/70865275-d2f55580-1f5b-11ea-8c9e-4d701b5103d8.gif)

**Case 4**
![6332-case4-fixed](https://user-images.githubusercontent.com/30186818/70865277-ddafea80-1f5b-11ea-9f28-d5c28556ae35.gif)

**Comment by AMBudnik** [comment] 2020-06-05 11:50
The main issue and all 3 cases are **solved** in 8.0.0-beta2-rev11 http://jsfiddle.net/AMBudnik/0wfLy784/

**Comment by pnowak** [comment] 2020-07-16 10:54
Hi @giorgitus 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by giorgitus** [comment] 2020-07-16 12:43
Now it works as aspected. Thank you

**Comment by AMBudnik** [comment] 2020-08-31 12:41
v8.0.0 demo to confirm that the issue is solved http://jsfiddle.net/95ao3jmy/ and we can close the ticket.

**Closed by AMBudnik** 2020-08-31 12:41 UTC
Labels: Read-only, Type: Bug
