### ISSUE TITLE
Column Filter Input Loses Focus 

### ISSUE THREAD

**Issue by ajangles** [handsontable/handsontable#6986] opened 2020-06-05 06:09 UTC
### Description

We have 27 columns in out table, and after scrolling to the complete right and selecting a filter, the selected input loses focus and subsequently the inputs are all out of order and the columns are out of alignment

### Steps to reproduce

1. Create table with large amount of columns and add filters
2. Scroll to the right
3. Start typing in a filter input

### Demo

This demo is pretty extreme in number of columns perhaps, but easily represents the problem:

https://jsfiddle.net/n2t8vhzs/

![handsontablefilter](https://user-images.githubusercontent.com/6114691/83842650-c69dc880-a746-11ea-8e3e-0fc110e1b371.gif)

![handsontablefilter](https://user-images.githubusercontent.com/6114691/83842655-c8678c00-a746-11ea-8534-f8dcc0013d71.png)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: All browsers
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2020-06-05 06:43
Thank you for sharing the issue report, Javier.

I can see that you use our `Filter as you type` example from the Filtering tutorial https://handsontable.com/docs/7.4.2/demo-filtering.html

I have replicated the issue in v 7.4.2 as well as our new beta2-rev11 of v 8.0.0. https://jsfiddle.net/AMBudnik/1svhojaz/

Tested on Chrome 80 / macOS Catalina
Related issue https://github.com/handsontable/handsontable/issues/5541 (fixed fo v7.0.0)

**Comment by AMBudnik** [comment] 2020-07-06 12:46
It works the same in 8.0.0-beta2-rev18 https://jsfiddle.net/moewkuL3/

**Comment by AMBudnik** [comment] 2020-08-11 13:15
The issue remains the same in v 8.0.0 https://jsfiddle.net/w5as0juk/

**Comment by wojciechczerniak** [comment] 2020-10-18 12:03
The demo in our documentation is a very simple one. Custom code should be adjusted if you want more columns.

With multiple columns and virtual rendering circumstances change. Inputs here, are reused, events are binded to wrong columns. When I try to filter last column, conditions are attached to column with an index 6, no results are shown. Focus is lost or scroll occurs because rerender reuses the input in totaly different column.

@ajangles @AMBudnik if there is a bug please provide a valid reproduction, otherwise we will have to close this issue.

**Comment by AMBudnik** [comment] 2020-10-20 08:15
We had many requests to fix this "issue" so as this is not a bug, we should move this topic to /docs and consider replacing the example with something else.

**Comment by AMBudnik** [comment] 2020-10-20 08:15
Issue moved to [handsontable/docs #220](https://github.com/handsontable/docs/issues/220) via [**ZenHub**](https://www.zenhub.com/)

**Closed by AMBudnik** 2020-10-20 08:15 UTC
Labels: Filtering, Headers, Type: Demo needed, focus/blur, scroll
