### ISSUE TITLE
Returning false from beforeCreateCol does not abort creation of column

### ISSUE THREAD

**Issue by JamesTreleaven** [handsontable/handsontable#5691] opened 2018-12-22 00:32 UTC
### Description
The hook callback for 'beforeCreateCol' should abort the operation when false is returned to be in line with other such hook functions. Returning false from beforeCreateRow, beforeRemoveCol, beforeRemoveRow all abort the operations - but returning false from beforeCreateCol does not abort the operation.

### Steps to reproduce
1. Return false from beforeCreateColHook hook-callback
2. Try to insert a column ... column will be successfully inserted

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Firefox 64.0
* Operating System: Ubuntu 18.04

**Comment by AMBudnik** [comment] 2018-12-24 09:06
Thank you for sharing the proposition. You're right we cannot return `false` nor `amount = 0` to stop the action.

**Comment by AMBudnik** [comment] 2019-06-12 08:09
Hey @JamesTreleaven 

I'm happy to announce that the issue is fixed in v 7.1.0 (released yesterday)

**Closed by AMBudnik** 2019-06-12 08:09 UTC
Labels: Core: callbacks, Status: Released, Type: Feature

**Comment by JamesTreleaven** [comment] 2019-06-12 16:10
That is terrific. Thank you.

James
