### ISSUE TITLE
Freezing the row causes the hansontable scrollbar to be invalid

### ISSUE THREAD

**Issue by dkenven** [handsontable/handsontable#5281] opened 2018-07-25 01:34 UTC
### Description
When the amount of data is large, click on the scroll bar to freeze more than the number of rows displayed on one page, then hansontable will roll back to the first bar, and the scroll bar will not be able to view the data, all of which are frozen.

* Handsontable version:4.0.0
* Browser Name and version:Goole Chrome65.0.3325.181

**Comment by dkenven** [comment] 2018-07-25 08:03
https://github.com/dkenven/video/blob/master/kk%202018-07-25%2015-29-30.avi

**Comment by AMBudnik** [comment] 2018-07-25 09:46
I'm sorry but I am not able to run this video (even if I open it in a software that supports .avi).
Can you attach a .gif within this topic?

**Comment by AMBudnik** [comment] 2018-07-25 09:48
Also, I need a working demo. You can use this demo as a base to fill it up with your settings http://jsfiddle.net/hk3rfm27/

**Comment by dkenven** [comment] 2018-07-26 01:00
https://v.youku.com/v_show/id_XMzc0NTk3OTc0NA==.html?spm=a2h3j.8428770.3416059.1

**Comment by AMBudnik** [comment] 2018-07-26 06:13
I am sorry but I do not see a bug here. The video is really blurry and I do not know what methods do you use. Can you share a demo? 
You do not need to share the data - only the settings.

**Comment by dkenven** [comment] 2018-07-26 06:20
When the number of rows you freeze exceeds the number of rows displayed on the hansontable page, you will not be able to pull the scroll bar to view the data.

**Comment by AMBudnik** [comment] 2018-07-26 07:08
This is just how it should work - that was intended. 
What would you like it to do?

**Comment by AMBudnik** [comment] 2018-08-20 12:25
I guess that we can close the issue as there are no updates since 26th of July

**Closed by AMBudnik** 2018-08-20 12:25 UTC
Labels: Type: Demo needed
