### ISSUE TITLE
afterRowMove hook returns improper target parameter

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4501] opened 2017-09-06 11:11 UTC
### Description
Copy for #4377. Moving rows from top to bottom still don't work.

Described issue: https://github.com/handsontable/handsontable/issues/4377#issuecomment-327434062

**Comment by aninde** [comment] 2019-09-16 14:41
@wszymanski looks like your new` index mapper` from issue [#5751](https://github.com/handsontable/handsontable/issues/5751) fixed this problem :)

Changes will be released soon.

**Steps to reproduce:**
Moving the first row after last one - target: 3 - (wrong result)
Should be a target: 2.

**Demo**
AMbudnik's version http://jsfiddle.net/rzs1Lcom 
8.0rc version http://jsfiddle.net/aninde/kdre8Lxb/ - fixed, with correct target: 2.

**Environment**
Handsontable version:8.0.0.rc
Browser Name and version: Google Chrome version 76.0.3809.100
Operating System: macOS Mojave 10.14.6

**Comment by wszymanski** [comment] 2019-09-17 06:04
There was introduced a new method `dragRows` which works as `moveRows` earlier. The `moveRows` function has `finalIndex` parameter from now which works as in the description. More about changes in the PR https://github.com/handsontable/handsontable/pull/5945.

**Comment by AMBudnik** [comment] 2020-08-07 08:28
Thank you for fixing guys!

Demo 1 http://jsfiddle.net/vz0763gL/ v 8.0.0 (result in console is `2`)
Demo 2 http://jsfiddle.net/2o8kbp97/ v 8.0.0 (result in console is `2`).
I'm closing this issue as solved in v 8.0.0

**Closed by AMBudnik** 2020-08-07 08:28 UTC
Labels: Core: callbacks, Guess: a day or more, Moving, Type: Bug
