### ISSUE TITLE
how copy data to handsontable many times

### ISSUE THREAD

**Issue by renjieyao** [handsontable/handsontable#10660] opened 2023-12-15 06:28 UTC
![image](https://github.com/handsontable/handsontable/assets/50436535/f2407192-20f1-4405-afff-378cb25fbb86)
when I try to copy data to hansontable again,this error happens,please help me.

**Comment by AMBudnik** [comment] 2023-12-15 07:56
Hi @renjieyao 

Please check this issue https://github.com/handsontable/handsontable/issues/10549 we got a report with the same error message. Is that the same issue that you have?

**Comment by renjieyao** [comment] 2023-12-15 09:13
> Hi @renjieyao
> 
> Please check this issue #10549 we got a report with the same error message. Is that the same issue that you have?

My problem is different from this,when I copy data to handsonTable first time,It will insert rows automatically,but when I clear data and try this again,the error happens.

**Comment by AMBudnik** [comment] 2023-12-15 11:51
Does it always happen? For example please check this demo https://jsfiddle.net/s7fobzv2/
This is a standard setup with the Handsontable v14 (the latest version). If so, please share your OS/Browser settings.

**Comment by renjieyao** [comment] 2023-12-18 02:29
> Does it always happen? For example please check this demo https://jsfiddle.net/s7fobzv2/ This is a standard setup with the Handsontable v14 (the latest version). If so, please share your OS/Browser settings.

I think u're not understand the problem that I said, which be like this:when I add one new row, copy 5 rows, handsontable can add 4 rows automatically, but when I clear data and add one rows, it can't add rows  automatically.I think it doesn't matter with OS/Browser settings.

**Comment by AMBudnik** [comment] 2023-12-18 07:16
@renjieyao Yes, I think that I lack some details about this case to understand it fully.

If you could send a demo where the issue is replicable and list steps on how to get the same error that would help a lot.

**Comment by renjieyao** [comment] 2023-12-18 08:15
> @renjieyao Yes, I think that I lack some details about this case to understand it fully.
> 
> If you could send a demo where the issue is replicable and list steps on how to get the same error that would help a lot.

ok, can u give me your email address, I will send demo to u later.

**Comment by AMBudnik** [comment] 2023-12-18 08:26
Sure, please send it at support@handsontable.com

**Comment by renjieyao** [comment] 2023-12-20 02:20
> Sure, please send it at [support@handsontable.com](mailto:support@handsontable.com)

<img width="660" alt="image" src="https://github.com/handsontable/handsontable/assets/50436535/89f209db-a759-4fc6-898b-ce5f17243fa7">
I can't recurrent this case in the demo,I think it may be matter with colorChange function, how can I reset cellProperties.renderer.

**Comment by renjieyao** [comment] 2023-12-20 07:40
> support@handsontable.com

Sorry,I can't recurrent this case in the demo, but I have send it the email, you can check the email.

**Comment by AMBudnik** [comment] 2023-12-20 07:42
Thank you. We got the email. I or my colleague from the team will update you later today after debugging the demo.

As we get the email we can close this thread here on GitHub.

**Closed by AMBudnik** 2023-12-20 07:42 UTC
Labels: Status: Answered
