### ISSUE TITLE
New docs: 404 response for links 

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8306] opened 2021-06-25 10:07 UTC
### locations

1. Page: https://dev.handsontable.com/docs/api/
Anchors: 
`Hello world` leads to the https://dev.handsontable.com/docs/9.0/hello-world/
 `Hooks` leads to the https://dev.handsontable.com/docs/9.0/api/hooks/
 `Options` leads to the https://dev.handsontable.com/docs/9.0/api/options/

2. Page: https://dev.handsontable.com/docs/building/#overview
Anchor: `our code style` leads to the https://github.com/handsontable/handsontable/blob/master/.eslintrc

ps. those issues haven't been reported in the old /docs repo.

**Comment by aninde** [comment] 2021-06-28 14:15
I was able to found another 12 broken links thanks to the broken link checker.

**Comment by aninde** [comment] 2021-06-29 08:59
> ### locations
> 1. Page: https://dev.handsontable.com/docs/api/
>    Anchors:
>    `Hello world` leads to the https://dev.handsontable.com/docs/9.0/hello-world/
>    `Hooks` leads to the https://dev.handsontable.com/docs/9.0/api/hooks/
>    `Options` leads to the https://dev.handsontable.com/docs/9.0/api/options/


1. Will be solved with https://github.com/handsontable/handsontable/issues/8328.

> 2. Page: https://dev.handsontable.com/docs/building/#overview
>    Anchor: `our code style` leads to the https://github.com/handsontable/handsontable/blob/master/.eslintrc
> 
> ps. those issues haven't been reported in the old /docs repo.

2. Done by https://github.com/handsontable/handsontable/pull/8327.

**Comment by aninde** [comment] 2021-06-29 08:59
Closing as duplicate of https://github.com/handsontable/handsontable/issues/8328.

**Closed by aninde** 2021-06-29 08:59 UTC
Labels: Type: Bug, Type: Documentation
