### ISSUE TITLE
[8.0.0+] We cannot use some of the cultures in the numeric cell type

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7419] opened 2020-12-01 11:49 UTC
### Description

We cannot use some of the cultures in the numeric cell type. 
When we load those cultures table does not display and we get a console error.

![Zrzut ekranu 2020-12-1 o 12 47 27](https://user-images.githubusercontent.com/10757813/100736660-62954d80-33d3-11eb-830b-cbced750e011.png)

It works for some of the languages as en-US, de-DE, jp-JP. But does not work for en-GB, nl-NL or pl-PL.

### Demo

* 8.0.0 - broken - https://jsfiddle.net/AMBudnik/1nfz5q9k/
* 7.4.2 - working well - https://jsfiddle.net/AMBudnik/0o4sqz2j/

### Your environment
* Handsontable version: 8.0.0+
* Browser Name and version: Chrome 87
* Operating System: macOS Catalina 10.15.7

inform [forum](https://forum.handsontable.com/t/gh-7419-using-gbp-currency/4844)

**Comment by AMBudnik** [comment] 2020-12-01 12:13
We got it working in v8.0.0-beta2-rev22 (last one) https://jsfiddle.net/aninde/2guqt1nc/ 
We also got it working when we load an un-minified language file https://jsfiddle.net/AMBudnik/1f2kjown/

**Comment by budnix** [comment] 2021-02-15 14:38
The issue is not related to the Handsontable. There is a `numbro` version mismatch between docs and the lib. The Handsontable has frozen the `numbro` version to `2.1.2` and docs uses the SemVer range prefix. After freezing the docs [`numbro` dependency](https://github.com/handsontable/docs/commit/527b26afb1e815598cff59dda7fe705a0e58af2b) the demo works https://jsfiddle.net/tmby6fkj/.

**Comment by AMBudnik** [comment] 2021-02-16 08:11
Thank you @budnix I've updated the Client who reported this issue.

**Comment by wojciechczerniak** [comment] 2021-03-03 16:57
@AMBudnik not a regression then and we should close it with a wontfix label?

**Comment by AMBudnik** [comment] 2021-03-04 07:08
True @wojciechczerniak 

I do not think that we can do anything more with that issue than just set up the version as @budnix proposed (I can't see this in the old docs https://github.com/handsontable/docs/blob/draft-next/package.json#L38 but maybe it's already in the new).

Definitely, I'm taking the 'regression' label off.

**Comment by wojciechczerniak** [comment] 2021-03-05 14:51
@AMBudnik @Osky772 Change was pushed by @budnix to the 8.3.1 branch only. We should push it to the `next` branch as well to have it solved for future docs versions.

**Comment by Osky772** [comment] 2021-03-05 15:33
> @AMBudnik @Osky772 Change was pushed by @budnix to the 8.3.1 branch only. We should push it to the `next` branch as well to have it solved for future docs versions.
> 
> Then we can close this issue

The version of `numbro` is now fixed to `2.1.2` for the `draft-next` branch https://github.com/handsontable/docs/commit/e0b00cea858ca7e9eab4bdcbf48ac75cb0b86be2

**Comment by AMBudnik** [comment] 2021-03-08 07:55
Cool. Let's mark the issue for QA and close after the official release.

**Comment by wojciechczerniak** [comment] 2021-03-23 08:03
@AMBudnik @aninde can we close it now?

**Comment by AMBudnik** [comment] 2021-03-23 08:46
IMO we can close it. As @Osky772 pointed it's already updated https://github.com/handsontable/docs/blob/draft-next/package.json#L38 
Waiting for your feedback @aninde

**Comment by aninde** [comment] 2021-03-23 13:19
Looks like that change introduced by  https://github.com/handsontable/docs/blob/draft-next/package.json#L38 is already on v8.3.2 https://github.com/handsontable/handsontable/blob/fa685dc8c194c0269b893d202580ce7091ed8322/package.json#L91

On demo, it looks fixed https://jsfiddle.net/8Lzr361w/2/ so I'm closing it as done.

**Closed by aninde** 2021-03-23 13:19 UTC
Labels: Cell type: numeric, Type: Documentation needed
