### ISSUE TITLE
The MergeCells creates many hidden <TD> elements and slows down Handsontable

### ISSUE THREAD

**Issue by bellcliff** [handsontable/handsontable#4421] opened 2017-07-20 01:19 UTC
### Description
When there is a table which has row cross the whole table, partial render do not work anymore.

### Steps to reproduce

1. open the demo
2. the merge cell cause the big table really slow down
3.

### Demo
http://jsfiddle.net/bellcliff/hrc5g0Ly/

### Your environment
* Handsontable version: 0.32
* Browser Name and version: chrome 59
* Operating System: win 7

**Comment by AMBudnik** [comment] 2017-07-20 08:43
Thank you for sharing 

I have tested it on Chrome 59 on Windows 10 and I have to say that the vertical scrolling experience is pretty bad. I've tested the newest (0.33.0) version as well and there's no difference in the results.

![scrolling](https://user-images.githubusercontent.com/10757813/28408525-136bf66a-6d38-11e7-8974-36c005f9219e.gif)


ps. adding `renderAllRows` doesn't seem to help. It just blocks the table of being loaded for little longer.

**Comment by bellcliff** [comment] 2017-07-24 12:35
Hi @AMBudnik , do we have a ETA for this one? Do you have any suggestions or walk around?

BTW, one quick question, do we have a method call row renderer or block renderer (for batch cell render)?
We are heavily using the [renderer](https://docs.handsontable.com/0.15.0-beta5/Options.html#renderer) method for customized style on cell, when do performance investigate, we found this method called quite a lot times when table render.

**Comment by AMBudnik** [comment] 2017-07-24 12:54
We are currently rewriting `mergeCells` plugin https://trello.com/c/SPxx77h0/85-in-progress-re-write-of-merge-cells
I have asked our developer to take a look at the issue but without an investigation, there's not much I can say.

ps. currently, when you edit a single cell the renderer is called for each cell in the grid. We are planning to change it but the following case will take around 2 months with tests. Here's a Trello Roadmap card for the feature https://trello.com/c/m9KTygSV/80-refactor-re-write-of-renderers

**Comment by bellcliff** [comment] 2017-08-01 13:14
Hi @AMBudnik , do you have any updates for merge cells investigation? 

> I have asked our developer to take a look at the issue but without an investigation, there's not much I can say.

**Comment by AMBudnik** [comment] 2017-08-07 11:32
Thank you for the reminder. I am sure that it will be investigated while completing this refactor https://github.com/handsontable/handsontable/milestone/84
It will be a big change and the whole plugin will be changed

**Comment by AMBudnik** [comment] 2018-01-17 12:15
The issue is still present. Updated demo http://jsfiddle.net/gzzrr34h/

I guess that the issue occurs as we are checking the metadata many times while we scroll. The demo contains fixed areas but commenting them does not change a lot.

It is definitely something to change. However, I do not see a solid workaround for this issue. We can make rows higher and add offset methods to shorten the line of cells that are waiting to be rendered. But it does not solve the issue.

**Comment by swistach** [comment] 2019-02-05 13:44
Simple demo: https://jsfiddle.net/g5Lpf0qj/

`MergeCells` plugin breaks virtual rendering and adds many persistent `<td>` elements with an inline style `display: none`.

**Comment by shivam100** [comment] 2020-01-20 05:50
What is the status of the issue. Can we have an ETA on this

**Comment by AMBudnik** [comment] 2020-01-20 09:01
@shivam100 the task hasn't been given a milestone yet

**Comment by underfisk** [comment] 2020-05-20 13:15
@AMBudnik I noticed you said you've tested and there is no difference, well with React you'll notice a huge impact in performance. HoT default behaviour is not well optimized to be used with immutable data and triggers a re-render on every row if you have a big merged cell and let's say 100 rows your table will basically freeze for some seconds while the redux update is being dispatched. It is not really user friendly when you want to display a table and it constantly freezes after you type and save.
If you could use React DevTools or internal logging to debug this it will help

**Comment by AMBudnik** [comment] 2020-05-20 13:30
If we decide that that's the time to develop a solution to solve the performance issue of mergedCells that cover larger areas of the viewport we will test not only the vanilla version, but also React, Angular, and Vue wrappers. 

I think that @bellcliff demo is sufficient, but feel free to add any other examples that you find appropriate to test. Just try not to enable too many other functionalities as it may cause the observation to be unreliable.

**Comment by underfisk** [comment] 2020-05-20 14:13
@AMBudnik Even with @bellcliff example, you see that each element that is sent to the DOM with display none is heavy and not efficient. What if we have 1k rows inside a big merged cell, we would end up with ~1k empty <td> and that's not good at all.
What i think might be necessary is shard the data in case it is bigger than the viewport but doing outside sharding and loading into the plugin is very slow, I've tried that but by doing that you can split 1k rows of a big merged cell into what the user can see and only render that proportion.
Also, i tested with only the basic features, in my project we have almost all features disabled, just using the core of HoT the problem will persist, it's a UX problem overall that many people probably is facing and when we decided to use handsontable we thought that the virtualization would work for rowspaning/merged cells
@AMBudnik Will, there be any news regarding this matter any time soon?

**Comment by AMBudnik** [comment] 2020-05-21 06:06
@underfisk the task hasn't been added a milestone - it means that it is not scheduled for this or probably next month. We need to publish stable 8, and maybe 9 before investigating this subject. As you mentioned the problem may lay deep down the core, so every change has to be reconsidered twice.

**Comment by underfisk** [comment] 2020-05-21 08:34
@AMBudnik Yes I understand that

**Comment by AMBudnik** [comment] 2020-09-02 09:41
This issue remains the same in v 8.0.0 http://jsfiddle.net/AMBudnik/m3246tj7/

**Comment by underfisk** [comment] 2020-09-02 15:55
@AMBudnik Also when one merge cell is giant, Handsontable instead of chunk renders all the rows which is not supposed to happen even though the merge is higher than the screen, you should adapt on the scroll/screen change events and not render everything

**Comment by AMBudnik** [comment] 2021-02-04 13:36
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Closed by AMBudnik** 2021-02-04 13:36 UTC
Labels: Core: performance, Merge cells, Part of scope, Type: Bug
