### ISSUE TITLE
If I update to v14.1. 0 with npm i @ Handsontable/vue, there will be over a thousand such errors. 

### ISSUE THREAD

**Issue by yanyinqing** [handsontable/handsontable#10739] opened 2024-01-18 08:48 UTC
### Describe the bug

If I update to v14.1. 0 with npm i @ Handsontable/vue, there will be over a thousand such errors. When I roll back to v14.0, I will not encounter this problem. Similarly, I also update Handsontable to v14.1. 0 with npm i Handsontable, and updating Handsontable alone will not cause any problems

### Video/Screenshots

<img width="1269" alt="image" src="https://github.com/handsontable/handsontable/assets/76729473/86148258-177a-4b51-af85-41194caafbeb">

### Handsontable version

14.1.0

### Framework version

vue2

### Your environment

edge,macos

**Comment by adrianszymanski89** [comment] 2024-01-18 11:17
Hi @yanyinqing 

Thank you for contacting us. I checked it in a local project with Vue 2.x and couldn't reproduce the problem. Can you please share your project where the issue is replicable?

**Comment by Dissident26** [comment] 2024-02-22 09:39
Had same issue upon upgrading to v14.1, seems that type have changed, all former stuff is available in `HotTableClass` now
`import HotTableClass from '@handsontable/react/hotTableClass';`

**Comment by adrianszymanski89** [comment] 2024-02-22 14:03
Hi @Dissident26 

Thank you for your input. I need to consult your approach, and I'll update you then.

**Comment by adrianszymanski89** [comment] 2024-03-19 09:37
Hi @Dissident26  @yanyinqing 

This bug is now fixed in v. 14.2.0. Can you please confirm if the issue is gone on your side?

**Comment by yanyinqing** [comment] 2024-03-19 09:40
> Hi @Dissident26 @yanyinqing
> 
> This bug is now fixed in v. 14.2.0. Can you please confirm if the issue is gone on your side?

Yes, I haven't had this problem again, but the issue with # 10824 is preventing me from using versions above 14.0.0. Can I speed up the fix

**Comment by adrianszymanski89** [comment] 2024-03-19 10:12
Hi @yanyinqing 

Thank you for the confirmation. As for #10824, it's not on our roadmap yet. I will update you once it's fixed.

**Comment by AMBudnik** [comment] 2024-06-06 09:48
Hi @yanyinqing we fixed the #10824 in the latest version - 14.3.0.

Please check if you can now update to the newest version and confirm that this issue is fixed.

**Comment by AMBudnik** [comment] 2024-06-06 09:52
Great! Thank you for the confirmation, @yanyinqing

**Closed** 2024-07-01 11:47 UTC
Labels: Status: Answered
