### ISSUE TITLE
Move `@angular/core` dependency to peer dependencies

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9574] opened 2022-06-13 12:18 UTC
### Description

The issue is about moving the `@angular/core` Angular wrapper dependency to peer dependencies (or dev dependencies). Then, add new tests as new examples for the Angular 9 to 14.

**Comment by AMBudnik** [comment] 2022-06-28 11:50
Issue closed as [solved](https://github.com/handsontable/handsontable/blob/develop/wrappers/angular/package.json#L58) in [Handsontable v12.1.0](https://handsontable.com/docs/release-notes/).

**Closed by AMBudnik** 2022-06-28 11:50 UTC
Labels: angular

**Comment by warpech** [comment] 2022-07-01 20:08
There is a regression caused by this change, which we are tracking in #9622
