### ISSUE TITLE
HandsontableCellType is not registered in some cases

### ISSUE THREAD

**Issue by akoskm** [handsontable/handsontable#9140] opened 2022-01-23 15:44 UTC
I'm trying to upgrade from v10 to v11.

Thank you for the effort in trying to reduce the bundle size 🎉 

I see you already updated some examples and I've come to the conclusion that in order to use `Autocomplete` and `Handsontable` cell types, I have to do something like:

```
import {
  registerCellType,
  AutocompleteCellType,
  HandsontableCellType
} from "handsontable/cellTypes";

registerCellType(AutocompleteCellType);
registerCellType(HandsontableCellType);
```

I updated one of my earlier examples from https://github.com/handsontable/handsontable/issues/8611 and this loads fine: https://codesandbox.io/s/elastic-agnesi-1ce5n?file=/src/Table.jsx

However, when I add the same imports to the entry point in my application it doesn't work and I'm getting this error:

```
Error
You declared cell type "handsontable" as a string that is not mapped to a known object.
Cell type must be an object or a string mapped to an object registered by
"Handsontable.cellTypes.registerCellType" method

Call Stack
 _getItem
  renderer.dev.js:286474:11
 expandMetaType
  renderer.dev.js:298499:114
 CellMeta.updateMeta
  renderer.dev.js:293183:133
 MetaManager.updateCellMeta
  renderer.dev.js:292514:21
 DynamicCellMetaMod.extendCellMeta
  renderer.dev.js:298446:26
 MetaManager.
  renderer.dev.js:298390:20
 fastCall
  renderer.dev.js:304518:17
 MetaManager.runLocalHooks
  renderer.dev.js:306524:72
 MetaManager.getCellMeta
  renderer.dev.js:292468:12
 Core.getCellMeta
  renderer.dev.js:289855:24
× Close

```

I did some debugging and left a breakpoint in the `_getItem` function, where the error is thrown:
```
function _getItem(name) {
  if (!hasItem(name)) {
    throw Error("You declared cell type \"".concat(name, "\" as a string that is not mapped to a known object.\n                 Cell type must be an object or a string mapped to an object registered by\n                 \"Handsontable.cellTypes.registerCellType\" method"));
  }

  return getItem(name);
}
```
This function is in the file

```
webpack://electron-boilerplate/./node_modules/handsontable/cellTypes/registry.mjs
```

I also put breakpoints to the code where I'm registering the two cell types:
```
registerCellType(AutocompleteCellType);
registerCellType(HandsontableCellType);
```

What I found is that when my code registers the cell types, the `registerCellType` ends up calling the `_register` function in 

```
webpack://electron-boilerplate/./node_modules/handsontable/cellTypes/registry.js
```

not in

```
webpack://electron-boilerplate/./node_modules/handsontable/cellTypes/registry.mjs
```

Because `registry.js` and `registry.mjs` are two different files, the `subCollection` in `registry.js` for the `cellType` namespace:

https://github.com/handsontable/handsontable/blob/22121087cb57d99f08e3105d20a0fb4de953877a/handsontable/src/utils/staticRegister.js#L11

won't have the same items a `subCollection` in `registry.mjs`.

I feel the problem is caused because I'm having both of these files because `registry.js` uses `require("../utils/staticRegister")` while `registry.mjs` imports explicitly the msj files `"../utils/staticRegister.mjs";`.

**Comment by mjastrzebowski** [comment] 2022-01-28 11:41
Hey @akoskm, I'm investigating the topic, but I still need some more time. I will get back to you as soon as I will have some update info.

**Comment by akoskm** [comment] 2022-01-28 13:19
Thanks @mjastrzebowski 🙌

**Comment by mjastrzebowski** [comment] 2022-02-02 12:54
Hi @akoskm, thanks for your patience, it looks like there's some problem with bundler itself that it's providing these 2 instances of HOT module (CommonJS and ES). To investigate it more we would need to have more details about the project - which bundler are you using and version, some config to reproduce (like your entry points) - the more you can share the easier will be to help you with the issue.

**Comment by danyx23** [comment] 2022-02-03 16:54
We just ran into this issue as well. We recently upgraded from Webpack 4 to Webpack 5 and as part of that switched to using modules. A full project that runs into this problem is here: https://github.com/owid/owid-grapher/tree/669371adc8aba60c3ece1bbdc3ca234ce3077930 .

**Comment by akoskm** [comment] 2022-02-03 17:34
@mjastrzebowski sorry, had no time to work on this during the week - this is my n-th side hustle 😅 - but essentially it was a webpack 4 to 5 upgrade, same as for @danyx23. Can get back to you with more details during the weekend.

**Comment by mjastrzebowski** [comment] 2022-02-15 21:46
Hey, thanks for the comment and example @MarcelGerber, as for now we can see that it's a bigger problem related to webpack 5 and react mainly (no matter of handsontable version). It's also not specific for any method, but as described in previous comments it's because of having 2 different instances of handsontable. We're still looking for a general solution and will update you with the progress.

**Comment by aninde** [comment] 2022-03-10 08:16
Work well with v12.0.0. Tested locally.

**Comment by AMBudnik** [comment] 2022-04-29 07:21
Hi @akoskm 

I'm more than happy to announce that v12 is live. The fix for this case was tested. But if you would have any further issues please let me know.

Here https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls you can read more about the changes in v12. And here https://handsontable.com/docs/migration-from-11.1-to-12.0/#step-1-verify-your-updatesettings-calls is the migration guide for this version.

**Closed by AMBudnik** 2022-04-29 07:21 UTC
Labels: Type: Bug, react
