### ISSUE TITLE
columns headers appear duplicated after editing a row

### ISSUE THREAD

**Issue by rjansen72** [handsontable/handsontable#2019] opened 2015-01-02 00:12 UTC
I'm having an issue with my handsontable that contains enough rows to cause the page to scroll. If the user scrolls down to the bottom of the table and tries to edit a cell, the edit control has a really small height and the column headers show up twice. I've attached a screenshot so you can see. I'll start diving into the code to see what is going on but am wondering if anyone else has seen this or know what I might look for?
![screen shot 2015-01-01 at 7 09 43 pm](https://cloud.githubusercontent.com/assets/3710730/5593624/028d1508-91ea-11e4-908d-2f6a47c6825f.png)
thanks!

**Comment by rjansen72** [comment] 2015-01-02 00:18
Including a screen shot of the tiny editor control that happens in this same scenario.
![screen shot 2015-01-01 at 7 17 14 pm](https://cloud.githubusercontent.com/assets/3710730/5593636/ed3198b8-91ea-11e4-9ec1-0054c3ba023e.png)

**Comment by kevin-j-morse** [comment] 2015-01-12 08:13
This may be a duplicate of #2006 although the developers would have to confirm that.

I am also experiencing exactly what your screen shots show.

**Comment by AMBudnik** [comment] 2015-03-13 13:44
Fixed with #2006 issue.

**Closed by AMBudnik** 2015-03-13 13:44 UTC
