### ISSUE TITLE
Docs: suspendRender and suspendExecution methods have the same description

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9807] opened 2022-08-22 12:17 UTC
### Description

In this section: https://handsontable.com/docs/batch-operations/#suspend-and-resume-methods both `suspendRender` and `suspendExecution` methods have the same description which is misleading.

The description from this PR https://github.com/handsontable/handsontable/pull/7406 might be a good base for fixing it.

**Comment by AMBudnik** [comment] 2022-10-29 10:56
Duplicate of https://github.com/handsontable/handsontable/issues/9136

**Closed by AMBudnik** 2022-10-29 10:56 UTC
Labels: Docs: Content
