### ISSUE TITLE
Bug with scrollbar and dimension calculation in Firefox

### ISSUE THREAD

**Issue by dscheinah** [handsontable/handsontable#6186] opened 2019-08-07 07:51 UTC
### Description
When toggling column visibility with fixed columns and stretchH the scroll calculation does not seem to work reliably in Firefox. The left overlay gets it's height calculated as if a scrollbar is visible, but it is not. 

This does not happen in Chrome as there is an unnecessary scrollbar rendered.

### Steps to reproduce
Setup a table with example data, fixedColumnsLeft, stretchH 'all' and a width and height to fit all example data. On toggling the options for hiddenColumns with updateSettings the bug should appear (see Demo).

### Demo
https://jsfiddle.net/3j94dzb5/8/
When clicking the "Toggle Columns" checkbox the bug appears. When run outside of the fiddle it also happens for the width of the top overlay.

### Your environment
* Handsontable version: 7.*.*
* Browser Name and version: Firefox 68.0.1
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2019-08-13 11:03
I get something like this on FF

![image](https://user-images.githubusercontent.com/10757813/62936651-a8876600-bdca-11e9-92b0-17543b1fcb98.png)

while on Chrome it looks fine.

Do you get the same result?

**Comment by dscheinah** [comment] 2019-08-13 16:02
Yeah, that's what I meant. This can also happen on the upper right corner. But I was not able to reproduce it in a fiddle.

> while on Chrome it looks fine.
Despite the fact that it adds a scrollbar that only scrolls for about 2px :)

**Comment by AMBudnik** [comment] 2019-08-14 09:41
Thank you for confirming. I've marked it as a bug.

**Comment by AMBudnik** [comment] 2020-04-16 08:58
Still replicable in Handsontable v7.4.2 FF / v75 https://jsfiddle.net/AMBudnik/k9bp6uvr/

![Zrzut ekranu 2020-04-16 o 10 58 00](https://user-images.githubusercontent.com/10757813/79436435-27274980-7fd1-11ea-807b-7df22718ef9c.png)

**Comment by AMBudnik** [comment] 2020-07-07 09:40
The issue is no longer replicable https://jsfiddle.net/gsh4vprd/  in 8.0.0-beta2-rev19
It was still replicable in 8.0.0-beta1 https://jsfiddle.net/gsh4vprd/1/

**Comment by pnowak** [comment] 2020-07-16 10:41
Hi @dscheinah 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by dscheinah** [comment] 2020-07-22 17:30
Thanks for the update. I am going to migrate to v8 when my current project is done.

**Comment by AMBudnik** [comment] 2020-08-06 07:55
Hi @dscheinah we just released the stable v8.0.0 so we can close this topic. Please share your feedback when you'll ready.

**Closed by AMBudnik** 2020-08-06 07:55 UTC
Labels: Firefox, Type: Bug
