### ISSUE TITLE
'close' of CustomEditor is fired twice after editing

### ISSUE THREAD

**Issue by luozhen513** [handsontable/handsontable#9922] opened 2022-09-19 03:46 UTC
### Description

'close' of CustomEditor is fired twice after editing.
why not once?

### Steps to reproduce

1.dblClick one cell
2.press 'Enter'
3.

### Demo

https://jsfiddle.net/tmnx90e4/1/

### Your environment
* Handsontable version:
* Browser name and version:
* Operating system:

**Comment by adrianszymanski89** [comment] 2022-09-19 08:18
Hi @luozhen513 

Thank you for reporting this issue. I can confirm that this method is fired twice. I also recreated this issue in a vanilla example:

https://jsfiddle.net/aszymanski/tfbmp938/

**Comment by adrianszymanski89** [comment] 2022-09-22 12:29
Hi @luozhen513 

I have an update regarding this issue. I had to consult my colleague on the subject.

Apparently, considering the architecture of the editor, a second check is needed.

The first time it is triggered by queueValidator w core.js when it tries to save the data.
The second time is triggered by the selection being applied.

As it's not considered a bug but an architectural choice by design, I will close this issue.

**Closed by adrianszymanski89** 2022-09-22 12:29 UTC
Labels: Editor
