### ISSUE TITLE
with hidden column , collapsibleColumns don't work well

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#6641] opened 2020-01-15 11:31 UTC
### Description
A hidden column appears after collapse/ expand header column

### Steps to reproduce

1.I collapse the column "I"
2.if i expand the column "I" , the Hidden column O appears

### Demo

https://jsfiddle.net/jeanmarc/3odc4w91/11/

### Your environment
* Handsontable version:PRO 7.3.0
* Browser Name and version:Chrome 79
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2020-01-15 11:35
This issue should be fixed after adding the hiddenColumns to the index mapper.
@aninde what do you think?

**Comment by aninde** [comment] 2020-01-16 15:39
@AMBudnik thanks for your vigilance. I will add it to the list of issues tested during testing of new hidden columns and check it out when PR's will be ready.

**Comment by wojciechczerniak** [comment] 2020-07-01 22:06
Duplicate of #6879

**Closed by wojciechczerniak** 2020-07-01 22:06 UTC
Labels: Collapsing, Hiding, Type: Duplicate
