### ISSUE TITLE
[10.0.0] Double warning in logs when HyperFormula is enabled

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8771] opened 2021-09-29 07:06 UTC
### Description

Handsontable v10 enabled with HyperFormula logs double information `"binarySearchThreshold option is deprecated since 1.1"` in the console logs. The one warning is enough.

A single [HyperFormula](https://codesandbox.io/s/github/handsontable/hyperformula-demos/tree/1.1.x/vanillajs-demo?from-embed=&file=/src/hyperformulaConfig.js) does not generate this information.

### Demo

https://jsfiddle.net/o08mp51d/ v10 double warning
https://jsfiddle.net/Lfc6r1pd/ v9.0.2 no warning

### Your environment
* Handsontable version: v10
* Browser Name and version: any
* Operating System: any

**Comment by jansiegel** [comment] 2021-09-29 07:43
@aninde 
> The one warning is enough.

I'd say one warning is one too many, as we don't declare this option anywhere in the HF settings for the Formula plugin.

> A single [HyperFormula](https://codesandbox.io/s/github/handsontable/hyperformula-demos/tree/1.1.x/vanillajs-demo?from-embed=&file=/src/hyperformulaConfig.js) does not generate this information.

It does, when you use the `rebuildAndRecalculate` method, as we do in Handsontable: https://jsfiddle.net/js_ziggle/qp6txbv2/2/. 

I reported this problem on the HF issue board: https://github.com/handsontable/hyperformula/issues/828.

**Comment by budnix** [comment] 2022-01-04 13:51
The issue is fixed within https://github.com/handsontable/hyperformula/pull/882.

**Comment by AMBudnik** [comment] 2022-01-20 08:55
The `full.js` version of Handsontable v11.1.0 does not contain the HyperFormula 1.3.1. that solves the issue (linked by @budnix above). However, as I was updated it works well for Clients who use the package management approach. That is why I'm closing this issue as solved and I will update the Clients on the forum with the appropriate description.

**Closed by AMBudnik** 2022-01-20 08:55 UTC
Labels: Type: Bug, Regression, hyperformula

**Comment by warpech** [comment] 2022-01-20 10:40
To clarify, the `full.js` package of Handsontable 11.1.0 contains HyperFormula 1.3.0. 

In the next release (Handsontable 12.0.0), that will be updated to HyperFormula 1.3.1.

Marking this issue as Release 12.0.0 not to miss it in the Release Notes.
